-- ============================================================
-- SEED EXT 5: Módulo 14 — Passive Voice (ex 261-300) — FINAL
-- Tópicos: consolidação passivo em TOEFL, registro avançado
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'passive-voice';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo passive-voice não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 51: passivo em revisão de literatura
  (cid,51,261,'gap_fill','Numerous studies _____ (conduct/passive) over the past two decades have investigated the long-term effects of early childhood nutrition.','conducted',NULL,'Reduced passive relative: ''studies conducted'' = ''studies that were conducted.''','medium'),
  (cid,51,262,'multiple_choice','In a literature review, ''has been studied'' (present perfect passive) is preferred over ''was studied'' (past simple passive) when:','The research is recent and its relevance to the present is being emphasized.','[''The agent is unknown'',''The research is recent and its relevance to the present is being emphasized.'',''Only past simple passive is correct in literature reviews'',''The subject is plural'']','PP passive = links past research to present state of knowledge.','medium'),
  (cid,51,263,'gap_fill','The relationship between income inequality and health outcomes _____ (examine/passive) in more than 200 studies since 1990.','has been examined',NULL,'PP passive for cumulative body of research up to the present.','easy'),
  (cid,51,264,'gap_fill','Although the mechanism _____ (not/fully/understand/passive), the correlation _____ (replicate/passive) consistently across independent studies.','is not yet fully understood / has been replicated',NULL,'Stative passive (understanding) + PP passive (replication).','hard'),
  (cid,51,265,'multiple_choice','Which sentence uses ''have been'' vs ''were'' CORRECTLY in a literature review?','Several remediation programs have been implemented in recent years, though few have been rigorously evaluated.','[''Several remediation programs were implemented and were evaluated in recent years.'',''Several remediation programs have been implemented in recent years, though few have been rigorously evaluated.'',''Several remediation programs are implemented in recent years, though few are rigorously evaluated.'',''Several remediation programs had been implemented, though few are rigorously evaluated.'']','PP passive for recent, ongoing developments + relevance to present.','hard'),

  -- BLOCK 52: passivo em conclusões e discussões
  (cid,52,266,'gap_fill','In conclusion, it _____ (demonstrate/passive) that access to early childhood education significantly improves long-term economic outcomes.','has been demonstrated / is demonstrated',NULL,'Passive in academic conclusions: impersonal passive summarizing the paper''s contribution.','medium'),
  (cid,52,267,'multiple_choice','Which is the most appropriate conclusion sentence using passive?','The present study has demonstrated that early intervention programs can be cost-effective and should be scaled.','[''We demonstrated that early intervention is cost-effective.'',''In this study, we have shown that early intervention can be cost-effective.'',''The present study has demonstrated that early intervention programs can be cost-effective and should be scaled.'',''This study demonstrates that early intervention programs were cost-effective.'']','Academic conclusion: present perfect passive emphasizes what has been established.','medium'),
  (cid,52,268,'gap_fill','Several limitations _____ (acknowledge/passive/must) before the conclusions can be accepted as definitive.','must be acknowledged',NULL,'''Must be acknowledged'' = modal passive for mandatory recognition of limitations.','medium'),
  (cid,52,269,'gap_fill','The findings reported here _____ (should/replicate/passive) in larger and more diverse samples before they _____ (can/generalize/passive) to the wider population.','should be replicated / can be generalized',NULL,'Modal passives in discussion: recommendation + condition for generalization.','hard'),
  (cid,52,270,'multiple_choice','Which passive construction is MOST appropriate for discussing future research in an academic conclusion?','Further research should be directed toward understanding the mechanisms underlying the observed effect.','[''Further research must directed toward understanding the mechanisms.'',''Further research will be directed to understand the mechanisms.'',''Further research should be directed toward understanding the mechanisms underlying the observed effect.'',''Further research is being directed toward the mechanisms.'']','''Should be directed toward'' = modal passive recommendation for future research direction.','medium'),

  -- BLOCK 53: passivo em diferentes disciplinas
  (cid,53,271,'gap_fill','[Medicina] The patient _____ (administer/passive) a loading dose of 500mg followed by daily maintenance doses of 250mg.','was administered',NULL,'Medical passive: ''was administered'' = patient received (double-object passive).','medium'),
  (cid,53,272,'gap_fill','[Ciências Sociais] Participants _____ (recruit/passive) through purposive sampling and _____ (interview/passive) using a semi-structured protocol.','were recruited / were interviewed',NULL,'Social sciences methods: passive past for completed recruitment and data collection.','easy'),
  (cid,53,273,'gap_fill','[Direito] The defendant _____ (convict/passive) on two counts of fraud and _____ (sentence/passive) to four years imprisonment.','was convicted / was sentenced',NULL,'Legal passive: passive for judicial outcomes.','easy'),
  (cid,53,274,'gap_fill','[Engenharia] The bridge _____ (design/passive) to withstand wind speeds of up to 250 km/h and _____ (inspect/passive/must) annually.','was designed / must be inspected',NULL,'Engineering passive: historical design + modal passive for ongoing inspection obligation.','medium'),
  (cid,53,275,'multiple_choice','[Política] Which sentence uses passive voice MOST appropriately in a political science report?','The legislation was passed by a two-thirds majority and was immediately challenged in the courts.','[''The parliament passed the legislation, and the courts challenged it.'',''The legislation was passed by a two-thirds majority and was immediately challenged in the courts.'',''The legislation has been passed and is being challenged in the courts right now.'',''The legislation gets passed by parliament and gets challenged in the courts.'']','Passive for political process where the process matters more than the actors.','medium'),

  -- BLOCK 54: consolidação — erros comuns e TOEFL completo
  (cid,54,276,'multiple_choice','[Erro Comum] Which sentence contains a PASSIVE VOICE ERROR?','The results were clearly demonstrated the effectiveness of the treatment.','[''The results clearly demonstrated the effectiveness of the treatment (active — correct).'',''The effectiveness of the treatment was clearly demonstrated (passive — correct).'',''The treatment''s effectiveness was clearly demonstrated by the results (passive — correct).'',''The results were clearly demonstrated the effectiveness of the treatment.'']','''Were clearly demonstrated the effectiveness'' = error. Either ''demonstrated'' (active) or ''was demonstrated'' (passive, single object).','hard'),
  (cid,54,277,'gap_fill','The committee _____ (present/passive) with three competing proposals and _____ (ask/passive) to select one by consensus.','was presented / was asked',NULL,'Double-object passive (presented with) + modal-style passive (was asked to).','hard'),
  (cid,54,278,'multiple_choice','Which best converts ''Someone should review the policy annually'' to passive?','The policy should be reviewed annually.','[''The policy should review annually.'',''The policy is reviewed annually by someone.'',''The policy should be reviewed annually.'',''The policy should have been reviewing annually.'']','''Should be + past participle'' = passive modal for recommendation.','medium'),
  (cid,54,279,'production','[TOEFL Writing — final] Write a 200-word academic paragraph on renewable energy using passive voice throughout: methods passive, present passive, modal passive, perfect passive, passive infinitive.','',NULL,'Renewable energy infrastructure has been expanded rapidly across most major economies over the past decade, driven by a combination of policy incentives and declining technology costs. Solar panels and wind turbines are now being manufactured at unprecedented scale, and large-scale installations are being constructed in regions that were previously considered unsuitable for renewable generation. In many countries, energy policy has been fundamentally redesigned to accommodate distributed generation, and national grids are being modified to handle bidirectional power flows. The transition to clean energy is projected to be accelerated further as battery storage technology continues to improve, since storage capacity is needed if intermittent renewable sources are to provide reliable baseline power. Significant investment must still be directed toward grid modernization and long-distance transmission infrastructure if the full potential of renewable energy is to be realized. Several technical and regulatory barriers remain to be addressed, and international cooperation in research and development should be strengthened. With sustained commitment, the transition to a predominantly renewable energy system is expected to be achieved well within the timescales required to meet existing climate commitments.','hard'),
  (cid,54,280,'production','[TOEFL Speaking — 60s] Discuss the role of international organizations in responding to global crises, using passive voice prominently: were established, have been created, are being deployed, should be empowered, must be reformed.','',NULL,'International organizations such as the United Nations, the World Health Organization, and the World Bank were established in the aftermath of World War II to prevent the recurrence of the catastrophic conflicts and economic collapses of the preceding decades. Since then, a wide range of specialized agencies and treaty bodies have been created to address emerging global challenges — from climate change to cybersecurity to pandemic preparedness. In recent years, these institutions have been criticized for responding too slowly when crises emerge; peacekeeping forces have been deployed too late and with insufficient resources, and early warning systems have not been adequately heeded. Proponents argue that these organizations must be reformed to give them faster decision-making authority and more reliable funding. Critics counter that national sovereignty cannot be set aside so easily. What seems clear is that the challenges being faced — pandemics, climate change, nuclear proliferation — cannot be managed effectively by individual nations alone, and that institutions capable of coordinating global responses must be strengthened rather than weakened.','hard'),

  -- BLOCK 55: exercícios de gap fill final
  (cid,55,281,'gap_fill','All data _____ (store/passive) in encrypted servers and _____ (not/share/passive) with third parties without explicit consent.','are stored / are not shared',NULL,'Present passive for current data protection practice.','easy'),
  (cid,55,282,'gap_fill','The theory _____ (first/propose/passive) in 1905 and _____ (subsequently/develop/passive) by a generation of physicists.','was first proposed / was subsequently developed',NULL,'Past passive sequence for historical development of a theory.','medium'),
  (cid,55,283,'gap_fill','Significant progress _____ (make/passive) in recent years, but much _____ (remain) to _____ (do/passive).','has been made / remains / be done',NULL,'PP passive + stative + passive infinitive for academic summary.','hard'),
  (cid,55,284,'gap_fill','The limitations of this study _____ (acknowledge/passive/should) and _____ (address/passive) in future research.','should be acknowledged / addressed',NULL,'Modal passive (should be) for limitations and future work.','medium'),
  (cid,55,285,'multiple_choice','Which sentence is grammatically CORRECT?','The proposal is expected to be approved by the board at next month''s meeting.','[''The proposal expects to be approved by the board.'',''The proposal is expected to be approve by the board.'',''The proposal is expected to be approved by the board at next month''s meeting.'',''The proposal is expected be approved by the board.'']','''Is expected to be approved'' = stative passive + passive infinitive.','medium'),

  -- BLOCK 56: production final avançada
  (cid,56,286,'production','[TOEFL Speaking — 45s] Describe a scientific discovery and how it was made. Use: past passive (×3), present passive (×2), reduced passive relative (×1).','',NULL,'The structure of DNA was discovered in 1953 by James Watson and Francis Crick, though the critical X-ray crystallography images used to determine the double helix structure were produced by Rosalind Franklin and Raymond Gosling at King''s College London. The discovery was announced in a brief paper published in Nature and was immediately recognized as one of the most significant scientific breakthroughs of the century. Today, the double helix structure is considered foundational to all of modern genetics and molecular biology. Research conducted since 1953 has built upon this discovery to produce the entire field of genomics, including techniques like CRISPR gene editing that are now being used to treat genetic diseases.','hard'),
  (cid,56,287,'production','[TOEFL Speaking — 45s] Describe a policy reform that should be implemented in higher education. Use modal passives (must be, should be, could be, ought to be, cannot be).','',NULL,'Higher education funding must be reformed to ensure that access is determined by academic ability rather than financial means. Tuition fees should be replaced with income-contingent repayment systems that are capped as a percentage of graduate earnings, so that higher education cannot be experienced as an unaffordable burden by students from lower-income families. University funding ought to be diversified beyond student fees through increased government grants and private endowments. Admission processes should be redesigned to eliminate structural disadvantages faced by graduates of under-resourced secondary schools. These reforms could be phased in over a decade to allow institutions to adapt. Without action, the cycle of educational disadvantage cannot be broken.','hard'),
  (cid,56,288,'gap_fill','The samples _____ (collect/passive), _____ (label/passive), and _____ (store/passive) at -20°C until analysis _____ (conduct/passive).','were collected / labelled / stored / was conducted',NULL,'Four-verb passive chain in methods section.','medium'),
  (cid,56,289,'multiple_choice','Which complex passive sentence is grammatically CORRECT?','It has been argued that the policy should have been implemented earlier.','[''It has been argued that the policy should been implemented earlier.'',''It is being argued that the policy has been implementing earlier.'',''It has been argued that the policy should have been implemented earlier.'',''It was been argued that the policy should have been implemented earlier.'']','''It has been argued that... should have been implemented'' = impersonal PP passive + modal PP passive.','hard'),
  (cid,56,290,'gap_fill','The hypothesis _____ (test/passive) rigorously before it _____ (accept/passive) as established scientific consensus.','must be tested / can be accepted',NULL,'Modal passive chain: must be tested → can be accepted.','hard'),

  -- BLOCK 57: final consolidação — mixed review
  (cid,57,291,'multiple_choice','Which sentence correctly combines THREE passive constructions?','The data have been collected, are being analyzed, and will be published next year.','[''The data was collected, is being analyzed, and will be published next year (''data'' is plural — use ''were''/''are'').'',''The data have been collected, are being analyzed, and will be published next year.'',''The data has been collected, is being analyzed, and will be published next year.'',''The data were collected, has been analyzed, and will be published next year.'']','Data (plural) + PP passive + PC passive + future passive in one sentence.','hard'),
  (cid,57,292,'gap_fill','She _____ (make/passive) aware of the risks at the outset; she cannot claim she _____ (not/inform/passive).','was made / was not informed',NULL,'Double passive: made aware + passive for information receipt.','hard'),
  (cid,57,293,'gap_fill','The report _____ (present/passive) to the board, _____ (discuss/passive) at length, and _____ (eventually/adopt/passive) with minor amendments.','was presented / discussed / eventually adopted',NULL,'Past passive chain for formal report lifecycle.','medium'),
  (cid,57,294,'production','[TOEFL Writing — 100 words] Write a mini-paragraph on ocean conservation using: have been, are being, must be, should be, to be + PP (infinitive passive).','',NULL,'Marine ecosystems have been degraded at an alarming rate by pollution, overfishing, and rising ocean temperatures. Coral reefs, once considered among the most biodiverse habitats on Earth, are being bleached by warming waters faster than they can recover. International fishing agreements must be strengthened if commercial species are to be protected from collapse. Marine protected areas should be established across at least 30 percent of the world''s oceans by 2030, as recommended by leading conservation scientists. The infrastructure needed to monitor and enforce these protections must also be developed and funded consistently.','hard'),
  (cid,57,295,'gap_fill','The intervention _____ (design/passive) to be minimally invasive, _____ (implement/passive) over eight weeks, and _____ (evaluate/passive) using validated outcome measures.','was designed / implemented / evaluated',NULL,'Three-verb past passive chain for intervention design.','medium'),

  -- BLOCK 58: final 5 exercícios de fechamento
  (cid,58,296,'multiple_choice','[TOEFL Final] Which passive construction is MOST formal for an academic recommendation?','It is recommended that future research should be conducted with larger, more representative samples.','[''People should do more research with larger samples.'',''We recommend larger samples in future research.'',''It is recommended that future research should be conducted with larger, more representative samples.'',''Future research needs to use larger samples.'']','''It is recommended that + clause'' = impersonal passive for formal academic recommendation.','medium'),
  (cid,58,297,'gap_fill','This conclusion _____ (support/passive) by multiple lines of evidence and _____ (consider/passive) robust by the scientific community.','is supported / is considered',NULL,'Two present passives for a well-established academic conclusion.','easy'),
  (cid,58,298,'production','[TOEFL Writing — closing sentence] Write a final sentence for an essay on climate action using passive: ''The urgency of this challenge cannot...''','The urgency of this challenge cannot be overstated: the decisions that are made in the next decade will determine the conditions under which all future generations will be required to live.',NULL,'Passive: ''cannot be overstated,'' ''are made,'' ''will be required.''','hard'),
  (cid,58,299,'gap_fill','In summary, it _____ (argue/passive) throughout this paper that structural inequality _____ (must/address/passive) before meaningful progress _____ (can/achieve/passive).','has been argued / must be addressed / can be achieved',NULL,'Impersonal PP passive + modal passives for summary.','hard'),
  (cid,58,300,'production','[TOEFL Speaking — 60s] Final speaking task: Discuss the ethics of artificial intelligence decision-making. Use at least 6 passive constructions.','',NULL,'Artificial intelligence systems are now being used to make consequential decisions that were previously made by human beings — decisions about who gets a job interview, who is granted bail, and who receives a loan. These systems are trained on historical data that may have been generated by processes that were themselves discriminatory, meaning that past biases can be embedded into algorithms and then reproduced at scale without being detected or corrected. It has been argued that this represents a form of algorithmic injustice that must be addressed through both technical redesign and regulatory oversight. Systems should be audited regularly, and the data on which they are trained must be examined for discriminatory patterns. Until these safeguards are in place, high-stakes decisions that affect people''s lives should not be fully delegated to automated systems that cannot currently be held accountable.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
