-- ============================================================
-- SEED EXT 5: Módulo 21 — Inversion (ex 174-248)
-- Novos tópicos: inversion em TOEFL essays avançados, inversion
-- com not until/only when/only after, nor, so/such inversion
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'inversion';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo inversion não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 51: Inversion com ''not until'' e ''only when''
  (cid,51,174,'gap_fill','Not until the publication of this landmark study _____ the scientific community _____ to accept the proposed mechanism.','did / begin',NULL,'''Not until + past noun/event + did + subject + base verb'' = inversion for emphasis.','medium'),
  (cid,51,175,'gap_fill','Only when robust longitudinal data _____ (become) available _____ researchers _____ (able) to assess the long-term consequences of the intervention.','became / were / able',NULL,'''Only when + clause + were + subject + adjective'' = inversion.','medium'),
  (cid,51,176,'gap_fill','Not until the 1990s _____ the full extent of the damage _____ (appreciate/passive) by the scientific community, _____ which point _____ (too/late) _____ (prevent) significant ecological loss.','did / come to be appreciated / by / it was too late / to prevent',NULL,'''Not until + decade + did + inversion'' + ''by which point.''','hard'),
  (cid,51,177,'multiple_choice','Which sentence uses ''only when'' inversion CORRECTLY?','Only when the final data were analyzed did the scale of the problem become apparent.','[''Only when the final data were analyzed the scale of the problem became apparent.'',''Only when the final data were analyzed did the scale of the problem become apparent.'',''Only when the final data were analyzed, the scale of the problem did become apparent.'',''Only when the final data were analyzed, did the scale of the problem became apparent.'']','''Only when + clause + did + subject + base verb'' = correct inversion pattern.','medium'),
  (cid,51,178,'gap_fill','Only after sustained international pressure _____ the government _____ (agree) to submit to independent monitoring of its compliance.','did / agree',NULL,'''Only after + noun phrase + did + subject + base verb'' = inversion.','easy'),

  -- BLOCK 52: Inversion com ''only then / only by / only through''
  (cid,52,179,'gap_fill','Only by _____ (address) both supply and demand simultaneously _____ policymakers _____ (hope) to achieve a lasting reduction in energy consumption.','addressing / can / hope',NULL,'''Only by + gerund + can + subject + base verb'' = inversion with modal.','hard'),
  (cid,52,180,'gap_fill','Only through sustained investment in research and development _____ the private sector _____ (succeed) in bringing these technologies to commercial viability.','did / succeed / has / succeeded',NULL,'''Only through + noun phrase + did/has + subject + verb'' = inversion.','medium'),
  (cid,52,181,'multiple_choice','Which sentence uses ''only by'' inversion CORRECTLY for an academic argument?','Only by integrating both quantitative and qualitative evidence can researchers develop a comprehensive understanding of this phenomenon.','[''Only by integrating both quantitative and qualitative evidence researchers can develop a comprehensive understanding.'',''Only by integrating both quantitative and qualitative evidence can researchers develop a comprehensive understanding of this phenomenon.'',''Only by integrating both quantitative and qualitative evidence researchers are able to develop a comprehensive understanding.'',''Only by integration of both quantitative and qualitative evidence can researchers develop a comprehensive understanding.'']','''Only by + gerund + can + subject + base verb'' = correct inversion form.','medium'),
  (cid,52,182,'gap_fill','Only then _____ policymakers _____ (begin) to grasp the full complexity of the problem they faced — and by then, the most cost-effective window for intervention _____ (already/close/passive).','did / begin / had already been closed',NULL,'''Only then + did + subject + verb'' + past perfect for prior completion.','hard'),
  (cid,52,183,'gap_fill','Only through collective action at the international level _____ the kinds of coordination failures that _____ (generate) these market distortions _____ (overcome/passive).','can / have generated / be overcome',NULL,'''Only through + noun phrase + can + subject + be overcome'' = inversion with passive.','hard'),

  -- BLOCK 53: Nor inversion
  (cid,53,184,'gap_fill','The approach is neither theoretically coherent _____ _____ it _____ (support/passive) by the empirical evidence.','nor / is / supported',NULL,'''Nor + auxiliary + subject + past participle'' = nor inversion.','medium'),
  (cid,53,185,'gap_fill','The study does not demonstrate causation, _____ _____ its findings _____ (replicate/passive) in larger or more diverse samples.','nor / have / been replicated',NULL,'''Nor + have + subject + been + PP'' = present perfect nor inversion.','hard'),
  (cid,53,186,'multiple_choice','Which ''nor'' inversion is CORRECT in formal academic writing?','The model does not account for distributional effects, nor does it address institutional heterogeneity.','[''The model does not account for distributional effects, nor it does address institutional heterogeneity.'',''The model does not account for distributional effects, nor does it address institutional heterogeneity.'',''The model does not account for distributional effects, nor addresses it institutional heterogeneity.'',''The model does not account for distributional effects, nor it addresses institutional heterogeneity.'']','''Nor + does + subject + base verb'' = standard nor inversion auxiliary form.','medium'),
  (cid,53,187,'gap_fill','The reforms _____ (not/produce) the expected improvements in efficiency, _____ _____ they _____ (succeed) in reducing the equity gaps that had motivated their introduction.','did not produce / nor / did / succeed',NULL,'''Did not produce + nor did + subject + verb'' = parallel nor inversion with PS.','medium'),
  (cid,53,188,'gap_fill','These findings _____ (not/resolve) the debate, _____ _____ the authors _____ (claim) they _____ (do).','do not resolve / nor / do / claim / do',NULL,'''Do not resolve + nor do + subject + claim + they do'' = nested nor inversion.','hard'),

  -- BLOCK 54: So/Such inversion
  (cid,54,189,'gap_fill','So _____ (rapid) _____ the pace of change _____ that existing governance frameworks _____ (design/passive) for a previous technological era _____ (simply/not/equipped) _____ (handle) the new challenges.','rapid / was / that / designed / are simply not equipped / to handle',NULL,'''So + adjective + was + subject + that'' = so inversion with result clause.','hard'),
  (cid,54,190,'gap_fill','Such _____ the complexity of the problem _____ no single discipline, working in isolation, _____ (be) able _____ (provide) adequate solutions.','was / that / is / to provide',NULL,'''Such was + subject + that'' = such inversion.','hard'),
  (cid,54,191,'multiple_choice','Which ''so...that'' inversion is CORRECT in academic English?','So profound were the implications of this finding that the research agenda of the entire field was subsequently reorganized.','[''So profound the implications of this finding were that the research agenda was reorganized.'',''So profound were the implications of this finding that the research agenda of the entire field was subsequently reorganized.'',''So profound the implications of this finding that the research agenda was reorganized.'',''So profoundly were the implications of this finding that the research agenda was reorganized.'']','''So + adjective + were + subject + that'' = inverted ''so...that'' with past tense.','hard'),
  (cid,54,192,'gap_fill','So _____ (significant) _____ the disparities between high- and low-income countries _____ that the concept of a single global standard _____ (apply/passive) uniformly has been described as fundamentally unrealistic.','significant / are / that / applied',NULL,'''So + adjective + are + subject + that'' = present tense so-inversion.','medium'),

  -- BLOCK 55: TOEFL Reading avançado com inversion
  (cid,55,193,'multiple_choice','[TOEFL Reading] ''Not since the Industrial Revolution has the economy undergone transformation of this magnitude.'' The inversion emphasizes:','The exceptional, historically unprecedented scale of the current transformation.','[''A routine change'',''The exceptional, historically unprecedented scale of the current transformation.'',''A change that happened before the Industrial Revolution'',''That the Industrial Revolution was unimportant'']','''Not since X has Y'' = inversion to stress the uniqueness by historical comparison.','easy'),
  (cid,55,194,'gap_fill','[TOEFL Reading] ''Only by _____ (recognize) the role of structural factors _____ we _____ (move) beyond superficial explanations.'' Best inversion forms?','recognizing / can / move',NULL,'''Only by + gerund + can + subject + base verb'' = inversion in academic argument.','medium'),
  (cid,55,195,'multiple_choice','[TOEFL Reading] ''So pervasive is the influence of social media that traditional information gatekeepers have lost much of their authority.'' The purpose of this inversion is:','To emphasize the extreme degree of social media''s influence.','[''To reduce formality'',''To emphasize the extreme degree of social media''s influence.'',''To contrast two time periods'',''To introduce a concession'']','''So + adjective + is + subject'' = inversion for emphasis on degree.','easy'),
  (cid,55,196,'gap_fill','[TOEFL Reading] ''Rarely in the history of science _____ a single discovery _____ (transform) a field so completely within a single decade.'' Best forms?','has / transformed',NULL,'''Rarely + has + subject + PP'' = present perfect inversion with negative adverb.','medium'),

  -- BLOCK 56: TOEFL Speaking avançado
  (cid,56,197,'production','[TOEFL Speaking — 45s] A reading describes the severity of global water scarcity. Use inversion structures in your summary.','',NULL,'The reading presents a stark picture of global water scarcity that uses several rhetorical devices to emphasize the severity of the problem. Not only does the reading note that approximately two billion people currently lack access to safe drinking water, but it also argues that this figure will worsen dramatically as climate change reduces snowpack and glaciers that feed major river systems. So severe is the mismatch between water availability and demand in certain regions that entire agricultural systems are at risk of collapse within decades under current trajectories. Only by fundamentally restructuring water governance frameworks, the reading argues — moving from open-access exploitation to managed, rights-based systems — can the most catastrophic outcomes be avoided. Nor does the reading spare criticism of wealthy nations: rarely have the countries with the highest per capita water consumption made meaningful concessions in international water governance negotiations, despite bearing disproportionate responsibility for the climate change that is exacerbating scarcity.','hard'),
  (cid,56,198,'production','[TOEFL Speaking — 45s] Discuss the importance of judicial independence using inversion for rhetorical effect.','',NULL,'Judicial independence is perhaps the most fundamental institutional feature distinguishing constitutional democracies from systems in which political power operates without effective legal constraint. Not until a judiciary is genuinely insulated from political pressure can it serve as a credible check on executive and legislative overreach. Only through robust appointment procedures, secure tenure, and adequate funding can courts resist the kind of political pressure that would compromise their impartiality. So important is judicial independence to the rule of law that its erosion — even incremental erosion through the appointment of ideologically loyal judges or the defunding of court systems — has historically proved to be among the most reliable early indicators of democratic backsliding. Nor is the threat to judicial independence limited to overt political interference: subtler pressures, including public campaigns to delegitimize courts that issue inconvenient rulings, can undermine public confidence in the judiciary without any formal institutional change. Only when citizens, legal professionals, and civil society organizations treat judicial independence as a non-negotiable commitment rather than a partisan issue does it acquire the political protection it requires.','hard'),

  -- BLOCK 57: TOEFL Writing avançado com inversion
  (cid,57,199,'production','[TOEFL Writing — 200 words] Write a paragraph on the global food system using inversion for rhetorical emphasis.','',NULL,'The global food system is under pressure from multiple directions simultaneously, and so severe are these pressures that many analysts argue it requires fundamental transformation rather than incremental reform. Not only does the current system fail to feed approximately 800 million people who suffer from chronic hunger, but it also generates significant overconsumption in wealthy countries that is associated with a different set of health crises. So profound is the environmental impact of industrial agriculture — contributing approximately one-third of global greenhouse gas emissions, consuming 70% of the world''s freshwater withdrawals, and driving the majority of terrestrial biodiversity loss — that food system transformation is now widely recognized as inseparable from climate change mitigation and nature conservation. Only by simultaneously reducing food waste, shifting dietary patterns in high-consumption countries toward more plant-based foods, and improving agricultural productivity in a way that is compatible with ecosystem health can the food system meet growing global demand without catastrophic environmental consequences. Nor can these changes be achieved through consumer choice alone: rarely in history have large-scale dietary and agricultural transitions occurred without significant policy intervention to restructure the incentives that shape what farmers grow and what food systems deliver. Only through coordinated action across agricultural, trade, and environmental policy can the necessary transformation be achieved at the speed and scale the evidence demands.','hard'),
  (cid,57,200,'production','[TOEFL Writing — 200 words] Write a paragraph on the role of media in democracy using inversion structures.','',NULL,'A free and pluralistic media is widely recognized as essential to democratic governance, yet so profound are the structural pressures facing journalism that the conditions for a well-functioning public sphere are deteriorating in many countries simultaneously. Not only has the collapse of the advertising-supported business model gutted the financial foundations of local journalism, leaving large swaths of the country without credible local reporting on government and public affairs, but the digital platforms that have captured the advertising revenue formerly supporting journalism have shown little interest in investing the resources required to fill the resulting information gap. Only when citizens have access to credible, independent reporting can they make informed electoral choices and hold powerful institutions accountable; not until this basic informational condition is met can democratic governance function as theory requires. So concentrated has media ownership become in many countries that a small number of corporations or wealthy individuals exert extraordinary influence over the information environment through which public opinion is formed. Nor has the proliferation of information sources online reliably compensated for these losses: rarely does the volume of available information translate automatically into a better-informed public, and often it correlates with greater exposure to misinformation and partisan narratives rather than more reliable civic knowledge.','hard'),

  -- BLOCK 58: Final
  (cid,58,201,'production','[TOEFL Writing — 200 words] Write a paragraph on technology and inequality using inverted structures throughout.','',NULL,'Technological innovation has historically been one of the most powerful drivers of rising living standards, yet the distributional consequences of the current wave of technological change are deeply troubling, and so significant are the risks of technology-driven inequality that policymakers can no longer treat distribution as a secondary consideration after growth. Not only do the productivity gains from automation and artificial intelligence accrue disproportionately to capital owners and highly skilled workers, but the communities most dependent on the employment categories at greatest risk of automation — manufacturing, routine clerical work, transportation — are often precisely those that have already experienced decades of relative economic decline. Only by investing in genuinely accessible retraining programs, portable social insurance systems, and regional economic development strategies can governments hope to distribute the gains from technological change more equitably. So inadequate have conventional education and training systems proved at managing previous technological transitions that simply extending existing programs is unlikely to be sufficient; only a more fundamental redesign of the relationship between technology, work, and social protection will address the structural challenge. Nor is this simply a domestic policy problem: rarely has technological inequality been addressed effectively without some degree of international coordination on issues such as digital taxation, technology transfer to lower-income countries, and global standards for AI governance.','hard'),
  (cid,58,202,'production','[TOEFL Speaking — 60s] Use inversion structures to make a persuasive argument about the importance of investing in early childhood education.','',NULL,'The evidence on early childhood development represents one of the most compelling cases in all of social policy for a specific public investment, and only by examining the neuroscientific, economic, and social evidence together does its full significance become apparent. Not until the research of James Heckman and others on the returns to early childhood investment became widely known did the economic case for public investment in early childhood education become central to mainstream policy discussion. So large are the returns to high-quality early childhood programs — estimates consistently suggest benefit-cost ratios of three to seven to one when downstream educational, health, and criminal justice savings are included — that it is difficult to identify any comparable public investment with such robust evidence of economic return. Only when children arrive at formal schooling with the cognitive and social-emotional foundations that high-quality early childhood programs provide are they positioned to benefit fully from subsequent educational investments; not until this foundational period has been adequately supported can later interventions compensate for early disadvantage cost-effectively. Nor is the case for early childhood investment only economic: so profound is the influence of the first five years on brain architecture and lifelong health that the moral argument for ensuring every child has access to high-quality early experiences is compelling independently of the economic returns. Only through treating early childhood as a genuine policy priority — rather than as a soft peripheral concern — will societies realize the full potential of their next generations.','hard'),
  (cid,58,203,'production','[TOEFL Writing — Final 200 words] Write a conclusion on global governance reform using inversion throughout.','',NULL,'This essay has argued that the global governance architecture inherited from the mid-twentieth century is increasingly inadequate to the challenges of a deeply interdependent world, and that only through ambitious institutional reform can the coordination failures that are generating the most serious collective risks be addressed. Not only do existing institutions lack the authority and resources to manage global challenges at the necessary scale, but their governance structures systematically underrepresent the interests of the populations most affected by their decisions. So entrenched are the vested interests of existing major powers in an institutional status quo that reflects their historical dominance that meaningful reform will require sustained political pressure from a broad coalition of countries whose combined economic weight has increased substantially since these institutions were designed. Only when the governance of international institutions reflects the actual distribution of global economic and political power of the twenty-first century rather than that of 1945 will these institutions have the legitimacy they need to function effectively. Nor is institutional reform the only requirement: rarely have international institutions delivered more than member states'' political will allows, and so the deeper challenge is building domestic coalitions within major countries that support ambitious multilateral cooperation on the issues — climate, health, financial stability, and AI governance — that genuinely require it.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
