-- ============================================================
-- SEED EXT 4: Módulo 07 — Present Perfect (ex 150-220)
-- Novos tópicos: PP em academic writing avançado, PP passivo,
-- PP em headlines, PP vs PS em contexto TOEFL
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'present-perfect';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo present-perfect não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 41: PP em academic writing — reporting current state of knowledge
  (cid,41,150,'gap_fill','Researchers _____ (establish) that sleep deprivation impairs cognitive performance, though the precise mechanisms remain debated.','have established',NULL,'PP in lit review: general field finding with current relevance.','easy'),
  (cid,41,151,'gap_fill','To date, no study _____ (demonstrate) a causal mechanism linking X to Y in human populations.','has demonstrated',NULL,'"To date" + PP negative = absence of finding up to present.','medium'),
  (cid,41,152,'multiple_choice','Why does academic writing often use present perfect in literature reviews?','Because the findings are presented as still relevant to the current discussion.','["Because the findings are very old","Because the findings are presented as still relevant to the current discussion.","Because present perfect is more formal than past simple","Because academic writing always avoids past simple"]','PP = past action with present relevance. Lit review findings → still matter now → PP.','medium'),
  (cid,41,153,'gap_fill','The field _____ (undergo) significant theoretical development since the original formulation was published in 1982.','has undergone',NULL,'PP + "since" for ongoing development from a past point to present.','easy'),
  (cid,41,154,'gap_fill','Several competing hypotheses _____ (propose/passive), but none _____ (yet/receive) universal acceptance.','have been proposed / has yet received / has yet been received',NULL,'PP passive (plural proposals) + PP negative for lack of consensus.','hard'),
  (cid,41,155,'multiple_choice','Which sentence correctly uses present perfect in an academic introduction?','Interest in this phenomenon has grown substantially over the past decade.','["Interest in this phenomenon grew substantially over the past decade (PS + completed past — use if specific decade end is stated).","Interest in this phenomenon has grown substantially over the past decade.","Interest in this phenomenon is growing substantially over the past decade (PC — for ongoing current trend, not accumulation).","Interest in this phenomenon grew over the past decade (PS acceptable if decade is specifically past)"]','PP + "over the past decade" = accumulation up to present. PS = completed period.','hard'),

  -- BLOCK 42: PP passivo em textos acadêmicos
  (cid,42,156,'gap_fill','A comprehensive meta-analysis _____ (conduct/passive) by Smith et al. (2023) confirming the robustness of the original findings.','has been conducted',NULL,'PP passive for recent completed research.','medium'),
  (cid,42,157,'gap_fill','These results _____ (replicate/passive) in three independent studies, providing strong evidence for the generalizability of the effect.','have been replicated',NULL,'PP passive for cumulative replication (multiple times).','medium'),
  (cid,42,158,'multiple_choice','Which sentence uses present perfect passive CORRECTLY in academic writing?','The data have been collected from a nationally representative sample of 10,000 households.','["The data has been collected from a nationally representative sample (''data'' is plural — have, not has).","The data have been collecting from a nationally representative sample (wrong -ing).","The data have been collected from a nationally representative sample of 10,000 households.","The data are been collected from a nationally representative sample."]','"Data" = plural noun → "have been collected" (plural PP passive).','medium'),
  (cid,42,159,'gap_fill','The model _____ (validate/passive) across multiple datasets, and its predictive accuracy _____ (confirm/passive) in out-of-sample tests.','has been validated / has been confirmed',NULL,'PP passive x2 for model validation process.','medium'),
  (cid,42,160,'gap_fill','No significant adverse effects _____ (report/passive) in any of the 14 trials included in this review.','have been reported',NULL,'PP passive negative: absence of reported adverse effects across multiple trials.','hard'),

  -- BLOCK 43: PP em notícias/headlines
  (cid,43,161,'multiple_choice','Why does English newspaper journalism use present perfect in headlines?','Because PP signals that the event has just happened and is still relevant — it emphasizes immediacy and current news value.','["Because past simple is too informal for headlines","Because PP signals that the event has just happened and is still relevant.","Because newspapers always avoid past simple","Because headlines must use present tense"]','PP in headlines = the news is fresh, has present consequences, is currently relevant.','easy'),
  (cid,43,162,'multiple_choice','Which of these is a correct HEADLINE using present perfect?','Scientists Have Identified Gene Linked to Early Alzheimer''s Onset','["Scientists Identified Gene Linked to Early Alzheimer''s Onset (past simple — also acceptable in many outlets)","Scientists Have Identified Gene Linked to Early Alzheimer''s Onset","Scientists Identify Gene Linked to Early Alzheimer''s Onset (present simple — dramatic present, also common)","Scientists Are Identifying Gene Linked to Early Alzheimer''s Onset (PC — wrong for completed discovery)"]','PP in headline: Scientists have identified = just happened, still relevant. All three options are used; PP is the canonical choice for recent event.','hard'),
  (cid,43,163,'gap_fill','[Headline] Central Bank _____ (raise) Interest Rates for Third Time This Year.','Has Raised',NULL,'PP in headline for recent financial event.','easy'),
  (cid,43,164,'gap_fill','[Headline] Negotiators _____ (reach) Agreement on Climate Finance After Weeks of Talks.','Have Reached',NULL,'PP in headline for recently completed negotiation.','easy'),
  (cid,43,165,'multiple_choice','When does a news article SWITCH from present perfect (headline) to past simple (body)?','When specific times, dates, or places are mentioned in the body.','["Never — always use present perfect throughout","When specific times, dates, or places are mentioned in the body.","When the event is considered very important","After the first paragraph"]','PP in headlines (no specific time). PS in body (time specified: ''on Tuesday'', ''at 3pm'').','medium'),

  -- BLOCK 44: PP vs PS — decisão avançada
  (cid,44,166,'multiple_choice','Which pair correctly uses PP vs PS?','"Researchers have identified three risk factors. Smith (2019) identified the same factors in a smaller cohort."','["''Researchers have identified three risk factors. Smith (2019) identified the same factors in a smaller cohort.''","''Researchers have identified three risk factors. Smith (2019) has identified the same factors.''","''Researchers identified three risk factors. Smith (2019) has identified the same factors.''","''Researchers are identifying three risk factors. Smith (2019) identified the same factors.''"]','General finding → PP. Specific study + year → PS.','hard'),
  (cid,44,167,'gap_fill','The number of internet users worldwide _____ (grow) from 400 million in 2000 to over 5 billion today.','has grown',NULL,'PP for change from a past point up to the present (with "from…to" spanning to now).','hard'),
  (cid,44,168,'gap_fill','Einstein _____ (propose) the theory of relativity in 1905, and its predictions _____ (confirm/passive) repeatedly in the century since.','proposed / have been confirmed',NULL,'PS for specific historical event + PP for ongoing confirmation to present.','hard'),
  (cid,44,169,'multiple_choice','Which sentence INCORRECTLY mixes PP and PS?','Darwin has proposed the theory of evolution in 1859, which challenged the prevailing religious worldview.','["Darwin proposed the theory of evolution in 1859, which challenged the prevailing religious worldview (past simple for historical event with specific year — correct).","The theory of evolution has been accepted by most biologists since it was proposed (PP for ongoing acceptance — correct).","Darwin has proposed the theory of evolution in 1859, which challenged the prevailing religious worldview.","Since Darwin proposed it in 1859, the theory of evolution has undergone numerous revisions (PS for specific past event + PP for subsequent changes — correct)."]','"Has proposed + 1859" = error. Specific year → past simple.','easy'),
  (cid,44,170,'gap_fill','The crisis _____ (last) three years before the government _____ (finally/intervene); by then, thousands _____ (already/lose) their homes.','lasted / finally intervened / had already lost',NULL,'PS x2 for completed events + PP for prior-to-past-point consequence.','hard'),

  -- BLOCK 45: PP com advérbios de tempo avançados
  (cid,45,171,'gap_fill','The team _____ (not/yet/publish) its findings, although the research _____ (complete/passive) six months ago.','has not yet published / was completed',NULL,'PP negative + "yet" + PS passive for completed past event.','hard'),
  (cid,45,172,'multiple_choice','Which sentence correctly uses "ever" with present perfect?','This represents the most significant environmental achievement ever recorded.','["This represents the most significant environmental achievement ever recorded.","This represents the most significant environmental achievement ever recorded (correct).","Has anyone ever seen such a transformation? (correct question form)","Scientists have never observed this phenomenon under natural conditions (PP negative + never = correct)"]','All are correct. Distractors exist to verify understanding. "Ever" = at any time = PP.','medium'),
  (cid,45,173,'gap_fill','The prime minister _____ (resign) — this _____ (just/announce/passive) by the cabinet secretary.','has resigned / has just been announced',NULL,'PP for immediate past event + PP passive with "just" for recent announcement.','easy'),
  (cid,45,174,'gap_fill','The organization _____ (exist) for over a century and _____ (help) millions of people during that time.','has existed / has helped',NULL,'PP for duration from past to present (for + period continuing to now).','easy'),
  (cid,45,175,'multiple_choice','Which sentence uses present perfect with "since" CORRECTLY?','Interest rates have risen sharply since the central bank changed its policy.','["Interest rates have risen sharply since the central bank has changed its policy (double PP with since — error: since + PS or PP in time clause, but not PP + PP in same clause logically).","Interest rates have risen sharply since the central bank changed its policy.","Interest rates rose sharply since the central bank changed its policy (PS + since — error: since requires PP in main clause).","Interest rates are rising sharply since the central bank changed its policy (PC — wrong for since clauses)."]','PP main clause + PS in since-clause = correct standard structure.','hard'),

  -- BLOCK 46: TOEFL Reading
  (cid,46,176,'multiple_choice','[TOEFL Reading] "Research has consistently shown that air pollution reduces life expectancy in urban areas." The PP "has shown" is used because:','The research finding remains relevant to current policy and public health discussions.','["The research was only conducted once","The research finding remains relevant to current policy and public health discussions.","Present perfect is always used with ''consistently''","The research occurred in the distant past"]','PP for ongoing relevance of past research to present situation.','easy'),
  (cid,46,177,'gap_fill','[TOEFL Reading] "Over the past five decades, the rate of ice sheet melting _____ (accelerate) dramatically." Best form?','has accelerated',NULL,'PP for change accumulated over a period extending to the present.','easy'),
  (cid,46,178,'multiple_choice','[TOEFL Reading] "Studies have been conducted, data have been collected, and results have been peer-reviewed — yet no consensus has emerged." What does this triple PP passive structure emphasize?','That all these processes are complete but the outcome (consensus) is still lacking.','["That the processes are ongoing","That the processes failed","That all these processes are complete but the outcome (consensus) is still lacking.","That the processes will be repeated"]','PP passive in series shows completion of process; PP negative shows persistent lack of result.','hard'),
  (cid,46,179,'gap_fill','[TOEFL Reading] "No vaccine _____ (yet/develop/passive) that provides complete and lasting protection against this pathogen." Best form?','has yet been developed',NULL,'PP passive negative + "yet" for absence of development up to present.','hard'),

  -- BLOCK 47: TOEFL Speaking
  (cid,47,180,'production','[TOEFL Speaking — 45s] A reading describes advances in renewable energy. The professor discusses challenges that have emerged. Summarize using PP for both.','',NULL,'The reading describes the remarkable advances that renewable energy technology has made over the past two decades. Solar and wind power costs have fallen dramatically — by more than 90% in the case of solar — making them the cheapest sources of new electricity generation in most markets. However, the professor points out that alongside these successes, significant challenges have also emerged. Electricity grids have struggled to handle the intermittency of renewable sources, and investment in storage technology has lagged behind the growth in generation capacity. Permitting processes have slowed down the construction of the new transmission infrastructure that renewables require, and supply chains for the critical minerals needed for solar panels and batteries have become geopolitically concentrated in ways that have introduced new vulnerabilities.','hard'),
  (cid,47,181,'production','[TOEFL Speaking — 45s] Describe what has changed in your city or region over the past ten years. Use PP for changes and PS for historical facts.','',NULL,'Over the past ten years, my city has undergone significant transformation. Housing costs have risen faster than incomes, making it increasingly difficult for younger residents and lower-income families to remain. At the same time, the public transportation system has expanded significantly — new metro lines have opened, and a bus rapid transit corridor has begun operating. The urban center has become considerably denser as new high-rise residential and commercial buildings have been constructed on former industrial land. The city''s economy has shifted away from manufacturing and toward services, particularly in technology, healthcare, and education. Some neighborhoods that were considered peripheral have become desirable as younger professionals have moved in. Not all changes have been positive: some long-established communities have been displaced by rising rents, and income inequality has widened despite the general growth in prosperity.','hard'),

  -- BLOCK 48: TOEFL Writing
  (cid,48,182,'production','[TOEFL Writing — 150 words] Write an introduction for a TOEFL essay on technological inequality. Use PP (×4), PS (×2), and PC (×1).','',NULL,'Technological change has transformed economic and social life in virtually every country over the past half century. Digital technology has created new forms of wealth, new occupational categories, and new channels of communication that were inconceivable to earlier generations. Yet the benefits of this transformation have not distributed themselves equitably. Research has consistently shown that access to digital technology correlates strongly with income, education, and geography, generating what scholars call the "digital divide." Those who lack reliable internet access, digital literacy, or the hardware necessary to participate fully in the digital economy are increasingly finding themselves excluded from economic opportunity that the connected majority takes for granted. This essay argues that addressing technological inequality is not merely a matter of social justice but an economic imperative: an economy in which a significant portion of the workforce cannot effectively deploy digital tools is an economy that is leaving substantial productive potential unrealized.','hard'),
  (cid,48,183,'production','[TOEFL Writing — 150 words] Write a body paragraph on the present perfect vs past simple distinction in academic writing. Use examples from real academic discourse.','',NULL,'The distinction between present perfect and past simple is one of the most significant and nuanced in academic English. Writers use the present perfect to situate past actions within a continuing relevance to the present, while past simple positions an action as completed and time-delimited. In literature reviews, the present perfect dominates when writers wish to report what a field has established (''Research has demonstrated that...''), while past simple appears when specific studies with named authors and dates are cited (''Smith and Jones (2019) found that...''). This contrast is not arbitrary: the present perfect implies that findings still hold and matter, while past simple implies a specific, bounded contribution. Non-native speakers frequently overuse past simple in contexts where present perfect would signal appropriate academic awareness of the ongoing relevance of prior scholarship.','hard'),
  (cid,48,184,'production','[TOEFL Writing — 200 words] Write a body paragraph on the history and current state of international human rights law. Use PP for ongoing developments and PS for historical founding moments.','',NULL,'International human rights law has evolved significantly since the adoption of the Universal Declaration of Human Rights in 1948, which established for the first time a comprehensive framework of rights to which all human beings are entitled. The Declaration was followed by binding legal instruments: the International Covenant on Civil and Political Rights and the International Covenant on Economic, Social and Cultural Rights, both adopted in 1966 and entering into force in 1976. Since that foundational period, the human rights treaty system has expanded considerably. The UN has established specialized conventions addressing the rights of women, children, and persons with disabilities, each accompanied by monitoring committees that review state compliance. Regional systems — most notably the European Convention on Human Rights, enforced by the European Court of Human Rights — have developed robust judicial enforcement mechanisms that have produced binding judgments against member states. However, the gap between the legal framework and its implementation on the ground has remained substantial. Many states have ratified human rights treaties without meaningfully incorporating them into domestic law, and enforcement mechanisms have struggled to hold powerful states accountable for systematic violations.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
