-- ============================================================
-- SEED EXT 5: Módulo 12 — Conditional Types 2 & 3 (ex 173-248)
-- Novos tópicos: conditionals em academic argumentation, mixed
-- conditionals avançados, implicit conditionals, TOEFL tasks
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'conditional-2-3';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo conditional-2-3 não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 51: Type 2 em academic argumentation
  (cid,51,173,'gap_fill','If policymakers _____ (take) distributional consequences more seriously, the political backlash against trade liberalization _____ (be) considerably less severe.','took / would be',NULL,'Type 2: if + PS + would + base verb = hypothetical about present/ongoing situation.','easy'),
  (cid,51,174,'gap_fill','If the proposed regulatory framework _____ (implement/passive) without adequate consultation, industry resistance _____ (likely/undermine) its effectiveness in practice.','were implemented / would likely undermine',NULL,'Type 2 passive: if + were + passive past participle + would.','medium'),
  (cid,51,175,'gap_fill','Were the evidence _____ (strong) than it currently is, a more definitive policy recommendation _____ (possible/be); as it stands, _____ (caution) _____ (remain) appropriate.','stronger / would be possible / caution / remains',NULL,'Inverted Type 2 (Were + adjective) + real present conclusion.','hard'),
  (cid,51,176,'multiple_choice','Which Type 2 conditional uses PASSIVE correctly in the if-clause?','If the data were re-analyzed using a different methodology, the results would likely change.','["If the data was re-analyzed using a different methodology, the results would likely change.","If the data were re-analyzed using a different methodology, the results would likely change.","If the data were re-analyzing using a different methodology, the results would likely change.","If the data would be re-analyzed using a different methodology, the results would likely change."]','"Were re-analyzed" = Type 2 passive subjunctive. "Was" = informal; "were" preferred in formal writing.','medium'),
  (cid,51,177,'gap_fill','If every nation _____ (adopt) an equivalent carbon price, the competitive distortions _____ (argue/passive) to _____ (reduce) substantially, _____ (make) border adjustment mechanisms less necessary.','adopted / could be argued / reduce / making',NULL,'Type 2 with complex result clause: could be argued to reduce + participial result.','hard'),

  -- BLOCK 52: Type 3 em análise histórica e política
  (cid,52,178,'gap_fill','If the Bretton Woods negotiators _____ (include) a more balanced international monetary adjustment mechanism, the persistent global imbalances of the early twenty-first century _____ (not/develop/passive) to the extent they did.','had included / would not have been developed / would not have developed',NULL,'Type 3: if + PP + would have + PP. Counterfactual about history.','hard'),
  (cid,52,179,'gap_fill','If the intervention _____ (begin) six months earlier, the study _____ (detect/passive) effects that may _____ (subsequently/disappear/passive) by the time data _____ (collect/passive).','had begun / could have detected / have subsequently disappeared / was collected',NULL,'Type 3 with modal variation (could have detected) + complex time references.','hard'),
  (cid,52,180,'multiple_choice','Which Type 3 sentence MOST APPROPRIATELY evaluates a historical counterfactual in academic writing?','Had the government intervened earlier, the crisis might have been contained before it reached systemic proportions.','["If the government would have intervened earlier, the crisis might have been contained.","If the government had intervened earlier, the crisis was contained.","Had the government intervened earlier, the crisis might have been contained before it reached systemic proportions.","If the government would intervene earlier, the crisis might have been contained."]','Inverted Type 3 (Had + PP) + "might have been contained" (Type 3 result with epistemic modal).','hard'),
  (cid,52,181,'gap_fill','If early warning signals _____ (not/ignore/passive), the subsequent policy response _____ (earlier/initiate/passive) and losses _____ (substantially/mitigate/passive).','had not been ignored / would have been earlier initiated / would have been substantially mitigated',NULL,'Type 3 triple passive: if + PP passive negative + would have been + PP.','hard'),
  (cid,52,182,'gap_fill','The financial crisis of 2008 _____ (not/be) as severe if adequate macroprudential regulation _____ (implement/passive) in the preceding decade.','would not have been / had been implemented',NULL,'Type 3 with inverted word order in main clause.','medium'),

  -- BLOCK 53: Mixed conditionals avançados
  (cid,53,183,'gap_fill','If the research team _____ (design) a more rigorous protocol three years ago, we _____ (now/have) much clearer evidence on which to base policy recommendations.','had designed / would now have',NULL,'Mixed conditional: Type 3 if-clause (past) + Type 2 result (present consequence).','hard'),
  (cid,53,184,'gap_fill','If current deforestation rates _____ (continue) unchecked, many of the species _____ (depend) on these habitats _____ (not/still/exist) by the end of this century.','continue / that depend / will not still exist / would not still exist',NULL,'Mixed: Type 1 if-clause (real current) + future result spanning to future point.','hard'),
  (cid,53,185,'multiple_choice','Which sentence is a MIXED conditional (past cause → present result)?','If researchers had collected longitudinal data from the beginning, we would now understand the long-term effects much better.','["If researchers had collected longitudinal data, we would have understood effects much better.","If researchers collected longitudinal data, we would understand effects better.","If researchers had collected longitudinal data from the beginning, we would now understand the long-term effects much better.","If researchers collect longitudinal data, we will understand effects better."]','Type 3 if-clause (had collected = past action not taken) + Type 2 result (would now understand = present consequence).','hard'),
  (cid,53,186,'gap_fill','If the institution _____ (build) greater trust with communities over the preceding decade, it _____ (now/face) considerably less resistance to implementing the reforms it currently _____ (need).','had built / would now be facing / needs',NULL,'Mixed Type 3→2: had built (past) + would now be facing (present consequence) + needs (present fact).','hard'),
  (cid,53,187,'gap_fill','Were she _____ (not/commit) to the current position, she _____ (be) far better placed to evaluate the evidence impartially; _____, having made a public commitment, _____ (now/find) it difficult _____ (change) course.','not committed / would be / however / she now finds / to change',NULL,'Inverted Type 2 + Type 2 result + real present contrast with "however."','hard'),

  -- BLOCK 54: Implicit conditionals
  (cid,54,188,'multiple_choice','Which sentence contains an IMPLICIT conditional (no "if" clause)?','A more prudent fiscal policy would have avoided the current debt crisis.','["The government should have adopted a more prudent fiscal policy.","A more prudent fiscal policy would have avoided the current debt crisis.","Without prudent fiscal policy, debt crises are more likely.","It is important to adopt prudent fiscal policy."]','"A more prudent fiscal policy would have avoided..." = implicit Type 3: if a more prudent policy had been adopted, the crisis would have been avoided.','hard'),
  (cid,54,189,'gap_fill','A country with stronger institutions _____ (weather) external shocks more successfully; a weaker state, by contrast, _____ (likely/find) its governance capacity overwhelmed.','would weather / would likely find',NULL,'Implicit Type 2: "a country with X" = "if a country had X" — implicit condition.','hard'),
  (cid,54,190,'gap_fill','Even a modest increase in female labor force participation _____ (translate) into significant GDP growth in economies _____ (currently/underutilize) this productive capacity.','would translate / that currently underutilize',NULL,'Implicit Type 2: if there were even a modest increase... would translate.','medium'),
  (cid,54,191,'multiple_choice','Identify the IMPLICIT conditional in this sentence: "Better coordination among international actors would have prevented the humanitarian crisis."','This implies: "If there had been better coordination... the crisis would have been prevented" (Type 3).','["This implies: ''If there had been better coordination... the crisis would have been prevented'' (Type 3).","No conditional is present.","This is an explicit Type 2 conditional.","This implies a Type 1 conditional about future coordination."]','"Better coordination would have prevented" = implicit Type 3 (counterfactual about past).','medium'),

  -- BLOCK 55: TOEFL Reading avançado
  (cid,55,192,'multiple_choice','[TOEFL Reading] "Had governments taken bolder action in the 1990s, the current climate situation would be considerably less dire." This is:','A mixed conditional: Type 3 if-clause (past inaction) + Type 2 result (present consequence).','["A Type 1 conditional about real future possibilities","A Type 2 conditional about imaginary present","A mixed conditional: Type 3 if-clause (past inaction) + Type 2 result (present consequence).","A Type 3 conditional about a purely past outcome"]','Had + PP (past) → would be (present state) = classic mixed conditional.','hard'),
  (cid,55,193,'gap_fill','[TOEFL Reading] "If the early results _____ (not/dismiss/passive), the field _____ (develop) along a fundamentally different trajectory." Best Type 3 forms?','had not been dismissed / would have developed',NULL,'Type 3 passive if-clause + simple Type 3 result.','medium'),
  (cid,55,194,'multiple_choice','[TOEFL Reading] "A more flexible exchange rate regime would reduce the magnitude of current account imbalances." This implicit conditional says:','If a more flexible exchange rate regime existed, it would reduce imbalances.','["If a flexible regime had existed, it would have reduced imbalances (Type 3)","If a flexible regime exists, it will reduce imbalances (Type 1)","If a more flexible exchange rate regime existed, it would reduce imbalances.","Exchange rate flexibility reduced imbalances in the past."]','Implicit Type 2: "A more flexible regime would reduce" = if there were a more flexible regime.','hard'),

  -- BLOCK 56: TOEFL Speaking avançado
  (cid,56,195,'production','[TOEFL Speaking — 45s] A reading argues that introducing a universal basic income would reduce poverty. A lecture raises practical concerns. Use conditionals to summarize.','',NULL,'The reading argues that a universal basic income, if introduced at a sufficient level, would eliminate extreme poverty by providing every citizen with an unconditional income floor regardless of their employment status. The reading suggests that were this policy implemented, it would simultaneously reduce poverty, simplify the administrative complexity of existing welfare programs, and provide workers with greater bargaining power in labor markets. However, the lecture raises several serious practical objections. The professor argues that if a UBI were set high enough to provide a genuine income floor, the fiscal cost would be enormous — far exceeding the savings from consolidating existing programs. If the payment were set too low, on the other hand, it would not adequately replace the targeted support that the most vulnerable populations currently receive. The professor concludes that had proponents of UBI engaged more carefully with the fiscal arithmetic, they might have recognized that a targeted expansion of existing programs would be significantly more cost-effective at reducing poverty than a universal payment.','hard'),
  (cid,56,196,'production','[TOEFL Speaking — 45s] Discuss what would happen if fossil fuel subsidies were eliminated globally. Use Type 2 and Type 3 conditionals.','',NULL,'If fossil fuel subsidies, which currently amount to trillions of dollars annually worldwide when both direct and implicit subsidies are counted, were eliminated, the effects on both the energy transition and public finances would be substantial. If fossil fuels were no longer artificially cheap, renewable energy would be immediately cost-competitive in a much wider range of applications, accelerating the transition without requiring additional policy support. Governments that redirected the fiscal savings from subsidy elimination toward health, education, and targeted support for energy-poor households would find their social investment capacity significantly expanded. If this shift had occurred a decade ago, the current energy transition would be considerably further advanced. However, it should be acknowledged that eliminating subsidies would not be straightforward: if energy prices were to rise sharply in countries where low-income households spend a large share of their income on energy, the distributional consequences would be severe without compensating measures. A politically sustainable subsidy reform would need to be accompanied by robust social protection systems capable of preventing the burden of higher energy costs from falling disproportionately on those least able to bear them.','hard'),

  -- BLOCK 57: TOEFL Writing avançado
  (cid,57,197,'production','[TOEFL Writing — 200 words] Write a paragraph on education policy reform using conditionals throughout.','',NULL,'The persistent gaps in educational achievement between advantaged and disadvantaged students suggest that the current distribution of educational resources is fundamentally misaligned with equity objectives, and modeling how different allocation strategies would affect outcomes reveals significant untapped potential for reform. If resources were allocated inversely to existing advantage — channeling the highest per-pupil funding to schools serving the most disadvantaged communities — research evidence suggests that achievement gaps would narrow substantially. This does not happen at present: in many education systems, higher-income communities receive more educational resources both because local property taxes fund public schools and because parents with greater social capital are more effective at advocating for additional support. Had equitable funding formulas been adopted earlier and more consistently, the cohorts of students who experienced underfunded schooling would have entered the labor market with stronger skills and better life outcomes. If early childhood education were universally available at high quality, the research evidence on the returns to early intervention suggests that achievement gaps would diminish before children entered formal schooling. The political barriers to these reforms are not primarily technical: the communities whose children benefit from existing resource distributions are often the most politically mobilized, and building coalitions for equitable education funding requires addressing this structural imbalance in educational politics.','hard'),
  (cid,57,198,'production','[TOEFL Writing — 200 words] Write a paragraph on technology policy using conditionals to argue for stronger regulation.','',NULL,'The current regulatory framework governing digital technology companies is inadequate to the scale of the social and economic harms these companies can generate, and a credible case can be made that if stronger regulatory oversight had been established in the first decade of platform growth, many of the most serious problems now manifest — algorithmic amplification of extremist content, surveillance capitalism, and market concentration — would have been substantially mitigated. If antitrust enforcement had been applied more aggressively to platform acquisitions during the 2010s, several of the market concentration patterns that now appear extremely difficult to reverse without divestiture might have been avoided. Were data privacy regulations equivalent to the EU''s General Data Protection Regulation adopted earlier and more widely, the data extraction practices on which the current advertising model depends would have faced significant constraints that might have prompted earlier experimentation with less privacy-invasive business models. It is not possible to know with certainty what the technology landscape would look like if these regulatory choices had been made differently, but the trajectory that the unregulated development of the first two decades has produced is troubling enough to make the counterfactual worth considering seriously. If governments act now with the ambition the situation requires, many harmful outcomes can still be prevented or reversed — but the window for relatively low-cost intervention is closing as concentration deepens and path dependencies multiply.','hard'),

  -- BLOCK 58: Final
  (cid,58,199,'production','[TOEFL Writing — 200 words] Write a paragraph on public health preparedness using Type 2, Type 3, and mixed conditionals.','',NULL,'The COVID-19 pandemic provided a stark demonstration of what happens when public health preparedness investment is systematically underfunded, and the counterfactual analysis reveals both how much worse the pandemic could have been and how much better it would have been with better preparation. If national stockpiles of personal protective equipment had been maintained at the levels recommended by public health experts following the SARS outbreak of 2003, the catastrophic shortages that compromised the safety of healthcare workers in the early months of the pandemic would not have occurred. Had pandemic early warning systems in the international community been better funded and politically supported, the period between initial emergence and global spread might have been longer, providing more time for effective containment. The vaccine development platforms that were established for MERS and SARS proved critical for the rapid development of COVID-19 vaccines; if these platforms had not existed, the vaccine timelines would have been considerably longer. Were governments now to invest in the pandemic preparedness infrastructure that the evidence clearly justifies, the next pandemic — which virologists regard as a matter of when rather than if — would likely have less catastrophic consequences. The political challenge is that preparedness investment is invisible when it succeeds, which makes sustained public support for it structurally difficult to maintain between crises.','hard'),
  (cid,58,200,'production','[TOEFL Speaking — 60s] Discuss what the world would be like if the Paris Agreement had been more ambitious. Use Type 2 and Type 3 conditionals throughout.','',NULL,'The Paris Agreement, adopted in 2015, represented a significant diplomatic achievement in establishing a multilateral framework for climate action, but its ambition was constrained by what was politically achievable at the time rather than by what the science required. If the nationally determined contributions submitted under Paris were consistent with a 1.5°C pathway — rather than putting the world on a trajectory closer to 2.5-3°C of warming — the energy transition would be proceeding at a considerably more rapid pace. If the agreement had included binding emissions reduction targets rather than voluntary pledges, the accountability mechanisms would be stronger and the gap between pledges and action that has persisted since 2015 might have been smaller. Had major emitting countries committed to net zero by 2040 rather than 2050 or 2060, the investment signals to private capital would have been significantly stronger, and the scaling of clean energy technology would likely have proceeded faster. The world we would be living in if these more ambitious commitments had been made and kept would have somewhat less severe climate impacts to manage and a cleaner energy system further advanced. The core question is not what a more ambitious agreement would have produced in physical terms — the models are relatively clear on this — but whether a more demanding agreement would actually have been implemented, or whether it would have collapsed under political pressure as some previous more ambitious frameworks did before Paris was concluded.','hard'),
  (cid,58,201,'production','[TOEFL Writing — Final 200 words] Write a conclusion on economic inequality policy using all types of conditionals.','',NULL,'This essay has argued that the current trajectory of economic inequality, if allowed to continue, will generate compounding social and political costs that eventually undermine the growth and stability that market economies require to function. The analysis has also suggested that if the policy changes with the strongest evidence base — progressive wealth taxation, strengthening labor market institutions, and universal access to high-quality education and healthcare — were implemented at the necessary scale, inequality would decline significantly without compromising the dynamism and innovation that market economies generate. It is also instructive to consider what a different path might have produced: had the policy responses to the structural shifts of the 1980s been more focused on managing the distributional consequences of globalization and technological change, the political conditions that have enabled the rise of economic populism might have been considerably less favorable. If we were starting from a blank slate, the institutional design of market economies that the evidence supports would combine much stronger social insurance, more progressive taxation of wealth and inheritance, and robust institutions that give workers meaningful voice in economic governance. We are not starting from a blank slate, but the policy tools are available. The remaining question is whether the political coalitions required to deploy them can be built and sustained.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
