-- ============================================================
-- SEED EXT 2: Módulo 04 — Present Continuous (exercícios 71-185)
-- Novos tópicos: stative verbs dinâmicos, always/constantly
-- (irritating habits), passiva contínua, TOEFL produção
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'present-continuous';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo present-continuous não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 11: stative verbs used DYNAMICALLY (dual-use verbs)
  (cid,11,71,'multiple_choice','Which sentence uses "think" as a DYNAMIC (action) verb?','I''m thinking about applying for a research grant.','["I think the results are reliable (opinion = stative).","I''m thinking about applying for a research grant.","He thinks she is wrong (opinion = stative).","They think the data is complete."]','"Think" as dynamic = to consider/deliberate (use -ing). As stative = opinion (no -ing).','hard'),
  (cid,11,72,'gap_fill','The professor ___ (have) a meeting with the dean right now.','is having',NULL,'"Have" as dynamic = experience/hold a meeting (use -ing). Stative have = possession.','hard'),
  (cid,11,73,'multiple_choice','Choose the correct form: "She ___ the food in this restaurant — it''s amazing!" (dynamic "taste")','is tasting','["tastes","is tasting","tasted","taste"]','"Taste" as dynamic verb = to try/sample (use -ing). As stative = has a flavor (no -ing).','hard'),
  (cid,11,74,'gap_fill','I ___ (see) a therapist every Thursday. (meet regularly as a professional)','see',NULL,'"See" as stative here = have appointments with. "Am seeing" also widely accepted.','hard'),
  (cid,11,75,'multiple_choice','Which sentence uses a stative verb INCORRECTLY in continuous form?','The chef is smelling the soup. (to check) — CORRECT','["The soup smells delicious (stative — correct).","The chef is smelling the soup to check if it''s ready (dynamic — correct).","She is seeing her professor about the thesis (dynamic — correct).","He is knowing the answer (stative — INCORRECT)."]','"Know" cannot be used in continuous form — it is always stative.','hard'),
  (cid,11,76,'gap_fill','He ___ (weigh) the samples carefully in the lab right now.','is weighing',NULL,'"Weigh" as dynamic = to measure weight (use -ing). Stative: "it weighs 5kg."','hard'),
  (cid,11,77,'multiple_choice','In the sentence "She is being very difficult today," "being" is used because:','It describes temporary behavior, not a permanent characteristic.','["Be is always continuous","Difficult requires -ing","It describes temporary behavior, not a permanent characteristic.","She is always difficult"]','"Be" as dynamic: temporary behavior/attitude. "She is difficult" = permanent trait.','hard'),
  (cid,11,78,'gap_fill','You''re ___ (be) very generous today — thank you! (temporary behavior)','being',NULL,'"Being + adjective" = describing current, temporary behavior.','hard'),

  -- BLOCK 12: always/constantly/forever + present continuous (irritating habits)
  (cid,12,79,'multiple_choice','What does "He is always losing his keys" express?','A habitual, annoying behavior that the speaker finds frustrating.','["An action happening right now","A planned future event","A habitual, annoying behavior that the speaker finds frustrating.","A stative meaning of ''lose''"]','Always + present continuous = repeated behavior, often expressing irritation.','medium'),
  (cid,12,80,'gap_fill','She ___ always ___ (interrupt) during presentations — it''s so annoying!','is / interrupting',NULL,'"Is always + -ing" = habitual irritating behavior.','medium'),
  (cid,12,81,'multiple_choice','Which sentence uses "constantly" correctly with present continuous?','My roommate is constantly leaving the lights on all night.','["My roommate constantly leaves the lights on all night (simple present — habitual, no irritation implied).","My roommate is constantly leaving the lights on all night.","My roommate is always left the lights on.","My roommate constantly is leaving the lights on."]','"Is constantly + -ing" = habitual + annoying. "Constantly leaves" = just a habit.','hard'),
  (cid,12,82,'gap_fill','They ___ forever ___ (complain) about the quality of the teaching materials.','are / complaining',NULL,'"Are forever + -ing" = habitual, annoying/exaggerated behavior.','hard'),
  (cid,12,83,'multiple_choice','Which word does NOT collocate with present continuous to express habitual irritation?','sometimes','["always","constantly","forever","sometimes"]','"Sometimes" is neutral — it does not imply irritation. Always/constantly/forever do.','medium'),
  (cid,12,84,'gap_fill','He is always ___ (borrow) things without asking — it''s infuriating.','borrowing',NULL,'"Is always borrowing" = habitual annoying behavior.','easy'),
  (cid,12,85,'production','Write a sentence using "constantly" + present continuous to express an annoying habit of a colleague.','',NULL,'e.g. "My colleague is constantly interrupting me during meetings."','medium'),

  -- BLOCK 13: present continuous vs present simple in academic contexts
  (cid,13,86,'multiple_choice','[Academic] "The field ___ (change) rapidly due to new technological advances." Which tense best emphasizes ONGOING CHANGE?','is changing','["changes","is changing","changed","will change"]','"Is changing" = ongoing process happening now. "Changes" = general habitual fact.','medium'),
  (cid,13,87,'gap_fill','Current research ___ (suggest) a link between sleep deprivation and academic performance. (ongoing findings)','is suggesting / suggests',NULL,'Both can work: "suggests" = general truth; "is suggesting" = current emerging evidence.','hard'),
  (cid,13,88,'multiple_choice','Which sentence describes a TEMPORARY academic trend (not a permanent fact)?','Climate science is increasingly influencing public policy decisions.','["Scientific consensus accepts the validity of peer review.","Water contains two hydrogen atoms and one oxygen atom.","Climate science is increasingly influencing public policy decisions.","Universities require students to cite all sources."]','"Is increasingly influencing" = present continuous for ongoing, developing trend.','hard'),
  (cid,13,89,'gap_fill','More universities ___ (adopt) online learning platforms every semester. (growing trend)','are adopting',NULL,'"Are adopting" = gradual, ongoing change over time.','medium'),
  (cid,13,90,'multiple_choice','Why do academic writers sometimes use present continuous instead of present simple?','To highlight that a situation is changing or developing right now, rather than permanent.','["Present continuous is always more formal","Present simple is for past events","To highlight that a situation is changing or developing right now, rather than permanent.","They are interchangeable in all academic contexts"]','Present continuous signals change/process; present simple signals permanent truth.','hard'),

  -- BLOCK 14: passive present continuous
  (cid,14,91,'gap_fill','New data ___ (collect/passive) by the research team at this very moment.','is being collected',NULL,'Passive present continuous: is/are + being + past participle.','hard'),
  (cid,14,92,'multiple_choice','Choose the passive present continuous:','The results are being analyzed by the committee.','["The committee is analyzing the results (active).","The results have been analyzed by the committee (present perfect passive).","The results are being analyzed by the committee.","The results were analyzed by the committee (past passive)."]','Is/are + being + past participle = passive present continuous.','medium'),
  (cid,14,93,'gap_fill','Several new vaccines ___ (test/passive) in clinical trials around the world right now.','are being tested',NULL,'"Are being tested" = passive present continuous for ongoing process.','hard'),
  (cid,14,94,'multiple_choice','Which sentence uses passive present continuous correctly?','The bridge is being repaired; traffic is therefore being diverted.','["The bridge is being repair; traffic is diverted.","The bridge being repaired; traffic is being diverted.","The bridge is being repaired; traffic is therefore being diverted.","The bridge is been repaired; traffic is being diverted."]','Is + being + past participle (repaired/diverted).','medium'),
  (cid,14,95,'gap_fill','The ancient manuscripts ___ (preserve/passive) in a climate-controlled vault.','are being preserved',NULL,'Passive present continuous: are + being + past participle.','medium'),
  (cid,14,96,'multiple_choice','What does "The software is being updated" mean?','The update process is currently in progress.','["The software was updated recently","The software will be updated soon","The update process is currently in progress.","Someone usually updates the software"]','Is being + past participle = action in progress now (passive).','easy'),

  -- BLOCK 15: TOEFL Reading
  (cid,15,97,'multiple_choice','[TOEFL Reading] "Scientists are increasingly recognizing the role of gut bacteria in mental health." The present continuous here implies:','This is a growing, developing understanding — not yet a settled permanent fact.','["Scientists permanently know this","Scientists recognized this in the past","This is a growing, developing understanding — not yet a settled permanent fact.","Scientists are doing an experiment right now"]','"Increasingly + present continuous" = evolving trend or developing awareness.','hard'),
  (cid,15,98,'gap_fill','[TOEFL Reading] "Urban populations ___ (grow) at unprecedented rates, straining infrastructure worldwide." Best tense?','are growing',NULL,'"Are growing" = ongoing current global process.','medium'),
  (cid,15,99,'multiple_choice','[TOEFL Reading] A passage states: "More companies are adopting sustainable practices." This means:','The adoption of sustainable practices is an ongoing, current trend.','["Companies always adopt sustainable practices","Companies adopted sustainable practices in the past","The adoption of sustainable practices is an ongoing, current trend.","Companies will adopt sustainable practices in the future"]','"Are adopting" = present continuous for current/developing trend.','medium'),
  (cid,15,100,'gap_fill','[TOEFL Reading] "Researchers ___ (uncover/passive) new evidence that challenges the dominant paradigm." Best form?','are uncovering / are having uncovered',NULL,'"Are uncovering" = active present continuous. "Is being uncovered" = passive present continuous.','hard'),
  (cid,15,101,'multiple_choice','[TOEFL Reading] Why does an academic text use "is shifting" instead of "shifts" when describing a social trend?','To emphasize that the shift is currently in progress and not yet complete.','["Shifts is grammatically incorrect","Is shifting is always required in academic writing","To emphasize that the shift is currently in progress and not yet complete.","They mean exactly the same thing"]','"Is shifting" emphasizes active, incomplete change; "shifts" = general/habitual.','hard'),

  -- BLOCK 16: TOEFL Listening
  (cid,16,102,'multiple_choice','[TOEFL Listening] A professor says: "As we''re seeing in today''s graphs, sea levels are rising faster than predicted." The phrase "we''re seeing" suggests:','The professor is directing attention to data being observed in real time.','["We observed this in the past","We will see this in the future","The professor is directing attention to data being observed in real time.","We is a grammatical error"]','"We''re seeing" = present continuous for real-time observation during the lecture.','medium'),
  (cid,16,103,'gap_fill','[TOEFL Listening] A student asks: "Why ___ more universities ___ (adopt) blended learning?" Complete the question.','are / adopting',NULL,'Present continuous question: why + are/is + subject + -ing?','easy'),
  (cid,16,104,'multiple_choice','[TOEFL Listening] "Technology companies are constantly disrupting traditional business models." The word "constantly" here implies:','The disruption is habitual and happening with high frequency.','["The disruption happened once","The disruption will happen eventually","The disruption is habitual and happening with high frequency.","The speaker approves of the disruption"]','"Are constantly + -ing" = high-frequency, ongoing habitual disruption.','medium'),

  -- BLOCK 17: TOEFL Speaking production
  (cid,17,105,'production','[TOEFL Speaking — 45s] Describe what is happening in your university or workplace right now, this semester, or this year. Use present continuous for: (1) something happening right now, (2) a temporary situation this term, (3) a growing trend.','',NULL,'Right now, students are preparing for final exams. This semester, our department is piloting a new online learning platform. More professors are adopting project-based assessment methods.','medium'),
  (cid,17,106,'production','[TOEFL Speaking — 45s] A passage says that cities are changing rapidly. Describe 3 specific ways cities are changing, using present continuous for each. Include one passive present continuous.','',NULL,'Cities are expanding outward into previously rural areas. Public transport systems are being upgraded to reduce carbon emissions. Meanwhile, more residents are choosing to cycle rather than drive.','hard'),
  (cid,17,107,'production','[TOEFL Speaking — 45s] Talk about a person you know who has an annoying habit. Use always/constantly/forever + present continuous in at least 2 sentences.','',NULL,'My brother is always leaving his dishes in the sink. He is constantly borrowing things without asking and forgetting to return them.','easy'),
  (cid,17,108,'production','[TOEFL Speaking — 45s] Compare what "scientists say" (permanent facts) vs. what "scientists are discovering" (current research). Use both present simple and present continuous in your response.','',NULL,'Scientists say that human activity contributes significantly to climate change. However, they are currently discovering that the rate of permafrost thaw is accelerating faster than models predicted. New data are being collected every month in Arctic monitoring stations.','hard'),

  -- BLOCK 18: TOEFL Writing production
  (cid,18,109,'production','[TOEFL Writing] Write 5 sentences about current trends in education using present continuous. Include: one passive, one with "increasingly," one with "constantly," one about a temporary situation, one about a future arrangement.','',NULL,'Educational institutions are increasingly adopting AI tools for personalized learning. Traditional curricula are being redesigned to include digital competencies. Some students are constantly struggling to keep up with the pace of technological change. This semester, many universities are piloting hybrid lecture formats. Next year, our institution is launching a fully online degree program.','hard'),
  (cid,18,110,'production','[TOEFL Writing — Error Correction] Fix all errors: "Scientists are knowing that climate change is worsening. The situation is getting more serious every year. More data is being collected currently. Governments is considering new policies right now."','',NULL,'know (stative — remove -ing); getting = correct; is being collected = correct (move "currently" to end or remove); are considering (plural: governments).','hard'),
  (cid,18,111,'production','[TOEFL Writing — 150 words] Write a paragraph on the topic "How is technology changing the way we work?" Use at least 5 present continuous verbs (including 2 passive). Vary structure: affirmative, negative, question.','',NULL,'Technology is fundamentally transforming the modern workplace. Remote work tools are being adopted by companies of all sizes, enabling employees to collaborate across continents. Traditional office jobs are disappearing as automation takes over routine tasks. However, new roles are emerging that require advanced digital skills. Are organizations providing sufficient training for this transition? Many are not. Workers are constantly adapting to new software, platforms, and workflows. Meanwhile, the boundary between professional and personal time is blurring. Unless steps are taken to support workers through this shift, productivity and well-being will suffer.','hard'),

  -- BLOCK 19: mixed review and error correction
  (cid,19,112,'multiple_choice','Which sentence has an error?','She is always loosing her notes before the exam.','["The team is currently analyzing the data.","She is always loosing her notes before the exam.","New treatments are being tested in clinical trials.","She is having a meeting with her supervisor."]','"Loosing" is wrong — correct spelling is "losing."','medium'),
  (cid,19,113,'gap_fill','The amount of data available to researchers ___ (increase) exponentially every year. (ongoing trend)','is increasing',NULL,'"Is increasing" for ongoing, accelerating trend.','easy'),
  (cid,19,114,'multiple_choice','Choose the correct present continuous passive: "Several new species ___ in the Amazon every year."','are being discovered','["are discovered","have been discovered","are being discovered","were discovered"]','"Are being discovered" = passive present continuous (ongoing discovery process).','medium'),
  (cid,19,115,'gap_fill','I ___ (not/think) of quitting — I''m making great progress! (dynamic think = consider)','am not thinking',NULL,'Dynamic "think" = to consider/deliberate → present continuous negative.','hard'),
  (cid,19,116,'multiple_choice','A student writes: "Researchers are knowing more about the human brain than ever before." What is wrong?','Know is a stative verb and cannot be used in continuous form.','["Researchers should be scientists","Brain should be brains","Know is a stative verb and cannot be used in continuous form.","Than ever before should be than always"]','"Know" = stative. Correct: "Researchers know more about the human brain than ever before."','medium'),

  -- BLOCK 20: advanced synthesis
  (cid,20,117,'production','[TOEFL Writing — Capstone] Write a 150-word academic paragraph on climate change. You must include: (1) a present simple for a permanent scientific fact, (2) a present continuous for an ongoing trend, (3) a passive present continuous for a current process, (4) an always/constantly structure for a problematic pattern, and (5) a present continuous for a future arrangement.','',NULL,'Scientific consensus confirms that CO₂ absorbs infrared radiation, trapping heat in the atmosphere. Global temperatures are rising at an accelerating rate, threatening ecosystems worldwide. Meanwhile, new renewable energy infrastructure is being built across six continents. Yet policymakers are constantly underestimating the urgency of the crisis, slowing meaningful action. Next month, world leaders are meeting at a UN climate summit to finalize new emission targets. If bold commitments are made and followed through, there is still a window to limit warming to 1.5°C.','hard'),
  (cid,20,118,'multiple_choice','[TOEFL] Which response BEST uses present continuous to answer "What changes are occurring in global food systems?"','Food systems are being restructured as climate change disrupts traditional agricultural zones. Moreover, consumers are increasingly demanding plant-based alternatives, and new farming technologies are being developed to meet this shift.','["Food systems change as climate changes.","Food systems have changed significantly in recent decades.","Food systems are being restructured as climate change disrupts traditional agricultural zones. Moreover, consumers are increasingly demanding plant-based alternatives, and new farming technologies are being developed to meet this shift.","Food systems will change in the future because of climate change."]','Best uses: passive present continuous (are being restructured/developed) + active continuous (are demanding) + "increasingly."','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
