-- ============================================================
-- SEED EXT 2: Módulo 07 — Present Perfect (exercícios 71-185)
-- Novos tópicos: Present Perfect Continuous, recently/lately,
-- how long questions, academic passive PP, PP vs PP Continuous
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'present-perfect';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo present-perfect não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 11: Present Perfect Continuous — have/has been + -ing
  (cid,11,71,'gap_fill','She ___ (study) for the TOEFL for six months and is now very well prepared.','has been studying',NULL,'Present perfect continuous: has/have + been + -ing for ongoing action with duration.','medium'),
  (cid,11,72,'multiple_choice','Choose the correct Present Perfect Continuous:','They have been conducting research on this phenomenon since 2018.','["They have conducted research since 2018 (PP — result focus).","They are conducting research since 2018 (wrong — since requires PP).","They have been conducting research on this phenomenon since 2018.","They were conducting research since 2018 (past continuous — wrong)."]','Have been + -ing + since = PP Continuous for ongoing activity.','medium'),
  (cid,11,73,'gap_fill','He looks exhausted — he ___ (work) on his dissertation all night.','has been working',NULL,'Evidence of ongoing activity (looks exhausted) → PP Continuous.','medium'),
  (cid,11,74,'gap_fill','The team ___ (develop) the vaccine for three years and is close to completion.','has been developing',NULL,'"For three years" with an ongoing process → PP Continuous.','medium'),
  (cid,11,75,'multiple_choice','Which sentence focuses on the RESULT (not the process)?','She has written three chapters of her thesis.','["She has been writing her thesis for six months (process/duration).","She has written three chapters of her thesis.","She has been reading the article (process).","She has been studying all morning (process/duration)."]','Present perfect simple → completed result (three chapters done).','hard'),
  (cid,11,76,'gap_fill','I ___ (wait) for the peer review response for four months — it''s taking forever!','have been waiting',NULL,'PP Continuous for ongoing, frustrating wait with "for" + duration.','medium'),
  (cid,11,77,'multiple_choice','What does "The experiment has been running for 72 hours" emphasize?','The ongoing, continuous nature of the experiment up to now.','["The experiment is now finished","The experiment ran 72 hours ago","The ongoing, continuous nature of the experiment up to now.","The experiment ran for exactly 72 hours in the past"]','Has been + -ing = still happening, duration emphasized.','medium'),

  -- BLOCK 12: PP vs PP Continuous — result vs process
  (cid,12,78,'multiple_choice','Which pair correctly contrasts Present Perfect and Present Perfect Continuous?','I have read the report. (done) / I have been reading the report. (still reading or evidence of effort)','["I have read. (ongoing) / I have been reading. (done)","I have read the report. (done) / I have been reading the report. (still reading or evidence of effort)","They are interchangeable — no difference","I have been reading = I just finished reading"]','PP = completed/result. PP Continuous = ongoing process or recent activity.','hard'),
  (cid,12,79,'gap_fill','Her eyes are red — she ___ (cry).','has been crying',NULL,'Physical evidence of recent continuous activity → PP Continuous.','medium'),
  (cid,12,80,'multiple_choice','Choose the BEST form: "Don''t move those papers — I ___ them."','have been organizing','["have organized (implies finished — but they''re still on the desk)","was organizing","am organizing","have been organizing"]','PP Continuous stresses that the activity is still in progress (don''t disturb).','hard'),
  (cid,12,81,'gap_fill','The lab ___ (develop) a new antibiotic that shows promising results. (completed development — result matters)','has developed',NULL,'PP Simple = result focus: the antibiotic exists now (completed).','hard'),
  (cid,12,82,'multiple_choice','Which sentence uses PP vs PP Continuous CORRECTLY?','I have been learning Portuguese for two years, but I haven''t mastered it yet.','["I have been mastering Portuguese for two years. (stative — wrong with continuous)","I have learned Portuguese for two years (wrong — for + ongoing → PP Continuous preferred).","I have been learning Portuguese for two years, but I haven''t mastered it yet.","I have been knowing Portuguese for two years (stative verb — wrong)."]','Have been learning (process) vs haven''t mastered (result).','hard'),
  (cid,12,83,'gap_fill','Scientists ___ (attempt) to solve this problem since the 1980s without success.','have been attempting',NULL,'"Since the 1980s" + ongoing failed attempts → PP Continuous.','medium'),
  (cid,12,84,'multiple_choice','Which stative verb CANNOT be used in PP Continuous?','know','["write","run","study","know"]','"Know" is stative — cannot take -ing in any tense (have been knowing = wrong).','hard'),

  -- BLOCK 13: recently/lately/in recent years
  (cid,13,85,'gap_fill','___ (recently), several studies ___ (emerge) challenging the traditional model.','Recently / have emerged',NULL,'"Recently" = indefinite past connected to present → present perfect.','medium'),
  (cid,13,86,'multiple_choice','Which time expression requires Present Perfect?','lately','["yesterday","last year","in 2019","lately"]','"Lately" = during a recent period up to now → Present Perfect (not past simple).','medium'),
  (cid,13,87,'gap_fill','Researchers ___ (observe) a significant increase in ocean temperatures ___ (lately).','have observed / lately',NULL,'"Have observed lately" = present perfect with "lately" at end.','medium'),
  (cid,13,88,'multiple_choice','Choose the correct sentence:','In recent years, artificial intelligence has transformed the healthcare industry.','["In recent years, artificial intelligence transformed the healthcare industry (past simple — wrong for still-ongoing).","In recent years, artificial intelligence has transformed the healthcare industry.","In recent years, artificial intelligence is transforming the healthcare industry.","In recent years, artificial intelligence transforms the healthcare industry."]','"In recent years" + present perfect for developments from recent past to now.','medium'),
  (cid,13,89,'gap_fill','___ (late) the team ___ (focus) on improving the model''s accuracy.','Lately / has been focusing',NULL,'"Lately" → PP Continuous (ongoing recent activity).','hard'),
  (cid,13,90,'multiple_choice','Which sentence is INCORRECT?','She has worked here yesterday.','["She has worked here for five years.","She has recently published a new paper.","She has worked here since 2019.","She has worked here yesterday."]','"Yesterday" = specific past time → past simple (worked, not has worked).','medium'),

  -- BLOCK 14: How long questions
  (cid,14,91,'gap_fill','___ ___ ___ (how long/you/study) English?','How long have you studied / been studying',NULL,'"How long have you + past participle / been + -ing?" for duration.','medium'),
  (cid,14,92,'multiple_choice','Which question form is correct?','How long has she been working on her dissertation?','["How long she has been working on her dissertation?","How long has she been working on her dissertation?","How long is she working on her dissertation?","How long did she work on her dissertation? (past — implies finished)"]','"How long has + subject + been + -ing?" for ongoing duration.','medium'),
  (cid,14,93,'gap_fill','A: "___ ___ ___ (how long/they/live) in this city?" B: "They have lived here ___ 2010."','How long have they lived / since',NULL,'"How long have they lived" + "since" (specific year).','medium'),
  (cid,14,94,'multiple_choice','Choose the natural response to "How long have you been a professor?"','I have been a professor for fifteen years.','["I am a professor for fifteen years.","I have been a professor since fifteen years.","I was a professor for fifteen years.","I have been a professor for fifteen years."]','"Have been + for" + period of time.','easy'),
  (cid,14,95,'gap_fill','___ ___ the research institute ___ (operate) in this location?','How long has / been operating',NULL,'How long has + subject + been + -ing?','medium'),
  (cid,14,96,'multiple_choice','A student asks the right question about duration. Which is correct?','How long have scientists been studying the effects of microplastics?','["How long scientists have been studying microplastics?","How long did scientists study microplastics?","How long have scientists been studying the effects of microplastics?","Since how long have scientists studied microplastics?"]','How long + have/has + subject + been + -ing?','medium'),

  -- BLOCK 15: academic passive Present Perfect
  (cid,15,97,'gap_fill','The relationship between sleep and cognitive performance ___ (demonstrate/passive) in multiple studies.','has been demonstrated',NULL,'"Has been + past participle" = passive present perfect for academic findings.','hard'),
  (cid,15,98,'multiple_choice','Which sentence uses passive Present Perfect correctly in academic writing?','It has been argued that economic growth alone does not reduce inequality.','["It has been argued that economic growth alone does not reduce inequality.","It was argued that economic growth does not reduce inequality (past simple = specific time reference).","It is argued that economic growth has been not reducing inequality.","Economic growth does not reduce inequality has been argued."]','It has been argued = impersonal passive PP for introducing academic arguments.','hard'),
  (cid,15,99,'gap_fill','A link between air pollution and neurological disorders ___ (establish/passive) by recent research.','has been established',NULL,'Passive PP: has been + past participle.','hard'),
  (cid,15,100,'multiple_choice','Why is passive Present Perfect common in academic writing?','It focuses on the finding rather than the researchers, making claims more objective.','["It is easier to write","It avoids using past simple","It focuses on the finding rather than the researchers, making claims more objective.","It is required by most journals"]','Impersonal passive PP = objective, formal academic register.','hard'),
  (cid,15,101,'gap_fill','It ___ (suggest/passive) that biodiversity loss may trigger cascade effects across ecosystems.','has been suggested',NULL,'"It has been suggested that" = impersonal passive PP for hedged academic claim.','hard'),
  (cid,15,102,'multiple_choice','Which sentence has the MOST formal academic register for reporting a finding?','It has been demonstrated that vitamin D deficiency correlates with increased risk of depression.','["Researchers found vitamin D deficiency causes depression.","We found that vitamin D deficiency correlates with depression.","It has been demonstrated that vitamin D deficiency correlates with increased risk of depression.","The study found that vitamin D makes people depressed."]','Impersonal passive PP + hedged language (correlates with, risk of) = formal academic.','hard'),

  -- BLOCK 16: TOEFL Reading
  (cid,16,103,'multiple_choice','[TOEFL Reading] "Scientists have long suspected that gut bacteria influence mood." The present perfect here indicates:','This suspicion existed in the past and is still relevant today.','["This was a past belief that has been disproven","Scientists are currently testing this for the first time","This suspicion existed in the past and is still relevant today.","Scientists are just beginning to study this area"]','"Have long suspected" = PP for a state from past to present.','medium'),
  (cid,16,104,'gap_fill','[TOEFL Reading] "The Arctic ice sheet ___ (shrink) by approximately 13% per decade since satellite measurements began." Best tense?','has been shrinking',NULL,'Ongoing process since a specific point → PP Continuous.','hard'),
  (cid,16,105,'multiple_choice','[TOEFL Reading] "Several competing theories have been proposed to explain the extinction event." This passive PP means:','Multiple theories exist and are still being evaluated now.','["The theories were proposed and then rejected","One theory was just proposed","Multiple theories exist and are still being evaluated now.","Researchers proposed theories a long time ago but forgot them"]','Have been proposed = passive PP; still relevant to current scientific debate.','medium'),
  (cid,16,106,'gap_fill','[TOEFL Reading] "The study''s findings ___ (not/replicate) by subsequent research." Best tense?','have not been replicated',NULL,'Passive PP negative: have not been + past participle.','hard'),
  (cid,16,107,'multiple_choice','[TOEFL Reading] In academic texts, "It has been noted that..." introduces a claim because:','It signals that this observation is an established, accepted part of the literature.','["It is more interesting than active voice","It shows the author''s personal opinion","It signals that this observation is an established, accepted part of the literature.","It avoids naming specific researchers"]','Impersonal passive PP = established fact in academic discourse.','hard'),

  -- BLOCK 17: TOEFL Listening
  (cid,17,108,'multiple_choice','[TOEFL Listening] A professor says: "As I''ve been explaining throughout this course, language acquisition is not simply a matter of memorization." "I''ve been explaining" signals:','The professor has been teaching this idea across multiple sessions.','["The professor just explained this","The professor is starting to explain now","The professor has been teaching this idea across multiple sessions.","The professor is confused about the topic"]','Has been explaining = PP Continuous for ongoing repeated activity.','medium'),
  (cid,17,109,'gap_fill','[TOEFL Listening] A student reports: "The professor mentioned that scientists ___ (collect) data on this for over 20 years." Best form in reported context?','have been collecting / had been collecting',NULL,'PP Continuous (or past perfect continuous in reported speech) for 20-year ongoing process.','hard'),
  (cid,17,110,'multiple_choice','[TOEFL Listening] "The investment in renewable energy has surged since 2015." The word "surged" is in present perfect because:','The increase started in 2015 and continues to affect the present.','["The investment happened in 2015 and ended","The investment will happen after 2015","The increase started in 2015 and continues to affect the present.","Surge requires present perfect grammar"]','"Since" signals connection between past event and present → PP.','easy'),

  -- BLOCK 18: TOEFL Speaking production
  (cid,18,111,'production','[TOEFL Speaking — 45s] Talk about how your understanding of a subject has changed over time. Use present perfect simple for results and present perfect continuous for ongoing processes. Include: have learned, have been studying, has changed, have discovered.','',NULL,'I have been studying English for five years. Over this time, I have learned that language acquisition requires consistent daily practice. My writing skills have improved significantly. I have discovered that reading academic texts has been the most effective method for expanding my vocabulary.','medium'),
  (cid,18,112,'production','[TOEFL Speaking — 45s] Summarize recent advances in a field you know (technology, medicine, environment). Use: has been shown, has been developed, have been discovered, has grown, has become.','',NULL,'Scientists have recently developed mRNA vaccines that have shown remarkable efficacy. Several new treatments for antibiotic-resistant infections have been discovered. Public interest in precision medicine has grown exponentially. Genetic sequencing has become affordable enough for widespread clinical use.','hard'),
  (cid,18,113,'production','[TOEFL Speaking — 45s] A professor claims that digital literacy has become the most important 21st-century skill. Agree or disagree using present perfect and present perfect continuous.','',NULL,'I agree with this claim. Digital technologies have transformed virtually every professional field. Students who have developed strong digital skills have gained a significant competitive advantage. Educational institutions have been adapting their curricula to address this need, though progress has been uneven. Governments have also begun investing in digital literacy programs for adults.','hard'),

  -- BLOCK 19: TOEFL Writing production
  (cid,19,114,'production','[TOEFL Writing] Write a 5-sentence paragraph about advances in climate science using: has been discovered, have been collecting, has shown, have become, has been suggested.','',NULL,'Scientists have been collecting climate data for over a century, revealing accelerating warming trends. New research has shown that the rate of Arctic melting has doubled since 2000. It has been suggested that we may reach critical tipping points earlier than previously estimated. Renewable energy technologies have become significantly more affordable in the past decade. Several countries have introduced carbon pricing systems that have been shown to reduce emissions effectively.','hard'),
  (cid,19,115,'production','[TOEFL Writing — Error Correction] Fix all present perfect errors: "Scientists have discover many new species in the Amazon. They collected data since 2015. Recently, deforestation has became a major concern. No solution has found yet. Researchers have been study the issue for years."','',NULL,'have discovered; have been collecting data since 2015; has become; has been found / no solution has been found; have been studying.','hard'),
  (cid,19,116,'production','[TOEFL Writing — 150 words] Write a paragraph on the topic "How has globalization changed the world economy?" Use: at least 3 present perfect simple verbs, 2 present perfect continuous verbs, 1 passive present perfect, and 1 "in recent years/recently" phrase. Underline each present perfect verb.','',NULL,'Globalization has fundamentally altered the structure of the world economy over the past century. International trade has grown by more than 1,000% since 1950, connecting markets that were once isolated. In recent years, emerging economies have played an increasingly central role in global production. Supply chains have been restructured to take advantage of cheaper labor and raw materials across the world. Meanwhile, multinational corporations have been shifting manufacturing to developing nations, raising both economic opportunities and ethical questions. At the same time, technological innovation has been accelerating the pace of economic integration. However, inequality between and within nations has also increased, suggesting that the benefits of globalization have not been distributed equitably.','hard'),

  -- BLOCK 20: advanced review
  (cid,20,117,'multiple_choice','[TOEFL] Which sentence BEST demonstrates academic present perfect usage?','It has been established that early childhood nutrition significantly influences long-term cognitive development.','["Researchers established early childhood nutrition influences cognition in 2019 (past simple, specific time).","It was established that early childhood nutrition influences cognition (passive past — specific time implied).","It has been established that early childhood nutrition significantly influences long-term cognitive development.","Researchers have established early childhood nutrition influences cognition (active, acceptable)."]','Impersonal passive PP + academic hedging = most formal register.','hard'),
  (cid,20,118,'production','[TOEFL Writing — Capstone] Write a 200-word academic paragraph about the impact of social media on political discourse. Include: 4 present perfect simple verbs, 2 present perfect continuous verbs, 1 passive present perfect, 1 "lately/recently/in recent years" phrase, and 1 "how long" structure. Every PP verb must be grammatically correct.','',NULL,'Social media has fundamentally changed the way political information is communicated and consumed. In recent years, platforms such as X and Instagram have become primary sources of political news for millions of citizens. Algorithms have amplified extreme content, contributing to the fragmentation of public discourse. Meanwhile, disinformation has spread at unprecedented rates, undermining trust in democratic institutions. Researchers have been studying this relationship for over a decade, and have found consistent evidence linking social media use to increased political polarization. It has also been demonstrated that targeted advertising enables political actors to exploit voter psychology with disturbing precision. Over the past decade — a period in which these platforms have been operating at scale — civic discourse has deteriorated in many democracies. The question of how long governments will delay comprehensive regulation is now critical.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
