-- ============================================================
-- SEED EXT 6: Módulo 24 — Discourse Markers (ex 215-300)
-- Blocos 71-80 | 86 exercícios
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'discourse-markers';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo discourse-markers não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 71: Contrast markers — however/nevertheless/nonetheless/by contrast (9 ex)
  (cid,71,215,'gap_fill','The initial findings appeared promising; _____, subsequent analysis revealed significant methodological limitations that cast doubt on the reliability of the conclusions.','however',NULL,'"However" introduces a contrast/contradiction after a semicolon. Formal academic adversative marker.','easy'),
  (cid,71,216,'gap_fill','The reform produced measurable short-term gains in administrative efficiency. _____, the longer-term effects on service quality remain uncertain and are the subject of ongoing debate.','Nevertheless',NULL,'"Nevertheless" = despite what was just said, the following is true. Stronger concessive force than "however."','easy'),
  (cid,71,217,'gap_fill','Critics argued that the evidence was insufficient to support the proposed intervention. The government proceeded _____, citing the urgency of the public health situation as justification for acting on incomplete information.','nonetheless',NULL,'"Nonetheless" = despite those objections/considerations. Emphasizes continuation of action despite stated obstacle.','medium'),
  (cid,71,218,'gap_fill','In developed economies, institutional reform tends to proceed incrementally through established legislative channels. _____, in transition economies, reform is often driven by external pressure and implemented through executive decree.','By contrast',NULL,'"By contrast" introduces a sharply contrasting alternative situation — formal, academic, paragraph-opening marker.','medium'),
  (cid,71,219,'gap_fill','The quantitative analysis yielded statistically significant results across all specifications; _____, the effect sizes were modest enough to raise questions about the practical significance of the findings.','however',NULL,'"However" after semicolon signals that what follows qualifies or contradicts the initial claim.','easy'),
  (cid,71,220,'gap_fill','Democratic systems tend to prioritize consensus-building and consultation in policy design. Authoritarian systems, _____, are more likely to implement reform rapidly through top-down directive.','by contrast',NULL,'"By contrast" in the middle or end of a sentence contrasting the subject with an alternative; note lowercase when mid-sentence.','medium'),
  (cid,71,221,'gap_fill','The proposed mechanism failed to achieve its stated objectives in the first two years of implementation. _____, the evaluation team recommended continuing the program on the grounds that early failure is not always predictive of long-term outcomes.','Nevertheless',NULL,'"Nevertheless" signals that the recommendation persists despite the negative evaluation evidence.','medium'),
  (cid,71,222,'gap_fill','Much of the literature assumes that more accountability leads to better governance outcomes. The available evidence, _____, is considerably more mixed, suggesting that the relationship is moderated by a range of contextual factors.','however',NULL,'"However" mid-sentence (between commas) signals the contrast without starting a new sentence — sophisticated academic style.','hard'),
  (cid,71,223,'multiple_choice','Which sentence uses a contrast discourse marker MOST effectively in academic writing?','The theoretical model predicts a positive relationship between institutional quality and economic growth; however, the empirical evidence from transition economies reveals a more ambiguous picture.','["The theoretical model predicts growth but evidence is ambiguous.","The theoretical model predicts a positive relationship between institutional quality and economic growth; however, the empirical evidence from transition economies reveals a more ambiguous picture.","However, the evidence is mixed although the model predicts growth.","The theoretical model predicts growth. But the evidence is mixed."]','Option B: "however" after semicolon, followed by precise qualification — formal academic contrast. "But" (D) is too informal; "Although" (C) misplaces the concessive.','medium'),

  -- BLOCK 72: Addition markers — moreover/furthermore/in addition/what is more (9 ex)
  (cid,72,224,'gap_fill','The reform reduced administrative costs by seventeen percent. _____, it significantly improved the consistency and predictability of regulatory decisions across the sector.','Moreover',NULL,'"Moreover" = and in addition, more importantly. Additive marker with upward scalar force — what follows is more significant than what preceded.','easy'),
  (cid,72,225,'gap_fill','The study demonstrates a robust correlation between governance quality and investment flows. _____, it provides evidence that the relationship holds across a range of different institutional contexts and time periods.','Furthermore',NULL,'"Furthermore" = in addition (formal). Adds an elaboration or extension of the preceding point.','easy'),
  (cid,72,226,'gap_fill','The proposed framework addresses the technical dimensions of the reform challenge. _____, it provides a practical mechanism for stakeholder consultation that previous frameworks had neglected.','In addition',NULL,'"In addition" = additive discourse marker (less scalar than "moreover" but equally formal in academic writing).','easy'),
  (cid,72,227,'gap_fill','The intervention produced measurable improvements in service delivery. _____, the cost-per-outcome ratio compared favorably with alternative approaches that had been considered during the design phase.','What is more',NULL,'"What is more" = furthermore/moreover — colloquially additive but used in academic writing for emphasis; note capital W at sentence start.','medium'),
  (cid,72,228,'gap_fill','The analysis reveals significant variation in reform outcomes across countries. _____, this variation is not random but is systematically associated with differences in initial institutional endowments.','Moreover',NULL,'"Moreover" adds a more significant point: not only is there variation, but it is structured/predictable.','medium'),
  (cid,72,229,'gap_fill','The framework successfully integrates insights from multiple disciplinary traditions. _____, its modular structure allows it to be adapted to a wide range of empirical contexts without requiring fundamental revision.','Furthermore',NULL,'"Furthermore" extends the evaluative point: not only integrates traditions, but also is adaptable.','medium'),
  (cid,72,230,'gap_fill','The findings replicate those of earlier studies conducted in other regional contexts. _____, they extend the literature by demonstrating that the effect persists even when controlling for previously unexamined confounders.','Moreover',NULL,'"Moreover" here carries scalar force: not just replication, but extension of knowledge — the second point is epistemically richer.','hard'),
  (cid,72,231,'gap_fill','The proposed intervention is technically feasible and cost-effective. _____, it has strong stakeholder support, which is often the critical factor in determining whether reforms are successfully implemented.','What is more',NULL,'"What is more" = and indeed even more importantly; signals the politically decisive consideration after the technical one.','hard'),
  (cid,72,232,'multiple_choice','Which additive discourse marker carries the STRONGEST implication that the second point is more significant than the first?','Moreover','["In addition","Furthermore","Moreover","Additionally"]','Option C: "Moreover" typically signals that what follows is not merely additional but more important/weighty. "Furthermore" and "in addition" are more neutral; "additionally" is the weakest.','medium'),

  -- BLOCK 73: Causal markers — therefore/thus/hence/consequently/as a result (9 ex)
  (cid,73,233,'gap_fill','The sample size was insufficient to detect effects of the magnitude observed in previous studies; _____, the failure to replicate earlier findings cannot be interpreted as evidence that those effects do not exist.','therefore',NULL,'"Therefore" = logical conclusion/inference from the preceding. Formal academic deductive marker.','easy'),
  (cid,73,234,'gap_fill','The consultation process was conducted under significant time pressure and lacked adequate provision for minority voices. _____, the legitimacy of the resulting decisions has been contested by several affected communities.','Consequently',NULL,'"Consequently" = as a direct result/consequence. Causal-resultative; more explicit about cause-effect than "therefore."','easy'),
  (cid,73,235,'gap_fill','The theoretical framework predicts that organizations operating in competitive markets will develop stronger accountability mechanisms. _____, we would expect to observe a positive correlation between market competition and governance quality.','Thus',NULL,'"Thus" = therefore (formal, slightly archaic but highly academic). Signals a logical consequence or inference.','medium'),
  (cid,73,236,'gap_fill','The institutional environment changed significantly during the period under study. _____, comparisons of governance outcomes across the full time series must be interpreted with considerable caution.','Hence',NULL,'"Hence" = therefore (formal, academic). Often used in academic writing to signal inference or recommendation.','medium'),
  (cid,73,237,'gap_fill','The reform failed to secure the support of key bureaucratic actors during the design phase. _____, implementation proceeded slowly and unevenly across the different agencies responsible for delivering the new regulatory framework.','As a result',NULL,'"As a result" = causal-resultative marker (more concrete than "therefore"; emphasizes the effect rather than the logical inference).','easy'),
  (cid,73,238,'gap_fill','The available evidence does not permit strong causal claims about the mechanisms linking governance quality to development outcomes; _____, this analysis is limited to establishing correlation and to identifying plausible mediating pathways.','therefore',NULL,'"Therefore" signals that the methodological limitation directly determines the scope of the claims the paper can make.','medium'),
  (cid,73,239,'gap_fill','The data collection was disrupted by the political crisis of 2019–2020, resulting in a gap in the time series for several key variables. _____, the analysis for this period relies on interpolated rather than directly observed values.','Consequently',NULL,'"Consequently" emphasizes that the disruption directly caused the methodological workaround.','medium'),
  (cid,73,240,'gap_fill','The theoretical model assumes that actors are rational and well-informed; _____, it is likely to underestimate the role of cognitive biases and information asymmetries in shaping actual governance behavior.','hence',NULL,'"Hence" mid-consequence: because of this assumption, the following limitation follows logically.','hard'),
  (cid,73,241,'multiple_choice','Which causal discourse marker MOST directly signals a logical inference rather than an empirical consequence?','Thus','["As a result","Consequently","Thus","Due to this"]','Option C: "Thus" and "hence" signal logical/deductive inference from premises. "As a result" and "consequently" signal empirical causal consequence. "Due to this" is informal.','medium'),

  -- BLOCK 74: Concessive markers — although/while/whereas/even though (9 ex)
  (cid,74,242,'gap_fill','_____ the reform produced demonstrable short-term efficiency gains, its longer-term effects on the quality and equity of service delivery remain deeply uncertain.','Although',NULL,'"Although" introduces a concessive subordinate clause — acknowledges something true before offering a qualification or contrast.','easy'),
  (cid,74,243,'gap_fill','_____ formal institutional design matters, the literature increasingly recognizes that informal norms and incentive structures are often more decisive in determining governance outcomes.','While',NULL,'"While" = although (concessive) — used to acknowledge a valid point before introducing a more important or qualifying one.','easy'),
  (cid,74,244,'gap_fill','In developed democracies, accountability mechanisms tend to be embedded in a dense network of formal institutions; _____ in many developing contexts, formal accountability structures exist largely on paper and are rarely activated in practice.','whereas',NULL,'"Whereas" (after semicolon or at clause start) = by contrast/while — strong contrastive/concessive marker for parallel situations.','medium'),
  (cid,74,245,'gap_fill','_____ the initial evaluation was broadly positive, subsequent and more rigorous reviews identified a number of significant concerns that had not been adequately addressed in the original assessment.','Even though',NULL,'"Even though" = despite the fact that — stronger concessive force than "although," emphasizing the unexpected nature of the contrast.','medium'),
  (cid,74,246,'gap_fill','The government proceeded with implementation _____ the evidence base was widely regarded as insufficient to justify the scale and pace of the proposed changes.','even though',NULL,'"Even though" mid-sentence concessive — emphasizes that the action was taken against or despite the named condition.','medium'),
  (cid,74,247,'gap_fill','_____ quantitative methods are better suited to testing hypotheses about the magnitude and generalizability of effects, qualitative approaches offer superior tools for understanding the mechanisms and processes through which those effects are produced.','While',NULL,'"While" = although/whereas — introduces the acknowledged strength of one approach before pivoting to the complementary strength of another.','medium'),
  (cid,74,248,'gap_fill','The reform was technically well-designed _____ politically ill-timed — a combination that, as the literature predicts, substantially undermined its prospects for successful implementation.','but',NULL,'"But" here is a simple coordinate conjunction for contrast within a single evaluative claim; the two adjectives are contrasted.','easy'),
  (cid,74,249,'gap_fill','_____ the quantitative findings suggest a positive average effect, the qualitative case studies reveal significant heterogeneity that the aggregate statistics obscure.','Whereas',NULL,'"Whereas" introduces the qualitative counter-evidence — formal academic contrastive marker, slightly stronger than "while."','hard'),
  (cid,74,250,'multiple_choice','Which concessive marker implies the STRONGEST contrast — that the result was unexpected or surprising?','Even though','["Although","While","Even though","Whereas"]','Option C: "Even though" carries the strongest concessive force — it suggests the result is surprising given the condition. "Although" and "while" are more neutral; "whereas" signals contrast without surprise.','medium'),

  -- BLOCK 75: Exemplification — for instance/for example/such as/notably/in particular (9 ex)
  (cid,75,251,'gap_fill','Several factors contributed to the failure of the reform, _____ the lack of adequate consultation with frontline implementers and the absence of a clear monitoring and evaluation framework.','for instance',NULL,'"For instance" = for example — introduces specific illustrations of a general claim.','easy'),
  (cid,75,252,'gap_fill','Informal institutions — _____ unwritten norms governing the exercise of bureaucratic discretion — often prove more resistant to reform than formal legal and regulatory structures.','for example',NULL,'"For example" introduces a specific illustration of the broader category "informal institutions."','easy'),
  (cid,75,253,'gap_fill','Several Nordic countries, _____ Denmark and Sweden, have developed highly effective public accountability systems that combine formal oversight mechanisms with strong informal norms of transparency.','such as',NULL,'"Such as" introduces examples within a noun phrase — integrated into the sentence without a comma + full clause.','easy'),
  (cid,75,254,'gap_fill','The reform agenda was ambitious in scope, addressing multiple dimensions of governance simultaneously — _____ the restructuring of the civil service, the introduction of performance-based budgeting, and the strengthening of legislative oversight.','notably',NULL,'"Notably" = in particular, especially — introduces prominent or especially significant examples.','medium'),
  (cid,75,255,'gap_fill','The study reveals significant variation in reform outcomes across the cases examined. _____, the contrast between Country A, which achieved sustained improvement, and Country B, which experienced rapid reversal, is especially instructive.','In particular',NULL,'"In particular" introduces the most salient or informative example from a broader set.','medium'),
  (cid,75,256,'gap_fill','The literature identifies several mechanisms through which governance quality affects economic performance, _____ by reducing transaction costs, improving contract enforcement, and lowering the risk premium demanded by investors.','for instance',NULL,'"For instance" introduces a list of mechanisms as examples of the broader claim.','medium'),
  (cid,75,257,'gap_fill','The political economy of reform is shaped by a range of actors with competing interests — _____, incumbent bureaucrats who stand to lose from changes that reduce their discretion, and reform advocates who may overestimate the ease of implementation.','for example',NULL,'"For example" introduces contrasting types of actors as illustrations of the broader category.','medium'),
  (cid,75,258,'gap_fill','Context-specific factors, _____ the degree of civil society mobilization and the strength of free media, have been shown to significantly moderate the relationship between formal accountability mechanisms and actual governance behavior.','such as',NULL,'"Such as" is integrated within the noun phrase to list specific examples of "context-specific factors."','medium'),
  (cid,75,259,'multiple_choice','Which sentence uses an exemplification marker MOST effectively in academic writing?','The reform produced unintended consequences in several domains; notably, the decentralization process accelerated in ways that undermined central coordination capacity.','["The reform produced bad effects for example.","For example the reform was bad.","The reform produced unintended consequences in several domains; notably, the decentralization process accelerated in ways that undermined central coordination capacity.","Such as the reform produced problems notably."]','Option C: "notably" after semicolon introduces a precise, significant example — high academic register, correctly positioned.','medium'),

  -- BLOCK 76: Reformulation/sequence — in other words/namely/firstly/subsequently/finally (9 ex)
  (cid,76,260,'gap_fill','The reform failed to generate the expected efficiency gains. _____, it produced outcomes that were, in most respects, worse than those observed before the intervention.','In other words',NULL,'"In other words" = reformulation — restates the preceding point more clearly or emphatically.','easy'),
  (cid,76,261,'gap_fill','The analysis focuses on two countries that satisfy all the selection criteria for the comparative case study design, _____ Estonia and Georgia, both of which have undergone significant governance reform since the early 2000s.','namely',NULL,'"Namely" introduces a precise specification or identification — "these two countries, which I will now name."','easy'),
  (cid,76,262,'gap_fill','The paper proceeds in three stages. _____, it reviews the relevant theoretical literature. _____, it presents the empirical analysis. _____, it considers the implications for policy and future research.','Firstly / Subsequently / Finally',NULL,'"Firstly / Subsequently / Finally" = sequential discourse markers for structuring a multi-part argument or methodology.','easy'),
  (cid,76,263,'gap_fill','The existing framework is inadequate to address the challenge. _____, it provides neither the conceptual tools needed to diagnose the problem accurately nor the practical guidance needed to design effective solutions.','That is to say',NULL,'"That is to say" = in other words — restates with additional specification or clarification.','medium'),
  (cid,76,264,'gap_fill','The relationship between governance and development is not linear; _____, the marginal returns to improvements in institutional quality appear to diminish as governance standards rise.','rather',NULL,'"Rather" = on the contrary / more precisely — reformulates or corrects a potentially misleading implication of the preceding statement.','hard'),
  (cid,76,265,'gap_fill','The study examines three dimensions of governance quality — _____, accountability, effectiveness, and rule of law — and analyzes their relative contribution to economic performance across a panel of sixty countries.','namely',NULL,'"Namely" specifies the three dimensions named as belonging to "three dimensions of governance quality."','medium'),
  (cid,76,266,'gap_fill','The reform was poorly sequenced. _____, the institutions needed to implement the new framework were dismantled before the replacement structures were in place, creating a vacuum of regulatory capacity during the transition period.','More specifically',NULL,'"More specifically" = detailed elaboration — moves from general claim (poorly sequenced) to specific illustration.','medium'),
  (cid,76,267,'gap_fill','The findings challenge the dominant view in the literature. _____, they suggest that the standard model systematically overestimates the importance of formal institutions relative to informal ones.','To be more precise',NULL,'"To be more precise" = specification/refinement of a general claim — formal academic reformulation marker.','hard'),
  (cid,76,268,'multiple_choice','Which reformulation marker introduces the MOST precise specification of the term or category just named?','Namely','["In other words","That is to say","Namely","More specifically"]','Option C: "Namely" introduces the exact names or items that constitute the previously mentioned category. "In other words" and "that is to say" restate the same idea differently; "more specifically" narrows rather than names.','medium'),

  -- BLOCK 77: TOEFL Reading — Discourse Markers (8 ex)
  (cid,77,269,'multiple_choice','[TOEFL Reading] "The reform produced short-term gains; however, its longer-term effects remain uncertain." The word "however" signals:','a contrast between a positive short-term finding and uncertainty about longer-term effects.','["an addition to the short-term finding","a contrast between a positive short-term finding and uncertainty about longer-term effects.","a causal relationship between short-term gains and long-term uncertainty","an example of the short-term gains"]','Option B: "however" = adversative/contrast marker. It signals that what follows qualifies or contradicts the preceding positive finding.','easy'),
  (cid,77,270,'gap_fill','[TOEFL Reading] "The formal structures are in place; _____, informal practices often circumvent them." The correct marker is:','however',NULL,'Contrast between formal design (in place) and informal reality (circumvented) — "however" is the most natural adversative marker.','easy'),
  (cid,77,271,'gap_fill','[TOEFL Reading] "The model assumes rational actors. _____, it likely underestimates the role of cognitive bias." The correct formal causal/inferential marker is:','Hence / Therefore / Thus',NULL,'"Hence/Therefore/Thus" signal that the limitation (underestimating bias) follows logically from the assumption (rational actors).','medium'),
  (cid,77,272,'gap_fill','[TOEFL Reading] "Several structural reforms were implemented — _____, the restructuring of the civil service, the introduction of performance budgeting, and the strengthening of oversight." The correct marker is:','notably',NULL,'"Notably" introduces the most salient examples from the reform agenda — exemplification marker.','medium'),
  (cid,77,273,'gap_fill','[TOEFL Reading] "The intervention is technically sound. _____, it has strong stakeholder support." The correct additive marker (implying additional importance) is:','Moreover / Furthermore / What is more',NULL,'"Moreover/Furthermore/What is more" add a point of equal or greater significance to the preceding claim.','easy'),
  (cid,77,274,'gap_fill','[TOEFL Reading] "_____ formal institutions are critical, informal norms often prove more decisive." The correct concessive marker is:','Although / While / Even though',NULL,'Concessive markers acknowledge the importance of formal institutions before introducing the qualification about informal norms.','easy'),
  (cid,77,275,'gap_fill','[TOEFL Reading] "The paper is structured as follows. _____, it reviews the theory. _____, it presents the evidence. _____, it draws conclusions." The correct sequence markers are:','Firstly / Subsequently / Finally',NULL,'Sequential discourse markers for structuring a paper: firstly, subsequently/secondly, finally.','easy'),
  (cid,77,276,'multiple_choice','[TOEFL Reading] "The findings are surprising. That is to say, the predicted positive effect was not observed." "That is to say" functions as:','a reformulation marker that restates the preceding claim with greater precision.','["a causal marker explaining why the findings are surprising","a contrast marker","a reformulation marker that restates the preceding claim with greater precision.","an addition marker strengthening the claim"]','Option C: "That is to say" = reformulation — it specifies what "surprising" means in concrete terms.','easy'),

  -- BLOCK 78: TOEFL Speaking — Discourse Markers (8 ex)
  (cid,78,277,'production','[TOEFL Speaking — 45s] Summarize the reading on governance reform using a range of discourse markers.','',NULL,'According to the reading, governance reform is a complex and frequently disappointing enterprise. Although formal institutional design matters, informal norms often prove more decisive in determining outcomes. Moreover, the reading argues that reform efforts have typically been poorly sequenced — firstly, the necessary political groundwork was not laid; consequently, implementation encountered resistance that could have been anticipated. The reading nonetheless maintains an optimistic view: it argues that better-designed reforms might achieve more durable outcomes and that, in particular, the integration of political economy analysis into reform design could significantly improve the odds of success.','hard'),
  (cid,78,278,'production','[TOEFL Speaking — 45s] The professor challenges the reading. Use discourse markers throughout.','',NULL,'The professor challenges the reading on several grounds. Firstly, she argues that the reading overstates the importance of technical design; by contrast, the political conditions that enable or constrain reform implementation deserve far greater attention. Furthermore, the professor insists that the reading''s optimism is premature: even though better-designed reforms have occasionally succeeded, the structural factors that drive failure are often beyond the control of reform designers. She argues, in other words, that the reading''s recommendations, however technically sound, are unlikely to be sufficient on their own. The professor concludes that a more politically sophisticated approach is needed — namely, one that treats the building of reform coalitions as central to the reform strategy itself.','hard'),
  (cid,78,279,'production','[TOEFL Speaking — 60s] Compare reading and professor. Use discourse markers throughout.','',NULL,'The reading and the professor both acknowledge that governance reform is a complex and often disappointing enterprise; however, they differ significantly in their diagnoses of why this is the case and in the remedies they propose. The reading argues that reform failures are primarily attributable to poor technical design. Moreover, it suggests that better-designed reforms — in particular, those grounded in careful political economy analysis — are likely to achieve more durable outcomes. By contrast, the professor insists that technical design improvements are necessary but not sufficient, and that the structural political factors driving reform failure are often beyond the reach of better design alone. Consequently, she argues for a fundamentally different approach — namely, one that treats coalition-building and political management as central rather than peripheral to the reform process. Whereas the reading focuses on what reforms should look like, the professor focuses on how they should be introduced and sustained. Furthermore, the professor challenges the reading''s implicit assumption that good design will generate its own political support; such as the examples she cites suggest, even well-designed reforms can fail if their architects neglect the political economy of implementation. In other words, the two perspectives are not simply in conflict but are complementary: together they suggest that successful governance reform requires both technical sophistication and political intelligence — and that neither alone is sufficient.','hard'),
  (cid,78,280,'gap_fill','[TOEFL Speaking] Using contrast markers: "The reading emphasizes technical design; _____, the professor emphasizes political coalition-building."','by contrast / however',NULL,'"By contrast" or "however" introduces the professor''s contrasting emphasis after describing the reading''s position.','easy'),
  (cid,78,281,'gap_fill','[TOEFL Speaking] Using additive markers: "The reading argues for better design. _____, it recommends more rigorous political economy analysis."','Furthermore / Moreover / In addition',NULL,'"Furthermore/Moreover/In addition" add a second, related recommendation to the first.','easy'),
  (cid,78,282,'gap_fill','[TOEFL Speaking] Using causal markers: "The reform lacked political support; _____, implementation was slow and uneven."','consequently / therefore / as a result',NULL,'"Consequently/therefore/as a result" signal that implementation difficulty followed causally from the lack of political support.','easy'),
  (cid,78,283,'gap_fill','[TOEFL Speaking] Using concessive markers: "_____ the design was technically sophisticated, it failed to achieve its objectives."','Although / Even though / While',NULL,'"Although/Even though/While" acknowledge the technical sophistication before introducing the disappointing outcome.','easy'),
  (cid,78,284,'multiple_choice','[TOEFL Speaking] Which response MOST effectively integrates discourse markers to structure a compare-contrast summary?','The reading focuses on technical design; by contrast, the professor emphasizes political conditions. Moreover, the professor argues that even well-designed reforms are bound to fail without adequate political support — consequently, a more politically sophisticated approach is needed.','["Reading and professor both talk about reform but they have differences.","The reading focuses on technical design; by contrast, the professor emphasizes political conditions. Moreover, the professor argues that even well-designed reforms are bound to fail without adequate political support — consequently, a more politically sophisticated approach is needed.","The reading is about design. The professor is about politics. Both are different.","Although design matters, the professor says politics is more important."]','Option B: uses "by contrast" (comparison), "moreover" (addition), "consequently" (causation) — full integration of three discourse marker types in a coherent, fluent academic response.','medium'),

  -- BLOCK 79: TOEFL Writing — produção (8 ex)
  (cid,79,285,'production','[TOEFL Writing — 200 words] Write a body paragraph comparing the reading and lecture using a full range of discourse markers.','',NULL,'The reading and the professor both engage seriously with the question of what determines the success or failure of governance reform; however, they reach substantially different conclusions about where the primary causes of failure lie. The reading argues that poor technical design is the central problem — in other words, that reforms fail primarily because they are insufficiently grounded in rigorous empirical analysis of the political economy in which they operate. Moreover, the reading maintains that better-designed reforms, in particular those incorporating systematic stakeholder consultation, are likely to achieve more durable outcomes. The professor, by contrast, insists that the reading fundamentally misdiagnoses the problem: although technical design matters, informal political dynamics are often more decisive. Furthermore, she argues that the reading''s emphasis on design improvements, while valuable, neglects the coalition-building and political management work without which even the best-designed reforms are unlikely to succeed. Consequently, the professor calls for a more politically sophisticated approach — namely, one that treats political strategy as central to reform design rather than as a secondary consideration. Whereas the reading offers a primarily technocratic account of reform failure and success, the professor offers a political economy account; together, they suggest that neither technical nor political dimensions can be safely neglected.','hard'),
  (cid,79,286,'gap_fill','[TOEFL Writing] "The reform produced short-term efficiency gains. _____, longer-term effects on equity remain uncertain." Correct marker:','However / Nevertheless / Nonetheless',NULL,'Contrast between confirmed short-term outcome and uncertain longer-term outcome — adversative marker needed.','easy'),
  (cid,79,287,'gap_fill','[TOEFL Writing] "The study demonstrates a robust correlation. _____, it identifies the causal mechanisms through which this effect is produced." Correct marker:','Furthermore / Moreover / In addition',NULL,'Addition of a more detailed or significant finding to a robust correlation claim.','easy'),
  (cid,79,288,'gap_fill','[TOEFL Writing] "The data were collected under significant time pressure; _____, several gaps in the time series required interpolation." Correct marker:','consequently / as a result / therefore',NULL,'Causal consequence: time pressure caused the data gaps requiring interpolation.','easy'),
  (cid,79,289,'gap_fill','[TOEFL Writing] "The framework addresses three dimensions of governance: _____, accountability, effectiveness, and rule of law." Correct marker:','namely',NULL,'"Namely" introduces the precise enumeration of what the three dimensions are.','easy'),
  (cid,79,290,'gap_fill','[TOEFL Writing] "_____ formal institutions are well-designed, they frequently fail to generate the expected behavioral change." Correct marker:','Although / Even though / While',NULL,'Concessive marker acknowledging the good design before introducing the failure to generate behavioral change.','easy'),
  (cid,79,291,'gap_fill','[TOEFL Writing] "The approach produced poor outcomes. _____, it systematically undermined the very institutions it was designed to strengthen." Correct marker (reformulation/emphasis):','More specifically / In other words / That is to say',NULL,'"More specifically" or "in other words" restates "poor outcomes" with a precise description of what the failure actually consisted of.','medium'),
  (cid,79,292,'multiple_choice','[TOEFL Writing] Which body paragraph MOST effectively integrates discourse markers for academic coherence?','The reform achieved its short-term objectives; however, its longer-term effects proved disappointing. Moreover, the evaluation revealed that the intervention had produced unintended consequences — notably, the erosion of informal accountability norms that had previously compensated for weaknesses in formal oversight. Consequently, the overall assessment is considerably less positive than the initial evaluation suggested.','["The reform worked short term but not long term. Also it had bad side effects. So overall it was bad.","The reform achieved its short-term objectives; however, its longer-term effects proved disappointing. Moreover, the evaluation revealed that the intervention had produced unintended consequences — notably, the erosion of informal accountability norms that had previously compensated for weaknesses in formal oversight. Consequently, the overall assessment is considerably less positive than the initial evaluation suggested.","Although the reform worked short term, long term it failed, furthermore it had consequences.","The reform was good then bad. Moreover it had effects on norms. Therefore the assessment is negative."]','Option B: "however" (contrast) + "moreover" (addition) + "notably" (exemplification) + "consequently" (causal result) = four distinct discourse marker types in a single coherent paragraph.','medium'),

  -- BLOCK 80: Production avançada — capstone (8 ex)
  (cid,80,293,'production','[TOEFL Writing — 200 words] Capstone: Write a conclusion integrating a full range of discourse markers.','',NULL,'The evidence examined in this analysis leads to several interconnected conclusions about the conditions under which governance reform succeeds or fails. Firstly, the technical quality of reform design matters — in other words, reforms that are grounded in rigorous empirical analysis and that incorporate systematic stakeholder consultation are more likely to achieve their stated objectives than those designed in a technocratic vacuum. Moreover, the sequencing of reform matters enormously: reforms introduced before the necessary political and institutional preconditions are in place are bound to encounter the kind of resistance that derails even technically sophisticated initiatives. Nonetheless, technical improvements alone are insufficient; consequently, any comprehensive strategy for governance reform must also address the political economy of change — namely, the incentive structures, coalition dynamics, and informal norms that shape how formal institutions actually function in practice. Although this conclusion may appear to set an impossibly demanding standard for reform design, it need not lead to pessimism: several countries have demonstrated that sustained improvement is achievable when both technical and political dimensions are addressed simultaneously. By contrast, reform efforts that neglect either dimension are unlikely to achieve durable results, however well-intentioned and technically sophisticated they may be. The challenge, in other words, is not merely to design better institutions but to create the political conditions in which better institutions can take root and function as intended.','hard'),
  (cid,80,294,'gap_fill','[Final capstone] "The reform produced measurable gains. _____, it undermined informal accountability norms. _____, the net assessment is mixed." Correct markers:','However / Consequently',NULL,'"However" contrasts the gains with the harm; "consequently" signals that the net assessment follows causally from both.','medium'),
  (cid,80,295,'gap_fill','[Final capstone] "The framework addresses all three governance dimensions — _____, accountability, effectiveness, and rule of law — and _____ represents a significant advance on its predecessors." Correct markers:','namely / therefore',NULL,'"Namely" specifies the three dimensions; "therefore" signals that the comprehensiveness is the reason the framework is an advance.','medium'),
  (cid,80,296,'gap_fill','[Final capstone] "_____ technical design is important, informal political dynamics often prove more decisive; _____, any reform strategy that neglects the latter is unlikely to succeed." Correct markers:','Although / consequently',NULL,'"Although" concedes the importance of technical design; "consequently" signals the practical implication for reform strategy.','medium'),
  (cid,80,297,'gap_fill','[Final capstone] "Several reform efforts have succeeded — _____, those in Estonia, Georgia, and Rwanda — suggesting that success is achievable under the right conditions." Correct marker:','notably',NULL,'"Notably" introduces the most salient examples from the set of successful reform efforts.','easy'),
  (cid,80,298,'gap_fill','[Final capstone] "The study reveals significant variation. _____, this variation is not random but is systematically associated with initial institutional endowments." Correct marker:','Moreover',NULL,'"Moreover" adds the more significant insight — not only is there variation, but it has a discoverable structure.','medium'),
  (cid,80,299,'production','[TOEFL Writing — 200 words] Final synthesis: Write a body paragraph comparing the reading and lecture using all major discourse marker types.','',NULL,'The reading and the professor both offer valuable insights into the conditions that determine governance reform outcomes; however, they reach strikingly different conclusions about where the primary leverage for improvement lies. The reading argues that technical design quality is the central determinant of reform success — in other words, that reforms fail primarily because they are not sufficiently grounded in rigorous evidence and careful stakeholder consultation. Moreover, the reading maintains that addressing this technical deficit would substantially improve the odds of success. The professor, by contrast, insists that this account is fundamentally incomplete: although technical design matters, the structural political factors that shape implementation are often more decisive, and these cannot be improved simply by designing better reforms. Consequently, she calls for a more politically sophisticated approach — namely, one that treats the building of reform coalitions and the alignment of political incentives as central rather than peripheral concerns. Whereas the reading''s implicit model of reform is primarily technocratic, the professor''s is primarily political. Furthermore, the professor argues that the reading''s optimism is premature — even well-designed reforms, she notes, have frequently failed when the political conditions for sustained implementation were absent. In other words, the debate between the reading and the professor ultimately reflects a deeper disagreement about whether governance is primarily a technical or a political challenge.','hard'),
  (cid,80,300,'production','[TOEFL Writing — Final capstone 300] Write a concluding paragraph on discourse markers and academic argumentation.','',NULL,'Academic discourse is held together by discourse markers — the connective tissue of scholarly argument. Without markers of contrast, addition, causation, exemplification, and reformulation, academic writing collapses into a sequence of disconnected assertions; with them, it becomes a coherent and navigable intellectual structure. The skilled academic writer uses "however" to signal that a complication is coming, "moreover" to indicate that a more important point follows, "consequently" to show that a conclusion has been earned through argument, "namely" to specify what was previously left general, and "in other words" to ensure that the reader has grasped the full force of a point before moving on. These are not merely stylistic flourishes; they are epistemic signals that tell the reader how to weight and relate the propositions that constitute an academic argument. The TOEFL candidate who commands this repertoire is not only demonstrating linguistic competence but also demonstrating the kind of analytical intelligence that good academic writing both requires and reveals. Although discourse markers can be learned as vocabulary items, their true mastery comes only when the writer has internalized the logical relationships they encode — contrast, addition, causation, exemplification, reformulation, sequence — and can deploy them fluently and accurately in the service of a coherent, well-structured academic argument. That, ultimately, is what this entire course has been working toward.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
