-- ============================================================
-- SEED EXT 3: Módulo 19 — Hedging Language (ex 106-205)
-- Novos tópicos: hedging por seção (intro/lit review/conclusion),
-- negative hedges, multi-device sentences, TOEFL
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'hedging-language';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo hedging-language não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 31: hedging in introductions (research aims)
  (cid,31,106,'gap_fill','This paper _____ (seek) to investigate the relationship between sleep quality and academic performance.','seeks',NULL,'"Seeks to investigate" = hedged aim statement. More cautious than "will prove."','easy'),
  (cid,31,107,'multiple_choice','Which introduction sentence is MOST appropriately hedged?','This study aims to explore the extent to which digital literacy skills may predict academic success.','["This study proves that digital literacy skills predict academic success.","This study aims to explore the extent to which digital literacy skills may predict academic success.","This study will definitely establish that digital literacy predicts success.","This study might possibly perhaps explore digital literacy."]','"Aims to explore" + "may predict" = double hedging appropriate for an introduction.','hard'),
  (cid,31,108,'gap_fill','The purpose of this research is to examine _____ (whether/if) early bilingual education influences cognitive development in later childhood.','whether',NULL,'"Whether" is more formal than "if" in academic writing for embedded questions.','medium'),
  (cid,31,109,'multiple_choice','In an academic introduction, which phrase INCORRECTLY hedges a research aim?','This paper will conclusively solve the debate about climate change.','["This paper seeks to contribute to the debate about...","This study aims to provide a preliminary analysis of...","This paper will conclusively solve the debate about climate change.","This research attempts to shed light on the relationship between..."]','"Will conclusively solve" = overclaim. Research aims should use hedged language.','medium'),
  (cid,31,110,'gap_fill','It _____ (hypothesize/passive + that) mindfulness training reduces cortisol levels in university students under academic pressure.','is hypothesized that',NULL,'"It is hypothesized that" = formal passive hedged claim in research introduction.','hard'),
  (cid,31,111,'multiple_choice','Which verb phrase is most hedged for stating a research hypothesis?','The data suggest that increased investment may lead to improved outcomes.','["The data prove that investment leads to better outcomes.","The data clearly show investment produces improved outcomes.","The data suggest that increased investment may lead to improved outcomes.","The data obviously demonstrate investment always improves outcomes."]','"Suggest" + "may lead" = two-device hedge (hedged verb + modal).','hard'),

  -- BLOCK 32: hedging in literature reviews
  (cid,32,112,'gap_fill','A number of studies _____ (indicate) that parental involvement is positively correlated with student achievement.','have indicated / indicate',NULL,'"A number of studies have indicated" = hedged attribution. Not "prove."','easy'),
  (cid,32,113,'multiple_choice','Which attribution phrase introduces a claim with maximum hedging?','Some researchers have argued that the benefits of standardized testing may be overstated.','["Research proves that standardized testing is overrated.","Studies show that standardized testing is completely useless.","Some researchers have argued that the benefits of standardized testing may be overstated.","It is clear that standardized testing is ineffective."]','"Some researchers have argued" + "may be overstated" = source attribution + modal hedge.','hard'),
  (cid,32,114,'gap_fill','While _____ (evidence + growing) supports this view, the causal mechanisms remain poorly understood.','there is growing evidence that / growing evidence',NULL,'"While + concessive + hedge" = balanced literature review statement.','hard'),
  (cid,32,115,'multiple_choice','In a literature review, which sentence most effectively balances claim and hedge?','Previous research has suggested a link between social media use and decreased attention spans, though the evidence is not yet conclusive.','["Social media destroys attention spans, as shown by all research.","Previous research has suggested a link between social media use and decreased attention spans, though the evidence is not yet conclusive.","Some research maybe shows social media possibly affects attention spans.","No research has addressed this topic adequately."]','"Has suggested" + "not yet conclusive" = paired claim-limitation structure.','hard'),
  (cid,32,116,'gap_fill','The findings of Smith (2019) _____ (be + consistent) with those of earlier studies but _____ (differ) in several key respects.','are broadly consistent / differ',NULL,'Hedged comparison: "broadly consistent" (scope hedge) + "differ in key respects" (specific limitation).','hard'),
  (cid,32,117,'multiple_choice','Which phrase signals that the writer is citing a view they don''t fully endorse?','According to proponents of this view, free trade invariably benefits developing economies.','["Research shows that free trade benefits developing economies.","It has been established that free trade benefits developing economies.","According to proponents of this view, free trade invariably benefits developing economies.","The evidence proves that free trade is always beneficial."]','"According to proponents of this view" = distancing attribution.','hard'),

  -- BLOCK 33: hedging in conclusions and implications
  (cid,33,118,'gap_fill','The findings of this study _____ (suggest/that) interventions targeting both diet and exercise _____ (be) most effective.','suggest that / may be',NULL,'"Suggest that X may be" = double-hedged conclusion statement.','medium'),
  (cid,33,119,'multiple_choice','Which is the most appropriate conclusion sentence for a research paper?','These findings suggest that the relationship between poverty and educational attainment may be mediated by access to digital resources.','["These findings prove that poverty causes poor education.","These findings clearly show poverty always leads to low attainment.","These findings suggest that the relationship between poverty and educational attainment may be mediated by access to digital resources.","These findings show that poverty might probably possibly affect education."]','"Suggest" + "may be mediated" = appropriate double hedge for a conclusion.','hard'),
  (cid,33,120,'gap_fill','Future research _____ (need) to examine a larger sample to confirm whether these results _____ (generalize) to other populations.','will need / can be generalized',NULL,'Conclusion with forward-looking hedge: "will need to examine" + "can be generalized" (can = possibility).','hard'),
  (cid,33,121,'multiple_choice','A limitation statement in a conclusion should:','Acknowledge what the study does not do, using hedging to specify scope.','["Dismiss the entire study''s findings","Acknowledge what the study does not do, using hedging to specify scope.","Claim the study is perfect","Use boosters to defend the research"]','Limitation = honest hedging about what was NOT addressed.','medium'),
  (cid,33,122,'gap_fill','While the present study provides preliminary evidence for this hypothesis, more research _____ (warrant/passive) before definitive conclusions _____ (draw/passive).','is warranted / can be drawn',NULL,'"Is warranted" (necessity passive) + "can be drawn" (possibility hedge).','hard'),
  (cid,33,123,'multiple_choice','Which is an appropriate limitation statement?','The study was limited to a single urban context, which may restrict the generalizability of the findings.','["The study was completely limited and its findings are worthless.","The study is perfect but future research should also be done.","The study was limited to a single urban context, which may restrict the generalizability of the findings.","The study was limited, possibly perhaps restricting some maybe findings."]','"Limited to" + "may restrict" = scope hedge for a limitation.','medium'),

  -- BLOCK 34: negative hedges (not necessarily, not always, by no means)
  (cid,34,124,'gap_fill','A high income does _____ (not/necessarily) guarantee happiness, as cross-cultural research has consistently shown.','not necessarily',NULL,'"Does not necessarily X" = negative hedge. Denies universality without denying possibility.','medium'),
  (cid,34,125,'multiple_choice','What does "not always" hedge in "Higher education does not always lead to better employment outcomes"?','It denies the universal claim while allowing for cases where it IS true.','["It says higher education never helps","It says higher education always helps","It denies the universal claim while allowing for cases where it IS true.","It is a double negative"]','"Not always" = partial negation (some cases are true; not universal).','medium'),
  (cid,34,126,'gap_fill','The relationship between stress and productivity is _____ (not/straightforward), as moderate stress can sometimes enhance performance.','not straightforward',NULL,'"Not straightforward" = negative evaluation hedge.','easy'),
  (cid,34,127,'multiple_choice','Which sentence uses "by no means" correctly as a negative hedge?','The results are by no means conclusive and require further validation.','["The results are by no means and require further validation.","The results are conclusive by no means.","The results are by no means conclusive and require further validation.","The results are conclusive, by no means requiring validation."]','"By no means + adjective" = strong negative hedge ("not at all conclusive").','medium'),
  (cid,34,128,'gap_fill','This _____ (not/the only) explanation for the observed phenomenon; alternative hypotheses deserve equal consideration.','is not the only',NULL,'"This is not the only explanation" = negative hedge opening alternative space.','medium'),
  (cid,34,129,'multiple_choice','The hedge "It would be premature to conclude that..." signals:','The writer believes more evidence is needed before the claim can be made with confidence.','["The claim is definitely true","The writer is confused","The writer believes more evidence is needed before the claim can be made with confidence.","The claim is definitely false"]','"Premature to conclude" = temporal hedge — too soon to claim certainty.','hard'),
  (cid,34,130,'gap_fill','These results _____ (not/mean) that all forms of exercise are equally effective for treating depression.','do not mean',NULL,'"Do not mean that" = careful negative hedge preventing over-interpretation of findings.','easy'),

  -- BLOCK 35: multi-device hedging (combining multiple hedges)
  (cid,35,131,'multiple_choice','How many hedging devices are in: "It has been suggested that moderate alcohol consumption may possibly be associated with a reduced risk of cardiovascular disease in some populations"?','Four: has been suggested (passive), may (modal), possibly (adverb), some populations (scope).','["One: may","Two: has been suggested and may","Three: has been suggested, may, and possibly","Four: has been suggested (passive), may (modal), possibly (adverb), some populations (scope)."]','Stacked hedges = four distinct devices.','hard'),
  (cid,35,132,'gap_fill','Write a sentence hedging the claim "Screen time causes anxiety in children" using three devices: a passive impersonal verb + a modal + a scope hedge.','It has been suggested that excessive screen time may contribute to anxiety symptoms in some children.',NULL,'Pattern: It has been suggested (passive) + may (modal) + in some children (scope).','hard'),
  (cid,35,133,'multiple_choice','Which sentence correctly uses BOTH a lexical hedge AND a modal hedge?','Dietary interventions appear to be more effective than pharmacological ones, at least in mild cases.','["Dietary interventions are certainly more effective than pharmacological ones.","Dietary interventions appear to be more effective than pharmacological ones, at least in mild cases.","Dietary interventions possibly are always more effective.","It appears dietary interventions are obviously more effective."]','"Appear to be" (lexical) + "at least in mild cases" (scope). Well-calibrated.','hard'),
  (cid,35,134,'gap_fill','Combine three hedges: modal + lexical + scope. Fill the blanks: "The new curriculum _____ (modal) _____ (lexical hedge: appear) to improve outcomes _____ (scope: in many cases)."','may / appear / in many cases',NULL,'Three-device hedge: "may appear to improve outcomes in many cases."','hard'),
  (cid,35,135,'multiple_choice','Why can over-stacking hedges be counterproductive in academic writing?','Too many hedges weaken the writer''s credibility and make the claim appear unsupported or incoherent.','["Journals forbid more than two hedges","Over-hedging is grammatically incorrect","Too many hedges weaken the writer''s credibility and make the claim appear unsupported or incoherent.","More hedges always increase formality"]','Over-hedging = signals excessive uncertainty and undermines the argument.','hard'),

  -- BLOCK 36: hedging in specific disciplines
  (cid,36,136,'gap_fill','[Hard Science] "The results _____ (be + consistent) with the hypothesis that X causes Y, though confounding variables cannot be ruled out."','are consistent',NULL,'"Are consistent with" = scientific hedging phrase (correlation, not proof). "Cannot be ruled out" = further hedge.','hard'),
  (cid,36,137,'multiple_choice','[Social Science] Which sentence is most typical of hedged social science writing?','Income inequality appears to be associated with lower levels of civic trust across most OECD countries.','["Income inequality causes lower civic trust.","Income inequality appears to be associated with lower levels of civic trust across most OECD countries.","There may possibly perhaps be an association between income inequality and civic trust.","Income inequality definitely reduces civic trust in all countries."]','"Appears to be associated" + scope hedge "most OECD countries" = social science hedging.','hard'),
  (cid,36,138,'gap_fill','[Medical] "The drug _____ (show + passive) promise in Phase 2 trials, though Phase 3 results are necessary before any clinical recommendation _____ (make/passive)."','has shown / can be made',NULL,'"Has shown promise" (hedged past) + "necessary before X can be made" (conditional hedge).','hard'),
  (cid,36,139,'multiple_choice','[Humanities] Which sentence uses appropriate hedging for a literary interpretation?','The imagery in this passage arguably reflects Woolf''s ambivalence about modernity.','["The imagery in this passage proves Woolf was ambivalent about modernity.","The imagery in this passage arguably reflects Woolf''s ambivalence about modernity.","The imagery is obviously showing Woolf''s ambivalence.","The imagery possibly maybe suggests some ambivalence."]','"Arguably" = hedging for interpretive claims in humanities — acknowledges other readings are possible.','hard'),

  -- BLOCK 37: TOEFL Reading
  (cid,37,140,'multiple_choice','[TOEFL Reading] "The data suggest that increased urbanization may be contributing to rising rates of respiratory illness." How many hedges are in this sentence?','Two: "suggest" and "may be contributing."','["One: suggest","Two: ''suggest'' and ''may be contributing.''","Three: data, suggest, and may","Four: data, suggest, may, and urbanization"]','"Suggest" (hedged reporting verb) + "may be contributing" (modal + progressive).','medium'),
  (cid,37,141,'gap_fill','[TOEFL Reading] "It _____ (note/passive + important) that the sample in this study consisted entirely of university students, which limits the generalizability of the findings." Best form?','should be noted / is important to note',NULL,'"It should be noted" = formal hedging marker introducing a limitation.','hard'),
  (cid,37,142,'multiple_choice','[TOEFL Reading] "There is some evidence to suggest that bilingualism may delay the onset of dementia." The phrase "some evidence" is:','A quantity hedge (not all evidence; a partial body of evidence).','["A booster","A quantity hedge (not all evidence; a partial body of evidence).","A negative hedge","A passive impersonal"]','"Some evidence" = quantity hedge (not "strong" or "conclusive" evidence).','medium'),
  (cid,37,143,'gap_fill','[TOEFL Reading] "These correlations _____ (not/establish) causation, and further experimental work is required to elucidate the mechanisms involved." Best form?','do not establish',NULL,'"Do not establish causation" = critical distinction between correlation and causation.','easy'),
  (cid,37,144,'multiple_choice','[TOEFL Reading] "Although promising, these preliminary results should be interpreted with caution." The phrase "with caution" indicates:','The results may not hold in different contexts or with larger samples.','["The results are incorrect","The results are definitely correct","The results may not hold in different contexts or with larger samples.","The word caution is itself a hedge"]','Epistemic caution = results are promising but not final.','medium'),

  -- BLOCK 38: TOEFL Speaking
  (cid,38,145,'production','[TOEFL Speaking — 45s] A reading says technology is making students lazy. Summarize using hedging. Include: it has been argued, appear to, may, not necessarily, some evidence.','',NULL,'It has been argued that the proliferation of digital tools may be reducing students'' capacity for independent problem-solving. Some evidence appears to support this view — students who rely on calculators and search engines may not develop the same analytical skills as those who practice manual computation. However, this is not necessarily a straightforward negative development: technology may simply be shifting the skills that students develop rather than reducing their overall intellectual capacity.','hard'),
  (cid,38,146,'production','[TOEFL Speaking — 45s] Should universities prioritize research or teaching? Take a position and hedge your weaker claims. Use: suggest, may, arguably, to some extent, it is worth noting.','',NULL,'The evidence suggests that the most innovative universities tend to excel in both research and teaching, which makes the binary framing of this debate arguably misleading. To some extent, strong research environments may enhance teaching quality by exposing students to cutting-edge ideas. However, it is worth noting that heavy research pressure may reduce the time and attention faculty can devote to undergraduate instruction. A balanced approach that incentivizes both activities is likely to produce the best outcomes.','hard'),

  -- BLOCK 39: TOEFL Writing
  (cid,39,147,'production','[TOEFL Writing — 150 words] Write an academic paragraph making and hedging a claim about the causes of obesity. Use: it has been argued, appear to, suggest, may not be, by no means, not necessarily, some evidence.','',NULL,'It has been argued that the rising rates of obesity across developed nations are primarily attributable to poor dietary choices and sedentary lifestyles. There is some evidence to suggest that these individual-level behaviors do play a significant role. However, the relationship between diet, exercise, and body weight is by no means straightforward. Genetic factors, socioeconomic status, mental health, and access to healthy food options all appear to contribute to the complex etiology of obesity. Blaming individuals for their weight is therefore not necessarily a productive or scientifically accurate response to a public health challenge that is shaped by structural as well as personal factors. Policy interventions that address the food environment and promote equitable access to physical activity may prove more effective than campaigns targeting individual behavior change.','hard'),
  (cid,39,148,'production','[TOEFL Writing — Error Correction] Fix hedging errors: "It has been suggested that exercise clearly proves mental health benefits. Research shows that meditation obviously eliminates stress. Scientists have argued that social media certainly destroys relationships. By no means is it possible that screen time has any positive effects."','',NULL,'clearly proves → may improve / appears to improve (hedging the mechanism); obviously eliminates → may reduce (eliminate = overclaim; obviously = unnecessary booster); certainly destroys → may adversely affect (destroys = overclaim; certainly = booster); "By no means is it possible that...any positive effects" = double negative contradiction. Fix: "It remains unclear whether all forms of screen time are harmful; some studies suggest certain uses may have educational or social benefits."','hard'),
  (cid,39,149,'production','[TOEFL Writing — 200 words] Write a literature review paragraph on "the effects of urban green spaces on mental health." Use at least 6 distinct hedging devices: passive impersonal, modal hedge, lexical hedge, quantity hedge, scope hedge, negative hedge. Label each one in brackets.','',NULL,'It has been suggested [passive impersonal] that access to urban green spaces may [modal] be associated with improved mental health outcomes among city residents. A number of studies [quantity hedge] appear to [lexical] demonstrate a positive correlation between proximity to parks and reduced rates of anxiety and depression. However, this relationship does not necessarily [negative hedge] hold across all demographic groups [scope hedge] — individuals with limited mobility or time may not benefit equally from the availability of green spaces. Furthermore, the mechanisms underlying these associations have not been fully established, and the existing evidence is based largely on observational rather than experimental designs. It has been argued [passive impersonal] that the restorative effects of natural environments may [modal] operate through reductions in cortisol levels and attentional fatigue, though this interpretation remains speculative in many respects [scope hedge].','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
