-- ============================================================
-- SEED EXT 2: Módulo 09 — First Conditional (exercícios 71-185)
-- Novos tópicos: imperative in result clause, modal variations,
-- when vs if, mixed conditional 0/1, formal academic register,
-- error correction, TOEFL production
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'conditional-1';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo conditional-1 não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 11: imperative in result clause
  (cid,11,71,'gap_fill','If you encounter any problems with the software, ___ (contact) the IT department immediately.','contact',NULL,'If + present simple → imperative in result clause (advice/instruction).','medium'),
  (cid,11,72,'multiple_choice','Which sentence uses an IMPERATIVE in the result clause correctly?','If you find an error in your data, check the raw files immediately.','["If you find an error, you will check the files.","If you will find an error, check the files.","If you find an error in your data, check the raw files immediately.","If you found an error, check the files."]','If + present simple → imperative (no will in the if-clause).','medium'),
  (cid,11,73,'gap_fill','If the temperature exceeds 40°C, ___ the experiment immediately.','stop / halt',NULL,'Emergency instruction: if + present → imperative result.','easy'),
  (cid,11,74,'multiple_choice','Which context MOST commonly uses the imperative result clause?','Safety instructions and academic guidelines.','["Predictions about the future","Formal academic hedging","Safety instructions and academic guidelines.","General facts"]','Imperative result clause is typical in instructions, recipes, safety procedures.','medium'),
  (cid,11,75,'gap_fill','If you don''t understand a concept, ___ (not/continue) — ___ the professor for clarification.','don''t continue / ask',NULL,'Negative imperative (don''t + base verb) in result clause.','medium'),
  (cid,11,76,'multiple_choice','Choose the CORRECT imperative conditional: "If you see the warning light, ___."','turn off the machine immediately','["you will turn off the machine","you turned off the machine","turning off the machine","turn off the machine immediately"]','Imperative: base verb + no subject.','easy'),
  (cid,11,77,'gap_fill','If the patient experiences chest pain, ___ the emergency team without delay.','call / notify',NULL,'Medical instruction: if + present → imperative.','easy'),

  -- BLOCK 12: result clause with can/may/might instead of will
  (cid,12,78,'gap_fill','If you review your notes daily, you ___ find it easier to recall information during the exam.','may / might / could / will',NULL,'Modal variations in result clause: may/might/could (possibility) or will (certainty).','medium'),
  (cid,12,79,'multiple_choice','Which sentence expresses a POSSIBLE (not certain) outcome?','If we reduce emissions, we might slow the rate of climate change.','["If we reduce emissions, we will slow climate change.","If we reduce emissions, we might slow the rate of climate change.","If we reduce emissions, we slow climate change.","If we reduce emissions, we have slowed climate change."]','"Might" in result clause = possible/uncertain outcome.','medium'),
  (cid,12,80,'gap_fill','If you submit early, you ___ receive feedback before the deadline. (possibility, not certainty)','may / might / could',NULL,'"May/might/could" for uncertain positive outcome.','medium'),
  (cid,12,81,'multiple_choice','What is the difference between "If you study, you WILL pass" vs "If you study, you MAY pass"?','Will = certain outcome; may = possible but not guaranteed.','["No difference — both are conditional","Will = possible; may = certain","Will = certain outcome; may = possible but not guaranteed.","May is more formal than will"]','"Will" = near-certain consequence; "may" = possibility.','hard'),
  (cid,12,82,'gap_fill','If the clinical trial succeeds, the drug ___ be approved for widespread use within two years. (not certain — possibility)','could / may / might',NULL,'Modal of possibility in result clause for uncertain scientific outcome.','medium'),
  (cid,12,83,'multiple_choice','Which is the most FORMAL academic version of "If we use this method, we''ll get better results"?','If this methodology is adopted, superior results may be obtained.','["If we use this method, we''ll get better results.","If this method is used, we get better results.","If this methodology is adopted, superior results may be obtained.","If we adopt this method, we will get better results."]','Passive + "may be obtained" = formal academic hedged conditional.','hard'),
  (cid,12,84,'gap_fill','If the data ___ (show) a significant correlation, researchers ___ (can/proceed) to the causal analysis phase.','shows / can proceed',NULL,'"Shows" (present) in if-clause; "can proceed" (ability/permission) in result clause.','hard'),
  (cid,12,85,'multiple_choice','Choose the sentence where the result clause uses the CORRECT modal for PERMISSION:','If you complete the prerequisite course, you can enroll in the advanced seminar.','["If you complete the course, you will can enroll.","If you complete the prerequisite course, you can enroll in the advanced seminar.","If you will complete the course, you can enroll.","If you complete the course, you should can enroll."]','"Can" for permission in result clause.','medium'),

  -- BLOCK 13: when vs if (certainty vs condition)
  (cid,13,86,'multiple_choice','Choose "when" or "if": "___ the economy improves, unemployment falls." (reliable pattern)','When the economy improves, unemployment falls.','["If the economy improves, unemployment falls.","When the economy improves, unemployment falls.","Both are equally correct here.","Neither fits this context."]','"When" for predictable/reliable patterns; "if" for uncertain conditions. Both can be correct, but "when" implies greater certainty.','hard'),
  (cid,13,87,'gap_fill','___ you call me, I will answer immediately. (certain future plan — caller will definitely call)','When',NULL,'"When" = I know/assume you will call (certain future event).','medium'),
  (cid,13,88,'multiple_choice','Which sentence uses "when" most appropriately?','When water reaches 100°C, it boils.','["When they arrive, I don''t know what to do.","When water reaches 100°C, it boils.","When it rains tomorrow (uncertain), take an umbrella.","When the alarm rings, I might wake up."]','"When" for certain events and scientific facts.','medium'),
  (cid,13,89,'gap_fill','___ you are unsure about the methodology, consult your supervisor. (may or may not be unsure)','If',NULL,'"If" for uncertain condition — the person may or may not be unsure.','easy'),
  (cid,13,90,'multiple_choice','In the sentence "If you need help, just ask," replacing "if" with "when" would imply:','The speaker assumes the listener WILL need help.','["The listener does not need help","The sentence becomes incorrect","The speaker assumes the listener WILL need help.","No difference in meaning"]','"When" = certainty of the event happening; "if" = only if it occurs.','hard'),
  (cid,13,91,'gap_fill','___ spring arrives, migratory birds return to their breeding grounds. (reliable annual pattern)','When',NULL,'"When" for predictable, cyclical, or certain events.','medium'),
  (cid,13,92,'gap_fill','___ the committee approves the budget, we can hire two more researchers. (uncertain outcome)','If',NULL,'"If" for uncertain future condition — approval is not guaranteed.','easy'),
  (cid,13,93,'multiple_choice','Which sentence uses "when" INCORRECTLY?','When I might get promoted, I will buy a new car.','["When I get home, I will call you.","When spring arrives, flowers bloom.","When the report is ready, please send it.","When I might get promoted, I will buy a new car."]','"When" does not combine with "might." The uncertainty in "might" should use "if."','hard'),

  -- BLOCK 14: mixed zero and first conditional
  (cid,14,94,'multiple_choice','Which is a ZERO conditional (general truth)?','If water is heated to 100°C, it boils.','["If it rains tomorrow, we will cancel the picnic.","If water is heated to 100°C, it boils.","If you study, you will pass.","If she calls, I''ll tell her."]','Zero conditional = both clauses in present simple = scientific/general fact.','easy'),
  (cid,14,95,'gap_fill','Zero: "If metals ___ (heat), they ___ (expand)." First: "If the budget ___ (increase), we ___ (can/hire) more staff."','are heated / expand / increases / can hire',NULL,'Zero: present + present (fact). First: present + can/will (specific future).','hard'),
  (cid,14,96,'multiple_choice','In "If you mix red and blue, you get purple," which conditional is this?','Zero — a general/permanent fact.','["First — a prediction","Second — an unlikely condition","Zero — a general/permanent fact.","Third — a past hypothetical"]','Zero conditional: always true, present + present.','easy'),
  (cid,14,97,'gap_fill','Zero: "If a cell lacks oxygen, it ___ (die)." First: "If funding is secured, the trial ___ (begin) next year."','dies / will begin',NULL,'Zero: present simple (dies). First: present simple → will + base (will begin).','medium'),
  (cid,14,98,'multiple_choice','Which pair correctly distinguishes zero from first conditional?','Zero: "If CO₂ increases, global temperatures rise." First: "If emissions aren''t cut, temperatures will rise by 2°C."','["Zero: ''If CO₂ increases, temperatures will rise.'' First: ''If CO₂ rises, temperatures rise.''","Zero: ''If CO₂ increases, global temperatures rise.'' First: ''If emissions aren''t cut, temperatures will rise by 2°C.''","Both use present + present in zero and present + will in first","Zero and first are structurally identical"]','Zero: present + present (always true). First: present + will (specific future outcome).','hard'),
  (cid,14,99,'gap_fill','If the experiment ___ (produce) consistent results, the methodology ___ (validate/passive) for future studies.','produces / will be validated',NULL,'First conditional with passive result clause.','hard'),
  (cid,14,100,'multiple_choice','Which conditional type is used in academic papers to describe hypothetical research scenarios?','First conditional for feasible future scenarios.','["Zero conditional for all predictions","First conditional for feasible future scenarios.","Second conditional only","Both zero and second only"]','First conditional: plausible future scenarios ("If funding is approved, the study will proceed").','hard'),

  -- BLOCK 15: formal academic first conditional
  (cid,15,101,'gap_fill','[Academic] Should the data ___ (show) statistical significance, the model ___ (refine/passive).','show / will be refined',NULL,'Formal inversion: "Should + subject + base verb" = formal first conditional. "Will be refined" = passive result.','hard'),
  (cid,15,102,'multiple_choice','Which is the FORMAL academic version of "If you don''t act now, you''ll miss the opportunity"?','Should immediate action not be taken, the opportunity will be forfeited.','["If you don''t act now, you''ll miss the opportunity.","Should immediate action not be taken, the opportunity will be forfeited.","If you fail to act now, the opportunity will be lost.","Unless you act, you will miss it."]','Formal inversion: "Should + subject + not + base verb" for formal conditional.','hard'),
  (cid,15,103,'gap_fill','___ ___ (should/the hypothesis) be supported by the data, a larger follow-up study will be commissioned.','Should the hypothesis',NULL,'Formal first conditional inversion: Should + subject + base verb.','hard'),
  (cid,15,104,'multiple_choice','What does the formal structure "Should + subject + verb..." mean?','It is a formal way of saying "If ... (first conditional)."','["It is a second conditional","It means ''must + verb''","It is a formal way of saying ''If ... (first conditional).''","It is always in the past"]','Formal inversion: "Should you need help" = "If you need help."','hard'),
  (cid,15,105,'gap_fill','___ ___ (should/the treatment) prove ineffective, alternative protocols will be explored.','Should the treatment',NULL,'"Should the treatment prove ineffective" = "If the treatment proves ineffective" (formal).','hard'),
  (cid,15,106,'multiple_choice','Which formal conditional is grammatically CORRECT?','Should further evidence emerge, the theory may require revision.','["Should further evidence will emerge, the theory may require revision.","Should further evidence emerged, the theory requires revision.","Should further evidence emerge, the theory may require revision.","Should further evidence emerges, the theory may require revision."]','"Should + subject + base verb" (not past or -s form).','hard'),
  (cid,15,107,'gap_fill','___ results ___ indicate (inversion) a positive trend, the research team ___ expand the sample.','Should / will',NULL,'"Should results indicate a positive trend, the research team will expand the sample."','hard'),

  -- BLOCK 16: error correction
  (cid,16,108,'multiple_choice','Find the error: "If it will rain tomorrow, we will cancel the event."','Will rain is wrong — should be: if it rains tomorrow.','["cancel should be cancelled","we should be they","Will rain is wrong — should be: if it rains tomorrow.","tomorrow should be today"]','If-clause: NEVER use will. Use present simple: "if it rains."','hard'),
  (cid,16,109,'gap_fill','Error: "If you will need help, ask me." Correct: "If you ___ help, ask me."','need',NULL,'Remove "will" from if-clause: If + present simple.','medium'),
  (cid,16,110,'multiple_choice','Which sentence has NO error?','If the budget is approved, the project will start next month.','["If the budget will be approved, the project starts next month.","If the budget is approved, the project starts (zero instead of first).","If the budget is approved, the project will start next month.","If the budget would be approved, the project will start."]','Correct first conditional: if + present simple + will + base verb.','medium'),
  (cid,16,111,'gap_fill','Error: "Unless you won''t submit by Friday, you''ll lose marks." Correct: "Unless you ___ by Friday, you''ll lose marks."','submit',NULL,'"Unless" = if not. "Unless you submit" = "If you don''t submit." Do NOT use "won''t" after unless.','hard'),
  (cid,16,112,'multiple_choice','Find the error: "If she doesn''t comes to the meeting, we''ll reschedule."','doesn''t comes should be doesn''t come','["she should be her","meeting should be meetings","doesn''t comes should be doesn''t come","we''ll should be we won''t"]','Third person: doesn''t + base verb (no -s after doesn''t).','medium'),
  (cid,16,113,'gap_fill','Error: "If you will miss the deadline, contact your supervisor." Correct: "If you ___ the deadline, contact your supervisor."','miss',NULL,'If-clause: present simple (no will). Imperative result clause is correct.','medium'),
  (cid,16,114,'multiple_choice','Which sentence correctly uses "unless"?','Unless the data is verified, the results cannot be published.','["Unless the data isn''t verified, the results cannot be published.","Unless if the data is verified, the results cannot be published.","Unless the data is verified, the results cannot be published.","Unless the data will be verified, the results cannot be published."]','"Unless" = "if not." Do NOT add "not" again or "if" alongside it.','hard'),
  (cid,16,115,'gap_fill','Error correction: "As long as you won''t give up, you will succeed." Correct: "As long as you ___ ___ up, you will succeed."','don''t give',NULL,'"As long as" + present simple (not won''t). "As long as you don''t give up."','hard'),

  -- BLOCK 17: TOEFL Reading — conditionals in academic texts
  (cid,17,116,'multiple_choice','[TOEFL Reading] "If deforestation continues at current rates, several species will face extinction within decades." This sentence:','Predicts a real future consequence of a present condition.','["Describes an imaginary scenario","States a scientific law","Predicts a real future consequence of a present condition.","Reports a past event"]','First conditional: real/likely future scenario based on current trend.','easy'),
  (cid,17,117,'gap_fill','[TOEFL Reading] "If antibiotic resistance ___ (continue) to increase, many common infections ___ (become) untreatable." Fill in the conditionals.','continues / will become',NULL,'First conditional: present simple → will + base verb.','medium'),
  (cid,17,118,'multiple_choice','[TOEFL Reading] "Should the central bank raise interest rates, borrowing costs will increase." This formal structure is equivalent to:','If the central bank raises interest rates...','["Although the central bank raises interest rates...","Despite the central bank raising interest rates...","If the central bank raises interest rates...","Unless the central bank raises interest rates..."]','Should + subject + base verb = formal if-clause.','hard'),
  (cid,17,119,'gap_fill','[TOEFL Reading] "If this trend continues, renewable energy ___ account for more than 50% of global power within 20 years."','will / could / may',NULL,'First conditional: present + will/could/may (varying certainty).','medium'),
  (cid,17,120,'multiple_choice','[TOEFL Reading] A passage uses "when" instead of "if": "When temperatures rise, glaciers melt." This choice implies:','The rise in temperature is viewed as certain or inevitable.','["The event is hypothetical","The event happened in the past","The rise in temperature is viewed as certain or inevitable.","This is a second conditional"]','"When" signals expected/certain condition; "if" signals mere possibility.','hard'),
  (cid,17,121,'gap_fill','[TOEFL Reading] "Unless immediate action ___ (take/passive), the ecosystem will collapse." Fill in.','is taken',NULL,'"Unless + passive present simple" in the if-clause.','hard'),
  (cid,17,122,'multiple_choice','[TOEFL Reading] In academic writing, "if" + present is preferred over "if" + future will because:','It is grammatically correct — the if-clause cannot use will for future reference.','["Will is too informal","If + present sounds more polite","It is grammatically correct — the if-clause cannot use will for future reference.","Will is only used in past conditionals"]','Standard grammar rule: if-clause uses present for future reference, not will.','hard'),

  -- BLOCK 18: TOEFL Listening
  (cid,18,123,'multiple_choice','[TOEFL Listening] The professor says: "If we find a pattern in the data, we''ll publish the findings immediately." A student paraphrases this as: "They''ll publish if they find a pattern." Is this accurate?','Yes — both express the same first conditional.','["No — the original uses second conditional","Yes — both express the same first conditional.","No — the original uses zero conditional","No — they changed the meaning"]','Correct paraphrase: same first conditional meaning.','easy'),
  (cid,18,124,'gap_fill','[TOEFL Listening] A professor says: "Unless we get more funding, the project ___ (can/continue) beyond next year." Fill the blank.','can''t continue / won''t continue',NULL,'"Unless" = if not; result clause: negative outcome (can''t/won''t continue).','hard'),
  (cid,18,125,'multiple_choice','[TOEFL Listening] "As long as the sample size remains above 1,000, the results will be statistically valid." This condition is:','A sufficient condition — if it is met, validity is guaranteed.','["A necessary but insufficient condition","An impossible condition","A sufficient condition — if it is met, validity is guaranteed.","A second conditional"]','"As long as" = on the condition that / provided that.','hard'),
  (cid,18,126,'gap_fill','[TOEFL Listening] A student asks: "What happens if the control group shows the same results as the test group?" The professor answers: "If that ___, it ___ mean our intervention had no effect."','happens / will',NULL,'First conditional: if + present → will + base verb.','medium'),
  (cid,18,127,'multiple_choice','[TOEFL Listening] The professor uses "when" instead of "if" to describe an experiment outcome. This suggests:','The professor believes the outcome is likely or expected.','["The outcome is impossible","The conditional is hypothetical","The professor believes the outcome is likely or expected.","The experiment has already been completed"]','"When" signals confidence in the outcome; "if" signals uncertainty.','hard'),

  -- BLOCK 19: TOEFL Speaking production
  (cid,19,128,'production','[TOEFL Speaking — 45s] You have read that air quality in cities will worsen unless governments take action. Discuss two conditions that, if met, could improve urban air quality. Use first conditional in your response.','',NULL,'If governments invest in public transport, fewer cars will be on the road. If electric vehicles become more affordable, citizens will adopt them faster. Unless emissions are regulated, the situation will worsen. When renewable energy replaces coal, air quality will improve significantly.','medium'),
  (cid,19,129,'production','[TOEFL Speaking — 45s] A professor argues that AI will replace many jobs within 20 years. Use first conditional to argue whether you agree or disagree, presenting two "if" scenarios.','',NULL,'If AI continues to advance at its current pace, many routine jobs may disappear. However, if governments invest in retraining programs, workers will adapt. If new industries emerge alongside AI, employment could remain stable. Unless societies plan carefully, economic inequality will likely increase.','hard'),
  (cid,19,130,'production','[TOEFL Speaking — 45s] You are describing a safety protocol to a new laboratory assistant. Use first conditional with imperative result clauses and modal variations (if ... will / might / can / should / call).','',NULL,'If a chemical spills, call the safety officer immediately. If the temperature exceeds the limit, turn off the heating system. If you aren''t sure about a procedure, ask your supervisor before proceeding. If you experience any symptoms, you should leave the lab and seek medical attention immediately.','hard'),

  -- BLOCK 20: TOEFL Writing production
  (cid,20,131,'production','[TOEFL Writing] Write 5 first conditional sentences about the effects of climate change, using: will, may, could, might, and can in the result clauses. All if-clauses should use present simple.','',NULL,'If global temperatures rise by 2°C, sea levels will increase by up to 1 meter. If coral reefs experience continued bleaching, entire marine ecosystems may collapse. If Arctic ice continues to melt, rare species could face extinction within decades. If extreme weather events become more frequent, billions of dollars in damage might be incurred annually. If nations cooperate effectively, they can still limit the worst impacts.','hard'),
  (cid,20,132,'production','[TOEFL Writing — Error Correction] Fix all errors: "If renewable energy will become cheaper, more countries will adopt it. Unless they won''t invest now, they''ll fall behind. As long as technology don''t stagnate, solar power could be competitive."','',NULL,'If renewable energy becomes cheaper (remove will); Unless they invest now (remove won''t — unless already means if not); As long as technology doesn''t stagnate.','hard'),
  (cid,20,133,'production','[TOEFL Writing — Formal Register] Rewrite these first conditionals in formal academic style using inversion (Should + subject + verb) and passive voice where appropriate: 1. "If the trial fails, we will end the program." 2. "If new data emerges, we will revise the model." 3. "If funding is not secured, we will cancel the project."','',NULL,'1. Should the trial fail, the program will be terminated. 2. Should new data emerge, the model will be revised accordingly. 3. Should funding not be secured, the project will be cancelled.','hard'),
  (cid,20,134,'production','[TOEFL Writing] Write a 150-word paragraph on climate policy using: if (×3), unless (×1), as long as (×1), should (formal inversion) (×1), and when (×1). Underline each conditional connector.','',NULL,'If governments commit to zero-emission targets by 2030, the most catastrophic effects of climate change may be avoided. However, unless financial support is provided to developing nations, they will struggle to transition away from fossil fuels. Should major economies fail to lead by example, global momentum will collapse. If renewable energy investment increases, costs will continue to fall. As long as international agreements remain in force, coordinated action is possible. When clean technology becomes universally affordable, the transition will accelerate. If humanity acts now, the window for meaningful change remains open.','hard'),

  -- BLOCK 21: advanced synthesis and capstone
  (cid,21,135,'production','[TOEFL Writing — Capstone] Write a full TOEFL-style body paragraph (150-180 words) arguing that universal access to education reduces poverty. Include: 4 first conditional sentences (mix of will/can/may in result clause), 1 formal inversion (Should...), 1 unless clause, and 1 when clause. Every conditional connector must be grammatically correct.','',NULL,'If all children have access to quality primary education, literacy rates will increase significantly. Should educational investment be prioritized by governments, an entire generation of skilled workers could emerge within two decades. If more individuals complete secondary schooling, unemployment rates may fall, as employers will have a larger pool of qualified candidates. Unless governments address the root causes of educational inequality — including poverty, discrimination, and geography — meaningful reform will remain incomplete. Furthermore, if women receive equal educational access, economic productivity can rise by up to 26%, according to UNESCO estimates. As long as funding is sustained and accountability mechanisms are in place, progress is achievable. When communities gain access to education, the cycle of poverty begins to break. If the evidence from developing nations is considered, education consistently emerges as the most powerful tool for economic development.','hard'),
  (cid,21,136,'multiple_choice','[TOEFL Writing] Which sentence demonstrates the MOST effective use of first conditional in an academic TOEFL essay?','Should economic inequality continue to widen, social cohesion may be irreparably damaged.','["If economic inequality will widen, society would face problems.","Economic inequality is widening, so society has problems.","Should economic inequality continue to widen, social cohesion may be irreparably damaged.","If economic inequality widened, social cohesion might be damaged (second conditional)."]','Formal inversion (Should) + continue + may be = appropriate hedged first conditional in academic register.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
