-- ============================================================
-- SEED EXT 3: Módulo 20 — Academic Connectors (ex 161-215)
-- Novos tópicos: conectores de propósito (so as to / in order that),
-- resultado proporcional (to such an extent / to the point where),
-- qualificação (to some extent / in certain respects), TOEFL
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'academic-connectors';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo academic-connectors não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 31: conectores de propósito avançados
  (cid,31,161,'gap_fill','The researchers simplified the model _____ (so as to) make the findings accessible to a non-specialist audience.','so as to',NULL,'"So as to + infinitive" = purpose connector (formal, continuous with main clause).','medium'),
  (cid,31,162,'multiple_choice','Which purpose connector requires a FULL CLAUSE (with subject)?','In order that the results can be verified, all raw data has been made publicly available.','["In order to verify the results, the data was made available.","So as to ensure accuracy, the team rechecked all calculations.","In order that the results can be verified, all raw data has been made publicly available.","To maintain consistency, the same protocol was applied."]','"In order that + full clause" — requires subject + verb. "In order to" takes infinitive.','hard'),
  (cid,31,163,'gap_fill','The government introduced stricter regulations _____ (so that) future incidents of this kind could be prevented.','so that',NULL,'"So that + clause" = purpose (less formal than ''in order that''; both correct).','medium'),
  (cid,31,164,'multiple_choice','Which sentence uses "lest" correctly?','The researchers documented every step lest the findings later be questioned.','["The researchers documented every step lest they didn''t question the findings.","The researchers documented every step lest the findings later be questioned.","The researchers documented every step lest they will question the findings.","The researchers documented every step, in case the findings later be questioned."]','"Lest + subjunctive" = in case something bad happens (very formal/literary).','hard'),
  (cid,31,165,'gap_fill','The protocol was standardized _____ (with a view to) ensuring reproducibility across laboratories.','with a view to',NULL,'"With a view to + -ing" = purpose connector (formal academic).','hard'),

  -- BLOCK 32: conectores de resultado proporcional
  (cid,32,166,'gap_fill','The temperature dropped _____ (to such an extent) that the experiment had to be suspended.','to such an extent',NULL,'"To such an extent that" = result proportional to degree.','hard'),
  (cid,32,167,'multiple_choice','Which connector expresses a PROPORTIONAL or DEGREE-BASED result?','The pollution became so severe that respiratory disease rates doubled.','["Although pollution increased, respiratory rates doubled.","The pollution became so severe that respiratory disease rates doubled.","Despite the pollution, respiratory disease rates doubled.","As a result of pollution, respiratory disease rates doubled."]','"So + adjective + that" = degree-result structure.','medium'),
  (cid,32,168,'gap_fill','The algorithm was optimized _____ (to the point where) it outperformed all previously published models.','to the point where',NULL,'"To the point where" = result reaching a threshold or peak.','hard'),
  (cid,32,169,'multiple_choice','What is the difference between "so that" (purpose) and "so...that" (result)?','"So that" introduces purpose (intention); "so...that" (with adjective between) introduces result.','["They are identical","''So that'' introduces purpose (intention); ''so...that'' (with adjective between) introduces result.","So that is only for purpose; it can never introduce result","So...that is always about concession"]','"She spoke slowly so that they could understand" (purpose) vs "She spoke so slowly that no one listened" (result).','hard'),
  (cid,32,170,'gap_fill','The economic disruption was _____ (so/widespread) _____ (that) entire industries had to be restructured.','so widespread that',NULL,'"So + adjective + that" = degree-result construction.','medium'),

  -- BLOCK 33: conectores de qualificação e nuance
  (cid,33,171,'gap_fill','_____ (To some extent), the results support the original hypothesis, although important exceptions exist.','To some extent / In part / Partly',NULL,'"To some extent" = partial agreement/qualification. Key hedging connector.','medium'),
  (cid,33,172,'multiple_choice','Which connector signals PARTIAL agreement or qualified support?','The policy has been successful in certain respects, though not universally so.','["However, the policy has been successful.","Furthermore, the policy has been successful.","The policy has been successful in certain respects, though not universally so.","Consequently, the policy has been successful."]','"In certain respects" = qualifies the claim: successful in some ways, not all.','medium'),
  (cid,33,173,'gap_fill','The study findings are _____ (broadly) consistent with previous research, with some notable exceptions in the age group 45-65.','broadly / largely / generally / predominantly',NULL,'Hedging adverbs before "consistent with" = qualify how well findings match prior research.','medium'),
  (cid,33,174,'multiple_choice','In academic writing, which phrase introduces a qualification MOST precisely?','While the evidence broadly supports this interpretation, it must be acknowledged that significant variability remains.','["Despite this, the evidence supports the interpretation.","However, the evidence supports the interpretation.","While the evidence broadly supports this interpretation, it must be acknowledged that significant variability remains.","Therefore, the evidence supports the interpretation."]','"While... broadly supports... must be acknowledged" = layered qualification.','hard'),
  (cid,33,175,'gap_fill','The treatment is _____ (to a considerable degree) effective in early-stage cases, though less so in advanced presentations.','to a considerable degree / highly / substantially / largely',NULL,'"To a considerable degree" = strong qualification adverbial.','hard'),

  -- BLOCK 34: conectores de causa-efeito encadeados
  (cid,34,176,'gap_fill','Climate change has disrupted traditional growing seasons, _____ (consequently) reducing crop yields and threatening food security.','consequently',NULL,'"Consequently" = cause-effect connector. Result clause follows.','easy'),
  (cid,34,177,'multiple_choice','Which sentence uses "thereby" correctly?','The research team streamlined the protocol, thereby reducing the time required for each trial by 40%.','["The research team streamlined the protocol. Thereby reducing the time required for each trial.","The research team streamlined the protocol; thereby, reducing the time.","The research team streamlined the protocol, thereby reducing the time required for each trial by 40%.","Thereby, the research team streamlined the protocol and reduced the time."]','"Thereby + -ing" = connector showing the mechanism of consequence. No subject needed.','hard'),
  (cid,34,178,'gap_fill','Increased automation has eliminated many routine tasks, _____ (thus/freeing) workers to focus on higher-value activities.','thus freeing',NULL,'"Thus + -ing" = shows the resulting action/state. Formal academic.','hard'),
  (cid,34,179,'multiple_choice','Which causal connector BEST introduces the MECHANISM by which a result occurred?','The new drug binds to the receptor more selectively, thereby reducing the incidence of side effects.','["The new drug binds to the receptor more selectively; as a result, side effects decrease.","The new drug binds to the receptor more selectively; therefore, side effects decrease.","The new drug binds to the receptor more selectively, thereby reducing the incidence of side effects.","The new drug binds to the receptor more selectively because side effects decrease."]','"Thereby + -ing" = shows the mechanism (the ''how''), not just the result.','hard'),

  -- BLOCK 35: TOEFL Reading
  (cid,35,180,'multiple_choice','[TOEFL Reading] "The researchers standardized the protocol so as to eliminate variability across sites." The connector "so as to" expresses:','Purpose — the reason for standardizing the protocol.','["Contrast","Cause","Purpose — the reason for standardizing the protocol.","Result"]','"So as to" = purpose connector. Equivalent to "in order to."','easy'),
  (cid,35,181,'gap_fill','[TOEFL Reading] "Industrial emissions increased _____ (to such an extent) that air quality in major cities fell below WHO safety thresholds." Best connector?','to such an extent',NULL,'"To such an extent that" = degree-result in formal academic text.','medium'),
  (cid,35,182,'multiple_choice','[TOEFL Reading] "The findings are broadly consistent with the existing literature, though important differences remain in the pediatric cohort." "Broadly" is used to:','Qualify the degree of consistency — not perfectly, but mostly.','["State absolute certainty","Introduce a contrast","Qualify the degree of consistency — not perfectly, but mostly.","Signal a causal relationship"]','"Broadly" = hedging adverb that qualifies the strength of a claim.','easy'),
  (cid,35,183,'gap_fill','[TOEFL Reading] "Technological innovation _____ (thus) enables smaller enterprises to compete with established multinational corporations." "Thus" functions as:','Thus = causal connector showing logical result.','Thus / thereby',NULL,'"Thus" = "as a result / therefore" in academic cause-effect chains.','medium'),

  -- BLOCK 36: TOEFL Speaking
  (cid,36,184,'production','[TOEFL Speaking — 45s] A reading discusses urban heat islands and their effects. Use: so as to, in order that, to such an extent, consequently, thereby, to some extent.','',NULL,'Urban heat islands are a serious environmental challenge. Cities absorb and retain heat to such an extent that urban temperatures can be five to ten degrees higher than surrounding rural areas. Consequently, energy demand for cooling increases sharply, thereby driving up carbon emissions from power generation. City planners are now exploring a range of mitigation strategies: increasing green cover so as to shade surfaces and lower temperatures through evapotranspiration; redesigning streets in order that air circulation is improved; and using reflective materials on rooftops. To some extent these measures can reduce the intensity of heat islands, though eliminating them entirely in densely built environments may be beyond reach without more fundamental changes to urban form.','hard'),
  (cid,36,185,'production','[TOEFL Speaking — 45s] Discuss the pros and cons of remote work. Use: to a considerable degree, in certain respects, broadly speaking, so that, in order to, thereby, to the point where.','',NULL,'Remote work has transformed professional life to a considerable degree, with both genuine benefits and meaningful drawbacks. Broadly speaking, the flexibility to work from home increases employee satisfaction and reduces commuting time, thereby improving work-life balance. In certain respects, remote work also supports environmental goals by reducing traffic and office energy consumption. Companies have redesigned communication workflows so that collaboration can occur asynchronously across time zones. However, remote work arrangements can go wrong to the point where isolation and miscommunication begin to erode team cohesion and organizational culture. In order to sustain the benefits, companies need to invest in intentional connection-building and clear norms around availability and response times.','hard'),

  -- BLOCK 37: TOEFL Writing
  (cid,37,186,'production','[TOEFL Writing — 150 words] Write an academic paragraph on "The impact of digital technology on reading habits." Use: in order to, so as to, to such an extent, thereby, consequently, broadly speaking, to some extent, with a view to.','',NULL,'Digital technology has altered reading habits to such an extent that book publishers have had to fundamentally redesign their distribution and marketing strategies. Broadly speaking, readers now access more content than ever before, though whether depth of engagement has increased is contested. Online platforms have been designed so as to maximize the time users spend scrolling, thereby fragmenting attention in ways that make sustained long-form reading more challenging. Consequently, research suggests that comprehension of complex texts declines among frequent digital media consumers. To some extent, digital tools have supported reading: e-readers and audiobooks have made content accessible to people with visual impairments or learning differences. Publishers are now investing in hybrid formats with a view to serving readers who want both the convenience of digital access and the cognitive benefits associated with reading printed texts.','hard'),
  (cid,37,187,'production','[TOEFL Writing — Error Correction] Fix academic connector errors: "The researchers simplified the model in order that make it accessible. The pollution became so that respiratory disease rates doubled. Thereby, they reduced errors. The evidence broadly consistent with prior research. The drug was administered so as the patient could recover."','',NULL,'in order that make it → in order to make it (in order that + full clause; in order to + infinitive); so that respiratory → so severe that (so + adjective + that for degree-result); Thereby, they reduced errors → They thereby reduced errors / They reduced errors, thereby minimizing X (thereby precedes the verb or introduces a participial phrase, not a sentence start alone); broadly consistent → is broadly consistent (missing verb ''is''); so as the patient → so that the patient (so as takes infinitive: so as to; so that takes a clause).','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
