-- ============================================================
-- SEED EXT 5: Módulo 09 — Conditional Type 1 (ex 194-265)
-- Novos tópicos: Type 1 em documentos legais e científicos,
-- Type 1 com modais na apódose, Type 1 em TOEFL avançado
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'conditional-1';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo conditional-1 não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 51: Type 1 com modais na apódose (may/might/can/should)
  (cid,51,194,'gap_fill','If the results _____ (replicate) in a larger sample, this finding _____ (have) significant implications for clinical practice.','are replicated / may have / could have',NULL,'''If + present passive + may/could have'' = real conditional with hedged certainty.','hard'),
  (cid,51,195,'gap_fill','If the temperature _____ (drop) below 4°C, pipes _____ (burst) and structural damage _____ (occur).','drops / may burst / could occur',NULL,'Type 1 with may/could for possible (not certain) consequences.','medium'),
  (cid,51,196,'multiple_choice','Which Type 1 conditional uses ''should'' in the result clause MOST appropriately?','If you encounter any discrepancies in the data, you should report them to the principal investigator immediately.','[''If you encounter discrepancies, you will report them.'',''If you encounter any discrepancies in the data, you should report them to the principal investigator immediately.'',''If you encounter discrepancies, you might report them.'',''If you will encounter discrepancies, you should report them.'']','''Should'' in result clause = obligation/advice in Type 1.','medium'),
  (cid,51,197,'gap_fill','If further evidence _____ (emerge) supporting this hypothesis, researchers _____ (need) to fundamentally revise the current theoretical model.','emerges / will need / may need',NULL,'Type 1: if + PS + will/may + need to.','easy'),
  (cid,51,198,'gap_fill','If carbon concentrations _____ (exceed) 450 ppm, the probability of exceeding 2°C of warming _____ (increase) dramatically.','exceed / will increase / increases',NULL,'Scientific fact conditional: if + PS + will/PS.','medium'),
  (cid,51,199,'multiple_choice','Which sentence uses a MODAL in the result clause for ADVICE rather than prediction?','If you are struggling with the essay structure, you might want to outline your argument before you draft.','[''If you are struggling, you will want to outline your argument.'',''If you are struggling with the essay structure, you might want to outline your argument before you draft.'',''If you struggle, you may outline your argument.'',''If you will be struggling, you might outline.'']','''Might want to'' = soft advice in Type 1 result clause.','medium'),

  -- BLOCK 52: Type 1 em textos legais e regulatórios
  (cid,52,200,'gap_fill','If a party _____ (fail) to comply with the terms of this agreement, the other party _____ (be) entitled to seek remedies under applicable law.','fails / shall be / will be',NULL,'''Shall be'' = legal Type 1 result clause (formal obligation).','hard'),
  (cid,52,201,'gap_fill','If the data _____ (collect/passive) in a manner inconsistent with the approved protocol, the study _____ (suspend/passive) pending review.','is collected / will be suspended / shall be suspended',NULL,'Type 1 passive in both clauses for legal/regulatory procedure.','hard'),
  (cid,52,202,'multiple_choice','In legal documents, which result clause is most appropriate in a Type 1 conditional?','''If either party breaches this agreement, the non-breaching party shall be entitled to seek damages.''','[''If either party breaches, the non-breaching party might seek damages.'',''If either party breaches this agreement, the non-breaching party shall be entitled to seek damages.'',''If either party breaches, the non-breaching party seeks damages.'',''If either party would breach, the non-breaching party shall seek damages.'']','''Shall be entitled'' = legal Type 1 result: formal obligation/entitlement language.','hard'),
  (cid,52,203,'gap_fill','If adverse effects _____ (report/passive), the clinical trial _____ (halt/passive) immediately and a safety review _____ (conduct/passive).','are reported / will be halted / will be conducted',NULL,'Type 1 passive sequence for clinical trial safety protocol.','hard'),
  (cid,52,204,'gap_fill','If a disclosure _____ (require/passive) under the applicable regulations, the company _____ (provide) it within 30 business days.','is required / shall provide / will provide',NULL,'''If + passive + shall/will provide'' = legal obligation conditional.','hard'),

  -- BLOCK 53: Type 1 científico — hipóteses e previsões
  (cid,53,205,'gap_fill','If the intervention _____ (prove) effective in Phase II trials, it _____ (advance) to Phase III for large-scale efficacy testing.','proves / will advance / shall advance',NULL,'Scientific procedure Type 1: if + PS + will + base verb.','easy'),
  (cid,53,206,'gap_fill','If X _____ (cause) Y, then we _____ (predict) that manipulating X _____ (also/change) Y, which _____ (precisely/what) this study tests.','causes / predict / will also change / is precisely what',NULL,'Logical-causal Type 1: experimental hypothesis statement.','hard'),
  (cid,53,207,'multiple_choice','Which sentence BEST states a scientific hypothesis as a Type 1 conditional?','If the proposed mechanism is correct, then organisms deprived of X should exhibit measurably lower levels of Y.','[''If the proposed mechanism is correct, then organisms deprived of X exhibited lower Y.'',''If the proposed mechanism is correct, then organisms deprived of X should exhibit measurably lower levels of Y.'',''If the proposed mechanism would be correct, then organisms deprived of X should exhibit lower Y.'',''If the proposed mechanism is correct, then organisms deprived of X would exhibit lower Y (Type 2 — wrong).'']','If + PS (hypothesis) + should + base verb (testable prediction) = scientific conditional.','hard'),
  (cid,53,208,'gap_fill','If warming _____ (exceed) 1.5°C, many low-lying islands _____ (face) severe flooding during storm surges, and agricultural yields in tropical regions _____ (decline) significantly.','exceeds / will face / will decline',NULL,'Policy-relevant scientific Type 1: if warming threshold → multiple consequences.','easy'),
  (cid,53,209,'gap_fill','If the null hypothesis _____ (reject/passive) at the 0.05 significance level, we _____ (conclude) that there _____ (be) a statistically significant relationship.','is rejected / will conclude / is',NULL,'Statistical interpretation Type 1: if + PS passive + will + conclude.','medium'),

  -- BLOCK 54: Type 1 avançado — casos especiais
  (cid,54,210,'gap_fill','If the meeting _____ (conclude) before 5 pm, we _____ (aim) to distribute the minutes by the following morning.','concludes / will aim',NULL,'Type 1 for scheduled events with planned response.','easy'),
  (cid,54,211,'gap_fill','Even if the initial results _____ (disappoint), the team _____ (not/abandon) the research program without further investigation.','are disappointing / will not abandon',NULL,'''Even if'' = regardless of condition. Still uses PS + will.','medium'),
  (cid,54,212,'multiple_choice','What does ''unless'' mean in ''Unless the proposal is revised, the committee will reject it''?','If the proposal is NOT revised, the committee will reject it.','[''If the proposal is revised, the committee will reject it'',''If the proposal is NOT revised, the committee will reject it.'',''Even though the proposal is revised, the committee will reject it'',''Whether or not the proposal is revised, the committee will reject it'']','''Unless'' = ''if not.'' Unless + PS = if + PS + NOT.','easy'),
  (cid,54,213,'gap_fill','Unless significant progress _____ (make/passive) before the deadline, the project _____ (risk) losing its funding.','is made / will risk',NULL,'''Unless + PS passive + will'' = conditional with negative condition.','medium'),
  (cid,54,214,'multiple_choice','Which Type 1 conditional uses ''provided that'' correctly?','Provided that all ethical requirements are met, the study may proceed.','[''Provided that all ethical requirements met, the study may proceed.'',''Provided that all ethical requirements are met, the study may proceed.'',''Providing all ethical requirements would be met, the study may proceed.'',''Provided all ethical requirements are met, the study may proceed.'']','''Provided that + PS'' = conditional with specific limiting condition (= if and only if).','medium'),
  (cid,54,215,'gap_fill','As long as the team _____ (maintain) data security protocols, the external auditors _____ (have) no grounds for concern.','maintains / will have',NULL,'''As long as + PS + will'' = Type 1 with positive condition.','easy'),

  -- BLOCK 55: TOEFL Reading
  (cid,55,216,'multiple_choice','[TOEFL Reading] ''If soil degradation continues at its current rate, an estimated 40% of arable land will be unusable within 50 years.'' This conditional implies:','A serious predictive warning based on current trends.','[''A hypothetical scenario that is unlikely'',''A serious predictive warning based on current trends.'',''A past completed problem'',''A situation that is already resolved'']','Type 1: real, possible future if current trend continues.','easy'),
  (cid,55,217,'gap_fill','[TOEFL Reading] ''If the proposed legislation _____ (pass), renewable energy installations _____ (eligible) for enhanced tax credits.'' Best forms?','passes / will be eligible / will be',NULL,'Type 1 for legislation: if + PS + will + base verb.','easy'),
  (cid,55,218,'multiple_choice','[TOEFL Reading] In a medical consent form: ''If you experience side effects, you should contact the trial coordinator immediately.'' The result clause ''should contact'' expresses:','An obligation/advice (not a prediction) in the Type 1 result.','[''Certainty about future events'',''A hypothetical'',''An obligation/advice (not a prediction) in the Type 1 result.'',''A past recommendation'']','''Should'' in Type 1 result = directive/advice to participant.','medium'),
  (cid,55,219,'gap_fill','[TOEFL Reading] ''If a country _____ (fail) to meet its emission reduction targets, _____ (face/passive) financial penalties under the new enforcement mechanism.'' Best forms?','fails / it will be faced with / it faces',NULL,'Type 1 for treaty enforcement: if + PS + will face/be faced with.','medium'),

  -- BLOCK 56: TOEFL Speaking
  (cid,56,220,'production','[TOEFL Speaking — 45s] A reading describes a proposed environmental policy. The professor argues it will only work under certain conditions. Summarize using Type 1 conditionals.','',NULL,'The reading advocates for a carbon tax as the most efficient mechanism for reducing greenhouse gas emissions. However, the professor argues that the carbon tax will only achieve its intended goals under specific conditions. If the tax is set at a high enough level — most economists argue at least $50 per tonne — it will provide a sufficient price signal to shift investment toward low-carbon alternatives. If revenue is recycled to low-income households through dividend payments, it will avoid the regressive distributional impact that has undermined public support for similar policies elsewhere. The professor further notes that if border adjustment mechanisms are not implemented simultaneously, carbon-intensive industries will relocate to countries without carbon pricing, reducing domestic emissions while shifting them abroad. If all three conditions are met, the professor concedes, the policy should work; if any of them is absent, however, its effectiveness will be severely compromised.','hard'),
  (cid,56,221,'production','[TOEFL Speaking — 45s] Discuss what will happen to higher education if current trends continue. Use Type 1 conditionals throughout.','',NULL,'If current trends in higher education costs continue, access to university education will become increasingly stratified by income. If student debt continues to rise faster than graduate earnings, fewer young people from lower-income backgrounds will consider university an economically rational investment. At the same time, if online learning platforms continue to improve in quality and credibility, many students may choose flexible, lower-cost digital alternatives to traditional residential degrees. If employers increasingly value demonstrable skills over formal credentials, the monopoly that degree programs currently hold on access to many high-skilled careers will weaken significantly. Conversely, if universities successfully differentiate themselves as places for deep intellectual development and social networking rather than merely credential delivery, they will remain valuable even in a highly competitive educational landscape. If they fail to make this case convincingly, they will face serious challenges to their traditional business model.','hard'),

  -- BLOCK 57: TOEFL Writing
  (cid,57,222,'production','[TOEFL Writing — 150 words] Write a paragraph on climate policy using Type 1 conditionals with varied result clause modals.','',NULL,'The success of international climate policy will depend on a chain of conditional relationships that must be managed simultaneously. If major emitting countries commit to ambitious nationally determined contributions at the next climate summit, the credibility of the multilateral framework will be substantially restored. If governments invest adequately in clean energy research and deployment, the cost curves for emerging technologies such as green hydrogen and long-duration storage will continue falling, making decarbonization progressively cheaper. If border carbon adjustments are implemented by major trading blocs, carbon leakage will be reduced and laggard countries will face stronger economic incentives to adopt comparable domestic carbon pricing. If civil society organizations maintain public pressure on governments and corporations, accountability mechanisms will be more rigorously enforced. Unless all of these conditions are substantially met, the 1.5°C target will become unreachable, and adaptation to considerably more severe climate change impacts will become the primary policy challenge.','hard'),
  (cid,57,223,'production','[TOEFL Writing — Error Correction] Fix Type 1 errors: ''If temperatures will rise, coral reefs will bleach. If the study would confirm the hypothesis, researchers will publish. Unless additional funding will be secured, the program shall be cancelled. Provided that the results are positive, the company will be proceeding.''','',NULL,'will rise → rise (if-clause = present simple, not future); would confirm → confirms (if-clause Type 1 = PS, not would); will be secured → is secured (unless + PS, same rule as if); will be proceeding → will proceed (result clause = will + base verb, not future continuous unless specific emphasis on ongoing action).','hard'),

  -- BLOCK 58: Consolidação final
  (cid,58,224,'production','[TOEFL Writing — 200 words] Write a paragraph on public health policy using at least 6 Type 1 conditionals with varied if/unless/provided that/as long as/even if constructions.','',NULL,'Effective public health policy requires careful attention to the conditions under which interventions succeed or fail. If vaccination coverage falls below 95% for highly contagious diseases like measles, herd immunity will be compromised and outbreaks will become more likely. Unless governments maintain robust surveillance systems, emerging infectious diseases will not be detected early enough for containment measures to be effective. Provided that primary care networks are adequately funded and staffed, they can serve as the first line of defense against chronic disease burden that otherwise creates enormous demand for expensive hospital care. Even if a new treatment proves highly effective in clinical trials, it will not reduce population-level disease burden if it is too expensive for most patients to access or too complex for healthcare workers in resource-limited settings to administer. As long as tobacco, alcohol, and ultra-processed food industries retain their current political influence over nutrition and public health regulation, preventive health measures will face structural opposition that limits their scope and effectiveness. If, on the other hand, governments strengthen their regulatory capacity and resist industry pressure, the potential gains in life expectancy and healthy years of life are substantial and achievable.','hard'),
  (cid,58,225,'production','[TOEFL Speaking — 60s] Discuss what will happen to global food security if climate change continues on its current trajectory. Use Type 1 conditionals, unless, even if, and provided that.','',NULL,'If the trajectory of climate change is not substantially altered within the next decade, the impacts on global food security will be severe and unevenly distributed. If temperatures continue to rise at their current rate, crop yields for the world''s staple grains — wheat, rice, and maize — will decline in tropical and subtropical regions where production is already heat-stressed. Unless irrigation infrastructure is dramatically expanded and made more water-efficient, agriculture in semi-arid regions will face increasing water stress as snowpack diminishes and precipitation patterns shift. Even if crop yields in temperate northern regions increase as longer growing seasons and higher CO₂ concentrations benefit some agricultural systems, these gains will not compensate for losses in the most food-insecure regions, which tend to be in tropical areas already facing the greatest climate stress. Provided that significant investment is made in drought-resistant crop varieties, improved storage systems to reduce post-harvest losses, and agricultural extension services that help smallholder farmers adapt, the worst outcomes can be mitigated. If governance systems ensure that this investment reaches the most vulnerable farming communities, food security can be maintained even under moderate climate change scenarios — but this will require sustained political will and international cooperation that has so far been insufficient to the scale of the challenge.','hard'),
  (cid,58,226,'production','[TOEFL Writing — 200 words] Write a body paragraph on technology policy using Type 1 conditionals at least 5 times.','',NULL,'The governance of digital technology stands at a crossroads that will define whether innovation serves broadly shared human welfare or primarily the interests of a small number of platform companies. If antitrust enforcement agencies develop new analytical frameworks suited to digital markets — where network effects, data advantages, and platform lock-in create durable monopoly power through mechanisms that traditional competition law was not designed to address — the competitive dynamics of the digital economy will improve substantially. If mandatory data portability and interoperability requirements are imposed on dominant platforms, users will regain some degree of choice and competition will function more effectively. Unless transparency requirements are extended to algorithmic recommendation systems, the public and regulators will remain unable to evaluate whether these systems are amplifying harmful content for commercial reasons. If independent auditing of AI systems is required before deployment in high-stakes domains, a significant source of algorithmic harm will be addressed. Provided that these regulatory measures are adopted in a coordinated manner across major jurisdictions — rather than piecemeal in a way that creates compliance complexity without achieving competitive reform — the digital ecosystem will become substantially more competitive, innovative, and safe. The window for effective governance intervention appears to be narrowing as market concentration deepens.','hard'),
  (cid,58,227,'gap_fill','If the proposed reforms _____ (implement/passive) effectively, public confidence in the institution _____ (likely/restore/passive); if they _____ (not/accompany/passive) by genuine cultural change, however, the structural improvements _____ (not/sufficient/prove/passive).','are implemented / is likely to be restored / are not accompanied / will not prove sufficient',NULL,'Type 1 double conditional: positive + contrasting negative condition.','hard'),
  (cid,58,228,'production','[TOEFL Writing — Final 200 words] Write a conclusion for a TOEFL essay on ''Can international cooperation solve climate change?'' Use Type 1 conditionals, unless/provided that, and academic hedging.','',NULL,'This essay has argued that international cooperation is a necessary but not sufficient condition for effective climate action, and the evidence examined suggests that whether it can ''solve'' climate change depends critically on the quality, ambition, and inclusiveness of the cooperation achieved. If the major emitting countries — China, the United States, India, the European Union, and a handful of others — commit to and implement nationally determined contributions consistent with a 1.5°C or 2°C pathway, the physical science indicates that the target remains achievable. If complementary measures — carbon pricing, technology transfer to developing nations, and loss and damage finance — are implemented alongside mitigation commitments, the political sustainability of the multilateral process will be substantially stronger. Unless the governance of international climate cooperation is reformed to ensure meaningful participation by the most climate-vulnerable nations, whose interests have so far been systematically subordinated to those of major emitters, the legitimacy of any agreement will be undermined. Provided that these conditions are met and that domestic political systems in major countries are able to sustain climate policy commitments across election cycles, international cooperation can contribute decisively to keeping warming within manageable bounds. The honest assessment, however, is that the current trajectory falls significantly short of what these conditions require.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
