-- ============================================================
-- SEED: Módulo 23 — Advanced Modals (C1)
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'advanced-modals';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo advanced-modals não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 1: Must / Can't for Deduction (Present)
  (cid,1,1,'gap_fill','She passed all her exams with perfect scores. She _____ be extremely intelligent and hardworking.','must',NULL,'"Must" for logical deduction from evidence. → She must be intelligent. ("Can''t be" for negative deduction.)','medium'),
  (cid,1,2,'multiple_choice','The lights are off and there''s no car in the driveway. They _____ be home.','can''t','["must","can''t","might not","shouldn''t"]','"Can''t be" = logical deduction of impossibility. → They can''t be home (the evidence suggests they''re not).','medium'),
  (cid,1,3,'gap_fill','The temperature in that room is 50°C. It _____ be incredibly uncomfortable to work there.','must',NULL,'"Must" for strong logical deduction based on objective evidence. → It must be incredibly uncomfortable.','easy'),
  (cid,1,4,'multiple_choice','This 400-page book was written in three days. The author _____ have taken any time for research.','can''t','["must","can''t","shouldn''t","needn''t"]','"Can''t have taken" = deduction of past impossibility. → The author can''t have taken time for research.','hard'),
  (cid,1,5,'gap_fill','He has been studying for 14 hours straight. He _____ be exhausted by now.','must',NULL,'"Must be" = present deduction based on the known facts. The exhaustion is logically certain.','easy'),
  (cid,1,6,'multiple_choice','She knew all the answers without looking at her notes. She _____ the material very well.','must know','["can know","must know","should know","could know"]','"Must know" = present deduction. The evidence (knowing all answers) points to this logical conclusion.','medium'),
  (cid,1,7,'gap_fill','The figures don''t add up at all. There _____ be an error in the calculations somewhere.','must',NULL,'"There must be" = deduction based on logical inconsistency. → There must be an error in the calculations.','easy'),
  (cid,1,8,'multiple_choice','Which sentence uses "can''t" for deduction correctly?','The sample size is only 10. The results can''t be statistically significant.','["The sample size is only 10. The results must not be statistically significant.","The sample size is only 10. The results can''t be statistically significant.","The sample size is only 10. The results shouldn''t be statistically significant.","The sample size is only 10. The results don''t have to be statistically significant."]','"Can''t be" expresses logical impossibility/strong negative deduction. → The results can''t be statistically significant.','medium'),

  -- BLOCK 2: Might / Could / May for Past Speculation
  (cid,2,9,'gap_fill','He didn''t answer the phone. He _____ (sleep) at the time.','might have been sleeping / could have been sleeping',NULL,'"Might/could have been + -ing" = speculation about a past continuous action. Either is correct.','hard'),
  (cid,2,10,'multiple_choice','The artifact was found deep underground. It _____ hundreds of years ago.','could have been buried','["might bury","could have been buried","must bury","should bury"]','"Could have been buried" = speculation about a past passive action. Appropriate for archaeological uncertainty.','hard'),
  (cid,2,11,'gap_fill','The experiment failed unexpectedly. The equipment _____ (malfunction) during the critical phase.','may have malfunctioned / might have malfunctioned',NULL,'"May/might have + past participle" = past speculation about a possible cause. → may have malfunctioned.','hard'),
  (cid,2,12,'multiple_choice','No one saw what caused the accident. The driver _____ fallen asleep at the wheel.','might have','["might have","should have","must have been","need have"]','"Might have fallen" = past speculation (one possible explanation among several). Appropriate for uncertainty.','hard'),
  (cid,2,13,'gap_fill','The manuscript was unsigned. It _____ (write) by any one of several scholars of the period.','could have been written',NULL,'"Could have been written" = passive past speculation. → It could have been written by any of several scholars.','hard'),
  (cid,2,14,'multiple_choice','The fossilized remains suggest the creature _____ reached a length of 12 meters.','may have','["must have been","may have","should have","need have"]','"May have reached" = cautious past speculation based on fossil evidence. Appropriate for scientific hedging.','hard'),
  (cid,2,15,'gap_fill','Nobody knows why the colony was abandoned. The inhabitants _____ (flee) due to famine or disease.','may have fled / might have fled / could have fled',NULL,'Any of the three modals (may/might/could) + have fled = past speculation about an unknown historical event.','hard'),
  (cid,2,16,'multiple_choice','Which sentence correctly expresses past speculation about a cause?','The results varied significantly between groups; this could have been due to sampling bias.','["The results varied; this must have due to sampling bias.","The results varied; this could have been due to sampling bias.","The results varied; this might be due to sampling bias.","The results varied; this should have been due to sampling bias."]','"Could have been due to" = correct past speculation about a possible cause. → could have been due to sampling bias.','hard'),

  -- BLOCK 3: Should Have / Needn't Have for Past Criticism & Regret
  (cid,3,17,'gap_fill','They made a serious methodological error. They _____ (use) a larger sample size.','should have used',NULL,'"Should have + past participle" = criticism of a past action (or failure to act). → They should have used.','hard'),
  (cid,3,18,'multiple_choice','She studied all night for the wrong exam. She _____ the schedule more carefully.','should have checked','["should check","should have checked","ought to check","must have checked"]','"Should have checked" = retrospective criticism/regret for a past failure. → She should have checked the schedule.','hard'),
  (cid,3,19,'gap_fill','You _____ (not worry) so much — the results came back completely normal.','needn''t have worried',NULL,'"Needn''t have + past participle" = past action that turned out to be unnecessary. → needn''t have worried.','hard'),
  (cid,3,20,'multiple_choice','He brought his umbrella, but it was sunny all day. He _____ it.','needn''t have brought','["shouldn''t bring","needn''t have brought","mustn''t have brought","didn''t need bring"]','"Needn''t have brought" = the action was done but turned out to be unnecessary. → needn''t have brought.','hard'),
  (cid,3,21,'gap_fill','The experiment was contaminated because the researcher forgot to sterilize the equipment. She _____ (sterilize) it.','should have sterilized',NULL,'"Should have sterilized" = criticism/reproach for a past failure that led to negative consequences.','hard'),
  (cid,3,22,'multiple_choice','The students submitted their essays a week early. They _____ so quickly — the deadline is still next week.','needn''t have submitted','["shouldn''t submit","needn''t have submitted","mustn''t have submitted","didn''t need to submit"]','"Needn''t have submitted" = they did it, but it was unnecessary. Different from "didn''t need to" (may not have done it).','hard'),
  (cid,3,23,'gap_fill','The committee rejected the proposal. They _____ (consider) the long-term economic implications more carefully.','should have considered',NULL,'"Should have considered" = retrospective criticism of the committee''s decision-making process.','hard'),
  (cid,3,24,'multiple_choice','What is the difference between "He didn''t need to attend" and "He needn''t have attended"?','"He didn''t need to attend" = he didn''t attend (not necessary); "He needn''t have attended" = he attended, but it was unnecessary.','["They mean exactly the same thing.","\"He didn''t need to attend\" = he didn''t attend (not necessary); \"He needn''t have attended\" = he attended, but it was unnecessary.","\"Needn''t have\" is simply more formal.","\"Didn''t need to\" is used for future events only."]','"Needn''t have" = action was done but was unnecessary. "Didn''t need to" = uncertain whether action was done; it was not required.','hard'),

  -- BLOCK 4: Would for Past Habits & Ought To vs Should
  (cid,4,25,'gap_fill','When she was a graduate student, she _____ (work) late into the night, often until 3am.','would work',NULL,'"Would + base verb" for repeated past habits. → she would work late into the night. Like "used to."','medium'),
  (cid,4,26,'multiple_choice','As children, they _____ spend summers at their grandmother''s house in the countryside.','would','["used","would","should","might"]','"Would + base verb" for past repeated habits. → they would spend summers at their grandmother''s house.','medium'),
  (cid,4,27,'gap_fill','The senior researcher _____ (always / arrive) before everyone else and set up the equipment.','would always arrive',NULL,'"Would always + base verb" for a characteristic past habit. → would always arrive and set up.','medium'),
  (cid,4,28,'multiple_choice','You _____ acknowledge the contributions of your collaborators in the acknowledgments section.','ought to','["must","ought to","needn''t","should have"]','"Ought to" expresses a moral obligation or expectation — similar to "should" but with a slightly stronger moral implication.','medium'),
  (cid,4,29,'gap_fill','The results _____ (ought) be interpreted with caution given the limitations of the study.','ought to',NULL,'"Ought to" for a moral/logical recommendation. → the results ought to be interpreted with caution.','medium'),
  (cid,4,30,'multiple_choice','What is the key difference between "should" and "ought to"?','They are nearly identical; "ought to" is slightly more formal and carries a stronger sense of moral obligation.','["\"Should\" is stronger than \"ought to.\"","They are nearly identical; \"ought to\" is slightly more formal and carries a stronger sense of moral obligation.","\"Ought to\" is only used for past habits.","\"Should\" can only be used in questions."]','"Ought to" and "should" are very similar. "Ought to" slightly emphasizes moral obligation or what is proper/expected.','hard'),
  (cid,4,31,'gap_fill','She _____ (need / not) resubmit the entire application — only the supporting documents were required.','needn''t / need not',NULL,'"Need not" = it is not necessary. Present, formal version: "need not resubmit."','hard'),
  (cid,4,32,'multiple_choice','Which sentence correctly uses "would" for a past habit?','He would spend hours in the library, reading everything he could find on the subject.','["He would have spent hours in the library as a student.","He used to would spend hours in the library.","He would spend hours in the library, reading everything he could find on the subject.","He would spending hours in the library reading."]','"Would + base verb" (not "used to would" or "would have"). → He would spend hours in the library.','medium'),

  -- BLOCK 5: TOEFL Academic – Modals in Reading
  (cid,5,33,'gap_fill','[TOEFL Reading] The lack of written records means the civilization _____ (must / disappear) long before European contact.','must have disappeared',NULL,'"Must have disappeared" = strong past deduction based on the evidence (lack of written records).','hard'),
  (cid,5,34,'multiple_choice','[TOEFL Reading] "The anomaly in the data _____ be the result of a transcription error or instrument calibration failure." Which best completes the sentence?','could','["must","can''t","could","should"]','"Could be" = present speculation about a possible explanation. Appropriate for uncertain academic conclusions.','medium'),
  (cid,5,35,'gap_fill','[TOEFL Reading] The researchers noted that early intervention _____ (should / significantly / improve) long-term health outcomes.','should significantly improve',NULL,'"Should + base verb" = expectation or recommendation. → early intervention should significantly improve outcomes.','medium'),
  (cid,5,36,'multiple_choice','[TOEFL Reading] "The authors argue that the decline in insect populations _____ caused by a combination of habitat loss, pesticide use, and climate change."','may have been','["must be","may have been","should be","can''t have been"]','"May have been caused" = past speculation with uncertainty. Appropriate for complex multi-factor causal claims.','hard'),
  (cid,5,37,'gap_fill','[TOEFL Listening] The professor noted: "The original data set _____ (not include) certain demographic groups, which would explain the skewed results."','may not have included / might not have included',NULL,'"May/might not have included" = past speculation about a possible methodological limitation.','hard'),
  (cid,5,38,'multiple_choice','[TOEFL Reading] "The scientists _____ more rigorous controls during the initial phase of the study." What does this sentence express?','criticism of what they failed to do','["praise for what they did","a prediction about the future","criticism of what they failed to do","certainty about the study method"]','Should have + past participle = retrospective criticism or reproach for a past failure.','medium'),
  (cid,5,39,'gap_fill','[TOEFL Reading] The patient population in this study _____ (can''t / represent) the broader population, given the narrow age range selected.','can''t represent',NULL,'"Can''t represent" = logical deduction of present impossibility based on the narrow age range mentioned.','hard'),
  (cid,5,40,'multiple_choice','[TOEFL Listening] "In my experience, graduate students _____ arrive early to the lab, check equipment, and begin preliminary readings before their supervisor arrived." Which modal is used for past habits?','would','["should","would","must","could"]','"Would + base verb" = past habit pattern. → students would arrive, check, and begin. Like "used to."','medium'),

  -- BLOCK 6: TOEFL Academic – Distinguishing Modal Meanings
  (cid,6,41,'multiple_choice','[TOEFL Reading] Choose the modal that expresses the strongest certainty about the PRESENT: "He _____ be aware of the research — it was published in the journal he edits."','must','["may","might","could","must"]','"Must be" = strongest deduction. The speaker is virtually certain based on the evidence. → He must be aware.','medium'),
  (cid,6,42,'gap_fill','[TOEFL Reading] Choose correctly: There are lights on and music playing. Someone _____ be home. (strong deduction)','must',NULL,'"Must be" = strong deduction about the present. The evidence (lights, music) makes it logically certain.','easy'),
  (cid,6,43,'multiple_choice','[TOEFL Reading] "The delegation _____ prepared more thoroughly for the negotiation." This expresses:','criticism of past inadequate preparation','["certainty about past preparation","speculation about past preparation","criticism of past inadequate preparation","a prediction about a future negotiation"]','"Should have prepared" = criticism that they did not prepare adequately (past failure/regret).','medium'),
  (cid,6,44,'gap_fill','[TOEFL Listening] "The professor _____ (might / realize) his mistake earlier if he had double-checked the figures."','might have realized',NULL,'"Might have realized" = past speculation: it was possible for him to realize earlier, but he didn''t.','hard'),
  (cid,6,45,'multiple_choice','[TOEFL Reading] "The discrepancy _____ have occurred if proper calibration procedures had been followed." Which modal fits?','wouldn''t','["shouldn''t","wouldn''t","needn''t","couldn''t"]','"Wouldn''t have occurred" = conditional past deduction — the error would not exist if the procedures had been followed.','hard'),
  (cid,6,46,'gap_fill','[TOEFL Reading] The ancient walls are 4 meters thick. The builders _____ (must / have) extraordinary engineering knowledge.','must have had',NULL,'"Must have had" = strong past deduction from physical evidence (the walls). → They must have had extraordinary knowledge.','hard'),
  (cid,6,47,'multiple_choice','[TOEFL Reading] "The researcher _____ have published her findings sooner — the delay allowed a competing lab to publish first."','should','["must","could","should","might"]','"Should have published" = criticism/regret about a past failure to act when action was needed.','hard'),
  (cid,6,48,'gap_fill','[TOEFL Listening] You _____ (need / not / bring) all those textbooks — everything we need is available online.','needn''t have brought',NULL,'"Needn''t have brought" = you did bring them, but it was unnecessary. → needn''t have brought all those textbooks.','hard'),

  -- BLOCK 7: TOEFL Academic – Modal Combinations & Perfect Modals
  (cid,7,49,'multiple_choice','[TOEFL Reading] "The species _____ migrated south during the ice age, which would explain its current distribution in warmer regions."','must have','["must have","should have","can''t have","would have"]','"Must have migrated" = past deduction from current distribution patterns. Strong logical inference from evidence.','hard'),
  (cid,7,50,'gap_fill','[TOEFL Reading] The building survived the earthquake intact. It _____ (must / reinforce) with modern seismic technology.','must have been reinforced',NULL,'"Must have been reinforced" = strong passive past deduction. → It must have been reinforced with modern technology.','hard'),
  (cid,7,51,'multiple_choice','[TOEFL Reading] "The initial findings _____ have been shared with the broader scientific community before the patent was filed." This implies:','the sharing would have been appropriate/beneficial but did not happen','["it was certain that findings were shared","the sharing would have been appropriate/beneficial but did not happen","the findings could not be shared","the researchers did share the findings"]','"Should have been shared" = recommendation/criticism that an appropriate action did not occur.','hard'),
  (cid,7,52,'gap_fill','[TOEFL Listening] "When I was a doctoral student, I _____ (would / often / work) on three different projects simultaneously."','would often work',NULL,'"Would often + base verb" = repeated past habit. → I would often work on three different projects simultaneously.','medium'),
  (cid,7,53,'multiple_choice','[TOEFL Reading] "The satellite image shows unusual thermal activity on the ocean floor. There _____ be a previously undiscovered hydrothermal vent system."','could','["might","could","must","should"]','Both "could" and "might" express speculation. "Could" slightly emphasizes capability/possibility based on conditions.','hard'),
  (cid,7,54,'gap_fill','[TOEFL Reading] The volcano has shown no signs of activity for 10,000 years. Scientists believe it _____ (can''t / still / be) active.','can''t still be',NULL,'"Can''t still be" = strong negative deduction from the evidence (no activity for 10,000 years).','hard'),
  (cid,7,55,'multiple_choice','[TOEFL Listening] The professor contrasted "need not" and "must not" by explaining that "need not" means:','"it is not necessary," while "must not" means "it is forbidden"','["it is forbidden","it is not necessary,\" while \"must not\" means \"it is forbidden\"","it is unlikely","it is impossible"]','"Need not" = absence of obligation. "Must not" = prohibition. These are frequently confused.','hard'),
  (cid,7,56,'gap_fill','[TOEFL Reading] Scientists _____ (ought / rely) on a single study when making policy recommendations.','ought not to rely',NULL,'"Ought not to + base verb" = moral/logical recommendation against an action. → ought not to rely on a single study.','hard'),

  -- BLOCK 8: TOEFL Academic – Modal Practice in Integrated Contexts
  (cid,8,57,'multiple_choice','[TOEFL Reading] Select the sentence with the correct modal for a strong past deduction: "The DNA evidence _____."','must have confirmed the suspect''s presence at the scene.','["could confirmed the suspect''s presence.","must have confirmed the suspect''s presence at the scene.","should have been confirmed the suspect''s presence.","might confirmed the suspect''s presence."]','"Must have confirmed" = past deduction from DNA evidence. Correct form: must + have + past participle.','hard'),
  (cid,8,58,'gap_fill','[TOEFL Reading] The lake contains no fish despite historical records showing abundant populations. Pollution _____ (might / kill) them off.','might have killed',NULL,'"Might have killed" = past speculation about the cause of the absence of fish. One possible explanation.','hard'),
  (cid,8,59,'multiple_choice','[TOEFL Listening] "The engineer _____ included a safety margin in the design. The collapse shows she didn''t." Which modal correctly criticizes the omission?','should have','["could have","should have","must have","might have"]','"Should have included" = criticism of a professional failure that led to consequences. → she should have included.','hard'),
  (cid,8,60,'gap_fill','[TOEFL Reading] Early astronomers _____ (must / find) the scale of the universe incomprehensible with the limited tools available to them.','must have found',NULL,'"Must have found" = past deduction: given the limited tools, it is logical they found it incomprehensible.','hard'),
  (cid,8,61,'multiple_choice','[TOEFL Reading] "The test subjects _____ have been exposed to such high concentrations of the substance — it was an ethical oversight." What does this express?','should not','["must not","should not","needn''t","can''t"]','"Should not have been exposed" = criticism of past action that violated ethical standards.','hard'),
  (cid,8,62,'gap_fill','[TOEFL Listening] "Back in the 1970s, researchers _____ (would / conduct) experiments that would be considered unethical by today''s standards."','would conduct',NULL,'"Would conduct" = past habit pattern in historical context. → researchers would conduct experiments.','medium'),
  (cid,8,63,'multiple_choice','[TOEFL Reading] "The manuscript shows signs of rapid writing and numerous corrections. The author _____ under considerable time pressure." Choose the best modal.','must have been working','["should have been working","must have been working","might work","could work"]','"Must have been working" = strong past continuous deduction from the physical evidence of the manuscript.','hard'),
  (cid,8,64,'gap_fill','[TOEFL Reading] The policy _____ (ought / review) regularly to ensure it remains relevant and effective.','ought to be reviewed',NULL,'"Ought to be reviewed" = passive modal for recommendation. → The policy ought to be reviewed regularly.','hard'),

  -- BLOCK 9: TOEFL Speaking Tasks
  (cid,9,65,'production','[TOEFL Speaking — 45s] The reading states that ancient Mayan astronomers made remarkably accurate predictions about celestial events. The lecture suggests that these astronomers must have used sophisticated mathematical models and observational techniques. Summarize the lecture''s main points and explain how they support or challenge the reading. Use modal verbs for deduction where appropriate. You have 45 seconds.','',NULL,'Modals to use: "They must have developed..." "This could have been achieved..." "They may have used..." "It couldn''t have been possible without..."','hard'),
  (cid,9,66,'production','[TOEFL Speaking — 45s] Think about a mistake you or someone you know made in the past. Describe what happened and use modal verbs to reflect on what should have been done differently, what might have caused the problem, and what could have been avoided. You have 45 seconds.','',NULL,'Practice: "I should have..." "I needn''t have..." "This might have been caused by..." "We could have avoided..."','hard'),
  (cid,9,67,'production','[TOEFL Speaking — 45s] A university professor gave a lecture arguing that scientists must communicate their findings more clearly to the public. Do you agree? Use modal verbs to express obligation, deduction, and speculation. You have 45 seconds.','',NULL,'Use: "Scientists ought to communicate..." "Failing to do so could cause..." "The public may not understand..." "This should be a priority..."','hard'),

  -- BLOCK 10: TOEFL Writing Tasks
  (cid,10,68,'production','[TOEFL Writing] Write an essay (150+ words) arguing for or against the following statement: "Governments must take immediate and drastic action to address climate change, even if this means significant economic costs." Use at least FIVE different modal constructions: (1) "must" for obligation/deduction, (2) "should have" for past criticism, (3) "could/might have been" for past speculation, (4) "ought to" for moral recommendation, (5) "need not" or "needn''t have" for necessity.','',NULL,'Targets: "Governments must act now..." "Previous governments should have introduced..." "Economic damage could have been avoided..." "World leaders ought to prioritize..." "Nations need not sacrifice growth entirely..."','hard'),
  (cid,10,69,'production','[TOEFL Writing] Integrated task: The reading argues that a newly discovered tomb must have belonged to a previously unknown pharaoh because of the unique hieroglyphic style. The lecture suggests the hieroglyphics could have been written by a scribe using an experimental style, and the tomb may have been misattributed. Write a 150+ word response summarizing the points and explaining the relationship between the reading and the lecture. Use modals for deduction and speculation throughout.','',NULL,'Modals: "The reading argues the tomb must have belonged to..." "The professor suggests it could have been written by..." "The style may indicate..." "The attribution might have been incorrect because..."','hard'),
  (cid,10,70,'production','[TOEFL Writing] Write a 200+ word essay responding to the following prompt: "In reviewing the history of scientific progress, one can argue that many breakthroughs could have happened earlier had scientists been more willing to challenge established theories." Do you agree or disagree? Use a wide range of modal constructions for past speculation, past deduction, criticism, and obligation. Label each modal type you use in brackets (e.g., [past deduction]).','',NULL,'Targets: [past speculation] "Scientists might have made breakthroughs earlier..." [past deduction] "The evidence must have been available..." [past criticism] "Earlier scientists should have challenged..." [obligation] "The scientific community ought to encourage..."','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
