-- ============================================================
-- SEED EXT 4: Módulo 02 — Present Simple (ex 206-300)
-- Novos tópicos: PS negativo avançado, perguntas formais,
-- PS em gêneros textuais especializados, TOEFL avançado
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'present-simple';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo present-simple não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 41: PS em definições e classificações acadêmicas
  (cid,41,206,'gap_fill','A paradigm shift, as Kuhn _____ (define) it, _____ (occur) when an accumulation of anomalies _____ (challenge) a prevailing scientific framework.','defines / occurs / challenges',NULL,'Literary present + present simple for academic definitions.','hard'),
  (cid,41,207,'gap_fill','Ecosystem services _____ (refer) to the benefits that humans _____ (derive) from natural environments.','refer / derive',NULL,'Present simple for academic definitions (stative "refer to").','medium'),
  (cid,41,208,'multiple_choice','Which sentence uses present simple for a scientific classification CORRECTLY?','Mammals are endothermic vertebrates that nurse their young with milk produced by mammary glands.','["Mammals were endothermic vertebrates that nursed their young.","Mammals are being endothermic vertebrates that nurse their young.","Mammals are endothermic vertebrates that nurse their young with milk produced by mammary glands.","Mammals have been endothermic vertebrates that nurse their young."]','Present simple for biological definitions and classifications (universal facts).','easy'),
  (cid,41,209,'gap_fill','The gig economy _____ (describe) a labor market characterized by short-term contracts and freelance work rather than permanent employment.','describes',NULL,'Present simple for economic concepts and their definitions.','easy'),
  (cid,41,210,'gap_fill','GDP _____ (stand) for Gross Domestic Product and _____ (represent) the total monetary value of all goods and services produced within a country.','stands / represents',NULL,'Present simple for acronym definitions in academic/economic writing.','easy'),

  -- BLOCK 42: PS em instruções, procedimentos e normas
  (cid,42,211,'gap_fill','To run the statistical analysis, the researcher _____ (open) the software, _____ (import) the dataset, and _____ (select) the appropriate test from the menu.','opens / imports / selects',NULL,'Present simple in procedural/instructional texts (how to do something).','medium'),
  (cid,42,212,'multiple_choice','Why is present simple used in instruction manuals?','It describes actions as universally valid steps, regardless of when the reader performs them.','["It is informal","It describes specific past actions","It describes actions as universally valid steps, regardless of when the reader performs them.","It is always more polite than imperative"]','Present simple in instructions = "this is always the procedure" (not a specific past event).','medium'),
  (cid,42,213,'gap_fill','In most legal contracts, the word "shall" _____ (indicate) obligation, while "may" _____ (indicate) permission.','indicates / indicates',NULL,'Present simple for legal/regulatory descriptions.','medium'),
  (cid,42,214,'multiple_choice','Which sentence CORRECTLY uses present simple in an academic methods section?','The study uses a mixed-methods design that incorporates both quantitative surveys and qualitative interviews.','["The study used a mixed-methods design that incorporated both surveys and interviews (past simple — only appropriate for completed past studies).","The study is using a mixed-methods design (continuous — wrong for stable design description).","The study uses a mixed-methods design that incorporates both quantitative surveys and qualitative interviews.","The study will use a mixed-methods design that will incorporate both."]','Present simple = current study design (still in place when written).','hard'),

  -- BLOCK 43: PS negativo avançado
  (cid,43,215,'gap_fill','The evidence _____ (not/support) the hypothesis that social media use directly causes depression.','does not support',NULL,'"Does not support" = present simple negative for rejecting a hypothesis.','easy'),
  (cid,43,216,'multiple_choice','Which negative present simple sentence is MOST appropriately hedged for academic writing?','The current data do not conclusively demonstrate a causal relationship.','["The data doesn''t prove anything.","There is no evidence.","The current data do not conclusively demonstrate a causal relationship.","The results don''t show causality."]','"Do not conclusively demonstrate" = hedged academic negative (doubly hedged).','hard'),
  (cid,43,217,'gap_fill','This study _____ (not/claim) to provide a definitive resolution to the debate, but rather _____ (aim) to open new avenues for investigation.','does not claim / aims',NULL,'Academic present simple for hedged scope statement (what the paper does/doesn''t do).','medium'),
  (cid,43,218,'gap_fill','The model _____ (not/account) for individual variation, which _____ (limit) the generalizability of the findings.','does not account / limits',NULL,'Present simple for describing model limitations.','medium'),
  (cid,43,219,'multiple_choice','Which uses "do not/does not" correctly in academic writing?','The authors do not dispute that further replication is necessary.','["The authors doesn''t dispute the findings.","The authors do not disputes that further replication is necessary.","The authors do not dispute that further replication is necessary.","The findings does not suggest causation."]','"Do not dispute" = present simple negative for authors (plural subject).','medium'),

  -- BLOCK 44: perguntas formais com PS — interrogativas retóricas
  (cid,44,220,'gap_fill','What _____ (constitute) acceptable evidence in qualitative research? This question _____ (lie) at the heart of longstanding methodological debates.','constitutes / lies',NULL,'Present simple in rhetorical academic questions.','medium'),
  (cid,44,221,'multiple_choice','Which rhetorical question uses present simple MOST appropriately?','How does economic inequality shape educational opportunity?','["How is economic inequality shaping educational opportunity? (continuous — implies specifically right now)","How did economic inequality shape educational opportunity? (past — historical)","How does economic inequality shape educational opportunity?","How has economic inequality shaped educational opportunity? (perfect — implies completed link)"]','Present simple in rhetorical/research questions = general, ongoing relationship.','medium'),
  (cid,44,222,'gap_fill','Under what conditions _____ (do) cooperation _____ (emerge) spontaneously between self-interested actors?','does / emerge',NULL,'Present simple interrogative with fronted prepositional phrase (formal word order).','hard'),

  -- BLOCK 45: PS em diferentes gêneros acadêmicos
  (cid,45,223,'gap_fill','The abstract _____ (summarize) the key objectives, methodology, findings, and implications of the study.','summarizes',NULL,'Present simple for describing what a text/section does (meta-discourse).','easy'),
  (cid,45,224,'multiple_choice','In abstracts, present simple is typically used for:','The aims of the study and its main findings/conclusions.','["The literature review only","The aims of the study and its main findings/conclusions.","Future work only","Describing data collection procedures"]','Abstracts = present simple for aims (''this paper investigates'') and conclusions (''the findings suggest'').','medium'),
  (cid,45,225,'gap_fill','The concluding chapter _____ (synthesize) the findings from the three empirical chapters and _____ (outline) directions for future research.','synthesizes / outlines',NULL,'Present simple for describing what a chapter does.','easy'),
  (cid,45,226,'gap_fill','This section _____ (introduce) the theoretical framework that _____ (inform) the subsequent empirical analysis.','introduces / informs',NULL,'Present simple for describing section function in academic writing.','easy'),
  (cid,45,227,'multiple_choice','In a thesis statement, why is present simple preferred?','Because the claim is being made as a general truth, not tied to a specific past moment.','["It sounds more interesting","It is a grammar rule for all formal documents","Because the claim is being made as a general truth, not tied to a specific past moment.","Because the writer is reporting past research"]','Present simple = timeless claim, appropriate for thesis arguments.','medium'),

  -- BLOCK 46: TOEFL Reading
  (cid,46,228,'multiple_choice','[TOEFL Reading] "The chapter reviews the main theoretical approaches to understanding identity formation and argues that a synthesis is necessary." What aspect of academic writing does "reviews" and "argues" exemplify?','Present simple used to describe what the text does (meta-discourse).','["Past simple for completed actions","Present perfect for recent scholarship","Present simple used to describe what the text does (meta-discourse).","Continuous for ongoing processes"]','"Reviews / argues" = present simple meta-discourse describing text function.','medium'),
  (cid,46,229,'gap_fill','[TOEFL Reading] "Photosynthesis _____ (occur) in the chloroplasts of plant cells, where solar energy _____ (convert/passive) into chemical energy." Best forms?','occurs / is converted',NULL,'Present simple for scientific process (universal fact) + passive passive.','easy'),
  (cid,46,230,'multiple_choice','[TOEFL Reading] "This paper does not argue that all migration is economically beneficial; rather, it suggests that context determines outcomes." What does "does not argue" + "suggests" achieve?','It precisely delimits what the paper claims and what it leaves open.','["It contradicts the title","It avoids academic register","It precisely delimits what the paper claims and what it leaves open.","It makes the paper more informal"]','Academic scope limitation: "does not argue that X; argues/suggests that Y."','hard'),
  (cid,46,231,'gap_fill','[TOEFL Reading] "The evidence _____ (not/support) a direct causal link, but _____ (suggest) a statistically significant correlation." Best forms?','does not support / suggests',NULL,'Negative + positive present simple for nuanced academic claim.','medium'),

  -- BLOCK 47: TOEFL Speaking
  (cid,47,232,'production','[TOEFL Speaking — 45s] Explain how volcanoes work using present simple for scientific processes, stative verbs, and passive present.','',NULL,'Volcanoes form at boundaries where tectonic plates converge or diverge, or above hot spots where magma rises through the earth''s crust. Magma consists of molten rock, gases, and solid particles, and it accumulates in chambers beneath the surface. When pressure builds to a critical level, the magma forces its way upward through channels or vents. During an eruption, lava, ash, and gases are expelled into the atmosphere. The resulting lava cools and solidifies as it flows downslope, gradually building the characteristic cone shape. Not all volcanoes behave identically — shield volcanoes produce slow-moving flows of low-viscosity lava, while stratovolcanoes tend to erupt more violently and explosively.','hard'),
  (cid,47,233,'production','[TOEFL Speaking — 45s] A reading discusses differences between inductive and deductive reasoning. Explain the distinction using present simple definitions, examples, and negative present simple.','',NULL,'The reading makes an important distinction between two fundamental forms of reasoning. Deductive reasoning moves from general principles to specific conclusions: if all mammals are warm-blooded and dolphins are mammals, then dolphins must be warm-blooded. Inductive reasoning works in the opposite direction — it draws general conclusions from specific observations. A scientist who observes that every swan she has ever seen is white inductively concludes that all swans are white. However, inductive conclusions do not carry the same logical certainty as deductive ones: they can be overturned by a single counterexample, as happened when black swans were discovered in Australia. The reading argues that scientific knowledge largely depends on inductive reasoning, which is why science does not produce absolute certainties but only probabilistic conclusions.','hard'),

  -- BLOCK 48: TOEFL Writing
  (cid,48,234,'production','[TOEFL Writing — 150 words] Write an introduction for a TOEFL argumentative essay on "Should universities prioritize vocational training over liberal arts education?" Use present simple for the topic context, thesis, and paper structure.','',NULL,'Contemporary debates about the purpose of higher education increasingly pit two competing visions against each other. On one side, advocates of vocational training argue that universities exist primarily to produce workforce-ready graduates who can contribute immediately to the economy. On the other, defenders of liberal arts education maintain that universities serve a broader civilizational purpose: developing critical thinking, ethical reasoning, and civic participation. This essay argues that the dichotomy between vocational and liberal arts education is largely false and ultimately counterproductive. The most effective university education integrates both: it equips students with discipline-specific professional competencies while simultaneously developing the analytical and communicative capacities that characterize genuinely educated citizens. The following paragraphs examine three key areas in which this integrated approach demonstrably outperforms either model pursued in isolation.','hard'),
  (cid,48,235,'production','[TOEFL Writing — Error Correction] Fix present simple errors: "The study is examining three research questions. The author argued in the introduction that policy reform is necessary. This section is defining the key terms. The results doesn''t support the hypothesis. The chapter review the theoretical literature."','',NULL,'is examining → examines (present simple for stable academic description); argued in the introduction → argues in the introduction (literary present — the text permanently contains this argument); is defining → defines (present simple, not continuous, for what a section does); doesn''t support → do not support (''results'' is plural — ''do not''); review → reviews (third person singular: ''the chapter reviews'').','hard'),

  -- BLOCK 49: Consolidação e prática avançada TOEFL
  (cid,49,236,'production','[TOEFL Writing — 200 words] Write a full body paragraph for a TOEFL essay on "The benefits and risks of genetic engineering." Use: present simple (×5+), stative verbs, academic negatives, passive present, and hedged claims.','',NULL,'Genetic engineering offers extraordinary promise for medicine, agriculture, and environmental management, but it also introduces risks that scientists and regulators do not fully understand. At the most basic level, gene-editing technology — particularly CRISPR-Cas9 — allows researchers to modify the genome of living organisms with unprecedented precision and speed. In medicine, this capacity holds genuine therapeutic potential: genetic diseases caused by single-gene mutations appear to be amenable to correction through targeted editing. In agriculture, crop varieties engineered for drought resistance or enhanced nutritional content represent a potential tool for addressing food insecurity in vulnerable regions. However, critics rightly point out that the long-term ecological effects of releasing genetically modified organisms into natural environments remain deeply uncertain. Horizontal gene transfer — the process by which genes move between organisms — poses a risk that modified genetic material will spread beyond intended boundaries in ways that are not reversible. This paper does not argue that genetic engineering should be banned; rather, it suggests that stringent regulatory frameworks, independent oversight, and mandatory long-term impact assessments are essential preconditions for its responsible development.','hard'),
  (cid,49,237,'production','[TOEFL Writing — 200 words] Write an argument for compulsory voting using present simple for general truths, frequency adverbs, academic negatives (do not), and hedged claims with modals.','',NULL,'Compulsory voting represents a policy instrument that ensures all citizens participate in the democratic process, regardless of their level of political engagement or socioeconomic status. Democracies that do not require voting typically see turnout fall disproportionately among lower-income groups, young people, and marginalized communities — precisely the populations whose interests most urgently need representation. When governments are elected by only 40 to 50 percent of eligible voters, as frequently happens in voluntary systems, they rarely represent the full range of public interests. Compulsory voting does not violate the freedom of conscience, since citizens in systems that require voting usually retain the option to submit a blank ballot. Australia, which has maintained compulsory voting for nearly a century, consistently demonstrates that the policy produces more representative outcomes without generating the widespread coercion that critics fear. This essay argues that the democratic benefits of universal participation substantially outweigh the minimal infringement on individual liberty that mandatory voting entails, and that voluntary systems systematically produce governments that are less accountable to the populations they are supposed to serve.','hard'),
  (cid,49,238,'gap_fill','The hypothesis _____ (not/assert) that poverty directly causes crime, but rather that it _____ (increase) the structural conditions under which criminal behavior _____ (become) more likely.','does not assert / increases / becomes',NULL,'Academic negative + causal chain in present simple: nuanced claim about relationship.','hard'),
  (cid,49,239,'multiple_choice','Which set of verbs is CORRECTLY conjugated in present simple for a formal academic paragraph?','The study examines / argues / demonstrates / suggests / contributes.','["The study examine / argues / demonstrates / suggest / contributes.","The study examines / argues / demonstrates / suggests / contributes.","The study examines / argue / demonstrate / suggests / contributes.","The studies examines / argues / demonstrates / suggests / contributes."]','All third-person singular verbs need -s: examines, argues, demonstrates, suggests, contributes.','medium'),
  (cid,49,240,'production','[TOEFL Writing — integrated task] A lecture challenges a reading. The reading argues that social media increases loneliness. The lecture suggests it reduces loneliness for isolated groups. Write a synthesis using present simple throughout.','',NULL,'The reading and the lecture present conflicting claims about social media''s effect on loneliness. The reading argues that social media use is associated with increased social isolation, citing studies that demonstrate an inverse relationship between time spent online and face-to-face social interaction. The author suggests that digital communication functions as a substitute rather than a supplement for in-person connection. The lecture challenges this claim, however. The professor notes that the reading relies predominantly on data from socially integrated populations for whom digital interaction does indeed displace rather than augment face-to-face contact. For individuals who lack access to in-person social networks — people with disabilities, those living in remote areas, or members of stigmatized minority communities — social media provides a form of connection that would otherwise not exist. The professor thus contends that the reading''s conclusion does not generalize across all populations equally.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
