-- ============================================================
-- SEED EXT 5: Módulo 10 — Basic Modals (ex 196-270)
-- Novos tópicos: modais em academic writing avançado, modais em
-- contextos multi-sentença, modais + passive advanced, TOEFL tasks
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'modais-basicos';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo modais-basicos não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 51: Modais em academic writing — ability, possibility, necessity
  (cid,51,196,'gap_fill','This framework _____ (use/passive) to analyze a wide range of policy contexts, though its applicability _____ (vary) depending on institutional conditions.','can be used / may vary',NULL,'''Can be used'' = capacity passive. ''May vary'' = epistemic possibility hedge.','medium'),
  (cid,51,197,'gap_fill','Policymakers _____ (must) address both the immediate symptoms and the underlying structural causes; _____ _____ treating the former _____ (not/be) sufficient.','must / otherwise / will not be / alone will not be',NULL,'''Must'' = strong obligation + ''otherwise + will not be'' = consequence of non-compliance.','hard'),
  (cid,51,198,'gap_fill','The algorithm _____ (can) process thousands of data points per second, _____ enabling analyses that _____ (would/previously/require) weeks of manual computation.','can / thereby / would previously have required',NULL,'''Can'' = capacity + ''thereby'' = result + ''would have required'' = counterfactual comparison.','hard'),
  (cid,51,199,'multiple_choice','Which modal expresses LOGICAL NECESSITY in academic argument?','The data must be collected before the analysis can begin.','["The data should be collected before analysis (advice).","The data might be collected before analysis (possibility).","The data must be collected before the analysis can begin.","The data could be collected before analysis (option)."]','''Must'' = logical/technical necessity (not a suggestion or option).','easy'),
  (cid,51,200,'gap_fill','Access to clean water _____ (recognize/passive) as a fundamental human right, yet millions _____ (still/not/access/passive) it safely and reliably.','must be recognized / can still not access / still cannot access',NULL,'''Must be recognized'' = normative obligation. ''Cannot access'' = denied capacity.','hard'),
  (cid,51,201,'multiple_choice','Which sentence uses ''could'' for PAST ABILITY in academic writing?','Before the development of MRI technology, physicians could not image soft tissue non-invasively.','["Before MRI, physicians couldn''t image soft tissue non-invasively.","Before the development of MRI technology, physicians could not image soft tissue non-invasively.","Before MRI, physicians would not image soft tissue.","Before MRI, physicians should not image soft tissue."]','''Could not'' = past inability (the technology did not allow it).','easy'),

  -- BLOCK 52: Modais com passiva avançados
  (cid,52,202,'gap_fill','These findings _____ (must/consider/passive) in the context of the study''s methodological limitations, particularly its _____ (rely) on self-reported data.','must be considered / reliance',NULL,'''Must be considered'' = modal passive obligation + nominalization ''reliance.''','medium'),
  (cid,52,203,'gap_fill','The data _____ (should/anonymize/passive) before _____ (share/passive) with external partners, _____ (ensure) compliance with data protection regulations.','should be anonymized / being shared / ensuring',NULL,'''Should be anonymized'' = modal passive + gerund passive + participial result clause.','hard'),
  (cid,52,204,'gap_fill','A causal relationship _____ (not/establish/passive) from observational data alone; experimental designs _____ (require/passive) to confirm the proposed mechanism.','cannot be established / are required',NULL,'''Cannot be established'' = capacity negative passive. ''Are required'' = modal-free passive of necessity.','hard'),
  (cid,52,205,'gap_fill','The results _____ (replicate/passive) across multiple sites before they _____ (accept/passive) as generalizable findings.','must be replicated / can be accepted / will be accepted',NULL,'Modal passive sequence for research validation.','hard'),
  (cid,52,206,'multiple_choice','Which passive modal sentence is MOST APPROPRIATE in a methods section?','Blood samples were collected under sterile conditions and must be stored at -80°C until analysis.','["Blood samples were collected under sterile conditions and should store at -80°C.","Blood samples were collected under sterile conditions and must be stored at -80°C until analysis.","Blood samples were collected under sterile conditions and can be storing at -80°C.","Blood samples were collected under sterile conditions and are stored at -80°C."]','''Must be stored'' = procedural obligation in methods passive.','medium'),

  -- BLOCK 53: Distinções entre modais semelhantes
  (cid,53,207,'multiple_choice','What is the EXACT difference between ''may'' and ''might'' in academic hedging?','''May'' = somewhat more likely; ''might'' = slightly less certain, more remote possibility.','["They are identical","''May'' = past; ''might'' = present","''May'' = somewhat more likely; ''might'' = slightly less certain, more remote possibility.","''May'' = permission; ''might'' = possibility (always)"]','''May'' = moderate epistemic possibility. ''Might'' = more remote or tentative. In academic hedging, both are used, with ''might'' slightly more cautious.','hard'),
  (cid,53,208,'gap_fill','The treatment _____ (alleviate) symptoms in the short term, but it _____ (not/address) the underlying disease mechanism, which _____ (remain) poorly understood.','may alleviate / may not address / remains',NULL,'''May'' (positive possibility) + ''may not'' (negative possibility) + PS (certainty of gap).','medium'),
  (cid,53,209,'multiple_choice','Which sentence correctly uses ''can'' vs ''may'' in academic writing?','''Biodiversity loss can be measured in several ways; its causes may include both anthropogenic and natural factors.''','["Biodiversity loss may be measured in several ways; its causes can include anthropogenic factors.","Biodiversity loss can be measured in several ways; its causes may include both anthropogenic and natural factors.","Biodiversity loss must be measured in several ways; its causes will include anthropogenic factors.","Biodiversity loss could be measured in several ways; its causes might include anthropogenic factors."]','''Can'' = capacity (ways of measuring exist). ''May'' = epistemic possibility (causes are not fully known).','hard'),
  (cid,53,210,'gap_fill','While _____ (may) seem paradoxical, the data _____ (suggest) that an increase in inequality _____ (actually/reduce) social mobility, _____ (not/merely/correlate with) it.','this / suggests / actually reduces / not merely correlates with',NULL,'''While + this may + seem'' + ''suggests'' + ''reduces'' + ''not merely correlates'' = nuanced causal claim.','hard'),
  (cid,53,211,'multiple_choice','In academic writing, when should you use ''will'' rather than a modal?','When stating something that is certain or follows logically with no doubt.','["When expressing possibility","When expressing advice","When stating something that is certain or follows logically with no doubt.","When expressing past ability"]','''Will'' = certain future or logical certainty. Modals (may/might/could) = uncertainty/hedging.','easy'),

  -- BLOCK 54: Modais em contextos multi-sentença TOEFL
  (cid,54,212,'production','[TOEFL Speaking — 45s] A reading describes how new battery technology may change the energy sector. Report the reading''s claims using modals.','',NULL,'The reading describes breakthroughs in solid-state battery technology and argues that they could fundamentally transform the energy storage sector within the next decade. According to the reading, solid-state batteries may offer energy density several times higher than current lithium-ion designs, which would significantly extend the range of electric vehicles and reduce charging time. The reading suggests that this technology might also address one of the most significant barriers to renewable energy deployment — intermittency — by enabling cost-effective grid-scale storage. However, the reading acknowledges that several manufacturing challenges must be overcome before these batteries can be produced at commercial scale, and that costs will need to fall substantially before they can compete with existing technologies on a purely economic basis.','hard'),
  (cid,54,213,'production','[TOEFL Speaking — 45s] Discuss what should be done to improve access to mental healthcare. Use a variety of modals.','',NULL,'Mental healthcare access represents one of the most significant unmet needs in health systems globally, and addressing it will require action across several dimensions simultaneously. Governments must invest substantially in training and deploying mental health workers at all levels of the health system, since the current workforce is insufficient to meet documented demand even in high-income countries. Primary care networks should be equipped to identify and manage common mental health conditions — depression and anxiety — rather than referring all cases to specialist services that lack capacity. Employers could play a significant role by creating workplace cultures that destigmatize mental health challenges and provide support resources. Digital mental health tools — chatbots, guided self-help apps — may extend the reach of care to people who cannot access face-to-face services, though they must not be used as a substitute for human therapeutic relationships in moderate-to-severe cases. Insurance and payment systems will need to be reformed to ensure that mental health services are covered on terms comparable to physical health services.','hard'),
  (cid,54,214,'production','[TOEFL Writing — 150 words] Write a paragraph on AI in healthcare using varied modals.','',NULL,'Artificial intelligence is beginning to transform several domains of healthcare, and the potential implications are both significant and complex. AI diagnostic systems can already match or exceed radiologist performance in detecting certain cancers from imaging data, a capacity that could substantially reduce the burden of diagnostic error. Machine learning models may predict patient deterioration hours before clinical signs are observable, enabling earlier intervention that could improve outcomes and reduce intensive care demand. However, these systems must be rigorously validated across diverse patient populations before deployment: models trained on data from high-income country hospitals may not perform reliably in settings with different patient demographics, disease profiles, or imaging equipment. Furthermore, AI should be deployed as a decision-support tool for clinicians rather than as an autonomous decision-maker, since the accountability and trust frameworks for autonomous clinical AI do not yet exist. Adequate digital infrastructure and data governance capacity will also need to be in place before AI can deliver these benefits equitably.','hard'),

  -- BLOCK 55: TOEFL Reading
  (cid,55,215,'multiple_choice','[TOEFL Reading] ''The immune response can be modulated by a variety of environmental and genetic factors, which may explain the wide variation in disease severity observed across patient populations.'' The modals ''can'' and ''may'' are used to:','Express capacity (can) and epistemic possibility (may) respectively.','["Both express certainty","Express prohibition and permission","Express capacity (can) and epistemic possibility (may) respectively.","Both express past ability"]','''Can be modulated'' = capacity (it is possible to modulate). ''May explain'' = epistemic hedge (this is a possible explanation).','medium'),
  (cid,55,216,'gap_fill','[TOEFL Reading] ''These investments _____ (must/prioritize/passive) if long-term economic competitiveness _____ (maintain/passive).'' Best forms?','must be prioritized / is to be maintained',NULL,'''Must be prioritized'' = obligation passive. ''Is to be maintained'' = conditional necessity passive.','hard'),
  (cid,55,217,'multiple_choice','[TOEFL Reading] ''The committee concluded that safety protocols could have been more stringent.'' ''Could have been'' expresses:','A missed past possibility — they had the ability to implement stricter protocols but did not.','["Certain past ability","A missed past possibility — they had the ability to implement stricter protocols but did not.","Future recommendation","A past necessity"]','''Could have been'' = capacity existed in the past but was not exercised.','medium'),
  (cid,55,218,'gap_fill','[TOEFL Reading] ''The government _____ (not/ignore) the early warning signs; action _____ (take/passive) months before the crisis reached its peak.'' Best critical modals?','should not have ignored / should have been taken',NULL,'''Should not have ignored'' + ''should have been taken'' = criticism of past inaction.','hard'),

  -- BLOCK 56: TOEFL Speaking
  (cid,56,219,'production','[TOEFL Speaking — 45s] Discuss what changes to education might be needed in the next decade. Use modals of varying strength.','',NULL,'Education systems around the world may need to undergo some of their most significant transformations in a century as AI reshapes the skills the labor market values. Teachers must be equipped with training in how to work alongside AI tools rather than compete with them, and curricula should be redesigned to emphasize judgment, creativity, and collaborative problem-solving over the recall of information that AI can retrieve instantly. Assessment systems will need to evolve: conventional examinations that can be passed with AI assistance can no longer serve as reliable measures of the competencies students need to develop. Digital equity must be addressed if AI-enhanced education is to benefit all students rather than widening existing inequalities; without reliable devices and connectivity, students from disadvantaged backgrounds will fall further behind those who can use AI tutoring systems at home. Institutions might also experiment with shorter, modular credentials that allow continuous skill updating throughout careers rather than front-loading all learning in the first two decades of life.','hard'),

  -- BLOCK 57: Production
  (cid,57,220,'production','[TOEFL Writing — 200 words] Write a paragraph on the energy transition using a variety of modals throughout.','',NULL,'The transition from fossil fuels to renewable energy represents one of the most significant economic and industrial transformations in human history, and the pace at which it occurs will determine how much climate disruption humanity is forced to manage. Solar and wind power can now generate electricity at costs competitive with or below those of new fossil fuel installations in most markets, removing the economic barrier that once made the transition contingent on subsidies. Energy storage technologies — particularly batteries and green hydrogen — must be scaled significantly if intermittent renewable generation is to meet demand reliably across seasons and geographies. Grid infrastructure will also need to be substantially upgraded and expanded, since the transmission systems currently in place were designed for a different generation portfolio and cannot efficiently distribute electricity from the locations where solar and wind are most abundant to the population centers where demand is concentrated. Governments should coordinate industrial policy, public procurement, and research investment to accelerate deployment of technologies that are not yet commercially viable but could become crucial — offshore wind, long-duration storage, and carbon capture and utilization among them. Private capital can and will flow into proven technologies; the role of public policy is to de-risk the technologies that markets will not finance at the necessary pace.','hard'),
  (cid,57,221,'production','[TOEFL Writing — 200 words] Write a conclusion for a TOEFL essay on urbanization using modals to state implications and recommendations.','',NULL,'The analysis presented in this essay suggests that urbanization, while presenting profound governance challenges, also offers conditions that — properly managed — can support higher living standards, lower per-capita resource consumption, and greater economic opportunity than dispersed rural settlement patterns. Cities can deliver public services, cultural institutions, and economic networks more efficiently than rural areas when their density is properly planned and governed; the question is whether institutional capacity can keep pace with the speed and scale of urban growth in the developing world. Governments must invest in infrastructure before populations arrive rather than after, since retrofitting infrastructure in densely occupied informal settlements is far more expensive and disruptive than forward planning. Land tenure security should be extended to the residents of informal settlements so that they can invest in improving their own housing and so that communities have a stake in participating in formal urban governance. International development finance could play a catalytic role in funding the infrastructure deficit that most rapidly growing cities face, particularly in sub-Saharan Africa and South Asia. Ultimately, the future of urbanization will depend on political choices about who urban growth serves — whether cities are built for real estate investors or for the people who actually live in them.','hard'),

  -- BLOCK 58: Final
  (cid,58,222,'production','[TOEFL Speaking — 60s] Discuss the role of international organizations in global health. Use modals throughout.','',NULL,'International organizations play an essential but imperfect role in global health governance, and their effectiveness depends significantly on the willingness of member states to fund them adequately and comply with their technical guidance. The World Health Organization must navigate a fundamental structural tension: it is dependent on voluntary contributions from wealthy member states, which can withhold funding if they disagree with WHO positions, yet it is expected to provide independent scientific leadership on matters where powerful governments may have competing economic or political interests. During the COVID-19 pandemic, these tensions became visible when political pressures constrained the timing and scope of WHO''s early pandemic declarations. The WHO should be given more reliable core funding, independent of voluntary contributions, if it is to function as the authoritative technical agency that global health governance requires. Other international health institutions — including GAVI, the vaccine alliance, and the Global Fund — have demonstrated that pooled purchasing and financing mechanisms can deliver essential health interventions at scale in low-income countries, suggesting that more ambitious multilateral funding vehicles could address other persistent global health inequities. Whether the political will to strengthen global health institutions can be maintained outside of crisis periods, when the urgency of cooperation feels less immediate, remains the central challenge.','hard'),
  (cid,58,223,'production','[TOEFL Writing — 200 words] Write a paragraph on social media''s role in democracy. Use modals throughout.','',NULL,'Social media''s relationship with democratic governance is deeply ambiguous, and any assessment of it must reckon with evidence pointing in opposite directions simultaneously. Digital platforms can facilitate civic engagement in ways that traditional media cannot: they enable citizens to organize rapidly, amplify marginalized voices, and hold powerful institutions accountable in real time. During the Arab Spring, social media arguably provided organizational infrastructure for mass mobilization that would not have been possible through broadcast media alone. However, the same platforms can also undermine democracy by enabling the rapid spread of misinformation, amplifying extremist content for commercial reasons, and providing authoritarian actors with new tools for surveillance and manipulation. The algorithmic architecture of major platforms tends to reward outrage and tribal identity over reasoned deliberation, which may be corroding the common information environment that democratic discourse requires. Regulators should require platforms to demonstrate that their recommendation systems do not systematically amplify false or harmful content, and platforms could be obligated to publish algorithmic transparency reports accessible to independent researchers. Civil society organizations must also develop the media literacy capacities of populations who are increasingly unable to distinguish reliable from unreliable information in high-volume digital environments. Democracy can coexist with social media, but it will require proactive institutional design to do so.','hard'),
  (cid,58,224,'production','[TOEFL Writing — 200 words] Final production task: Write a paragraph on the ethics of autonomous weapons systems. Use modals to address obligations, possibilities, prohibitions, and recommendations.','',NULL,'The development of autonomous weapons systems — machines capable of selecting and engaging targets without direct human control — raises ethical questions of a different order from those posed by previous weapons technologies, and the international community must address them before these systems are deployed at scale. International humanitarian law requires that armed force be directed only at legitimate military targets and that civilian harm be minimized; it is not clear that autonomous systems can reliably make the distinctions that these principles require, and if they cannot, their deployment would violate obligations that states have already accepted under the laws of war. The principle of meaningful human control over the use of lethal force may be incompatible with the operational tempo at which fully autonomous systems are designed to function, suggesting that some form of human-in-the-loop requirement should be mandated regardless of the resulting reduction in speed or efficiency. An international treaty prohibiting the development and deployment of fully autonomous lethal systems should be negotiated without further delay: the longer the development continues, the harder effective prohibition will become. States that are advancing these technologies might voluntarily commit to moratoriums while negotiations proceed, though whether they will do so without binding international agreement seems doubtful given the perceived strategic advantages at stake.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
