-- ============================================================
-- SEED EXT 4: Módulo 22 — Subjunctive (ex 140-210)
-- Novos tópicos: subjuntivo em linguagem formal/legal, subjuntivo
-- em contextos acadêmicos, subjuntivo mandativo vs optativo,
-- subjuntivo em TOEFL writing (argumentação formal)
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'subjunctive';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo subjunctive não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 41: Subjuntivo mandativo (recommend/suggest/insist/demand/propose + that)
  (cid,41,140,'gap_fill','The committee recommends that the funding _____ (allocate/passive) to priority research areas before the end of the fiscal year.','be allocated',NULL,'Mandative subjunctive passive: that + subject + be + past participle.','hard'),
  (cid,41,141,'gap_fill','The ethics board insists that all participants _____ (give/passive) written consent before any data _____ (collect/passive).','be given / is collected / be collected',NULL,'Mandative subjunctive: that + subject + be + PP; second clause with PS or subjunctive.','hard'),
  (cid,41,142,'multiple_choice','Which sentence uses the mandative subjunctive CORRECTLY?','The report proposes that the government establish an independent regulatory body.','["The report proposes that the government establishes an independent regulatory body.","The report proposes that the government established an independent regulatory body.","The report proposes that the government establish an independent regulatory body.","The report proposes that the government has established an independent regulatory body."]','Mandative subjunctive: propose + that + subject + base form (not -s, not past).','medium'),
  (cid,41,143,'gap_fill','Legal experts urge that any future agreement _____ (include) an independent enforcement mechanism and _____ (not/exempt) signatories from accountability.','include / not exempt',NULL,'Urge + that + base form. Negative: not + base verb (no do).','hard'),
  (cid,41,144,'gap_fill','The international tribunal demanded that the state _____ (return) the confiscated assets and _____ (provide) compensation to affected parties.','return / provide',NULL,'Demand + that + subject + base verb (both coordinated: return and provide).','medium'),
  (cid,41,145,'multiple_choice','In which of these sentences does the mandative subjunctive apply?','It is essential that each candidate submit a portfolio of original work.','["It is probable that each candidate submits a portfolio.","It is essential that each candidate submit a portfolio of original work.","It is likely that each candidate will submit a portfolio.","It is true that each candidate submits a portfolio."]','"It is essential that" = mandative context → subjunctive "submit" (not "submits").','medium'),

  -- BLOCK 42: Subjuntivo em linguagem legal e formal
  (cid,42,146,'gap_fill','It is a condition of this grant that the principal investigator _____ (report) annually on progress and _____ (maintain) all records for a minimum of ten years.','report / maintain',NULL,'Formal condition clause: that + subject + base verb (mandative).','hard'),
  (cid,42,147,'multiple_choice','In a formal legal document, "The court orders that the defendant appear before the tribunal on the specified date" — why is "appear" used instead of "appears"?','It is the mandative subjunctive — the base form is required after formal directives.','["''Appear'' is past tense here","It is the mandative subjunctive — the base form is required after formal directives.","Legal language uses infinitive forms","There is an error — should be ''appears''"]','Legal mandative subjunctive: orders that + subject + base form.','medium'),
  (cid,42,148,'gap_fill','The resolution stipulates that member states _____ (reduce) emissions by 40% and _____ (submit) annual progress reports.','reduce / submit',NULL,'International legal language: stipulates that + base verb.','hard'),
  (cid,42,149,'gap_fill','It is imperative that all evidence _____ (preserve/passive) and that the integrity of the chain of custody _____ (maintain/passive).','be preserved / be maintained',NULL,'Mandative subjunctive passive x2 for legal/forensic context.','hard'),
  (cid,42,150,'multiple_choice','Which sentence uses the formal "lest" + subjunctive correctly?','Researchers must ensure data integrity, lest their findings be dismissed as unreliable.','["Researchers must ensure data integrity, lest their findings are dismissed as unreliable.","Researchers must ensure data integrity, lest their findings were dismissed as unreliable.","Researchers must ensure data integrity, lest their findings be dismissed as unreliable.","Researchers must ensure data integrity, lest their findings dismiss as unreliable."]','"Lest" + subject + base verb (subjunctive): lest + findings + be dismissed.','hard'),

  -- BLOCK 43: Were + to (formal hypothetical subjunctive)
  (cid,43,151,'gap_fill','Were the government _____ (introduce) a carbon tax, businesses would face significantly higher operational costs.','to introduce',NULL,'"Were + subject + to + base verb" = formal hypothetical subjunctive (Type 2).','hard'),
  (cid,43,152,'gap_fill','Were this discovery _____ (replicate/passive) across multiple studies, it _____ (constitute) strong evidence for the proposed mechanism.','to be replicated / would constitute',NULL,'"Were + subject + to be + PP" = formal subjunctive passive + would result.','hard'),
  (cid,43,153,'multiple_choice','Which "were...to" subjunctive is CORRECT?','Were the policy to be implemented immediately, it would require substantial institutional restructuring.','["Were the policy implemented immediately, it would require substantial restructuring (Type 3 structure, not were...to).","Were the policy to be implemented immediately, it would require substantial institutional restructuring.","Were the policy to implemented immediately, it would require substantial restructuring.","Were the policy has implemented immediately, it would require substantial restructuring."]','"Were + subject + to be + PP" = passive formal subjunctive.','hard'),
  (cid,43,154,'gap_fill','Were all countries _____ (agree/passive) to a binding framework, the pace of decarbonization _____ (accelerate) dramatically.','to agree / would accelerate',NULL,'"Were + subject + to + base verb" = formal hypothetical for policy scenario.','hard'),

  -- BLOCK 44: Subjuntivo optativo (literary/archaic)
  (cid,44,155,'multiple_choice','What is the subjunctive form in "Long live the republic" expressing?','An optative subjunctive — a wish or exhortation about a desired state.','["A command","An optative subjunctive — a wish or exhortation about a desired state.","A condition","A prediction"]','Optative subjunctive = expresses wish: "Live" (base form) not "lives."','hard'),
  (cid,44,156,'gap_fill','The researchers hope, and the evidence tentatively suggests, that a cure _____ (be) within reach within the next decade.','may be / be',NULL,'That + subjunctive "be" in a hope/wish clause = optative use.','hard'),
  (cid,44,157,'gap_fill','Be that _____ it _____, the fundamental question of equity in access to education _____ (remain) unresolved.','as / may / remains',NULL,'"Be that as it may" = concessive optative subjunctive expression.','hard'),
  (cid,44,158,'multiple_choice','In academic writing, "It is vital that all parties be represented in the negotiation process" uses what form?','Mandative subjunctive: "be represented" (base form of be + past participle).','["Present continuous","Passive perfect","Mandative subjunctive: ''be represented'' (base form of be + past participle).","Conditional"]','Vital that + subjunctive (be) + passive participle = mandative passive subjunctive.','medium'),

  -- BLOCK 45: TOEFL Reading
  (cid,45,159,'multiple_choice','[TOEFL Reading] "The working group recommends that the treaty be ratified before the next summit." The subjunctive "be" in "be ratified" appears because:','The verb "recommends" triggers the mandative subjunctive in formal written English.','["''Be'' is a helping verb here","The sentence is passive","The verb ''recommends'' triggers the mandative subjunctive in formal written English.","''Be ratified'' is future tense"]','Mandative subjunctive: recommends that + passive subjunctive (be + PP).','medium'),
  (cid,45,160,'gap_fill','[TOEFL Reading] "The resolution urged that member states _____ (submit) detailed action plans and _____ (refrain) from unilateral measures that might undermine collective progress." Best forms?','submit / refrain',NULL,'Mandative subjunctive: urged that + base verb x2.','medium'),
  (cid,45,161,'multiple_choice','[TOEFL Reading] "Were the scientific community to reach consensus on this point, it would significantly accelerate policy implementation." This sentence expresses:','A formal hypothetical condition about a future possible state.','["A historical fact","A definite prediction","A formal hypothetical condition about a future possible state.","A past completed event"]','"Were + subject + to + base verb" = formal hypothetical condition (Type 2 inversion).','medium'),
  (cid,45,162,'gap_fill','[TOEFL Reading] "It is crucial that the data _____ (anonymize/passive) before analysis and that all identifying information _____ (remove/passive)." Best forms?','be anonymized / be removed',NULL,'Crucial that + passive subjunctive x2 for research ethics.','hard'),

  -- BLOCK 46: TOEFL Speaking
  (cid,46,163,'production','[TOEFL Speaking — 45s] A reading proposes institutional reforms. Summarize the proposals using mandative subjunctive throughout.','',NULL,'The reading proposes a comprehensive reform of the global financial architecture to reduce the risk of future systemic crises. The reading suggests that voting rights in the International Monetary Fund be redistributed to reflect the current share of global economic output rather than the post-World War II distribution that currently prevails. It recommends that developing countries be given a greater voice in decisions that affect their economies and that the IMF adopt more flexible conditionality requirements. The reading also proposes that an independent oversight board be established to review major lending decisions and that the Fund''s mandate be explicitly broadened to incorporate considerations of social equity alongside macroeconomic stability.','hard'),
  (cid,46,164,'production','[TOEFL Speaking — 45s] Discuss what you think governments should do about income inequality. Use mandative subjunctive, were...to hypothetical, and hedged recommendations.','',NULL,'Addressing income inequality effectively requires that governments pursue a combination of tax policy reform, investment in public services, and labor market regulation. It is essential that tax systems be designed to ensure that returns to capital are taxed at rates comparable to returns to labor, since the divergence between these rates has contributed significantly to wealth concentration at the top of the distribution. Were governments to implement a comprehensive wealth tax on assets above a high threshold, it would generate revenue that could fund universal education, healthcare, and social insurance programs. I would also argue that minimum wage policy be regularly reviewed and adjusted, and that the rights of workers to organize collectively be protected rather than weakened. However, it is important that such reforms be designed carefully, lest unintended consequences — such as capital flight or reductions in investment — undermine the distributional goals.','hard'),

  -- BLOCK 47: TOEFL Writing
  (cid,47,165,'production','[TOEFL Writing — 150 words] Write a paragraph on health policy reform using mandative subjunctive throughout.','',NULL,'Effective health system reform requires that policymakers address both the supply and demand sides of healthcare simultaneously. It is essential that primary care infrastructure be strengthened before resources are directed toward expensive tertiary services, since preventive care consistently demonstrates greater cost-effectiveness per quality-adjusted life year than acute intervention. Most health economists recommend that pharmaceutical pricing be regulated more effectively, lest the cost of essential medicines remain beyond the reach of low-income populations. The evidence further suggests that health outcomes be disaggregated by income, ethnicity, and geography in national reporting systems, so that disparities do not remain invisible in aggregate statistics that conceal significant variation. International health organizations insist that member states report communicable disease data transparently and promptly, and that protocols for information sharing be established before rather than during the emergence of epidemic threats. Were these reforms to be implemented in concert, the returns in reduced mortality and morbidity would be substantial.','hard'),
  (cid,47,166,'production','[TOEFL Writing — Error Correction] Fix subjunctive errors: "The committee requires that all members submits their reports on time. It is vital that the evidence is preserved. The treaty stipulates that nations reduces emissions. Were the policy implemented sooner, the crisis may have been avoided. Lest researchers lose credibility, they must ensures accuracy."','',NULL,'submits → submit (mandative subjunctive: base form, no -s); is preserved → be preserved (mandative subjunctive passive: be + PP); reduces → reduce (mandative: base form); may have been avoided → would have been avoided (hypothetical past: would have + PP, not may); ensures → ensure (mandative/imperative: must + base verb, not ensures).','hard'),

  -- BLOCK 48: Consolidação final
  (cid,48,167,'production','[TOEFL Writing — 200 words] Write a paragraph recommending reforms to international environmental governance using mandative subjunctive, were...to, and formal hedging.','',NULL,'The limitations of current international environmental governance have been thoroughly exposed by the modest ambition and weak enforcement of successive climate agreements. Addressing these structural failures requires fundamental reform rather than incremental adjustment. It is essential that the principle of sovereignty not be permitted to exempt major emitting nations from binding commitments when the consequences of their emissions are felt globally. International lawyers and governance scholars recommend that an independent compliance body be established with the authority to assess national progress against treaty obligations and to impose proportionate consequences for persistent non-compliance. It is further proposed that the financing of the transition in developing countries be treated as a collective obligation of wealthy nations rather than a matter of voluntary contribution, and that the institutions managing this financing be governed democratically rather than by a small group of major donor countries. Were these reforms to be agreed upon at the next major climate summit, it would represent a substantial strengthening of the international framework, though the political obstacles to such ambition should not be underestimated, lest unrealistic expectations undermine the credibility of the reform process before it begins.','hard'),
  (cid,48,168,'production','[TOEFL Speaking — 60s] Discuss what should be done to reform higher education. Use mandative subjunctive throughout, plus were...to for hypotheticals.','',NULL,'Meaningful reform of higher education requires that institutions rethink their purpose, their financing, and their relationship with the communities they serve. It is vital that the cost of a university education not be permitted to create levels of debt that constrain graduates'' life choices for decades after they leave campus — a situation that current evidence suggests is deterring talented students from lower-income backgrounds from pursuing advanced education. Governments should require that universities publish outcome data disaggregated by student background, so that prospective students can assess where investment in education produces the best return. It is further recommended that institutions be required to invest a meaningful proportion of their research capacity in addressing problems of local and national relevance, rather than allocating all research effort toward prestige metrics that primarily benefit institutional rankings. Were tuition fees to be replaced by a publicly funded system with income-contingent repayment only above a generous threshold, access to higher education would be significantly more equitable. I would also propose that faculty evaluation systems be reformed so that excellence in teaching be weighted at least as heavily as research output in promotion and tenure decisions.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
