-- ============================================================
-- SEED EXT 5: Módulo 06 — Be Going To (ex 166-248)
-- Tópicos: planos concretos, previsões baseadas em evidências,
-- be going to vs will, linguagem acadêmica/policy, reported speech,
-- tarefas TOEFL integradas avançadas
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'be-going-to';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo be-going-to não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 51: Be going to para planos concretos e intenções definidas
  (cid,51,166,'gap_fill','The government _____ (introduce) a new carbon pricing mechanism next quarter, following months of consultation with industry stakeholders.','is going to introduce',NULL,'"Is going to introduce" = concrete governmental plan already decided, with evidence of preparation.','easy'),
  (cid,51,167,'gap_fill','The research team _____ (publish) their findings in a peer-reviewed journal once the data _____ (verify/passive) by an independent panel.','is going to publish / have been verified',NULL,'"Is going to publish" = definite plan; "have been verified" = future perfect in time clause.','medium'),
  (cid,51,168,'gap_fill','Both parties _____ (sign) the agreement at a formal ceremony next week, _____ (mark) the conclusion of three years of negotiations.','are going to sign / marking',NULL,'"Are going to sign" = scheduled plan + participial marking temporal result.','easy'),
  (cid,51,169,'multiple_choice','Which sentence expresses a DEFINITE PLAN using be going to?','The committee is going to review all submitted proposals before announcing the shortlist.','["The committee will probably review the proposals soon.","The committee might review the proposals next month.","The committee is going to review all submitted proposals before announcing the shortlist.","The committee would review the proposals if asked."]','"Is going to review" = concrete plan already decided. "Will probably" = lower certainty. "Might" = possibility.','easy'),
  (cid,51,170,'gap_fill','The central bank _____ (raise) interest rates by 50 basis points at its next meeting — the governor confirmed this in a press conference this morning.','is going to raise',NULL,'Confirmation of plan in press conference = definite intention signaled by "be going to."','easy'),
  (cid,51,171,'gap_fill','Three major tech companies _____ (announce) a joint initiative _____ (address) digital literacy gaps in underserved communities, _____ (represent) an unprecedented level of cross-industry collaboration.','are going to announce / to address / representing',NULL,'"Are going to announce" = confirmed plan; "to address" = infinitive of purpose; "representing" = participial.','medium'),
  (cid,51,172,'gap_fill','After years of legal battles, the city council _____ (approve) _____ rezoning of _____ waterfront district, _____ (pave) _____ way for _____ largest urban redevelopment project in _____ region''s history.','is going to approve / the / the / paving / the / the / the',NULL,'"Is going to approve" = confirmed plan + participial consequence.','medium'),

  -- BLOCK 52: Be going to para previsões baseadas em evidências presentes
  (cid,52,173,'gap_fill','Look at these unemployment figures — the economy _____ (enter) a recession. These numbers _____ (not/recover) without significant policy intervention.','is going to enter / are not going to recover',NULL,'"Going to" for evidence-based prediction: current data indicates future outcome.','easy'),
  (cid,52,174,'gap_fill','The latest climate models _____ (show) that if emissions _____ (not/cut/passive), average temperatures _____ (exceed) 2°C above pre-industrial levels within two decades.','show / are not cut / are going to exceed',NULL,'Present evidence (models show) + conditional + "going to" for evidence-based projection.','medium'),
  (cid,52,175,'multiple_choice','Which sentence uses "be going to" CORRECTLY for an evidence-based prediction?','Given current migration trends, several coastal cities are going to face severe housing shortages within a decade.','["Given current trends, several coastal cities will perhaps face housing shortages.","Several coastal cities are going to face severe housing shortages — we can see the early signs already.","Several coastal cities might face housing shortages in the future.","Several coastal cities would face housing shortages if nothing changed."]','Evidence-based prediction uses "going to": current evidence points directly to the future outcome.','medium'),
  (cid,52,176,'gap_fill','Based on _____ polling data released this morning, _____ incumbent _____ (lose) _____ election — _____ gap has widened beyond _____ margin of error.','the / the / is going to lose / the / the / the',NULL,'"Going to lose" = evidence-based prediction from current polling data.','medium'),
  (cid,52,177,'gap_fill','The supply chain disruptions _____ (worsen) unless _____ immediate action _____ (take/passive) — inventory levels _____ (reach) critical lows by end of month.','are going to worsen / immediate / is taken / are going to reach',NULL,'Evidence-based "going to" for imminent deterioration + passive in conditional.','hard'),
  (cid,52,178,'gap_fill','This structural deficit _____ (not/resolve/itself) without fundamental reforms; _____ trajectory _____ (lead) to a fiscal crisis within five years if _____ current course _____ (maintain/passive).','is not going to resolve itself / the / is going to lead / the / is maintained',NULL,'Evidence-based "going to" for structural inevitability + conditional clause.','hard'),
  (cid,52,179,'gap_fill','The early clinical trial data _____ (be) extremely promising; this treatment _____ (change) _____ way we approach chronic pain management if _____ Phase 3 results _____ (confirm) what we _____ (see).','is / is going to change / the / the / confirm / are seeing',NULL,'"Going to change" = prediction based on current evidence from trials.','hard'),

  -- BLOCK 53: Be going to vs Will — distinção crítica
  (cid,53,180,'multiple_choice','Which pair of sentences CORRECTLY contrasts "be going to" (plan) with "will" (spontaneous decision)?','A: I am going to present my research next Friday. B: The projector isn\'t working — I\'ll use the whiteboard instead.','["A: I will present my research next Friday. B: I am going to use the whiteboard instead.","A: I am going to present my research next Friday. B: The projector isn\'t working — I\'ll use the whiteboard instead.","A: I will present my research next Friday. B: I\'m going to use the whiteboard.","A: I am going to present next Friday. B: I am going to use the whiteboard."]','"Going to present" = pre-planned; "will use" = spontaneous decision made at moment of speaking.','medium'),
  (cid,53,181,'gap_fill','A: "The conference room is double-booked." B: "Don''t worry — I _____ (move) the meeting to Room B right now." A: "Good. And the catering team _____ (arrive) at noon as originally planned."','will move / is going to arrive',NULL,'"Will move" = spontaneous on-the-spot decision; "is going to arrive" = pre-arranged plan.','medium'),
  (cid,53,182,'gap_fill','Policy makers _____ (introduce) sweeping reforms next year — this has been announced. However, critics warn that without proper funding, the reforms _____ (not/achieve) their stated objectives.','are going to introduce / will not achieve / are not going to achieve',NULL,'"Going to introduce" = announced plan; "will not achieve" = prediction/assessment.','medium'),
  (cid,53,183,'multiple_choice','In academic writing, which is MORE APPROPRIATE for describing an announced government policy?','The government is going to implement the new carbon tax in January.','["The government will implement the new carbon tax in January.","The government is going to implement the new carbon tax in January.","The government implements the new carbon tax in January.","The government would implement the new carbon tax in January."]','Both are acceptable, but "is going to implement" signals that the policy has been officially announced/decided, making it slightly more precise for describing confirmed plans.','hard'),
  (cid,53,184,'gap_fill','A: "Has anyone prepared the budget report?" B: "I _____ (do) it now — give me twenty minutes." A: "Thanks. The finance team _____ (present) it to the board on Thursday regardless."','will do / is going to present',NULL,'"Will do" = spontaneous offer/decision; "is going to present" = pre-scheduled plan.','medium'),
  (cid,53,185,'gap_fill','The merger _____ (complete/passive) by Q3 — both boards _____ (approve) it unanimously. As a result, the company _____ (rebrand) across all markets, which _____ (require) significant investment.','is going to be completed / have approved / is going to rebrand / will require',NULL,'"Going to be completed/rebrand" = confirmed plans; "will require" = natural consequence/prediction.','hard'),
  (cid,53,186,'gap_fill','Unless the legislature _____ (act) swiftly, the funding shortfall _____ (force) significant service cuts — the budget office has already modeled _____ scenarios.','acts / is going to force / the',NULL,'"Is going to force" = evidence-based prediction from budget modeling.','hard'),

  -- BLOCK 54: Be going to em linguagem acadêmica e de políticas públicas
  (cid,54,187,'gap_fill','The proposed legislation _____ (transform) _____ regulatory landscape for _____ digital economy, introducing new obligations for platforms _____ (operate) across _____ jurisdiction.','is going to transform / the / the / operating / the',NULL,'"Is going to transform" for announced legislative plan + participial "operating."','medium'),
  (cid,54,188,'gap_fill','This paper _____ (argue) that current approaches to _____ problem _____ (prove) insufficient; _____ following sections _____ (examine) _____ evidence and _____ (propose) _____ alternative framework.','is going to argue / the / are going to prove / the / are going to examine / the / propose / an',NULL,'Academic "going to" for paper''s announced argumentative structure and methodology.','medium'),
  (cid,54,189,'multiple_choice','Which use of "be going to" is MOST APPROPRIATE in a policy brief?','The proposed measure is going to reduce administrative burdens on small businesses by an estimated 30%.','["The proposed measure will definitely reduce administrative burdens.","The proposed measure might reduce administrative burdens.","The proposed measure is going to reduce administrative burdens on small businesses by an estimated 30%.","The proposed measure reduces administrative burdens by 30%."]','"Is going to reduce" = based on evidence/modeling; appropriate for citing projected policy outcomes.','medium'),
  (cid,54,190,'gap_fill','The implementation of _____ new curriculum _____ (require) substantial retraining of teaching staff — _____ ministry has already budgeted for this and _____ (begin) _____ process in January.','the / is going to require / the / is going to begin / the',NULL,'"Going to require/begin" = announced plans with budget confirmation = concrete evidence of intention.','medium'),
  (cid,54,191,'gap_fill','Critics _____ (argue) that _____ proposed austerity measures _____ (disproportionately/affect) _____ most vulnerable populations — this analysis _____ (inform) our evaluation in _____ subsequent chapters.','are going to argue / the / are going to disproportionately affect / the / is going to inform / the',NULL,'Academic paper''s announced analytical trajectory using "going to."','hard'),
  (cid,54,192,'gap_fill','_____ independent evaluation _____ (assess) whether _____ program _____ (achieve) its stated outcomes. _____ evaluation team _____ (use) _____ mixed-methods approach combining _____ quantitative analysis with _____ qualitative case studies.','The / is going to assess / the / has achieved / The / is going to use / a / quantitative / qualitative',NULL,'Evaluation methodology announced with "going to" for confirmed planned approach.','hard'),
  (cid,54,193,'gap_fill','The think tank _____ (release) its annual policy review next month, which _____ (provide) _____ most comprehensive assessment of _____ government''s reform agenda to date, _____ (draw) on data from _____ 47 countries.','is going to release / is going to provide / the / the / drawing / across',NULL,'"Going to release/provide" = confirmed publication plan + participial "drawing."','medium'),

  -- BLOCK 55: Be going to em discurso indireto e estruturas complexas
  (cid,55,194,'gap_fill','The minister announced that _____ government _____ (overhaul) _____ pension system, _____ (ensure) sustainability for future generations.','the / was going to overhaul / the / ensuring',NULL,'Reported speech: "is going to" → "was going to" in past reported speech.','medium'),
  (cid,55,195,'gap_fill','The report predicted that _____ urban population _____ (double) within three decades and that _____ current infrastructure _____ (not/cope) with _____ increased demand.','the / was going to double / the / was not going to cope / the',NULL,'Reported prediction: past "was going to" for plans/predictions reported in past tense.','medium'),
  (cid,55,196,'multiple_choice','Which correctly converts "We are going to launch the initiative in March" into reported speech?','The spokesperson confirmed that they were going to launch the initiative in March.','["The spokesperson confirmed that they are going to launch the initiative in March.","The spokesperson confirmed that they were going to launch the initiative in March.","The spokesperson confirmed that they will launch the initiative in March.","The spokesperson confirmed that they would launch the initiative in March."]','Reported speech: "are going to launch" → "were going to launch" (backshift in past reporting context).','medium'),
  (cid,55,197,'gap_fill','Analysts warned that _____ policy _____ (create) _____ perverse incentives and that _____ unintended consequences _____ (outweigh) _____ projected benefits.','the / was going to create / perverse / the / were going to outweigh / the',NULL,'Reported warning with backshifted "was/were going to."','hard'),
  (cid,55,198,'gap_fill','The CEO stated that _____ company _____ (not/restructure) _____ core business but _____ (expand) into adjacent markets where _____ technology _____ (provide) _____ competitive advantage.','the / was not going to restructure / its / was going to expand / their / was going to provide / a',NULL,'Reported corporate strategy with backshifted "was going to" in complex sentence.','hard'),
  (cid,55,199,'gap_fill','Officials indicated that _____ summit _____ (address) four key agenda items and that _____ communiqué _____ (include) specific, _____ (measure/passive) commitments rather than _____ aspirational language.','the / was going to address / the / was going to include / measurable / aspirational',NULL,'Reported diplomatic announcement with backshifted "going to."','hard'),
  (cid,55,200,'gap_fill','_____ negotiating team confirmed that they _____ (accept) _____ compromise proposal but _____ (not/concede) on _____ core issue of _____ intellectual property protections.','The / were going to accept / the / were not going to concede / the / intellectual',NULL,'Reported negotiation position with backshifted "were going to."','hard'),

  -- BLOCK 56: TOEFL Reading avançado com be going to
  (cid,56,201,'multiple_choice','[TOEFL Reading] "The committee is going to review the policy framework before the end of the fiscal year." What does "is going to review" communicate?','A concrete, already-decided plan with a specific timeline.','["A spontaneous decision","A general prediction about the future","A concrete, already-decided plan with a specific timeline.","A habitual action"]','"Is going to review" = pre-decided plan, not spontaneous. Specific timeline ("before end of fiscal year") reinforces this.','easy'),
  (cid,56,202,'gap_fill','[TOEFL Reading] "Given _____ accelerating pace of sea level rise documented in _____ study, coastal communities _____ (face) increasingly frequent flooding events within _____ next two decades." Best form?','the / the / are going to face / the',NULL,'Evidence-based "going to" prediction from documented data in current study.','medium'),
  (cid,56,203,'multiple_choice','[TOEFL Reading] "The researchers are going to publish their findings, which contradict the prevailing consensus." The phrase "are going to publish" suggests:','The researchers have a definite, decided plan to publish.','["They might publish if conditions are right","The researchers have a definite, decided plan to publish.","They published already","They will spontaneously decide to publish"]','"Are going to publish" = concrete pre-existing plan, not spontaneous or tentative.','easy'),
  (cid,56,204,'gap_fill','[TOEFL Reading] "The legislation _____ (introduce/passive) during _____ next parliamentary session, _____ (mark) _____ first major reform of _____ telecommunications sector in over a decade." Best forms?','is going to be introduced / the / marking / the / the',NULL,'"Going to be introduced" = announced legislative plan (passive); participial "marking" for significance.','medium'),
  (cid,56,205,'gap_fill','[TOEFL Reading] "Unless _____ parties _____ (reach) _____ agreement before _____ deadline, _____ arbitration panel _____ (intervene) and _____ (impose) _____ binding settlement." Best forms?','the / reach / an / the / the / is going to intervene / impose / a',NULL,'Conditional + "going to intervene/impose" = confirmed procedural plan triggered by deadline.','hard'),

  -- BLOCK 57: TOEFL Speaking avançado com be going to
  (cid,57,206,'production','[TOEFL Speaking — 45s] A reading describes a city''s urban renewal plan. Summarize using "be going to" for concrete plans.','',NULL,'According to the reading, the city is going to undertake a comprehensive urban renewal program over the next decade, focusing on three interconnected priorities. First, the city is going to redevelop its waterfront district, converting former industrial land into mixed-use neighborhoods combining residential, commercial, and cultural uses. The reading also explains that the transportation authority is going to expand the metro network, adding twelve new stations to reduce car dependency and connect underserved neighborhoods to the city center. Finally, the city is going to establish a network of green corridors linking parks and natural areas, which urban planners believe is going to significantly improve air quality and residents'' quality of life. The reading notes that the city is going to fund these initiatives through a combination of public investment and public-private partnerships, with the first phase scheduled to begin within eighteen months.','hard'),
  (cid,57,207,'production','[TOEFL Speaking — 45s] A professor discusses evidence that a species is going to become extinct. Summarize the key points.','',NULL,'The professor presents compelling evidence that the species the reading describes is going to face extinction within the next thirty years unless urgent conservation measures are implemented. She explains that the species is going to lose approximately 70% of its remaining habitat as a result of deforestation and agricultural expansion, which are going to continue at current rates according to land use projections. The professor also notes that the species'' reproductive rate is too low to offset these pressures — the population is going to fall below the minimum viable threshold within two decades even under optimistic assumptions. She argues that the species is going to survive only if three conditions are met: protected habitat corridors are going to have to be established, captive breeding programs are going to need to be scaled up significantly, and illegal hunting, which is currently going to undermine conservation efforts, is going to have to be eliminated through stronger enforcement.','hard'),
  (cid,57,208,'production','[TOEFL Speaking — 60s] Discuss what a government is going to do to address climate change, based on a reading about a national climate action plan.','',NULL,'The national climate action plan described in the reading is one of the most ambitious frameworks any government has committed to, and the reading explains in detail what the government is going to do across several sectors over the next decade. In the energy sector, the government is going to phase out coal power by 2030 and replace it with renewable capacity — the reading specifies that offshore wind and utility-scale solar are going to account for 65% of electricity generation by the end of the decade, and the grid is going to be upgraded to accommodate the increased variability of renewable supply. In transportation, the government is going to mandate that all new vehicle sales be electric from 2028, and the public charging infrastructure is going to be expanded to support this transition. Buildings are going to be required to meet new energy efficiency standards by 2035, and retrofits of existing housing stock are going to be subsidized for lower-income households. The government is also going to establish a carbon pricing mechanism that is going to provide revenue for a just transition fund supporting workers in fossil fuel industries. The reading emphasizes that the government is going to review progress annually and is going to strengthen its targets if early results show that the plan is going to fall short of its 2050 net-zero commitment.','hard'),

  -- BLOCK 58: TOEFL Writing avançado com be going to
  (cid,58,209,'production','[TOEFL Writing — 200 words] Write a paragraph on educational reform using "be going to" for announced policy plans.','',NULL,'The government''s announced educational reform package is going to transform the school system in ways that have not been attempted since the comprehensive reforms of the 1970s, and the scale of the proposed changes has generated both enthusiasm among reform advocates and significant concern among teaching professionals. The reform is going to introduce a revised national curriculum that places greater emphasis on critical thinking, digital literacy, and collaborative problem-solving skills, moving away from the knowledge-transmission model that has dominated for decades. Assessment structures are going to change substantially: standardized testing at age sixteen is going to be replaced by a portfolio-based assessment system that is going to evaluate students across a broader range of competencies. The government is also going to increase per-pupil funding for schools serving disadvantaged communities, addressing the resource gap that has contributed to persistent achievement disparities. Teacher training is going to be reformed to require a stronger practicum component, and serving teachers are going to be entitled to twenty days of professional development annually. Critics have questioned whether the implementation timeline is realistic and whether the government is going to sustain funding commitments across electoral cycles. Proponents argue that without these changes, the education system is going to continue to produce graduates who are ill-prepared for an economy that is going to look very different from the one previous generations entered.','hard'),
  (cid,58,210,'production','[TOEFL Writing — 200 words] Write a paragraph about what is going to happen to global food systems under climate change.','',NULL,'Climate change is going to place unprecedented stress on global food systems over the coming decades, and the nature of the challenge is going to vary significantly across regions in ways that will require differentiated policy responses. In tropical and subtropical regions, rising temperatures are going to reduce crop yields for staple grains — wheat, maize, and rice — in areas that already struggle with food insecurity, and the compounding effects of more frequent drought and more intense rainfall events are going to make agricultural planning significantly more difficult. Irrigation-dependent agriculture in semi-arid regions is going to face growing water scarcity as glacial meltwater diminishes and rainfall patterns become less predictable. At the same time, some higher-latitude regions are going to experience longer growing seasons and the possibility of cultivating crops that were previously climatically unsuitable, potentially creating new agricultural opportunities. Fisheries are going to be disrupted by ocean warming and acidification, with tropical fisheries facing the most severe declines and significant consequences for the food security of coastal communities that depend on them. Global food trade is going to become a more important buffer against regional production failures, but it is also going to become more vulnerable to simultaneous shocks affecting multiple major producing regions. The agricultural sector is going to have to adapt through a combination of crop breeding, water management innovation, and changes in land use patterns that are going to require substantial public investment.','hard'),

  -- BLOCK 59: TOEFL Writing — perspectivas contrastantes com be going to
  (cid,59,211,'production','[TOEFL Writing — 200 words] An essay contrasting two views on what automation is going to do to employment. Write the body paragraph presenting the optimistic view.','',NULL,'Proponents of the optimistic view argue that automation is going to create more employment opportunities than it destroys, following a historical pattern in which each wave of technological change has ultimately expanded rather than contracted the total volume of work. Advocates of this position point out that automation is going to eliminate primarily routine tasks rather than entire jobs, freeing workers to concentrate on the higher-value, more fulfilling components of their roles that require human judgment, creativity, and interpersonal connection. New industries are going to emerge around the technologies of automation themselves — designing, manufacturing, programming, maintaining, and improving automated systems is going to require a substantial and growing workforce. The optimists also emphasize that rising productivity from automation is going to increase incomes and therefore demand, generating employment in sectors — particularly services — where automation is going to remain limited for the foreseeable future. They argue that education systems and retraining programs are going to adapt to equip workers with the skills that a more automated economy is going to demand, and that the transition, while disruptive for some workers, is going to result in a labor market that offers most people more rewarding work and higher living standards than the one we have today.','hard'),
  (cid,59,212,'production','[TOEFL Writing — 200 words] Write the counter-argument paragraph presenting the pessimistic view on automation and employment.','',NULL,'Critics of the optimistic scenario contend that this wave of automation is going to be fundamentally different from previous technological transitions in ways that make historical analogies misleading. Unlike earlier technologies that automated specific physical tasks while leaving cognitive work largely intact, artificial intelligence and advanced robotics are going to penetrate cognitive domains that were previously considered safe, including legal analysis, medical diagnosis, financial advice, and creative work. The pace of displacement is going to outstrip the capacity of workers to retrain, particularly older workers and those with lower educational attainment whose accumulated skills are going to become obsolete faster than new ones can be acquired. The pessimists argue that the new jobs automation is going to create are going to be concentrated at the high-skill end of the labor market, accessible only to workers with advanced technical education, while the middle-skill jobs that provided economic security for the broad middle class are going to disappear. The geographic concentration of technology-driven growth in a small number of metropolitan areas means that the gains from automation are going to bypass many communities entirely, exacerbating regional inequalities. Without active policy intervention — in retraining, income support, and the distribution of productivity gains — automation is going to deepen inequality rather than broadly share the benefits of technological progress.','hard'),

  -- BLOCK 60: TOEFL Writing — conclusões e sínteses com be going to
  (cid,60,213,'production','[TOEFL Writing — 200 words] Write a conclusion to an essay on whether renewable energy is going to replace fossil fuels.','',NULL,'The analysis presented in this essay suggests that the question is not whether renewable energy is going to replace fossil fuels, but rather how rapidly and equitably this transition is going to occur, and what policy frameworks are going to determine the distribution of its costs and benefits. The evidence reviewed demonstrates that renewable energy is going to achieve cost competitiveness across all major applications within the coming decade, driven by continuing technology improvements and economies of scale in manufacturing. The critical uncertainties are not technological but political and institutional: whether fossil fuel interests are going to successfully delay the transition through regulatory capture and political influence; whether the international coordination required to prevent carbon leakage is going to be achieved; and whether the workers and communities most dependent on fossil fuel industries are going to receive adequate support to navigate the transition. The optimistic scenario, in which renewable energy is going to account for the dominant share of global energy supply by mid-century, is technically and economically feasible. Whether it is going to be realized depends on choices that governments, institutions, and societies are making now. The stakes — for climate stability, energy security, and economic opportunity — make it imperative that these choices be made with a clear understanding of what is going to be required and what is going to be at risk if the transition is delayed.','hard'),
  (cid,60,214,'production','[TOEFL Writing — 200 words] Write an introduction to an essay on what international institutions are going to look like in 2050.','',NULL,'The international institutional architecture that is going to govern global affairs by 2050 is going to look substantially different from the system built in the aftermath of the Second World War, and the direction of change is going to be shaped by pressures that are already reshaping the distribution of global power, the nature of transnational challenges, and the domestic politics of the major states whose participation is essential for any effective multilateral system. The United Nations system, while it is not going to disappear, is going to require significant adaptation to reflect the changed relative weight of the major powers and to address the governance gaps that have become apparent in responding to global challenges — from pandemic preparedness to cyber security to climate change — that the existing institutional structure was not designed to handle. New forms of minilateral cooperation, in which smaller groups of states with shared interests or values agree to deeper forms of coordination than is possible in universal forums, are going to play an increasingly significant role alongside universal institutions. This essay is going to examine three dimensions of institutional evolution: the reform of existing multilateral bodies, the emergence of new institutional forms, and the role of non-state actors — including corporations, civil society organizations, and subnational governments — that are going to be increasingly important participants in global governance even as formal international institutions remain primarily constituted by states.','hard'),

  -- BLOCK 61: TOEFL Writing — análises complexas finais
  (cid,61,215,'production','[TOEFL Writing — 200 words] What is going to happen to global inequality over the next fifty years? Write a nuanced analytical paragraph.','',NULL,'Projecting the trajectory of global inequality over the next fifty years requires distinguishing between its international dimension — inequality between countries — and its domestic dimension — inequality within countries — since the forces driving each are going to evolve in different directions. At the international level, the convergence that has characterized the past three decades, as several large developing economies — particularly in Asia — achieved per capita income growth rates well above those of high-income countries, is going to continue for some countries and regions while stalling or reversing for others. Sub-Saharan Africa, if it is able to harness its demographic dividend through adequate investment in education and health, is going to close a significant portion of the income gap with high-income countries; if it fails to do so, the absolute gaps in living standards are going to widen further. Within countries, the picture is going to be shaped substantially by how governments respond to the distributional pressures of technological change and climate transition. Countries that invest in universal education and health, maintain strong labor market institutions, and design the taxation and transfer system to share the gains from productivity growth broadly are going to manage the within-country inequality challenge successfully; those that do not are going to experience the political tensions that accompany sustained rises in inequality, with consequences that are difficult to predict but that historical experience suggests are going to be disruptive.','hard'),
  (cid,61,216,'production','[TOEFL Writing — Final 200 words] Write a synthesis paragraph on what global health is going to look like in 2050.','',NULL,'The global health landscape of 2050 is going to be shaped by the intersection of several powerful forces, some of which are going to improve population health and others of which are going to create new challenges that current health systems are not adequately prepared to address. On the positive side, continuing advances in genomic medicine, AI-assisted diagnosis and drug development, and the diffusion of effective interventions to low-income countries are going to reduce the burden of many infectious and non-communicable diseases that currently cause enormous suffering. Life expectancy is going to continue to rise in most regions, though the pace of improvement is going to slow as populations age and the returns to further reductions in premature mortality become harder to achieve. On the negative side, the health consequences of climate change — through heat stress, vector-borne disease spread, food insecurity, and mental health impacts of displacement and extreme weather events — are going to become an increasingly significant burden, particularly in tropical and low-income regions. Antimicrobial resistance is going to undermine the effectiveness of treatments that modern medicine currently takes for granted unless major investments in new antibiotic development and stewardship programs are made. The equity dimension of global health is going to remain the central moral challenge: the technologies that are going to transform health outcomes in high-income countries are going to reach low-income populations only if deliberate effort is made to ensure access rather than allowing market forces alone to determine the distribution of health innovation.','hard'),
  (cid,61,217,'gap_fill','_____ new trade agreement _____ (enter) into force on _____ first day of _____ coming fiscal year, _____ (eliminate) tariffs on _____ wide range of goods and _____ (establish) _____ dispute resolution mechanism that _____ (govern) _____ commercial relations between _____ two blocs.','The / is going to enter / the / the / eliminating / a / establishing / a / is going to govern / the / the',NULL,'"Going to enter/govern" = confirmed treaty plan with implementation date.','hard'),
  (cid,61,218,'gap_fill','_____ commission _____ (examine) _____ proposal and _____ (report) its findings to _____ parliament within _____ three-month timeframe stipulated in _____ enabling legislation.','The / is going to examine / the / report / the / a / the',NULL,'"Going to examine" = legally mandated plan with timeline from enabling legislation.','medium'),
  (cid,61,219,'gap_fill','Barring unforeseen complications, _____ summit _____ (produce) _____ joint communiqué addressing all four agenda items, though _____ language on _____ most contentious issue _____ (require) _____ last-minute negotiation.','the / is going to produce / a / the / the / is going to require / last-minute',NULL,'"Going to produce/require" = planned outcome with caveat ("barring unforeseen complications").','hard'),
  (cid,61,220,'gap_fill','This research _____ (contribute) to _____ growing body of literature on _____ topic and _____ (inform) _____ design of future interventions aimed at _____ (address) _____ structural barriers identified in _____ analysis.','is going to contribute / the / the / is going to inform / the / addressing / the / the',NULL,'Academic "going to" for paper''s announced contribution and applied implications.','medium'),
  (cid,61,221,'multiple_choice','Which sentence uses "be going to" MOST PRECISELY in an academic policy analysis?','The regulatory changes are going to disproportionately affect SMEs, as evidenced by the impact assessment commissioned by the ministry.','["The regulatory changes will disproportionately affect SMEs.","The regulatory changes might disproportionately affect SMEs.","The regulatory changes are going to disproportionately affect SMEs, as evidenced by the impact assessment commissioned by the ministry.","The regulatory changes would disproportionately affect SMEs if implemented."]','"Are going to" + "as evidenced by" = evidence-based prediction grounded in specific commissioned research.','hard'),
  (cid,61,222,'gap_fill','_____ pilot program _____ (run) for twelve months in _____ selected districts before _____ nationwide rollout _____ (begin) — _____ evaluation _____ (provide) _____ evidence base needed to _____ (refine) _____ implementation approach.','The / is going to run / five / the / begins / the / is going to provide / the / refine / the',NULL,'"Going to run/provide" = confirmed programmatic plan; "begins" PS in time clause.','hard'),
  (cid,61,223,'gap_fill','If current demographic trends _____ (continue), _____ working-age population _____ (shrink) significantly relative to _____ retiree population, _____ (place) _____ fiscal pressure on _____ pension and healthcare systems that _____ (necessitate) fundamental reform.','continue / the / is going to shrink / the / placing / severe / the / will necessitate / is going to necessitate',NULL,'"Going to shrink" for evidence-based demographic projection; "necessitate" for consequence.','hard'),
  (cid,61,224,'gap_fill','_____ bilateral investment treaty _____ (provide) _____ framework for _____ (resolve) disputes and _____ (protect) investors from _____ discriminatory practices that _____ (undermine) _____ confidence needed to _____ (sustain) _____ long-term economic relationship.','The / is going to provide / a / resolving / protecting / discriminatory / would undermine / the / sustain / the',NULL,'"Going to provide" = confirmed treaty function + gerunds + conditional "would undermine."','hard'),
  (cid,61,225,'production','[TOEFL Speaking — 60s] A reading argues that artificial intelligence is going to fundamentally change how governments operate. Summarize and evaluate.','',NULL,'The reading makes a compelling argument that artificial intelligence is going to transform governmental operations in ways that are going to be both profound and difficult to fully anticipate. According to the reading, AI is going to change three dimensions of governance in particular. First, the delivery of public services is going to become significantly more efficient as AI tools are going to enable personalization of services at a scale that human caseworkers cannot achieve, and routine administrative tasks are going to be automated, freeing civil servants for more complex judgment-intensive work. Second, policy analysis and decision support are going to be transformed as AI systems are going to be capable of processing vastly larger bodies of evidence than human analysts and identifying patterns and connections that would otherwise be missed. Third, regulatory compliance and enforcement are going to be enhanced as AI-powered monitoring systems are going to detect violations more effectively and consistently than current inspection-based approaches. However, the reading also acknowledges that these transformations are going to create significant governance challenges of their own: questions about algorithmic accountability, the potential for embedded bias in AI systems to perpetuate discriminatory outcomes, and the concentration of powerful AI capabilities in a small number of private firms whose interests are not always going to align with the public interest are going to require new regulatory frameworks that themselves are going to need to evolve as the technology continues to develop.','hard'),
  (cid,61,226,'production','[TOEFL Writing — 200 words] Write a paragraph evaluating whether current international trade rules are going to be adequate for the twenty-first century economy.','',NULL,'The question of whether current international trade rules are going to prove adequate for the challenges of the twenty-first century economy is one of the most important and underappreciated issues in global governance, and the honest answer is that significant reform is going to be necessary if the multilateral trading system is going to remain relevant and effective. The rules established through successive GATT and WTO negotiating rounds were designed primarily for trade in physical goods between relatively similar economies and are going to be increasingly strained by the realities of a global economy in which digital services, data flows, and intellectual property are going to account for a growing share of cross-border economic exchange. The WTO''s dispute settlement system, already under severe strain from the United States'' blocking of appellate body appointments, is going to face further tests as the number and complexity of trade disputes involving digital economy issues, industrial policy, and environmental measures are going to increase. The geopolitical dimension of trade governance is going to intensify as the major powers pursue competing visions of how the global economy should be organized. The multilateral system is not going to collapse — the costs of its absence are too high — but it is going to require significant adaptation to remain the primary framework for governing international economic relations in an era when the nature of trade, the composition of major trading powers, and the political economy of trade liberalization are all going to look very different from the world in which current rules were negotiated.','hard'),
  (cid,61,227,'production','[TOEFL Writing — 200 words] Write a paragraph on how demographic change is going to reshape welfare states.','',NULL,'Demographic change is going to pose fundamental challenges to the welfare state architectures that high-income countries developed in the mid-twentieth century, when very different age structures made the financial arithmetic of pay-as-you-go pension and healthcare systems much more favorable than it is going to be over the coming decades. The ratio of workers to retirees is going to decline significantly in most high-income countries as baby boom cohorts age and fertility rates remain well below replacement level, meaning that a shrinking workforce is going to be asked to finance the retirement and healthcare costs of a growing elderly population. The fiscal implications are going to be severe: pension spending is going to consume a larger share of GDP even if benefit levels are not increased, and healthcare spending is going to rise as older populations, who consume disproportionately large amounts of medical care, account for a growing share of the total. Governments are going to face difficult choices between raising taxes, cutting benefits, increasing the retirement age, and relying more heavily on immigration to expand the working-age population. The political economy of these choices is going to be complicated by the growing electoral weight of older voters, who are going to have strong incentives to resist benefit reductions and retirement age increases. The countries that are going to manage this transition most successfully are those that begin adjusting now, while the demographic pressures are still manageable, rather than waiting until the financial imbalances are going to become acute.','hard'),
  (cid,61,228,'gap_fill','As _____ international community _____ (grapple) with _____ consequences of _____ rapid technological change, _____ governance frameworks _____ (need) _____ (adapt) _____ (ensure) that _____ benefits of innovation _____ (distribute/passive) equitably and that _____ risks _____ (manage/passive) effectively.','the / grapples / the / the / the / are going to need / to adapt / to ensure / the / are going to be distributed / the / are going to be managed',NULL,'Complex governance sentence with "going to" chains and infinitives of purpose.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
