-- ============================================================
-- SEED EXT 5: Módulo 24 — Discourse Markers (ex 184-260)
-- Novos tópicos: DMs para estruturação de TOEFL essays avançados,
-- DMs de precisão discursiva em academic writing, DMs contrastivos
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'discourse-markers';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo discourse-markers não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 51: DMs para estruturação de argumentos
  (cid,51,184,'multiple_choice','Which discourse marker signals that the writer is about to present the COUNTERARGUMENT before refuting it?','It might be argued that...','[''Furthermore...'',''It might be argued that...'',''In other words...'',''As a result...'']','''It might be argued that...'' = concessive DM that introduces an opposing view the writer will then counter.','easy'),
  (cid,51,185,'gap_fill','_____, the research does suggest a positive correlation; _____, correlation does not establish causation, and the confounding variables identified in Section 3 significantly complicate any causal interpretation.','Admittedly / however / that said',NULL,'''Admittedly'' = concessive opener + ''however/that said'' = contrastive pivot.','medium'),
  (cid,51,186,'gap_fill','The economic case for free trade is _____ compelling; _____, the distributional consequences of rapid trade liberalization can be severe for workers in import-competing industries, and these costs require serious policy attention.','undeniably / nonetheless / nevertheless',NULL,'''Undeniably'' = full concession + ''nonetheless/nevertheless'' = pivot.','medium'),
  (cid,51,187,'multiple_choice','Which sequence of DMs BEST structures a three-part argument?','First, ...; furthermore, ...; ultimately, ...','[''However, ...; in addition, ...; therefore, ...'',''First, ...; furthermore, ...; ultimately, ...'',''In contrast, ...; similarly, ...; consequently, ...'',''Although ...; because ...; despite ...'']','First (introduce), furthermore (expand), ultimately (conclude): logical three-part progression.','easy'),
  (cid,51,188,'gap_fill','The government''s fiscal consolidation strategy rests on two assumptions: _____, that economic growth will accelerate sufficiently to generate additional revenue; _____, that interest rates will remain manageable for the duration of the consolidation period.','first / second / and second',NULL,'''First...second'' = enumeration DMs in a multi-premise analysis.','easy'),
  (cid,51,189,'gap_fill','_____ reducing absolute poverty, economic growth has _____ generated new forms of inequality that raise distinct policy challenges; these two dimensions, _____, must be analyzed separately.','While / also / however / therefore / in turn',NULL,'''While...also'' = dual-effect contrast + ''however/therefore/in turn'' = analytical pivot.','hard'),

  -- BLOCK 52: DMs de precisão — nuance e limitação
  (cid,52,190,'multiple_choice','Which DM indicates that the writer is NARROWING the scope of a claim?','More specifically, this analysis focuses on middle-income countries in Sub-Saharan Africa.','[''Furthermore, this analysis...'',''In particular, therefore...'',''More specifically, this analysis focuses on middle-income countries in Sub-Saharan Africa.'',''As a result, this analysis...'']','''More specifically'' = scope-narrowing DM.','easy'),
  (cid,52,191,'gap_fill','The study''s conclusions should be treated with caution; _____, the sample size was limited, and _____, the self-reported measures may not accurately reflect actual behavior.','most notably / above all / in addition / furthermore',NULL,'DM of saliency (''most notably/above all'') + DM of addition (''in addition/furthermore'').','medium'),
  (cid,52,192,'gap_fill','This is _____ to say that no progress has been made; _____, the evidence presented above clearly demonstrates significant improvements on multiple dimensions. _____, these gains have been unevenly distributed.','not / on the contrary / however / rather / nevertheless',NULL,'''Not...to say'' + ''on the contrary'' = correction DMs. ''However/nevertheless'' = pivot.','hard'),
  (cid,52,193,'multiple_choice','Which DM phrase BEST introduces a clarification of a preceding claim?','To be precise, the study did not find that X causes Y; it found an association between them.','[''Furthermore, the study did not find that X causes Y.'',''To be precise, the study did not find that X causes Y; it found an association between them.'',''In contrast, the study did not find that X causes Y.'',''Similarly, the study did not find that X causes Y.'']','''To be precise'' = precision-clarification DM.','medium'),
  (cid,52,194,'gap_fill','The mechanism is _____ straightforward, _____ upon closer examination several complicating factors emerge, including the mediating role of institutional context.','apparently / yet / but',NULL,'''Apparently straightforward'' + ''yet'' = contrast DM introducing complication.','medium'),

  -- BLOCK 53: DMs de consequência e causalidade
  (cid,53,195,'multiple_choice','Which DM correctly introduces a LOGICAL CONSEQUENCE in academic writing?','Institutional capacity was insufficient; consequently, implementation of the reform was delayed by three years.','[''Institutional capacity was insufficient; however, implementation was delayed.'',''Institutional capacity was insufficient; consequently, implementation of the reform was delayed by three years.'',''Institutional capacity was insufficient; in contrast, implementation was delayed.'',''Institutional capacity was insufficient; similarly, implementation was delayed.'']','''Consequently'' = result DM. ''However'' = contrast; ''in contrast'' = contrast; ''similarly'' = similarity.','easy'),
  (cid,53,196,'gap_fill','The commodity price shock reduced government revenues by 30%; _____, _____ a significant contraction in public investment across health and education; _____, human capital development stalled for nearly a decade.','this led to / as a result / consequently / in turn',NULL,'Causal chain: ''led to'' + ''as a result/consequently'' + ''in turn'' = cascading causal DMs.','hard'),
  (cid,53,197,'gap_fill','Public trust in institutions has declined sharply, _____ undermining the legitimacy of the governance mechanisms _____ essential for managing collective action problems.','thereby / that are / which are',NULL,'''Thereby'' = result DM introducing participial result phrase.','hard'),
  (cid,53,198,'gap_fill','The increase in automation has displaced workers in manufacturing; _____, _____ has it reduced the total number of jobs — contrary to predictions, overall employment has actually risen — but it _____ fundamentally altered the distribution of jobs across sectors.','moreover / not only / has also',NULL,'''Moreover + not only...has also'' = additive + emphatic DM pair.','hard'),
  (cid,53,199,'multiple_choice','Which sentence uses ''hence'' CORRECTLY?','Population growth rates have stabilized in most regions; hence, demographic projections can now be made with greater confidence.','[''Population growth rates have stabilized; hence, were projected with confidence.'',''Population growth rates have stabilized in most regions; hence, demographic projections can now be made with greater confidence.'',''Hence population growth has stabilized; projections are confident.'',''Population growth stabilized; hence they have stabilized.'']','''Hence'' = formal consequence DM (= therefore/consequently), placed after the cause clause.','medium'),

  -- BLOCK 54: DMs de concession
  (cid,54,200,'gap_fill','_____ the government''s macroeconomic fundamentals remain sound, the structural reforms necessary to sustain long-term growth have yet to be implemented.','While / although / even though / despite the fact that',NULL,'''While/although/even though'' = subordinating concessive DMs. All are correct here.','easy'),
  (cid,54,201,'gap_fill','The theoretical model is elegant and parsimonious; _____, _____, it relies on assumptions that empirical research has repeatedly challenged.','that said / however / nonetheless / nevertheless / be that as it may',NULL,'''That said/however/nonetheless'' = concessive pivot DMs after the concession.','easy'),
  (cid,54,202,'gap_fill','_____ the obvious limitations of the dataset, the findings are _____ informative for policy, _____ they provide the most comprehensive cross-national comparison currently available.','despite / still / as / in that / given',NULL,'''Despite'' (concessive) + ''still'' (nonetheless) + ''in that/as'' (reason/specification).','hard'),
  (cid,54,203,'multiple_choice','Which DM introduces an UNEXPECTED result after a concession?','The intervention was implemented with significant fanfare; surprisingly, however, outcomes were no better than in the control group.','[''The intervention was implemented with significant fanfare; similarly, outcomes were no better.'',''The intervention was implemented with significant fanfare; surprisingly, however, outcomes were no better than in the control group.'',''The intervention was implemented; consequently, outcomes were better.'',''Furthermore, the intervention was implemented; outcomes were better.'']','''Surprisingly, however'' = unexpected-result DM pair combining attitude marker + contrast.','medium'),

  -- BLOCK 55: TOEFL Reading avançado com DMs
  (cid,55,204,'multiple_choice','[TOEFL Reading] ''The data suggests an improvement; however, the improvement is confined to high-income groups. In other words, aggregate progress may mask distributional deterioration.'' The DMs ''however'' and ''in other words'' serve to:','Contrast the surface result and then clarify the distributional problem.','[''Add information, then summarize'',''Contrast the surface result and then clarify the distributional problem.'',''Enumerate two separate findings'',''Concede a limitation and then refute it'']','''However'' = contrast (aggregate vs. distributional). ''In other words'' = clarification/restatement.','medium'),
  (cid,55,205,'gap_fill','[TOEFL Reading] ''Innovation has accelerated in recent decades; _____, the benefits have not been evenly shared across the population, _____, they have disproportionately accrued to those who were already well positioned to capture them.'' Best DMs?','however / indeed / in fact / rather',NULL,'''However'' = contrast + ''indeed/in fact'' = intensification/specification of the contrast.','medium'),
  (cid,55,206,'multiple_choice','[TOEFL Reading] ''First, X; second, Y; finally, Z.'' This structure signals:','Enumeration of three sequential or parallel points.','[''A concession followed by a rebuttal'',''A cause-and-effect sequence'',''Enumeration of three sequential or parallel points.'',''A definition followed by two examples'']','First/second/finally = ordinal enumeration DMs.','easy'),
  (cid,55,207,'gap_fill','[TOEFL Reading] ''The proposed solution is not merely impractical; _____, it may actively worsen the problem it seeks to address.'' Best intensifying DM?','worse still / more seriously / what is more',NULL,'''Worse still/more seriously'' = escalating DMs that intensify the critique beyond the initial claim.','medium'),

  -- BLOCK 56: TOEFL Speaking avançado com DMs
  (cid,56,208,'production','[TOEFL Speaking — 45s] A reading argues for expanding nuclear energy. A lecture raises safety and cost concerns. Summarize using discourse markers.','',NULL,'The reading presents a case for expanding nuclear energy as a reliable low-carbon energy source. It argues that nuclear power offers consistent baseload generation that renewable energy currently cannot provide, and that modern reactor designs have improved substantially in safety relative to older designs. However, the lecture complicates this picture in two significant respects. First, the professor argues that the cost trajectory for nuclear energy has been unfavorable: whereas the costs of solar and wind have fallen dramatically, the cost of constructing new nuclear facilities has, by contrast, increased substantially in most Western countries. Second, and more fundamentally, the professor emphasizes that the problem of long-term nuclear waste storage has not been resolved; despite decades of research, no country has successfully implemented a permanent high-level waste repository. Consequently, the lecture concludes, expanding nuclear energy would compound an already serious unresolved problem. Taken together, these arguments suggest that the case for nuclear is considerably weaker than the reading implies.','hard'),
  (cid,56,209,'production','[TOEFL Speaking — 45s] Use discourse markers to structure an argument about whether social media does more harm than good.','',NULL,'At first glance, social media might appear to offer a straightforward net benefit: it enables global communication, facilitates social movements, and provides access to information on an unprecedented scale. However, on closer examination, the evidence suggests that the harms it generates may outweigh these benefits. To begin with, the algorithmic design of major platforms incentivizes content that provokes strong emotional responses, which in practice means that misinformation and outrage travel further and faster than accurate, measured information. Furthermore, experimental research has linked heavy social media use to increased rates of depression and anxiety, particularly among adolescents. That said, it would be an overstatement to attribute all of these harms to social media alone; pre-existing social and economic conditions also play a significant role. Nevertheless, the fact that platform design choices actively amplify harmful content for commercial reasons means that these harms are not an unavoidable byproduct of social media — they are, in large part, a designed outcome. In sum, while social media has genuine benefits, its current form does more harm than good.','hard'),

  -- BLOCK 57: TOEFL Writing avançado com DMs
  (cid,57,210,'production','[TOEFL Writing — 200 words] Write a body paragraph on healthcare inequality using a rich variety of discourse markers.','',NULL,'Healthcare inequality represents one of the most persistent failures of contemporary social policy, and its causes are multifaceted. To begin with, geographical concentration of healthcare resources in urban areas means that rural populations must travel long distances or forgo care entirely; this disparity is particularly acute in large countries with dispersed populations. Furthermore, systemic inequalities in the quality of care provided to different racial and socioeconomic groups have been extensively documented, even when controlling for insurance coverage. In addition, cost remains a fundamental barrier: in healthcare systems with high out-of-pocket expenses, the poorest households consistently face the most severe access constraints at precisely the moments when they are most vulnerable to health shocks. It might be argued that expanded insurance coverage adequately addresses these access problems; however, coverage is a necessary but not sufficient condition for equitable care — quality, provider availability, and cultural competence matter equally. What is more, the social determinants of health — housing, nutrition, education, and environmental conditions — shape health outcomes profoundly upstream of the healthcare system itself, meaning that healthcare reform alone, however ambitious, cannot close health gaps driven by broader socioeconomic inequality. A comprehensive approach must therefore address both the healthcare system and the social conditions it serves.','hard'),
  (cid,57,211,'production','[TOEFL Writing — 200 words] Write a body paragraph on technological unemployment using discourse markers to structure a balanced argument.','',NULL,'The relationship between technological change and employment has been a source of debate since the Industrial Revolution, and the advent of artificial intelligence and automation has reinvigorated concerns about large-scale job displacement. On one hand, historical evidence is reassuring: previous waves of technological change eliminated certain categories of work while simultaneously creating new ones, often resulting in net employment growth over the long run. The introduction of mechanized agriculture, for example, displaced agricultural laborers; however, it also released labor for industrial and service employment that ultimately supported far higher living standards. On the other hand, there are reasons to question whether the current wave of AI-driven automation will follow the same pattern. Unlike previous technologies, AI can perform cognitive as well as physical tasks, which means the scope of automation is broader. Furthermore, the pace of technological change may be too rapid for labor markets and educational systems to adapt through the mechanisms that worked in previous transitions. That said, the magnitude of actual displacement so far has been smaller than many forecasters predicted. In sum, the evidence is mixed: technological unemployment is a serious risk that warrants policy attention, but it is not the economic catastrophe that the most alarmist accounts suggest.','hard'),

  -- BLOCK 58: Final
  (cid,58,212,'production','[TOEFL Writing — 200 words] Write a paragraph on immigration policy using varied discourse markers throughout.','',NULL,'Immigration policy engages some of the most contested questions in contemporary democratic politics, and the discourse markers that structure arguments about it often reveal unstated assumptions about national identity, economic interest, and social cohesion. At the most basic level, the economic evidence on immigration is consistent: immigrants tend to contribute positively to the receiving country''s economic output, fill labor shortages in both high-skill and essential low-wage sectors, and in most cases contribute more in taxes than they receive in public services over their lifetimes. Furthermore, high-immigration societies consistently rank among the most innovative, since the diversity of perspectives and experiences that immigrants bring generates measurably higher rates of new firm formation and patent applications. However, these aggregate benefits mask distributional concerns that political discourse has often been slow to address honestly: when immigration competes directly for jobs and housing with existing low-income workers, those workers bear costs that are not evenly spread across the population. What is more, the pace of demographic change in receiving communities can generate legitimate social anxieties about cultural continuity and public service capacity that economic data alone cannot resolve. Consequently, effective immigration policy must balance openness with managed pace, credible enforcement, and serious investment in integration — not because the economic case for immigration is weak, but because sustainable openness requires a social contract that most receiving societies have not yet built.','hard'),
  (cid,58,213,'production','[TOEFL Speaking — 60s] Summarize arguments for and against free trade using discourse markers throughout.','',NULL,'The case for free trade rests on economic theory that has been tested and refined over two centuries. In brief, the theory of comparative advantage holds that when countries specialize in the goods and services they produce most efficiently and exchange with others, total economic output is higher than if each country tried to produce everything domestically. Empirically, the dramatic expansion of global trade since the mid-twentieth century has been accompanied by historically unprecedented economic growth and poverty reduction. Furthermore, trade exposes domestic firms to international competition, which creates pressure for productivity improvement and innovation. That said, the distributional consequences of trade liberalization are considerably more contested. While aggregate gains are well documented, those gains are concentrated among owners of capital and highly skilled workers; in contrast, workers in import-competing industries may face job losses, wage stagnation, and community disruption that are both economically and socially severe. What is more, economists have often understated these adjustment costs and overstated the speed with which displaced workers transition to new employment. Consequently, the strongest argument for free trade is not that it benefits everyone — it manifestly does not in the short run — but that the aggregate gains are sufficient to compensate losers, if governments have the political will to actually do so. In practice, however, that redistribution has been systematically underprovided, which is a central reason why popular support for trade liberalization has declined.','hard'),
  (cid,58,214,'production','[TOEFL Writing — 200 words] Write a conclusion on urban planning using discourse markers for summary, implication, and recommendation.','',NULL,'The foregoing analysis has demonstrated that effective urban planning requires simultaneous attention to spatial efficiency, social equity, and environmental sustainability — three objectives that are in tension with one another but not fundamentally incompatible if governance frameworks are designed with that complexity in mind. In sum, the evidence suggests that compact, mixed-use, transit-oriented development patterns offer the most promising path toward cities that are both economically productive and environmentally sustainable. However, this conclusion comes with an important caveat: density and compactness, if they are not accompanied by deliberate policies to maintain housing affordability and prevent displacement, tend to benefit the already-advantaged and push lower-income populations to peri-urban areas with poor connectivity and services. Consequently, transport-oriented development must be paired with affordable housing mandates, community land trusts, or other mechanisms for capturing land value increases for public benefit rather than allowing them to accrue exclusively to existing landowners. Furthermore, effective urban planning requires governance capacity and political coordination across municipal boundaries that most metropolitan areas currently lack. In conclusion, the technical knowledge required to plan equitable and sustainable cities largely exists; what is missing, in most cases, is the political architecture to implement it — and building that architecture is ultimately a democratic rather than a technocratic challenge.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
