-- ============================================================
-- SEED EXT 2: Módulo 13 — Reported Speech (exercícios 71-190)
-- Novos tópicos: reporting questions, commands, verb variety,
-- no backshift cases, mixed tenses, TOEFL production
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'reported-speech';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo reported-speech não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 11: reporting yes/no questions
  (cid,11,71,'gap_fill','Direct: "Are you coming to the conference?" → Reported: She asked me ___ I ___ coming to the conference.','if/whether / was',NULL,'Yes/No questions → asked + if/whether + subject + past verb.','medium'),
  (cid,11,72,'multiple_choice','Change to reported speech: "Is the data available?"','The researcher asked whether the data was available.','["The researcher asked was the data available.","The researcher asked if the data is available.","The researcher asked whether the data was available.","The researcher said whether the data was available."]','Asked + whether/if + subject + past verb (no inversion in reported).','medium'),
  (cid,11,73,'gap_fill','Direct: "Do you understand the methodology?" → Reported: He asked her ___ she ___ the methodology.','if/whether / understood',NULL,'Do + understand → if/whether + understood.','medium'),
  (cid,11,74,'gap_fill','Direct: "Have you submitted your application?" → Reported: The professor asked me ___ I ___ my application.','whether / had submitted',NULL,'Have + submitted → had + submitted (present perfect → past perfect).','hard'),
  (cid,11,75,'multiple_choice','Identify the error: "She asked me did I have the results."','Word order error — no inversion in reported questions','["She should be He","asked should be told","Word order error — no inversion in reported questions","results should be result"]','Reported questions: no auxiliary inversion. "She asked me if I had the results."','hard'),
  (cid,11,76,'gap_fill','Direct: "Will the experiment be completed on time?" → Reported: They wondered ___ the experiment ___ be completed on time.','if/whether / would',NULL,'Will → would; if/whether + normal word order.','medium'),
  (cid,11,77,'multiple_choice','Which sentence correctly reports a yes/no question?','She asked whether he had read the article.','["She asked had he read the article.","She asked whether did he read the article.","She asked whether he had read the article.","She asked if he reads the article."]','Whether + subject + past perfect (no inversion, backshift).','medium'),

  -- BLOCK 12: reporting wh-questions
  (cid,12,78,'gap_fill','Direct: "Where did you conduct the research?" → Reported: She asked me ___ I ___ conducted the research.','where / had',NULL,'Wh- + subject + past perfect (when-question → past perfect in reported).','hard'),
  (cid,12,79,'multiple_choice','Change to reported speech: "What does the hypothesis suggest?"','He asked what the hypothesis suggested.','["He asked what does the hypothesis suggest.","He asked what the hypothesis suggested.","He asked what did the hypothesis suggest.","He said what the hypothesis suggested."]','Wh- + subject + past verb (no inversion).','medium'),
  (cid,12,80,'gap_fill','Direct: "Why haven''t you submitted the report?" → Reported: She asked me why I ___ submitted the report.','hadn''t',NULL,'Why + hadn''t + past participle for present perfect negative backshift.','hard'),
  (cid,12,81,'gap_fill','Direct: "How long did the experiment last?" → Reported: They asked how long the experiment ___ lasted.','had',NULL,'Past simple → past perfect in reported wh-question.','hard'),
  (cid,12,82,'multiple_choice','Which reported wh-question is CORRECT?','The professor asked what topic I had chosen for my thesis.','["The professor asked what topic had I chosen.","The professor asked what topic I had chosen for my thesis.","The professor asked what topic did I choose.","The professor asked what topic I choose."]','Wh- + subject + past perfect (no inversion, backshift).','medium'),
  (cid,12,83,'gap_fill','Direct: "Who wrote this paper?" → Reported: She asked ___ ___ written the paper.','who had',NULL,'"Who" as subject in reported question: who + had + past participle (subject question keeps word order).','hard'),
  (cid,12,84,'multiple_choice','Convert: "When will the results be published?" → Reported?','The editor asked when the results would be published.','["The editor asked when will the results be published.","The editor asked when would the results be published.","The editor asked when the results would be published.","The editor asked when the results will be published."]','When + subject + would (will → would, no inversion).','medium'),

  -- BLOCK 13: reporting commands and requests
  (cid,13,85,'gap_fill','Direct: "Please submit your assignment by Friday." → Reported: The professor ___ us to submit our assignment by Friday.','told / asked',NULL,'Reporting commands: tell/ask + object + to + infinitive.','easy'),
  (cid,13,86,'multiple_choice','Change to reported speech: "Don''t plagiarize your work!"','The professor warned them not to plagiarize their work.','["The professor warned them don''t plagiarize.","The professor warned them that don''t plagiarize.","The professor warned them not to plagiarize their work.","The professor warned them to not plagiarize."]','Negative reported command: told/warned + object + not + to + infinitive.','medium'),
  (cid,13,87,'gap_fill','Direct: "Could you help me with the data analysis?" → Reported: He asked her ___ help him with the data analysis.','to',NULL,'Polite request → asked + object + to + infinitive.','easy'),
  (cid,13,88,'gap_fill','Direct: "Stop using your phone in the lab!" → Reported: She ordered them ___ using their phones in the lab.','to stop',NULL,'Reporting orders: ordered/told + object + to + infinitive.','medium'),
  (cid,13,89,'multiple_choice','Convert: "Please don''t interrupt during the lecture." → Reported?','She asked us not to interrupt during the lecture.','["She asked us don''t interrupt during the lecture.","She asked us to not interrupt during the lecture.","She asked us not to interrupt during the lecture.","She asked not to us interrupt during the lecture."]','Asked + us + not + to + infinitive.','medium'),
  (cid,13,90,'gap_fill','Direct: "Be at the lab by 8 AM." → Reported: He instructed them ___ at the lab by 8 AM.','to be',NULL,'Instructed + object + to + be.','medium'),
  (cid,13,91,'multiple_choice','Which reporting verb is MOST appropriate for: "Direct: ''You must attend the seminar.''"?','insisted','["suggested","insisted","wondered","claimed"]','"Insisted" = strong obligation. "Must → insisted (that) + clause OR insisted on + gerund."','hard'),
  (cid,13,92,'gap_fill','Direct: "Try to read at least 3 articles per week." → Reported: She advised them ___ to read at least 3 articles per week.','to try',NULL,'Advised + object + to + infinitive.','easy'),
  (cid,13,93,'multiple_choice','Choose the reported form of a suggestion: "Why don''t you use a different methodology?"','She suggested using a different methodology.','["She suggested them to use a different methodology.","She suggested why don''t I use a different methodology.","She suggested using a different methodology.","She suggested to use a different methodology."]','Suggest + gerund OR suggest + that + clause (NOT suggest + to + infinitive).','hard'),

  -- BLOCK 14: variety of reporting verbs
  (cid,14,94,'multiple_choice','Which reporting verb best fits: "Direct: ''I didn''t take the files,'' he said."?','denied','["suggested","denied","admitted","warned"]','"Denied" + gerund or that-clause for denial of an action.','medium'),
  (cid,14,95,'gap_fill','He ___ that the experiment had been a success. (admit)','admitted',NULL,'"Admit" = confess/acknowledge. Admitted + that-clause.','medium'),
  (cid,14,96,'multiple_choice','Which verb fits: "Direct: ''You should definitely apply for the grant,'' she said."?','encouraged','["ordered","denied","encouraged","complained"]','"Encouraged" + object + to + infinitive for positive advice.','medium'),
  (cid,14,97,'gap_fill','The researcher ___ having made an error in the calculations. (refuse to accept → admit)','admitted',NULL,'"Admitted having made" = admitted + perfect gerund.','hard'),
  (cid,14,98,'multiple_choice','Choose the correct reporting verb: "''I will absolutely win the award,'' she said."','boasted','["asked","boasted","doubted","suggested"]','"Boasted" = claimed proudly/arrogantly.','medium'),
  (cid,14,99,'gap_fill','She ___ that the new policy would increase inequality. (warn in formal speech)','warned',NULL,'"Warned" + that-clause for prediction of negative consequence.','medium'),
  (cid,14,100,'multiple_choice','Which structure is correct with "suggest"?','She suggested that the team reconsider the approach.','["She suggested to reconsider the approach.","She suggested the team to reconsider the approach.","She suggested that the team reconsider the approach.","She suggested to the team that reconsider the approach."]','Suggest + that + subject + base verb (subjunctive) OR suggest + gerund.','hard'),
  (cid,14,101,'gap_fill','The professor ___ participating in the research project. (recommend)','recommended',NULL,'"Recommended" + gerund OR recommend + that + subject + base verb.','medium'),
  (cid,14,102,'multiple_choice','Match: "''I''m sorry I was late,'' he said." → Reported?','He apologized for being late.','["He apologized that he is late.","He said sorry he was late.","He apologized for being late.","He apologized to be late."]','Apologize + for + gerund.','hard'),
  (cid,14,103,'gap_fill','The committee ___ the proposal, saying it lacked sufficient evidence. (reject → reporting verb)','rejected / criticized',NULL,'"Criticized" or "rejected" for negative evaluation in reported speech context.','medium'),
  (cid,14,104,'multiple_choice','Which reporting verb implies UNCERTAINTY about the truth of the claim?','claimed','["stated","announced","claimed","confirmed"]','"Claimed" implies the speaker asserted something that may or may not be true. "Stated" and "confirmed" are more certain.','hard'),

  -- BLOCK 15: no backshift cases (still true / general fact)
  (cid,15,105,'multiple_choice','When is backshift NOT required in reported speech?','When the reported statement is still true at the time of reporting.','["When the reporting verb is in the past","When the reported statement is still true at the time of reporting.","When the speaker is formal","When the reporting verb is ''say''"]','No backshift when the original statement is still a fact/truth.','hard'),
  (cid,15,106,'gap_fill','Direct: "Water freezes at 0°C." → Reported: She explained that water ___ at 0°C. (no backshift needed)','freezes',NULL,'Scientific fact: backshift optional. Freezes is correct (still true).','hard'),
  (cid,15,107,'multiple_choice','Choose the sentence where backshift is CORRECTLY omitted:','He said that the Earth revolves around the Sun.','["He said that the deadline was the following day (time-sensitive — backshift needed).","He said that the Earth revolves around the Sun.","He said that he will finish soon (future — backshift needed: would).","He told me that she was arriving (present continuous — backshift to past continuous)."]','Scientific permanent truth → no backshift required.','hard'),
  (cid,15,108,'gap_fill','Direct: "I work at Oxford University." → Reported (she still works there): She said she ___ at Oxford. (two options)','works / worked',NULL,'When still true at time of reporting, present simple (works) is acceptable. Past (worked) also accepted.','hard'),
  (cid,15,109,'multiple_choice','A journalist reports a politician''s speech given today: "The Prime Minister said inflation is under control." Why is the present tense used?','The statement was made recently and may still be the official position.','["The journalist made a grammar error","Present tense is never used in reported speech","The statement was made recently and may still be the official position.","\"Said\" is not a reporting verb"]','Immediate reporting or still-valid facts allow no backshift.','hard'),
  (cid,15,110,'gap_fill','Direct: "The best way to learn is through practice." → Reported: The professor reminded us that the best way to learn ___ through practice.','is / was',NULL,'General truth / opinion — both are acceptable; no backshift (is) or backshift (was).','hard'),
  (cid,15,111,'multiple_choice','Which scenario REQUIRES backshift?','She told me last week that she "will" send the files.','["The professor explained that DNA contains genetic information (permanent fact).","She told me last week that she ''will'' send the files.","He said the meeting starts at 10 (schedule still valid).","The author argues that literacy rates are improving."]','A personal promise/future made in the past that may not have happened requires backshift: would.','hard'),

  -- BLOCK 16: mixed tense review
  (cid,16,112,'gap_fill','Direct: "We have been studying this phenomenon for two years." → Reported: They reported that they ___ studying the phenomenon for two years.','had been',NULL,'Present perfect continuous → past perfect continuous.','hard'),
  (cid,16,113,'multiple_choice','Convert: "The results will be ready by next week." → Reported?','She said the results would be ready by the following week.','["She said the results will be ready by next week.","She said the results would be ready by the following week.","She said the results were ready by the following week.","She said the results would be ready by next week."]','Will → would; next week → the following week.','medium'),
  (cid,16,114,'gap_fill','Direct: "I had already submitted the report before the deadline." → Reported: He said he ___ already ___ the report before the deadline.','had / submitted',NULL,'Past perfect stays as past perfect (no further backshift possible).','hard'),
  (cid,16,115,'multiple_choice','Which reported speech sentence is CORRECT?','He told me that he had been working on the project for months and that the deadline was approaching quickly.','["He told me that he has been working on the project for months and that the deadline is approaching.","He told me that he had been working on the project for months and that the deadline was approaching quickly.","He said me that he had been working and that deadline was approaching.","He told that he has been working and the deadline was approaching quickly."]','Had been working (present perfect continuous → past perfect continuous) + was approaching.','hard'),
  (cid,16,116,'gap_fill','Direct: "Don''t worry — everything is under control." → Reported: She assured us ___ not to worry and that everything ___ under control.','not to / was',NULL,'Command (not to worry) + statement (was under control) combined.','hard'),
  (cid,16,117,'multiple_choice','Convert: "I might join the research team next semester." → Reported?','He said he might join the research team the following semester.','["He said he might join the research team next semester.","He said he might join the research team the following semester.","He said he may join the research team the following semester.","He told he might join the research team the following semester."]','Might stays as might (no further backshift); next semester → the following semester.','medium'),
  (cid,16,118,'gap_fill','Direct: "The paper has just been accepted by the journal!" → Reported: She announced that the paper ___ just ___ accepted by the journal.','had / been',NULL,'Present perfect → past perfect passive in reported speech.','hard'),

  -- BLOCK 17: TOEFL Reading — reported speech in academic texts
  (cid,17,119,'multiple_choice','[TOEFL Reading] "Smith (2019) argued that economic growth does not necessarily lead to improved well-being." The verb "argued" indicates:','Smith made this claim in his published work.','["Smith changed his mind later","Smith made this claim in his published work.","Smith is currently arguing this","The author disagrees with Smith"]','Academic reporting verb "argued" = this was his published position.','easy'),
  (cid,17,120,'gap_fill','[TOEFL Reading] A passage reports: "Early researchers hypothesized that the virus ___ (spread) primarily through air." Best tense?','spread',NULL,'Hypothesized + that + past simple for reporting a past belief.','medium'),
  (cid,17,121,'multiple_choice','[TOEFL Reading] "Critics contend that current climate models underestimate warming rates." The present tense "underestimate" (no backshift) suggests:','The critics still hold this position — it is their ongoing claim.','["This was a past position now abandoned","The critics still hold this position — it is their ongoing claim.","The author is reporting a historical error","The models have been corrected"]','No backshift = ongoing view still held by critics.','hard'),
  (cid,17,122,'gap_fill','[TOEFL Reading] "The study reported that participants ___ (experience) significant improvements in both physical and cognitive health." Best tense?','experienced / had experienced',NULL,'Reported + that + past simple or past perfect for completed outcome.','medium'),
  (cid,17,123,'multiple_choice','[TOEFL Reading] In the sentence "The author notes that rising temperatures correlate with increased migration," what does "notes" signal?','The author is drawing attention to a relationship as a current observation.','["A historical discovery","A future prediction","The author is drawing attention to a relationship as a current observation.","A command to the reader"]','Notes = present academic reporting verb; correlate = present simple (general truth).','hard'),
  (cid,17,124,'gap_fill','[TOEFL Reading] "Darwin maintained that species ___ (evolve) through natural selection." Fill the blank (reporting ongoing theory).','evolve',NULL,'Maintained = past reporting verb; evolve = present (still-true theory). No backshift needed.','hard'),
  (cid,17,125,'multiple_choice','[TOEFL Reading] "The researchers admitted they had overlooked several confounding variables." This reports:','A concession/acknowledgment of a methodological error.','["A prediction","A command","A concession/acknowledgment of a methodological error.","A question"]','Admitted = acknowledging something (often negative) that was not initially disclosed.','medium'),

  -- BLOCK 18: TOEFL Listening
  (cid,18,126,'multiple_choice','[TOEFL Listening] The professor says: "As Smith noted in 2018, migration patterns have shifted dramatically." How would a student report this?','The professor said that Smith had noted that migration patterns had shifted dramatically.','["The professor said Smith noted migration patterns shift dramatically.","The professor said that Smith had noted that migration patterns had shifted dramatically.","The professor says Smith noted migration patterns shifted.","The professor told Smith that migration patterns had shifted."]','Said + that (reporting clause) + past perfect (noted → had noted) + had shifted (backshift).','hard'),
  (cid,18,127,'gap_fill','[TOEFL Listening] A student reports what the professor said: "She explained that the brain ___ (rewire) itself throughout life, a process known as neuroplasticity." Best form?','can rewire / rewires',NULL,'Can rewire or rewires = general fact; no backshift because it''s a scientific truth.','hard'),
  (cid,18,128,'multiple_choice','[TOEFL Listening] A professor warns: "Don''t rely solely on quantitative data." A student reports this as:','The professor warned us not to rely solely on quantitative data.','["The professor warned us don''t rely solely on data.","The professor warned that we don''t rely solely on data.","The professor warned us not to rely solely on quantitative data.","The professor told we not to rely solely on data."]','Warned + us + not + to + infinitive.','medium'),
  (cid,18,129,'gap_fill','[TOEFL Listening] "The lecturer suggested ___ the methodology section before the literature review." (complete → gerund)','reviewing / reading',NULL,'Suggested + gerund for informal recommendation.','medium'),
  (cid,18,130,'multiple_choice','[TOEFL Listening] A student summarizes a lecture: "The professor explained how the printing press changed information distribution." Which is the best reported speech expansion?','The professor explained that the printing press had dramatically changed the way information was distributed.','["The professor explained how does the printing press change information distribution.","The professor explained that the printing press had dramatically changed the way information was distributed.","The professor explained the printing press changes information distribution.","The professor explained how had the printing press changed information."]','Explained + that + past perfect (changed → had changed) + normal word order.','hard'),

  -- BLOCK 19: TOEFL Speaking production
  (cid,19,131,'production','[TOEFL Speaking — 45s] You just read an article arguing that cities should invest more in public transport. Report what the article argued, what evidence it provided, and what it recommended. Use at least 4 different reporting verbs.','',NULL,'The article argued that... It claimed that... The author noted that... It recommended that cities... The study suggested investing in...','hard'),
  (cid,19,132,'production','[TOEFL Speaking — 45s] A professor gave a lecture about the effects of social media on mental health. Report 3 key points from the lecture using reported speech. Include: a statement, a question posed to the class, and a recommendation.','',NULL,'The professor stated that... She asked us whether... She then recommended that students...','hard'),
  (cid,19,133,'production','[TOEFL Speaking — 45s] Describe a conversation you had with your academic advisor about your study plan. Use reported speech throughout, including what each person said, asked, and suggested.','',NULL,'My advisor told me that I should focus on... She asked whether I had considered... I explained that I was planning to... She suggested taking...','hard'),
  (cid,19,134,'production','[TOEFL Speaking — 45s] Report the main arguments from a debate on whether technology should be used in classrooms. Use a variety of reporting verbs: argued, claimed, maintained, contended, acknowledged, admitted.','',NULL,'Supporters argued that technology enhances engagement... Critics maintained that it distracts students... One participant acknowledged that evidence is mixed... Opponents contended that face-to-face learning cannot be replaced...','hard'),

  -- BLOCK 20: TOEFL Writing production
  (cid,20,135,'production','[TOEFL Writing] Write a paragraph summarizing an academic study using at least 5 different reporting verbs. Include: what the authors argued, what they found, what they acknowledged, what they recommended, and what they claimed.','',NULL,'Smith et al. (2022) argued that climate change accelerates migration. They found a significant correlation between temperature and displacement rates. The authors acknowledged that their sample was limited. They recommended further longitudinal research. They claimed that their model could predict future migration flows with 80% accuracy.','hard'),
  (cid,20,136,'production','[TOEFL Writing — Error Correction] Fix all errors in reported speech: "The professor said me that I must work harder. She asked where did I live. She suggested me to study more. She admitted that she was wrong about the deadline."','',NULL,'said me → told me; must → should/had to; where did I live → where I lived (no inversion); suggested me → suggested (that) I should study more (not "suggested me to"); admitted → correct.','hard'),
  (cid,20,137,'production','[TOEFL Writing] Write 5 sentences in reported speech summarizing a fictional panel discussion on artificial intelligence, using a different reporting verb for each speaker (argued, claimed, acknowledged, warned, suggested).','',NULL,'The first speaker argued that AI would create more jobs than it eliminated. A researcher claimed that safety protocols were inadequate. An ethicist acknowledged that both risks and benefits were significant. A CEO warned that regulation could stifle innovation. The moderator suggested that international cooperation was essential.','hard'),
  (cid,20,138,'production','[TOEFL Writing — 150 words] Write a paragraph reporting the key points of a hypothetical lecture on the psychology of motivation. Use: stated, noted, argued, highlighted, recommended. Include backshifted tenses and time expression changes.','',NULL,'The professor stated that intrinsic motivation was a more powerful driver than external rewards. She noted that previous research had consistently supported this finding. She argued that educational systems too often relied on grades rather than curiosity. She highlighted that students who pursued genuine interest performed significantly better. She recommended that educators should therefore design curricula around authentic problems and student choice.','hard'),

  -- BLOCK 21: advanced mixed practice
  (cid,21,139,'multiple_choice','[TOEFL] Which correctly reports: "I''ll have finished the analysis by tomorrow"?','She said she would have finished the analysis by the following day.','["She said she will have finished the analysis by tomorrow.","She said she would have finished the analysis by the following day.","She said she had finished the analysis by the following day.","She said she would finish the analysis by tomorrow."]','Will have + past participle → would have + past participle (future perfect backshift) + tomorrow → the following day.','hard'),
  (cid,21,140,'gap_fill','Direct: "I wouldn''t say the results are conclusive." → Reported: He cautioned that he ___ say the results ___ conclusive.','wouldn''t / were',NULL,'Wouldn''t stays (no backshift for already past modals); are → were.','hard'),
  (cid,21,141,'multiple_choice','Which sentence uses a reporting verb + preposition correctly?','The committee insisted on reviewing the proposal before making a decision.','["The committee insisted to review the proposal.","The committee insisted reviewing the proposal.","The committee insisted on reviewing the proposal before making a decision.","The committee insisted that they review the proposal before make a decision."]','Insist + on + gerund.','hard'),
  (cid,21,142,'production','[TOEFL Writing — Capstone] Write a 200-word academic paragraph in which you summarize and evaluate two contrasting studies on screen time and children''s cognitive development. Use reported speech (at least 6 reporting verbs) with correct tense backshift, and give your own evaluative conclusion.','',NULL,'Johnson et al. (2019) claimed that excessive screen time impaired children''s attention spans... However, Lee (2021) argued that interactive educational content enhanced vocabulary acquisition... Johnson acknowledged that their study had focused solely on passive viewing... Lee noted that the type of content mattered more than total time... Both studies suggested that parental guidance was essential... In my view, the evidence indicates that screen time itself is not inherently harmful...','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
