-- ============================================================
-- SEED: Módulo 16 — Advanced Articles (B2)
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'articles-advanced';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo articles-advanced não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 1: A/An vs The – First vs Second Mention
  (cid,1,1,'gap_fill','A scientist discovered _____ new comet last year. _____ comet has now been named after her.','a / The',NULL,'First mention: "a new comet" (indefinite). Second mention: "The comet" (now specific, known to listener).','easy'),
  (cid,1,2,'multiple_choice','She bought _____ laptop yesterday. _____ laptop has a 12-hour battery life.','a / The','["the / The","a / A","a / The","an / The"]','First mention uses "a" (indefinite); second mention uses "the" (definite — now known).','easy'),
  (cid,1,3,'gap_fill','There is _____ error in _____ report you submitted.','an / the',NULL,'"An error" = indefinite, first mention; "the report" = specific report already known to both parties.','easy'),
  (cid,1,4,'multiple_choice','We need to hire _____ engineer for the project. _____ engineer must have experience in renewable energy.','an / The','["a / The","an / The","the / The","an / An"]','First mention: "an engineer" (any engineer). Second: "The engineer" (the specific one to be hired).','medium'),
  (cid,1,5,'gap_fill','I watched _____ documentary about marine biology. _____ documentary argued that ocean temperatures are rising.','a / The',NULL,'First mention = "a documentary" (unspecified). Second mention = "The documentary" (now identified).','easy'),
  (cid,1,6,'multiple_choice','He submitted _____ proposal to the committee. _____ committee rejected it without explanation.','a / The','["a / The","the / The","a / A","an / The"]','"a proposal" = first mention (one of many possible). "The committee" = already known, specific body.','medium'),
  (cid,1,7,'gap_fill','She has _____ dog and _____ cat. _____ dog is older than _____ cat.','a / a / The / the',NULL,'First mentions use "a/a." Second mentions use "The/the" because both animals are now identified.','medium'),
  (cid,1,8,'multiple_choice','_____ paper was published in _____ prestigious journal. _____ journal has been in print since 1952.','The / a / The','["A / a / The","The / a / The","The / the / The","A / the / A"]','"The paper" = specific one being discussed. "a prestigious journal" = first mention. "The journal" = now identified.','hard'),

  -- BLOCK 2: The with Unique Things (sun, president, etc.)
  (cid,2,9,'gap_fill','_____ sun rises in the east and sets in the west.','The',NULL,'There is only one sun. Unique nouns use "the." → The sun.','easy'),
  (cid,2,10,'multiple_choice','_____ president addressed the nation in a televised speech last night.','The','["A","An","The","Ø"]','There is one president (specific, unique position). → The president.','easy'),
  (cid,2,11,'gap_fill','Scientists are studying _____ atmosphere to understand climate change better.','the',NULL,'"The atmosphere" refers to the unique atmosphere of Earth. → the atmosphere.','easy'),
  (cid,2,12,'multiple_choice','_____ Internet has transformed the way people access information.','The','["A","An","The","Ø"]','"The Internet" is a unique, specific network. → The Internet.','easy'),
  (cid,2,13,'gap_fill','_____ equator divides Earth into the Northern and Southern Hemispheres.','The',NULL,'The equator is a unique geographical feature. → The equator.','medium'),
  (cid,2,14,'multiple_choice','She was elected _____ first female prime minister of her country.','the','["a","an","the","Ø"]','Superlative + ordinal constructions use "the." → the first female prime minister.','medium'),
  (cid,2,15,'gap_fill','Astronomers discovered that _____ Milky Way contains billions of stars.','the',NULL,'Galaxy names with "Milky Way" use "the." → the Milky Way.','medium'),
  (cid,2,16,'multiple_choice','_____ Vatican is the world''s smallest country by area.','The','["A","An","The","Ø"]','Countries that are unique institutions or contain a common noun use "the." → The Vatican.','hard'),

  -- BLOCK 3: No Article with Abstract Nouns in General
  (cid,3,17,'gap_fill','_____ knowledge is power. (general statement about knowledge as a concept)','Ø (no article)',NULL,'Abstract nouns used in a general sense take no article. → Knowledge is power.','easy'),
  (cid,3,18,'multiple_choice','_____ education is essential for economic development in developing nations.','Ø','["The","A","An","Ø"]','When "education" is used in a general, abstract sense, no article is used. → Education is essential...','easy'),
  (cid,3,19,'gap_fill','Researchers believe that _____ poverty is linked to poor health outcomes.','Ø (no article)',NULL,'"Poverty" used as a general abstract concept takes no article. → poverty is linked to...','medium'),
  (cid,3,20,'multiple_choice','_____ love is often described as the most powerful human emotion.','Ø','["The","A","An","Ø"]','"Love" in a general, abstract sense → no article. Compare: "The love she felt was overwhelming" (specific).','medium'),
  (cid,3,21,'gap_fill','In academic writing, _____ language must be precise and formal.','Ø (no article)',NULL,'General reference to "language" as a concept → no article needed.','medium'),
  (cid,3,22,'multiple_choice','She wrote her dissertation on _____ social inequality in urban environments.','Ø','["the","a","an","Ø"]','"Social inequality" used as a general concept → no article.','medium'),
  (cid,3,23,'gap_fill','_____ music has been shown to reduce stress and anxiety levels.','Ø (no article)',NULL,'"Music" as a general concept → no article. Compare: "The music at the concert was loud" (specific).','easy'),
  (cid,3,24,'multiple_choice','_____ patience is required when learning a new language.','Ø','["The","A","An","Ø"]','Abstract noun in general sense → no article. → Patience is required...','easy'),

  -- BLOCK 4: The with Superlatives & No Article with Proper Nouns
  (cid,4,25,'gap_fill','Mount Everest is _____ highest mountain in the world.','the',NULL,'Superlatives always take "the." → the highest mountain.','easy'),
  (cid,4,26,'multiple_choice','_____ Amazon River is _____ largest river by water discharge.','The / the','["The / a","A / the","The / the","Ø / the"]','River names with "River" use "the." Superlative → "the largest."','medium'),
  (cid,4,27,'gap_fill','She attended _____ Harvard University and then worked at _____ United Nations.','Ø / the',NULL,'"Harvard University" = proper noun, no article. "The United Nations" = uses "the" (plural/institutional name).','hard'),
  (cid,4,28,'multiple_choice','We visited _____ Louvre Museum during our trip to _____ Paris.','the / Ø','["a / Ø","the / Ø","Ø / the","the / the"]','"The Louvre Museum" = specific institution. "Paris" = city, no article.','medium'),
  (cid,4,29,'gap_fill','_____ Amazon (the company) was founded by Jeff Bezos in 1994.','Ø (no article)',NULL,'Company name used alone as a proper noun does not require "the." → Amazon was founded...','hard'),
  (cid,4,30,'multiple_choice','She is _____ best student in her class and hopes to attend _____ MIT.','the / Ø','["a / the","the / Ø","the / a","a / Ø"]','Superlative → "the best." MIT (proper noun, acronym without "university" in name) → no article.','hard'),
  (cid,4,31,'gap_fill','_____ Great Wall of China is one of _____ most visited historical landmarks.','The / the',NULL,'"The Great Wall" = unique proper noun with common noun "Wall." "The most visited" = superlative.','medium'),
  (cid,4,32,'multiple_choice','He studied at _____ Oxford and later taught at _____ University of Cambridge.','Ø / the','["the / the","Ø / the","the / Ø","Ø / Ø"]','"Oxford" as an institution → no article. "The University of Cambridge" = "University of" construction → "the."','hard'),

  -- BLOCK 5: TOEFL Academic – A/An with Jobs & The in Academic Writing
  (cid,5,33,'gap_fill','[TOEFL Reading] She works as _____ engineer at a renewable energy company.','an',NULL,'Jobs/roles after "as" or "become" use "a/an." → an engineer.','easy'),
  (cid,5,34,'multiple_choice','[TOEFL Reading] He became _____ professor after completing his doctorate at Stanford.','a','["a","an","the","Ø"]','Jobs and titles after "become" use "a/an." → a professor.','easy'),
  (cid,5,35,'gap_fill','[TOEFL Reading] _____ relationship between diet and cognitive function has been the subject of numerous studies.','The',NULL,'"The relationship between X and Y" = specific relationship being discussed → "the."','medium'),
  (cid,5,36,'multiple_choice','[TOEFL Reading] _____ findings suggest that regular exercise reduces the risk of cardiovascular disease.','The','["A","An","The","Ø"]','Specific findings from the study being discussed → "The findings."','medium'),
  (cid,5,37,'gap_fill','[TOEFL Listening] _____ professor mentioned in the lecture is _____ expert in behavioral economics.','The / an',NULL,'"The professor" = specific one mentioned. "An expert" = first mention, indefinite.','medium'),
  (cid,5,38,'multiple_choice','[TOEFL Reading] _____ data collected during _____ experiment were analyzed using SPSS software.','The / the','["A / a","The / the","The / a","Ø / the"]','Both refer to specific, identified items → "The data," "the experiment."','medium'),
  (cid,5,39,'gap_fill','[TOEFL Reading] She was appointed _____ director of the research institute.','Ø (no article)',NULL,'When "appointed + title" is used without modification, no article is needed. → appointed director.','hard'),
  (cid,5,40,'multiple_choice','[TOEFL Listening] _____ theory proposed by Darwin transformed _____ biology as _____ science.','The / Ø / a','["The / Ø / a","A / the / a","The / the / the","Ø / the / a"]','"The theory" = specific. "Biology" = field in general → no article. "A science" = classifying biology as a type.','hard'),

  -- BLOCK 6: TOEFL Academic – Common Mistakes
  (cid,6,41,'multiple_choice','[TOEFL Reading] Which sentence uses articles correctly?','The researchers concluded that the evidence supports their hypothesis.','["The researchers concluded that an evidence supports their hypothesis.","A researchers concluded that the evidence supports their hypothesis.","The researchers concluded that the evidence supports their hypothesis.","The researchers concluded that a evidence supports their hypothesis."]','"Evidence" is uncountable → no "an evidence." "The evidence" = specific evidence from this study.','medium'),
  (cid,6,42,'gap_fill','[TOEFL Reading] _____ information provided in _____ appendix contradicts _____ main argument.','The / the / the',NULL,'All three refer to specific, identified elements → all use "the."','medium'),
  (cid,6,43,'multiple_choice','[TOEFL Reading] _____ deforestation in _____ Amazon has accelerated in recent decades.','Ø / the','["The / the","Ø / the","A / the","Ø / Ø"]','"Deforestation" as a general abstract process → no article. "The Amazon" = specific geographical region.','hard'),
  (cid,6,44,'gap_fill','[TOEFL Reading] _____ aim of _____ study was to examine _____ effects of sleep deprivation on memory.','The / the / the',NULL,'All refer to specific aspects of a particular study → "The aim," "the study," "the effects."','medium'),
  (cid,6,45,'multiple_choice','[TOEFL Listening] The professor argued that _____ technology cannot replace _____ human judgment.','Ø / Ø','["the / the","a / a","Ø / Ø","the / Ø"]','Both "technology" and "human judgment" used in a general sense → no articles.','hard'),
  (cid,6,46,'gap_fill','[TOEFL Reading] _____ results of _____ experiment were published in _____ Nature.','The / the / Ø',NULL,'"The results" and "the experiment" are specific. "Nature" (journal proper noun) → no article.','hard'),
  (cid,6,47,'multiple_choice','[TOEFL Reading] He is considered _____ leading authority on _____ urban planning.','a / Ø','["the / the","a / Ø","an / Ø","the / Ø"]','"A leading authority" = one of several authorities (indefinite). "Urban planning" = general field → no article.','hard'),
  (cid,6,48,'gap_fill','[TOEFL Listening] _____ paper that _____ student submitted last week was _____ best in _____ class.','The / the / the / the',NULL,'All elements are specific and identified → all require "the."','medium'),

  -- BLOCK 7: TOEFL Academic – Advanced Error Identification
  (cid,7,49,'multiple_choice','[TOEFL Reading] Which option correctly completes the sentence? "_____ ancient Rome was _____ center of _____ vast empire."','Ø / the / a','["The / a / the","Ø / the / a","A / the / a","Ø / a / the"]','"Ancient Rome" = proper noun → no article. "The center" = unique position. "A vast empire" = first mention.','hard'),
  (cid,7,50,'multiple_choice','[TOEFL Reading] Identify the correct sentence.','A rising sea level is a major concern for coastal communities.','["The rising sea level is a major concern for a coastal community.","A rising sea level is a major concern for coastal communities.","Rising sea level is a major concern for the coastal communities.","A rising sea levels are a major concern for coastal communities."]','"A rising sea level" = general phenomenon (countable, singular). "Coastal communities" = general → no article.','hard'),
  (cid,7,51,'gap_fill','[TOEFL Reading] _____ United States has _____ highest rate of carbon emissions per capita among major economies.','The / the',NULL,'"The United States" = country with "the." "The highest" = superlative → "the."','medium'),
  (cid,7,52,'multiple_choice','[TOEFL Listening] "She wrote _____ article about _____ history of medicine." Which is correct?','an / the','["a / the","an / the","an / a","a / Ø"]','"An article" = first mention, indefinite. "The history of medicine" = specific, well-defined topic.','medium'),
  (cid,7,53,'gap_fill','[TOEFL Reading] _____ economic growth can be measured by _____ GDP, which stands for Gross Domestic Product.','Ø / Ø (no article for either)',NULL,'"Economic growth" = abstract concept in general. "GDP" = abbreviation for a proper concept → no article.','hard'),
  (cid,7,54,'multiple_choice','[TOEFL Reading] Which sentence is correct?','The committee reached a consensus after three hours of debate.','["A committee reached the consensus after three hours of debate.","The committee reached a consensus after three hours of debate.","Committee reached a consensus after three hours of debate.","The committee reached the consensus after three hours of debate."]','"The committee" = specific committee being discussed. "A consensus" = one agreement (first mention).','medium'),
  (cid,7,55,'gap_fill','[TOEFL Listening] _____ most important factor in academic success is _____ ability to manage time effectively.','The / the',NULL,'"The most important" = superlative → "the." "The ability" = specific ability being identified.','medium'),
  (cid,7,56,'multiple_choice','[TOEFL Reading] "_____ introduction of _____ new technologies has changed _____ way we communicate."','The / Ø / the','["A / the / a","The / Ø / the","The / a / the","Ø / Ø / the"]','"The introduction of" = specific event. "New technologies" = general class → no article. "The way" = unique way.','hard'),

  -- BLOCK 8: TOEFL Academic – Integrated Article Practice
  (cid,8,57,'gap_fill','[TOEFL Reading] _____ study examined _____ link between _____ air pollution and _____ respiratory disease.','The / the / Ø / Ø',NULL,'"The study" = specific. "The link" = specific relationship. "Air pollution/respiratory disease" = general concepts.','hard'),
  (cid,8,58,'multiple_choice','[TOEFL Reading] "According to _____ author, _____ main cause of _____ poverty is _____ lack of access to education."','the / the / Ø / a','["the / the / Ø / a","a / the / the / a","the / a / Ø / the","the / the / the / the"]','"the author" = identified. "the main cause" = specific. "poverty" = abstract general. "a lack" = indefinite noun phrase.','hard'),
  (cid,8,59,'gap_fill','[TOEFL Listening] _____ second experiment yielded _____ unexpected result: _____ temperature affected _____ reaction rate.','The / an / Ø / the',NULL,'"The second" = ordinal. "An unexpected result" = first mention. "Temperature" = general factor. "The reaction rate" = specific.','hard'),
  (cid,8,60,'multiple_choice','[TOEFL Reading] "_____ researchers from _____ MIT published _____ paper in _____ journal Science."','Ø / Ø / a / Ø','["The / the / a / the","Ø / Ø / a / Ø","The / Ø / a / Ø","Ø / the / a / the"]','"Researchers" = general group. "MIT" = proper noun. "A paper" = first mention. "Science" (journal) = proper noun.','hard'),
  (cid,8,61,'gap_fill','[TOEFL Reading] _____ findings suggest that _____ biodiversity loss is occurring at _____ unprecedented rate.','The / Ø / an',NULL,'"The findings" = specific. "Biodiversity loss" = general phenomenon. "An unprecedented rate" = indefinite first mention.','hard'),
  (cid,8,62,'multiple_choice','[TOEFL Reading] "She is _____ most influential scholar in _____ field of _____ computational linguistics."','the / the / Ø','["a / the / Ø","the / the / Ø","the / a / Ø","the / the / the"]','"The most influential" = superlative. "The field of" = specific field. "Computational linguistics" = proper field name → no article.','hard'),
  (cid,8,63,'gap_fill','[TOEFL Listening] _____ government announced that _____ new policy would take effect at _____ beginning of next year.','The / a / the',NULL,'"The government" = specific. "A new policy" = first mention. "The beginning of" = specific point in time.','medium'),
  (cid,8,64,'multiple_choice','[TOEFL Reading] "_____ research suggests that _____ moderate exercise can improve _____ mental health."','Ø / Ø / Ø','["The / the / Ø","Ø / Ø / Ø","The / Ø / the","A / a / Ø"]','All three used in general sense: "Research" = uncountable abstract. "Moderate exercise" = general. "Mental health" = general.','hard'),

  -- BLOCK 9: TOEFL Speaking Tasks
  (cid,9,65,'production','[TOEFL Speaking — 45s] A university is planning to build either a new library or a new sports center on campus. Which do you think would benefit students more? Give specific reasons to support your choice. You have 45 seconds to respond.','',NULL,'Practice using articles correctly: "A new library would provide..." "The sports center could help..." "Students need access to the resources..."','medium'),
  (cid,9,66,'production','[TOEFL Speaking — 45s] Some people believe that the Internet has made education more accessible. Others feel it has created new inequalities. What is your opinion? Support your answer with specific examples. You have 45 seconds to respond.','',NULL,'Focus on article use: "The Internet has..." "A student without access to..." "The gap between..."','medium'),
  (cid,9,67,'production','[TOEFL Speaking — 45s] Describe a technological innovation that has significantly changed the way people live. Explain how it changed daily life and whether the changes have been mostly positive or negative. You have 45 seconds.','',NULL,'Use: "The smartphone..." "A major change..." "The way people communicate..." Focus on article accuracy.','hard'),

  -- BLOCK 10: TOEFL Writing Tasks
  (cid,10,68,'production','[TOEFL Writing] The use of social media has transformed communication in the modern world. Discuss the advantages and disadvantages of social media use. Do the benefits outweigh the drawbacks? Support your argument with specific reasons and examples. Write at least 150 words.','',NULL,'Article focus: "The use of social media..." "A major advantage is..." "The disadvantages include..." "The way people interact..."','hard'),
  (cid,10,69,'production','[TOEFL Writing] Some people argue that a university education is essential for success in today''s economy. Others believe that practical skills and experience are more valuable than a degree. Discuss both views and give your own opinion. Write at least 150 words.','',NULL,'Article focus: "A university education..." "The value of practical experience..." "The economy requires..."','hard'),
  (cid,10,70,'production','[TOEFL Writing] Environmental protection and economic development are often seen as competing priorities. Do you think it is possible for a country to achieve both simultaneously? Use specific reasons and examples to support your position. Write at least 150 words.','',NULL,'Article focus: "The environment..." "A country that prioritizes..." "The balance between economic growth and environmental protection..." "A sustainable approach..."','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
