-- ============================================================
-- SEED EXT 3: Módulo 11 — Relative Clauses (ex 121-215)
-- Novos tópicos: whom formal, preposition+which avançado,
-- múltiplas cláusulas, discriminação avançada, TOEFL
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'relative-clauses';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo relative-clauses não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 31: whom — pronome formal de objeto
  (cid,31,121,'gap_fill','The researcher _____ (whom) the committee selected was highly qualified.','whom',NULL,'"Whom" = object relative pronoun (formal). The committee selected her.','hard'),
  (cid,31,122,'multiple_choice','Which sentence uses "whom" correctly?','The candidate whom we interviewed most recently has been offered the position.','["The candidate who we interviewed most recently has been offered the position (informal — also acceptable).","The candidate whom we interviewed most recently has been offered the position.","The candidate whom interviewed us most recently has been offered the position.","The candidate that we interviewed most recently (acceptable informal)."]','"Whom" = object relative (we interviewed whom). Formal written English.','hard'),
  (cid,31,123,'gap_fill','The professor _____ (who/whom) I studied under for three years later became my doctoral supervisor.','whom / who',NULL,'"Whom" is formal correct (object of ''studied under''). "Who" is informal but acceptable.','hard'),
  (cid,31,124,'multiple_choice','In formal academic writing, when is "whom" required?','When it is the object of the verb in the relative clause.','["Always with people","Only after prepositions","When it is the object of the verb in the relative clause.","Only in non-defining clauses"]','"Whom" = object function: "the person whom they criticized" (they criticized whom).','hard'),
  (cid,31,125,'gap_fill','To _____ (who/whom) it may concern — this is the formal opening of an official complaint letter.','whom',NULL,'"To whom it may concern" = fixed formal phrase. Whom = object of concerns.','medium'),

  -- BLOCK 32: preposition + which/whom — avançado
  (cid,32,126,'gap_fill','The conditions _____ (under which) the experiment was conducted must be precisely replicated.','under which',NULL,'"Under which" = preposition + relative pronoun for defining clause about conditions.','hard'),
  (cid,32,127,'multiple_choice','Which formal sentence uses preposition + relative pronoun correctly?','The framework within which the analysis was conducted draws on three theoretical traditions.','["The framework which within the analysis was conducted draws on three traditions.","The framework within that the analysis was conducted draws on three traditions.","The framework within which the analysis was conducted draws on three theoretical traditions.","The framework which the analysis was conducted within (informal — acceptable)."]','Preposition + which = formal: within which, for which, by which, in which.','hard'),
  (cid,32,128,'gap_fill','The professor _____ (with whom) I co-authored this paper is internationally recognized in the field.','with whom',NULL,'"With whom" = formal preposition + object relative pronoun.','hard'),
  (cid,32,129,'multiple_choice','Rank from most to least formal: (A) "the method that we used," (B) "the method we used," (C) "the method which we used," (D) "the method by which we obtained the results."','D > C > A > B.','["A > B > C > D","D > C > A > B.","B > A > C > D","C > D > A > B"]','Preposition + which = most formal. Zero pronoun = least formal.','hard'),
  (cid,32,130,'gap_fill','The mechanism _____ (by which) cells communicate has been the focus of decades of research.','by which',NULL,'"By which" = mechanism of action; formal relative clause.','hard'),

  -- BLOCK 33: relative clauses com where/when/why
  (cid,33,131,'gap_fill','The period _____ (when/in which) the study was conducted saw unprecedented political instability.','when / during which',NULL,'"When" or "during which" = temporal relative clause.','medium'),
  (cid,33,132,'multiple_choice','Which sentence correctly uses "where" in a relative clause?','The laboratory where the breakthrough was made has since been converted into a museum.','["The laboratory when the breakthrough was made has since been converted.","The laboratory which the breakthrough was made in has since been converted (informal — also correct).","The laboratory where the breakthrough was made has since been converted into a museum.","The laboratory that the breakthrough was made has since been converted."]','"Where" = place relative pronoun in defining clause.','medium'),
  (cid,33,133,'gap_fill','This is the reason _____ (why/for which) the team decided to abandon the original methodology.','why / for which',NULL,'"Why" or "for which" = reason relative clause.','medium'),
  (cid,33,134,'multiple_choice','Which sentence uses "when" as a relative pronoun correctly?','The 1990s, when globalization accelerated most rapidly, saw significant economic restructuring.','["The 1990s, which globalization accelerated most rapidly, saw significant restructuring.","The 1990s, where globalization accelerated most rapidly, saw significant restructuring.","The 1990s, when globalization accelerated most rapidly, saw significant economic restructuring.","The 1990s, that globalization accelerated most rapidly, saw significant restructuring."]','"When" = temporal relative pronoun after decade/year/period.','medium'),

  -- BLOCK 34: múltiplas cláusulas relativas
  (cid,34,135,'multiple_choice','Which sentence correctly uses two relative clauses?','The researcher who developed the model and whose findings have since been widely cited will receive an honorary degree.','["The researcher who developed the model and who''s findings have since been cited will receive an honorary degree.","The researcher who developed the model and whose findings have since been widely cited will receive an honorary degree.","The researcher that developed the model, that findings have been cited, will receive an honorary degree.","The researcher, who developed the model, and whose findings have been cited will receive a degree."]','"Who" (subject) + "whose findings" (possessive) = two different relative pronouns for the same head noun.','hard'),
  (cid,34,136,'gap_fill','The study, which was conducted by a team that included specialists from five countries, produced results that surprised even its authors.','which / that / that',NULL,'Three relative clauses: non-defining (which) + defining (that) + defining (that).','hard'),
  (cid,34,137,'multiple_choice','Which sentence INCORRECTLY combines two relative clauses?','The paper which received the award, that was written by three graduate students, has been cited 500 times.','["The paper which received the award and which was written by three graduate students has been cited 500 times.","The paper that received the award, written by three graduate students, has been cited 500 times.","The paper which received the award, that was written by three graduate students, has been cited 500 times.","The prize-winning paper, which was written by three graduate students, has been cited 500 times."]','"That" cannot be used in a non-defining relative clause (after comma).','hard'),

  -- BLOCK 35: TOEFL Reading
  (cid,35,138,'multiple_choice','[TOEFL Reading] "The process by which the brain consolidates long-term memories during sleep has been a central focus of neuroscience for decades." The phrase "by which" is used because:','It creates a formal defining relative clause modifying "process."','["By which is always used with brain","It creates a formal defining relative clause modifying ''process.''","By which is a fixed expression for sleep","The passive requires by which"]','"By which" = formal preposition + relative pronoun. "The process by which X happens."','medium'),
  (cid,35,139,'gap_fill','[TOEFL Reading] "The scientists _____ (whom) the committee awarded the prize had conducted their research over fifteen years." Best form?','whom',NULL,'"Whom" = object relative pronoun. The committee awarded the prize to whom.','hard'),
  (cid,35,140,'multiple_choice','[TOEFL Reading] In "Species that are highly specialized for a particular ecological niche are often the most vulnerable to habitat loss," removing "that are" creates:','A reduced relative clause: "Species highly specialized for a particular niche are often..."','["An error","A passive construction","A reduced relative clause: ''Species highly specialized for a particular niche are often...''","An absolute phrase"]','Reduced relative: "species highly specialized" = "species that are highly specialized."','medium'),
  (cid,35,141,'gap_fill','[TOEFL Reading] "The era _____ (during which) these technologies emerged was marked by unprecedented social change." Best form?','during which',NULL,'"During which" = temporal preposition + relative pronoun for a period.','hard'),

  -- BLOCK 36: TOEFL Speaking
  (cid,36,142,'production','[TOEFL Speaking — 45s] Describe an important scientific discovery using: who (subject), whom (object, formal), whose (possessive), by which (formal), and a reduced relative clause.','',NULL,'Marie Curie, who discovered both polonium and radium, remains one of the most celebrated scientists of all time. The process by which she isolated radioactive elements — grinding and refining tons of pitchblende — required years of exhausting labor. Curie, whose work fundamentally changed physics and chemistry, was the first person to win two Nobel Prizes in different sciences. The mechanisms she identified, later refined by physicists whom she inspired, laid the groundwork for modern nuclear medicine and radiation therapy.','hard'),
  (cid,36,143,'production','[TOEFL Speaking — 45s] Discuss the role of universities in society. Use at least 4 relative clauses: defining (that/which), non-defining (who/which), preposition+which, and reduced (-ing or past participle).','',NULL,'Universities are institutions that play a critical role in advancing knowledge and training the professionals on whom modern societies depend. Research conducted at universities — funded by grants that governments and private foundations award competitively — has produced many of the technologies that define contemporary life. Scholars whose work crosses disciplinary boundaries often make the most transformative contributions. The environment in which this research takes place needs to be protected from short-term commercial pressures, ensuring that basic science, which may have no immediately obvious application, continues to be valued.','hard'),

  -- BLOCK 37: TOEFL Writing
  (cid,37,144,'production','[TOEFL Writing — 150 words] Write an academic paragraph on biodiversity loss using at least 5 relative clauses across different types: that/which (defining), who/which (non-defining), whose, by which, reduced -ing, reduced past participle.','',NULL,'Biodiversity, which encompasses the variety of life across all ecosystems, is declining at a rate that scientists describe as the sixth mass extinction. Species that occupy narrow ecological niches are particularly vulnerable, as their survival depends on habitats that are being destroyed by deforestation, pollution, and climate change. Researchers studying the functional roles of threatened species have found that even organisms considered economically insignificant may serve critical roles in maintaining ecosystem stability. The mechanisms by which species interact within food webs are complex, and the loss of a single keystone species can trigger cascading effects across entire ecosystems. Conservation biologists, whose warnings have been largely unheeded by policymakers, emphasize that the window for meaningful action is narrowing. Internationally protected areas, carefully managed by local communities working in partnership with governments, represent the most effective tool for preserving biodiversity at scale.','hard'),
  (cid,37,145,'production','[TOEFL Writing — Error Correction] Fix relative clause errors: "The scientist who discovered she the vaccine is famous. The theory which it changed physics was proposed in 1905. The professor, that I respect most, has retired. She is the person which I contacted. The conditions which under the test was conducted are important."','',NULL,'who discovered she the vaccine → who discovered the vaccine (remove ''she'' — pronoun repetition); which it changed → which changed (remove ''it'' — pronoun repetition); that I respect → whom I respect (formal) or who I respect (informal), NOT that in non-defining; which I contacted → whom I contacted (object of contacted — formal) or who/that (informal, defining); which under → under which (preposition before relative pronoun in formal style).','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
