-- ============================================================
-- SEED EXT 2: Módulo 22 — Subjunctive (exercícios 71-165)
-- Novos tópicos: verbos mandativos menos comuns, lest + subj,
-- passive subjunctive, as if/as though + were, TOEFL
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'subjunctive';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo subjunctive não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 11: verbos mandativos menos comuns
  (cid,11,71,'gap_fill','The committee proposed that the budget _____ (allocate) equally across all departments.','be allocated',NULL,'"Propose + that + subject + base verb (subjunctive)" — no third-person -s, no auxiliary.','hard'),
  (cid,11,72,'multiple_choice','Which sentence uses a mandative subjunctive correctly after "stipulate"?','The contract stipulates that the work be completed within 30 days.','["The contract stipulates that the work is completed within 30 days.","The contract stipulates that the work be completed within 30 days.","The contract stipulates that the work was completed within 30 days.","The contract stipulates that the work should be completed within 30 days (also correct but not subjunctive)."]','"Stipulate + that + subject + base verb (subjunctive)." "Be completed" = passive subjunctive.','hard'),
  (cid,11,73,'gap_fill','The judge ordered that the evidence _____ (re-examine/passive) by an independent forensic team.','be re-examined',NULL,'"Order + that + passive subjunctive" = that + subject + be + past participle.','hard'),
  (cid,11,74,'multiple_choice','Which mandative verb does NOT typically take a subjunctive that-clause?','Believe','["Recommend","Propose","Stipulate","Believe"]','"Believe" = cognitive verb (not mandative). Recommend/propose/stipulate/require/demand = mandative.','hard'),
  (cid,11,75,'gap_fill','The board moved that the chairman _____ (resign) with immediate effect.','resign',NULL,'"Move + that + subjunctive" (formal meeting language). No "should" — bare base verb.','hard'),
  (cid,11,76,'multiple_choice','Formal meeting → subjunctive: "Someone proposed that voting be deferred to the next meeting." Is this correct?','Yes — proposed + that + subject + base verb (subjunctive passive).','["No — should be deferred is correct","No — the proposed is wrong","Yes — proposed + that + subject + base verb (subjunctive passive).","No — deferring is needed"]','"Voting be deferred" = mandative subjunctive passive. Correct.','hard'),
  (cid,11,77,'gap_fill','It was decreed that no citizen _____ (bear) arms within the city limits.','bear',NULL,'"Decree + that + subjunctive." "Bear" = base verb without -s.','hard'),

  -- BLOCK 12: passive subjunctive (that it be done)
  (cid,12,78,'gap_fill','The committee recommended that all data _____ (archive/passive) for a minimum of ten years.','be archived',NULL,'"Recommend + that + passive subjunctive" = that + subject + be + past participle.','hard'),
  (cid,12,79,'multiple_choice','Which sentence uses a passive mandative subjunctive correctly?','The protocol requires that participants be informed of their right to withdraw at any stage.','["The protocol requires that participants are informed.","The protocol requires that participants were informed.","The protocol requires that participants be informed of their right to withdraw at any stage.","The protocol requires that participants being informed."]','"Requires + that + subject + be + past participle (passive subjunctive)."','hard'),
  (cid,12,80,'gap_fill','The judge ruled that the defendant _____ (release/passive) on bail pending appeal.','be released',NULL,'"Ruled + that + passive subjunctive" — base form "be" + past participle.','hard'),
  (cid,12,81,'multiple_choice','Transform: "The manager insisted on reviewing all proposals." → passive mandative subjunctive.','The manager insisted that all proposals be reviewed before a decision was made.','["The manager insisted that all proposals are reviewed.","The manager insisted that all proposals were reviewed.","The manager insisted that all proposals be reviewed before a decision was made.","The manager insisted on all proposals being reviewed (gerund — also correct, not subjunctive)."]','"Insisted + that + passive subjunctive" = formal written English.','hard'),
  (cid,12,82,'gap_fill','The ethics board stipulated that all experiments _____ (approve/passive) in writing before commencement.','be approved',NULL,'"Stipulate + that + passive subjunctive." "Be approved" = base form.','hard'),
  (cid,12,83,'multiple_choice','In formal legal or academic writing, why is passive subjunctive preferred over active?','It removes focus from specific agents and emphasizes the process or requirement.','["It is shorter","It removes focus from specific agents and emphasizes the process or requirement.","It is grammatically simpler","It is required in all written English contexts"]','Passive subjunctive = impersonal + process-focused = formal academic/legal register.','hard'),
  (cid,12,84,'gap_fill','The resolution stated that the decision _____ (implement/passive) within 90 days.','be implemented',NULL,'"Stated + that + passive subjunctive." — that + subject + be + past participle.','hard'),

  -- BLOCK 13: lest + subjunctive
  (cid,13,85,'gap_fill','She rehearsed her presentation thoroughly, lest she _____ (forget) her key points under pressure.','forget',NULL,'"Lest + subject + subjunctive (bare base verb)" = formal expression of fear/precaution.','hard'),
  (cid,13,86,'multiple_choice','Which sentence uses "lest" correctly?','The treaty was carefully worded, lest any clause be misinterpreted by signatory nations.','["The treaty was carefully worded, lest any clause is misinterpreted.","The treaty was carefully worded, lest any clause was misinterpreted.","The treaty was carefully worded, lest any clause be misinterpreted by signatory nations.","The treaty was carefully worded, lest any clause would be misinterpreted."]','"Lest + subject + subjunctive (be misinterpreted)" = correct formal usage.','hard'),
  (cid,13,87,'gap_fill','He spoke quietly during the ceremony, lest he _____ (disturb) the other attendees.','disturb',NULL,'"Lest + base verb (subjunctive)" — no auxiliary, no -s.','hard'),
  (cid,13,88,'multiple_choice','What is the meaning of "lest" in: "She checked her figures twice, lest the report contain errors."?','In order to prevent the possibility that the report would contain errors.','["Because the report contained errors","In order to prevent the possibility that the report would contain errors.","Unless the report contained errors","Although the report might contain errors"]','"Lest" = for fear that / to prevent. Introduces a negative purpose/risk.','hard'),
  (cid,13,89,'gap_fill','Researchers must document every procedural step meticulously, lest the study _____ (be/irreproducible).','be irreproducible / be deemed irreproducible',NULL,'"Lest + subjunctive" for a formal risk statement.','hard'),
  (cid,13,90,'multiple_choice','Which is the modern equivalent of "lest he forget"?','In case he forgets / so that he doesn''t forget.','["Before he forgets","Because he might forget","In case he forgets / so that he doesn''t forget.","Unless he forgets"]','"Lest + subjunctive" = archaic/formal. Modern equivalent: "in case" or "so that...not."','medium'),

  -- BLOCK 14: as if / as though + were + subjunctive
  (cid,14,91,'gap_fill','The CEO spoke as if the acquisition _____ (be) already confirmed, though negotiations were ongoing.','were',NULL,'"As if + subject + were" = subjunctive (irreal/hypothetical comparison in present).','hard'),
  (cid,14,92,'multiple_choice','Which sentence correctly uses the subjunctive after "as though"?','She described the experiment as though it were a personal discovery, not a team effort.','["She described the experiment as though it was a personal discovery (informal/acceptable).","She described the experiment as though it were a personal discovery, not a team effort.","She described the experiment as though it is a personal discovery.","She described the experiment as though it be a personal discovery."]','Formal: "as though + were" = subjunctive for hypothetical/unreal comparison.','hard'),
  (cid,14,93,'gap_fill','He treated the junior researchers as if they _____ (be) beneath him — an attitude that damaged team morale.','were',NULL,'"As if + were" = unreal subjunctive comparison (they are not beneath him).','hard'),
  (cid,14,94,'multiple_choice','What does "as if it were" signal in formal writing?','The comparison is hypothetical or contrary to fact.','["The comparison is real","The writer is uncertain","The comparison is hypothetical or contrary to fact.","The sentence is in the past"]','"As if + were" = irreal/subjunctive mood = comparison does not reflect reality.','medium'),
  (cid,14,95,'gap_fill','The politician spoke as if the economic recovery _____ (be) complete, despite all evidence to the contrary.','were',NULL,'Unreal subjunctive: the recovery is NOT complete — "as if it were" signals the claim is contrary to fact.','hard'),
  (cid,14,96,'multiple_choice','When is "as if it was" (indicative) acceptable vs. "as if it were" (subjunctive)?','Were (subjunctive) = clearly hypothetical; was (indicative) = possibly real, especially in informal English.','["Was is never correct after as if","Were is only for past situations","Were (subjunctive) = clearly hypothetical; was (indicative) = possibly real, especially in informal English.","They are always interchangeable in all contexts"]','The subjunctive (were) signals a clearly counterfactual comparison. Indicative (was) = ambiguous register.','hard'),

  -- BLOCK 15: TOEFL Reading
  (cid,15,97,'multiple_choice','[TOEFL Reading] "The report recommended that all findings be disclosed publicly." The subjunctive "be" is used because:','It follows the mandative verb "recommend" in a that-clause.','["Be is always used after that","It follows the mandative verb ''recommend'' in a that-clause.","Findings is a plural noun","It is a passive construction only"]','"Recommend + that + passive subjunctive": recommend → that → subject + be + past participle.','medium'),
  (cid,15,98,'gap_fill','[TOEFL Reading] "The court ruled that the evidence _____ (suppress/passive) on grounds of illegality." Best form?','be suppressed',NULL,'Mandative passive subjunctive: ruled + that + subject + be + past participle.','hard'),
  (cid,15,99,'multiple_choice','[TOEFL Reading] "She worked as though her life were at stake, refusing to rest until the deadline passed." The subjunctive "were" implies:','The comparison is exaggerated or hypothetical — her life was not literally at stake.','["Her life was literally in danger","She was exhausted","The comparison is exaggerated or hypothetical — her life was not literally at stake.","The subjunctive is required after ''as though'' in all cases"]','"As though + were" = hypothetical/irreal comparison.','medium'),
  (cid,15,100,'gap_fill','[TOEFL Reading] "The regulation stipulates that every financial transaction _____ (record/passive) and _____ (store) for seven years." Best subjunctive forms?','be recorded / stored',NULL,'Passive subjunctive: stipulates + that + subject + be + past participle.','hard'),
  (cid,15,101,'multiple_choice','[TOEFL Reading] "Lest this trend continue unchecked, policymakers must introduce binding international regulations." "Lest" means:','In order to prevent the continuation of the trend.','["Although the trend continues","If the trend continues","In order to prevent the continuation of the trend.","As long as the trend continues"]','"Lest" = for fear that / to prevent + subjunctive.','medium'),

  -- BLOCK 16: TOEFL Speaking
  (cid,16,102,'production','[TOEFL Speaking — 45s] A reading argues that AI companies should be required to disclose their algorithms. Agree or disagree using: recommend + that + subjunctive, it is essential + that + subjunctive, lest, as if.','',NULL,'I strongly agree that AI companies should be required to disclose their algorithms. It is essential that transparency be mandated by international regulatory bodies. Experts have long recommended that algorithmic systems be subject to independent audits, lest they perpetuate bias or discrimination unchecked. Companies currently behave as if their code were proprietary and above public scrutiny, which is untenable given the societal impact of these systems.','hard'),
  (cid,16,103,'production','[TOEFL Speaking — 45s] A committee is deciding whether to ban fast food advertising targeting children. Use mandative subjunctive (propose/recommend), passive subjunctive, and lest.','',NULL,'The committee recommends that all fast food advertising targeting children be banned during peak viewing hours. It has been proposed that advertisers be required to include health warnings in any food-related commercial. This policy must be implemented carefully, lest loopholes allow companies to circumvent the regulations via social media platforms. I propose that an independent monitoring body be established to ensure compliance, as the evidence that such advertising harms children''s health is overwhelming.','hard'),

  -- BLOCK 17: TOEFL Writing
  (cid,17,104,'production','[TOEFL Writing — 150 words] Write an academic paragraph arguing for mandatory environmental impact assessments for all major construction projects. Use: propose + subjunctive, require + passive subjunctive, it is vital + that + subjunctive, lest, as if + were.','',NULL,'Many environmental organizations propose that mandatory impact assessments be conducted before any major construction project receives approval. It is vital that all potential ecological consequences be evaluated thoroughly and independently, not just by the companies seeking permits. Regulatory frameworks should require that full transparency be maintained throughout the review process, with public access to all findings. Lest the construction industry continue to prioritize profit over environmental protection, governments must enforce strict accountability mechanisms. Currently, many developers behave as if environmental regulations were optional guidelines rather than binding legal requirements. The implementation of comprehensive mandatory assessments would not only protect biodiversity but also ensure that infrastructure development is sustainable in the long term, benefiting both the economy and the environment for future generations.','hard'),
  (cid,17,105,'production','[TOEFL Writing — Error Correction] Fix subjunctive errors: "The committee recommended that all evidence is reviewed. The board proposed that the director resigns immediately. Lest the truth comes out, he refused to speak. She spoke as if the decision was already final (formal context)."','',NULL,'is reviewed → be reviewed (mandative passive subjunctive after recommend); resigns → resign (base verb, no -s, in mandative subjunctive); comes → come (lest + base verb subjunctive); was → were (formal as if + subjunctive = were for irreal/hypothetical).','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
