-- ============================================================
-- SEED EXT 4: Módulo 09 — Conditional Type 1 (ex 164-243)
-- Novos tópicos: Type 1 em gêneros formais, future-in-the-past,
-- conditionals com when vs if, zero conditional avançado
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'conditional-1';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo conditional-1 não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 41: when vs if em conditionals
  (cid,41,164,'multiple_choice','What is the key difference between "if" and "when" in future conditionals?','"If" expresses uncertainty (may or may not happen); "when" expresses certainty (it will definitely happen).','["They are identical in future contexts","''If'' expresses uncertainty (may or may not happen); ''when'' expresses certainty (it will definitely happen).","When is more formal than if","If requires will; when does not"]','"If the results are positive, we will publish." (uncertain) vs "When the results come in, we will analyze them." (certain it will happen).','hard'),
  (cid,41,165,'gap_fill','_____ (When) the trial period ends, all participants will receive a full debriefing and their data will be anonymized.','When',NULL,'"When" = certain future event (the trial WILL end). Not "if" (uncertain).','medium'),
  (cid,41,166,'gap_fill','_____ (If) the new policy _____ (introduce/passive) without public consultation, there will be significant backlash.','If / is introduced',NULL,'"If" = uncertain event. Passive present simple in the if-clause.','medium'),
  (cid,41,167,'multiple_choice','Which sentence uses "when" INCORRECTLY (should be "if")?','When the funding application succeeds, we will begin the research immediately.','["When the funding application succeeds, we will begin the research immediately.","When you press Enter, the program will save the file automatically.","When the results come in, we will analyze them.","When she arrives, please let me know."]','"When the application succeeds" = implies certainty of success. Should be "if" — the outcome is uncertain.','hard'),
  (cid,41,168,'gap_fill','_____ (When) you _____ (multiply) a number by zero, you _____ (always/get) zero. (Type 0 with when)','When / multiply / always get',NULL,'"When" in Type 0 = every time (equivalent to "if" for universal truth).','easy'),

  -- BLOCK 42: Type 1 com present continuous / present perfect na if-clause
  (cid,42,169,'gap_fill','If you _____ (still/work) on the assignment when the power _____ (cut), make sure to save regularly.','are still working / is cut',NULL,'Present continuous in if-clause = condition that may be ongoing when something happens.','hard'),
  (cid,42,170,'multiple_choice','Which sentence correctly uses present perfect in a Type 1 if-clause?','If the team has collected all the data by Friday, we will begin analysis next week.','["If the team will have collected all the data by Friday, we will begin analysis.","If the team has collected all the data by Friday, we will begin analysis next week.","If the team had collected all the data by Friday, we will begin analysis.","If the team collects all the data by Friday, we will begin analysis next week (also correct — both acceptable)."]','Present perfect in if-clause = condition that will be complete before the result occurs.','hard'),
  (cid,42,171,'gap_fill','If the medication _____ (not/take/passive) within 48 hours of symptoms appearing, it _____ (be) significantly less effective.','is not taken / will be',NULL,'Passive present simple in Type 1 if-clause.','hard'),
  (cid,42,172,'multiple_choice','What is the effect of using present perfect in the if-clause vs present simple? "If you have finished" vs "If you finish"?','"If you have finished" = after the action is complete. "If you finish" = at the moment of completion.','["They are identical","''If you have finished'' = after the action is complete. ''If you finish'' = at the moment of completion.","Present perfect is wrong in Type 1 if-clauses","Present simple is more formal"]','Present perfect in if-clause = when the action is done (emphasis on completion).','hard'),

  -- BLOCK 43: Type 1 em textos legais/formais/regulatórios
  (cid,43,173,'gap_fill','If a participant _____ (withdraw) from the study, all data _____ (delete/passive) immediately upon request.','withdraws / will be deleted',NULL,'Type 1 in consent forms/legal context: present simple + will + passive.','medium'),
  (cid,43,174,'multiple_choice','Which sentence is MOST appropriate in a contract or legal document?','Should either party fail to meet their obligations, the agreement will be subject to immediate termination.','["If either party fails to meet their obligations, the agreement gets terminated.","Should either party fail to meet their obligations, the agreement will be subject to immediate termination.","If either party will fail to meet their obligations, the agreement will be terminated.","Provided either party fails, the agreement terminates."]','Inverted Type 1 formal + "will be subject to" = formal legal language for conditional obligation.','hard'),
  (cid,43,175,'gap_fill','If the submitted materials _____ (not/meet) the minimum requirements, the application _____ (return/passive) without review.','do not meet / will be returned',NULL,'Formal Type 1 passive result clause.','medium'),
  (cid,43,176,'gap_fill','Unless written consent _____ (obtain/passive) prior to data collection, the research _____ (cannot/proceed).','is obtained / cannot proceed',NULL,'"Unless" + passive present simple + modal negative result.','hard'),
  (cid,43,177,'multiple_choice','Which regulatory sentence uses the MOST formal Type 1 pattern?','Should the inspection reveal non-compliance, the facility will be required to cease operations immediately.','["If the inspection will reveal non-compliance, the facility must cease operations.","If they find non-compliance, the facility stops.","Should the inspection reveal non-compliance, the facility will be required to cease operations immediately.","Unless non-compliance is not found, the facility must stop."]','Inverted Type 1 (Should + base verb) + passive result clause = formal regulatory language.','hard'),

  -- BLOCK 44: futuro no passado (reporting Type 1 conditionals)
  (cid,44,178,'gap_fill','Direct: "If the results are good, we will publish." → Reported: She said that if the results _____ (be) good, they _____ (publish).','were / would publish',NULL,'Reported Type 1 conditional: present → past, will → would.','hard'),
  (cid,44,179,'multiple_choice','Which correctly reports a Type 1 conditional? Direct: "If it rains, the match will be cancelled."','The coach said that if it rained, the match would be cancelled.','["The coach said that if it rains, the match will be cancelled (no backshift — informal/journalistic).","The coach said that if it had rained, the match would have been cancelled (Type 3 — wrong).","The coach said that if it rained, the match would be cancelled.","The coach said that if it rains, the match would be cancelled (mixed — avoid)."]','Type 1 in reported speech: if-clause → past simple, will → would.','hard'),
  (cid,44,180,'gap_fill','Direct: "If you submit by Friday, you will receive priority review." → Reported: The editor told her that if she _____ (submit) by Friday, she _____ (receive) priority review.','submitted / would receive',NULL,'Reported Type 1: present → past simple, will → would.','medium'),
  (cid,44,181,'multiple_choice','In which context does the "future-in-the-past" pattern (would + base verb) appear?','When reporting predictions or conditional promises made in the past.','["In Type 2 conditionals only","In all hypothetical conditionals","When reporting predictions or conditional promises made in the past.","In Type 0 conditionals only"]','"Future-in-the-past" = ''will'' reported in past tense → ''would''.','medium'),

  -- BLOCK 45: TOEFL Reading
  (cid,45,182,'multiple_choice','[TOEFL Reading] "If ocean acidity continues to rise, coral reef ecosystems will lose their ability to calcify and will eventually collapse." This is a Type 1 conditional because:','It presents a real, plausible future scenario with a projected consequence.','["It describes a past event","It expresses a Type 2 hypothetical","It presents a real, plausible future scenario with a projected consequence.","It describes a universal scientific law (Type 0)"]','Type 1: present simple if-clause + will result = real, likely future prediction.','easy'),
  (cid,45,183,'gap_fill','[TOEFL Reading] "If antibiotic resistance _____ (continue) to develop unchecked, routine medical procedures _____ (become) life-threatening within decades." Best forms?','continues / will become / could become',NULL,'Type 1 (or hedged Type 1) for public health projection.','medium'),
  (cid,45,184,'multiple_choice','[TOEFL Reading] "When resources are shared equitably, collective outcomes improve." This is a Type _____ conditional.','Type 0 — states a universal/general pattern using ''when.''','["Type 1","Type 2","Type 0 — states a universal/general pattern using ''when.''","Type 3"]','When + present simple + present simple = Type 0 (universal truth).','easy'),
  (cid,45,185,'gap_fill','[TOEFL Reading] "Should governments fail to act decisively, the window for effective climate intervention _____ (close)." Best result form?','will close / will have closed',NULL,'"Should + base verb" inverted conditional + will + base verb = formal prediction.','hard'),

  -- BLOCK 46: TOEFL Speaking
  (cid,46,186,'production','[TOEFL Speaking — 45s] Give advice about university success using Type 1, when vs if, and implicit conditionals (imperative + and/or). Also use unless and provided that.','',NULL,'University success is largely a product of consistent habits, not natural talent. If you attend every lecture and take detailed notes, you will have a much stronger foundation when examinations arrive. Attend office hours regularly, and your professors will come to know you as a serious student — which may open doors to research opportunities. Unless you prioritize sleep and manage your workload proactively, academic performance will suffer no matter how intelligent you are. Provided that you build strong relationships with both your professors and your peers, you will find the transition to graduate study or professional life considerably smoother. When you receive feedback on your work — whether positive or critical — treat it as an invaluable resource.','hard'),
  (cid,46,187,'production','[TOEFL Speaking — 45s] A reading warns that if global temperatures rise more than 1.5°C, multiple irreversible tipping points will be triggered. Discuss the implications using Type 1, Type 0 (when), and hedged futures (may/could/are likely to).','',NULL,'The reading presents a scientifically grounded warning: if the Earth warms by more than 1.5 degrees above pre-industrial levels, several climate tipping points may be triggered simultaneously. When ice sheets destabilize beyond a threshold, they tend to continue melting regardless of subsequent emissions reductions — a self-reinforcing process. If permafrost thaws rapidly, vast quantities of stored methane will be released, further accelerating warming in a feedback cycle. The reading notes that the probability of crossing multiple tipping points increases sharply between 1.5°C and 2°C, a range we could reach within the next two to three decades if current trends continue. This suggests that the window for prevention is narrow and that every fraction of a degree of warming averted is meaningful.','hard'),

  -- BLOCK 47: TOEFL Writing
  (cid,47,188,'production','[TOEFL Writing — 150 words] Write an argumentative paragraph on digital literacy using: Type 1 (×3), when vs if, modal variations (can/may/might in result), provided that, unless.','',NULL,'Digital literacy has become a prerequisite for meaningful participation in contemporary economic and civic life. If educational systems fail to integrate digital literacy training into curricula from an early age, students will enter the workforce unprepared for roles that require basic data literacy and online communication skills. When young people understand how algorithms curate the information they see, they can engage with digital media more critically and resist manipulation. Provided that digital literacy programs are thoughtfully designed to address equity as well as skills, they may help close rather than widen existing educational gaps. Unless access to reliable internet and devices is treated as an infrastructure priority alongside roads and electricity, digital literacy training will fail to reach the communities that need it most. If these conditions are met, the benefits of digital inclusion could be substantial and broadly shared.','hard'),
  (cid,47,189,'production','[TOEFL Writing — Error Correction] Fix Type 1 conditional errors: "If it will rain tomorrow, we will cancel the event. When the results might be available, we will analyze them. If you will submit on time, you will receive full credit. Provided that you won''t comply with the rules, you will be disqualified. Should you will need assistance, contact the support team."','',NULL,'will rain → rains (if-clause = present simple in Type 1); When the results might be available → When the results are available (when = certain future, present simple — not might); will submit → submit (if-clause = present simple, not will); won''t comply → comply (provided that/unless + positive verb — ''provided that you don''t comply'' or ''unless you comply''); Should you will need → Should you need (inverted Type 1: Should + subject + base verb, no ''will'').','hard'),

  -- BLOCK 48: Consolidação — Type 1 completo
  (cid,48,190,'production','[TOEFL Writing — 200 words] Write an essay body paragraph on water scarcity using every major Type 1 variation: standard (if + PS / will), inverted (Should), when vs if contrast, unless, provided that, modal variants (can/may/might in result), implicit conditional (imperative + and), and passive present simple in if-clause.','',NULL,'Water scarcity represents one of the defining resource challenges of the twenty-first century, and the choices made by governments and industries in the coming decades will determine whether this challenge becomes a crisis. If current agricultural irrigation practices are not reformed, water tables in major food-producing regions may fall below the threshold needed to sustain production within a generation. Should innovation in water recycling and desalination accelerate as projected, costs will decline sufficiently to make these technologies viable at scale in water-stressed regions. When countries invest in natural water catchment systems — restoring wetlands, protecting river catchments, and rebuilding urban green infrastructure — they can often achieve water security at a fraction of the cost of engineering solutions. Unless international agreements governing transboundary water bodies are strengthened, upstream users will continue to divert flows in ways that harm downstream populations. Invest in water literacy programs for farmers, and adoption of water-efficient irrigation technology will increase rapidly. Provided that governments treat water as a public good rather than a tradeable commodity, equitable distribution across urban and rural communities can be achieved.','hard'),
  (cid,48,191,'production','[TOEFL Writing — 200 words] Integrated task body paragraph: The reading argues that universal basic income will reduce poverty. The lecture argues that it will reduce work incentives. Use Type 1 conditionals to express both conditional claims.','',NULL,'The reading and the lecture reach opposite conclusions about the likely effects of a universal basic income on labor market participation and poverty reduction. The reading contends that if all citizens receive a guaranteed minimum income, the poverty trap — the disincentive to work created by benefit withdrawal rates — will be eliminated. When individuals are freed from the threat of destitution, the reading suggests, they can take the kinds of risks associated with entrepreneurship, further education, and career change that generate long-term economic dynamism. The lecture, however, presents a counterargument grounded in incentive economics: if people receive income regardless of their work status, the marginal utility of additional labor income may decline to the point where participation rates fall. Should this happen across a significant proportion of the workforce, tax revenues may decline, threatening the very funding base that sustains the universal basic income program itself. The lecture thus argues that unless basic income is carefully calibrated — set below the level that would generate substantial work disincentives — the policy risks undermining its own fiscal foundations.','hard'),
  (cid,48,192,'production','[TOEFL Writing — short] Finish this academic sentence using Type 1 logic: "If the peer review process continues to rely primarily on unpaid academic labor..."','...journals will struggle to maintain quality as submission volumes increase, unless alternative models — such as paid review or open post-publication review — are adopted to distribute the burden more equitably.',NULL,'Complete Type 1 academic sentence with unless and alternative outcome.','hard'),
  (cid,48,193,'gap_fill','If a theory _____ (fail) to make testable predictions, it _____ (cannot/consider/passive) genuinely scientific, according to Popper''s criterion of falsifiability.','fails / cannot be considered',NULL,'Type 1 + modal passive in result clause: academic philosophical claim.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
