-- ============================================================
-- SEED EXT 5: Módulo 11 — Relative Clauses (ex 177-248)
-- Novos tópicos: RCs em TOEFL essays, relative clauses com
-- quantificadores avançados, participial phrases, RCs encaixadas
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'relative-clauses';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo relative-clauses não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 51: RCs em argumentação acadêmica avançada
  (cid,51,177,'gap_fill','The countries _____ (demonstrate) the fastest economic recovery are precisely those _____ (invest) most heavily in digital infrastructure prior to the pandemic.','that have demonstrated / which have demonstrated / that invested / which invested',NULL,'Defining RC with relative pronoun (that/which) for non-human antecedent.','easy'),
  (cid,51,178,'gap_fill','The researchers _____ conducted the original study _____ the results _____ had been widely cited now acknowledge significant methodological limitations.','who / whose / which / that',NULL,'RC with ''who'' (researchers) + ''whose'' (possessive) + ''which'' (results).','hard'),
  (cid,51,179,'gap_fill','The policy framework within _____ these decisions _____ (take/passive) matters enormously for outcomes, particularly _____ jurisdictions _____ institutional capacity _____ (remain) limited.','which / are taken / in / whose / remains',NULL,'''Within which'' (preposition + relative) + ''in which'' + ''whose'' (possessive relative).','hard'),
  (cid,51,180,'multiple_choice','Which RC correctly uses ''in which'' for a formal academic context?','The conditions in which these experiments were conducted may have influenced the results significantly.','[''The conditions which these experiments were conducted may have influenced the results.'',''The conditions in which these experiments were conducted may have influenced the results significantly.'',''The conditions where these experiments were conducted may have influenced the results.'',''The conditions that these experiments were conducted in may have influenced the results.'']','''In which'' = formal relative (not ''where'' in writing, not ending in preposition).','medium'),
  (cid,51,181,'gap_fill','The mechanism _____ (by/which) antibiotics _____ (kill) bacteria has been extensively studied, yet the precise molecular pathway _____ (through/which) resistance _____ (emerge) _____ (remain) incompletely understood.','by which / kill / through which / emerges / remains',NULL,'Preposition + which (by which/through which) in complex academic sentence.','hard'),

  -- BLOCK 52: Quantificadores com RCs
  (cid,52,182,'gap_fill','Several interventions _____ (evaluate/passive) in the literature, _____ of _____ _____ (show/passive) to be effective across all demographic groups.','have been evaluated / none / which / has been shown',NULL,'''None of which'' = zero-quantity quantifier relative clause.','hard'),
  (cid,52,183,'gap_fill','The researchers identified twelve potential risk factors, _____ of _____ _____ (statistically/significant) in the final regression model.','three / which / were statistically significant',NULL,'''Three of which'' = specific quantifier RC.','medium'),
  (cid,52,184,'multiple_choice','Which sentence CORRECTLY uses a quantifier with a relative clause?','The committee reviewed forty proposals, most of which fell outside the stated eligibility criteria.','[''The committee reviewed forty proposals, most of that fell outside the criteria.'',''The committee reviewed forty proposals, most of which fell outside the stated eligibility criteria.'',''The committee reviewed forty proposals, the most of which fell outside the criteria.'',''The committee reviewed forty proposals, most which fell outside the criteria.'']','''Most of which'' = quantifier + ''of which'' (not ''of that'' or ''most which'').','medium'),
  (cid,52,185,'gap_fill','The report examined twelve case studies, _____ of _____ _____ (involve) countries with per capita incomes below $2,000, and the majority of _____ _____ (implement) reforms under conditions of economic crisis.','eight / which / involved / which / had implemented',NULL,'Quantifier RC chains: ''eight of which'' + ''the majority of which.''','hard'),
  (cid,52,186,'gap_fill','Several competing theories _____ (advance/passive), each of _____ _____ (capture) some aspect of the phenomenon but none of _____ _____ (adequate/explain) the full pattern of observations.','have been advanced / which / captures / which / adequately explains',NULL,'''Each of which'' + ''none of which'' = distributive and zero-quantifier RCs.','hard'),

  -- BLOCK 53: Participial phrases como redução de RCs
  (cid,53,187,'gap_fill','Countries _____ (experience) rapid urbanization face distinct governance challenges from those _____ (complete) their urban transition decades ago.','experiencing / that experienced / having completed',NULL,'Present participle (ongoing) + past participle (completed action) as reduced RCs.','medium'),
  (cid,53,188,'gap_fill','The data _____ (collect/passive) across 47 countries _____ (span) three decades _____ (provide) the most comprehensive longitudinal evidence currently available.','collected / spanning / provides',NULL,'Participial phrase (collected) + (spanning) = reduced defining RCs modifying ''data.''','hard'),
  (cid,53,189,'multiple_choice','What is the PARTICIPIAL PHRASE form of ''The research, which was conducted over a decade, revealed...''?','The research, conducted over a decade, revealed...','[''The research, conducting over a decade, revealed...'',''The research, having conducted over a decade, revealed...'',''The research, conducted over a decade, revealed...'',''The research, which has been conducted over a decade, revealed...'']','Passive participle ''conducted'' = reduced non-defining RC (passive participial phrase).','medium'),
  (cid,53,190,'gap_fill','The model _____ (develop/passive) by X and Y (1998), _____ (subsequently/refine/passive) and _____ (extend/passive) by later researchers, _____ (remain) the dominant framework in the field.','developed / subsequently refined / extended / remains',NULL,'Chain of passive participials: developed + refined + extended = three reduced non-defining RCs.','hard'),
  (cid,53,191,'gap_fill','Governments _____ (seek) to reduce inequality must grapple with both the mechanisms _____ (generate) it and the political obstacles _____ (impede) redistributive action.','seeking / generating / impeding',NULL,'Present participial phrases: seeking (purpose), generating (cause), impeding (obstacle).','hard'),

  -- BLOCK 54: Embedded RCs (RCs dentro de RCs)
  (cid,54,192,'gap_fill','The scholar _____ (argue) that the reforms _____ (advocate/passive) by the government _____ (prove) insufficient was subsequently vindicated by the evidence.','who argued / that were advocated / proved',NULL,'Embedded RC: ''who argued [that the reforms [that were advocated] proved insufficient].''','hard'),
  (cid,54,193,'gap_fill','The communities in _____ the organizations _____ (support/passive) by the foundation _____ (operate) _____ (have) the highest indices of social fragmentation.','which / supported / operate / have',NULL,'Embedded RC: ''in which [the organizations [supported by the foundation] operate].''','hard'),
  (cid,54,194,'multiple_choice','Which sentence uses EMBEDDED relative clauses CORRECTLY?','The theory that the mechanism by which inflation erodes purchasing power operates differently in open economies requires empirical verification.','[''The theory which the mechanism by which inflation erodes purchasing power operates differently requires verification.'',''The theory that the mechanism by which inflation erodes purchasing power operates differently in open economies requires empirical verification.'',''The theory, which the mechanism by which inflation erodes, operates differently in open economies requires verification.'',''The theory that the mechanism which by inflation erodes purchasing power operates differently requires empirical verification.'']','Embedded RC: ''that [the mechanism [by which inflation erodes purchasing power] operates differently].''','hard'),

  -- BLOCK 55: TOEFL Reading avançado com RCs
  (cid,55,195,'multiple_choice','[TOEFL Reading] ''Researchers who have studied communities where traditional practices have been maintained report higher levels of social cohesion.'' How many relative clauses are in this sentence?','Two: ''who have studied communities'' (defining) and ''where traditional practices have been maintained'' (defining).','[''One'',''Three'',''Two: ''who have studied communities'' (defining) and ''where traditional practices have been maintained'' (defining).'',''Zero — these are participial phrases'']','RC1: ''who have studied communities'' (relative pronoun who). RC2: ''where traditional practices have been maintained'' (relative adverb where).','hard'),
  (cid,55,196,'gap_fill','[TOEFL Reading] ''A country _____ (fiscal position) _____ (weaken/passive) significantly is likely to face higher borrowing costs.'' Best RC form?','whose / has been weakened / fiscal position has been weakened',NULL,'''Whose fiscal position has been weakened'' = possessive defining RC.','hard'),
  (cid,55,197,'gap_fill','[TOEFL Reading] ''The mechanism by _____ economic shocks _____ (transmit/passive) across borders _____ (involve) complex interactions between trade, capital flows, and expectations.'' Best forms?','which / are transmitted / involves',NULL,'''By which'' + passive + PS verb for main clause.','hard'),
  (cid,55,198,'multiple_choice','[TOEFL Reading] ''The findings, many of which contradict earlier assumptions, have significant implications for the field.'' The phrase ''many of which'' is:','A quantifier relative clause referring to ''the findings.''','[''A parenthetical comment'',''A quantifier relative clause referring to ''the findings.'''',''An independent clause'',''A defining relative clause'']','''Many of which'' = quantifier + relative pronoun, modifying ''the findings.''','medium'),

  -- BLOCK 56: TOEFL Speaking avançado com RCs
  (cid,56,199,'production','[TOEFL Speaking — 45s] A reading describes the benefits of green urban spaces. The professor raises concerns about equity. Use relative clauses throughout.','',NULL,'The reading describes research findings that suggest urban green spaces, which include parks, urban forests, and community gardens, confer significant benefits on the populations that have access to them. These benefits, which range from improved air quality to reduced urban heat island effects and better mental health outcomes, make the case for substantially expanding green infrastructure in cities. However, the professor raises a concern that the reading does not adequately address: the distribution of green spaces within cities tends to reflect existing socioeconomic inequalities. Neighborhoods whose residents have lower incomes and belong to minority groups are precisely the communities in which green space is most lacking, which means that the populations that would benefit most from expanded urban greenery are often those that current investment patterns are not reaching. The professor concludes that urban greening initiatives that are not specifically designed to prioritize underserved neighborhoods risk benefiting groups who are already advantaged, thereby widening inequalities rather than addressing them.','hard'),
  (cid,56,200,'production','[TOEFL Speaking — 45s] Discuss the advantages of international scientific collaboration. Use relative clauses throughout.','',NULL,'International scientific collaboration, which has become increasingly central to the production of cutting-edge research, offers benefits that individual national research communities cannot easily replicate independently. Studies that draw on data from multiple countries, which allows researchers to test hypotheses across contexts that differ in important ways, tend to produce findings that are more generalizable than those generated by single-country research designs. Large-scale research infrastructure — particle accelerators, telescope arrays, genomic databases — requires investment at a scale that exceeds what any single country, even those whose scientific budgets are very large, can easily justify individually. Furthermore, researchers who have trained and worked in different national traditions bring diverse problem-solving approaches and cultural perspectives that can generate intellectual breakthroughs that would be less likely to emerge in more homogeneous scientific communities. The collaborative networks that have developed around major international scientific projects also create relationship capital that facilitates communication and trust in contexts beyond science, which suggests that international research collaboration has a broader social value that extends beyond the specific knowledge it produces.','hard'),

  -- BLOCK 57: TOEFL Writing avançado com RCs
  (cid,57,201,'production','[TOEFL Writing — 200 words] Write a paragraph on foreign investment policy using relative clauses extensively.','',NULL,'Foreign direct investment, which has been a central driver of economic integration over the past half century, presents governments with a complex set of trade-offs that require careful policy design. Countries that have attracted substantial inflows of foreign investment have typically benefited from job creation, technology transfer, and integration into global supply chains that would otherwise be difficult to access. However, the relationship between foreign investment and development is not straightforwardly positive: the terms under which foreign firms invest matter enormously, and extractive industries in particular, which generate significant revenues that often accrue disproportionately to foreign shareholders and corrupt domestic elites, have in several cases left host countries in a worse position than they were before the investment occurred. The investment agreements through which foreign investors seek protection for their assets have also been criticized for constraining the regulatory policy space that governments need to address labor standards, environmental protection, and public health in ways whose effects on the poorest populations can be severe. Governments that have negotiated carefully, that have insisted on technology and skills transfer, and that have maintained the regulatory capacity to hold investors accountable to agreed standards have generally had significantly better outcomes than those whose investment policy was driven primarily by the competitive imperative to attract capital on whatever terms investors demanded.','hard'),
  (cid,57,202,'production','[TOEFL Writing — 200 words] Write a paragraph on the digital divide using relative clauses throughout.','',NULL,'The digital divide, which describes the gap between populations that have reliable, affordable access to digital technology and those that do not, has become one of the most consequential dimensions of global inequality in the twenty-first century. Communities in which digital access is limited are increasingly excluded from economic and educational opportunities that are delivered primarily through digital channels, a pattern that risks entrenching disadvantage across generations. Students whose schools lack adequate connectivity and devices fall behind peers in better-resourced settings in ways that affect their long-term earnings potential and social mobility. Workers who lack digital skills are being systematically disadvantaged in labor markets in which an expanding share of employment requires at least basic technological competence. The households that are most likely to be on the wrong side of the digital divide — those whose incomes are low, who live in rural or remote areas, and who belong to groups that have historically been underserved by public investment — are also those that stand to benefit most from equitable access to digital tools for learning, economic participation, and civic engagement. Closing the digital divide requires simultaneously addressing the infrastructure gaps, affordability barriers, and skills deficits that together produce exclusion, none of which can be addressed adequately by market mechanisms operating without deliberate policy intervention.','hard'),

  -- BLOCK 58: Final
  (cid,58,203,'production','[TOEFL Writing — 200 words] Write a conclusion on housing policy using relative clauses throughout.','',NULL,'The foregoing analysis has argued that housing affordability, which has deteriorated in many cities worldwide, is not primarily a market failure in the conventional sense — it is the predictable outcome of a set of policy and institutional choices that have systematically privileged the interests of existing property owners over those of tenants and aspiring homeowners. The most significant of these choices, which include restrictive zoning regimes that limit housing supply, tax systems that reward speculative property investment, and public housing programs whose funding has been progressively eroded, can all be reversed through deliberate policy action. Cities and regions that have adopted more permissive land use regulations have consistently seen slower price growth than those whose zoning systems remain restrictive. The inclusionary zoning requirements that have been adopted in several jurisdictions, under which developers are required to include below-market units in new projects, represent a promising approach whose scale would need to expand considerably to make a meaningful contribution to affordability at the population level. Solving the housing crisis ultimately requires a political coalition that includes the renters and young households whose interests are not well represented in the political processes through which land use decisions are typically made, and building that coalition is a project that demands community organizing as much as policy analysis.','hard'),
  (cid,58,204,'production','[TOEFL Speaking — 60s] Discuss reforms to global financial governance. Use relative clauses throughout.','',NULL,'Global financial governance, which refers to the international institutions, agreements, and norms that regulate cross-border financial flows and provide mechanisms for managing financial crises, has evolved significantly since the Bretton Woods institutions were established in the aftermath of the Second World War. The International Monetary Fund, which was originally designed to manage a system of fixed exchange rates that no longer exists, has reinvented itself as a crisis lender and macroeconomic surveillance body, though critics argue that the conditionality requirements it has attached to its loans, many of which have required pro-cyclical fiscal tightening in countries whose economies were already contracting, have caused significant harm. The governance structures through which decisions in the IMF and World Bank are made, which give disproportionate voting weight to wealthy countries whose financial interests may not align with those of developing borrowers, have been a persistent source of criticism. The G20, which has emerged as the primary forum for coordination among major economies since the 2008 financial crisis, has addressed some aspects of financial regulation that the formal international institutions whose mandates were established in the 1940s were not designed to handle. The reforms that are most needed — a genuine rebalancing of voice and governance rights toward developing countries, and the development of effective mechanisms for sovereign debt restructuring that do not require protracted negotiations whose costs fall primarily on debtor populations — have remained elusive, largely because the major creditor countries that would need to agree to them have little immediate incentive to do so.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
