-- ============================================================
-- SEED EXT 3: Módulo 12 — Conditional 2/3 (ex 117-210)
-- Novos tópicos: mixed conditionals, unless/provided/as long as,
-- conditionals sem if, academic conditionals, TOEFL
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'conditional-2-3';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo conditional-2-3 não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 31: mixed conditionals (Type 2 result + Type 3 condition)
  (cid,31,117,'multiple_choice','What is a mixed conditional?','A conditional that combines the if-clause of one type with the result clause of another.','["A conditional with two if-clauses","A conditional that combines the if-clause of one type with the result clause of another.","A conditional that uses might instead of would","A conditional with no result clause"]','Mixed conditionals blend Type 2 and Type 3 — crossing past conditions with present results or present conditions with past results.','hard'),
  (cid,31,118,'gap_fill','If she _____ (have) a doctorate, she _____ (be) a senior researcher now. (past condition + present result)','had had / would be',NULL,'Mixed conditional: past perfect if-clause (Type 3) + would + base verb (Type 2 result) → past cause, present consequence.','hard'),
  (cid,31,119,'multiple_choice','Which sentence is a correct mixed conditional (past condition, present result)?','If he had studied medicine, he would be a doctor now.','["If he had studied medicine, he would have been a doctor now.","If he studies medicine, he will be a doctor.","If he had studied medicine, he would be a doctor now.","If he studied medicine, he would have been a doctor."]','"Had studied" (past perfect/Type 3) + "would be now" (present/Type 2) = past condition → present result.','hard'),
  (cid,31,120,'gap_fill','If I _____ (not/born) in a poor country, I _____ (have) access to better education now. (past fact → present consequence)','hadn''t been born / would have',NULL,'Mixed: Type 3 if-clause (past perfect) + Type 2 result clause (would + base verb present).','hard'),
  (cid,31,121,'multiple_choice','Which is a correct mixed conditional (present condition, past result)?','If he were more careful, he wouldn''t have made that mistake yesterday.','["If he were more careful, he wouldn''t make that mistake yesterday.","If he were more careful, he wouldn''t have made that mistake yesterday.","If he had been more careful, he wouldn''t make that mistake.","If he is more careful, he wouldn''t have made the mistake."]','"Were" (present unreal/Type 2) + "wouldn''t have made yesterday" (past result/Type 3) = present character → past consequence.','hard'),
  (cid,31,122,'gap_fill','If the vaccine _____ (not/exist), millions _____ (die/still) every year from diseases now preventable. (present fact → ongoing present)','didn''t exist / would still be dying',NULL,'Mixed: Type 2 present condition + Type 2 present result (ongoing).','hard'),

  -- BLOCK 32: unless / provided that / as long as / given that
  (cid,32,123,'gap_fill','The experiment will proceed _____ (unless) the ethics board raises objections at the next meeting.','unless',NULL,'"Unless" = if not. Condition must NOT be true for the result to occur.','easy'),
  (cid,32,124,'multiple_choice','What is the difference between "if not" and "unless"?','They are often synonymous, but "unless" is more emphatic and formal, focusing on the exceptional condition.','["They are identical in all contexts","Unless requires a negative verb in the result clause","They are often synonymous, but ''unless'' is more emphatic and formal, focusing on the exceptional condition.","If not is always more formal than unless"]','"Unless" = except if / only if not. Slightly stronger/more formal than "if not."','hard'),
  (cid,32,125,'gap_fill','The funding will be released, _____ (provided that) all milestones have been achieved on schedule.','provided that / provided',NULL,'"Provided (that)" = conditional meaning "only if." More formal than "if."','medium'),
  (cid,32,126,'multiple_choice','Which conditional conjunction expresses the MOST restricted condition?','Only if the results are independently verified will the paper be accepted.','["Unless the results are independently verified...","As long as the results are verified...","Only if the results are independently verified will the paper be accepted.","Provided the results are verified..."]','"Only if" = the most restrictive: this condition and no other.','hard'),
  (cid,32,127,'gap_fill','The partnership _____ (will/continue) _____ (as long as) both parties adhere to the agreed-upon terms.','will continue / as long as',NULL,'"As long as" = on the condition that (continuous condition).','medium'),
  (cid,32,128,'multiple_choice','Which sentence uses "given that" correctly?','Given that the sample size was small, the results should be interpreted with caution.','["Given that if the sample size was small, interpret with caution.","Given that the sample size was small, the results should be interpreted with caution.","Given that the sample size will be small, the results are less reliable.","Given that sample size was small, interpret results with caution."]','"Given that + clause" = since/considering that. Concessive-conditional.','medium'),

  -- BLOCK 33: conditionals sem if (inversion avançada)
  (cid,33,129,'gap_fill','_____ (Were) the government to introduce a universal basic income, the effects on the labor market would be profound.','Were',NULL,'"Were + subject + to + base verb" = formal inversion of Type 2 conditional.','hard'),
  (cid,33,130,'multiple_choice','Which is the correct inverted form of "If the trial had been successful, the drug would be available now"?','Had the trial been successful, the drug would be available now.','["Were the trial successful, the drug would be available now (wrong type — mixes Type 2 inversion with Type 3 meaning).","Had the trial been successful, the drug would be available now.","Should the trial be successful, the drug would be available now (Type 1 formal).","Had the trial been successful, the drug would have been available now (Type 3 only — not mixed)."]','Inverted mixed conditional: "Had + subject + past participle + would + base verb now."','hard'),
  (cid,33,131,'gap_fill','_____ (Should) you require any further information, please do not hesitate to contact us.','Should',NULL,'"Should + subject + base verb" = formal inverted Type 1 conditional.','medium'),
  (cid,33,132,'multiple_choice','In formal academic writing, which inverted conditional is most common?','Were the data to suggest otherwise, the hypothesis would need to be revised.','["Should you need any help, please contact us (formal but more common in business letters).","Were the data to suggest otherwise, the hypothesis would need to be revised.","Had we known earlier, we would have informed you (Type 3 — common in academic discussion).","Were I you, I would reconsider (advice — less academic)."]','"Were + the + noun + to + base verb" = highly formal academic conditional.','hard'),

  -- BLOCK 34: conditionals em textos acadêmicos
  (cid,34,133,'gap_fill','If the correlation _____ (prove/passive) to be causal, it _____ (have) significant implications for treatment protocols.','were proven / would have',NULL,'Academic Type 2 conditional for speculative implications.','hard'),
  (cid,34,134,'multiple_choice','Which sentence is most appropriate in the discussion section of a research paper?','If the sample size had been larger, the results might have been more generalizable.','["If the sample size is larger, the results might be more generalizable.","The results would be more generalizable if the sample size will be larger.","If the sample size had been larger, the results might have been more generalizable.","If the sample size were larger, the results would be more generalizable (Type 2 — suggests hypothetical, also acceptable)."]','Type 3 conditional for reflecting on study limitations in a discussion section.','hard'),
  (cid,34,135,'gap_fill','_____ (Given that) the mechanism is not yet fully understood, any clinical recommendation _____ (be + premature).','Given that / would be premature',NULL,'"Given that + clause, would + base verb" = academic conditional reasoning.','hard'),
  (cid,34,136,'multiple_choice','Which of these academic statements uses a conditional most effectively?','Were this hypothesis to be confirmed by further research, it would necessitate a fundamental revision of current theory.','["If this hypothesis is confirmed, it will necessitate revision (Type 1 — implies high confidence).","If this hypothesis was confirmed, it would necessitate revision (Type 2 — hypothetical).","Were this hypothesis to be confirmed by further research, it would necessitate a fundamental revision of current theory.","Unless this hypothesis is confirmed, no revision is necessary."]','Inverted Type 2 with academic hedging = most formal and appropriately tentative.','hard'),

  -- BLOCK 35: TOEFL Reading
  (cid,35,137,'multiple_choice','[TOEFL Reading] "Had early antibiotics not been developed, the death toll from bacterial infections in the 20th century would have been staggering." This is:','A Type 3 conditional expressing a past counterfactual.','["A Type 1 conditional prediction","A Type 2 conditional","A Type 3 conditional expressing a past counterfactual.","A mixed conditional"]','Had + past participle / would have + past participle = Type 3 (past unreal).','easy'),
  (cid,35,138,'gap_fill','[TOEFL Reading] "If human-induced warming _____ (continue) unchecked, global sea levels _____ (rise) by more than a meter by 2100." Type 1 formal academic form?','continues / will rise / are projected to rise',NULL,'Type 1: present simple if-clause + will/project future result (formal academic).','medium'),
  (cid,35,139,'multiple_choice','[TOEFL Reading] "Were the sun to suddenly disappear, Earth would lose its primary source of heat within eight minutes." This conditional:','Is a formal Type 2 with inverted "were" — a highly unlikely hypothetical.','["Is a Type 3 conditional about a past event","Is a Type 1 prediction","Is a formal Type 2 with inverted ''were'' — a highly unlikely hypothetical.","Is a mixed conditional"]','"Were + subject + to + base verb + would" = inverted Type 2 for highly hypothetical.','medium'),
  (cid,35,140,'gap_fill','[TOEFL Reading] "Unless immediate steps _____ (take/passive), the situation is likely to deteriorate further." Best form?','are taken',NULL,'"Unless + passive present simple" = present condition required for future result.','medium'),

  -- BLOCK 36: TOEFL Speaking
  (cid,36,141,'production','[TOEFL Speaking — 45s] A reading says that if developing countries had received more financial support in the 1990s, poverty rates would be much lower today. Agree or disagree. Use: mixed conditional, Type 3, unless, provided that.','',NULL,'I agree strongly. If wealthier nations had fulfilled their aid commitments in the 1990s, millions who are living in poverty today would not be. This is a classic case of a past failure producing present consequences. Unless richer nations now provide both financial resources and technology transfers, meaningful poverty reduction will remain elusive in the most disadvantaged regions. Progress is achievable, provided that commitments are made legally binding and tied to measurable outcomes rather than vague pledges.','hard'),
  (cid,36,142,'production','[TOEFL Speaking — 45s] Discuss the risks of artificial intelligence. Use: were + to (Type 2 inverted), had + PP (Type 3), unless, mixed conditional, given that.','',NULL,'Were AI systems to be deployed without rigorous oversight, the risks to privacy and democratic processes could be severe. Given that these systems are already influencing hiring decisions, credit ratings, and even criminal sentencing, the stakes are high. Had regulators moved sooner to establish accountability frameworks, many of the harms already observed might have been avoided and public trust in AI would be stronger today. Unless governments coordinate internationally, individual national regulations will be insufficient to govern systems that operate across borders without constraints.','hard'),

  -- BLOCK 37: TOEFL Writing
  (cid,37,143,'production','[TOEFL Writing — 150 words] Write an academic paragraph about educational inequality using: Type 2, Type 3, mixed conditional, unless, provided that, as long as, were + to (formal inversion).','',NULL,'Were governments to invest substantially in early childhood education for disadvantaged communities, the long-term economic benefits would far exceed the initial costs. Studies suggest that if disadvantaged children had received high-quality preschool programs, their cognitive outcomes and lifetime earnings would be measurably higher. Even today, unless access to quality education is equalized, the intergenerational transmission of poverty will continue unchecked. Children from lower-income families will not close the achievement gap with their more affluent peers provided that structural disparities in school funding, teacher quality, and access to resources persist. As long as educational policy prioritizes efficiency over equity, systemic inequality will remain entrenched. Mixed conditional thinking is useful here: if governments in the 1970s had funded universal early childhood programs, we would not be dealing with the scale of educational inequality we observe today.','hard'),
  (cid,37,144,'production','[TOEFL Writing — Error Correction] Fix conditional errors: "If she would study harder, she will pass. Had the government acted sooner, the crisis would be avoidable. Unless you won''t attend the seminar, you won''t receive credit. Were I know the answer, I would tell you. If it rains tomorrow, we would cancel the event."','',NULL,'would study → studied (Type 2 if-clause: past simple, not would); would be avoidable → would have been avoidable (Type 3 result: would have + past participle); Unless you won''t attend → Unless you attend (unless + positive verb); Were I know → Were I to know (were + subject + to + base verb); would cancel → will cancel (Type 1: present simple → will, not would).','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
