-- ============================================================
-- SEED EXT 2: Módulo 19 — Hedging Language (exercícios 71-165)
-- Novos tópicos: boosters vs hedges, passive impersonal hedging,
-- over-hedging errors, hedging in conclusions, TOEFL
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'hedging-language';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo hedging-language não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 11: boosters vs hedges
  (cid,11,71,'multiple_choice','Which word is a BOOSTER (increases certainty), not a hedge?','Clearly','["Arguably","Apparently","Clearly","Possibly"]','"Clearly" and "obviously" are boosters (claim certainty). "Arguably/apparently/possibly" are hedges.','medium'),
  (cid,11,72,'gap_fill','The evidence _____ (clear/booster) demonstrates that early childhood nutrition is critical for cognitive development. (writer is confident)','clearly',NULL,'"Clearly" = booster. The writer presents this as established fact.','easy'),
  (cid,11,73,'multiple_choice','Which sentence is OVER-CONFIDENT for a research claim?','This study proves that exercise eliminates depression.','["This study suggests that exercise may reduce symptoms of depression.","Exercise appears to be associated with reduced symptoms of depression.","This study proves that exercise eliminates depression.","The findings indicate that exercise could be beneficial for mood disorders."]','"Proves" and "eliminates" = overclaims. Academic writing requires hedging uncertain conclusions.','medium'),
  (cid,11,74,'gap_fill','_____ (it seems / booster), the benefits of bilingualism extend beyond language itself to cognitive flexibility. (writer is confident based on evidence)','It is clear that / The evidence clearly shows that',NULL,'When confident in well-supported claims, boosters (clearly / it is clear that) are appropriate.','hard'),
  (cid,11,75,'multiple_choice','A researcher writes: "Apparently, the data shows that the treatment is effective." What is wrong?','Apparently implies the researcher is uncertain or has heard this from others — should be "clearly" or "the data show."','["Apparently is a hedge and hedges are never used in research","Apparently implies the researcher is uncertain or has heard this from others — should be ''clearly'' or ''the data show.''","The sentence should use a passive construction","Data should be singular"]','"Apparently" = based on appearance/hearsay. For data you have collected, use "the data show" or "clearly."','hard'),
  (cid,11,76,'gap_fill','While some studies _____ (suggest) a link between social media use and anxiety, the causal mechanism remains poorly understood.','suggest / appear to suggest / indicate',NULL,'Hedged first clause + stronger unhedged second claim about what IS clear.','medium'),
  (cid,11,77,'multiple_choice','Rank from MOST to LEAST certain: "The treatment proved effective / The treatment seems effective / The treatment may be effective."','Proved > seems > may be.','["May be > seems > proved","Seems > proved > may be","Proved > seems > may be.","Seems > may be > proved"]','Proved = full certainty. Seems = likelihood. May be = possibility.','medium'),

  -- BLOCK 12: passive impersonal hedging
  (cid,12,78,'gap_fill','_____ (it + passive + argue) that social media is fundamentally altering human communication patterns.','It has been argued',NULL,'"It has been argued that" = passive impersonal hedge. Attributes claim to unspecified others.','hard'),
  (cid,12,79,'multiple_choice','Which sentence uses passive impersonal hedging correctly?','It is widely believed that economic inequality contributes to political instability.','["People widely believe economic inequality contributes to instability (informal/personal).","It is widely believed that economic inequality contributes to political instability.","We widely believe that economic inequality contributes to political instability.","It is wide belief that economic inequality contributes to instability."]','"It is widely believed that" = formal passive impersonal hedge.','hard'),
  (cid,12,80,'gap_fill','_____ (it + passive + accept + widely) that correlation does not imply causation in empirical research.','It is widely accepted that',NULL,'"It is widely accepted that" = consensus hedge.','hard'),
  (cid,12,81,'multiple_choice','Transform: "Many researchers have suggested that the findings may not be replicable." → passive impersonal form.','It has been suggested that the findings may not be replicable.','["People suggest that the findings may not be replicable.","It has been suggested that the findings may not be replicable.","The findings may not be replicable has been suggested.","They suggest that the findings may not be replicable."]','"It has been suggested that" = removes specific agents.','hard'),
  (cid,12,82,'gap_fill','_____ (it + passive + claim) that this new methodology produces more reliable results than previous approaches.','It has been claimed',NULL,'"It has been claimed that" = someone has made this claim but the writer remains cautious.','hard'),
  (cid,12,83,'multiple_choice','What is the pragmatic function of "It is important to note that..."?','It signals that the following information is significant and may qualify or limit the preceding claim.','["It is a hedge that reduces certainty","It signals that the following information is significant and may qualify or limit the preceding claim.","It introduces a new topic","It is a filler phrase with no function"]','"It is important to note" = metalinguistic signal drawing attention to a qualifier.','hard'),
  (cid,12,84,'gap_fill','_____ (it + passive + demonstrate) in multiple studies that omega-3 fatty acids support brain health.','It has been demonstrated',NULL,'"It has been demonstrated that" = strong evidence hedge with passive impersonal construction.','medium'),

  -- BLOCK 13: hedging in conclusions
  (cid,13,85,'multiple_choice','Which is the most appropriate hedge for a CONCLUSION in a TOEFL essay?','The findings of this analysis suggest that further policy reform may be necessary.','["The findings of this analysis prove that policy reform is essential (overclaims).","The findings of this analysis suggest that further policy reform may be necessary.","I think policy reform could perhaps possibly be needed (over-hedged).","This analysis shows we need policy reform (informal)"]','"Suggest + may" = double hedge appropriate for conclusions (certainty is limited).','hard'),
  (cid,13,86,'gap_fill','Based on the evidence presented, it _____ (conclude/passive) that remote work has measurable benefits for productivity in knowledge-based industries.','can be concluded / may be concluded',NULL,'"It can be concluded / may be concluded that" = hedged conclusion formula.','hard'),
  (cid,13,87,'multiple_choice','Which sentence is OVER-HEDGED and therefore too weak for a TOEFL conclusion?','It might possibly perhaps be the case that some people could sometimes benefit from exercise.','["The evidence suggests that exercise may reduce anxiety in some populations.","It might possibly perhaps be the case that some people could sometimes benefit from exercise.","Research indicates that exercise is likely to have positive effects on mental health.","The data seem to support the view that regular exercise is beneficial."]','Over-hedged = three uncertainty markers in one sentence (might possibly perhaps). Weakens credibility.','hard'),
  (cid,13,88,'gap_fill','While the results of this study are promising, they ___ (interpret) with caution given the small sample size.','should be interpreted / must be interpreted',NULL,'Hedging caveat in conclusion: modal passive for how to treat the results.','hard'),
  (cid,13,89,'multiple_choice','A good TOEFL conclusion hedge balances:','Acknowledging limitations without completely undermining the claims.','["Removing all certainty from the argument","Never using hedge words in conclusions","Acknowledging limitations without completely undermining the claims.","Replacing all verbs with passive impersonal constructions"]','Effective hedging = calibrated uncertainty; not over- or under-hedging.','hard'),
  (cid,13,90,'gap_fill','The present study has several limitations, and the findings ___ (generalize/should + negative) to all populations without further research.','should not be generalized',NULL,'Negative modal hedge in limitations/conclusion section.','hard'),

  -- BLOCK 14: scope and approximation hedges
  (cid,14,91,'multiple_choice','Which phrase is a SCOPE hedge (limiting to a particular context)?','In most cases, early intervention leads to better outcomes.','["It is clear that","In most cases, early intervention leads to better outcomes.","Obviously","The evidence proves"]','"In most cases" = scope hedge (not claiming universality).','easy'),
  (cid,14,92,'gap_fill','The treatment was effective _____ (to some extent) for patients with mild symptoms.','to some extent / to a certain degree / in some respects',NULL,'Scope hedges: "to some extent / to a certain degree" limit the strength of a claim.','medium'),
  (cid,14,93,'multiple_choice','Which pair of sentences has the CORRECT level of hedging?','Claim about accepted fact: "Water boils at 100°C." Claim about uncertain finding: "The mechanism may involve dopamine pathways."','["Claim about accepted fact: ''Water arguably boils at 100°C.'' Claim about uncertain finding: ''The mechanism involves dopamine pathways.''","Claim about accepted fact: ''Water boils at 100°C.'' Claim about uncertain finding: ''The mechanism may involve dopamine pathways.''","Claim about accepted fact: ''Water perhaps boils at 100°C.'' Claim about uncertain finding: ''The mechanism is involved with dopamine.''","Both sentences should use may."]','Facts = no hedge. Uncertain findings = hedge (may/appear to/seem to).','hard'),
  (cid,14,94,'gap_fill','_____ (large majority + approximator), the participants reported improved sleep quality after the intervention.','The large majority of / Most',NULL,'"The large majority of" = approximator (not "all" — avoids overclaiming).','medium'),
  (cid,14,95,'multiple_choice','Which sentence CORRECTLY uses an approximation hedge?','Approximately 70% of participants reported improvement.','["Exactly 70% of participants reported improvement (overclaims precision).","A lot of participants reported improvement (informal).","Approximately 70% of participants reported improvement.","All participants reported some improvement."]','"Approximately" = approximator hedging the precision of a percentage.','easy'),

  -- BLOCK 15: TOEFL Reading
  (cid,15,96,'multiple_choice','[TOEFL Reading] "The data appear to suggest a correlation between sleep deprivation and decreased academic performance." Two hedging devices are used. What are they?','"Appear to" (lexical hedge) and "suggest" (distancing reporting verb).','["Appear to (booster) and suggest (hedge)","Appear to (lexical hedge) and suggest (distancing reporting verb).","Data (impersonal) and decreased (approximator)","Correlation (hedge) and appear (booster)"]','"Appear to" = lexical hedge. "Suggest" = less-than-certain reporting verb.','hard'),
  (cid,15,97,'gap_fill','[TOEFL Reading] "It _____ (be + argue + passive) that the current model fails to account for cultural variation." Best form?','has been argued',NULL,'"It has been argued that" = passive impersonal hedging for a contested claim.','hard'),
  (cid,15,98,'multiple_choice','[TOEFL Reading] "This finding could have important implications for vaccine development." The word "could" here:','Hedges the claim — acknowledging the implications are possible but not certain.','["Proves the importance of the finding","Hedges the claim — acknowledging the implications are possible but not certain.","Is a modal of ability (can)","Indicates a past event"]','"Could" = epistemic possibility hedge.','medium'),
  (cid,15,99,'gap_fill','[TOEFL Reading] "The treatment _____ (seem) to reduce inflammation in about half of the cases studied." The hedge word is?','seems / appeared',NULL,'"Seems to" = lexical hedge (epistemic distance).','easy'),
  (cid,15,100,'multiple_choice','[TOEFL Reading] Why do academic writers hedge their claims?','To maintain intellectual honesty about the limits of their evidence and avoid overclaiming.','["To make their writing longer","To avoid responsibility for incorrect statements","To maintain intellectual honesty about the limits of their evidence and avoid overclaiming.","Because academic journals require hedging in all sentences"]','Hedging = calibrated confidence + intellectual honesty + academic credibility.','medium'),

  -- BLOCK 16: TOEFL Speaking production
  (cid,16,101,'production','[TOEFL Speaking — 45s] A reading claims that students who sleep less than 7 hours perform worse academically. Use: It has been suggested that, appear to, may, to some extent, could.','',NULL,'It has been suggested that sleep deprivation may negatively affect cognitive performance and academic outcomes. Students who sleep fewer than 7 hours appear to struggle more with memory consolidation and concentration. To some extent, these findings could reflect broader lifestyle factors rather than sleep alone. While the correlation is well-documented, the causal mechanisms could require further investigation before definitive recommendations are made.','hard'),
  (cid,16,102,'production','[TOEFL Speaking — 45s] You are discussing a controversial new study claiming social media causes loneliness. Use hedging language: It has been argued that, seem to, may not, in some cases, could be attributed to.','',NULL,'It has been argued that heavy social media use leads to increased feelings of loneliness and social isolation. While this claim has attracted widespread attention, the findings seem to apply more strongly to passive consumption than to active engagement. The relationship between social media and loneliness may not be causal — in some cases, increased online activity could be attributed to pre-existing loneliness rather than its cause. Further longitudinal research is needed before policy recommendations can be made.','hard'),

  -- BLOCK 17: TOEFL Writing
  (cid,17,103,'production','[TOEFL Writing] Fix the hedging in these sentences: (1) "This study proves that coffee improves memory." (2) "It might possibly perhaps be the case that sleep could maybe affect health." (3) "Apparently, water boils at 100°C at sea level." (4) "All students who study abroad become more open-minded."','',NULL,'(1) proves → suggests; eliminates overclaiming. (2) Over-hedged — fix to: "Sleep may affect health." or "Sleep appears to have an impact on health." (3) Apparently → [remove hedge] — this is a scientific fact. (4) All students → Most students / Students who study abroad tend to — avoids universal overclaim.','hard'),
  (cid,17,104,'production','[TOEFL Writing — 150 words] Write an academic paragraph arguing that cities should invest in cycling infrastructure. Use at least 5 hedging devices: modal hedge, lexical hedge (appear/seem/tend), passive impersonal, approximation hedge, scope hedge.','',NULL,'It has been argued that investment in urban cycling infrastructure can produce significant benefits in terms of public health, environmental sustainability, and traffic congestion. Research appears to show that cities with well-developed cycling networks tend to report lower rates of cardiovascular disease and respiratory illness among their populations. In most cases, the introduction of dedicated cycling lanes has been associated with a measurable reduction in car usage, particularly for short commutes. Approximately 60–70% of urban journeys under 3 kilometers could, in principle, be made by bicycle. It should be noted that outcomes may vary depending on climate, urban density, and pre-existing transport infrastructure. Nevertheless, the evidence suggests that investment in cycling represents a cost-effective and sustainable strategy for addressing urban mobility challenges.','hard'),
  (cid,17,105,'production','[TOEFL Writing — Error Correction] Identify and fix all hedging errors: "It is clearly proven by scientists that climate change will absolutely destroy coastal cities by 2050. The data suggests we can possibly perhaps avoid this by reducing emissions. It is obviously clear that renewable energy certainly solves every problem."','',NULL,'Sentence 1: clearly proven + will absolutely destroy = overclaim. Fix: It has been suggested / The evidence indicates / ... may pose serious threats... by the end of the century. Sentence 2: possibly perhaps = over-hedged (double hedge). Fix: "may allow us to mitigate..." Sentence 3: obviously + clearly + certainly + every problem = triple booster + absolute claim. Fix: Evidence suggests that renewable energy could significantly reduce emissions, though a full transition will require systemic change.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
