-- ============================================================
-- SEED EXT 5: Módulo 17 — Non-Defining Clauses (ex 174-248)
-- Novos tópicos: NDRCs em TOEFL essays avançados, sentence RCs
-- (which = entire proposition), NDRCs com prepositions avançados,
-- participial non-defining phrases complexas
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'non-defining-clauses';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo non-defining-clauses não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 51: NDRCs com ''which'' referindo à proposição anterior
  (cid,51,174,'gap_fill','The government failed to consult affected communities before introducing the reforms, _____ (which) many observers argued _____ (undermine) the legitimacy of the entire process.','which / undermined',NULL,'''which'' as sentence RC = refers to the entire preceding action (failure to consult), not just the noun.','medium'),
  (cid,51,175,'gap_fill','The study found no significant effect, _____ (which) was surprising given _____ the robust findings that _____ (report/passive) in the prior literature.','which / the robust findings / had been reported',NULL,'''which was surprising'' = sentence RC commenting on the null finding.','medium'),
  (cid,51,176,'gap_fill','Several competing theoretical frameworks _____ (exist), none of _____ has achieved universal acceptance, _____ (reflect) the fundamental complexity of the phenomenon being studied.','exist / which / reflecting',NULL,'''None of which'' = quantifier non-defining RC + participial phrase ''reflecting.''','hard'),
  (cid,51,177,'multiple_choice','Which sentence uses ''which'' as a SENTENCE relative clause (referring to the whole proposition)?','The funding was withdrawn at a critical stage of the project, which severely disrupted implementation.','[''The funding, which was withdrawn, severely disrupted implementation.'',''The funding was withdrawn at a critical stage of the project, which severely disrupted implementation.'',''The funding which was withdrawn severely disrupted implementation.'',''The funding was withdrawn at a critical stage, which funding severely disrupted implementation.'']','''which severely disrupted'' = refers to the fact of withdrawal being at a critical stage (entire proposition).','medium'),
  (cid,51,178,'gap_fill','The discovery fundamentally altered the field''s understanding of the mechanism, _____ _____ _____ (require/passive) to _____ (update) their theoretical models in _____ light of _____ new evidence.','which meant that researchers were required / update / the / the',NULL,'''which meant that'' = sentence RC + new clause explaining consequence.','hard'),

  -- BLOCK 52: NDRCs com preposições complexas
  (cid,52,179,'gap_fill','The committee produced a comprehensive report, _____ _____ _____ (draw) a series of recommendations that _____ (subsequently/adopt/passive) by the government.','from which / was drawn / from which were drawn / were subsequently adopted',NULL,'''From which were drawn'' = NDRC with preposition fronted.','hard'),
  (cid,52,180,'gap_fill','The institution was established in 1948, _____ _____ _____ initial mandate _____ (be) to provide short-term balance of payments support to member countries.','at which time / whose / of which / the initial mandate was',NULL,'''At which time'' = NDRC with time-preposition + relative.','hard'),
  (cid,52,181,'multiple_choice','Which sentence uses ''of which'' correctly in a NON-DEFINING context?','The study examined twelve variables, the most significant of which turned out to be institutional capacity.','[''The study examined twelve variables the most significant of which turned out to be institutional capacity.'',''The study examined twelve variables, the most significant of which turned out to be institutional capacity.'',''The study examined twelve variables, of which the most significant turned out to be institutional capacity.'',''Both B and C are correct — commas and of which placement are both acceptable.'']','B is the most typical written academic form; C is also acceptable with different information structure. B with comma is standard.','hard'),
  (cid,52,182,'gap_fill','The negotiations _____ (produce) a framework agreement, _____ _____ _____ (emerge) several subsidiary protocols that _____ (govern) specific aspects of implementation.','produced / from which / subsequently emerged / govern',NULL,'''From which subsequently emerged'' = NDRC with fronted preposition + unusual word order for emphasis.','hard'),
  (cid,52,183,'gap_fill','The researchers identified three key variables, _____ _____ _____ — institutional capacity — _____ (prove) consistently predictive across all seven countries examined.','the most important of which / the most important / proved',NULL,'''The most important of which'' = superlative quantifier NDRC.','hard'),

  -- BLOCK 53: Participial non-defining phrases
  (cid,53,184,'gap_fill','The commission, _____ (establish/passive) in 1994 and _____ (charge/passive) with reviewing the constitutional framework, _____ (produce) its final report after three years of deliberation.','established / charged / produced',NULL,'Passive participial NDRC pair: established + charged = reduced non-defining clauses.','medium'),
  (cid,53,185,'gap_fill','The new framework, _____ (draw) on best practices from twelve jurisdictions and _____ (develop/passive) through an extensive consultative process, _____ (represent) a significant advance on _____ its predecessor.','drawing / developed / represents / its',NULL,'Active participial (drawing) + passive participial (developed) = two NDRC reductions.','hard'),
  (cid,53,186,'multiple_choice','What is the full NDRC equivalent of ''The policy, widely criticized for its distributional consequences, was eventually revised''?','The policy, which was widely criticized for its distributional consequences, was eventually revised.','[''The policy, having been widely criticized for its distributional consequences, was eventually revised.'',''The policy, which was widely criticized for its distributional consequences, was eventually revised.'',''The policy, criticizing widely for its distributional consequences, was eventually revised.'',''The policy, to be widely criticized for its distributional consequences, was eventually revised.'']','''Widely criticized'' = reduced from ''which was widely criticized'' (passive participial NDRC).','medium'),
  (cid,53,187,'gap_fill','The intervention, _____ (design/passive) to address structural barriers to access and _____ (pilot/passive) in three regions before _____ (scale) nationally, _____ (demonstrate) significant improvements in outcome measures across all sites.','designed / piloted / being scaled / demonstrated',NULL,'Passive participial NDRC (designed/piloted) + gerund clause (before being scaled) + main verb.','hard'),
  (cid,53,188,'gap_fill','The dataset, _____ (comprise) over two million observations _____ (collect/passive) across forty countries over two decades, _____ (allow) for the most comprehensive cross-national analysis attempted to date.','comprising / collected / allows',NULL,'Active participial (comprising) + passive participial (collected) = pair of non-defining modifiers.','hard'),

  -- BLOCK 54: NDRCs em argumentação acadêmica avançada
  (cid,54,189,'gap_fill','The theoretical model proposed by X (2018), _____ (which) _____ (have) _____ (subsequently/test/passive) in multiple contexts, _____ (provide) the analytical framework for the current study.','which has been subsequently tested / which has since been tested / provides',NULL,'''which has been subsequently tested'' = NDRC with PP passive providing background on the model.','hard'),
  (cid,54,190,'gap_fill','The commission''s recommendations, _____ of _____ _____ (implement/passive) within the first year, _____ (include) measures to _____ (reform) both the regulatory framework and _____ oversight mechanisms.','several / which / were implemented / included / reform / the',NULL,'''Several of which were implemented'' = quantifier NDRC in non-defining position.','hard'),
  (cid,54,191,'multiple_choice','In academic writing, what is the key difference between defining and non-defining relative clauses?','Defining clauses restrict the meaning of the noun (no commas); non-defining clauses add extra information (commas required).','[''Defining clauses use who; non-defining use which'',''Defining clauses add extra information; non-defining clauses restrict meaning'',''Defining clauses restrict the meaning of the noun (no commas); non-defining clauses add extra information (commas required).'',''Non-defining clauses are only used in speech'']','Defining: no commas, ''that'' or ''which'' acceptable, restricts reference. Non-defining: commas, ''which'' only (not ''that''), adds parenthetical info.','easy'),
  (cid,54,192,'gap_fill','The government''s austerity program, _____ (initially/welcome/passive) by international creditors, _____ (prove) deeply unpopular domestically, _____ (lead) to a wave of protests that _____ (ultimately/force) significant modifications.','initially welcomed / proved / leading / ultimately forced',NULL,'Participial NDRC (initially welcomed) + main verb + participial result (leading) + relative clause (that forced).','hard'),

  -- BLOCK 55: TOEFL Reading avançado com NDRCs
  (cid,55,193,'multiple_choice','[TOEFL Reading] ''Carbon taxes, which have been implemented in over forty jurisdictions, have produced mixed results.'' The non-defining clause ''which have been implemented in over forty jurisdictions'' provides:','Additional contextual information about carbon taxes without restricting which carbon taxes are being discussed.','[''A definition of what carbon taxes are'',''Additional contextual information about carbon taxes without restricting which carbon taxes are being discussed.'',''A reason why carbon taxes produce mixed results'',''A condition under which carbon taxes work'']','NDRC adds extra information. No commas needed for identifying carbon taxes — they are already uniquely identifiable.','easy'),
  (cid,55,194,'gap_fill','[TOEFL Reading] ''The study, _____ (conduct/passive) over a period of fifteen years and _____ (involve) a cohort of 10,000 participants, provides the strongest longitudinal evidence yet available.'' Best forms?','conducted / involving',NULL,'Passive participial NDRC (conducted) + active participial NDRC (involving) = pair of non-defining phrases.','medium'),
  (cid,55,195,'multiple_choice','[TOEFL Reading] ''The researchers proposed a new model, which was immediately contested by other experts in the field.'' What does ''which'' refer to?','The act of proposing a new model (the entire preceding proposition).','[''The word ''model'''',''The word ''researchers'''',''The act of proposing a new model (the entire preceding proposition).'',''The ''field'''']','''Which'' in this sentence = sentence relative clause referring to the entire proposition (proposal of model + immediate contestation).','hard'),

  -- BLOCK 56: TOEFL Speaking avançado
  (cid,56,196,'production','[TOEFL Speaking — 45s] A reading describes a new economic theory. Use non-defining relative clauses throughout your summary.','',NULL,'The reading describes a new economic theory, which challenges several assumptions that have dominated mainstream economics since the 1970s. The theory, developed by a team of researchers at three leading universities, argues that the conventional model of labor markets, which treats wages as determined by marginal productivity, fails to account for the significant bargaining power disparities that characterize most real-world employer-employee relationships. The reading presents evidence, collected from a decade-long study of wage dynamics across multiple industries, which suggests that minimum wage increases do not reduce employment at the levels observed historically — a finding that contradicts the standard model''s most prominent prediction. The theory, which has attracted both significant attention and considerable controversy, proposes that labor markets are better understood as monopsonistic, with employers possessing more market power than competitive models assume. The reading concludes that policy interventions, including stronger collective bargaining rights and minimum wage legislation, are more likely to improve both efficiency and equity than the conventional model would predict.','hard'),
  (cid,56,197,'production','[TOEFL Speaking — 45s] Discuss governance challenges in developing countries. Use non-defining relative clauses and participial phrases throughout.','',NULL,'Developing countries face governance challenges that are shaped by the distinctive institutional contexts in which these states operate, contexts which differ profoundly from those in which the institutions of successful developed-country governance emerged. Many developing countries, having inherited administrative structures designed for colonial extraction rather than public service delivery, face the challenge of building effective state capacity without the century-long institutional learning processes that established the bureaucratic norms of wealthier countries. Patronage politics, which distributes public resources on the basis of political loyalty rather than merit or need, undermines both the efficiency and the equity of public service systems. Civil society organizations, which provide accountability mechanisms that are often more effective than formal oversight bodies in contexts where those bodies are captured by political interests, remain underfunded and sometimes legally constrained. International governance reform, which requires both technical advice and sustained financial support matched to recipient country priorities, has produced uneven results — producing genuine improvements in some contexts while failing to take root in others, which suggests that the conditions under which external support contributes to governance improvement remain poorly understood.','hard'),

  -- BLOCK 57: TOEFL Writing avançado
  (cid,57,198,'production','[TOEFL Writing — 200 words] Write a paragraph on intellectual property in the digital age using non-defining relative clauses throughout.','',NULL,'Intellectual property law, which was developed primarily in the nineteenth and twentieth centuries to govern the creation and distribution of physical goods and printed works, has struggled to adapt to the realities of the digital economy, in which copying and distribution have become essentially costless. Copyright law, which in many jurisdictions extends protection for the life of the creator plus seventy years, was originally designed to provide a time-limited monopoly sufficient to incentivize creative production; critics argue, however, that these terms, which have been extended repeatedly since the original Berne Convention, now serve primarily to lock up cultural content rather than to encourage new creation. Patent law, which has expanded over recent decades to cover software and business methods in some jurisdictions, has generated significant controversy, with critics arguing that overly broad patents — which can be granted for ideas that are insufficiently novel — create barriers to innovation rather than incentives for it. Open-source software, which has demonstrated that highly complex and economically valuable technology can be produced without proprietary intellectual property protection, suggests that the relationship between intellectual property rights and innovation is more complex than the standard economic justification for intellectual property implies. Reform of the intellectual property system, which has become a significant battleground in international trade negotiations, requires balancing the legitimate interests of creators with the public interest in a rich and accessible commons of knowledge and culture.','hard'),
  (cid,57,199,'production','[TOEFL Writing — 200 words] Write a paragraph on migration and development. Use non-defining relative clauses and participial NDRCs throughout.','',NULL,'The relationship between migration and development is one of the most complex in international political economy, involving dynamics that operate simultaneously at the level of individual households, sending and receiving communities, and national economies. Remittances, which represent flows of money sent by migrants to their families in countries of origin, have become one of the largest and most stable sources of external finance for many developing countries, exceeding official development assistance in volume and proving more countercyclical than private capital flows. The communities of origin, enriched by remittances and transformed by the return of migrants bringing new skills and broader networks, often experience significant economic development — a process which, however, is geographically concentrated and may exacerbate inequality between areas with high emigration rates and those with lower rates. Brain drain, which describes the emigration of highly skilled workers from countries that have invested in their education, represents a potentially significant cost to sending countries, though the evidence on net effects is more mixed than the simple brain drain narrative suggests. Diaspora networks, connecting migrants with their countries of origin and facilitating investment, trade, and knowledge transfer, represent a potentially powerful development resource whose significance has been increasingly recognized in development policy, though effective mechanisms for mobilizing diaspora contributions remain underdeveloped.','hard'),

  -- BLOCK 58: Final
  (cid,58,200,'production','[TOEFL Writing — 200 words] Write a paragraph on global health governance using NDRCs throughout.','',NULL,'Global health governance, which has evolved significantly since the founding of the World Health Organization in 1948, reflects both the achievements and the limitations of post-war multilateralism. The WHO, which serves as the lead United Nations agency for health, has played an important coordinating role in global disease surveillance and response, supporting the eradication of smallpox and the near-elimination of polio — achievements which stand as perhaps the greatest successes of international collective action in any domain. However, the COVID-19 pandemic, which revealed serious gaps in the international community''s capacity to detect, report, and respond to emerging infectious diseases, exposed the structural vulnerabilities of the global health architecture. The pandemic preparedness frameworks that existed prior to the pandemic, which many assumed provided adequate protection against novel pathogens, proved insufficient to prevent the rapid global spread of SARS-CoV-2 — an outcome which triggered a substantial reform effort, including negotiations toward a new pandemic treaty. Vaccine equity, which proved deeply inadequate during COVID-19 with wealthy countries securing the vast majority of initial doses while lower-income countries waited months or years, has become a central focus of reform discussions. The reform process, which involves complex negotiations among countries with very different institutional interests and perspectives on sovereignty over health policy, is proceeding slowly, which underscores the difficulty of building the more capable and equitable global health governance architecture that the evidence demands.','hard'),
  (cid,58,201,'production','[TOEFL Speaking — 60s] Discuss changes in the nature of work. Use non-defining relative clauses extensively.','',NULL,'The nature of work, which has been shaped by successive waves of technological change throughout human history, is undergoing a transformation in the current period that appears qualitatively different in important respects from previous transitions. Automation, which has displaced agricultural and industrial workers in previous eras, is now extending into cognitive tasks — legal research, medical diagnosis, financial analysis — which were previously considered safely within the exclusive domain of human expertise. Gig economy platforms, which connect workers to tasks through digital intermediaries rather than employment relationships, have grown rapidly and now employ significant numbers of workers in many countries; these workers, who typically lack the social protections associated with standard employment, have become the focus of important policy debates about the appropriate regulatory frameworks for platform labor. Remote work, which expanded dramatically during the COVID-19 pandemic and has persisted in hybrid forms in many organizations, has altered the geography of work in ways whose long-term consequences for cities, commuting patterns, and organizational culture are not yet fully apparent. The social contract that historically linked employment to social insurance, career development, and a degree of economic security has been substantially eroded, which presents a significant governance challenge: how to maintain broadly shared prosperity in an economy in which the returns to labor are increasingly concentrated among those with the skills and capital to capture the gains from new technologies. This challenge, which is simultaneously economic, political, and institutional, has no easy answer — but addressing it is essential if the benefits of technological change are to be broadly shared.','hard'),
  (cid,58,202,'production','[TOEFL Writing — Final 200 words] Write a conclusion on nuclear non-proliferation using non-defining relative clauses throughout.','',NULL,'This essay has argued that the nuclear non-proliferation regime, which has prevented the spread of nuclear weapons to most of the countries that have sought to acquire them over the past half century, represents a significant but increasingly fragile achievement. The Non-Proliferation Treaty, which entered into force in 1970 and has been signed by 191 states, rests on a bargain — between the nuclear weapon states, which committed to eventual disarmament, and the non-nuclear states, which agreed not to acquire nuclear weapons — that has been progressively eroded by the failure of the nuclear weapon states to honor the disarmament commitment. The development of nuclear weapons by India, Pakistan, and North Korea, each of which pursued acquisition outside the NPT framework, and the uncertain status of Iran''s nuclear program, which has been the subject of intensive international scrutiny and negotiation, underscore the limits of the regime''s reach. The most significant threat to the regime, however, may be internal: the modernization programs of the major nuclear powers, which involve sustained investment in new weapons and delivery systems, communicate a commitment to nuclear deterrence that contradicts the disarmament obligation and provides a rationale for aspiring nuclear states to resist non-proliferation pressure. Strengthening the regime requires the nuclear weapon states to make credible disarmament progress — an objective which requires political will that, at present, appears to be diminishing rather than growing among the states most capable of providing it.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
