-- ============================================================
-- SEED EXT 4: Módulo 20 — Academic Connectors (ex 188-267)
-- Novos tópicos: conectores de comparação, reformulação formal,
-- conectores no nível do texto (intertextual), TOEFL avançado
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'academic-connectors';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo academic-connectors não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 41: conectores de comparação e contraste avançados
  (cid,41,188,'gap_fill','In _____ (contrast) to the results obtained in Study 1, Study 2 found a statistically significant effect.','contrast',NULL,'"In contrast to + noun phrase" = formal academic comparison.','easy'),
  (cid,41,189,'multiple_choice','Which connector introduces a COMPARISON rather than a contrast?','Similarly, the second experiment confirmed the patterns observed in the first.','["However, the second experiment confirmed the patterns.","In contrast, the second experiment confirmed the patterns.","Similarly, the second experiment confirmed the patterns observed in the first.","Nevertheless, the second experiment confirmed the patterns."]','"Similarly" = introduces a comparison (same direction as previous point).','easy'),
  (cid,41,190,'gap_fill','The United States spends significantly more on healthcare per capita than other developed nations; _____ (by contrast), outcomes such as life expectancy and infant mortality rank below those of many peer countries.','by contrast',NULL,'"By contrast" = strong formal contrast connector.','medium'),
  (cid,41,191,'multiple_choice','Which pair of connectors CORRECTLY shows comparison and contrast respectively?','Likewise / whereas.','["However / similarly","Likewise / whereas.","In the same way / furthermore","Whereas / similarly"]','"Likewise" = comparison (same as). "Whereas" = contrast within a single sentence.','medium'),
  (cid,41,192,'gap_fill','Urban schools received additional funding; _____ (by the same token), rural schools were allocated equivalent resources on a per-student basis.','by the same token',NULL,'"By the same token" = similarly / by the same logic.','hard'),

  -- BLOCK 42: conectores de ênfase e escalada
  (cid,42,193,'gap_fill','The data were unreliable; _____ (indeed), several measurements exceeded what is physically possible.','indeed',NULL,'"Indeed" = strong emphatic confirmation or intensification of previous point.','medium'),
  (cid,42,194,'multiple_choice','Which connector adds an even STRONGER point after a surprising one?','The experiment was poorly designed; what is more, the data appear to have been selectively reported.','["The experiment was poorly designed; however, the data appear to have been selectively reported.","The experiment was poorly designed; in addition, the data appear to have been selectively reported.","The experiment was poorly designed; what is more, the data appear to have been selectively reported.","The experiment was poorly designed; consequently, the data appear selectively reported."]','"What is more" = escalation (stronger than ''furthermore'').','medium'),
  (cid,42,195,'gap_fill','Not only _____ (do) the findings contradict the hypothesis, but they also suggest a completely different causal mechanism.','do',NULL,'"Not only do + subject + verb" = fronted emphatic negative + auxiliary inversion.','hard'),
  (cid,42,196,'multiple_choice','In "Not only did the treatment reduce inflammation, but it also eliminated the primary symptoms entirely," what is the grammatical structure?','Not only + inverted auxiliary (did) + subject + verb, but also + additional clause.','["Standard additive sentence with moreover","Inverted conditional (Should + had)","Not only + inverted auxiliary (did) + subject + verb, but also + additional clause.","Relative clause with non-defining structure"]','"Not only + did + subject + verb / but also" = emphatic addition with fronted negative.','hard'),
  (cid,42,197,'gap_fill','The impact of the policy was substantial; _____ (above all), it succeeded in reducing child poverty by 15%.','above all',NULL,'"Above all" = introduces the most important or impressive point.','medium'),

  -- BLOCK 43: conectores de reformulação e aclaração formal
  (cid,43,198,'gap_fill','The intervention _____ (put it another way), it restructured the incentives rather than the behavior.','or, to put it another way,',NULL,'"To put it another way" = reformulation in simpler or different terms.','medium'),
  (cid,43,199,'multiple_choice','Which connector MOST precisely specifies a general category?','The study focuses on vulnerable groups — namely, refugees, undocumented migrants, and stateless persons.','["The study focuses on vulnerable groups, for example, refugees (also correct but less precise — for example doesn''t mean only these).","The study focuses on vulnerable groups, such as refugees, undocumented migrants, and stateless persons (also correct).","The study focuses on vulnerable groups — namely, refugees, undocumented migrants, and stateless persons.","The study focuses on vulnerable groups; that is, some groups."]','"Namely" = introduces the complete, precise list of what was referred to.','hard'),
  (cid,43,200,'gap_fill','The algorithm produced biased results — _____ (more specifically), it systematically underestimated risk scores for applicants from minority communities.','more specifically',NULL,'"More specifically" = narrows and sharpens the preceding general claim.','medium'),
  (cid,43,201,'multiple_choice','What is the difference between "in other words" and "to be more precise"?','"In other words" = restates for clarity; "to be more precise" = sharpens/narrows the claim.','["They are identical","''In other words'' = restates for clarity; ''to be more precise'' = sharpens/narrows the claim.","''To be more precise'' is always followed by a list","''In other words'' introduces a contrast"]','"In other words" = same content, clearer phrasing. "To be more precise" = adds specificity.','hard'),
  (cid,43,202,'gap_fill','The project was completed successfully _____ (in terms of) cost and timeline, though quality issues emerged in the final phase.','in terms of',NULL,'"In terms of + noun" = specifies the dimension of evaluation.','easy'),

  -- BLOCK 44: conectores no nível do texto (meta-connectors)
  (cid,44,203,'gap_fill','This study _____ (builds on) previous work by introducing a multi-dimensional framework for analysis.','builds on',NULL,'"Builds on" = academic connector showing cumulative progress on prior research.','medium'),
  (cid,44,204,'multiple_choice','Which phrase BEST signals the beginning of a counterargument in a TOEFL essay?','It could be argued, however, that...','["Furthermore, it is important that...","To begin with, some people think that...","It could be argued, however, that...","Therefore, this shows that..."]','"It could be argued, however, that" = formal academic counterargument signal.','medium'),
  (cid,44,205,'gap_fill','The preceding section established the theoretical context; _____ (the present section) turns to the empirical evidence.','the present section / this section / the following section',NULL,'Text-organizing connector: "the present/following section turns to."','easy'),
  (cid,44,206,'multiple_choice','Which sentence uses a meta-connector to signal the paper''s LIMITATION?','This study is, however, limited in scope: it examines only one region over a ten-year period.','["This study examines one region over a ten-year period.","This study is, however, limited in scope: it examines only one region over a ten-year period.","This study examines one region; furthermore, it covers ten years.","This study will examine one region over a ten-year period."]','"Limited in scope" + "only" = limitation signal with meta-connector "however" for pivot.','medium'),
  (cid,44,207,'gap_fill','_____ (As will be argued) in the following section, the relationship between these variables is more complex than previously assumed.','As will be argued / As the following section argues',NULL,'Forward-referencing meta-connector for academic text organization.','hard'),

  -- BLOCK 45: TOEFL Reading
  (cid,45,208,'multiple_choice','[TOEFL Reading] "Although correlation does not imply causation, the evidence is nonetheless compelling." What discourse function does "nonetheless" serve?','It concedes the methodological limitation while maintaining the argument''s force.','["It adds a new point","It introduces a contrast with no concession","It concedes the methodological limitation while maintaining the argument''s force.","It summarizes the paragraph"]','"Nonetheless" = concessive pivot: acknowledges limitation, then defends the claim.','medium'),
  (cid,45,209,'gap_fill','[TOEFL Reading] "The new treatment is effective; _____ (moreover), it has fewer side effects than existing alternatives." Best connector?','moreover / furthermore / what is more',NULL,'"Moreover/Furthermore" = additive with escalation (second point stronger).','easy'),
  (cid,45,210,'multiple_choice','[TOEFL Reading] "The author uses the phrase ''to put it simply'' to..." (paraphrase question)','Signal a reformulation of a technical concept in more accessible language.','["Introduce a contrasting argument","Dismiss the previous paragraph","Signal a reformulation of a technical concept in more accessible language.","Begin the conclusion"]','"To put it simply" = reformulation connector (clearer restatement follows).','easy'),
  (cid,45,211,'gap_fill','[TOEFL Reading] "The findings not only confirm the original hypothesis _____ (but also) suggest a previously unconsidered mechanism." Best connector?','but also',NULL,'"Not only... but also" = emphatic additive structure.','easy'),

  -- BLOCK 46: TOEFL Speaking
  (cid,46,212,'production','[TOEFL Speaking — 45s] A reading argues that economic growth is necessary for poverty reduction. A lecture argues that growth alone is insufficient. Connect both arguments using: however, moreover, by contrast, indeed, what is more, nonetheless, that said.','',NULL,'The reading presents a compelling macroeconomic case: economic growth generates employment and tax revenues that enable governments to fund public services and social transfers, thereby reducing poverty. Indeed, the historical record shows that sustained growth has lifted hundreds of millions out of poverty in East and Southeast Asia over the past four decades. The lecture, however, introduces an important qualification. Growth alone is insufficient — its distributional character determines whether poverty falls or remains entrenched. What is more, the lecture notes that growth models based on natural resource extraction have frequently produced wealth concentrated at the top while leaving the majority of the population no better off. By contrast, economies that have invested in education, healthcare, and rural infrastructure tend to achieve more broadly shared prosperity. That said, the professor acknowledges that without some degree of growth, the resources for redistribution are simply unavailable.','hard'),
  (cid,46,213,'production','[TOEFL Speaking — 45s] Summarize a reading about the psychological effects of social comparison. Use: as a result, in other words, more specifically, nonetheless, by contrast, above all.','',NULL,'The reading argues that social comparison — the tendency to evaluate oneself relative to others — has significant psychological effects, particularly in the age of social media. As a result of constant exposure to curated images of others'' achievements and lifestyles, many users report increased dissatisfaction with their own lives. In other words, comparison shifts the standard against which people measure their wellbeing from an internal to an external frame of reference. More specifically, research cited in the reading found that ''upward comparison'' — comparing oneself to people perceived as better off — was associated with depression and reduced self-esteem in 78% of cases. Nonetheless, the reading acknowledges that comparison can also motivate positive change. By contrast, ''downward comparison'' — measuring oneself against those perceived as worse off — consistently produced increased feelings of gratitude. Above all, the reading concludes, the key factor is whether comparison is used constructively or destructively.','hard'),

  -- BLOCK 47: TOEFL Writing
  (cid,47,214,'production','[TOEFL Writing — 150 words] Write an argumentative paragraph on global inequality using at least 8 distinct academic connectors from different functional categories: contrast, addition/escalation, exemplification, concession, result, comparison, reformulation, and text-organization.','',NULL,'Global inequality has widened significantly over the past four decades, driven by a convergence of technological change, tax policy, and the erosion of labor protections. Specifically, the wealth held by the richest one percent of the global population now exceeds that held by the remaining ninety-nine percent combined. This disparity is not, however, an inevitable feature of market economies: by contrast, several Nordic countries maintain dynamic market economies alongside relatively low levels of wealth concentration. Indeed, both economic efficiency and social cohesion can coexist, as the Scandinavian experience demonstrates. Moreover, high inequality is not merely an ethical problem — research suggests it reduces economic mobility, depresses consumer demand, and undermines democratic governance. Consequently, addressing wealth concentration requires coordinated international tax reform. To put it plainly, the tools exist to build more equitable economies; what has been lacking is the political will to deploy them.','hard'),
  (cid,47,215,'production','[TOEFL Writing — Error Correction] Fix connector errors: "The study was large; despite, it had limitations. However the results were positive, concerns remained. The findings were significant; by the same token, further research is needed (correct). Not only the study was flawed but it was also biased. The treatment was effective; above of all, it was affordable."','',NULL,'despite, it had limitations → despite this / despite having limitations / however, it had limitations (''despite'' needs noun/gerund, not clause alone); However the results were positive → Although the results were positive (''however'' = sentence connector, not subordinating conjunction); by the same token sentence = correct; Not only the study was flawed → Not only was the study flawed (fronted negative = inverted auxiliary: Not only + was + subject + adjective); above of all → above all (no preposition ''of'').','hard'),

  -- BLOCK 48: Consolidação avançada
  (cid,48,216,'production','[TOEFL Writing — 200 words] Write an essay body paragraph on "The responsibility of corporations in addressing climate change." Use at least 10 different academic connectors including: in particular, not only...but also, indeed, whereas, consequently, nevertheless, to the extent that, in terms of, by contrast, above all.','',NULL,'Corporations bear substantial responsibility for addressing climate change, not only because they are responsible for a significant proportion of global emissions, but also because they possess the capital, technology, and organizational capacity to drive the transition to low-carbon economic models at a scale that individual action cannot achieve. Indeed, it has been estimated that just one hundred companies are responsible for approximately 71 percent of global emissions — a concentration of cause that implies a corresponding concentration of responsibility. In terms of the tools available, corporations can restructure supply chains to reduce embodied carbon, invest in renewable energy, and redesign products to extend their useful life. Nevertheless, it would be naive to assume that voluntary corporate action will be sufficient: whereas some leading companies have set ambitious science-based targets, the majority have not. Consequently, binding regulation — including credible carbon pricing and mandatory disclosure of climate-related financial risk — is essential to drive system-wide transformation. To the extent that corporations continue to resist such frameworks through lobbying, they are effectively prioritizing short-term shareholder returns over long-term civilizational stability. Above all, the transition to a low-carbon economy requires that the full cost of carbon emissions be reflected in market prices.','hard'),
  (cid,48,217,'production','[TOEFL Writing — 200 words] Integrated paragraph: A reading argues that the arts should receive more government funding. A lecture argues that STEM education is a higher priority. Use academic connectors to fairly represent and synthesize both positions.','',NULL,'The reading and the lecture represent two positions in a longstanding policy debate about the appropriate allocation of educational resources. The reading contends that arts education develops critical thinking, empathy, and cultural competency — capacities that are, indeed, essential for a functioning democracy and for innovation in the creative industries. Moreover, the reading argues that public investment in the arts generates measurable economic returns through tourism, cultural exports, and the creative economy. The lecture, by contrast, focuses on the imperative of economic competitiveness: specifically, it argues that advanced industrial nations face acute shortages of qualified STEM graduates, whereas arts graduates face comparatively higher rates of unemployment. Consequently, the professor maintains, funding priorities should reflect the demonstrated needs of the labor market. That said, the lecture does not entirely dismiss the value of arts education; rather, it suggests that integration of arts with STEM — the so-called STEAM model — may represent a more productive framework than treating the two as competing priorities. In terms of policy design, this synthesis approach may offer the most pragmatic path forward, provided that adequate resources are allocated to both domains.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
