-- ============================================================
-- SEED EXT 4: Módulo 03 — Past Simple (ex 208-300)
-- Novos tópicos: PS em revisão de literatura, PS para eventos
-- únicos vs. habituais, PS em narrativa pessoal TOEFL
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'past-simple';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo past-simple não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 41: PS em revisão de literatura
  (cid,41,208,'gap_fill','Smith (2018) _____ (find) that participants _____ (perform) better under time pressure when given clear objectives.','found / performed',NULL,'Past simple in literature review when reporting specific past study results.','medium'),
  (cid,41,209,'multiple_choice','In a literature review, when is past simple preferred over present simple for reporting findings?','When the study is dated, potentially superseded, or when a specific time is referenced.','["Always — literature reviews always use past simple","When the study is dated, potentially superseded, or when a specific time is referenced.","Never — present simple is always preferred","Only when the authors are named"]','Past simple = specific past study. Present simple = still-valid general truth.','hard'),
  (cid,41,210,'gap_fill','A landmark study by Johnson et al. (2009) _____ (demonstrate) for the first time that epigenetic changes _____ (can/transmit/passive) across generations.','demonstrated / could be transmitted',NULL,'Past simple for describing what a specific past study showed.','hard'),
  (cid,41,211,'gap_fill','Early theories _____ (attribute) the observed effect entirely to genetic factors; subsequent research, however, _____ (reveal) the central role of environmental variables.','attributed / revealed',NULL,'Past simple for historical sequence in literature narrative.','medium'),
  (cid,41,212,'multiple_choice','Which sentence INCORRECTLY mixes tenses in a literature review?','Early researchers argued that motivation drives performance; Smith (2018) has confirmed this in a longitudinal study.','["Early researchers suggested that motivation drives performance (mixed: past claim, present general truth — acceptable).","A 2015 meta-analysis confirmed findings from six previous studies.","Early researchers argued that motivation drives performance; Smith (2018) has confirmed this in a longitudinal study.","Jones (2019) demonstrated that X, and Chen (2020) replicated these findings."]','"Has confirmed" with a specific year (2018) = error. Use "confirmed" (past simple) with dates.','hard'),

  -- BLOCK 42: PS para habitual past (used to / would + PS context)
  (cid,42,213,'gap_fill','Before automated data collection systems existed, researchers _____ (record) observations by hand in field notebooks.','recorded',NULL,'Past simple for past habitual practice that has since changed.','medium'),
  (cid,42,214,'multiple_choice','What is the difference between "Scientists used to believe X" and "Scientists believed X"?','"Used to believe" emphasizes contrast with now; "believed" is a neutral past report.','["They are identical","''Used to believe'' emphasizes contrast with now; ''believed'' is a neutral past report.","''Believed'' is more formal","''Used to'' cannot be used in academic writing"]','"Used to" = implies the belief has changed. "Believed" = neutral past statement.','hard'),
  (cid,42,215,'gap_fill','In the pre-digital era, information _____ (travel) slowly; it sometimes _____ (take) months for new scientific findings to reach researchers in other countries.','travelled / took',NULL,'Past simple for describing historical conditions that have since changed.','medium'),
  (cid,42,216,'multiple_choice','Which sentence uses past simple to describe a PAST HABIT (not a single completed event)?','Nineteenth-century physicians routinely prescribed mercury compounds as treatment for a range of ailments.','["A physician prescribed mercury for a patient in 1850 (single event).","Nineteenth-century physicians routinely prescribed mercury compounds as treatment for a range of ailments.","The physician prescribed mercury yesterday (specific past event).","Physicians have prescribed mercury for centuries (ongoing link to present)."]','"Routinely prescribed" = past simple for habitual professional practice in the past.','medium'),

  -- BLOCK 43: PS em narrativa pessoal (TOEFL Speaking tasks)
  (cid,43,217,'production','[TOEFL Speaking preparation] Write a past simple narrative of a challenging academic experience. Use: past simple (active + passive), irregular verbs (found/led/taught/chose/took/rose), time sequencers (first / then / finally / by the end of).','',NULL,'My most challenging academic experience came during my second year of university, when I enrolled in a course that combined advanced mathematics with computational modeling. At first, I struggled significantly — the material moved faster than anything I had previously encountered, and I found the programming assignments particularly daunting. I chose to work with a study group that met three times a week, and together we worked through each problem set systematically. By the end of the semester, my understanding of the material rose considerably, and I taught myself three programming languages along the way. The course ultimately led me to change my major entirely.','medium'),
  (cid,43,218,'gap_fill','First, the researchers _____ (gather) baseline data. Then, they _____ (divide/passive) participants into two groups. Finally, the intervention _____ (apply/passive) over a twelve-week period.','gathered / were divided / was applied',NULL,'Past simple sequence in methods (active + passive).','medium'),
  (cid,43,219,'multiple_choice','Which sentence uses past simple MOST appropriately in a personal TOEFL narrative?','When I realized I had been misunderstanding the assignment, I immediately spoke with my professor and she helped me reorganize my approach.','["When I realize I had been misunderstanding the assignment, I immediately speak with my professor.","When I realized I had been misunderstanding the assignment, I immediately spoke with my professor and she helped me reorganize my approach.","When I realized I had been misunderstanding the assignment, I immediately was speaking with my professor.","When I have realized the assignment issue, I spoke with my professor."]','Past simple for completed sequence of past actions in narrative.','medium'),

  -- BLOCK 44: PS em gêneros formais — cartas, relatórios, atas
  (cid,44,220,'gap_fill','The meeting _____ (commence) at 09:00 and _____ (adjourn) at 11:30 after all agenda items _____ (address/passive).','commenced / adjourned / were addressed',NULL,'Past simple in formal meeting minutes.','medium'),
  (cid,44,221,'multiple_choice','Which sentence is most appropriate in a formal incident report (past simple)?','At approximately 14:00 on 12 June, a water main ruptured in the basement of Building B, causing significant flooding.','["A water main ruptures in Building B on June 12.","At approximately 14:00 on 12 June, a water main ruptured in the basement of Building B, causing significant flooding.","A water main has ruptured in Building B on June 12.","A water main was rupturing in Building B on June 12."]','Incident reports use past simple for completed events with specific times.','medium'),
  (cid,44,222,'gap_fill','The audit _____ (reveal) several inconsistencies in the financial records that _____ (date) back to the previous fiscal year.','revealed / dated',NULL,'Past simple in audit/formal business report.','easy'),
  (cid,44,223,'gap_fill','Participants _____ (complete) a validated questionnaire and _____ (provide) written consent before the study commenced.','completed / provided',NULL,'Past simple in ethics/methods report for completed procedures.','easy'),

  -- BLOCK 45: TOEFL Reading — PS em textos históricos
  (cid,45,224,'multiple_choice','[TOEFL Reading] "The printing press transformed European society in the fifteenth century by democratizing access to written knowledge." Why past simple?','The transformation is a completed, time-anchored historical event.','["The transformation is still ongoing","The author is speculating","The transformation is a completed, time-anchored historical event.","The printing press is recent history"]','Specific century (15th) + completed impact = past simple.','easy'),
  (cid,45,225,'gap_fill','[TOEFL Reading] "Watson and Crick _____ (propose) the double helix structure of DNA in 1953, drawing on X-ray crystallography data that Franklin and Wilkins _____ (produce)." Best forms?','proposed / had produced',NULL,'Past simple for main event + past perfect for prior action.','hard'),
  (cid,45,226,'multiple_choice','[TOEFL Reading] "Throughout the nineteenth century, urban populations grew rapidly as rural workers migrated to industrializing cities." "Grew" and "migrated" are past simple because:','They describe processes completed within a defined historical period.','["They express past habits","They follow ''as'' which requires past simple","They describe processes completed within a defined historical period.","They are irregular verbs"]','Past simple for historical trends within a specified completed timeframe.','medium'),
  (cid,45,227,'gap_fill','[TOEFL Reading] "The earthquake _____ (strike) without warning and _____ (destroy) large portions of the city''s infrastructure within minutes." Best forms?','struck / destroyed',NULL,'Irregular past simple for sudden, completed historical event.','easy'),

  -- BLOCK 46: TOEFL Speaking
  (cid,46,228,'production','[TOEFL Speaking — 45s] Describe a significant historical event and its consequences. Use past simple (active + passive), irregular verbs, and time markers.','',NULL,'The 1969 Apollo 11 moon landing stands as one of the defining achievements of the twentieth century. In July of that year, three astronauts departed from Kennedy Space Center in Florida aboard the Saturn V rocket. After a four-day journey, the lunar module descended and landed on the Sea of Tranquility. Neil Armstrong stepped onto the lunar surface first, followed by Buzz Aldrin, while Michael Collins orbited above. The mission was watched by an estimated 600 million people worldwide. The landing demonstrated the extraordinary potential of human engineering and inspired a generation of scientists and engineers. It also marked the defining moment in the Space Race, making clear that the United States had surpassed the Soviet Union in the competition to reach the moon.','hard'),
  (cid,46,229,'production','[TOEFL Speaking — 45s] A reading discusses the causes of World War I. Summarize using past simple and past perfect.','',NULL,'The reading argues that World War I resulted from an interlocking system of alliances, nationalist ambitions, and imperial rivalries that had developed over several decades before the war broke out in 1914. When Archduke Franz Ferdinand was assassinated in Sarajevo in June 1914, the event triggered a cascade of military mobilizations that the great powers had obligated themselves to through treaty commitments. Germany declared war on Russia, then France; Britain entered after Germany violated Belgian neutrality. The reading suggests that while the assassination provided the immediate spark, the deeper structural causes — militarism, colonial competition, and the alliance system — had already made a major European conflict virtually inevitable.','hard'),

  -- BLOCK 47: TOEFL Writing
  (cid,47,230,'production','[TOEFL Writing — 150 words] Write an academic paragraph about the Industrial Revolution''s impact on working conditions. Use: past simple (active ×4, passive ×3), irregular verbs (fell/rose/led/drove/grew), time expressions (by the mid-19th century / throughout / in the early decades of).','',NULL,'The Industrial Revolution transformed the nature of work for millions of people across Britain and, later, across much of the world. In the early decades of industrialization, factory owners drove laborers to work shifts of fourteen hours or more in conditions that were dangerous and poorly regulated. Child labor was common; children as young as eight worked alongside adults in mines and mills. Throughout the first half of the nineteenth century, wages for industrial workers fell in real terms even as industrial output grew dramatically. By the mid-nineteenth century, however, labor movements began to organize, and the first protective legislation was passed in Britain. Working hours were gradually reduced, safety requirements were introduced, and child labor was progressively restricted. These reforms were won through sustained political pressure and were supported by the moral arguments of reformers such as Charles Dickens and Robert Owen.','hard'),
  (cid,47,231,'production','[TOEFL Writing — Error Correction] Fix past simple errors: "Watson and Crick have proposed the double helix in 1953. The researchers were conducting the survey last summer. The study has found significant correlations (no specific time given — also acceptable as ''found''). The company go public in 2015. The participants completed the questionnaire and they signed the consent form (correct — no fix needed)."','',NULL,'have proposed → proposed (specific year 1953 forces past simple); were conducting → conducted (last summer = specific completed timeframe → past simple, not continuous for general description); ''has found'' with no specific time is acceptable as present perfect — no fix needed or optionally ''found'' is also fine; go → went (past simple irregular: go → went); the final sentence is correct.','hard'),

  -- BLOCK 48: Consolidação avançada
  (cid,48,232,'production','[TOEFL Writing — 200 words] Write a body paragraph about the effects of colonialism on indigenous education systems. Use past simple active, passive, irregular verbs, and academic hedging in the past.','',NULL,'European colonial powers systematically dismantled indigenous education systems throughout the nineteenth and early twentieth centuries, replacing them with schools designed to assimilate native populations into European cultural norms. In many colonized territories, governments prohibited the use of indigenous languages in formal education and punished children who spoke their mother tongue in school. These policies, enforced through a combination of legal coercion and physical punishment, drove a profound rupture between generations: elders who held traditional knowledge often found themselves unable to communicate this knowledge to children educated in colonial schools. Indigenous oral traditions, agricultural techniques, and ecological knowledge systems were devalued, marginalized, and in some cases permanently lost. The consequences proved lasting: postcolonial nations inherited educational systems that were poorly adapted to local contexts and that frequently perpetuated the hierarchies of the colonial period rather than dismantling them. Historians now argue that the full costs of these policies — in terms of cultural loss, psychological harm, and social fragmentation — were substantially underestimated by the administrators who designed and implemented them.','hard'),
  (cid,48,233,'production','[TOEFL Writing — 200 words] Write an essay body paragraph on "The causes of the 2008 financial crisis." Use: past simple throughout, passive past (were created / were sold / were not regulated), irregular verbs (grew / fell / rose / swept / froze), and causal connectors.','',NULL,'The 2008 global financial crisis arose from a dangerous accumulation of unregulated risk within the financial system. Throughout the early 2000s, mortgage lenders extended credit to borrowers who lacked the income or assets to service their loans under adverse conditions. These mortgages were packaged into complex financial instruments — collateralized debt obligations — and were sold to investors worldwide as low-risk assets, despite containing significant embedded risk that rating agencies systematically underestimated. As housing prices rose rapidly and then plateaued, default rates among subprime borrowers climbed sharply. When the US housing bubble deflated in 2007, the value of mortgage-backed securities fell dramatically, and the resulting losses spread quickly through the banking system. Credit markets froze almost overnight in September 2008 as trust between financial institutions collapsed. Governments were consequently forced to intervene with unprecedented quantities of public funds to prevent systemic bank failure. The crisis swept across global markets and drove the world economy into the deepest recession since the 1930s.','hard'),
  (cid,48,234,'gap_fill','The committee _____ (review) all submitted applications, _____ (shortlist) twelve candidates, and _____ (invite) them for interview in March.','reviewed / shortlisted / invited',NULL,'Past simple sequence in formal procedural account.','easy'),
  (cid,48,235,'multiple_choice','Which sentence shows CORRECT tense choice distinguishing a specific past event from a general truth?','Semmelweis discovered that handwashing reduces infection; he published his findings in 1861.','["Semmelweis discovered that handwashing reduced infection; he published his findings in 1861.","Semmelweis discovers that handwashing reduces infection; he published his findings in 1861.","Semmelweis discovered that handwashing reduces infection; he published his findings in 1861.","Semmelweis has discovered that handwashing reduces infection; he publishes his findings in 1861."]','Past simple for discovery event + present simple for the enduring scientific truth.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
