-- ============================================================
-- SEED EXT 3: Módulo 05 — Future Simple (ex 110-205)
-- Novos tópicos: future perfect, future continuous, futures
-- para previsões científicas, will vs be going to vs present
-- continuous — revisão completa, TOEFL
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'future-simple';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo future-simple não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 31: future perfect (will have + past participle)
  (cid,31,110,'gap_fill','By 2050, global temperatures _____ (rise) by at least 1.5°C above pre-industrial levels, according to current projections.','will have risen',NULL,'"Will have + past participle" = future perfect for completion before a future point.','hard'),
  (cid,31,111,'multiple_choice','Which sentence uses future perfect correctly?','By the time the study is published, the team will have been working on it for three years.','["By the time the study is published, the team works on it for three years.","By the time the study is published, the team will have been working on it for three years.","By the time the study is published, the team has worked on it for three years.","By the time the study is published, the team will work on it for three years."]','Future perfect (will have + past participle) or future perfect continuous (will have been + -ing) before a future deadline.','hard'),
  (cid,31,112,'gap_fill','The conference _____ (end) by the time you arrive — you should book an earlier flight.','will have ended',NULL,'"Will have ended" = future perfect for completion before another future event.','hard'),
  (cid,31,113,'multiple_choice','What does "will have done" express?','An action completed before a specific point in the future.','["An ongoing action in the future","An action completed before a specific point in the future.","A past action viewed from the present","A conditional outcome"]','Future perfect = future completion (before a deadline or reference point).','medium'),
  (cid,31,114,'gap_fill','By the time the next generation enters the workforce, AI _____ (transform/passive) most knowledge industries.','will have transformed / will have been transformed',NULL,'Future perfect active or passive for transformation before a future generational point.','hard'),

  -- BLOCK 32: future continuous (will be + -ing)
  (cid,32,115,'gap_fill','This time next year, she _____ (present) her findings at the International Linguistics Conference.','will be presenting',NULL,'"Will be + -ing" = future continuous. Ongoing action at a specific future time.','medium'),
  (cid,32,116,'multiple_choice','Which sentence uses future continuous correctly?','The team will be running three separate trials simultaneously throughout the spring.','["The team will run three separate trials simultaneously throughout spring.","The team will be running three separate trials simultaneously throughout the spring.","The team is running three separate trials simultaneously next spring.","The team runs three separate trials simultaneously throughout spring."]','"Will be + -ing" for an ongoing activity across a future time span.','medium'),
  (cid,32,117,'gap_fill','At this time tomorrow, the participants _____ (complete) the final questionnaire.','will be completing',NULL,'Future continuous for an activity in progress at a specific future moment.','medium'),
  (cid,32,118,'multiple_choice','What is the difference: "I''ll call you" vs "I''ll be calling you"?','"I''ll call" = a specific decision/promise; "I''ll be calling" = an action already planned that happens to occur (no special effort implied).','["They are identical","''I''ll call'' is more formal","''I''ll call'' = a specific decision/promise; ''I''ll be calling'' = an action already planned that happens to occur (no special effort implied).","''I''ll be calling'' implies annoyance"]','Future simple = decision/promise. Future continuous = planned ongoing action, politer request implication.','hard'),

  -- BLOCK 33: future perfect continuous
  (cid,33,119,'gap_fill','By 2030, scientists _____ (study) the effects of microplastics on human health for over two decades.','will have been studying',NULL,'"Will have been + -ing" = future perfect continuous. Duration up to a future point.','hard'),
  (cid,33,120,'multiple_choice','What does "will have been working" express?','An action that will have been ongoing up to a specific future point, emphasizing duration.','["A future completed action","A conditional","An action that will have been ongoing up to a specific future point, emphasizing duration.","A past action"]','Future perfect continuous = future duration emphasized (up to a reference point).','hard'),
  (cid,33,121,'gap_fill','When this project ends, the team _____ (collaborate/continuous) for over ten years.','will have been collaborating',NULL,'"Will have been + -ing" for duration of an ongoing collaboration up to a future endpoint.','hard'),

  -- BLOCK 34: revisão — all future forms compared
  (cid,34,122,'multiple_choice','Which future form is MOST appropriate? "The shuttle ___ at 9 a.m. tomorrow." (scheduled departure)','departs','["will depart (also correct — strong prediction)","is departing","departs (scheduled timetable — present simple for future).","is going to depart"]','Timetable schedules = present simple for the future.','medium'),
  (cid,34,123,'gap_fill','Look at those dark clouds! It _____ (rain). (evidence-based prediction — going to)','is going to rain',NULL,'"Is going to + base verb" = prediction based on visible present evidence.','easy'),
  (cid,34,124,'multiple_choice','Which sentence uses the WRONG future form?','We are going to have dinner at 8 — it''s on my calendar. (should use present continuous)','["We will probably have dinner at a restaurant nearby (prediction with probably — will correct).","We are having dinner with the team at 8 — it''s booked (present continuous for arrangement — correct).","We are going to have dinner at 8 — it''s on my calendar. (should use present continuous)","It will rain tomorrow, according to the forecast (prediction — will correct)."]','Calendar-booked arrangements = present continuous (not going to for personal plans).','hard'),
  (cid,34,125,'gap_fill','By the time the data analysis is complete, the team _____ (spend) over 500 hours on this project.','will have spent',NULL,'Future perfect for a quantified duration that will be complete by a future milestone.','hard'),
  (cid,34,126,'multiple_choice','Academic writing: which future form is most formal and impersonal?','Passive will: "It is anticipated that global demand will increase by 30% by 2030."','["Going to: it''s going to be a major breakthrough","Present continuous: we''re presenting the findings next week","Passive will: ''It is anticipated that global demand will increase by 30% by 2030.''","I think it''ll work out"]','Passive will + anticipate/expect/project = formal academic/scientific future expression.','hard'),

  -- BLOCK 35: futures em textos científicos e acadêmicos
  (cid,35,127,'gap_fill','Further research _____ (require/passive) to establish the long-term efficacy of this treatment.','will be required',NULL,'"Will be required" = passive will for future necessity in academic writing.','medium'),
  (cid,35,128,'multiple_choice','Which sentence is MOST appropriate in the conclusion of a TOEFL essay?','This analysis suggests that renewable energy investment will continue to grow as costs decline.','["I think renewable energy will get bigger.","Renewable energy is going to grow (informal prediction).","This analysis suggests that renewable energy investment will continue to grow as costs decline.","Renewable energy definitely grows in the future."]','"Will + base verb" with hedging verb (suggests) = formal prediction in conclusion.','hard'),
  (cid,35,129,'gap_fill','By 2050, it is estimated that the global population _____ (reach) approximately 9.7 billion.','will have reached',NULL,'"Will have reached" = future perfect for completion by a specific future date.','hard'),
  (cid,35,130,'multiple_choice','In an academic projection, which phrasing is most appropriate?','Sea levels are projected to rise by between 0.3 and 1 meter by 2100.','["Sea levels will definitely rise a lot.","Sea levels are projected to rise by between 0.3 and 1 meter by 2100.","Sea levels are going to rise a lot by 2100.","Sea levels rise by between 0.3 and 1 meter by 2100 (wrong tense for future projection)."]','Passive + to + infinitive (are projected to rise) = hedged formal future projection.','hard'),
  (cid,35,131,'gap_fill','The results of this study _____ (present/passive) at the annual conference next spring.','will be presented',NULL,'"Will be presented" = passive will for planned future event.','medium'),

  -- BLOCK 36: TOEFL Reading
  (cid,36,132,'multiple_choice','[TOEFL Reading] "Scientists predict that by 2100, species extinction rates will have increased tenfold." The future perfect here indicates:','The increase will be complete/cumulative by the year 2100.','["Species are already extinct","The increase is happening now","The increase will be complete/cumulative by the year 2100.","Scientists made this prediction in 2100"]','Future perfect = completion by a future reference point.','easy'),
  (cid,36,133,'gap_fill','[TOEFL Reading] "If current trends continue, the Arctic _____ (be) ice-free in summer within the next three decades." Best form?','will be / will have become',NULL,'"Will be" = future state prediction. "Will have become ice-free" = future perfect for completion.','medium'),
  (cid,36,134,'multiple_choice','[TOEFL Reading] "It is anticipated that advances in gene therapy will transform treatment of hereditary diseases within this decade." "It is anticipated that" is:','A formal passive construction hedging a future prediction.','["A present perfect construction","A formal passive construction hedging a future prediction.","A conditional clause","A reported speech construction"]','"It is anticipated that + will" = formal passive future prediction in academic writing.','medium'),
  (cid,36,135,'gap_fill','[TOEFL Reading] "By the time a viable commercial fusion reactor is operational, engineers _____ (work) on the technology for over a century." Best form?','will have been working',NULL,'Future perfect continuous for an ongoing process that will reach a duration milestone.','hard'),

  -- BLOCK 37: TOEFL Speaking
  (cid,37,136,'production','[TOEFL Speaking — 45s] A reading says artificial intelligence will replace most jobs within 50 years. Agree or disagree. Use: will, going to, will have, will be doing, is projected to.','',NULL,'While AI is certainly going to automate many routine tasks, I believe it will also create new categories of work we cannot yet predict. By 2075, the nature of employment will have changed dramatically, but skilled workers will be adapting continuously alongside the technology. New industries are projected to emerge around AI oversight, ethics, and human-AI collaboration. Rather than mass unemployment, we are more likely to see a profound restructuring of the labor market.','hard'),
  (cid,37,137,'production','[TOEFL Speaking — 45s] Describe the future of urban transportation. Use all 5 future forms: present simple (schedule), going to, will, future continuous, future perfect.','',NULL,'The next Urban Transport Summit opens next March, where city planners are going to announce major new investment in autonomous vehicle infrastructure. Self-driving buses will replace most existing fleet within a decade. By 2040, electric autonomous vehicles will have reduced urban carbon emissions by over 60%. Meanwhile, new generations of high-speed rail will be connecting cities that currently have no direct rail links. Traditional car ownership will likely decline sharply as shared mobility services become more reliable and affordable.','hard'),

  -- BLOCK 38: TOEFL Writing
  (cid,38,138,'production','[TOEFL Writing — 150 words] Write an academic paragraph predicting the future of higher education. Use: will (prediction), will have (future perfect), will be doing (future continuous), is projected to, it is anticipated that. Include at least one passive future form.','',NULL,'Higher education will undergo profound transformation over the coming decades as digital technologies reshape how knowledge is created and transmitted. By 2050, a significant proportion of university courses will have migrated to hybrid or fully online formats, reducing the need for large physical campuses. It is anticipated that artificial intelligence will be personalizing learning experiences for individual students in real time, adapting pace and content to each learner''s profile. Institutions that fail to innovate are projected to face declining enrollment and financial pressure. Conversely, universities that successfully integrate technology while preserving the intellectual community and mentorship that define higher education will be positioned as the most competitive in the global market. The academic credentials valued by employers will also have shifted significantly, with demonstrated competencies potentially supplementing or even replacing traditional degree qualifications.','hard'),
  (cid,38,139,'production','[TOEFL Writing — Error Correction] Fix future tense errors: "By 2030, the climate will be warmed by 1.5°C. Scientists will studying this for decades before a solution emerges. The conference will had ended by the time you arrive. It is expects that demand will increase."','',NULL,'will be warmed → will have warmed (future perfect for completion by 2030) OR will have risen by 1.5°C; will studying → will be studying (future continuous = will + be + -ing); will had ended → will have ended (future perfect = will + have + past participle, not will + had); It is expects → It is expected (passive present for formal predictions).','hard'),
  (cid,38,140,'production','[TOEFL Writing — 200 words] Write a TOEFL-style argumentative paragraph on "Should governments invest in space exploration?" Use: will (prediction), will have (future perfect), is expected to, be going to, future continuous, passive future. Include hedging.','',NULL,'The question of whether governments should invest in space exploration involves weighing significant costs against uncertain but potentially transformative long-term benefits. Proponents argue that humanity will almost certainly face existential threats — from asteroid impacts to climate collapse — that will require capabilities currently under development by space agencies. By the end of this century, it is expected that at least one permanent lunar base will have been established, with Mars exploration actively underway. Advances in space technology are going to continue yielding terrestrial benefits: satellite systems will be providing critical services in communications, agriculture, navigation, and disaster response for billions of people. Critics counter that the resources invested in space could be more immediately directed at pressing earthly challenges such as poverty and climate change. This concern should be taken seriously. Nevertheless, the history of exploration suggests that the innovations emerging from the drive to reach space may ultimately be indispensable to solving the very problems that critics cite. Investment in both domains is therefore likely to be necessary rather than mutually exclusive.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
