-- ============================================================
-- SEED EXT 3: Módulo 17 — Non-Defining Clauses (ex 107-205)
-- Novos tópicos: non-defining vs defining discrimination,
-- clauses reduzidas (participial), TOEFL escrita acadêmica
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'non-defining-clauses';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo non-defining-clauses não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 31: defining vs non-defining — discriminação de significado
  (cid,31,107,'multiple_choice','What is the meaning difference between: (A) "Scientists who work with radioactive materials must follow strict safety protocols" and (B) "Scientists, who work with radioactive materials, must follow strict safety protocols"?','A restricts "scientists" to those who work with radioactive materials; B implies ALL scientists work with radioactive materials.','["There is no difference","A is more formal than B","A restricts ''scientists'' to those who work with radioactive materials; B implies ALL scientists work with radioactive materials.","B is incorrect"]','Defining (no commas) = restricts. Non-defining (commas) = all members of the group.','hard'),
  (cid,31,108,'multiple_choice','Which sentence CORRECTLY uses a defining relative clause?','The drug that showed the most promise in early trials has now entered Phase 3.','["The drug, that showed the most promise in early trials, has now entered Phase 3 (that + commas = wrong).","The drug that showed the most promise in early trials has now entered Phase 3.","The drug, which showed the most promise in early trials, has now entered Phase 3 (non-defining — changes meaning).","The drug which showed the most promise, has now entered Phase 3."]','Defining clause (no commas, which/that) = identifies which specific drug.','medium'),
  (cid,31,109,'gap_fill','The study _____ (which/that) produced the most cited results was conducted in 2018. (defines which study)','that / which',NULL,'Defining clause: "that" or "which" without commas — identifies which study.','easy'),
  (cid,31,110,'multiple_choice','Which sentence changes meaning most significantly when commas are added?','Students who fail the exam twice must retake the course.','["The professor who won the award is retiring.","The book which the professor recommended was out of stock.","Students who fail the exam twice must retake the course.","The lab that was renovated last year won an award."]','With commas: ALL students must retake (implies all fail twice). Without: only those who fail twice.','hard'),
  (cid,31,111,'gap_fill','Compare: "The researchers _____ (who/which) collected data in rural areas found markedly different results." (only some researchers collected in rural areas)','who',NULL,'Defining clause about people: "who" without commas = restricts to researchers who collected in rural areas.','easy'),
  (cid,31,112,'multiple_choice','In academic writing, when is a non-defining relative clause preferable to a defining one?','When the information is supplementary and the noun phrase is already sufficiently identified.','["Always in formal writing","Never — defining is always preferred","When the information is supplementary and the noun phrase is already sufficiently identified.","When using whose or where"]','Non-defining = extra information. Defining = identifying/restricting information.','hard'),

  -- BLOCK 32: reduced relative clauses with present participle (-ing)
  (cid,32,113,'gap_fill','The research team _____ (investigate) the outbreak made a surprising discovery. (active, ongoing action)','investigating',NULL,'Reduced relative clause: "the research team investigating X" = who were investigating X. -ing replaces "who was/were + -ing."','medium'),
  (cid,32,114,'multiple_choice','Which sentence uses a reduced relative clause (present participle) correctly?','The scientists studying Arctic ice cores have documented an accelerating rate of melt.','["The scientists who study Arctic ice cores have documented an accelerating rate of melt (defining full clause — also correct).","The scientists studying Arctic ice cores have documented an accelerating rate of melt.","The scientists studied Arctic ice cores have documented an accelerating melt.","The scientists to study Arctic ice cores have documented an accelerating melt."]','Reduced: "scientists studying X" = "scientists who are studying X."','medium'),
  (cid,32,115,'gap_fill','Data _____ (come) from the control group showed no statistically significant change over the trial period.','coming',NULL,'"Data coming from" = reduced relative (which came from / coming from).','medium'),
  (cid,32,116,'multiple_choice','Which reduced clause is INCORRECT?','The molecule consisting of hydrogen and oxygen known as water.','["The molecules exhibiting unusual magnetic properties were isolated for further study.","Data collected from three independent sites support the hypothesis.","The organism found at the deepest point in the ocean was entirely new to science.","The molecule consisting of hydrogen and oxygen known as water."]','Two uncoordinated reduced clauses without a verb — missing a main verb. "The molecule consisting of hydrogen and oxygen, known as water, is..."','hard'),

  -- BLOCK 33: reduced relative clauses with past participle (passive)
  (cid,33,117,'gap_fill','The samples _____ (collect/passive) from deep-sea sediment cores provided evidence of ancient climate shifts.','collected',NULL,'Reduced passive relative: "samples collected from X" = "samples which were collected from X."','medium'),
  (cid,33,118,'multiple_choice','Which sentence uses a reduced passive relative clause correctly?','The theory proposed by Darwin in 1859 fundamentally changed biology.','["The theory which proposed by Darwin in 1859 changed biology.","The theory that was proposed by Darwin in 1859 changed biology (full relative — also correct).","The theory proposed by Darwin in 1859 fundamentally changed biology.","The theory proposing by Darwin in 1859 changed biology (active -ing is wrong here — passive action)."]','"Proposed by Darwin" = reduced passive relative. "The theory which was proposed by Darwin."','medium'),
  (cid,33,119,'gap_fill','The policy _____ (implement/passive) by the previous administration had unintended consequences.','implemented',NULL,'"Implemented by" = reduced passive relative: which was implemented by.','medium'),
  (cid,33,120,'multiple_choice','What is the full relative clause of "Results obtained through randomized trials are considered most reliable"?','Results that/which were obtained through randomized trials are considered most reliable.','["Results that obtain through randomized trials are considered most reliable.","Results obtaining through randomized trials are considered most reliable.","Results that/which were obtained through randomized trials are considered most reliable.","Results that have been obtained through randomized trials are considered most reliable (also correct — present perfect)."]','Obtained = past participle (passive reduced relative). Was/were obtained = full passive form.','medium'),
  (cid,33,121,'gap_fill','The hypothesis _____ (test/passive) in the first three experiments was not supported by subsequent data.','tested',NULL,'"Tested in the experiments" = reduced passive relative (which was tested).','medium'),

  -- BLOCK 34: combining information — building complex non-defining clauses
  (cid,34,122,'gap_fill','Combine into one sentence using a non-defining relative clause: "CRISPR-Cas9 is a gene-editing technology. It has revolutionized genetic research." → "CRISPR-Cas9, _____ (which/have/revolutionize) genetic research, is a gene-editing technology."','which has revolutionized',NULL,'"CRISPR-Cas9, which has revolutionized genetic research, is..." = non-defining with present perfect.','hard'),
  (cid,34,123,'multiple_choice','Which combination is MOST effective for academic writing?','The standard deviation, which measures the spread of data around the mean, is a fundamental concept in statistics.','["The standard deviation measures the spread of data around the mean. The standard deviation is a fundamental concept.","The standard deviation, which measures the spread of data around the mean, is a fundamental concept in statistics.","The standard deviation (which measures spread) is a concept in statistics (over-reduced parenthetical).","The standard deviation that measures spread is a fundamental concept (defining — changes meaning)."]','Non-defining clause elegantly integrates supplementary definition.','hard'),
  (cid,34,124,'gap_fill','Combine: "Professor Chen has studied marine biodiversity for 30 years. Her research was published in Nature." → "Professor Chen, _____ (whose) research was published in Nature, has studied marine biodiversity for 30 years."','whose',NULL,'"Whose research" = possessive relative pronoun in non-defining clause.','medium'),
  (cid,34,125,'multiple_choice','Which sentence contains BOTH a reduced relative clause and a non-defining relative clause?','The samples collected from the Amazon, which have now been analyzed, suggest a previously unknown species.','["The samples were collected from the Amazon. They suggest a new species.","The samples collected from the Amazon, which have now been analyzed, suggest a previously unknown species.","The samples, collected from the Amazon which have been analyzed, suggest a new species.","Samples collected suggest a new species."]','Reduced passive (collected from the Amazon) + non-defining (which have now been analyzed).','hard'),

  -- BLOCK 35: non-defining clauses in TOEFL Academic writing
  (cid,35,126,'multiple_choice','[Academic] Which version of this sentence is most appropriate in a TOEFL essay?','The Paris Agreement, which was signed in 2015, represents the most ambitious international effort to address climate change.','["The Paris Agreement that was signed in 2015 represents the most ambitious international effort (defining — changes meaning).","The Paris Agreement, which was signed in 2015, represents the most ambitious international effort to address climate change.","The Paris Agreement signed in 2015 is the most ambitious international effort (reduced — also correct but less full).","The Paris Agreement is the most ambitious international effort, which was signed in 2015 (dangling clause)."]','Non-defining (commas + which) = best for providing supplementary historical context.','hard'),
  (cid,35,127,'gap_fill','[Academic] "The placebo effect, _____ (which) occurs when a patient improves after receiving a treatment with no active ingredient, poses significant challenges for clinical trial design."','which',NULL,'"Which" in non-defining clause provides a definition of the placebo effect.','easy'),
  (cid,35,128,'multiple_choice','[Academic] "The researchers, whose methodology has been extensively peer-reviewed, reported a 35% reduction in symptom severity." This non-defining clause does what?','Lends credibility to the researchers by mentioning peer review of their methods.','["Restricts which researchers are meant","Lends credibility to the researchers by mentioning peer review of their methods.","Introduces a contrast","Explains the 35% figure"]','Non-defining clause adds a trust-building detail about methodology.','medium'),
  (cid,35,129,'gap_fill','[Academic] "Cognitive behavioral therapy, _____ (reduce/reduced relative) treatment of anxiety disorders, has also shown promise in addressing chronic pain."','widely used in the',NULL,'"Cognitive behavioral therapy, widely used in the treatment of anxiety disorders, has also shown..." = reduced non-defining participial clause.','hard'),
  (cid,35,130,'multiple_choice','[Academic] In the sentence "The Industrial Revolution, which transformed European societies between 1760 and 1840, was driven primarily by technological innovation," removing the non-defining clause would:','Leave the main claim intact but remove important historical context.','["Change the meaning of ''industrial revolution''","Make the sentence ungrammatical","Leave the main claim intact but remove important historical context.","Make the sentence define a specific industrial revolution"]','Non-defining clause = removable supplement. Main clause still complete without it.','easy'),

  -- BLOCK 36: error correction
  (cid,36,131,'multiple_choice','Find the error: "The data, that was collected during the winter months, showed a clear seasonal pattern."','That should be which (non-defining clauses cannot use that).','["Data should be plural","Was should be were","That should be which (non-defining clauses cannot use that).","Seasonal should have a hyphen"]','"That" = only in defining relative clauses. Non-defining requires "which."','easy'),
  (cid,36,132,'gap_fill','Error: "My supervisor, who her advice I value enormously, will attend the conference." Fix: "My supervisor, _____ advice I value enormously, will attend the conference."','whose',NULL,'"Whose advice" = possessive relative pronoun. "Who her" is wrong — possessive requires whose.','medium'),
  (cid,36,133,'multiple_choice','Which sentence has a punctuation error?','The experiment which lasted six months produced unexpected results.','["The experiment, which lasted six months, produced unexpected results (correct — commas + which).","My colleague, who reviewed the paper, found several errors (correct).","The experiment which lasted six months produced unexpected results.","The data, which were collected over two years, were analyzed carefully (correct)."]','Non-defining clause (which lasted six months) = requires commas. Missing commas = error.','medium'),
  (cid,36,134,'gap_fill','Error: "The committee, that approved the proposal, meets once a month." Fix: "The committee, _____ approved the proposal, meets once a month."','which',NULL,'"Which" replaces "that" in non-defining clauses.','easy'),

  -- BLOCK 37: TOEFL Reading
  (cid,37,135,'multiple_choice','[TOEFL Reading] "The Amazon basin, which covers approximately 40% of South America, hosts over 10% of all known species on Earth." The non-defining clause functions to:','Provide a supporting factual detail about the scale of the Amazon basin.','["Identify which Amazon basin is being discussed","Provide a supporting factual detail about the scale of the Amazon basin.","Contrast the Amazon with other basins","Introduce a conditional"]','Non-defining = supplementary fact (scale). Main clause = biodiversity claim.','easy'),
  (cid,37,136,'gap_fill','[TOEFL Reading] "The control group, _____ received a placebo for 12 weeks, showed no significant change in symptoms." Best pronoun?','which',NULL,'"Which" for a non-defining clause about a thing/group.','easy'),
  (cid,37,137,'multiple_choice','[TOEFL Reading] "The standard model of particle physics, developed in the 1970s, has successfully predicted many experimental results." "Developed in the 1970s" is:','A reduced relative clause (which was developed in the 1970s).','["A main clause","A reduced relative clause (which was developed in the 1970s).","A participial adjective phrase modifying ''results''","An absolute phrase"]','Reduced passive relative: "(which was) developed in the 1970s."','medium'),
  (cid,37,138,'gap_fill','[TOEFL Reading] "The study found that stress, _____ affects nearly one in four adults, is a major contributing factor to cardiovascular disease." Best pronoun?','which',NULL,'Non-defining clause about an abstract concept (stress) → which.','easy'),

  -- BLOCK 38: TOEFL Speaking
  (cid,38,139,'production','[TOEFL Speaking — 45s] Describe a technological advancement. Use: (1) a non-defining relative clause with who, (2) a non-defining with which, (3) a reduced relative clause (-ing), and (4) which referring to a whole clause.','',NULL,'The team at DeepMind, who developed the AlphaFold protein-folding model, made a discovery that may rival the decoding of DNA in its scientific importance. AlphaFold, which can predict three-dimensional protein structures with remarkable accuracy, was released publicly in 2021. Scientists working on neglected tropical diseases were among the first to benefit from the tool, which has since accelerated drug discovery timelines significantly.','hard'),
  (cid,38,140,'production','[TOEFL Speaking — 45s] A reading says social media is harmful to teenagers. Use 3 non-defining relative clauses to embed evidence and qualify the argument.','',NULL,'A growing body of research, which has been conducted across multiple countries, suggests that heavy social media use is associated with increased anxiety in teenagers. Platforms like Instagram and TikTok, whose algorithms are specifically designed to maximize engagement, may expose young users to content that negatively affects body image and self-esteem. Regulators in several countries, who have examined internal company data, have called for age verification requirements and restrictions on addictive design features.','hard'),

  -- BLOCK 39: TOEFL Writing
  (cid,39,141,'production','[TOEFL Writing — 150 words] Write an academic paragraph about global health using at least 5 non-defining relative clauses across these types: who, which, whose, reduced -ing, reduced past participle, and which referring to a whole clause.','',NULL,'The World Health Organization, which coordinates international responses to health emergencies, has identified antimicrobial resistance as one of the most urgent threats to global public health. Bacteria, having evolved over billions of years, are extraordinarily adaptable organisms whose capacity to develop resistance to antibiotics is well documented. Researchers working on novel antimicrobials face enormous financial disincentives, which has led many pharmaceutical companies to abandon the field entirely. New antibiotics discovered in the past two decades have often failed to reach patients due to the high costs of clinical development, a challenge that demands new public-private funding models. The scientists most likely to solve this crisis are those engaged in fundamental microbiology research, whose work is chronically underfunded relative to its global significance.','hard'),
  (cid,39,142,'production','[TOEFL Writing — Error Correction] Fix all relative clause errors: "The ocean, that covers over 70% of the Earth, is largely unexplored. Viruses, who can mutate rapidly, pose ongoing challenges to vaccine development. The data, which they were collected over ten years, reveal an important trend. The hypothesis tested by the team, which was a rigorous study, was ultimately confirmed."','',NULL,'that → which (non-defining, not that); who → which (viruses are not people); which they were collected → which were collected (remove ''they'' — pronoun repetition error); "the hypothesis tested... which was a rigorous study" — ''which'' should refer to the study, but it is ambiguous. Cleaner: "The hypothesis tested by the team — a study known for its rigor — was ultimately confirmed." OR: "The team''s hypothesis, which was tested in a rigorous study, was ultimately confirmed."','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
