-- ============================================================
-- SEED EXT 3: Módulo 24 — Discourse Markers (ex 123-215)
-- Novos tópicos: força de transição, exemplificação/clarificação,
-- reformulação, marcadores entre-parágrafos, TOEFL
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'discourse-markers';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo discourse-markers não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 31: marcadores de exemplificação
  (cid,31,123,'gap_fill','Many factors contribute to academic underperformance; _____ (for example), sleep deprivation, poor nutrition, and excessive screen time.','for example / for instance',NULL,'"For example / for instance" = introduces a specific illustration.','easy'),
  (cid,31,124,'multiple_choice','Which discourse marker introduces a SPECIFIC example most formally?','To illustrate this point, consider the case of Finland''s education system.','["For example, Finland''s education system is good (less formal).","To illustrate this point, consider the case of Finland''s education system.","Like Finland, which has a good education system.","Take Finland, for instance (also acceptable — slightly less formal)."]','"To illustrate (this point)" = formal academic exemplification.','medium'),
  (cid,31,125,'gap_fill','Deforestation affects biodiversity in multiple ways: _____ (that is to say), it eliminates habitats, disrupts food chains, and alters local climate.','that is to say / namely / specifically',NULL,'"That is to say / Namely" = reformulates a general claim with specific content.','medium'),
  (cid,31,126,'multiple_choice','Which sentence uses "such as" correctly?','Several heavy metals, such as lead, mercury, and cadmium, are toxic to human health.','["Several heavy metals such as they are lead, mercury, and cadmium are toxic.","Several heavy metals, such as lead, mercury, and cadmium, are toxic to human health.","Such as lead, mercury, and cadmium are several heavy metals toxic to health.","Several heavy metals are toxic: such as lead, mercury, and cadmium."]','"Such as" introduces examples mid-clause. No verb after "such as."','easy'),
  (cid,31,127,'gap_fill','The study examined a wide range of cognitive abilities, _____ (namely) working memory, processing speed, and verbal fluency.','namely',NULL,'"Namely" = specifies exactly what was mentioned before. More formal than "for example."','medium'),

  -- BLOCK 32: marcadores de clarificação e reformulação
  (cid,32,128,'gap_fill','The policy is fiscally neutral; _____ (in other words), it will not increase the overall tax burden.','in other words',NULL,'"In other words" = reformulates/clarifies the preceding statement.','easy'),
  (cid,32,129,'multiple_choice','Which discourse marker signals clarification?','The approach is holistic; that is, it addresses the problem at multiple levels simultaneously.','["Furthermore, the approach is holistic.","The approach is holistic; that is, it addresses the problem at multiple levels simultaneously.","However, the approach is holistic.","The approach is holistic; in addition, it addresses multiple levels."]','"That is (to say)" = explains/clarifies what was just stated.','medium'),
  (cid,32,130,'gap_fill','The results were inconclusive, _____ (or rather), they pointed in two contradictory directions.','or rather',NULL,'"Or rather" = self-correction or more precise reformulation.','hard'),
  (cid,32,131,'multiple_choice','What is the difference between "in other words" and "that is to say"?','Both reformulate; "in other words" is slightly more informal; "that is (to say)" is more formal and precise.','["They are identical","In other words is more formal","Both reformulate; ''in other words'' is slightly more informal; ''that is (to say)'' is more formal and precise.","That is to say introduces a contrast"]','Both = reformulation/clarification, but register differs slightly.','hard'),
  (cid,32,132,'gap_fill','The patient showed signs of hypothyroidism — _____ (more precisely), abnormally low TSH levels and clinical fatigue.','more precisely / to be more specific / specifically',NULL,'"More precisely" = narrows or sharpens the preceding claim.','medium'),

  -- BLOCK 33: marcadores de adição e reforço
  (cid,33,133,'gap_fill','The new drug reduced inflammation; _____ (moreover), it showed no significant side effects in Phase 2 trials.','moreover / furthermore / what is more',NULL,'"Moreover/Furthermore" = adds a stronger or more surprising point.','easy'),
  (cid,33,134,'multiple_choice','Which marker adds a point that STRENGTHENS or ESCALATES the previous idea?','What is more, the treatment produced results within 48 hours, significantly faster than the current standard of care.','["However, the treatment produced results within 48 hours.","In contrast, the treatment produced results within 48 hours.","What is more, the treatment produced results within 48 hours, significantly faster than the current standard of care.","Nevertheless, the treatment produced results within 48 hours."]','"What is more" = escalation. The added point is even more significant.','medium'),
  (cid,33,135,'gap_fill','The algorithm is efficient; _____ (not only / but also), it is more accurate than any previously published model.','not only that, but it is also / not only is it efficient, but it is also',NULL,'"Not only (that), but also" = adds a second quality that strengthens the argument.','hard'),
  (cid,33,136,'multiple_choice','In academic writing, which marker is MOST formal for adding a point?','Furthermore, the findings have significant implications for clinical practice.','["Also, the findings have significant implications.","And also, the findings have significant implications.","Furthermore, the findings have significant implications for clinical practice.","Plus, the findings have significant implications."]','"Furthermore" = high-register additive marker. "Also" and "And also" are lower register.','easy'),

  -- BLOCK 34: marcadores de concessão avançados
  (cid,34,137,'gap_fill','_____ (Despite) the team''s best efforts, the experiment failed to produce statistically significant results.','Despite',NULL,'"Despite + noun phrase" = concessive without a clause.','easy'),
  (cid,34,138,'multiple_choice','Which pair correctly uses "although" and "even though"?','Although some evidence supports this view, the consensus remains unclear. Even though the sample was large, the methodology has been criticized.','["Even though has to go at the beginning of a sentence; although does not","Although some evidence supports this view, the consensus remains unclear. Even though the sample was large, the methodology has been criticized.","Although and even though cannot both be used in the same text","Even though is more formal than although"]','"Although" and "even though" are near-synonyms. "Even though" emphasizes stronger contrast.','medium'),
  (cid,34,139,'gap_fill','_____ (Granted), the study has limitations, it nonetheless makes a valuable contribution to the field.','Granted (that) / Admittedly',NULL,'"Granted (that)" = acknowledges a concession before the main argument.','hard'),
  (cid,34,140,'multiple_choice','What does "be that as it may" signal in discourse?','A concessive shift — acknowledging a point while maintaining the main argument.','["A conclusion","An exemplification","A concessive shift — acknowledging a point while maintaining the main argument.","A contradiction"]','"Be that as it may" = fixed concessive: acknowledges the previous point, then pivots.','hard'),
  (cid,34,141,'gap_fill','The costs are significant; _____ (that said), the long-term benefits clearly justify the initial investment.','that said / that being said / nonetheless',NULL,'"That said / that being said" = concessive pivot: acknowledges point, then rebalances.','medium'),

  -- BLOCK 35: marcadores entre parágrafos e estrutura global
  (cid,35,142,'gap_fill','Having established the theoretical framework, the following section _____ (turn to) the empirical evidence.','turns to',NULL,'Structuring discourse marker: "the following section turns to" = organizational signal.','medium'),
  (cid,35,143,'multiple_choice','Which discourse marker BEST signals a shift to a new topic in a TOEFL essay?','Turning to the economic dimension of this issue, it is important to consider...','["However, the economic dimension of this issue is important.","Turning to the economic dimension of this issue, it is important to consider...","In conclusion, the economic dimension is important.","Specifically, the economy matters here."]','"Turning to" = explicit topic-shift marker. Common in complex academic arguments.','medium'),
  (cid,35,144,'gap_fill','This section has examined the causes of the crisis. _____ (The next section), the analysis turns to the policy responses.','In the following section / Next',NULL,'Between-paragraph markers: "In the following section" / "We now turn to" = text-organizational.','medium'),
  (cid,35,145,'multiple_choice','Which discourse marker correctly summarizes a section before moving on?','In summary, the evidence presented above strongly supports the hypothesis that early intervention is beneficial.','["In contrast, the evidence strongly supports the hypothesis.","In summary, the evidence presented above strongly supports the hypothesis that early intervention is beneficial.","As a result, the evidence strongly supports the hypothesis.","Specifically, the evidence strongly supports the hypothesis."]','"In summary" = synthesizes what has been said before transitioning to the next point.','easy'),

  -- BLOCK 36: TOEFL Reading
  (cid,36,146,'multiple_choice','[TOEFL Reading] "Deforestation destroys habitats; moreover, it contributes to climate change by releasing stored carbon." What function does "moreover" serve?','It adds a second, arguably more significant consequence.','["It introduces a contrast","It explains the cause of deforestation","It adds a second, arguably more significant consequence.","It qualifies the first claim"]','"Moreover" = additive escalation.','easy'),
  (cid,36,147,'gap_fill','[TOEFL Reading] "The drug reduced inflammation; _____ (however), side effects in long-term use remain a concern." Best discourse marker?','however / nonetheless / that said',NULL,'Contrast after positive finding: however/nonetheless/that said.','easy'),
  (cid,36,148,'multiple_choice','[TOEFL Reading] "The study included a large sample; that is, over 10,000 participants from 15 countries." "That is" functions to:','Specify/clarify what "large sample" means in concrete terms.','["Contradict the previous claim","Specify/clarify what ''large sample'' means in concrete terms.","Add a new, separate finding","Introduce a conclusion"]','"That is" = clarification/specification of the preceding claim.','easy'),
  (cid,36,149,'gap_fill','[TOEFL Reading] "_____ (In spite of) the lack of large-scale clinical trials, the treatment is now widely used in the field." Best marker?','In spite of / Despite',NULL,'"In spite of / Despite + noun phrase" = concessive. No clause follows directly.','easy'),

  -- BLOCK 37: TOEFL Speaking
  (cid,37,150,'production','[TOEFL Speaking — 45s] A reading argues that social media has more benefits than drawbacks. Agree or disagree. Use: however, moreover, that said, for instance, in other words, despite.','',NULL,'Social media platforms do offer genuine benefits — for instance, they enable real-time communication across distances and have proven invaluable for organizing communities. Moreover, they have given marginalized groups unprecedented access to public discourse. However, the benefits come at significant social costs: algorithmic amplification of misinformation and addictive design patterns undermine informed democratic participation. That said, regulation rather than elimination may be the more appropriate response. In other words, the goal should be to harness the benefits of connectivity while curbing the harms. Despite the challenges, social media remains too deeply embedded in modern life to be meaningfully restricted.','hard'),
  (cid,37,151,'production','[TOEFL Speaking — 45s] Summarize a lecture about the effectiveness of different teaching methods. Use: for example, in contrast, furthermore, that is, turning to, in summary.','',NULL,'The professor highlighted the strengths and weaknesses of several pedagogical approaches. Lecturing, for example, is efficient for transmitting large amounts of information quickly. In contrast, project-based learning tends to develop deeper critical thinking skills, though it requires more time and resources. Furthermore, research suggests that combining both methods yields the strongest results overall. The professor clarified that ''active learning'' — that is, any approach that requires students to engage and apply knowledge rather than passively receive it — consistently outperforms pure lecturing. Turning to assessment, the professor noted that authentic tasks reflect real-world competencies more accurately than multiple-choice exams. In summary, the most effective educational environments blend diverse instructional approaches tailored to specific learning objectives.','hard'),

  -- BLOCK 38: TOEFL Writing
  (cid,38,152,'production','[TOEFL Writing — 150 words] Write an academic paragraph about urbanization using at least 6 different discourse markers: a concessive (although/despite/that said), an additive (furthermore/moreover), a causal (therefore/consequently), an exemplification (for instance/such as), a contrast (however/whereas), and a reformulation (in other words/namely).','',NULL,'Although urbanization is often associated with economic growth and improved living standards, it also generates significant environmental and social challenges. Cities such as Delhi, Jakarta, and Lagos are experiencing rapid population growth that strains existing infrastructure and services. Furthermore, the concentration of economic activity in urban centers has widened regional inequalities, leaving rural areas with declining investment and services. In other words, the gains from urbanization have not been equitably distributed across populations or geographies. Consequently, policymakers must develop urban planning strategies that balance economic development with social equity and environmental sustainability. That said, many urban centers have demonstrated that with appropriate governance and investment, high-density living can coexist with high quality of life. Copenhagen and Singapore, for instance, rank among the most livable cities globally despite — or perhaps because of — their high population densities.','hard'),
  (cid,38,153,'production','[TOEFL Writing — Error Correction] Fix discourse marker errors: "However the results were positive, some concerns remained. The study was large; despite, it had limitations. Turning to the economy, furthermore, it is important to consider employment. The drug worked; in other words, it didn''t eliminate all symptoms. The method was effective; although, it was expensive."','',NULL,'However the results were positive → Although the results were positive (however = contrast between sentences, not subordinating conjunction); despite, it had limitations → despite this / despite having limitations / however, it had limitations (despite needs a noun/gerund, not a full clause or just a comma); "Turning to the economy, furthermore" — ''furthermore'' is redundant after a topic-shift marker, remove it; "in other words, it didn''t eliminate all symptoms" — this contradicts ''worked''; should be: "However, it did not eliminate all symptoms" or "It worked in most respects; that said, it did not eliminate all symptoms"; "although, it was expensive" → although it was expensive (although = subordinating conjunction, no comma after it mid-sentence).','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
