-- ============================================================
-- SEED EXT 3: Módulo 22 — Subjunctive (ex 106-205)
-- Novos tópicos: frases fixas, it is time + subjunctive,
-- would rather + past subjunctive, registro formal/legal, TOEFL
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'subjunctive';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo subjunctive não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 31: frases fixas com subjuntivo
  (cid,31,106,'multiple_choice','In "Come what may, the experiment will proceed as planned," "come what may" is:','A fixed phrase with subjunctive meaning "whatever happens."','["An imperative","A fixed phrase with subjunctive meaning ''whatever happens.''","A conditional clause","A wish expression"]','"Come what may" = fixed subjunctive phrase (archaic/formal) meaning regardless of what happens.','hard'),
  (cid,31,107,'gap_fill','The motion was passed, _____ (so / be) it — there is no further appeal.','so be it',NULL,'"So be it" = fixed subjunctive phrase expressing acceptance of an outcome.','hard'),
  (cid,31,108,'multiple_choice','Which sentence contains a fixed subjunctive phrase?','Suffice it to say that the experiment yielded unexpected results.','["It suffices to say that the experiment was unexpected.","Suffice it to say that the experiment yielded unexpected results.","It is sufficient to say the experiment yielded unexpected results.","Suffice it says that the experiment yielded unexpected results."]','"Suffice it to say (that)" = fixed phrase with subjunctive "suffice."','hard'),
  (cid,31,109,'gap_fill','_____ (be/that as it may), the committee has decided to proceed with the original proposal.','Be that as it may',NULL,'"Be that as it may" = fixed concessive phrase (subjunctive "be"). Means "even so."','hard'),
  (cid,31,110,'multiple_choice','The phrase "if need be" contains a subjunctive because:','"Be" is in the base form (subjunctive), not "is" — an archaic fixed expression.','["It is a conditional","Need is a modal","''Be'' is in the base form (subjunctive), not ''is'' — an archaic fixed expression.","It is always correct to use be after if"]','"If need be" = "if it is necessary." Fixed archaic subjunctive.','hard'),
  (cid,31,111,'gap_fill','_____ (long/live) the Queen — used at formal ceremonies and royal proclamations.','Long live',NULL,'"Long live + noun" = fixed optative subjunctive (wish/blessing).','hard'),
  (cid,31,112,'multiple_choice','Which sentence uses a fixed subjunctive phrase correctly?','God save the king from enemies both foreign and domestic.','["God saves the king from enemies.","God saved the king from enemies.","God save the king from enemies both foreign and domestic.","God will save the king from enemies."]','"God save..." = optative subjunctive (wish/prayer). Not "saves" (third-person -s removed).','hard'),

  -- BLOCK 32: it is time + past subjunctive
  (cid,32,113,'gap_fill','It is time the international community _____ (take) decisive action on climate change.','took',NULL,'"It is time + subject + past simple (subjunctive sense)" = past form used for present urgency.','hard'),
  (cid,32,114,'multiple_choice','What does "It is time we reviewed the policy" imply?','The review should happen now — there has been a delay.','["The review happened recently","The review will happen in the future","The review should happen now — there has been a delay.","The review is unnecessary"]','"It is time + past = urgency that something has not yet happened.','hard'),
  (cid,32,115,'gap_fill','It is high time the government _____ (invest) in renewable energy infrastructure.','invested',NULL,'"It is high time + subject + past (subjunctive)" — "high time" = even stronger urgency.','hard'),
  (cid,32,116,'multiple_choice','Which sentence uses "it is time" correctly?','It is time scientists shared their data more openly with the public.','["It is time scientists share their data with the public (present — informal/acceptable but less idiomatic).","It is time scientists will share their data.","It is time scientists shared their data more openly with the public.","It is time that scientists should share their data."]','"It is time + subject + past (shared)" = correct subjunctive-like pattern.','hard'),
  (cid,32,117,'gap_fill','It is about time we _____ (acknowledge) the systemic inequalities in academic publishing.','acknowledged',NULL,'"It is about time + subject + past" = mild urgency/reproach.','hard'),
  (cid,32,118,'multiple_choice','The difference between "It is time to act" and "It is time we acted" is:','"To act" = impersonal infinitive (what needs to be done); "we acted" = subjunctive pointing at a specific group.','["There is no difference","To act is more urgent","''To act'' = impersonal infinitive (what needs to be done); ''we acted'' = subjunctive pointing at a specific group.","''We acted'' is incorrect"]','Infinitive = general; past subjunctive with subject = more pointed.','hard'),

  -- BLOCK 33: would rather + past subjunctive (preference about others)
  (cid,33,119,'gap_fill','I would rather you _____ (not/reveal) the results before the paper is published.','did not reveal',NULL,'"Would rather + subject + past" = preference about someone else''s action.','hard'),
  (cid,33,120,'multiple_choice','What is the difference between "I''d rather go" and "I''d rather you went"?','"I''d rather go" = my own preference (infinitive); "I''d rather you went" = preference about what someone else does (past subjunctive).','["They are identical","Both require an infinitive","''I''d rather go'' = my own preference (infinitive); ''I''d rather you went'' = preference about what someone else does (past subjunctive).","''I''d rather you went'' is always incorrect"]','Would rather + bare inf (own action) vs. would rather + subject + past (other''s action).','hard'),
  (cid,33,121,'gap_fill','The editor would rather the authors _____ (revise) the methodology section before resubmission.','revised',NULL,'"Would rather + subject + past" for preference about another person''s action.','hard'),
  (cid,33,122,'multiple_choice','Which is correct? "The committee would rather the decision ___ postponed until more data are available."','were','["be","is","were","will be"]','"Would rather + subject + were + past participle (passive)" = subjunctive.','hard'),
  (cid,33,123,'gap_fill','She would rather her research _____ (not/publish) without peer review.','were not published / not be published',NULL,'"Would rather + subject + past/were + passive" for strong preference.','hard'),
  (cid,33,124,'multiple_choice','Complete: "I''d rather you ___ the conference alone." (preference you don''t go alone)','didn''t attend','["don''t attend","won''t attend","didn''t attend","hadn''t attend"]','"Would rather + subject + past (didn''t attend)" = preference about others.','medium'),

  -- BLOCK 34: formal mandative subjunctive in legal/official contexts
  (cid,34,125,'gap_fill','The statute requires that all companies _____ (disclose) their carbon emissions annually.','disclose',NULL,'Legal mandative subjunctive: require + that + base verb (no -s, no auxiliary).','hard'),
  (cid,34,126,'multiple_choice','Which sentence is appropriate in a formal legal document?','The regulation stipulates that no party be permitted to share confidential data.','["The regulation stipulates that no party is permitted to share confidential data.","The regulation stipulates that no party be permitted to share confidential data.","The regulation stipulates that no party should share confidential data (acceptable but weaker).","The regulation stipulates no party shares confidential data."]','Mandative passive subjunctive in legal register: stipulates + that + passive base form.','hard'),
  (cid,34,127,'gap_fill','The bylaws dictate that a quorum of two-thirds of members _____ (present) at any vote on constitutional matters.','be present',NULL,'"Dictate + that + subjunctive." "Be present" = base form.','hard'),
  (cid,34,128,'multiple_choice','In formal legal and academic English, why is the mandative subjunctive preferred over "should"?','The subjunctive (base form) is more concise and has a long tradition in formal written English.','["Should is grammatically incorrect","The subjunctive is more modern","The subjunctive (base form) is more concise and has a long tradition in formal written English.","Should can only be used in spoken English"]','Mandative subjunctive = traditional formal register; "should" = more common in British English.','hard'),
  (cid,34,129,'gap_fill','The resolution states that all parties _____ (commit) to reducing emissions by 45% before 2030.','commit',NULL,'Mandative subjunctive: states + that + base verb (no -s for third-person singular).','hard'),

  -- BLOCK 35: TOEFL Reading
  (cid,35,130,'multiple_choice','[TOEFL Reading] "The committee recommended that the proposal be tabled until further environmental assessments were conducted." The subjunctive "be tabled" is correct because:','It follows "recommended," which is a mandative verb requiring a subjunctive that-clause.','["Past passive is used after all committee verbs","It follows ''recommended,'' which is a mandative verb requiring a subjunctive that-clause.","The sentence is in the passive","Be is used here as a main verb"]','"Recommended + that + passive mandative subjunctive."','medium'),
  (cid,35,131,'gap_fill','[TOEFL Reading] "The court order demands that the company _____ (cease) operations immediately and _____ (restore) the site to its original condition." Best forms?','cease / restore',NULL,'Mandative subjunctive: demand + that + base verb (no -s, no to).','hard'),
  (cid,35,132,'multiple_choice','[TOEFL Reading] "Be that as it may, the council voted to proceed with the demolition." "Be that as it may" means:','Even so; despite what has been said, the following is true.','["Because of that","That is correct","Even so; despite what has been said, the following is true.","As a result"]','"Be that as it may" = fixed subjunctive concession phrase.','medium'),
  (cid,35,133,'gap_fill','[TOEFL Reading] "It is high time the scientific community _____ (adopt) standardized protocols for reporting research findings." Best form?','adopted',NULL,'"It is high time + subject + past (adopted)" = subjunctive-like urgency.','hard'),
  (cid,35,134,'multiple_choice','[TOEFL Reading] "The authors suggest that the model be tested under a wider range of conditions." Why is "be tested" correct?','Suggest is a mandative verb; "be tested" is the passive mandative subjunctive form.','["Be tested is a participle","The authors is plural so be is used","Suggest is a mandative verb; ''be tested'' is the passive mandative subjunctive form.","Tests is used after suggest"]','Suggest + that + passive base form = mandative passive subjunctive.','medium'),

  -- BLOCK 36: TOEFL Speaking
  (cid,36,135,'production','[TOEFL Speaking — 45s] A university is deciding whether to require all students to take a research methods course. Support this using: propose + that + subjunctive, require + passive subjunctive, it is time, it is essential + that + subjunctive.','',NULL,'I propose that all undergraduate students be required to complete a research methods course before graduating. It is essential that they understand the principles of evidence evaluation, which are critical for navigating an era of misinformation. It is time universities recognized that research literacy is as fundamental as communication skills. I would further recommend that the course be assessed through a practical project rather than a written exam, ensuring that students develop genuine competency.','hard'),
  (cid,36,136,'production','[TOEFL Speaking — 45s] A company is considering a new working policy. Use: would rather + subject + past, it is high time, stipulate + that + subjunctive, be that as it may.','',NULL,'Most employees I know would rather the company introduced a four-day workweek than continued with the current five-day model. It is high time organizations recognized the relationship between overwork and burnout. Be that as it may, the company has valid concerns about productivity, which deserve serious consideration. The new policy should stipulate that all client-facing teams maintain coverage on five days while internal teams experiment with compressed schedules.','hard'),

  -- BLOCK 37: TOEFL Writing
  (cid,37,137,'production','[TOEFL Writing — 150 words] Write an academic paragraph arguing for mandatory data sharing in scientific research. Use: recommend + that + subjunctive, require + passive subjunctive, it is essential, stipulate, lest, would rather.','',NULL,'Leading scientific bodies have recommended that all publicly funded research be made freely accessible upon publication. It is essential that data transparency be upheld as a core principle of scientific integrity, not merely an aspiration. Funding agencies should stipulate that raw datasets be deposited in publicly accessible repositories before or simultaneously with the publication of results. Lest proprietary interests prevent the replication of important findings, regulators must establish binding requirements rather than voluntary guidelines. Some researchers would rather their raw data remain unpublished, citing concerns about misuse or premature interpretation. Be that as it may, the benefits of open science — accelerated discovery, reduced duplication, and increased public trust — outweigh these concerns. It is high time the scientific community adopted a unified standard for data sharing that is enforceable across disciplines and institutions.','hard'),
  (cid,37,138,'production','[TOEFL Writing — Error Correction] Fix subjunctive errors: "It is time we take action on this issue. I would rather you don''t tell him. The board suggested that the project is cancelled. Be that as may, the vote will proceed. The law requires that all employees are paid minimum wage."','',NULL,'take → took (it is time + past); don''t tell → didn''t tell (would rather + subject + past); is cancelled → be cancelled (mandative passive subjunctive after suggest); "Be that as may" → "Be that as it may" (fixed phrase); are paid → be paid (require + mandative passive subjunctive).','hard'),
  (cid,37,139,'production','[TOEFL Writing — 200 words] Write an TOEFL-style argument paragraph on "The importance of regulating social media platforms" using: it is essential + that + subjunctive, require + passive subjunctive, it is high time, lest, would rather, be that as it may, and at least one fixed subjunctive phrase.','',NULL,'It is essential that governments establish robust regulatory frameworks for social media platforms without further delay. It is high time legislators recognized that algorithmic amplification of misinformation poses a systemic threat to democratic processes. Platforms should be required to disclose their content moderation algorithms and be held accountable for harms that result from their design choices. Lest the power of these companies go unchecked, policymakers must act decisively before public trust in institutions is permanently eroded. Many platform executives would rather operate under minimal regulatory oversight, arguing that intervention stifles innovation. Be that as it may, the public interest must take precedence over commercial considerations. Regulation should stipulate that independent audits be conducted annually and that users be informed clearly about how their data are used. Come what may, the current era of self-regulation has demonstrably failed to prevent significant social harms, and a new approach is urgently warranted.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
