-- ============================================================
-- SEED EXT 2: Módulo 14 — Passive Voice (exercícios 71-200)
-- Novos tópicos: modais, infinitivo, impessoal, causativo,
-- relativas, correção de erros + TOEFL avançado
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'passive-voice';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo passive-voice não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 11: passive with modal verbs
  (cid,11,71,'gap_fill','The report ___ (must/submit) before the end of the fiscal year.','must be submitted',NULL,'Modal passive: modal + be + past participle. Must be submitted.','medium'),
  (cid,11,72,'gap_fill','All data ___ (should/store) securely to comply with privacy regulations.','should be stored',NULL,'Should + be + past participle = obligation passive.','medium'),
  (cid,11,73,'multiple_choice','Choose the correct modal passive: "The experiment ___ under controlled conditions."','must be conducted','["must conducted","must be conduct","must be conducted","must have conducted"]','Must + be + past participle (conduct → conducted).','medium'),
  (cid,11,74,'gap_fill','Errors in the manuscript ___ (can/correct) before submission.','can be corrected',NULL,'Can + be + past participle = possibility passive.','easy'),
  (cid,11,75,'gap_fill','The policy ___ (may/change) following the review committee''s findings.','may be changed',NULL,'May + be + past participle = possibility (less certain).','medium'),
  (cid,11,76,'multiple_choice','Which sentence uses modal passive correctly in an academic context?','Environmental damage cannot be reversed without significant investment.','["Environmental damage cannot reverse without investment.","Environmental damage cannot be reversed without significant investment.","Environmental damage can''t be reversing without investment.","Environmental damage could not reversed without investment."]','Cannot + be + reversed (past participle of reverse).','medium'),
  (cid,11,77,'gap_fill','New regulations ___ (might/introduce) to control carbon emissions next year.','might be introduced',NULL,'Might + be + past participle for uncertain future.','medium'),
  (cid,11,78,'gap_fill','The samples ___ (have to/analyze) within 24 hours of collection.','have to be analyzed',NULL,'Have to + be + past participle = necessity passive.','medium'),
  (cid,11,79,'multiple_choice','Convert: "They should reconsider the proposal." → Modal passive?','The proposal should be reconsidered.','["The proposal should reconsidered.","The proposal should be reconsidering.","The proposal should be reconsidered.","The proposal must be reconsidered."]','Should + be + past participle (reconsider → reconsidered).','medium'),
  (cid,11,80,'gap_fill','The budget ___ (ought to/approve) by the board before any expenditure can be made.','ought to be approved',NULL,'Ought to + be + past participle = moral obligation passive.','hard'),
  (cid,11,81,'multiple_choice','Which modal passive expresses the STRONGEST obligation?','The findings must be verified before publication.','["The findings could be verified before publication.","The findings might be verified before publication.","The findings must be verified before publication.","The findings may be verified before publication."]','Must = strongest obligation among the options.','easy'),
  (cid,11,82,'gap_fill','Participants ___ (not/coerce) into taking part in research under any circumstances.','must not be coerced',NULL,'Must not + be + past participle for prohibition.','hard'),
  (cid,11,83,'multiple_choice','Which sentence correctly expresses past possibility with passive?','The data could have been misinterpreted during analysis.','["The data could be misinterpreted during analysis (present).","The data could have been misinterpreting during analysis.","The data could have been misinterpreted during analysis.","The data might misinterpreted during analysis."]','Could + have + been + past participle = past possibility passive.','hard'),

  -- BLOCK 12: passive infinitive and gerund
  (cid,12,84,'gap_fill','The students expected ___ (inform) about the schedule change.','to be informed',NULL,'Passive infinitive: to + be + past participle.','medium'),
  (cid,12,85,'multiple_choice','Choose the correct passive infinitive: "She hoped ___ for the grant."','to be selected','["to select","to have selected","to be selected","being selected"]','To + be + past participle = passive infinitive.','medium'),
  (cid,12,86,'gap_fill','The researcher''s work deserves ___ (recognize) at the international level.','to be recognized',NULL,'Deserves + to + be + past participle.','medium'),
  (cid,12,87,'gap_fill','Being ___ (nominate) for the award was an honor for the entire team.','nominated',NULL,'Passive gerund: being + past participle.','medium'),
  (cid,12,88,'multiple_choice','Choose the correct passive gerund: "___ without proper citation is unacceptable in academia."','Being plagiarized','["Being plagiarize","Being plagiarizing","Being plagiarized","To be plagiarize"]','Being + past participle = passive gerund.','medium'),
  (cid,12,89,'gap_fill','The professor resented ___ (exclude) from the research committee''s discussion.','being excluded',NULL,'Resentment + gerund. Passive gerund: being + past participle.','hard'),
  (cid,12,90,'multiple_choice','Which uses passive gerund correctly?','Being rejected by top journals is common for researchers submitting groundbreaking work.','["Being reject by top journals is common.","Been rejected by top journals is common.","Being rejected by top journals is common for researchers submitting groundbreaking work.","To be rejected by top journals are common."]','Being + rejected (past participle) = passive gerund.','medium'),
  (cid,12,91,'gap_fill','The hypothesis appears ___ (support) by the most recent data.','to be supported',NULL,'Appears + passive infinitive: to + be + past participle.','hard'),
  (cid,12,92,'gap_fill','The theory seemed ___ (ignore) by mainstream researchers for decades.','to have been ignored',NULL,'Perfect passive infinitive: to + have + been + past participle.','hard'),
  (cid,12,93,'multiple_choice','Choose the perfect passive infinitive: "The document appears ___ before the deadline."','to have been submitted','["to submit","to be submitted","to have been submitted","to have submitted"]','To + have + been + past participle = perfect passive infinitive (before the deadline = prior action).','hard'),
  (cid,12,94,'gap_fill','After ___ (examine) thoroughly, the evidence was deemed inconclusive.','being examined',NULL,'After + passive gerund (being + past participle).','hard'),
  (cid,12,95,'multiple_choice','Which passive form follows "without"?','The paper was published without being peer-reviewed.','["The paper was published without to be peer-reviewed.","The paper was published without peer-reviewed.","The paper was published without been peer-reviewed.","The paper was published without being peer-reviewed."]','Without + being + past participle = passive gerund after preposition.','hard'),
  (cid,12,96,'gap_fill','The artist is honored ___ (commission) by the National Museum.','to be commissioned',NULL,'Honored + passive infinitive: to + be + past participle.','medium'),

  -- BLOCK 13: impersonal passive (it is said/believed/reported/known)
  (cid,13,97,'gap_fill','___ (say) that the new treatment significantly reduces recovery time.','It is said',NULL,'Impersonal passive: It + is/was + said/believed/reported + that-clause.','medium'),
  (cid,13,98,'multiple_choice','Rewrite formally: "People believe the economy will recover."','It is believed that the economy will recover.','["People are believing the economy will recover.","It is believed that the economy will recover.","The economy is believed to recover.","It was believed the economy recovered."]','It + is + believed + that = impersonal passive.','medium'),
  (cid,13,99,'gap_fill','___ (report) in several studies that stress negatively affects academic performance.','It has been reported',NULL,'Present perfect impersonal passive: It + has been + past participle.','medium'),
  (cid,13,100,'multiple_choice','Which sentence uses the personal form of impersonal passive?','The new drug is reported to reduce inflammation by 40%.','["It is reported that the new drug reduces inflammation by 40% (impersonal).","The new drug is reported to reduce inflammation by 40%.","The new drug has been reported reducing inflammation by 40%.","The new drug is reported to reduced inflammation."]','Subject + is + past participle + to-infinitive = personal passive.','hard'),
  (cid,13,101,'gap_fill','The theory ___ (think) to be incorrect until new evidence emerged in the 1980s.','was thought',NULL,'Was + past participle + to-infinitive = past personal passive.','hard'),
  (cid,13,102,'gap_fill','___ (know) that exposure to a second language improves cognitive function.','It is known',NULL,'It + is + known + that-clause for established scientific fact.','easy'),
  (cid,13,103,'multiple_choice','Choose the correct impersonal passive: "People claimed the discovery would change medicine."','It was claimed that the discovery would change medicine.','["It is claimed that the discovery would change medicine.","It was claimed that the discovery would change medicine.","It was claiming that the discovery would change medicine.","It claimed that the discovery would change medicine."]','Was + claimed + that-clause for past impersonal passive.','medium'),
  (cid,13,104,'gap_fill','Climate change ___ (widely/consider) to be the defining challenge of the 21st century.','is widely considered',NULL,'Is + widely + past participle + to-infinitive = personal passive with adverb.','medium'),
  (cid,13,105,'multiple_choice','Which is NOT a correct impersonal passive structure?','It is known to the discovery changed medicine.','["It is known that the discovery changed medicine.","The discovery is known to have changed medicine.","It was known that the discovery would change medicine.","It is known to the discovery changed medicine."]','Correct structures: "It is known that..." or "X is known to..."','hard'),
  (cid,13,106,'gap_fill','The results ___ (show) to be consistent across all demographic groups.','have been shown',NULL,'Have + been + past participle + to-infinitive = personal perfect passive.','hard'),
  (cid,13,107,'gap_fill','___ (estimate) that over 1 billion people are currently affected by this condition.','It is estimated',NULL,'It + is + estimated + that = impersonal passive for statistics.','medium'),
  (cid,13,108,'multiple_choice','Convert: "Archaeologists believe the site dates back to 3000 BCE." → Impersonal passive?','It is believed by archaeologists that the site dates back to 3000 BCE.','["Archaeologists are believed that the site dates back to 3000 BCE.","It is believed by archaeologists that the site dates back to 3000 BCE.","The site is believing to date back to 3000 BCE.","It believed that the site dates back to 3000 BCE."]','It + is + believed + by + agent + that-clause.','hard'),
  (cid,13,109,'gap_fill','The compound ___ (allege) to have significant therapeutic properties.','is alleged',NULL,'Is + alleged + to-infinitive = personal passive for unverified claim.','hard'),

  -- BLOCK 14: causative passive (have/get something done)
  (cid,14,110,'gap_fill','The professor ___ (have) her thesis ___ (proofread) before the defense.','had / proofread',NULL,'Causative: have + object + past participle (arranged by agent).','medium'),
  (cid,14,111,'multiple_choice','Choose the correct causative: "The university ___ the new wing ___ last year."','had the new wing built','["had the new wing builds","has the new wing build","had the new wing built","had built the new wing"]','Have + object + past participle = causative (arranging for someone else to do it).','medium'),
  (cid,14,112,'gap_fill','She ___ (get) her research ___ (publish) in a top-tier journal.','got / published',NULL,'Causative: get + object + past participle.','medium'),
  (cid,14,113,'multiple_choice','What does "I need to have this data verified" mean?','I need to arrange for someone to verify this data.','["I will verify this data myself.","I need to arrange for someone to verify this data.","I have already verified this data.","I must verify this data urgently."]','Have + object + past participle = causative (arrange for someone else).','hard'),
  (cid,14,114,'gap_fill','The department ___ (have) its budget ___ (audit) every year by an external firm.','has / audited',NULL,'Causative have: present simple + object + past participle.','medium'),
  (cid,14,115,'gap_fill','The researchers ___ (get) their equipment ___ (calibrate) before starting the trial.','got / calibrated',NULL,'Causative get: past simple + object + past participle.','medium'),
  (cid,14,116,'multiple_choice','Which sentence uses causative passive?','The hospital had its records digitized by a specialist company.','["The hospital digitized its records.","The specialist company digitized the hospital records.","The hospital had its records digitized by a specialist company.","The hospital was digitizing its records."]','Had + object + past participle + by + agent = causative passive.','hard'),
  (cid,14,117,'gap_fill','The author ___ (have) the manuscript ___ (translate) into three languages.','had / translated',NULL,'Have + object + past participle for causative.','medium'),
  (cid,14,118,'multiple_choice','Choose the sentence that expresses a negative causative experience.','He got his research funding cut by the committee.','["He cut his research funding.","The committee cut research funding.","He got his research funding cut by the committee.","He will have his funding cut soon."]','Got + object + past participle = negative causative experience (undesirable).','hard'),
  (cid,14,119,'gap_fill','The team ___ (have) its proposal ___ (reject) twice before it was finally accepted.','had / rejected',NULL,'Had + object + past participle = negative causative experience.','hard'),
  (cid,14,120,'multiple_choice','What is the difference between "I had my data destroyed" and "My data was destroyed"?','The causative implies I arranged it; the passive implies it happened to me.','["They mean the same thing.","The causative implies I arranged it; the passive implies it happened to me.","The passive implies I arranged it; the causative happened to me.","There is no difference in academic writing."]','Causative = arranged; passive = happened without arranging.','hard'),
  (cid,14,121,'gap_fill','The government ___ (have) the contaminated water ___ (test) after public complaints.','had / tested',NULL,'Causative: had + object + past participle.','medium'),
  (cid,14,122,'gap_fill','Students can ___ (have) their essays ___ (review) by the writing center.','have / reviewed',NULL,'Can have + object + past participle = modal causative.','medium'),

  -- BLOCK 15: passive in relative clauses
  (cid,15,123,'gap_fill','The theory ___ (propose) by Einstein fundamentally changed our understanding of gravity.','that was proposed / which was proposed',NULL,'Relative clause with passive: that/which + was/were + past participle.','medium'),
  (cid,15,124,'multiple_choice','Choose the correct relative clause: "The data ___ in the survey were analyzed."','that was collected','["who were collected","that was collected","which collected","that collected"]','That/which + was + past participle for passive relative clause with singular data.','medium'),
  (cid,15,125,'gap_fill','The participants ___ (select) for the study were between the ages of 18 and 30.','who were selected / that were selected',NULL,'Who/that + were + past participle for people in passive relative clause.','medium'),
  (cid,15,126,'gap_fill','The university ___ (found) in 1851 is one of the oldest research institutions in the country.','founded',NULL,'Reduced passive relative clause: past participle without "which was" for formal writing.','hard'),
  (cid,15,127,'multiple_choice','Choose the reduced passive relative clause: "The results ___ in the study support the hypothesis."','obtained','["that were obtained","which was obtained","obtained","have been obtained"]','Reduced passive relative: past participle alone (no that was).','hard'),
  (cid,15,128,'gap_fill','The chemicals ___ (store) in the basement were found to be hazardous.','stored',NULL,'Reduced passive relative: stored = which were stored.','hard'),
  (cid,15,129,'multiple_choice','Which sentence has a reduced passive relative clause?','The experiment conducted in 2020 produced significant results.','["The experiment that was conducted in 2020 produced significant results.","The experiment conducted in 2020 produced significant results.","The experiment which has been conducted in 2020 produced significant results.","The experiment being conducted in 2020 produced significant results."]','Conducted (without that was) = reduced passive relative clause.','hard'),
  (cid,15,130,'gap_fill','The paper ___ (write) by three co-authors has been cited over 500 times.','written',NULL,'Written = reduced passive relative clause (written by = which was written by).','hard'),
  (cid,15,131,'multiple_choice','Expand the reduced relative: "The vaccine approved last year is now widely available."','The vaccine that was approved last year is now widely available.','["The vaccine approved by last year is now widely available.","The vaccine that was approved last year is now widely available.","The vaccine which approved last year is now widely available.","The vaccine approving last year is now widely available."]','That + was + past participle = full passive relative clause.','medium'),
  (cid,15,132,'gap_fill','The funds ___ (allocate) to research should be increased, according to the committee.','allocated',NULL,'Allocated = reduced passive relative (which were allocated).','hard'),
  (cid,15,133,'gap_fill','The methods ___ (describe) in the previous section were adapted from Chen et al. (2019).','described',NULL,'Described = reduced passive relative clause (which were described).','medium'),
  (cid,15,134,'multiple_choice','Choose the most natural academic phrasing:','The model developed by the research team predicted outcomes with 90% accuracy.','["The model which was developed by the research team predicted outcomes with 90% accuracy.","The model developed by the research team predicted outcomes with 90% accuracy.","The model that has been developed by the research team predicted outcomes with 90% accuracy.","The model being developed by the research team predicted outcomes with 90% accuracy."]','Reduced passive relative (developed) is more concise in academic writing.','hard'),
  (cid,15,135,'gap_fill','Variables ___ (not/control) in the original study were addressed in the replication.','not controlled',NULL,'Negative reduced passive relative: not + past participle.','hard'),

  -- BLOCK 16: error correction in passive voice
  (cid,16,136,'multiple_choice','Find and correct the error: "The experiment was conduct by a team of researchers."','was conducted (past participle required after "was")','["was conducting","is conducted","was conducted (past participle required after ''was'')","has been conduct"]','Was + past participle: conduct → conducted.','easy'),
  (cid,16,137,'gap_fill','Error: "The data have been analyzed by us." → More academic: "The data ___ systematically."','were analyzed',NULL,'Remove "by us" and rephrase to depersonalize in academic writing.','medium'),
  (cid,16,138,'multiple_choice','Which sentence contains an error?','The results have been publishing in Nature.','["The results were published in Nature.","The results have been published in Nature.","The results will be published in Nature.","The results have been publishing in Nature."]','Have been + past participle. Publishing is -ing form, not past participle.','easy'),
  (cid,16,139,'gap_fill','Error correction: "It is knowing that the compound is toxic." → Correct: "It ___ that the compound is toxic."','is known',NULL,'Impersonal passive: it + is + past participle. Knowing → Known.','easy'),
  (cid,16,140,'multiple_choice','Correct the error: "The papers were submitted by us to the conference."','The papers were submitted to the conference. (omit "by us" — we is obvious)','["The papers submitted to the conference by us.","The papers were submitted to the conference. (omit ''by us'' — we is obvious)","The papers have been submitted to the conference by us.","The papers are submitted to the conference by us."]','By + agent omitted when agent is obvious (us = the researchers).','hard'),
  (cid,16,141,'gap_fill','Error: "The results was published in 2022." → Correct: "The results ___ in 2022."','were published',NULL,'Plural subject (results) requires were, not was.','easy'),
  (cid,16,142,'multiple_choice','Find the error: "The participants have been selected using random sampling methods."','No error — the sentence is correct.','["Have been selecting","Selected using","Have been selected — correct","No error — the sentence is correct."]','Have + been + selected (past participle) = correct present perfect passive.','medium'),
  (cid,16,143,'gap_fill','Error: "She got her article accepted by the committee yesterday." Is this correct? Answer: ___ — this is a valid causative passive.','Yes',NULL,'Got + object + past participle = correct causative passive (informal, acceptable in speech).','hard'),
  (cid,16,144,'multiple_choice','Which error appears in: "The building is being construct."?','construct should be constructed (past participle)','["building should be buildings","is should be was","construct should be constructed (past participle)","being should be been"]','Is + being + past participle. Construct → Constructed.','easy'),
  (cid,16,145,'gap_fill','Error: "The theory was proposed Darwin in 1859." → Correct: "The theory was proposed ___ Darwin in 1859."','by',NULL,'"By" is required to introduce the agent in passive voice.','easy'),
  (cid,16,146,'multiple_choice','Which sentence is CORRECTLY written in passive?','The vaccine had been tested on thousands of volunteers before approval.','["The vaccine has test on thousands of volunteers before approval.","The vaccine was being tested before approved.","The vaccine had been tested on thousands of volunteers before approval.","The vaccine was test by researchers before approval."]','Had + been + tested = past perfect passive, correct.','medium'),
  (cid,16,147,'gap_fill','Error: "The essay is written by the students and submit tomorrow." → Correct: "The essay ___ by the students and ___ tomorrow."','is being written / will be submitted',NULL,'Two parallel passives: present continuous + future.','hard'),
  (cid,16,148,'multiple_choice','Identify the error: "The data is being analyzed since January."','is being should be has been (present perfect passive for duration)','["data is incorrect — should be datum","analyzed should be analysis","is being should be has been (present perfect passive for duration)","since January should be from January"]','Since + duration → present perfect passive (has been analyzed).','hard'),

  -- BLOCK 17: TOEFL Reading — advanced passive identification
  (cid,17,149,'multiple_choice','[TOEFL Reading] The sentence "Urban sprawl has been linked to increased rates of obesity and social isolation." indicates that:','Researchers have found a connection between urban sprawl and those health issues.','["Urban sprawl causes obesity and social isolation directly.","Researchers have found a connection between urban sprawl and those health issues.","The connection between urban sprawl and obesity is disputed.","Urban residents are linked to obesity by researchers."]','Has been linked = present perfect passive; by-agent omitted (by researchers implied).','medium'),
  (cid,17,150,'gap_fill','[TOEFL Reading] "The fossils ___ (estimate) to be approximately 65 million years old." The passive here is used to:','express scientific consensus without naming specific researchers',NULL,'Personal passive (are estimated + to-infinitive) depersonalizes the scientific claim.','hard'),
  (cid,17,151,'multiple_choice','[TOEFL Reading] "It was not until the 20th century that the theory was widely accepted." The passive construction emphasizes:','The theory itself and when it gained acceptance.','["Who accepted the theory","The theory itself and when it gained acceptance.","The researchers who resisted the theory","The century as an agent"]','Passive focuses on theory (subject) not on who accepted it.','hard'),
  (cid,17,152,'gap_fill','[TOEFL Reading] Which tense is used in: "Greenhouse gases have been accumulating in the atmosphere since industrialization"? Answer: ___','present perfect (progressive sense)',NULL,'Have been + -ing = present perfect progressive (not passive here). Distinguish passive from progressive.','hard'),
  (cid,17,153,'multiple_choice','[TOEFL Reading] "The grant was awarded to a team of researchers from three countries." What does this passive sentence emphasize?','The grant and who received it, not who gave it.','["Who awarded the grant","The grant and who received it, not who gave it.","The countries from which researchers came","The process of awarding grants"]','Passive shifts focus to the grant (subject) and its recipients (to + noun phrase).','medium'),
  (cid,17,154,'gap_fill','[TOEFL Reading] "The initial findings ___ (replicate) by independent laboratories, which ___ (consider) essential for scientific validity." Fill both blanks.','were replicated / is considered',NULL,'Past simple passive + present simple passive.','hard'),
  (cid,17,155,'multiple_choice','[TOEFL Reading] "Some species are thought to have gone extinct before they were ever discovered." Which passive structures are in this sentence?','Personal impersonal passive + past simple passive','["Two past simple passives","Present simple passive only","Personal impersonal passive + past simple passive","Present perfect passive + past simple passive"]','Are thought (personal impersonal) + were discovered (past simple passive).','hard'),
  (cid,17,156,'gap_fill','[TOEFL Reading] "The participants ___ (randomly assign) to one of three treatment groups." Use past simple passive.','were randomly assigned',NULL,'Were + past participle for methods section.','easy'),
  (cid,17,157,'multiple_choice','[TOEFL Reading] In which section of a research article does passive voice appear MOST frequently?','Methods','["Introduction","Discussion","Methods","Conclusion"]','Methods sections depersonalize procedures using passive extensively.','easy'),
  (cid,17,158,'gap_fill','[TOEFL Reading] "Although the data ___ (initially/interpret) as supporting the hypothesis, further analysis revealed inconsistencies." Fill the blank.','were initially interpreted',NULL,'Past simple passive: were + interpreted with adverb initially.','hard'),
  (cid,17,159,'multiple_choice','[TOEFL Reading] "The genome of the virus has been sequenced, making vaccine development possible." The present perfect passive here implies:','The sequencing has recently been completed and has current relevance.','["The sequencing was done in the past with no current relevance.","The sequencing has recently been completed and has current relevance.","The sequencing will be done soon.","The sequencing is happening right now."]','Present perfect passive = completed action with present relevance.','medium'),
  (cid,17,160,'gap_fill','[TOEFL Reading] "The traditional view ___ (challenge) by several recent longitudinal studies." Which tense fits best?','has been challenged',NULL,'Present perfect passive for recently challenged established view.','medium'),
  (cid,17,161,'multiple_choice','[TOEFL Reading] Which sentence BEST demonstrates a passive shift of focus used in academic argument?','Higher mortality rates were observed in the placebo group, which suggests that the treatment is effective.','["Researchers observed higher mortality rates in the placebo group, which suggests treatment effectiveness.","Higher mortality rates were observed in the placebo group, which suggests that the treatment is effective.","The placebo group showed higher mortality rates, which we observed.","Mortality rates were being observed in the placebo group."]','Were observed (passive) shifts focus from researchers to the finding.','hard'),

  -- BLOCK 18: TOEFL Listening — passive in spoken academic context
  (cid,18,162,'multiple_choice','[TOEFL Listening] A professor says "Now, the ancient city was thought to have been abandoned due to drought." What does this imply?','This was a widely held belief in the past (possibly changed by new evidence).','["The city was definitely abandoned because of drought.","This was a widely held belief in the past (possibly changed by new evidence).","The professor is arguing drought caused abandonment.","The city is currently being studied for drought evidence."]','Was thought = past personal passive, suggesting a previous belief that may now be challenged.','hard'),
  (cid,18,163,'gap_fill','[TOEFL Listening] The professor says: "The building was constructed over a period of 40 years and ___ (eventually/complete) in 1502." Fill the blank.','was eventually completed',NULL,'Past simple passive + adverb eventually.','easy'),
  (cid,18,164,'multiple_choice','[TOEFL Listening] "It''s been reported that class sizes have been increasing." Which two verb structures are used?','Present perfect passive + present perfect progressive','["Past simple + present perfect","Present perfect passive + present perfect progressive","Two past simple passives","Present simple + present continuous"]','Has been reported (passive) + have been increasing (progressive).','hard'),
  (cid,18,165,'gap_fill','[TOEFL Listening] "The experiment was carefully designed to eliminate bias. Variables ___ (control) and all equipment ___ (calibrate) before testing began." Fill both blanks.','were controlled / was calibrated',NULL,'Past simple passive for parallel methods steps.','medium'),
  (cid,18,166,'multiple_choice','[TOEFL Listening] "By the end of the decade, it''s expected that over 500 million people will be affected." The passive construction "it''s expected" is used to:','Present an impersonal projection without naming a specific source.','["Disagree with the projection","State the professor''s personal opinion","Present an impersonal projection without naming a specific source.","Report a past discovery"]','Impersonal passive (it is expected) = academic projection without personal attribution.','hard'),
  (cid,18,167,'gap_fill','[TOEFL Listening] "The lecture focuses on how diseases ___ (spread) in pre-modern cities and how infection ___ (manage) before modern medicine." Fill both blanks.','were spread / was managed',NULL,'Past simple passive for historical processes.','medium'),
  (cid,18,168,'multiple_choice','[TOEFL Listening] A student says: "The paper was giving to us last week." What is the error?','giving should be given (past participle)','["Paper should be papers","was should be were","giving should be given (past participle)","last week should be yesterday"]','Was + past participle: give → given (not giving).','easy'),
  (cid,18,169,'gap_fill','[TOEFL Listening] "According to recent studies, stress hormones ___ (link) to decreased immune function." Fill the blank.','have been linked',NULL,'Present perfect passive for recently established research finding.','medium'),
  (cid,18,170,'multiple_choice','[TOEFL Listening] Which phrase signals that the professor is about to use passive voice to introduce an established fact?','It is widely believed that...','["I personally think that...","We found that...","It is widely believed that...","I want to argue that..."]','It is + believed/known/reported = impersonal passive for established fact.','medium'),
  (cid,18,171,'gap_fill','[TOEFL Listening] "The concept ___ (introduce) to Western philosophy by Arab scholars in the 12th century." Fill the blank.','was introduced',NULL,'Was + past participle + by + agent for historical attribution.','easy'),
  (cid,18,172,'multiple_choice','[TOEFL Listening] "The research was replicated three times before the findings were accepted." This sentence contains:','Two past simple passive constructions.','["A past simple active and a past simple passive","Two past simple passive constructions.","A present perfect passive and a past simple passive","A causative and a passive"]','Was replicated + were accepted = two past simple passives.','medium'),
  (cid,18,173,'gap_fill','[TOEFL Listening] "The samples must ___ (handle) with extreme care to avoid contamination." Fill the blank.','be handled',NULL,'Must + be + past participle = modal passive.','easy'),
  (cid,18,174,'multiple_choice','[TOEFL Listening] "The proposal was turned down three times before it was finally approved." What does this tell us?','The proposal was rejected repeatedly before eventually succeeding.','["The proposal succeeded on the first attempt.","The proposal was never accepted.","The proposal was rejected repeatedly before eventually succeeding.","Someone turned down the approval proposal."]','Was turned down (past passive) + was finally approved (past passive) = sequence.','medium'),

  -- BLOCK 19: TOEFL Speaking — extended practice
  (cid,19,175,'production','[TOEFL Speaking — 45s] Explain the process of how a new drug is approved in your country. Use at least 4 different passive constructions (modal passive, present perfect passive, future passive, past simple passive).','',NULL,'Is tested, has been approved, will be released, was submitted...','hard'),
  (cid,19,176,'production','[TOEFL Speaking — 45s] Describe a historical technological invention (e.g., the telephone, the internet, the printing press). Use passive voice to explain: when it was invented, by whom it was developed, how it has been used since, and how it will continue to be used.','',NULL,'Was invented in..., was developed by..., has been used for..., will be used to...','hard'),
  (cid,19,177,'production','[TOEFL Speaking — 45s] A campus policy states that all exams will be conducted online next semester. Use passive voice to: (1) describe the policy change, (2) explain how students will be affected, and (3) state what concerns have been raised.','',NULL,'Exams will be conducted... Students will be required to... Concerns have been raised about...','hard'),
  (cid,19,178,'production','[TOEFL Speaking — 45s] Summarize a reading passage you have studied recently. Use passive voice at least 3 times to describe what was argued, what evidence was presented, and what conclusions were drawn.','',NULL,'The passage argues that... Evidence was presented showing... The conclusion drawn was that...','hard'),
  (cid,19,179,'production','[TOEFL Speaking — 45s] Describe a scientific discovery that has been made in the last 10 years. Include: what was discovered, how it was discovered, why it is considered important, and how it is currently being applied.','',NULL,'Was discovered, was found by, is considered, is being applied...','hard'),
  (cid,19,180,'production','[TOEFL Speaking — 45s] Agree or disagree: "Too much emphasis is placed on standardized testing in modern education." Use passive voice at least twice in your response.','',NULL,'Is placed on / are tested / has been shown / are evaluated...','hard'),
  (cid,19,181,'production','[TOEFL Speaking — 45s] Using the get-passive and the formal passive, contrast how you would discuss an academic failure in a formal essay versus in a casual conversation.','',NULL,'Formal: The project was not completed on time. Informal: The project got abandoned halfway through.','hard'),

  -- BLOCK 20: TOEFL Writing — advanced production
  (cid,20,182,'production','[TOEFL Writing — 150 words] Write a methods paragraph for a study on reading habits of university students. Use passive voice throughout: describe how participants were recruited, how data were collected (survey/interview), how responses were recorded, and how results were analyzed.','',NULL,'Were recruited, were collected, were recorded, were analyzed — all past simple passive.','hard'),
  (cid,20,183,'production','[TOEFL Writing] Rewrite this active-voice paragraph using appropriate passive constructions: "We conducted interviews with 40 participants. We recorded all sessions with permission. We then transcribed the audio and analyzed themes. We found three major patterns in the data."','',NULL,'Interviews were conducted... Sessions were recorded... Audio was transcribed... Three major patterns were found...','hard'),
  (cid,20,184,'production','[TOEFL Writing] Write a 5-sentence introduction paragraph on climate policy. Use: (1) impersonal passive (it has been established that), (2) present perfect passive for recent developments, (3) personal passive with to-infinitive, (4) modal passive for proposed action, (5) future passive.','',NULL,'It has been established that... Targets have been set... The problem is known to affect... Emissions must be reduced... New policies will be implemented...','hard'),
  (cid,20,185,'production','[TOEFL Writing — Error Correction] Rewrite with correct passive forms: "The survey are conduct last year. Data was collect from 200 students. Results have being analyzed by our team."','',NULL,'Was conducted, were collected, have been analyzed (remove "by our team" — depersonalize).','hard'),
  (cid,20,186,'production','[TOEFL Writing] Write a short argumentative paragraph (5 sentences) arguing that renewable energy investment should be increased. Use at least 4 different passive constructions including a modal passive, a present perfect passive, a future passive, and an impersonal passive.','',NULL,'It has been shown that... Billions have been invested... Renewable targets must be met... New infrastructure will be built...','hard'),
  (cid,20,187,'production','[TOEFL Writing — Synthesis] Based on two perspectives: (A) Online education should replace traditional classrooms; (B) Face-to-face learning cannot be replicated online. Write a 150-word paragraph synthesizing both views using passive voice to present each perspective formally.','',NULL,'It is argued that online education can be implemented more efficiently... However, it has been noted that certain learning outcomes cannot be achieved...','hard'),
  (cid,20,188,'production','[TOEFL Writing] Choose ONE: (a) the discovery of penicillin, (b) the development of the internet, (c) the invention of the printing press. Write a 5-sentence historical summary using: past simple passive, past perfect passive, present perfect passive, and impersonal passive (it is considered / it has been argued).','',NULL,'Was discovered by, had been tested before, has been used since, it is now considered one of the most important...','hard'),
  (cid,20,189,'production','[TOEFL Writing — 200 words] Write an academic essay paragraph arguing for stronger environmental regulations. Your paragraph must include: (1) an impersonal passive as the topic sentence, (2) at least two present perfect passives for evidence, (3) a modal passive for recommendation, (4) a future passive for expected outcomes, (5) a reduced passive relative clause.','',NULL,'It is widely acknowledged... Several studies have been conducted... Emissions have been linked to... Stricter regulations must be enforced... Policies implemented now will determine...','hard'),
  (cid,20,190,'production','[TOEFL Academic Writing — Formal Register] Rewrite the following informal paragraph in formal academic register, converting active verbs to passive where appropriate: "We all know global warming is getting worse. Scientists keep finding new evidence. People are losing their homes because of floods. Governments need to do something now."','',NULL,'It is widely known that... New evidence has been found... Homes have been lost... Action must be taken immediately...','hard'),

  -- BLOCK 21: mixed advanced revision
  (cid,21,191,'multiple_choice','Which sentence demonstrates the most complex passive construction?','The compound is believed to have been synthesized centuries before it was officially documented.','["The compound was synthesized centuries ago.","The compound has been synthesized.","The compound is believed to have been synthesized centuries before it was officially documented.","The compound was believed to be synthesizing when it was documented."]','Is believed (personal impersonal) + to have been synthesized (perfect passive infinitive) + was documented (past passive).','hard'),
  (cid,21,192,'gap_fill','All the variables ___ (account for) before the final model ___ (select).','had been accounted for / was selected',NULL,'Past perfect passive + past simple passive for sequence.','hard'),
  (cid,21,193,'multiple_choice','Which tense combination is most appropriate for a discussion section of a TOEFL academic paper?','Present perfect passive (findings) + past simple passive (methods) + modal passive (recommendations)','["Two past simple passives","Present perfect passive (findings) + past simple passive (methods) + modal passive (recommendations)","Future passive + present passive","Three present simple passives"]','Discussion sections mix tenses: present perfect for findings, past for methods, modal for implications.','hard'),
  (cid,21,194,'gap_fill','The enzyme ___ (not/previously/associate) with this metabolic pathway until the 2018 study.','had not previously been associated',NULL,'Past perfect passive negative: had + not + been + past participle + adverb.','hard'),
  (cid,21,195,'multiple_choice','Which sentence correctly uses passive voice with two agents?','The study was funded by the government and reviewed by an independent ethics committee.','["The study was funded by the government and reviewing by an independent ethics committee.","The study was funded by the government and reviewed by an independent ethics committee.","The study funded by the government and was reviewed by an independent ethics committee.","The study was fund by the government and reviewed by an ethics committee."]','Was + funded (correct) + was + reviewed (correct) = two past simple passives with different agents.','hard'),
  (cid,21,196,'gap_fill','___ (widely/accept) that language acquisition is most efficient during early childhood, a view ___ (support) by decades of neurological research.','It is widely accepted / supported',NULL,'Impersonal passive + reduced passive relative clause.','hard'),
  (cid,21,197,'multiple_choice','Which passive construction is INCORRECT in formal academic English?','Data was collected by us and by we analyzed it.','["Data was collected and analyzed by the research team.","The study was approved by the ethics committee.","Data was collected by us and by we analyzed it.","All participants were treated with respect and their responses were kept confidential."]','By we is grammatically wrong (should be by us, but ideally omit entirely in academic writing).','hard'),
  (cid,21,198,'gap_fill','The findings, which ___ (present) at three international conferences, ___ (eventually/publish) in a peer-reviewed journal.','were presented / were eventually published',NULL,'Two past simple passives: relative clause passive + main clause passive.','hard'),
  (cid,21,199,'multiple_choice','[TOEFL] Which sequence of passive constructions best describes a complete research cycle?','A hypothesis was proposed → data were collected → results were analyzed → findings have been published.','["A hypothesis proposes → data collects → results analyze → findings publish.","A hypothesis was proposed → data were collected → results were analyzed → findings have been published.","A hypothesis is proposed → data is collected → results are analyzed → findings were published.","A hypothesis has been proposed → data were collecting → results have analyzed → findings will publish."]','Past simple passive for completed steps + present perfect passive for recently published outcome.','hard'),
  (cid,21,200,'production','[TOEFL — Capstone Task] Write a 200-word academic paragraph on the topic: "The role of technology in transforming modern education." Your paragraph must contain at least 8 different passive voice constructions spanning at least 4 different tenses or modal forms. Underline each passive construction.','',NULL,'Technology has been used... Online platforms were introduced... Blended learning is being adopted... Students are expected to... Skills must be developed... Learning will be personalized... It is believed that... Barriers have been reduced...','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
