-- ============================================================
-- SEED: Módulo 9 — Conditional Type 1 (A2)
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'conditional-1';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo conditional-1 não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 1: if + present simple, will + base verb
  (cid,1,1,'gap_fill','If you ___ (study) consistently, you ___ (improve) your TOEFL score.','study / will improve',NULL,'Type 1 conditional: If + present simple, will + base verb for real/possible conditions.','easy'),
  (cid,1,2,'gap_fill','She ___ (pass) the exam if she ___ (prepare) well.','will pass / prepares',NULL,'The main clause (will + base verb) can also come first.','easy'),
  (cid,1,3,'multiple_choice','Choose the correct Type 1 conditional.','If temperatures rise by 2°C, many species will face extinction.','["If temperatures will rise by 2°C, many species will face extinction.","If temperatures rise by 2°C, many species will face extinction.","If temperatures rose by 2°C, many species would face extinction.","If temperatures rise by 2°C, many species face extinction."]','If + present simple, will + base verb. Never use "will" in the if-clause.','easy'),
  (cid,1,4,'gap_fill','If the funding ___ (be) approved, the researchers ___ (begin) the project next month.','is / will begin',NULL,'If clause: is (present simple), main clause: will begin (future).','easy'),
  (cid,1,5,'gap_fill','What ___ (happen) if the experiment ___ (fail)?','will happen / fails',NULL,'Wh-question conditional: What will happen if + present simple?','medium'),
  (cid,1,6,'multiple_choice','Identify the error: "If she will submit the report on time, the professor will grade it today."','will submit should be submits','["she should be her","will grade is incorrect","will submit should be submits","professor should have no article"]','Never use "will" in the if-clause. Use present simple.','medium'),
  (cid,1,7,'gap_fill','If you ___ (not/review) your notes, you ___ (not/remember) the material.','don''t review / won''t remember',NULL,'Negative type 1: if + don''t/doesn''t + base verb, won''t + base verb.','medium'),

  -- BLOCK 2: will + base verb in the main clause
  (cid,2,8,'multiple_choice','Complete: "If the data ___, the researchers will have to repeat the study."','is corrupted','["will be corrupted","was corrupted","is corrupted","be corrupted"]','Present simple in the if-clause, even when the result is future.','medium'),
  (cid,2,9,'gap_fill','If you ___ (not/understand) a word, ___ (look) it up in the dictionary.','don''t understand / look',NULL,'Conditional with imperative in main clause: if + present simple, imperative.','medium'),
  (cid,2,10,'multiple_choice','Choose the correct sentence.','If the hypothesis is correct, the results will support the theoretical framework.','["If the hypothesis is correct, the results support the theoretical framework.","If the hypothesis will be correct, the results will support the framework.","If the hypothesis is correct, the results will support the theoretical framework.","If the hypothesis was correct, the results would support the framework."]','If + present simple, will + base verb.','medium'),
  (cid,2,11,'gap_fill','If she ___ (take) the advanced grammar course, her writing ___ (improve) significantly.','takes / will improve',NULL,'Possible/realistic condition → Type 1 conditional.','easy'),
  (cid,2,12,'multiple_choice','Which sentence is a Type 1 conditional?','If the team presents strong evidence, the committee will approve the proposal.','["If the team presented strong evidence, the committee would approve the proposal (Type 2).","If the team has presented strong evidence, the committee approves the proposal.","If the team presents strong evidence, the committee will approve the proposal.","If the team will present strong evidence, the committee will approve the proposal."]','If + present simple (presents), will + base verb (will approve).','medium'),
  (cid,2,13,'gap_fill','Unless we ___ (receive) more data, we ___ (not/be able to) draw conclusions.','receive / won''t be able to',NULL,'"Unless" = if not. Unless + present simple, won''t + base verb.','hard'),
  (cid,2,14,'multiple_choice','What is the correct modal variation: "If you heat water to 100°C, it ___ boil."','will','["would","will","should","might"]','Type 1: will for the expected result of a real condition.','easy'),

  -- BLOCK 3: unless / as long as / provided that
  (cid,3,15,'gap_fill','___ you practice speaking daily, your fluency won''t improve.','Unless',NULL,'"Unless" = if not. Unless you practice = if you don''t practice.','medium'),
  (cid,3,16,'multiple_choice','Which sentence correctly uses "unless"?','The experiment won''t succeed unless the conditions are controlled carefully.','["The experiment won''t succeed unless the conditions won''t be controlled.","The experiment won''t succeed unless the conditions are controlled carefully.","The experiment will succeed unless the conditions are controlled carefully.","The experiment won''t succeed unless if the conditions are controlled."]','Unless + positive present simple for negative condition.','medium'),
  (cid,3,17,'gap_fill','___ you cite your sources correctly, your paper won''t be accepted.','Unless',NULL,'"Unless you cite" = "if you don''t cite".','medium'),
  (cid,3,18,'multiple_choice','Choose the sentence with "as long as" used correctly.','As long as you submit the application by Friday, you will be considered.','["As long as you will submit by Friday, you will be considered.","As long as you submitted by Friday, you will be considered.","As long as you submit the application by Friday, you will be considered.","As long as you submit by Friday, you are considered."]','As long as + present simple, will + base verb.','medium'),
  (cid,3,19,'gap_fill','The scholarship ___ (be) available ___ the student ___ (maintain) a GPA above 3.5.','will be / as long as / maintains',NULL,'"As long as" = on the condition that. Present simple in the condition clause.','hard'),
  (cid,3,20,'multiple_choice','Choose the correct sentence with "provided that".','Provided that the participants give informed consent, the study will proceed.','["Provided that the participants will give informed consent, the study will proceed.","Provided that the participants give informed consent, the study will proceed.","Provided that the participants gave informed consent, the study would proceed.","Providing the participants give informed consent, the study proceed."]','Provided that + present simple, will + base verb.','hard'),
  (cid,3,21,'gap_fill','The conference ___ (accept) your abstract ___ that it ___ (meet) the word limit.','will accept / provided / meets',NULL,'"Provided that + present simple" for formal conditions.','hard'),

  -- BLOCK 4: zero conditional (if + present, present)
  (cid,4,22,'gap_fill','If you ___ (heat) ice, it ___ (melt). (scientific fact)','heat / melts',NULL,'Zero conditional: if + present simple, present simple. For universal truths.','easy'),
  (cid,4,23,'multiple_choice','Which is a ZERO conditional?','If you don''t water plants, they die.','["If you don''t water plants, they will die (Type 1).","If you don''t water plants, they would die (Type 2).","If you don''t water plants, they die.","If you haven''t watered plants, they die."]','Zero conditional uses present simple in both clauses — permanent truths.','medium'),
  (cid,4,24,'gap_fill','If demand ___ (exceed) supply, prices ___ (rise). (economic principle)','exceeds / rise',NULL,'Zero conditional for economic laws: present simple in both clauses.','medium'),
  (cid,4,25,'multiple_choice','Which sentence is a zero conditional?','If the temperature drops below zero, water freezes.','["If the temperature drops below zero, water will freeze (Type 1 — also possible).","If the temperature dropped below zero, water would freeze (Type 2).","If the temperature drops below zero, water freezes.","If the temperature has dropped below zero, water freezes."]','Zero conditional: present simple, present simple — scientific fact.','medium'),
  (cid,4,26,'gap_fill','If carbon dioxide levels ___ (increase) in the atmosphere, the greenhouse effect ___ (intensify). (environmental principle)','increase / intensifies',NULL,'Zero conditional for scientific/environmental principles.','medium'),
  (cid,4,27,'multiple_choice','Distinguish: "If you press the button, the machine starts" vs "If you press the button, the machine will start."','The first is zero conditional (fact/automatic); the second is Type 1 (predicted future outcome).','["They are identical in meaning","The first is zero conditional (fact/automatic); the second is Type 1 (predicted future outcome).","The second uses zero conditional","The first uses Type 1 conditional"]','Zero (present/present) = automatic truth; Type 1 (present/will) = likely future result.','hard'),
  (cid,4,28,'gap_fill','If you ___ (mix) red and blue paint, you ___ (get) purple. (art/chemistry fact)','mix / get',NULL,'Universal truth → zero conditional: present simple in both clauses.','easy'),

  -- BLOCK 5: common mistakes in Type 1 conditionals
  (cid,5,29,'multiple_choice','Identify the error: "If she will study harder, she will get a better grade."','will study should be studies','["she should be her","will study should be studies","will get is wrong","grade should be grades"]','Never use "will" in the if-clause. Use present simple.','medium'),
  (cid,5,30,'gap_fill','Correct this sentence: "If it will rain, the ceremony will be moved indoors." Answer: If it ___, the ceremony will be moved indoors.','rains',NULL,'Remove "will" from the if-clause; use present simple.','medium'),
  (cid,5,31,'multiple_choice','Which sentence is CORRECT?','If you don''t submit the form today, you won''t be registered.','["If you won''t submit the form today, you won''t be registered.","If you don''t submit the form today, you won''t be registered.","If you didn''t submit the form today, you wouldn''t be registered (Type 2).","If you haven''t submitted the form today, you won''t be registered."]','Don''t + base verb in if-clause; won''t + base verb in main clause.','medium'),
  (cid,5,32,'gap_fill','If the sample size ___ (not/be) large enough, the results ___ (not/be) reliable.','isn''t / won''t be',NULL,'Negative in both clauses using doesn''t/isn''t and won''t.','medium'),
  (cid,5,33,'multiple_choice','Identify the error: "Unless she won''t submit by Monday, she''ll lose the scholarship."','won''t submit should be submits','["she should be her","won''t submit should be submits","she''ll should be she will","Monday should be Monday morning"]','"Unless" already implies negativity — don''t add "won''t" in the unless-clause.','hard'),
  (cid,5,34,'gap_fill','Correct this: "Unless it doesn''t rain, the outdoor lecture will proceed." Correct: Unless it ___, the outdoor lecture will proceed.','rains',NULL,'"Unless + positive" = "if + negative". Don''t use double negatives with unless.','hard'),
  (cid,5,35,'multiple_choice','Which conditional correctly uses "might" in the result clause?','If she practices daily, she might achieve a TOEFL score above 110.','["If she practices daily, she might achieved a TOEFL score above 110.","If she practiced daily, she might achieve a TOEFL score above 110 (Type 2).","If she practices daily, she might achieve a TOEFL score above 110.","If she will practice daily, she might achieve above 110."]','Might + base verb in main clause for less certain Type 1 result.','hard'),

  -- BLOCK 6: can/may/might/should in result clause
  (cid,6,36,'gap_fill','If you ___ (need) help with the essay, you ___ (can/ask) a writing tutor.','need / can ask',NULL,'Can in the result clause for ability/permission.','medium'),
  (cid,6,37,'multiple_choice','Choose the correct modal in the result: "If the experiment is successful, we ___ publish the results."','may','["will certainly","may","would","had"]','"May" for possibility in the result of a Type 1 conditional.','medium'),
  (cid,6,38,'gap_fill','If the proposal ___ (be) approved, the team ___ (should/begin) immediately.','is / should begin',NULL,'"Should" in result clause for advice/expectation.','hard'),
  (cid,6,39,'multiple_choice','Which sentence uses "might" correctly in a Type 1 conditional?','If the samples are contaminated, the results might be unreliable.','["If the samples are contaminated, the results might be unreliable.","If the samples were contaminated, the results might be unreliable (Type 2).","If the samples are contaminated, the results might were unreliable.","If the samples will be contaminated, the results might be unreliable."]','Might + base verb for uncertain result in Type 1.','hard'),
  (cid,6,40,'gap_fill','If she ___ (score) above 100, she ___ (can/apply) to top universities.','scores / can apply',NULL,'Can in result clause for possibility/opportunity.','medium'),
  (cid,6,41,'multiple_choice','Which modal gives a WARNING in the result clause?','If you don''t cite sources properly, you could face academic penalties.','["If you don''t cite sources properly, you will face academic penalties (certain).","If you don''t cite sources properly, you could face academic penalties.","If you don''t cite sources properly, you should face academic penalties.","If you don''t cite sources properly, you might have faced academic penalties."]','"Could" for possible negative consequences (warning).','hard'),
  (cid,6,42,'gap_fill','If the vaccine ___ (prove) effective, governments ___ (should/distribute) it as quickly as possible.','proves / should distribute',NULL,'"Should" for recommendation in result clause.','hard'),

  -- BLOCK 7: real vs hypothetical - Type 1 vs Type 2 distinction
  (cid,7,43,'multiple_choice','Which is Type 1 (real/possible) not Type 2 (hypothetical)?','If she applies now, she will meet the deadline.','["If she had more time, she would apply (Type 2).","If she applied now, she would meet the deadline (Type 2).","If she applies now, she will meet the deadline.","If she had applied earlier, she would have met the deadline (Type 3)."]','Type 1: if + present simple, will + base verb — real/possible situation.','medium'),
  (cid,7,44,'gap_fill','If the professor ___ (agree) to supervise her, she ___ (start) the research immediately.','agrees / will start',NULL,'Real/possible future condition: Type 1.','medium'),
  (cid,7,45,'multiple_choice','Which pair correctly shows Type 1 vs Type 2?','Type 1: "If it rains, we will cancel." Type 2: "If it rained, we would cancel."','["Type 1: ''If it rains, we would cancel.'' Type 2: ''If it rained, we will cancel.''","Type 1: ''If it rains, we will cancel.'' Type 2: ''If it rained, we would cancel.''","Type 1: ''If it rained, we will cancel.'' Type 2: ''If it rains, we would cancel.''","Type 1: ''If it rains, we cancel.'' Type 2: ''If it rained, we had cancelled.''"]','Type 1: present/will; Type 2: past/would.','hard'),
  (cid,7,46,'gap_fill','If I ___ (have) enough money, I ___ (buy) the expensive textbook. (real situation — money is possible)','have / will buy',NULL,'If the situation is real/possible → Type 1: have (present) / will buy.','medium'),
  (cid,7,47,'multiple_choice','Which sentence describes an UNLIKELY or HYPOTHETICAL situation (Type 2, not Type 1)?','If I were the department chair, I would restructure the curriculum.','["If I become department chair, I will restructure the curriculum (Type 1 — possible).","If I were the department chair, I would restructure the curriculum.","If I am the department chair, I will restructure the curriculum (Type 1).","If I was the department chair, I restructured the curriculum."]','If + were/past simple, would + base verb = Type 2 (unlikely/hypothetical).','hard'),
  (cid,7,48,'gap_fill','If researchers ___ (not/consider) ethical issues, their studies ___ (not/be) approved.','don''t consider / won''t be',NULL,'Real warning/condition: Type 1 conditional.','medium'),
  (cid,7,49,'multiple_choice','In an academic context, which conditional is more common for describing research implications?','Type 1: "If the results are significant, the findings will influence policy."','["Type 2: ''If the results were significant, the findings would influence policy.''","Type 1: ''If the results are significant, the findings will influence policy.''","Type 3: ''If the results had been significant, the findings would have influenced policy.''","Zero: ''If the results are significant, the findings influence policy.''"]','Type 1 for possible/expected research outcomes.','hard'),

  -- BLOCK 8: mixed conditional 1 review
  (cid,8,50,'multiple_choice','Which sentence uses Type 1 conditional correctly?','If governments invest in renewable energy, CO2 emissions will decrease.','["If governments invest in renewable energy, CO2 emissions would decrease (Type 2).","If governments invested in renewable energy, CO2 emissions will decrease (mixed error).","If governments invest in renewable energy, CO2 emissions will decrease.","If governments will invest in renewable energy, CO2 emissions will decrease (error)."]','If + present simple, will + base verb.','medium'),
  (cid,8,51,'gap_fill','If the budget ___ (be) cut further, several research programs ___ (have to/shut) down.','is / will have to shut',NULL,'"Will have to" in result clause for obligation as result.','hard'),
  (cid,8,52,'multiple_choice','Identify the correct negative conditional.','If students don''t engage with feedback, they won''t make progress.','["If students won''t engage with feedback, they won''t make progress.","If students don''t engage with feedback, they won''t make progress.","If students don''t engage with feedback, they would not make progress (Type 2).","If students didn''t engage with feedback, they won''t make progress (mixed)."]','Don''t + base verb (if-clause); won''t + base verb (result).','medium'),
  (cid,8,53,'gap_fill','Unless you ___ (take) notes during the lecture, you ___ (not/remember) the key points.','take / won''t remember',NULL,'"Unless + present simple" = if you don''t... Won''t in result clause.','medium'),
  (cid,8,54,'multiple_choice','Choose the most natural academic version of a Type 1 conditional.','If the study is replicated with a larger sample, the findings will be more generalizable.','["If the study will be replicated with a larger sample, the findings will be more generalizable.","If the study is replicated with a larger sample, the findings will be more generalizable.","If the study was replicated with a larger sample, the findings would be more generalizable (Type 2).","If the study has been replicated, the findings are more generalizable."]','If + present passive simple, will + base verb in academic context.','hard'),
  (cid,8,55,'gap_fill','The program ___ (not/continue) unless enough students ___ (enrol).','won''t continue / enrol',NULL,'"Unless + positive present simple" for negative condition.','medium'),
  (cid,8,56,'multiple_choice','Which sentence correctly uses "as long as" in an academic context?','The methodology will be considered valid as long as the sample is representative.','["The methodology is considered valid as long as the sample will be representative.","The methodology will be considered valid as long as the sample is representative.","The methodology would be considered valid as long as the sample is representative.","The methodology will be considered valid as long as the sample was representative."]','As long as + present simple, will + base verb.','hard'),

  -- BLOCK 9: TOEFL academic contexts
  (cid,9,57,'multiple_choice','[TOEFL Reading] Which sentence from an academic passage uses Type 1 conditional correctly?','If deforestation rates continue at the current pace, biodiversity loss will accelerate dramatically.','["If deforestation rates will continue, biodiversity loss will accelerate.","If deforestation rates continue at the current pace, biodiversity loss will accelerate dramatically.","If deforestation rates continued, biodiversity loss would accelerate.","If deforestation rates continue, biodiversity loss accelerates."]','If + present simple, will + base verb for academic projections.','medium'),
  (cid,9,58,'gap_fill','[TOEFL Listening] The professor states: "If we ___ (not/address) antibiotic resistance now, we ___ (face) a major public health crisis."','don''t address / will face',NULL,'Type 1 conditional in academic warning.','hard'),
  (cid,9,59,'multiple_choice','[TOEFL Reading] Complete the academic sentence: "Provided that investment in infrastructure increases, economic growth ___."','will follow','["would follow (Type 2)","follows (Zero conditional)","will follow","followed"]','"Provided that" + present simple, will + base verb.','hard'),
  (cid,9,60,'gap_fill','[TOEFL Listening] The lecturer says: "If the central bank ___ (raise) interest rates, inflation ___ (decrease) but unemployment ___ (may/rise)."','raises / will decrease / may rise',NULL,'Type 1 with will and may for certainty/possibility in result clause.','hard'),
  (cid,9,61,'multiple_choice','[TOEFL Reading] Which academic sentence correctly uses "unless"?','Unless stricter environmental regulations are introduced, carbon emissions will continue to rise.','["Unless stricter regulations won''t be introduced, emissions will rise (double negative error).","Unless stricter environmental regulations are introduced, carbon emissions will continue to rise.","Unless stricter regulations are introduced, carbon emissions would continue to rise (Type 2).","Unless if stricter regulations are introduced, emissions will rise (unless if = error)."]','Unless + positive present simple, will + base verb.','hard'),
  (cid,9,62,'gap_fill','[TOEFL Reading] If researchers ___ (fail) to control for confounding variables, the conclusions ___ (not/be) valid.','fail / won''t be',NULL,'Type 1 conditional for methodological warnings in academic writing.','hard'),
  (cid,9,63,'multiple_choice','[TOEFL Listening] The professor warns: "If students ___ not cite their sources, they ___ face academic misconduct procedures."','do / will','["will / will","do / would","do / will","are / will"]','If + do not (present simple), will for academic warning.','hard'),

  -- BLOCK 10: TOEFL production tasks
  (cid,10,64,'multiple_choice','[TOEFL Reading] Which sentence best concludes an argument about climate policy using Type 1 conditional?','If world leaders commit to net-zero targets, the worst effects of climate change will be mitigated.','["If world leaders committed to net-zero targets, the worst effects would be mitigated (Type 2 — hypothetical).","If world leaders commit to net-zero targets, the worst effects of climate change will be mitigated.","If world leaders will commit to net-zero targets, the worst effects will be mitigated (error).","If world leaders have committed to net-zero targets, the worst effects are mitigated."]','Real/possible outcome → Type 1: commit (present simple), will be mitigated.','hard'),
  (cid,10,65,'gap_fill','[TOEFL Reading] The conclusion states: "Unless governments ___ (take) immediate action, the window for limiting warming to 1.5°C ___ (close). Provided that emissions ___ (peak) before 2030, scientists believe the target ___ (remain) achievable."','take / will close / peak / will remain',NULL,'Unless + present simple and provided that + present simple → will in main clauses.','hard'),
  (cid,10,66,'multiple_choice','[TOEFL Speaking — 45s] You are asked: "What will happen to universities if more students choose online education?" Which answer best uses Type 1 conditional?','If more students choose online education, traditional universities will need to adapt their models, offer more flexible programs, and reduce tuition fees to remain competitive.','["If more students chose online education, traditional universities would need to adapt (Type 2).","If more students choose online education, traditional universities will need to adapt their models, offer more flexible programs, and reduce tuition fees to remain competitive.","If more students will choose online education, universities will need to adapt.","If more students choose online education, universities needed to adapt."]','If + present simple, will + base verb for realistic future prediction.','hard'),
  (cid,10,67,'production','[TOEFL Speaking — 45s] Respond to this prompt: "What will happen to public health if governments cut funding to medical research?" Use Type 1 conditionals, at least one "unless" structure, and one "provided that" construction in your response.','',NULL,'Type 1: if + present simple, will/may/might/can + base verb; unless + positive; provided that + present simple.','hard'),
  (cid,10,68,'production','[TOEFL Writing] Write a paragraph (4-5 sentences) making policy recommendations about environmental sustainability. Use: at least 2 Type 1 conditionals, 1 unless structure, and 1 zero conditional for a scientific fact.','',NULL,'Mix Type 1 (policy recommendations) and zero conditional (scientific principles) in academic writing.','hard'),
  (cid,10,69,'multiple_choice','[TOEFL Writing] Which sentence is most appropriate in an academic argument about education reform?','If schools integrate critical thinking skills into the curriculum, students will be better prepared for the challenges of the 21st century.','["If schools will integrate critical thinking, students will be better prepared.","If schools integrated critical thinking, students would be better prepared (Type 2 — less assertive).","If schools integrate critical thinking skills into the curriculum, students will be better prepared for the challenges of the 21st century.","If schools have integrated critical thinking, students will be better prepared."]','If + present simple, will + base verb for confident academic recommendation.','hard'),
  (cid,10,70,'production','[TOEFL Writing] Write a 5-sentence paragraph arguing for a specific solution to a problem of your choice (education, health, environment, technology). Use: 2 Type 1 conditionals with different modal verbs in the result clause (will, may, can), 1 unless clause, and distinguish your argument from a hypothetical by explicitly avoiding Type 2 conditionals.','',NULL,'Demonstrate mastery of Type 1 conditional in persuasive academic writing.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
