-- ============================================================
-- SEED: Módulo 22 — Subjunctive Mood (C1)
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'subjunctive';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo subjunctive não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 1: That-Clause Subjunctive – recommend/suggest/insist/demand
  (cid,1,1,'gap_fill','The doctor recommended that the patient _____ (take) the medication twice daily.','take',NULL,'Mandative subjunctive: after "recommend that," use the base form of the verb (no -s, no "should"). → that the patient take.','medium'),
  (cid,1,2,'multiple_choice','The committee insisted that the report _____ submitted before the end of the fiscal year.','be','["is","was","be","should be"]','Subjunctive: after "insist that," use the base form "be" (not "is" or "was"). Both "be" and "should be" are possible; "be" is the pure subjunctive.','hard'),
  (cid,1,3,'gap_fill','The professor suggested that each student _____ (submit) a draft outline before beginning the full essay.','submit',NULL,'Mandative subjunctive: "suggest that + subject + base verb." No -s ending, no auxiliaries. → that each student submit.','medium'),
  (cid,1,4,'multiple_choice','The regulations demand that every researcher _____ a data management plan before the project begins.','file','["files","filed","file","has filed"]','Subjunctive: "demand that + subject + base verb (no -s)." → that every researcher file a data management plan.','hard'),
  (cid,1,5,'gap_fill','The board requires that all contractors _____ (carry) liability insurance before starting work.','carry',NULL,'Mandative subjunctive: "require that + subject + base verb." → that all contractors carry.','medium'),
  (cid,1,6,'multiple_choice','The ethics committee proposed that the study _____ redesigned to include a control group.','be','["is","was","be","is being"]','Subjunctive: "propose that + subject + base form be" → that the study be redesigned. Passive subjunctive.','hard'),
  (cid,1,7,'gap_fill','The supervisor requested that the intern _____ (not share) the preliminary data with external parties.','not share',NULL,'Negative subjunctive: "requested that + subject + not + base verb." → that the intern not share.','hard'),
  (cid,1,8,'multiple_choice','Which sentence correctly uses the mandative subjunctive?','The judge ordered that the defendant be held without bail.','["The judge ordered that the defendant is held without bail.","The judge ordered that the defendant was held without bail.","The judge ordered that the defendant be held without bail.","The judge ordered that the defendant should hold without bail."]','Mandative subjunctive: "ordered that + subject + base form be." → that the defendant be held (passive subjunctive).','hard'),

  -- BLOCK 2: That-Clause Subjunctive – urge/request/recommend/move (formal)
  (cid,2,9,'gap_fill','It is essential that the data _____ (verify) by an independent auditor before publication.','be verified',NULL,'Impersonal subjunctive: "It is essential that + subject + base passive." → that the data be verified.','hard'),
  (cid,2,10,'multiple_choice','It is vital that every member of the team _____ aware of the safety protocols.','be','["is","was","be","should"]','Impersonal subjunctive: "It is vital that + subject + base verb be." → that every member be aware.','hard'),
  (cid,2,11,'gap_fill','The report urged that immediate action _____ (take) to address the water crisis.','be taken',NULL,'"Urge that + subject + passive base verb." → that immediate action be taken. Passive subjunctive.','hard'),
  (cid,2,12,'multiple_choice','It is important that the results _____ interpreted within the context of the study''s limitations.','be','["are","were","be","being"]','Impersonal subjunctive: "It is important that + subject + base passive be." → that the results be interpreted.','hard'),
  (cid,2,13,'gap_fill','The motion moved that the meeting _____ (adjourn) until further notice.','be adjourned',NULL,'Parliamentary subjunctive: "moved that + subject + passive base verb." → that the meeting be adjourned.','hard'),
  (cid,2,14,'multiple_choice','It is crucial that the government _____ additional funding for public health infrastructure.','allocate','["allocates","allocated","allocate","is allocating"]','Impersonal subjunctive: "It is crucial that + subject + base verb (no -s)." → that the government allocate.','hard'),
  (cid,2,15,'gap_fill','Experts recommend that each individual _____ (receive) at least 150 minutes of moderate exercise per week.','receive',NULL,'Mandative subjunctive: "recommend that + subject + base verb." → that each individual receive.','medium'),
  (cid,2,16,'multiple_choice','Which is the correct formal academic version?','It is imperative that policymakers address the root causes of poverty.','["It is imperative that policymakers addresses the root causes.","It is imperative that policymakers addressed the root causes.","It is imperative that policymakers address the root causes of poverty.","It is imperative that policymakers are addressing the root causes."]','Impersonal subjunctive: "It is imperative that + subject + base verb (no -s)." → that policymakers address.','hard'),

  -- BLOCK 3: Were-Subjunctive in Conditionals
  (cid,3,17,'gap_fill','If I _____ (be) the committee chair, I would propose a complete restructuring of the funding model.','were',NULL,'Subjunctive "were" is used in second conditional for all persons (not "was"). → If I were the committee chair.','medium'),
  (cid,3,18,'multiple_choice','If she _____ to resign, the organization would face a significant leadership crisis.','were','["was","is","were","would be"]','Subjunctive "were + infinitive" for a hypothetical event. → If she were to resign (formal conditional).','hard'),
  (cid,3,19,'gap_fill','He speaks as if he _____ (be) the only expert in the field.','were',NULL,'"As if" + subjunctive: "were" for all persons to describe an imagined/untrue situation. → as if he were.','hard'),
  (cid,3,20,'multiple_choice','If the technology _____ more affordable, it would be adopted much more widely.','were','["was","is","were","would be"]','Subjunctive "were" (not "was") in second conditional for formal/academic writing. → If the technology were more affordable.','medium'),
  (cid,3,21,'gap_fill','She talks as if the problem _____ (already / solve).','were already solved',NULL,'"As if + were + past participle (passive subjunctive)" for an imagined untrue state. → as if the problem were already solved.','hard'),
  (cid,3,22,'multiple_choice','If this _____ a different era, the discovery would have been considered miraculous.','were','["was","is","were","had been"]','Subjunctive "were" is preferred in formal writing for second conditional. → If this were a different era.','medium'),
  (cid,3,23,'gap_fill','If the government _____ (be) to reverse the policy, the economic consequences would be severe.','were',NULL,'"If + subject + were + to + base verb" = formal conditional using were-subjunctive. → If the government were to reverse.','hard'),
  (cid,3,24,'multiple_choice','Which sentence uses the were-subjunctive correctly?','Were I in a position of authority, I would prioritize environmental legislation.','["Was I in a position of authority, I would prioritize environmental legislation.","If I am in a position of authority, I prioritize environmental legislation.","Were I in a position of authority, I would prioritize environmental legislation.","Were I be in a position of authority, I would prioritize."]','Inverted were-subjunctive: "Were + subject + in/at..." replaces "If + subject + were." Formal and C1 level.','hard'),

  -- BLOCK 4: Fixed Phrases & Formal Subjunctive Expressions
  (cid,4,25,'multiple_choice','The laboratory will continue its work, come what _____.','may','["will","might","may","can"]','"Come what may" is a fixed subjunctive phrase meaning "whatever happens." The base form "may" is used.','hard'),
  (cid,4,26,'gap_fill','If _____ (need) be, the experiment can be repeated with a larger sample size.','need',NULL,'"If need be" is a fixed subjunctive phrase meaning "if necessary." "Need" appears as a bare infinitive.','hard'),
  (cid,4,27,'multiple_choice','The council voted to proceed with the project. So _____ it.','be','["is","was","be","let it be"]','"So be it" is a fixed subjunctive phrase meaning "let this be the case" or "I accept this outcome."','hard'),
  (cid,4,28,'gap_fill','Heaven _____ (forbid) that we should make the same mistake again.','forbid',NULL,'"Heaven forbid" is a fixed subjunctive expression of strong wish/fear. → Heaven forbid that we should make.','hard'),
  (cid,4,29,'multiple_choice','Long _____ the republic!','live','["lives","lived","live","to live"]','"Long live + subject" is a subjunctive expression of strong wish (survival/prosperity). Base form used for all persons.','hard'),
  (cid,4,30,'gap_fill','Far _____ (be) it from me to question the committee''s judgment, but this decision seems premature.','be',NULL,'"Far be it from me to" is a fixed subjunctive phrase used to introduce a polite objection.','hard'),
  (cid,4,31,'multiple_choice','_____ the research findings be published before the study has completed its peer review process?','Lest','["If","Lest","Unless","Whether"]','"Lest" = "in case / for fear that." → Lest the findings be published (subjunctive: "be published"). Formal warning.','hard'),
  (cid,4,32,'gap_fill','The manager spoke to the team, lest there _____ (be) any misunderstanding about the new procedures.','be',NULL,'"Lest + subject + be (subjunctive)" → lest there be any misunderstanding. Fixed subjunctive with "lest."','hard'),

  -- BLOCK 5: TOEFL Academic – Subjunctive in Reading
  (cid,5,33,'gap_fill','[TOEFL Reading] The review board recommended that the clinical trial _____ (halt) pending further investigation.','be halted',NULL,'Mandative passive subjunctive: "recommend that + subject + be + past participle." → that the trial be halted.','hard'),
  (cid,5,34,'multiple_choice','[TOEFL Reading] The policy document states that every institution _____ a formal data retention strategy within the next fiscal year.','adopt','["adopts","adopted","adopt","is adopting"]','Mandative subjunctive: "states that + subject + base verb." → that every institution adopt.','hard'),
  (cid,5,35,'gap_fill','[TOEFL Reading] It is imperative that the methodology _____ (describe) in sufficient detail to allow replication.','be described',NULL,'"It is imperative that + subject + passive base verb." → that the methodology be described.','hard'),
  (cid,5,36,'multiple_choice','[TOEFL Reading] "The authors argue that future research _____ the long-term effects of the intervention on diverse populations."','examine','["examines","examined","examine","should examine"]','Mandative subjunctive: "argue that + subject + base verb." → that future research examine. "Should examine" is the British alternative.','hard'),
  (cid,5,37,'gap_fill','[TOEFL Listening] The professor insisted that no conclusions _____ (draw) until all the data had been reviewed.','be drawn',NULL,'"Insist that + subject + passive subjunctive." → that no conclusions be drawn.','hard'),
  (cid,5,38,'multiple_choice','[TOEFL Reading] "If the current model _____ to be accurate, it would predict a 3°C rise in global temperatures by 2100."','were','["was","is","were","would be"]','Were-subjunctive in formal conditional. → If the current model were to be accurate (second conditional).','hard'),
  (cid,5,39,'gap_fill','[TOEFL Reading] The funding agency requires that all grant recipients _____ (submit) annual progress reports.','submit',NULL,'"Require that + subject + base verb (no -s)." → that all grant recipients submit.','medium'),
  (cid,5,40,'multiple_choice','[TOEFL Listening] The professor used the mandative subjunctive to express:','a recommendation, demand, or requirement expressed through a that-clause','["uncertainty about a future event","a condition in the past","a recommendation, demand, or requirement expressed through a that-clause","a habitual action in the past"]','The mandative subjunctive appears after verbs of recommending, demanding, suggesting, etc. in that-clauses.','medium'),

  -- BLOCK 6: TOEFL Academic – Subjunctive vs Indicative
  (cid,6,41,'multiple_choice','[TOEFL Reading] Which sentence uses the subjunctive correctly?','The committee suggested that the findings be presented at the annual conference.','["The committee suggested that the findings are presented.","The committee suggested that the findings was presented.","The committee suggested that the findings be presented at the annual conference.","The committee suggested presenting the findings."]','Subjunctive passive: "be presented" (not "are presented" or "was presented"). → that the findings be presented.','hard'),
  (cid,6,42,'gap_fill','[TOEFL Reading] The director proposed that a new ethics framework _____ (develop) before any further trials proceed.','be developed',NULL,'Mandative passive subjunctive: "propose that + subject + be + past participle." → that a new ethics framework be developed.','hard'),
  (cid,6,43,'multiple_choice','[TOEFL Reading] Identify the sentence where the subjunctive is incorrectly used.','The teacher demanded that her students submitted their work on time.','["The teacher demanded that her students submit their work on time.","It is essential that the data be independently verified.","The teacher demanded that her students submitted their work on time.","Were the results to be confirmed, it would be a breakthrough."]','"Demanded that her students submitted" is wrong. Subjunctive requires the base form: "submit" not "submitted."','hard'),
  (cid,6,44,'gap_fill','[TOEFL Listening] The professor noted: "It is crucial that future studies _____ (control) for socioeconomic status as a confounding variable."','control',NULL,'"It is crucial that + subject + base verb (no -s)." → that future studies control for.','hard'),
  (cid,6,45,'multiple_choice','[TOEFL Reading] "The treaty stipulates that each signatory nation _____ its carbon emissions by a minimum of 30% within ten years."','reduce','["reduces","reduced","reduce","is reducing"]','Mandative subjunctive: "stipulate that + subject + base verb." → that each nation reduce.','hard'),
  (cid,6,46,'gap_fill','[TOEFL Reading] If the hypothesis _____ (be) correct, it would challenge decades of established scientific thinking.','were',NULL,'Were-subjunctive in formal second conditional. → If the hypothesis were correct, it would challenge.','hard'),
  (cid,6,47,'multiple_choice','[TOEFL Listening] "The researcher argued as if the result _____ already settled, though in fact it remained highly contested."','were','["was","is","were","has been"]','"As if + were" = subjunctive for an untrue/imagined situation. → argued as if the result were already settled.','hard'),
  (cid,6,48,'gap_fill','[TOEFL Reading] It is recommended that the sample size _____ (increase) in future studies to improve statistical power.','be increased',NULL,'"It is recommended that + subject + passive base verb." → that the sample size be increased.','hard'),

  -- BLOCK 7: TOEFL Academic – Academic Formal Register
  (cid,7,49,'multiple_choice','[TOEFL Reading] In American English academic writing, the mandative subjunctive is preferred over "should + base verb" because it:','is more concise and is the standard form in formal American academic prose','["sounds more conversational","is more commonly understood by international readers","is more concise and is the standard form in formal American academic prose","is easier to conjugate"]','In US academic writing, "suggest that he be" is preferred over "suggest that he should be." British English more commonly uses "should."','hard'),
  (cid,7,50,'gap_fill','[TOEFL Reading] The academic editor demanded that the passive voice _____ (use) more consistently throughout the paper.','be used',NULL,'"Demand that + subject + be + past participle." Passive subjunctive. → that the passive voice be used.','hard'),
  (cid,7,51,'multiple_choice','[TOEFL Reading] Which sentence is most appropriate for a formal academic paper?','It is essential that all data be made publicly available upon publication.','["It is essential that all data should be made publicly available upon publication.","It is essential that all data is made publicly available upon publication.","It is essential that all data be made publicly available upon publication.","It is essential that all data are made publicly available upon publication."]','Pure mandative subjunctive "be made" is preferred over "should be made" in formal US academic writing.','hard'),
  (cid,7,52,'gap_fill','[TOEFL Listening] The committee voted that the resolution _____ (adopt) by a two-thirds majority.','be adopted',NULL,'Parliamentary/formal subjunctive: "voted that + subject + be + past participle." → that the resolution be adopted.','hard'),
  (cid,7,53,'multiple_choice','[TOEFL Reading] "Whether he _____ right or wrong, the outcome of the debate will shape future policy for years to come."','be','["is","was","be","might be"]','"Whether + subject + be" = subjunctive in formal concessive clauses. → Whether he be right or wrong.','hard'),
  (cid,7,54,'gap_fill','[TOEFL Reading] _____ (be) that as it may, the committee must still address the underlying structural issues.','Be',NULL,'"Be that as it may" is a fixed subjunctive concessive phrase meaning "regardless of that." → Be that as it may.','hard'),
  (cid,7,55,'multiple_choice','[TOEFL Reading] The court ordered that all evidence _____ sealed until further notice.','be','["is","was","be","should be"]','Mandative passive subjunctive: "ordered that + subject + be + past participle." → that all evidence be sealed.','hard'),
  (cid,7,56,'gap_fill','[TOEFL Reading] If _____ (need) be, the committee has the authority to call an emergency session.','need',NULL,'"If need be" = fixed subjunctive expression for "if necessary." The base form "need" is used without an auxiliary.','hard'),

  -- BLOCK 8: TOEFL Academic – Mixed Subjunctive Practice
  (cid,8,57,'multiple_choice','[TOEFL Reading] "It is vital that the government _____ immediate steps to address the housing crisis."','take','["takes","took","take","is taking"]','Impersonal subjunctive: "It is vital that + subject + base verb (no -s)." → that the government take.','hard'),
  (cid,8,58,'gap_fill','[TOEFL Reading] The review committee recommended that the trial _____ (extend) for an additional 12 months.','be extended',NULL,'Passive mandative subjunctive: "recommended that + subject + be + past participle." → that the trial be extended.','hard'),
  (cid,8,59,'multiple_choice','[TOEFL Listening] "If the data _____ more representative, the conclusions would carry greater weight." Complete correctly.','were','["was","is","were","had been"]','Were-subjunctive for formal second conditional. → If the data were more representative.','hard'),
  (cid,8,60,'gap_fill','[TOEFL Reading] The motion proposed that a new subcommittee _____ (establish) to oversee the implementation of the reforms.','be established',NULL,'"Proposed that + subject + be + past participle." → that a new subcommittee be established.','hard'),
  (cid,8,61,'multiple_choice','[TOEFL Reading] "The supervisor insisted that each intern _____ a weekly progress report."','submit','["submits","submitted","submit","is submitting"]','Mandative subjunctive: "insist that + subject + base verb." → that each intern submit.','hard'),
  (cid,8,62,'gap_fill','[TOEFL Reading] Come what _____, the research team is committed to completing the project.','may',NULL,'"Come what may" = fixed subjunctive expression. "May" is the subjunctive base form used without a subject.','hard'),
  (cid,8,63,'multiple_choice','[TOEFL Reading] "Lest there _____ any doubt about the committee''s position, the statement was issued in writing."','be','["is","was","be","are"]','"Lest there be" = subjunctive after "lest" (for fear that). → Lest there be any doubt.','hard'),
  (cid,8,64,'gap_fill','[TOEFL Reading] If the new treatment _____ (be) to fail in the final phase, the company would face enormous financial losses.','were',NULL,'"If + subject + were + to + base verb" = formal conditional with were-subjunctive. → If the treatment were to fail.','hard'),

  -- BLOCK 9: TOEFL Speaking Tasks
  (cid,9,65,'production','[TOEFL Speaking — 45s] The reading argues that universities should make academic publishing open-access. The professor agrees but insists that certain conditions be met first. Summarize the professor''s position and explain how it relates to the reading. Try to use one subjunctive construction in your response. You have 45 seconds.','',NULL,'Target: "The professor insists that universities be given..." "It is essential that publishers..." "The reading suggests that all research be..."','hard'),
  (cid,9,66,'production','[TOEFL Speaking — 45s] If you were a university president, what changes would you make to improve the educational experience for students? Describe two changes you would implement, and explain why they are important. Use "If I were..." and subjunctive forms where possible. You have 45 seconds.','',NULL,'Practice: "If I were the university president, I would require that all students be..." "It is vital that students have access to..."','hard'),
  (cid,9,67,'production','[TOEFL Speaking — 45s] Some people argue that it is essential that students be taught critical thinking skills from an early age rather than focusing on memorization. Do you agree or disagree? Explain your view with reasons and examples. You have 45 seconds.','',NULL,'Use: "It is essential that critical thinking be..." "I would recommend that teachers focus on..." "If education were to prioritize..."','hard'),

  -- BLOCK 10: TOEFL Writing Tasks
  (cid,10,68,'production','[TOEFL Writing] Write a formal essay (150+ words) in response to the following policy recommendation: "It is essential that governments mandate that all new buildings meet strict energy efficiency standards." Agree or disagree. Use at least THREE mandative subjunctive constructions (e.g., "require that... be," "it is vital that... adopt," "recommend that... implement") in your essay.','',NULL,'Target: "It is essential that all new buildings be designed..." "Policymakers should insist that developers meet..." "It is vital that the construction industry adopt..."','hard'),
  (cid,10,69,'production','[TOEFL Writing] Integrated task: The reading passage argues that international trade agreements demand that participating countries reduce agricultural subsidies. The lecture presents evidence that were this requirement to be implemented immediately, developing countries would face severe food insecurity. Write a 150+ word response summarizing the relationship between the reading and the lecture. Use subjunctive forms where appropriate.','',NULL,'Target: "The reading demands that countries reduce..." "The professor argues that were this to happen..." "It is crucial that an adjustment period be granted..."','hard'),
  (cid,10,70,'production','[TOEFL Writing] Write a 200+ word formal position paper arguing for or against the following: "It is imperative that all scientific research funded by public money be made freely available to the public." Use at least FOUR different subjunctive structures: (1) mandative subjunctive, (2) passive mandative subjunctive, (3) were-subjunctive, (4) a fixed subjunctive phrase. Label each one.','',NULL,'Four targets: (1) "it is imperative that researchers make..." (2) "it is essential that data be shared..." (3) "If this policy were to be adopted..." (4) "Come what may, open access must..."','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
