-- ============================================================
-- SEED EXT 4: Módulo 12 — Conditional 2 & 3 (ex 145-215)
-- Novos tópicos: mixed conditionals avançado, condicionais
-- implícitas/nominais, hedging academic com would, TOEFL tasks
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'conditional-2-3';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo conditional-2-3 não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 41: Mixed conditional avançado (present ← past)
  (cid,41,145,'multiple_choice','What type of conditional is "If they had invested in renewable energy earlier, the country would not be facing an energy crisis now"?','Mixed conditional: past if-clause, present result clause.','["Type 2 (present unreal)","Type 3 (past unreal)","Mixed conditional: past if-clause, present result clause.","Zero conditional"]','Mixed: If + PP (past unreal) + would + base (present unreal result).','medium'),
  (cid,41,146,'gap_fill','If governments _____ (take) action on deforestation in the 1980s, we _____ (not/face) such severe biodiversity loss today.','had taken / would not be facing',NULL,'Mixed conditional: past unreal if + would be + -ing for present result.','hard'),
  (cid,41,147,'gap_fill','If the early clinical trials _____ (not/show) such promising results, the drug _____ (not currently/receive/passive) emergency approval.','had not shown / would not currently be receiving',NULL,'Mixed: past unreal if + present continuous result with "currently."','hard'),
  (cid,41,148,'multiple_choice','Which mixed conditional correctly shows that a PAST event affects a PRESENT state?','If the company had diversified its revenue streams earlier, it would not be facing bankruptcy today.','["If the company diversified earlier, it would not face bankruptcy today (Type 2 — present only).","If the company had diversified earlier, it would not have faced bankruptcy (Type 3 — past result only).","If the company had diversified its revenue streams earlier, it would not be facing bankruptcy today.","If the company had diversified earlier, it faces no bankruptcy today (wrong main clause)."]','Mixed: PP in if-clause + would be + -ing in main clause = past cause → present consequence.','hard'),
  (cid,41,149,'gap_fill','If I _____ (not/choose) this research area five years ago, I _____ (probably/not/work) in this field today.','had not chosen / would probably not be working',NULL,'Mixed conditional: past choice + present ongoing situation.','hard'),

  -- BLOCK 42: Mixed conditional (past ← present)
  (cid,42,150,'multiple_choice','What type of conditional is "If I were more disciplined, I would have finished the project by now"?','Mixed conditional: present unreal if-clause, past result clause.','["Type 2 (present unreal, present result)","Type 3 (past unreal, past result)","Mixed conditional: present unreal if-clause, past result clause.","Inverted conditional"]','Mixed: If + were (present unreal) + would + have + PP (past unreal result).','hard'),
  (cid,42,151,'gap_fill','If the algorithm _____ (be) more sophisticated, it _____ (detect) the anomaly before it _____ (cause) problems.','were / would have detected / caused',NULL,'Mixed: present unreal condition + past unreal result.','hard'),
  (cid,42,152,'multiple_choice','Which sentence correctly mixes a PRESENT CONDITION with a PAST RESULT?','If she were a native speaker, she would have understood the legal document without a translation.','["If she had been a native speaker, she would understand the legal document (Type 3 if + Type 2 result — inverted mixed).","If she were a native speaker, she would have understood the legal document without a translation.","If she is a native speaker, she would have understood the legal document.","If she were a native speaker, she would understand the legal document (Type 2, present result — correct but different meaning)."]','If + were (present unreal) + would have + PP (past result she missed).','hard'),
  (cid,42,153,'gap_fill','If the system _____ (be) more secure by design, the data breach _____ (not/occur) last month.','were / would not have occurred',NULL,'Present unreal system + past unreal event that happened.','hard'),

  -- BLOCK 43: Condicionais implícitas (without if)
  (cid,43,154,'gap_fill','With better institutional support, the research team _____ (complete) the project on time.','would have completed / would complete',NULL,'"With + NP" = implicit Type 2 or 3 conditional without "if."','hard'),
  (cid,43,155,'multiple_choice','Which implicit conditional matches "If you had asked earlier, I would have helped"?','Asked earlier, I would have helped.','["Earlier asking, I would have helped.","Asked earlier, I would have helped.","If I would have helped if asked earlier.","Had you asked earlier, I would have helped. (This is an INVERTED conditional, not an implicit one.)"]','"Asked earlier" = reduced conditional. "Had you asked earlier" = inverted conditional (both correct alternatives to if-clause).','hard'),
  (cid,43,156,'gap_fill','_____ (invert) the if-clause: "If you had followed the protocol, this problem would not have arisen."','Had you followed the protocol, this problem would not have arisen.',NULL,'Inverted Type 3: Had + subject + PP + comma + main clause.','hard'),
  (cid,43,157,'gap_fill','_____ (invert): "If she were in charge, the decision-making process would be faster."','Were she in charge, the decision-making process would be faster.',NULL,'Inverted Type 2: Were + subject + adjective/NP + comma + main clause.','hard'),
  (cid,43,158,'multiple_choice','Which inverted conditional correctly replaces "If there should be any complications, please contact us immediately"?','Should there be any complications, please contact us immediately.','["Were there any complications, please contact us immediately (were = present, should = future possibility).","Had there been any complications, please contact us immediately.","Should there be any complications, please contact us immediately.","If should there be any complications, please contact us immediately."]','"Should + subject + base verb" = inverted conditional for future possibility/formality.','medium'),

  -- BLOCK 44: Hedging acadêmico com would
  (cid,44,159,'multiple_choice','Why does academic writing use "would" rather than "will" in sentences like "This approach would reduce costs significantly"?','To hedge the claim — indicating that the outcome is conditional on assumptions, not certain.','["Would is past tense of will","To hedge the claim — indicating that the outcome is conditional on assumptions, not certain.","Would is more formal than will","To describe a past habit"]','Academic "would" without explicit if-clause = implicit conditional + epistemic hedging.','medium'),
  (cid,44,160,'gap_fill','A carbon tax _____ (generate) significant revenue that _____ (use/passive) to fund renewable energy research.','would generate / could be used',NULL,'Hypothetical policy proposal using conditional hedging.','medium'),
  (cid,44,161,'gap_fill','Under these conditions, species diversity _____ (decline) significantly, _____ (have) cascading effects on ecosystem services.','would decline / having',NULL,'Hypothetical consequence + participial clause for result.','hard'),
  (cid,44,162,'multiple_choice','Which sentence shows MOST appropriate use of conditional hedging in academic writing?','This policy would be more effective if it incorporated incentive structures aligned with behavioral economics research.','["This policy is more effective if it incorporates incentive structures.","This policy will be more effective if it incorporates incentive structures.","This policy would be more effective if it incorporated incentive structures aligned with behavioral economics research.","This policy could be more effective if it may incorporate incentive structures."]','Type 2 = hedge: "would be/incorporated" for policy that does not yet exist.','medium'),

  -- BLOCK 45: TOEFL Reading
  (cid,45,163,'multiple_choice','[TOEFL Reading] "If the dam had been designed with modern seismic standards, it would not have failed during the 1994 earthquake." This sentence implies:','The dam failed because it was not built to modern seismic standards.','["Modern seismic standards did not exist in 1994","The dam survived the earthquake","The dam failed because it was not built to modern seismic standards.","Future dams will be designed with better standards"]','Type 3 conditional = past unreal: failing implies the condition (lack of modern standards) was real.','easy'),
  (cid,45,164,'gap_fill','[TOEFL Reading] "Without the contributions of amateur naturalists, Darwin _____ (not/compile) the breadth of evidence _____ (require) to support his theory." Best forms?','would not have compiled / required',NULL,'Type 3 conditional implicit (without + NP) + reduced passive RC.','hard'),
  (cid,45,165,'multiple_choice','[TOEFL Reading] "Were the scientific community to accept this hypothesis, it would transform the entire theoretical framework of the field." This inverted conditional expresses:','A currently hypothetical scenario whose consequences are outlined.','["A fact that is currently true","A past event and its consequences","A currently hypothetical scenario whose consequences are outlined.","A threat or warning"]','Inverted Type 2: Were + to + base = formal, hypothetical present/future condition.','hard'),
  (cid,45,166,'gap_fill','[TOEFL Reading] "Had the industrial revolution not occurred when it did, economic growth _____ (remain) far slower and the global standard of living _____ (look) very different today." Best forms?','would have remained / would look',NULL,'Mixed conditional: past if + would have (for past trajectory) + would (for present state).','hard'),

  -- BLOCK 46: TOEFL Speaking
  (cid,46,167,'production','[TOEFL Speaking — 45s] A reading discusses a past policy failure. Using Type 3 and mixed conditionals, explain how different decisions could have changed the outcome.','',NULL,'The reading describes the collapse of several regional banks in the 1980s. Had regulators applied stricter capital requirements in the years preceding the crisis, the banks would have been forced to maintain larger safety buffers and would not have been as vulnerable to the real estate market collapse. Had early warning signs — particularly the rapid deterioration in loan quality — been taken more seriously, intervention would have occurred earlier and the contagion would not have spread as widely as it did. From a mixed conditional perspective: if the regulatory framework were more robust today, reflecting the lessons that were available from these events, we would not be having similar conversations about regulatory inadequacy in the aftermath of more recent bank failures.','hard'),
  (cid,46,168,'production','[TOEFL Speaking — 45s] Discuss how your life would have been different if you had made a different major choice at university. Use Type 3, mixed conditionals, and inverted conditionals.','',NULL,'Had I chosen engineering rather than social science at the beginning of my undergraduate program, my career path would have diverged significantly. I would have developed a fundamentally different analytical toolkit — one based on quantitative modeling and systems design rather than qualitative analysis and theoretical critique. The questions I ask would be different today, and the professional community I belong to would be entirely different. Had I not enrolled in the social theory course that first year, I would not have encountered the intellectual framework that has guided most of my subsequent work. Mixed conditionals make these counterfactuals interesting: if I were an engineer, I would have already applied for very different positions and would not be completing this research degree. Were I to have access to parallel lives, I would be genuinely curious to see where the engineering path would have taken me — though I suspect I would not have found it as engaging.','hard'),

  -- BLOCK 47: TOEFL Writing
  (cid,47,169,'production','[TOEFL Writing — 150 words] Write a body paragraph arguing for a policy intervention using Type 2 conditional (hypothetical present/future) and academic hedging with "would."','',NULL,'Universal access to early childhood education would produce substantial social and economic returns that current cost-benefit analyses consistently underestimate. If governments were to guarantee high-quality early learning environments for all children between the ages of two and five, the long-term benefits — measured in educational attainment, labor market participation, health outcomes, and reduced criminal justice costs — would substantially exceed the initial investment. Research from programs implemented in the United States and Scandinavia suggests that the return on investment in early childhood education ranges from 7:1 to 13:1 when long-term benefits are properly discounted. Were policymakers to incorporate this evidence into budget allocation decisions, early childhood education would rank among the highest-return investments available to government. The primary obstacle is not economic but political: the benefits materialize over decades, while the costs appear in the immediate budget cycle.','hard'),
  (cid,47,170,'production','[TOEFL Writing — Error Correction] Fix conditional errors: "If scientists would have acted sooner, the epidemic would be contained now. Were the government to acted immediately, the crisis may be averted. If I was richer, I would have donated more to research. Without better data, we cannot have made better decisions."','',NULL,'would have acted → had acted (if-clause Type 3: had + PP, not would have); would be contained → would have been contained OR would still be containable (mixed or pure Type 3); would to acted → to act (were + to + base verb); may be averted → might have been averted (past modal passive for past unreal result); was → were (subjunctive: if + were for unreal conditions); cannot have made → could not have made (past modal: could not have + PP for Type 3 result).','hard'),

  -- BLOCK 48: Consolidação final
  (cid,48,171,'production','[TOEFL Writing — 200 words] Write a paragraph on how a historical scientific discovery could have changed the course of history if it had been made a century earlier. Use Type 3, mixed conditionals, inverted conditionals, and academic hedging.','',NULL,'The discovery of antibiotics represents one of the most consequential medical breakthroughs in human history, and it is sobering to consider how different the world might look had it occurred a century earlier. If penicillin had been developed and mass-produced in the 1830s rather than the 1940s, the demographic trajectory of the nineteenth century would have been profoundly different. Epidemics of bacterial infection — cholera, typhoid, scarlet fever, tuberculosis — claimed millions of lives throughout the 1800s; had effective treatments been available, population growth in urban centers would have accelerated decades sooner. The Industrial Revolution, already well underway in mid-century Britain, might have proceeded faster with a healthier and more numerous workforce. Were it not for the scale of mortality from infectious disease in the nineteenth century, some of the major famines of the period — in which disease killed many of those that hunger weakened — would have been substantially less deadly. Had germ theory and antibiotic therapy arrived together in 1840, the entire pace of economic and social modernization might have compressed into a shorter historical window, with consequences for political development that remain genuinely difficult to predict.','hard'),
  (cid,48,172,'production','[TOEFL Writing — 200 words] Write a body paragraph on hypothetical climate policy. Use Type 2 and Type 3 conditionals, inverted conditionals, and implicit conditionals.','',NULL,'A global carbon pricing mechanism, consistently applied across all major emitting economies, would represent one of the most efficient approaches to reducing greenhouse gas emissions at scale. If all G20 countries were to implement a carbon price of at least $50 per tonne — the level that most economists regard as a minimum signal strong enough to shift investment decisions — the energy transition would accelerate significantly. Renewable energy deployment would expand as fossil fuel costs rose to reflect their true social cost, and innovation incentives in clean technology would intensify. With proper border adjustment mechanisms in place, carbon pricing would not create a competitive disadvantage for early-moving countries relative to those choosing to delay. Had the international community adopted this approach at the first Rio Earth Summit in 1992, atmospheric CO₂ concentrations today would be substantially lower, and the climate system would face considerably less accumulated warming commitment. Were major emerging economies to commit to coordinated carbon pricing at the next climate summit, the credibility of the global emissions reduction pathway would increase substantially — reducing the financing cost of climate investment and accelerating the transition that markets alone cannot deliver at sufficient speed.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
