-- ============================================================
-- SEED: Módulo 13 — Reported Speech (B1)
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'reported-speech';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo reported-speech não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 1: say vs tell
  (cid,1,1,'gap_fill','She ___ that the experiment had been successful.','said',NULL,'"Say" is not followed by an indirect object. She said that...','easy'),
  (cid,1,2,'gap_fill','He ___ the students that the exam would be on Friday.','told',NULL,'"Tell" is followed by a person (indirect object). He told the students that...','easy'),
  (cid,1,3,'multiple_choice','Choose the correct verb: "The professor ___ that the deadline had been extended."','said','["told","said","spoke","talked"]','"Say" + that clause (no indirect object).','easy'),
  (cid,1,4,'multiple_choice','Choose the correct verb: "She ___ me that the results were surprising."','told','["said","told","spoke","said to"]','"Tell" + person + that clause.','easy'),
  (cid,1,5,'gap_fill','He ___ the committee that additional funding would be required.','told',NULL,'"Tell" + indirect object (the committee) + that clause.','easy'),
  (cid,1,6,'multiple_choice','Identify the error: "She said me that the paper was rejected."','said me should be told me','["She should be Her","said should be tells","said me should be told me","paper should be papers"]','"Say" cannot be followed directly by a person. Use "told me."','medium'),
  (cid,1,7,'gap_fill','The lecturer ___ that new research challenges previous assumptions about the topic.','said',NULL,'"Say + that clause" for reporting statements without naming the person being told.','easy'),

  -- BLOCK 2: tense backshift - present → past
  (cid,2,8,'gap_fill','Direct: "I study at Oxford." → Reported: She said she ___ at Oxford.','studied',NULL,'Present simple → past simple in reported speech.','easy'),
  (cid,2,9,'multiple_choice','Change to reported speech: "We are conducting a new study."','They said they were conducting a new study.','["They said they are conducting a new study (no backshift — error).","They said they were conducting a new study.","They said they conducted a new study (wrong tense).","They told they were conducting a new study (wrong verb)."]','Present continuous → past continuous.','medium'),
  (cid,2,10,'gap_fill','Direct: "The hypothesis has been confirmed." → Reported: The researcher reported that the hypothesis ___ been confirmed.','had',NULL,'Present perfect → past perfect in reported speech.','medium'),
  (cid,2,11,'multiple_choice','Which backshift is correct? Direct speech: "I have finished the analysis."','She said she had finished the analysis.','["She said she has finished the analysis (no backshift).","She said she finished the analysis (wrong — should be past perfect).","She said she had finished the analysis.","She said she will finish the analysis (future — wrong)."]','Present perfect → past perfect.','medium'),
  (cid,2,12,'gap_fill','Direct: "The data shows a clear trend." → Reported: The author argued that the data ___ a clear trend.','showed',NULL,'Present simple → past simple.','easy'),
  (cid,2,13,'multiple_choice','Backshift: "We were analyzing the samples." → Reported speech?','He said they had been analyzing the samples.','["He said they were analyzing the samples (no backshift).","He said they had been analyzing the samples.","He said they analyzed the samples (wrong tense).","He said they are analyzing the samples."]','Past continuous → past perfect continuous.','hard'),
  (cid,2,14,'gap_fill','Direct: "The conference is taking place next month." → Reported: She announced that the conference ___ (take) place the following month.','was taking',NULL,'Present continuous → past continuous in reported speech.','medium'),

  -- BLOCK 3: will → would / can → could
  (cid,3,15,'gap_fill','Direct: "I will submit the report tomorrow." → Reported: He said he ___ submit the report the following day.','would',NULL,'"Will" → "would" in reported speech.','easy'),
  (cid,3,16,'multiple_choice','Change: "She can speak four languages." → Reported speech?','He said she could speak four languages.','["He said she can speak four languages (no backshift).","He said she could speak four languages.","He said she would speak four languages (wrong modal).","He said she should speak four languages (wrong modal)."]','"Can" → "could" in reported speech.','medium'),
  (cid,3,17,'gap_fill','Direct: "We won''t publish without further review." → Reported: They stated they ___ publish without further review.','wouldn''t',NULL,'"Won''t" → "wouldn''t" in reported speech.','medium'),
  (cid,3,18,'multiple_choice','Which modal does NOT backshift in reported speech?','should','["will → would","can → could","may → might","should → should (no change)"]','"Should," "would," "could," and "might" do not backshift further.','hard'),
  (cid,3,19,'gap_fill','Direct: "You may use the lab after 5 p.m." → Reported: The professor said we ___ use the lab after 5 p.m.','might',NULL,'"May" → "might" in reported speech.','medium'),
  (cid,3,20,'multiple_choice','Convert: "I must submit my application today." → Reported?','She said she had to submit her application that day.','["She said she must submit her application today (no backshift).","She said she had to submit her application that day.","She said she should submit her application that day.","She said she would have to submit her application today."]','"Must" → "had to" in reported speech for obligation. Time shift: today → that day.','hard'),
  (cid,3,21,'gap_fill','Direct: "The results could be significant." → Reported: She noted that the results ___ be significant.','could',NULL,'"Could" does not backshift — it remains "could" in reported speech.','medium'),

  -- BLOCK 4: time expression changes
  (cid,4,22,'gap_fill','Direct: "I''ll finish it today." → Reported: He said he would finish it ___.','that day',NULL,'"Today" → "that day" in reported speech.','easy'),
  (cid,4,23,'multiple_choice','Convert the time expression: "now" → reported speech','then','["now","then","here","today"]','"Now" → "then" in reported speech.','easy'),
  (cid,4,24,'gap_fill','Direct: "We submitted it yesterday." → Reported: They said they had submitted it ___.','the day before / the previous day',NULL,'"Yesterday" → "the day before" or "the previous day."','medium'),
  (cid,4,25,'multiple_choice','Which time expression change is CORRECT in reported speech?','"last week" → "the previous week"','['"now" → "here"','"last week" → "the previous week"','"tomorrow" → "the next yesterday"','"here" → "now"']','"Last week" → "the previous week" or "the week before."','medium'),
  (cid,4,26,'gap_fill','Direct: "The results will be published next month." → Reported: She said the results would be published ___.','the following month / the next month',NULL,'"Next month" → "the following month" or "the next month" in reported speech.','medium'),
  (cid,4,27,'multiple_choice','Convert: "I started working here two years ago." → Reported?','He said he had started working there two years before.','["He said he started working here two years ago.","He said he had started working there two years before.","He said he has started working there two years ago.","He said he started working there two years ago."]','"Here" → "there"; "ago" → "before"; past simple → past perfect.','hard'),
  (cid,4,28,'gap_fill','Direct: "I''ll present my findings tomorrow." → Reported: She said she would present her findings ___.','the following day / the next day',NULL,'"Tomorrow" → "the following day" or "the next day."','easy'),

  -- BLOCK 5: reporting questions - if/whether
  (cid,5,29,'gap_fill','Direct: "Did you finish the assignment?" → Reported: She asked him ___ he had finished the assignment.','if / whether',NULL,'Yes/no questions in reported speech use "if" or "whether" + normal word order.','medium'),
  (cid,5,30,'multiple_choice','Convert the yes/no question: "Has the paper been peer-reviewed?"','The editor asked whether the paper had been peer-reviewed.','["The editor asked whether had the paper been peer-reviewed (wrong word order).","The editor asked if the paper was peer-reviewed (wrong tense).","The editor asked whether the paper had been peer-reviewed.","The editor asked that the paper had been peer-reviewed (wrong connector)."]','If/whether + subject + verb (normal word order, no inversion).','hard'),
  (cid,5,31,'gap_fill','Direct: "Are you planning to publish the results?" → Reported: The journalist asked ___ I was planning to publish the results.','if / whether',NULL,'If/whether for yes/no reported questions.','medium'),
  (cid,5,32,'multiple_choice','Identify the error: "She asked him did he understand the concept."','The sentence needs "if" or "whether" and normal word order.','["him should be to him","understand should be understood","The sentence needs ''if'' or ''whether'' and normal word order.","did he understand is correct"]','Reported yes/no questions: if/whether + subject + verb (not inverted question form).','hard'),
  (cid,5,33,'gap_fill','Direct: "Can I use the equipment?" → Reported: The student asked ___ she could use the equipment.','if / whether',NULL,'Can → could; yes/no question → if/whether + normal word order.','medium'),
  (cid,5,34,'multiple_choice','Which reported question is correct?','The supervisor asked whether the analysis had been completed.','["The supervisor asked whether had the analysis been completed (inverted — error).","The supervisor asked that the analysis had been completed (statement, not question).","The supervisor asked whether the analysis had been completed.","The supervisor asked if the analysis was completed (tense error — should be had been)."]','Whether + subject + past perfect for reported yes/no question.','hard'),
  (cid,5,35,'gap_fill','Direct: "Will the conference be held online?" → Reported: She asked ___ the conference would be held online.','if / whether',NULL,'Will → would; if/whether for yes/no reported questions.','medium'),

  -- BLOCK 6: reporting questions - wh-words
  (cid,6,36,'gap_fill','Direct: "Where did she publish her research?" → Reported: He asked where she ___ published her research.','had',NULL,'Wh-word + subject + verb (normal order). Past simple → past perfect.','medium'),
  (cid,6,37,'multiple_choice','Convert: "What time does the lecture start?" → Reported?','She asked what time the lecture started.','["She asked what time does the lecture start (no backshift, wrong order).","She asked what time the lecture started.","She asked what time started the lecture (wrong order).","She asked that the lecture started at what time."]','Wh-word + subject + verb (no inversion); present simple → past simple.','medium'),
  (cid,6,38,'gap_fill','Direct: "Why have the results not been published?" → Reported: The committee asked why the results ___ not been published.','had',NULL,'Wh-word + subject + past perfect (passive) in reported question.','hard'),
  (cid,6,39,'multiple_choice','Which reported wh-question is correct?','She asked how long the study had taken.','["She asked how long did the study take (inverted — error).","She asked how long had the study taken (inverted — error).","She asked how long the study had taken.","She asked that how long the study had taken."]','How long + subject + had + past participle (no inversion in reported questions).','hard'),
  (cid,6,40,'gap_fill','Direct: "Who wrote this report?" → Reported: The professor asked who ___ written that report.','had',NULL,'Who + past perfect in reported speech (past simple → past perfect).','hard'),
  (cid,6,41,'multiple_choice','Convert: "How many participants were in the study?"','The reviewer asked how many participants had been in the study.','["The reviewer asked how many participants were in the study (no backshift).","The reviewer asked how many participants had been in the study.","The reviewer asked how many participants in the study had.","The reviewer asked that how many participants had been in the study."]','How many + subject + past perfect.','hard'),
  (cid,6,42,'gap_fill','Direct: "Where will the data be stored?" → Reported: She inquired where the data ___ be stored.','would',NULL,'"Will" → "would" in reported question. Where + subject + would + base verb.','hard'),

  -- BLOCK 7: reporting commands and requests
  (cid,7,43,'gap_fill','Direct: "Please submit the form by Friday." → Reported: The administrator ___ them to submit the form by Friday.','told / asked',NULL,'Reporting commands/requests: told/asked + object + to + base verb.','medium'),
  (cid,7,44,'multiple_choice','Convert: "Don''t share the results with anyone yet." → Reported?','The professor told the students not to share the results with anyone yet.','["The professor told the students don''t share the results with anyone yet.","The professor said the students not to share the results yet.","The professor told the students not to share the results with anyone yet.","The professor told to the students not to share the results yet."]','Negative command: told + object + not to + base verb.','hard'),
  (cid,7,45,'gap_fill','Direct: "Please review my draft." → Reported: He asked her ___ his draft.','to review',NULL,'Polite command/request: asked + person + to + base verb.','medium'),
  (cid,7,46,'multiple_choice','Which reported command is correct?','The instructor told students to take detailed notes.','["The instructor told students take detailed notes (missing to).","The instructor said students to take detailed notes (wrong verb — say doesn''t take to-infinitive).","The instructor told students to take detailed notes.","The instructor told to students to take detailed notes (wrong preposition)."]','Tell + object + to + base verb for reported commands.','medium'),
  (cid,7,47,'gap_fill','Direct: "Don''t plagiarize!" → Reported: The professor warned them ___ plagiarize.','not to',NULL,'Negative reported command: warned + object + not to + base verb.','medium'),
  (cid,7,48,'multiple_choice','Convert: "Could you please send me the data?" → Reported?','She asked him to send her the data.','["She asked him could he send her the data.","She asked if he would send her the data. (also possible)","She asked him to send her the data.","She told him to send her the data (too strong — command, not request)."]','Polite question converted to reported request: asked + object + to + base verb.','hard'),
  (cid,7,49,'gap_fill','Direct: "Please don''t interrupt me during the presentation." → Reported: She requested them ___ interrupt her during the presentation.','not to',NULL,'Reported negative request: requested + object + not to + base verb.','medium'),

  -- BLOCK 8: mixed reported speech review
  (cid,8,50,'multiple_choice','Which sentence is correctly reported?','The professor said that the exam would cover all chapters.','["The professor said that the exam will cover all chapters (no backshift).","The professor told that the exam would cover all chapters (wrong verb — told needs object).","The professor said that the exam would cover all chapters.","The professor said us that the exam would cover all chapters (wrong — say us)."]','Said + that + backshifted clause (will → would).','medium'),
  (cid,8,51,'gap_fill','Direct: "I haven''t read the article yet." → Reported: She admitted she ___ read the article yet.','hadn''t',NULL,'Present perfect negative → past perfect negative in reported speech.','medium'),
  (cid,8,52,'multiple_choice','Convert: "Are you going to attend the symposium?" → Reported?','She asked him whether he was going to attend the symposium.','["She asked him if he is going to attend the symposium (no backshift).","She asked him whether he was going to attend the symposium.","She asked him that he was going to attend the symposium.","She asked him whether he would going to attend the symposium."]','Whether + subject + was going to (past continuous of going to).','hard'),
  (cid,8,53,'gap_fill','Direct: "The study confirmed our hypothesis." → Reported: The researcher stated that the study ___ confirmed their hypothesis.','had',NULL,'Past simple → past perfect in reported speech.','medium'),
  (cid,8,54,'multiple_choice','Identify the error in reported speech: "He told that the funding had been approved."','told that should be said that OR told them that','["He should be She","that should be which","told that should be said that OR told them that","approved is wrong"]','"Tell" must be followed by an object (told them/us/her). "Said that" needs no object.','hard'),
  (cid,8,55,'gap_fill','Direct: "You must complete the ethics form before starting." → Reported: The supervisor ___ them ___ the ethics form before starting.','told / to complete',NULL,'"Must" in command → told + object + to + base verb.','hard'),
  (cid,8,56,'multiple_choice','Which sentence correctly uses a reporting verb other than say/tell?','The researcher claimed that the new treatment was more effective than existing options.','["The researcher told that the new treatment was more effective.","The researcher claimed that the new treatment was more effective than existing options.","The researcher claimed the new treatment is more effective (no backshift).","The researcher claimed to the team that the new treatment was more effective."]','"Claimed that + backshifted clause" (no indirect object needed).','hard'),

  -- BLOCK 9: TOEFL academic contexts
  (cid,9,57,'multiple_choice','[TOEFL Reading] The author reports that earlier scientists "claimed the atom was indivisible." In reported speech, what is the backshifted verb?','claimed → had claimed (if further backshifted)','["claim","is claiming","claimed → had claimed (if further backshifted)","will claim"]','"Claimed" in the passage is already past. In further reported speech: had claimed.','hard'),
  (cid,9,58,'gap_fill','[TOEFL Listening] The professor says: "The study concluded that prolonged screen time ___ (affect) children''s sleep quality." What form completes this reported conclusion?','affected',NULL,'In reported speech summarizing findings: present simple → past simple (concluded that + affected).','hard'),
  (cid,9,59,'multiple_choice','[TOEFL Reading] Which sentence correctly reports a researcher''s finding using formal academic language?','Darwin argued that species had evolved through a process of natural selection.','["Darwin argues that species evolved through natural selection (present tense — acceptable in academic review).","Darwin said species will evolve through natural selection.","Darwin argued that species had evolved through a process of natural selection.","Darwin told that species had evolved through natural selection."]','Argued + that + backshifted past perfect for reporting historical academic positions.','hard'),
  (cid,9,60,'gap_fill','[TOEFL Listening] The lecturer explains: "Einstein suggested that space and time ___ (be) not absolute but relative."','were',NULL,'"Suggested that" + past simple (be → were) for backshifted reported speech.','hard'),
  (cid,9,61,'multiple_choice','[TOEFL Reading] Which reporting verb is most appropriate for introducing a controversial academic claim?','contended','["said","told","contended","asked"]','"Contended" = argued strongly, appropriate for controversial academic claims.','hard'),
  (cid,9,62,'gap_fill','[TOEFL Listening] The professor reports: "Researchers warned that unless action ___ (take) immediately, the window for intervention ___ (close)."','were taken / would close',NULL,'Reported Type 1 conditional: present → past simple; will → would.','hard'),
  (cid,9,63,'multiple_choice','[TOEFL Reading] The author notes that "Pavlov demonstrated that animals ___ be conditioned to respond to neutral stimuli." What is the original direct speech?','Animals can be conditioned to respond to neutral stimuli.','["Animals could be conditioned.","Animals can be conditioned to respond to neutral stimuli.","Animals are conditioned to respond.","Animals were conditioned."]','"Could" in reported speech = "can" in original. Passive structure preserved.','hard'),

  -- BLOCK 10: TOEFL production tasks
  (cid,10,64,'multiple_choice','[TOEFL Reading] Which sentence best demonstrates formal academic reported speech?','The researchers asserted that the experimental group had demonstrated significantly greater improvement than the control group.','["The researchers said the experimental group shows greater improvement.","The researchers told that the experimental group had demonstrated greater improvement.","The researchers asserted that the experimental group had demonstrated significantly greater improvement than the control group.","The researchers asserted the experimental group demonstrated greater improvement."]','Asserted + that + past perfect for formal academic reported speech.','hard'),
  (cid,10,65,'gap_fill','[TOEFL Reading] The article reports: "Scientists discovered that the virus ___ (mutate) more rapidly than expected and ___ (already/develop) resistance to the treatment."','had mutated / had already developed',NULL,'Past simple in original → past perfect in reported speech for both verbs.','hard'),
  (cid,10,66,'multiple_choice','[TOEFL Speaking — 45s] You are summarizing a professor''s lecture. Which response best uses reported speech?','The professor explained that urbanization had accelerated dramatically since the 1950s and argued that this trend would continue unless rural development policies were implemented.','["The professor explains that urbanization accelerated dramatically since the 1950s.","The professor explained that urbanization has accelerated dramatically since the 1950s.","The professor explained that urbanization had accelerated dramatically since the 1950s and argued that this trend would continue unless rural development policies were implemented.","The professor told us urbanization has accelerated and will continue unless rural development."]','Full backshift + modal shift + unless clause all correctly reported.','hard'),
  (cid,10,67,'production','[TOEFL Speaking — 45s] Summarize what a professor said in a lecture about climate change. Report: (1) a statement with will/would, (2) a yes/no question the professor asked, (3) a wh-question the professor raised, and (4) a command the professor gave to students. Use correct backshift, word order, and time expression changes.','',NULL,'Practice all aspects of reported speech: statements, yes/no questions, wh-questions, and commands.','hard'),
  (cid,10,68,'production','[TOEFL Writing] Write a paragraph (4-5 sentences) summarizing a research article you have read (real or imaginary). Report the researchers'' main claim, one finding, one question they raised, and one recommendation they made. Use say, argue, claim, suggest, and ask/wonder.','',NULL,'Academic writing uses a variety of reporting verbs and correct backshift for literature reviews.','hard'),
  (cid,10,69,'multiple_choice','[TOEFL Writing] Which sentence best introduces a counterargument using reported speech in an academic essay?','However, critics have argued that the study''s methodology was flawed and that the sample size was too small to support such broad conclusions.','["However, critics argued that the study''s methodology is flawed and sample size is too small.","However, critics have argued that the study''s methodology was flawed and that the sample size was too small to support such broad conclusions.","However, critics have said us that the study''s methodology was flawed.","However, critics have told that the methodology was flawed and the sample too small."]','Have argued + that + backshifted clauses for academic counterargument.','hard'),
  (cid,10,70,'production','[TOEFL Writing] Write a 5-sentence literature review paragraph reporting the views of at least three different researchers or groups. Use: say/tell, argue, claim, suggest, and warn as reporting verbs. Include at least one reported question and one reported command or recommendation. Apply all backshift rules correctly.','',NULL,'Demonstrate mastery of reported speech in academic literature review writing.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
