-- ============================================================
-- SEED EXT 4: Módulo 17 — Non-Defining Clauses (ex 146-215)
-- Novos tópicos: NDRCs em academic prose, participle clauses
-- absolutas, NDRC com preposições, NDRCs de sentença inteira
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'non-defining-clauses';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo non-defining-clauses não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 41: NDRC vs defining RC — contraste avançado
  (cid,41,146,'multiple_choice','What changes in meaning: "Scientists who work in remote environments face unique challenges" vs "Scientists, who work in remote environments, face unique challenges"?','The first restricts meaning to a subset. The second claims all scientists work in remote environments.','["No difference","The first restricts meaning to a subset. The second claims all scientists work in remote environments.","Commas only change punctuation","The second is grammatically wrong"]','Defining (no commas) = some scientists. Non-defining (commas) = all scientists.','hard'),
  (cid,41,147,'gap_fill','The vaccine, _____ developed through an unprecedented collaboration between public and private sectors, received emergency authorization in December 2020.','which was',NULL,'NDRC: "which was developed" = non-defining passive RC with subject included.','medium'),
  (cid,41,148,'multiple_choice','Which sentence uses a NON-DEFINING RELATIVE CLAUSE correctly?','Professor Martinez, who has published over 200 peer-reviewed articles, was awarded the Fields Medal.','["Professor Martinez who has published over 200 peer-reviewed articles was awarded the Fields Medal (missing commas — defining, wrong meaning).","Professor Martinez, who has published over 200 peer-reviewed articles, was awarded the Fields Medal.","Professor Martinez, which has published over 200 peer-reviewed articles, was awarded the Fields Medal (which for people — error).","Professor Martinez, whom has published over 200 articles, was awarded the Fields Medal (whom = object — wrong for subject position)."]','NDRC: commas + who (subject) = non-defining for specific named person.','medium'),
  (cid,41,149,'gap_fill','The Great Barrier Reef, _____ stretches for more than 2,300 kilometers along the Queensland coast, supports one of the world''s most biodiverse marine ecosystems.','which',NULL,'NDRC with "which" for thing (not "that" in non-defining clauses).','easy'),
  (cid,41,150,'multiple_choice','Which NDRC is NOT correctly punctuated?','The findings, that contradicted earlier research, required careful replication.','["The findings, which contradicted earlier research, required careful replication (correct — which in NDRC).","The research, conducted over five years, revealed significant patterns (correct — reduced NDRC).","The findings, that contradicted earlier research, required careful replication.","Professor Lee, whose work spans three decades, is the leading authority in this area (correct — whose in NDRC)."]','"That" cannot introduce a non-defining relative clause. Use "which."','medium'),

  -- BLOCK 42: NDRC de sentença inteira (sentence relative clause)
  (cid,42,151,'multiple_choice','What does the "which" refer to in "The experiment failed to produce the expected results, which surprised the research team"?','The entire preceding clause/fact (that the experiment failed).','["The results","The experiment","The expected results","The entire preceding clause/fact (that the experiment failed)."]','"Which" after comma referring to entire sentence = sentence relative clause.','medium'),
  (cid,42,152,'gap_fill','The committee approved the budget increase, _____ _____ many observers had not expected, given the ongoing fiscal constraints.','which / which',NULL,'"Which" for sentence RC. Full form: "which was something which/that many observers had not expected" → contracted to "which many observers had not expected."','hard'),
  (cid,42,153,'gap_fill','The government reversed its position on the issue, _____ came as a surprise to analysts _____ had been expecting further delay.','which / who',NULL,'Sentence RC "which" for the reversal + defining RC "who" for analysts.','hard'),
  (cid,42,154,'multiple_choice','Which sentence uses a SENTENCE RELATIVE CLAUSE (where which refers to a whole idea)?','The bridge was completed six months ahead of schedule, which led to significant cost savings.','["The bridge, which was completed six months ahead of schedule, led to cost savings (NDRC modifying bridge — different meaning).","The bridge was completed six months ahead of schedule, which led to significant cost savings.","The bridge''s completion, which led to cost savings, was six months ahead of schedule.","The bridge that was completed ahead of schedule led to cost savings (defining RC)."]','"which led to cost savings" = sentence RC. "Which" refers to the fact of early completion.','medium'),
  (cid,42,155,'gap_fill','The study found no significant difference between the two groups, _____ suggested that the intervention had not had the intended effect.','which',NULL,'Sentence RC: "which suggested" = the absence of difference suggested this.','easy'),

  -- BLOCK 43: Participle clauses não-definidoras
  (cid,43,156,'multiple_choice','Which participial phrase functions as a NON-DEFINING addition to the sentence (like a NDRC)?','The proposal, drawing on insights from three disciplines, offered a novel theoretical synthesis.','["The proposal drawing on three disciplines offered a novel synthesis (defining participial — which proposal?).","The proposal, drawing on insights from three disciplines, offered a novel theoretical synthesis.","Drawing on three disciplines, the proposal offered a novel synthesis (fronted participle — slightly different function).","The proposal, which drawing on three disciplines, offered a novel synthesis (wrong — ''which'' without verb)."]','Commas around participial phrase = non-defining addition (like NDRC).','hard'),
  (cid,43,157,'gap_fill','The algorithm, _____ (design) to minimize false positives, _____ (unfortunately/produce) a high rate of false negatives instead.','designed / unfortunately produced',NULL,'Reduced NDRC (passive: designed) + past simple for actual outcome.','medium'),
  (cid,43,158,'gap_fill','The participants, _____ (range) in age from 18 to 65, _____ (complete) a battery of cognitive assessments over three sessions.','ranging / completed',NULL,'Active participle NDRC (whose ages ranged = ranging) + PS for main action.','medium'),
  (cid,43,159,'multiple_choice','Which sentence correctly reduces a NON-DEFINING RELATIVE CLAUSE to a participial phrase?','"The study, conducted by an international research consortium, confirmed earlier findings."','["The study, conducted by an international research consortium, confirmed earlier findings.","The study which conducted by a consortium confirmed earlier findings.","The study, having conducted by a consortium, confirmed earlier findings.","The study, conducting by a consortium, confirmed earlier findings."]','Passive NDRC reduced: "which was conducted" → "conducted" (past participle).','medium'),

  -- BLOCK 44: NDRC com preposições (of which, in which, for whom)
  (cid,44,160,'gap_fill','The study examined 500 schools, _____ of _____ had received additional government funding.','fewer than half / which',NULL,'"Fewer than half of which" = NDRC with quantifier prepositional phrase.','hard'),
  (cid,44,161,'gap_fill','The team recruited 80 participants, for _____ of _____ the experiment represented their first experience of extended isolation.','many / whom',NULL,'"For many of whom" = NDRC with preposition "for" + quantifier + "whom" (people).','hard'),
  (cid,44,162,'multiple_choice','Which NDRC with preposition is CORRECT?','The mountain range, at the foot of which the ancient city was built, stretches for 400 kilometers.','["The mountain range, at the foot of that the ancient city was built, stretches for 400 kilometers.","The mountain range, at the foot of whom the ancient city was built, stretches for 400 kilometers.","The mountain range, at the foot of which the ancient city was built, stretches for 400 kilometers.","The mountain range, at the foot that the ancient city was built, stretches for 400 kilometers."]','Preposition + "of which" in NDRC: "at the foot of which."','hard'),
  (cid,44,163,'gap_fill','The organization employed 3,000 researchers, only a fraction of _____ _____ (specialize) in the area directly relevant to this study.','whom / specialized',NULL,'"Only a fraction of whom" = NDRC for people. PS for ongoing specialization at that time.','hard'),
  (cid,44,164,'gap_fill','Three competing explanations have been proposed, none of _____ _____ (fully/account for) all the available evidence.','which / fully accounts for',NULL,'"None of which" = NDRC with negative quantifier. PS for current state.','hard'),

  -- BLOCK 45: TOEFL Reading
  (cid,45,165,'multiple_choice','[TOEFL Reading] "The Treaty of Westphalia (1648), which is widely regarded as the foundation of the modern state system, established the principle of national sovereignty." The NDRC "which is widely regarded..." functions to:','Add background information about the treaty''s significance without restricting which treaty is meant.','["Restrict which treaty is being discussed","Add background information about the treaty''s significance without restricting which treaty is meant.","Contradict the main clause","Introduce a condition"]','Proper noun is already unique → NDRC adds context, not restriction.','easy'),
  (cid,45,166,'gap_fill','[TOEFL Reading] "The organism uses a toxin, _____ mechanism of action _____ (not/fully/understand/passive), to deter predators." Best forms?','whose / has not been fully understood',NULL,'"Whose" in NDRC (the toxin''s mechanism). PP passive negative for incomplete understanding.','hard'),
  (cid,45,167,'multiple_choice','[TOEFL Reading] "The pandemic accelerated many digital trends, which in turn transformed employment patterns across most sectors of the economy." The phrase "which in turn" introduces:','A sentence relative clause showing a consequence of the preceding fact.','["A non-defining clause about the pandemic","A defining clause about which trends","A sentence relative clause showing a consequence of the preceding fact.","A subordinate clause expressing time"]','"Which in turn" = sentence RC: the digital transformation (triggered by pandemic) → then changed employment.','medium'),

  -- BLOCK 46: TOEFL Speaking
  (cid,46,168,'production','[TOEFL Speaking — 45s] A lecture discusses a scientific figure who made contributions despite resistance from the establishment. Use NDRCs with which/who/whose throughout.','',NULL,'The lecture discusses the career of Barry Marshall, who shared the 2005 Nobel Prize in Physiology or Medicine for his discovery that peptic ulcers are caused by the bacterium Helicobacter pylori. Marshall''s research, which he conducted with Robin Warren in the early 1980s, contradicted the established medical consensus that the stomach was too acidic to support bacterial life. The scientific community, which initially rejected his findings as implausible, required him to conduct a dramatic demonstration: he swallowed a culture of the bacterium and developed gastritis within days. His work, whose implications extended far beyond ulcer treatment, ultimately led to antibiotic treatments that could cure a condition that had previously been managed only symptomatically. The Nobel Committee, which rarely awards the prize for a discovery made less than 25 years earlier, made an exception for work whose clinical impact had been so immediately and measurably transformative.','hard'),
  (cid,46,169,'production','[TOEFL Speaking — 45s] Describe a city you know. Use NDRCs (which, who, whose), reduced NDRCs, and sentence relative clauses.','',NULL,'Berlin, which is now the political and cultural capital of unified Germany, is a city whose history reads as a compressed account of the twentieth century''s most significant upheavals. The city was divided by the Berlin Wall for twenty-eight years, a period during which it functioned simultaneously as a showcase of Western prosperity and a symbol of Cold War confrontation. The Wall, which fell in November 1989, had physically embodied the division of Europe, and its demolition triggered a cascade of political changes across the continent, which in turn reshaped the entire post-war international order. The reunified Berlin, whose population has grown rapidly since the 1990s, has become one of Europe''s most attractive destinations for creative industries and technology startups, drawn by relatively affordable costs by the standards of major European capitals and a distinctive cultural atmosphere rooted in its unusual history.','hard'),

  -- BLOCK 47: TOEFL Writing
  (cid,47,170,'production','[TOEFL Writing — 150 words] Write a paragraph on artificial intelligence policy. Use NDRC (×2), sentence RC (×1), reduced participial NDRC (×2).','',NULL,'Artificial intelligence, which is developing at a pace that most regulatory systems were not designed to manage, poses governance challenges that span technical, ethical, legal, and economic domains simultaneously. Most existing regulatory frameworks, developed primarily to address risks posed by physical products and services, lack the tools to evaluate algorithmic systems whose behavior is not always predictable even to their designers. The European Union''s Artificial Intelligence Act, signed into law in 2024, represents the most comprehensive attempt to date to establish a risk-based framework for AI governance, which may serve as a template for regulatory approaches elsewhere. The Act, covering high-risk applications in areas such as employment, credit, and law enforcement, requires transparency and human oversight, which in turn imposes compliance costs that smaller developers may find difficult to absorb. Whether this approach can keep pace with the rate of AI development remains genuinely uncertain.','hard'),
  (cid,47,171,'production','[TOEFL Writing — Error Correction] Fix NDRC errors: "London, that is the capital of the UK, is one of Europe''s largest cities. The data, which were collected last year are available online. The policy affected all employees, much of whom had not been consulted. Einstein, whom proposed relativity, was born in Germany."','',NULL,'that → which (NDRCs use which, not that); were collected last year are → were collected last year, are (missing comma before main verb); much of whom → many of whom (many for countable people, not much); whom → who (subject position: who proposed, not whom).','hard'),

  -- BLOCK 48: Consolidação final
  (cid,48,172,'production','[TOEFL Writing — 200 words] Write a paragraph on the history of the United Nations. Use: NDRC (×2), sentence RC (×1), reduced NDRC (×2), NDRC with preposition (×1).','',NULL,'The United Nations, which was founded in October 1945 in the immediate aftermath of the Second World War, emerged from a conviction that the catastrophic failures of the League of Nations could not be allowed to repeat themselves. The League, established in 1919 with similar ambitions, had ultimately proved incapable of preventing the rise of aggressive nationalism and the collapse of the international order in the 1930s — a failure that shaped the design of its successor in fundamental ways. The UN Charter, signed by 51 original member states, created a more elaborate institutional architecture, including the Security Council, in which the five permanent members were granted veto power, a compromise that reflected the realities of post-war power rather than any principled commitment to equality among nations. The organization has grown to include nearly 200 member states, representing virtually every recognized country, which has made it the most universally inclusive international institution in history. Its effectiveness has been persistently constrained by the great-power dynamics inscribed into the Security Council structure, many of whose most significant provisions reflect a world that no longer exists.','hard'),
  (cid,48,173,'production','[TOEFL Speaking — 60s] Discuss the concept of privacy in the digital age. Use NDRCs, sentence RCs, and reduced NDRCs throughout.','',NULL,'Privacy, which most democratic legal systems recognize as a fundamental right, faces challenges in the digital age that its legal frameworks were not designed to address. The informational environment in which individuals now live is characterized by continuous data generation — every digital transaction, search query, location signal, and social media interaction produces data that can be collected, stored, analyzed, and traded. This data, accumulated over years of digital activity, creates profiles of individual behavior and preference far more detailed than any surveillance system of the pre-digital era could have assembled. The legal frameworks governing privacy, developed primarily in the late twentieth century, were designed for a world in which information was scarce and expensive to collect, which makes them poorly suited to a world in which it is abundant and cheap. Recent regulatory developments — most notably the European General Data Protection Regulation, signed into law in 2018 — represent serious attempts to extend meaningful privacy protection into the digital domain, which other jurisdictions have watched closely as potential templates. The fundamental tension between the economic value of personal data to platform companies and the privacy interests of users whose data they collect has not yet been resolved.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
