-- ============================================================
-- SEED: Módulo 19 — Hedging Language (B2)
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'hedging-language';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo hedging-language não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 1: Modal Hedges (may, might, could)
  (cid,1,1,'gap_fill','The increase in temperature _____ be linked to industrial emissions, according to preliminary data.','may/might/could',NULL,'"May," "might," and "could" all express uncertainty or possibility. Any of these is correct for hedging a claim.','easy'),
  (cid,1,2,'multiple_choice','The results _____ suggest a correlation, but further research is needed to confirm this.','may','["will","do","are","may"]','"May suggest" hedges the claim by expressing possibility rather than certainty. "Will suggest" would be too strong.','easy'),
  (cid,1,3,'gap_fill','This treatment _____ prove more effective than current therapies, though clinical trials are ongoing.','could',NULL,'"Could" expresses possibility without certainty — appropriate for claims not yet proven.','easy'),
  (cid,1,4,'multiple_choice','The policy _____ have unintended consequences for low-income households.','might','["will certainly","definitely does","might","must"]','"Might" hedges the claim; "will certainly" and "definitely does" are too strong for uncertain predictions.','easy'),
  (cid,1,5,'gap_fill','Rising sea levels _____ pose a significant threat to coastal cities by 2050.','may/might/could',NULL,'Modal hedges express possibility rather than certainty for future predictions. Any of the three modals is correct.','easy'),
  (cid,1,6,'multiple_choice','Antibiotic resistance _____ become one of the most serious public health challenges of the 21st century.','could','["is definitely","could","will certainly","must"]','"Could become" expresses a possibility that is projected but not guaranteed.','medium'),
  (cid,1,7,'gap_fill','The new data _____ challenge the existing consensus on the timing of human migration out of Africa.','may/might/could',NULL,'Any of the three modal hedges (may/might/could) is appropriate for an unconfirmed academic claim.','medium'),
  (cid,1,8,'multiple_choice','Which sentence uses hedging language correctly?','The experiment might yield different results if repeated under controlled conditions.','["The experiment yields different results if repeated.","The experiment will yield different results if repeated.","The experiment might yield different results if repeated under controlled conditions.","The experiment does yield different results if repeated."]','"Might yield" appropriately hedges the prediction. "Will" or "does" would be too definitive.','medium'),

  -- BLOCK 2: Lexical Hedges (appear to, seem to, tend to)
  (cid,2,9,'gap_fill','The data _____ (appear) support the hypothesis that exercise improves cognitive function.','appear to',NULL,'"Appear to" hedges by presenting the finding as apparent rather than confirmed. → The data appear to support.','easy'),
  (cid,2,10,'multiple_choice','Students who study abroad _____ perform better in cross-cultural communication tasks.','tend to','["always","definitely","tend to","certainly"]','"Tend to" hedges by expressing a general pattern without claiming it is always true.','easy'),
  (cid,2,11,'gap_fill','The new compound _____ (seem) be more stable than its predecessors at high temperatures.','seems to',NULL,'"Seems to" hedges by presenting the observation as apparent. → The new compound seems to be more stable.','easy'),
  (cid,2,12,'multiple_choice','Urban populations _____ experience higher rates of stress-related illness than rural populations.','tend to','["always","tend to","absolutely","definitely"]','"Tend to" is a common hedging device that softens a generalization.','easy'),
  (cid,2,13,'gap_fill','The proposed mechanism _____ (appear) consistent with all the observed data points.','appears',NULL,'"Appears" (or "appears to be") hedges the claim. → The proposed mechanism appears consistent.','medium'),
  (cid,2,14,'multiple_choice','Which sentence uses "seem to" correctly as a hedging device?','The drug seems to reduce inflammation without significant side effects.','["The drug seems to reducing inflammation.","The drug seems reducing inflammation.","The drug seems to reduce inflammation without significant side effects.","The drug seeming to reduce inflammation."]','"Seems to reduce" = correct form of "seem to + base verb." Used to hedge the observed outcome.','medium'),
  (cid,2,15,'gap_fill','Higher income groups _____ (tend) have better access to healthcare and educational resources.','tend to',NULL,'"Tend to" hedges the generalization, acknowledging exceptions may exist.','easy'),
  (cid,2,16,'multiple_choice','The findings _____ indicate that early intervention produces better long-term outcomes.','appear to','["definitely","appear to","must","clearly"]','"Appear to indicate" is a double hedge, making the claim appropriately cautious for preliminary findings.','medium'),

  -- BLOCK 3: Reporting Verbs & "It is possible that"
  (cid,3,17,'gap_fill','The authors _____ (suggest) that a more nuanced interpretation is required.','suggest',NULL,'"Suggest" is a hedging reporting verb (weaker than "prove" or "demonstrate"). → The authors suggest that.','easy'),
  (cid,3,18,'multiple_choice','The data _____ that temperature fluctuations are becoming more extreme.','indicate','["prove absolutely","are certain","indicate","guarantee"]','"Indicate" hedges the interpretation. "Prove" and "guarantee" are too strong for data-based claims.','easy'),
  (cid,3,19,'gap_fill','It is _____ that air pollution contributes to increased rates of neurological disorders.','possible',NULL,'"It is possible that" is a common hedging construction. → It is possible that air pollution contributes to.','easy'),
  (cid,3,20,'multiple_choice','_____ that the current pace of deforestation will lead to the extinction of numerous species within decades.','It seems likely','["It is certain","It is obvious","It seems likely","Everyone knows"]','"It seems likely that" hedges the prediction appropriately for a scientific concern.','medium'),
  (cid,3,21,'gap_fill','The results _____ (indicate) a relationship between sleep deprivation and increased error rates.','indicate',NULL,'"Indicate" is softer than "prove" — appropriate hedging for correlational findings.','easy'),
  (cid,3,22,'multiple_choice','Which is the most appropriately hedged academic sentence?','The data suggest that screen time may be associated with sleep disruption in adolescents.','["Screen time definitely causes sleep disruption in all adolescents.","The data prove that screen time always causes sleep disruption.","The data suggest that screen time may be associated with sleep disruption in adolescents.","Everyone knows screen time disrupts sleep."]','Multiple layers of hedging: "suggest" + "may be associated." Avoids absolute claims not supported by the data.','medium'),
  (cid,3,23,'gap_fill','It _____ (seem) likely that the population will exceed 10 billion by 2050.','seems',NULL,'"It seems likely that" hedges the demographic projection. → It seems likely that the population will exceed.','easy'),
  (cid,3,24,'multiple_choice','The researcher concludes that the results _____ a causal link between the variables studied.','may suggest','["prove","confirm","may suggest","definitely establish"]','"May suggest" is a double hedge (modal + hedging verb), appropriate for preliminary findings.','hard'),

  -- BLOCK 4: Approximators & Frequency Hedges (approximately, generally, in most cases)
  (cid,4,25,'gap_fill','The sample consisted of _____ 450 participants, drawn from three universities.','approximately',NULL,'"Approximately" hedges a numerical claim to acknowledge measurement uncertainty.','easy'),
  (cid,4,26,'multiple_choice','_____, higher levels of education correlate with higher income over a lifetime.','Generally','["Always","Inevitably","Generally","Absolutely"]','"Generally" hedges by expressing a typical pattern while acknowledging exceptions.','easy'),
  (cid,4,27,'gap_fill','_____ most cases, the treatment was effective within the first two weeks.','In',NULL,'"In most cases" = a frequency hedge. → In most cases, the treatment was effective.','easy'),
  (cid,4,28,'multiple_choice','The study found that _____ 70% of participants reported improved sleep quality after the intervention.','approximately','["exactly","precisely","approximately","completely"]','"Approximately 70%" hedges by acknowledging rounding and measurement imprecision.','easy'),
  (cid,4,29,'gap_fill','Air quality tends to be _____ (poor) in cities with high industrial activity than in rural areas.','poorer',NULL,'Comparative form used as a hedged claim. "Tends to be poorer" hedges the generalization.','medium'),
  (cid,4,30,'multiple_choice','Which sentence uses an approximator correctly?','The intervention was conducted over a period of roughly six months.','["The intervention lasted for exactly six months.","The intervention was conducted over a period of roughly six months.","The intervention lasted for always six months.","The intervention was conducted over often six months."]','"Roughly" is an approximator that hedges the duration, acknowledging slight variation.','easy'),
  (cid,4,31,'gap_fill','_____ (large) studies tend to produce more reliable results than smaller ones.','Larger',NULL,'This is a generalization (hedged by "tend to"). "Larger" is the comparative adjective form needed.','easy'),
  (cid,4,32,'multiple_choice','In academic writing, approximators like "roughly," "approximately," and "around" are used to:','acknowledge that measurements are estimates and may not be exact','["make claims stronger and more credible","acknowledge that measurements are estimates and may not be exact","avoid providing specific data","replace statistical analysis"]','Approximators hedge numerical claims by signaling that precise values are uncertain or rounded.','medium'),

  -- BLOCK 5: TOEFL Academic – Hedging in Reading Passages
  (cid,5,33,'gap_fill','[TOEFL Reading] The authors _____ that the decrease in species diversity _____ be attributed to habitat loss.','suggest / may',NULL,'"Suggest" = hedging reporting verb. "May be" = modal hedge. Together, they make the claim appropriately cautious.','medium'),
  (cid,5,34,'multiple_choice','[TOEFL Reading] Which word in the sentence "The findings might imply that existing models are inadequate" serves as a hedge?','might','["findings","imply","models","might"]','"Might" is the modal hedge, making "imply" less certain than "prove" or "show."','easy'),
  (cid,5,35,'gap_fill','[TOEFL Reading] It _____ (be) worth noting that the sample size was relatively small, which limits generalizability.','is',NULL,'"It is worth noting that" is a hedging phrase used to add a cautionary note about limitations.','medium'),
  (cid,5,36,'multiple_choice','[TOEFL Reading] "The results appear to _____ that cognitive decline begins earlier than previously thought."','suggest','["proves","demonstrates","suggest","confirms"]','"Appear to suggest" is a double hedge: "appear to" + "suggest." Appropriate for disputed or preliminary findings.','medium'),
  (cid,5,37,'gap_fill','[TOEFL Listening] The professor mentioned that the data _____ (seem) to challenge the traditional view on migration.','seem',NULL,'"Seem" as a hedging verb presents the challenge as apparent but not definitive.','easy'),
  (cid,5,38,'multiple_choice','[TOEFL Reading] "The mechanism by which stress leads to disease is not yet fully understood." This sentence hedges by:','using "not yet fully understood" to signal incomplete knowledge','["using a passive construction","using future tense","using \"not yet fully understood\" to signal incomplete knowledge","using a question form"]','"Not yet fully understood" explicitly signals that knowledge is incomplete, which is a form of epistemic hedging.','hard'),
  (cid,5,39,'gap_fill','[TOEFL Reading] There is _____ (some) evidence to suggest that early music education enhances mathematical reasoning.','some',NULL,'"Some evidence" is a hedged quantifier — it avoids saying "proof" or "all evidence."','easy'),
  (cid,5,40,'multiple_choice','[TOEFL Reading] Which statement is most appropriately hedged for an academic context?','There is some evidence to suggest that increased screen time may be associated with attention difficulties in children.','["Screen time causes attention difficulties in all children.","Increased screen time is obviously linked to attention difficulties.","There is some evidence to suggest that increased screen time may be associated with attention difficulties in children.","Everyone agrees that screen time is harmful to children."]','Multiple hedges: "some evidence," "suggest," "may be associated." Appropriate for correlational research.','medium'),

  -- BLOCK 6: TOEFL Academic – Contrasting Hedged vs Strong Claims
  (cid,6,41,'multiple_choice','[TOEFL Reading] Which is the STRONGER (unhedged) claim that would be inappropriate in academic writing?','Exercise eliminates all risk of cardiovascular disease.','["Exercise may reduce the risk of cardiovascular disease.","Exercise appears to lower blood pressure in most adults.","Exercise eliminates all risk of cardiovascular disease.","Exercise tends to be beneficial for cardiovascular health."]','"Eliminates all risk" is an absolute, unhedged claim that no research can fully support.','easy'),
  (cid,6,42,'gap_fill','[TOEFL Reading] Rewrite this overly strong claim with hedging: "Climate change will destroy all coral reefs by 2050." → Climate change _____ cause severe damage to coral reefs by 2050.','could/may/might',NULL,'Replace "will destroy all" with a modal + "severe damage" to hedge appropriately.','medium'),
  (cid,6,43,'multiple_choice','[TOEFL Listening] The professor hedged her claim by saying, "The data _____ a link between diet and cognitive aging, though the evidence is not yet conclusive."','suggest','["prove","confirm","guarantee","suggest"]','"Suggest" is a hedging reporting verb appropriate for inconclusive findings.','easy'),
  (cid,6,44,'gap_fill','[TOEFL Reading] The policy _____ (have) unintended consequences in regions with high poverty rates, though this _____ (require) further study.','may have / would require',NULL,'Double hedging: "may have" for speculative prediction; "would require" for conditional recommendation.','hard'),
  (cid,6,45,'multiple_choice','[TOEFL Reading] "This suggests that the findings _____ be generalizable to other populations." Which word correctly hedges the claim?','may','["will","do","are","may"]','"May be generalizable" appropriately hedges the extent to which findings apply beyond the sample.','easy'),
  (cid,6,46,'gap_fill','[TOEFL Reading] The new vaccine _____ (appear) effective in initial trials, but long-term protection _____ (require) further study.','appears / requires',NULL,'"Appears effective" = hedged present observation. "Requires further study" = standard hedging conclusion.','medium'),
  (cid,6,47,'multiple_choice','[TOEFL Listening] Which phrase is NOT a typical hedging device in academic writing?','It is absolutely proven that','["It is possible that","There is some evidence to suggest that","It may be the case that","It is absolutely proven that"]','"It is absolutely proven that" is an unhedged, overconfident claim. The others are all valid hedges.','easy'),
  (cid,6,48,'gap_fill','[TOEFL Reading] _____ from the study are _____ by the relatively small sample size of only 45 participants.','Conclusions drawn / limited',NULL,'"Conclusions drawn from the study are limited by..." is a standard hedging phrase acknowledging study limitations.','hard'),

  -- BLOCK 7: TOEFL Academic – Hedging for Limitations
  (cid,7,49,'gap_fill','[TOEFL Reading] _____ caution should be exercised when interpreting these results, as the sample was not representative.','Some',NULL,'"Some caution should be exercised" is a standard academic hedging phrase for signaling interpretive limitations.','medium'),
  (cid,7,50,'multiple_choice','[TOEFL Reading] "While the results are promising, it would be premature to _____ definitive conclusions."','draw','["making","drew","draw","makes"]','"It would be premature to draw definitive conclusions" is a standard hedging phrase for early-stage research.','medium'),
  (cid,7,51,'gap_fill','[TOEFL Reading] The correlation observed in this study _____ (not necessarily) imply a causal relationship.','does not necessarily',NULL,'"Does not necessarily imply" hedges the interpretation of correlational data — a critical academic skill.','hard'),
  (cid,7,52,'multiple_choice','[TOEFL Reading] Which phrase is most effective for hedging a claim about causation?','The data suggest a possible link between X and Y.','["X definitely causes Y.","X is clearly the cause of Y.","The data suggest a possible link between X and Y.","Obviously, X causes Y."]','"Suggest a possible link" uses both a hedging verb and "possible" — appropriate for correlational studies.','medium'),
  (cid,7,53,'gap_fill','[TOEFL Listening] The professor noted that "further research _____ (be) needed to establish whether the findings are replicable."','is',NULL,'"Further research is needed" is a standard hedging phrase used at the end of academic arguments.','easy'),
  (cid,7,54,'multiple_choice','[TOEFL Reading] In academic writing, expressing uncertainty through hedging is important because it:','reflects the provisional nature of scientific knowledge and shows intellectual honesty','["makes texts longer and more complex","reflects the provisional nature of scientific knowledge and shows intellectual honesty","helps writers avoid all criticism","makes claims easier for readers to remember"]','Hedging reflects the epistemological reality that most scientific claims are probabilistic, not absolute.','hard'),
  (cid,7,55,'gap_fill','[TOEFL Reading] The _____ (find) should be interpreted with caution, as they may not generalize to other cultural contexts.','findings',NULL,'"Findings should be interpreted with caution" — standard academic hedging for generalizability limitations.','medium'),
  (cid,7,56,'multiple_choice','[TOEFL Reading] Choose the best hedged conclusion for a research paper.','The results indicate that mindfulness-based interventions may reduce anxiety symptoms in clinical populations.','["Mindfulness definitely cures anxiety forever.","The results indicate that mindfulness-based interventions may reduce anxiety symptoms in clinical populations.","Mindfulness clearly eliminates all forms of anxiety.","The results prove mindfulness is the best treatment for anxiety."]','Multiple hedges: "indicate" + "may reduce" → appropriate for reporting findings without overclaiming.','medium'),

  -- BLOCK 8: TOEFL Academic – Mixed Hedging Practice
  (cid,8,57,'gap_fill','[TOEFL Reading] The model _____ (appear) to underestimate the impact of seasonal variation on the results.','appears',NULL,'"Appears to underestimate" hedges by presenting the limitation as apparent rather than confirmed.','medium'),
  (cid,8,58,'multiple_choice','[TOEFL Reading] "_____ most instances, educational technology has been shown to improve student engagement."','In','["At","For","In","By"]','"In most instances" is a frequency hedge that acknowledges that the pattern is not universal.','easy'),
  (cid,8,59,'gap_fill','[TOEFL Reading] This _____ (be) one possible explanation, though alternative interpretations cannot be ruled out.','may be',NULL,'"May be one possible explanation" = double hedge. "Cannot be ruled out" signals ongoing uncertainty.','hard'),
  (cid,8,60,'multiple_choice','[TOEFL Listening] The professor used the phrase "it is worth noting that" in order to:','introduce a qualifying observation without making a strong claim','["emphasize the most important point of her argument","introduce a qualifying observation without making a strong claim","conclude her lecture","challenge the reading passage directly"]','"It is worth noting that" signals additional, hedged information — a softening device, not a main claim.','hard'),
  (cid,8,61,'gap_fill','[TOEFL Reading] The rate of economic growth _____ (tend) to slow during periods of political instability.','tends',NULL,'"Tends to slow" is a hedged generalization — it applies in most but not all cases.','easy'),
  (cid,8,62,'multiple_choice','[TOEFL Reading] Select the sentence that uses the most layers of hedging appropriately.','The preliminary data may suggest a possible association between variable X and outcome Y.','["Variable X definitely causes outcome Y.","The preliminary data may suggest a possible association between variable X and outcome Y.","Variable X is obviously linked to outcome Y.","The data proves variable X causes outcome Y."]','Multiple hedges: "preliminary" + "may suggest" + "possible association." Most appropriately hedged for initial findings.','hard'),
  (cid,8,63,'gap_fill','[TOEFL Reading] There _____ (be) some uncertainty about the long-term effects of this medication on kidney function.','is',NULL,'"There is some uncertainty about" is a direct hedging phrase acknowledging incomplete knowledge.','medium'),
  (cid,8,64,'multiple_choice','[TOEFL Reading] Which pair of hedging strategies is used in the following sentence? "It is possible that microplastics may interfere with hormone regulation in marine mammals."','epistemic hedge ("it is possible") + modal hedge ("may")','["approximator + frequency hedge","epistemic hedge (\"it is possible\") + modal hedge (\"may\")","reporting verb + approximator","lexical verb + superlative"]','Two distinct hedging strategies: epistemic phrase "it is possible that" + modal verb "may."','hard'),

  -- BLOCK 9: TOEFL Speaking Tasks
  (cid,9,65,'production','[TOEFL Speaking — 45s] The reading passage claims that social media use among teenagers is directly linked to increased rates of depression. The professor argues that the relationship is more complex and that other factors may be involved. Summarize the points made in the lecture and explain how they cast doubt on the reading''s claims. Use hedging language where appropriate. You have 45 seconds to respond.','',NULL,'Use: "The professor suggests that..." "It may be the case that..." "The evidence appears to indicate..." "However, this does not necessarily mean..."','hard'),
  (cid,9,66,'production','[TOEFL Speaking — 45s] Do you agree or disagree with the following statement: "Governments should invest more in renewable energy research." Use hedging language to express your opinion, acknowledging uncertainty and counterarguments. You have 45 seconds.','',NULL,'Practice: "It seems likely that..." "Investment in renewables may reduce..." "While some might argue that... it appears that..."','medium'),
  (cid,9,67,'production','[TOEFL Speaking — 45s] What do you think will be the most significant global challenge of the next 50 years? Use appropriate hedging language to express your prediction. Give reasons to support your view. You have 45 seconds.','',NULL,'Key hedges: "I believe it is possible that..." "Climate change might..." "This could lead to..." "It seems likely that..."','hard'),

  -- BLOCK 10: TOEFL Writing Tasks
  (cid,10,68,'production','[TOEFL Writing] Some researchers argue that artificial intelligence will replace most human jobs within the next 30 years. Others believe that AI will create new types of employment. Write an essay discussing both views and giving your opinion. Use hedging language throughout your response to express appropriate levels of certainty. Write at least 150 words.','',NULL,'Include: "It seems possible that..." "AI may replace..." "However, this might also create..." "It is worth noting that..." "Some evidence suggests..."','hard'),
  (cid,10,69,'production','[TOEFL Writing] The following sentence makes an unhedged, absolute claim: "Social media is destroying young people''s ability to communicate face-to-face." Rewrite this claim using appropriate hedging language, then write a 150+ word essay that develops the argument with properly hedged evidence and qualifications.','',NULL,'Rewrite example: "There is some evidence to suggest that excessive social media use may be associated with reduced face-to-face communication skills in certain populations." Then develop: "Studies tend to show..." "However, it should be noted that..."','hard'),
  (cid,10,70,'production','[TOEFL Writing] Write a 150+ word academic response to the following prompt. Use at least SIX different hedging devices (modal verbs, hedging verbs, epistemic phrases, approximators, frequency hedges, or limitation phrases). Prompt: "To what extent does economic inequality contribute to social conflict?" Underline or label each hedging device you use.','',NULL,'Target hedges: "may contribute," "tend to," "it is possible that," "approximately," "in most cases," "appears to suggest," "it is worth noting," "the evidence indicates."','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
