-- ============================================================
-- SEED: Módulo 21 — Inversion (C1)
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'inversion';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo inversion não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 1: Never / Seldom / Rarely Inversion
  (cid,1,1,'gap_fill','Never _____ (see) such a dramatic shift in public opinion in such a short period of time.','have I seen',NULL,'"Never" at the beginning triggers inversion: auxiliary + subject + main verb. → Never have I seen.','medium'),
  (cid,1,2,'multiple_choice','Seldom _____ researchers encounter a dataset so complete and free from sampling bias.','do','["researchers do","did researchers","do","have researchers"]','After "Seldom," inversion: Seldom + do + subject + base verb. → Seldom do researchers encounter.','medium'),
  (cid,1,3,'gap_fill','Rarely _____ (a government / admit) its own policy failures so openly and quickly.','does a government admit',NULL,'"Rarely" triggers inversion: Rarely + does + subject + base verb. → Rarely does a government admit.','medium'),
  (cid,1,4,'multiple_choice','Never before _____ the scientific community faced such a complex ethical dilemma.','has','["never has","does","is","has"]','"Never before" triggers inversion with perfect aspect: Never before + has + subject + past participle. → has the community faced.','hard'),
  (cid,1,5,'gap_fill','Seldom _____ (researchers / have) such access to real-time data on a scale like this.','have researchers had',NULL,'"Seldom" triggers inversion. Perfect form: Seldom + have + subject + past participle. → Seldom have researchers had.','hard'),
  (cid,1,6,'multiple_choice','Rarely _____ a scientific paper generate such widespread public interest.','does','["is","rarely does","do","has"]','"Rarely" + inversion: Rarely does + subject + base verb. → Rarely does a scientific paper generate.','medium'),
  (cid,1,7,'gap_fill','Never in the history of medicine _____ (one / find) a cure for a disease so quickly.','has one found',NULL,'"Never in the history of..." triggers inversion. → Never in the history of medicine has one found.','hard'),
  (cid,1,8,'multiple_choice','Which sentence is correctly inverted?','Seldom does the committee reach consensus on the first vote.','["Seldom the committee does reach consensus.","Seldom reaches the committee consensus on the first vote.","Seldom does the committee reach consensus on the first vote.","The committee seldom does reach consensus."]','Correct inversion: Seldom + does + subject + base verb. → Seldom does the committee reach consensus.','medium'),

  -- BLOCK 2: Not Only... But Also / Hardly / No Sooner
  (cid,2,9,'gap_fill','Not only _____ (the experiment / fail) to replicate the original results, but it also revealed a significant flaw in the methodology.','did the experiment fail',NULL,'"Not only" triggers inversion: Not only + did + subject + base verb. → Not only did the experiment fail.','hard'),
  (cid,2,10,'multiple_choice','Hardly _____ the committee begun its review when new evidence emerged that changed everything.','had','["did","was","hardly had","had"]','After "Hardly," use past perfect inversion: Hardly + had + subject + past participle. → Hardly had the committee begun.','hard'),
  (cid,2,11,'gap_fill','No sooner _____ (the results / announce) than three competing labs began to challenge the methodology.','had the results been announced',NULL,'"No sooner had... than" uses past perfect passive inversion. → No sooner had the results been announced than.','hard'),
  (cid,2,12,'multiple_choice','Not only _____ the new policy reduce emissions, but it also created thousands of jobs in the renewable energy sector.','did','["does","has","not only did","did"]','"Not only did + subject + base verb... but also" → Not only did the new policy reduce emissions.','hard'),
  (cid,2,13,'gap_fill','Hardly _____ (she / begin) speaking when the audience interrupted with applause.','had she begun',NULL,'"Hardly had + subject + past participle + when" = inversion for immediate sequence of events.','hard'),
  (cid,2,14,'multiple_choice','No sooner _____ arrived than the meeting was called to order.','had the delegates','["the delegates had","had the delegates","did the delegates","the delegates have"]','"No sooner had + subject + past participle + than" = correct inversion pattern.','hard'),
  (cid,2,15,'gap_fill','Not only _____ (the research team / discover) a new species, but they also documented a previously unknown behavior.','did the research team discover',NULL,'"Not only did + subject + base verb... but also" pattern. → Not only did the research team discover.','hard'),
  (cid,2,16,'multiple_choice','Which sentence correctly uses inversion with "hardly"?','Hardly had the ink dried on the agreement when the first violation was reported.','["Hardly the ink had dried when the first violation was reported.","Hardly did the ink dry when the first violation was reported.","Hardly had the ink dried on the agreement when the first violation was reported.","Hardly was the ink dried when the first violation was reported."]','Correct: Hardly + had + subject + past participle + when. → Hardly had the ink dried when.','hard'),

  -- BLOCK 3: Only After / Only By / Only When Inversion
  (cid,3,17,'gap_fill','Only after years of research _____ (the scientists / able) to isolate the responsible gene.','were the scientists able',NULL,'"Only after + time phrase" triggers inversion. → Only after years of research were the scientists able.','hard'),
  (cid,3,18,'multiple_choice','Only by reducing carbon emissions significantly _____ prevent the worst effects of climate change.','can we','["we can","can we","we could","could we possibly"]','"Only by + gerund phrase" triggers inversion: can/could + subject + base verb. → Only by reducing... can we prevent.','hard'),
  (cid,3,19,'gap_fill','Only when the final data were analyzed _____ (the team / realize) the full significance of their discovery.','did the team realize',NULL,'"Only when + clause" triggers inversion in the main clause: did + subject + base verb. → did the team realize.','hard'),
  (cid,3,20,'multiple_choice','Only after the treaty was signed _____ the displaced communities return to their homeland.','could','["only could","could","did","they could"]','"Only after + clause" → could + subject + base verb. → Only after the treaty was signed could the communities return.','hard'),
  (cid,3,21,'gap_fill','Only by developing alternative energy sources _____ (we / reduce) our dependence on fossil fuels.','can we reduce',NULL,'"Only by + gerund" triggers inversion: can + subject + base verb. → Only by developing... can we reduce.','hard'),
  (cid,3,22,'multiple_choice','Only when governments cooperate _____ global environmental problems be effectively addressed.','can','["only can","can","do","will"]','"Only when + clause" triggers inversion in the main clause. → Only when governments cooperate can global problems be addressed.','hard'),
  (cid,3,23,'gap_fill','Only after considerable debate _____ (the committee / reach) a consensus on the proposed amendments.','did the committee reach',NULL,'"Only after + noun phrase" → inversion: did + subject + base verb. → did the committee reach.','hard'),
  (cid,3,24,'multiple_choice','Which sentence demonstrates "Only by" inversion correctly?','Only by increasing investment in education can a country ensure its long-term prosperity.','["Only by increasing investment in education a country can ensure its long-term prosperity.","Only by increasing investment in education can a country ensure its long-term prosperity.","Only increasing investment in education can ensure a country its long-term prosperity.","Only by investment in education a country can ensure prosperity."]','Correct: Only by + gerund phrase + can/will + subject + base verb. → Only by increasing... can a country ensure.','hard'),

  -- BLOCK 4: Conditional Inversion (Were I to / Had I known / Should you need)
  (cid,4,25,'gap_fill','_____ (were / I / know) the risks, I would never have agreed to participate in the study.','Had I known',NULL,'"Had I known" = formal conditional inversion for third conditional (past unreal). Replaces "If I had known."','hard'),
  (cid,4,26,'multiple_choice','_____ the government to introduce stricter regulations, many companies would be forced to restructure.','Were','["Had","Should","If","Were"]','"Were + subject + infinitive" replaces "If + subject + were + infinitive" in formal conditionals.','hard'),
  (cid,4,27,'gap_fill','_____ (should / you / require) further assistance, please do not hesitate to contact our research office.','Should you require',NULL,'"Should you require" = formal conditional inversion replacing "If you should require." Common in formal writing.','hard'),
  (cid,4,28,'multiple_choice','_____ the experiment been conducted under controlled conditions, the results might have been more reliable.','Had','["Were","Should","If","Had"]','"Had + subject + past participle" replaces "If + subject + had + past participle" for third conditional inversion.','hard'),
  (cid,4,29,'gap_fill','_____ (were / the new treatment / prove) effective, it could revolutionize the management of autoimmune diseases.','Were the new treatment to prove',NULL,'"Were + subject + to + base verb" = formal conditional inversion. Replaces "If the new treatment were to prove."','hard'),
  (cid,4,30,'multiple_choice','Which inverted conditional correctly replaces "If you need more information, please contact us"?','Should you need more information, please contact us.','["Were you need more information, please contact us.","Had you needed more information, please contact us.","Should you need more information, please contact us.","If should you need more information, please contact us."]','"Should you need" = present/future conditional inversion. Replaces "If you need/should need."','hard'),
  (cid,4,31,'gap_fill','_____ (had / we / foresee) the complications, we would have chosen a different research methodology.','Had we foreseen',NULL,'"Had we foreseen" = third conditional inversion (past unreal). Replaces "If we had foreseen."','hard'),
  (cid,4,32,'multiple_choice','Which sentence is NOT a correct conditional inversion?','If were I to consider the proposal, I would need more data.','["Were I to consider the proposal, I would need more data.","Had the data been available, we would have reached different conclusions.","Should the committee approve the plan, implementation would begin in January.","If were I to consider the proposal, I would need more data."]','"If were I to" is incorrect — inversion replaces "if," so you cannot have both "if" AND the inverted structure.','hard'),

  -- BLOCK 5: TOEFL Academic – Inversion in Reading
  (cid,5,33,'gap_fill','[TOEFL Reading] Not only _____ (the study / challenge) existing theories, but it also proposed a novel explanatory framework.','did the study challenge',NULL,'"Not only did + subject + base verb... but also" — academic inversion for emphatic contrast.','hard'),
  (cid,5,34,'multiple_choice','[TOEFL Reading] "Rarely _____ a single variable account for the full range of observed variation in a complex system."','does','["is","rarely does","has","do"]','"Rarely does + subject + base verb" = inversion pattern for "rarely" at the start of a clause.','hard'),
  (cid,5,35,'gap_fill','[TOEFL Reading] _____ (only after / the researchers / control) for confounding variables were the true effects of the treatment revealed.','Only after the researchers controlled',NULL,'"Only after + clause" triggers inversion in the main clause. → Only after the researchers controlled... were the effects revealed.','hard'),
  (cid,5,36,'multiple_choice','[TOEFL Reading] "No sooner _____ the publication released than it sparked significant controversy in the academic community."','had','["was","did","has","had"]','"No sooner had + subject + past participle + than" = past perfect inversion for immediate sequence.','hard'),
  (cid,5,37,'gap_fill','[TOEFL Listening] The professor noted: "Never before in history _____ (we / have) access to such vast quantities of real-time climate data."','have we had',NULL,'"Never before in history have we had" = present perfect inversion with "never before."','hard'),
  (cid,5,38,'multiple_choice','[TOEFL Reading] "Hardly _____ the treaty been ratified when three signatories announced they would withdraw their support."','had','["was","did","has","had"]','"Hardly had + subject + past participle + when" = past perfect inversion for immediate reversal.','hard'),
  (cid,5,39,'gap_fill','[TOEFL Reading] _____ (were / the findings / corroborate) by independent research, they would represent a major breakthrough.','Were the findings to be corroborated',NULL,'"Were + subject + to + passive infinitive" = formal conditional inversion for uncertain future events.','hard'),
  (cid,5,40,'multiple_choice','[TOEFL Reading] Why is inversion used in academic and formal writing?','to add emphasis, formality, and stylistic variation to a sentence','["to shorten sentences","to add emphasis, formality, and stylistic variation to a sentence","to avoid passive constructions","to make sentences easier to understand"]','Inversion serves rhetorical and stylistic purposes: it emphasizes the fronted element and raises the register.','medium'),

  -- BLOCK 6: TOEFL Academic – Error Identification with Inversion
  (cid,6,41,'multiple_choice','[TOEFL Reading] Identify the error: "Not only the committee did reject the proposal, but it also demanded a full review."','Inversion error: should be "Not only did the committee reject"','["No error","Inversion error: should be \"Not only did the committee reject\"","Tense error: should use present perfect","Word order: \"also\" should come before \"it\""]','"Not only did + subject + base verb" is the correct inversion pattern. → Not only did the committee reject.','hard'),
  (cid,6,42,'gap_fill','[TOEFL Reading] Correct the inversion: "Seldom the researchers encountered a more complex ethical dilemma." → Seldom _____ a more complex ethical dilemma.','did the researchers encounter',NULL,'"Seldom" triggers inversion: Seldom + did + subject + base verb. → Seldom did the researchers encounter.','hard'),
  (cid,6,43,'multiple_choice','[TOEFL Reading] Which sentence is grammatically correct?','Had the treatment been administered earlier, the patient''s prognosis would have been far more positive.','["If had the treatment been administered earlier, the prognosis would have been more positive.","Had the treatment been administered earlier, the patient''s prognosis would have been far more positive.","Had been the treatment administered earlier, the prognosis would have been more positive.","The treatment had been administered earlier, the prognosis would have been more positive."]','Correct third conditional inversion: Had + subject + past participle... → Had the treatment been administered.','hard'),
  (cid,6,44,'gap_fill','[TOEFL Listening] The professor said: "Only by integrating multiple methodologies _____ (we / hope) to capture the full complexity of the phenomenon."','can we hope',NULL,'"Only by + gerund" triggers inversion: can + subject + base verb. → Only by integrating... can we hope.','hard'),
  (cid,6,45,'multiple_choice','[TOEFL Reading] "Rarely in academic research _____ a single study provide definitive answers to complex questions."','does','["rarely does","is","do","does"]','"Rarely in academic research does + subject + base verb" = inversion with "rarely" + prepositional phrase.','hard'),
  (cid,6,46,'gap_fill','[TOEFL Reading] _____ (should / the current policy / fail) to achieve its targets, alternative measures will need to be considered.','Should the current policy fail',NULL,'"Should + subject + base verb" = conditional inversion (replaces "If the policy fails/should fail").','hard'),
  (cid,6,47,'multiple_choice','[TOEFL Reading] "Not only _____ the new technology reduce production costs, but it also minimizes environmental impact." Complete the sentence.','does','["does","is","not only does","has"]','"Not only does + subject + base verb... but also" = present tense inversion pattern.','hard'),
  (cid,6,48,'gap_fill','[TOEFL Reading] No sooner _____ (the announcement / make) than rival companies began developing competing products.','had the announcement been made',NULL,'"No sooner had + subject + been + past participle + than" = passive inversion for immediate sequence.','hard'),

  -- BLOCK 7: TOEFL Academic – Distinguishing Inversion Types
  (cid,7,49,'multiple_choice','[TOEFL Reading] Which type of inversion is used in "Were I to accept this position, significant changes would be necessary"?','conditional inversion (replaces "If I were to accept")','["negative adverb inversion","conditional inversion (replaces \"If I were to accept\")","\"not only\" inversion","\"only by\" inversion"]','"Were I to" = conditional inversion. It replaces "If I were to" in formal writing.','hard'),
  (cid,7,50,'gap_fill','[TOEFL Reading] _____ (never / in / this lab / observe) such rapid cell division under non-pathological conditions.','Never in this lab have we observed / Never have we observed in this lab',NULL,'"Never" triggers inversion with present perfect: Never + have + subject + past participle.','hard'),
  (cid,7,51,'multiple_choice','[TOEFL Reading] Which sentence uses inversion to emphasize an unexpected reversal?','No sooner had the peace talks begun than renewed conflict broke out in the border region.','["Furthermore, peace talks began and conflict broke out.","No sooner had the peace talks begun than renewed conflict broke out in the border region.","Peace talks began; however, conflict broke out.","Although peace talks began, conflict broke out."]','"No sooner had... than" emphasizes the immediacy and unexpectedness of the reversal.','hard'),
  (cid,7,52,'gap_fill','[TOEFL Listening] The professor emphasized: "Only when all variables are controlled _____ (we / draw) reliable inferences from the data."','can we draw',NULL,'"Only when + clause" triggers inversion in main clause: can + subject + base verb. → can we draw reliable inferences.','hard'),
  (cid,7,53,'multiple_choice','[TOEFL Reading] "Not only does climate change threaten biodiversity, but it also _____ existing patterns of human settlement." Complete the sentence.','disrupts','["disrupting","disrupted","to disrupt","disrupts"]','After "but also" in a "not only...but also" inversion, the verb returns to normal word order: subject + verb.','hard'),
  (cid,7,54,'gap_fill','[TOEFL Reading] _____ (had / the committee / aware) of the conflict of interest, the vote would have been delayed.','Had the committee been aware',NULL,'"Had + subject + been + adjective" = third conditional inversion for past unreal situation.','hard'),
  (cid,7,55,'multiple_choice','[TOEFL Reading] "Only after" inversion is typically used to emphasize that:','a result or action was not possible until a specific condition was met','["two things happened simultaneously","a result or action was not possible until a specific condition was met","the writer is unsure about the timing","an action was repeated"]','"Only after + condition" stresses the prerequisite nature of the condition for the result to occur.','hard'),
  (cid,7,56,'gap_fill','[TOEFL Reading] _____ (should / any / discrepancy / arise) during the audit, the relevant department must be notified immediately.','Should any discrepancy arise',NULL,'"Should + any + noun + base verb" = conditional inversion for formal instructions or procedures.','hard'),

  -- BLOCK 8: TOEFL Academic – Mixed Inversion Practice
  (cid,8,57,'multiple_choice','[TOEFL Reading] Choose the correct completion: "Hardly _____ the new regulations announced when industry groups began lobbying for their reversal."','had','["were","did","has","had"]','"Hardly had + subject + past participle + when" = inversion for immediate past sequence.','hard'),
  (cid,8,58,'gap_fill','[TOEFL Reading] Not only _____ (the drug / demonstrate) efficacy in clinical trials, but it also showed unprecedented safety at high doses.','did the drug demonstrate',NULL,'"Not only did + subject + base verb... but also" = emphatic inversion for formal academic writing.','hard'),
  (cid,8,59,'multiple_choice','[TOEFL Reading] "_____ the budget been approved in time, the research station would have opened last spring."','Had','["Were","Should","If","Had"]','"Had + subject + past participle" = third conditional inversion. → Had the budget been approved.','hard'),
  (cid,8,60,'gap_fill','[TOEFL Listening] "Only by listening to multiple perspectives _____ (one / hope) to arrive at a nuanced understanding of complex issues."','can one hope',NULL,'"Only by + gerund" → can + subject + base verb. → Only by listening... can one hope.','hard'),
  (cid,8,61,'multiple_choice','[TOEFL Reading] Which sentence does NOT contain correct inversion?','Not only the government failed to act, but it also ignored expert advice.','["Not only did the government fail to act, but it also ignored expert advice.","Seldom does a policy achieve all its stated objectives.","Not only the government failed to act, but it also ignored expert advice.","Were the data to be verified, the conclusions would need to be revised."]','"Not only the government failed" is incorrect. "Not only" requires inversion: Not only did the government fail.','hard'),
  (cid,8,62,'gap_fill','[TOEFL Reading] Seldom _____ (a policy / achieve) such broad bipartisan support in the current political climate.','does a policy achieve',NULL,'"Seldom does + subject + base verb" = correct inversion. → Seldom does a policy achieve.','hard'),
  (cid,8,63,'multiple_choice','[TOEFL Reading] "Only when socioeconomic inequality is addressed _____ sustained improvements in public health be achieved."','can','["will","do","are","can"]','"Only when + clause" triggers inversion: can + subject + base verb. → can sustained improvements be achieved.','hard'),
  (cid,8,64,'gap_fill','[TOEFL Reading] _____ (were / the policy / implement) across all member states, significant reductions in emissions would be achieved within a decade.','Were the policy to be implemented',NULL,'"Were + subject + to + passive infinitive" = formal conditional inversion for uncertain events.','hard'),

  -- BLOCK 9: TOEFL Speaking Tasks
  (cid,9,65,'production','[TOEFL Speaking — 45s] The reading passage describes the challenges of renewable energy adoption. The lecture argues that only by investing in grid infrastructure can countries achieve widespread renewable energy use. Summarize the main points of the lecture and explain how they relate to the reading. Try to use at least one inverted structure in your response. You have 45 seconds.','',NULL,'Target structures: "Not only does the professor argue... but also..." "Only by investing..." "Rarely do countries..."','hard'),
  (cid,9,66,'production','[TOEFL Speaking — 45s] Think of a time when you faced an unexpected challenge or obstacle. Describe the situation and explain what you did. Use emphatic structures like "Not only did I..., but I also..." or "Never before had I..." to make your response more vivid and emphatic. You have 45 seconds.','',NULL,'Practice: "Not only did I have to... but I also..." "Never before had I faced..." "Only after ... did I realize..."','hard'),
  (cid,9,67,'production','[TOEFL Speaking — 45s] Some people argue that only by overhauling the current education system can countries prepare young people for the demands of the 21st century. Do you agree? Explain your view with specific reasons. Use at least one inverted structure. You have 45 seconds.','',NULL,'Use: "Only by restructuring curricula can schools..." "Not only does traditional education fail to... but it also..." "Rarely do students develop..."','hard'),

  -- BLOCK 10: TOEFL Writing Tasks
  (cid,10,68,'production','[TOEFL Writing] Write an essay (150+ words) on the following topic: "Technological innovation alone cannot solve the world''s most pressing environmental problems." Agree or disagree? Use at least THREE inverted structures in your essay (e.g., "Not only does..., but...," "Only by...," "Never before have we...," "Were governments to..."). Underline each inverted structure.','',NULL,'Inverted structures to include: "Not only does technology offer solutions, but it also creates new problems." "Only by changing consumption habits can we address..." "Were governments to invest..."','hard'),
  (cid,10,69,'production','[TOEFL Writing] Integrated task: The reading argues that urban agriculture can contribute significantly to food security. The lecture challenges this claim, arguing that only after major infrastructure challenges are resolved can urban farming scale effectively. Write a 150+ word response. Include at least TWO inverted structures in your analysis.','',NULL,'Target: "Not only does the professor challenge the reading''s claim, but she also..." "Only after... can urban farming..." "Seldom does the reading address..."','hard'),
  (cid,10,70,'production','[TOEFL Writing] Write a 150+ word formal essay on the following statement: "Rarely has a single technological development had as profound an impact on society as the Internet." Discuss the social, educational, and economic impacts of the Internet. Use at least FOUR different types of inversion (negative adverb, "not only...but also," "only by/after/when," and conditional inversion). Identify each type of inversion you use.','',NULL,'Four inversion types to target: 1. Negative adverb: "Never before has..." 2. "Not only did/has...but also" 3. "Only by/after/when..." 4. Conditional: "Were governments to..." or "Had the Internet not been invented..."','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
