-- ============================================================
-- SEED EXT 6: Módulo 21 — Inversion (ex 204-300)
-- Blocos 71-82 | 97 exercícios
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'inversion';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo inversion não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 71: Negative adverbials — Never, Rarely, Seldom (8 ex)
  (cid,71,204,'gap_fill','_____ (Never) _____ (before/have/the/field/witness) such a rapid convergence of empirical evidence around a single theoretical framework, and _____ (never/before/has/the/need) for rigorous methodological standards been more urgent.','Never before has the field witnessed / never before has the need',NULL,'Negative adverbial ''Never before'' triggers subject-auxiliary inversion: ''has the field witnessed,'' ''has the need been.''','hard'),
  (cid,71,205,'gap_fill','_____ (Rarely) _____ (does/such/a/comprehensive/study) emerge from a single research team, and _____ (rarely/has/the/question) of institutional reform been addressed with such analytical precision.','Rarely does such a comprehensive study / rarely has the question',NULL,'''Rarely does'' = do-support inversion with simple present; ''rarely has'' = auxiliary inversion with present perfect.','hard'),
  (cid,71,206,'gap_fill','_____ (Seldom) _____ (has/the/relationship) between formal design and governance outcomes been examined with such methodological rigor — and _____ (seldom/have/the/implications) of such an examination been so far-reaching.','Seldom has the relationship / seldom have the implications',NULL,'''Seldom has the relationship been examined'' + ''seldom have the implications been'' = parallel inversion with present perfect passive.','hard'),
  (cid,71,207,'gap_fill','_____ (Hardly) _____ (had/the/reform/be/announce/passive) before critics began to challenge its fundamental assumptions — and _____ (hardly/had/one/objection/be/address/passive) before another emerged to take its place.','Hardly had the reform been announced / hardly had one objection been addressed',NULL,'''Hardly had...been + past participle'' = past perfect inversion with passive; time connective triggers inversion.','hard'),
  (cid,71,208,'gap_fill','_____ (Scarcely) _____ (had/the/ink/dry/passive) on the agreement when the first signs of implementation difficulties became apparent, _____ (scarcely/had/anyone/anticipate/passive) the depth of the resistance that would materialize.','Scarcely had the ink dried / scarcely had anyone anticipated',NULL,'''Scarcely had...dried'' (past perfect inversion); ''scarcely had anyone anticipated'' = similar pattern with existential subject.','hard'),
  (cid,71,209,'gap_fill','_____ (No sooner) _____ (had/the/committee/release/passive/its/report) than the government announced a comprehensive review — _____ (no sooner/had/the/review/begin) than additional complications emerged.','No sooner had the committee released its report / no sooner had the review begun',NULL,'''No sooner had...than'' = past perfect inversion; second clause mirrors the pattern.','hard'),
  (cid,71,210,'gap_fill','_____ (Little) _____ (did/the/architects/of/the/reform/realize) that their assumptions about compliance would prove so inaccurate — _____ (little/did/they/anticipate) the degree to which vested interests would mobilize against implementation.','Little did the architects of the reform realize / little did they anticipate',NULL,'''Little did...realize/anticipate'' = emphatic inversion signaling that something was unknown or underestimated.','hard'),
  (cid,71,211,'multiple_choice','Which sentence CORRECTLY applies negative adverbial inversion?','Rarely has the question of governance reform attracted such sustained scholarly attention.','[''Rarely the question of governance reform has attracted such sustained scholarly attention.'',''Rarely has the question of governance reform attracted such sustained scholarly attention.'',''Rarely did the question of governance reform has attracted such scholarly attention.'',''Rarely the governance reform question has such attention attracted.'']','Option B: ''Rarely has + subject + past participle'' = correct present perfect inversion. Option A lacks inversion. Options C/D have structural errors.','easy'),

  -- BLOCK 72: Not only...but also / Not until (8 ex)
  (cid,72,212,'gap_fill','_____ (Not only) _____ (did/the/reform/fail/to/achieve) its stated objectives, _____ (but/it/also/produce/passive) a range of unintended consequences that proved more costly than the original problem.','Not only did the reform fail to achieve / but it also produced',NULL,'''Not only did...fail'' = inversion in first clause; ''but it also'' = normal order in second clause.','hard'),
  (cid,72,213,'gap_fill','_____ (Not only) _____ (has/the/evidence/become/stronger) in recent years, _____ (but/the/methodological/tool) available to researchers have also improved significantly, _____ (enable) more rigorous _____ (test → noun) of _____ (compete → noun) _____ (hypothesis).','Not only has the evidence become stronger / but the methodological tools / enabling / testing / competing / hypotheses',NULL,'''Not only has...become'' (present perfect inversion) + ''but the methodological tools have also'' (normal order) + ''enabling testing.''','hard'),
  (cid,72,214,'gap_fill','_____ (Not until) _____ (the/committee/publish/past/its/findings) did the government acknowledge the severity of the problem — and _____ (not until/those/finding/be/widely/report/passive) did public pressure begin to build.','Not until the committee published its findings / not until those findings were widely reported',NULL,'''Not until...did'' = past simple inversion after ''not until + past simple clause.''','hard'),
  (cid,72,215,'gap_fill','_____ (Not only) _____ (does/effective/governance/require) formal institutional structures, _____ (but/it/also/depend) on the informal norms and professional cultures that shape how those structures operate in practice.','Not only does effective governance require / but it also depends',NULL,'''Not only does...require'' (present simple do-support inversion) + ''but it also depends'' (normal order).','medium'),
  (cid,72,216,'gap_fill','_____ (Not until/the/late/twentieth/century) _____ (did/researchers/begin) to appreciate the full complexity of the relationship between institutional design and governance outcomes — _____ (not until/then/did/the/field) develop the methodological tools adequate to address it.','Not until the late twentieth century / did researchers begin / not until then did the field',NULL,'''Not until [time phrase] did'' = temporal inversion; second clause uses ''not until then did'' as condensed version.','hard'),
  (cid,72,217,'gap_fill','_____ (Not only) _____ (was/the/design/flawed), _____ (but/the/implementation/process) was also poorly managed, _____ (leave/gerund) the reform _____ (unable) to _____ (achieve) any of its principal _____ (objective/noun).','Not only was the design flawed / but the implementation process / leaving / unable / achieve / objectives',NULL,'''Not only was...flawed'' (be-verb inversion) + ''but the implementation was also'' (normal order).','medium'),
  (cid,72,218,'gap_fill','_____ (Not only) _____ (had/the/previous/policy/fail/passive) to address the core problem, _____ (but/it/had/also/exacerbate/passive) it by _____ (create/gerund) _____ (perverse) _____ (incentive) that _____ (discourage) the _____ (precise) _____ (behavior) it _____ (was) _____ (intend/passive) to _____ (promote).','Not only had the previous policy failed / but it had also been exacerbated / creating / perverse / incentives / discouraged / precise / behavior / was / intended / promote',NULL,'''Not only had...failed'' (past perfect inversion) + ''but it had also been exacerbated by creating perverse incentives.''','hard'),
  (cid,72,219,'multiple_choice','Which sentence CORRECTLY uses ''not only...but also'' inversion?','Not only did the reform fail to achieve its objectives, but it also produced unintended consequences.','[''Not only the reform failed to achieve its objectives, but it also produced unintended consequences.'',''Not only did the reform fail to achieve its objectives, but it also produced unintended consequences.'',''Not only did the reform failed to achieve its objectives, but also it produced consequences.'',''Not only failed the reform to achieve its objectives, but also it produced unintended consequences.'']','Option B: ''Not only did + base verb'' + ''but it also + past simple'' (normal order in second clause).','easy'),

  -- BLOCK 73: Only + adverbial (Only when, Only after, Only by) (8 ex)
  (cid,73,220,'gap_fill','_____ (Only when) _____ (the/full/extent/of/the/problem/become/passive/known) _____ (did/the/government/agree) to commission an independent review — and even then, only _____ (after/significant/public/pressure/have/mount).','Only when the full extent of the problem became known / did the government agree / after significant public pressure had mounted',NULL,'''Only when + clause + did + subject + verb'' = inversion triggered by fronted ''only when'' clause.','hard'),
  (cid,73,221,'gap_fill','_____ (Only after) _____ (several/year/of/intensive/research) _____ (did/the/team/manage) to identify the mechanisms through which the intervention produced its effects — _____ (a) _____ (delay) that _____ (reflect) the inherent _____ (difficulty) of _____ (causal/noun) _____ (inference) in complex _____ (system).','Only after several years of intensive research / did the team manage / a / delay / reflects / difficulty / causal / inference / systems',NULL,'''Only after [time phrase] did + subject + verb'' = temporal inversion. Second clause: normal order.','hard'),
  (cid,73,222,'gap_fill','_____ (Only by) _____ (adopt/gerund) _____ (a) _____ (more) _____ (nuanced) _____ (approach) _____ (to) _____ (the) _____ (measure → noun) _____ (of) _____ (governance) _____ (quality) _____ (can/researcher/hope) to capture the full range of factors that determine organizational performance.','Only by adopting / a / more / nuanced / approach / to / the / measurement / of / governance / quality / can researchers hope',NULL,'''Only by + gerund phrase + can + subject + verb'' = inversion triggered by fronted ''only by'' phrase.','hard'),
  (cid,73,223,'gap_fill','_____ (Only) _____ (in) _____ (the) _____ (context) _____ (of) _____ (a) _____ (broader) _____ (understand → noun) _____ (of) _____ (institutional) _____ (dynamic) _____ (can/these/finding) be properly _____ (interpret/passive) and their _____ (implication) for _____ (policy) _____ (assess/passive).','Only / in / the / context / of / a / broader / understanding / of / institutional / dynamics / can these findings / interpreted / implications / policy / assessed',NULL,'''Only in the context of... can + subject + be + past participle'' = inversion with fronted prepositional phrase containing ''only.''','hard'),
  (cid,73,224,'gap_fill','_____ (Only when) _____ (formal) _____ (incentive) _____ (align) _____ (with) _____ (informal) _____ (norm) _____ (do/governance/arrangement) tend to produce the kind of _____ (sustain) _____ (improve → noun) in _____ (performance) that _____ (reform) _____ (are) _____ (design/passive) to _____ (achieve).','Only when / formal / incentives / align / with / informal / norms / do governance arrangements / sustained / improvement / performance / reforms / are / designed / achieve',NULL,'''Only when + clause + do + subject + verb'' = present simple inversion; ''sustained improvement in performance.''','hard'),
  (cid,73,225,'gap_fill','_____ (Only after) _____ (the/reform/process/has/run/its/course) _____ (will/it/be/possible) to evaluate its full impact — and even then, _____ (only/with/access/to/comprehensive/outcome/data) _____ (will/researcher/be/able) to distinguish genuine improvement from superficial change.','Only after the reform process has run its course / will it be possible / only with access to comprehensive outcome data / will researchers be able',NULL,'''Only after...will + subject + be'' = future inversion; second: ''only with...will + subject + be able.''','hard'),
  (cid,73,226,'gap_fill','_____ (Only by) _____ (recogniz/gerund) the inherent limitations of any single _____ (methodological/noun) _____ (approach) _____ (can/researcher/make) the kind of _____ (epistem → noun) _____ (modest → noun) that _____ (responsible) _____ (scholarship) _____ (require).','Only by recognizing / methodological / approach / can researchers make / epistemic / modesty / responsible / scholarship / requires',NULL,'''Only by + gerund + can + subject + verb'' = modal inversion; epistemic modesty = key academic concept.','hard'),
  (cid,73,227,'multiple_choice','Which sentence CORRECTLY applies ''only when'' inversion?','Only when the full extent of the crisis became apparent did the government commission an independent review.','[''Only when the full extent of the crisis became apparent the government commissioned a review.'',''Only when did the full extent of the crisis become apparent did the government commission a review.'',''Only when the full extent of the crisis became apparent did the government commission an independent review.'',''Only when becomes apparent the crisis did the government commission a review.'']','Option C: ''Only when + past simple clause + did + subject + base verb'' = correct inversion pattern.','easy'),

  -- BLOCK 74: Under no circumstances / In no way / On no account (8 ex)
  (cid,74,228,'gap_fill','_____ (Under no circumstances) _____ (should/the/integrity/of/the/review/process/compromise/passive) — _____ (any) _____ (departure) from _____ (establish/passive) _____ (procedure) _____ (will) _____ (undermine) public _____ (confidence) in the _____ (institution).','Under no circumstances should the integrity of the review process be compromised / any / departure / established / procedures / will / undermine / confidence / institution',NULL,'''Under no circumstances should + subject + be + past participle'' = negative adverbial inversion with should.','hard'),
  (cid,74,229,'gap_fill','_____ (In no way) _____ (does/this/analysis/suggest) that formal institutional design is irrelevant — _____ (on/the/contrary), it _____ (argue) that _____ (design) _____ (matter) considerably but _____ (must/supplement/passive) by attention to informal factors.','In no way does this analysis suggest / on the contrary / argues / design / matters / must be supplemented',NULL,'''In no way does...suggest'' = negative adverbial do-support inversion; ''on the contrary'' transition.','hard'),
  (cid,74,230,'gap_fill','_____ (On no account) _____ (should/these/preliminary/finding/treat/passive) as _____ (definitive/noun) _____ (evidence) — they _____ (represent) a _____ (tentative) _____ (step) in the _____ (direction) of _____ (a) _____ (more) _____ (comprehensive) _____ (understand → noun) of the _____ (phenomenon).','On no account should these preliminary findings be treated / definitive / evidence / represent / tentative / step / direction / a / more / comprehensive / understanding / phenomenon',NULL,'''On no account should + subject + be + past participle'' = negative adverbial inversion; epistemic modesty follows.','hard'),
  (cid,74,231,'gap_fill','_____ (Under no circumstances) _____ (can/the/conclusion) that corruption is an inevitable feature of political life _____ (accept/passive) without _____ (profound) _____ (damage) to the _____ (enterprise) of _____ (governance) _____ (reform).','Under no circumstances can the conclusion / be accepted / profound / damage / enterprise / governance / reform',NULL,'''Under no circumstances can + subject + be + past participle'' = modal inversion with can.','hard'),
  (cid,74,232,'gap_fill','_____ (In no way) _____ (do/these/finding/contradict) the established consensus — rather, they _____ (refine) and _____ (extend) it by _____ (draw/gerund) _____ (attention) to _____ (dimension) that have _____ (receive/passive) _____ (insufficient) _____ (empirical) _____ (examine → noun).','In no way do these findings contradict / refine / extend / drawing / attention / dimensions / received / insufficient / empirical / examination',NULL,'''In no way do...contradict'' (present simple inversion) + ''rather, they refine and extend'' (normal order).','hard'),
  (cid,74,233,'gap_fill','_____ (At no point) _____ (did/the/authors/claim) that their _____ (analysis) _____ (was) _____ (exhaustive) — on the _____ (contrary), they _____ (acknowledge/past) explicitly that _____ (significant) _____ (gap) _____ (remain) and that _____ (further) _____ (research) _____ (is) _____ (needed/passive).','At no point did the authors claim / analysis / was / exhaustive / contrary / acknowledged / significant / gaps / remain / further / research / is / needed',NULL,'''At no point did + subject + base verb'' = negative adverbial past inversion; ''acknowledge...explicitly.''','hard'),
  (cid,74,234,'gap_fill','_____ (Under no circumstances) _____ (should/the/political) _____ (pressure) _____ (that) _____ (inevitably) _____ (surround) _____ (governance) _____ (reform) _____ (allow/passive) to _____ (compromise) the _____ (independence) of _____ _____ (those) _____ (charged) _____ (with) _____ (evaluate/gerund) _____ (its) _____ (effectiveness).','Under no circumstances should the political / pressure / that / inevitably / surrounds / governance / reform / be allowed / to / compromise / independence / of / those / charged / with / evaluating / its / effectiveness',NULL,'''Under no circumstances should...be allowed to compromise'' = extended passive inversion.','hard'),
  (cid,74,235,'multiple_choice','Which sentence CORRECTLY uses negative adverbial inversion?','In no way does this finding suggest that formal rules are irrelevant to governance outcomes.','[''In no way this finding suggests that formal rules are irrelevant.'',''In no way does this finding suggest that formal rules are irrelevant to governance outcomes.'',''In no way this finding does suggest formal rules are irrelevant.'',''In no way is suggesting this finding that formal rules are irrelevant.'']','Option B: ''In no way does + subject + base verb'' = correct do-support inversion in present simple.','easy'),

  -- BLOCK 75: Conditional inversion (Had, Were, Should) (8 ex)
  (cid,75,236,'gap_fill','_____ (Had/the/reformers/anticipate/past) the degree of opposition they would face, they might have designed a more incremental approach — _____ (had/they/do/so), the _____ (prospect) of _____ (success) _____ (have/be) considerably _____ (higher).','Had the reformers anticipated / had they done so / prospect / success / would have been / higher',NULL,'''Had...anticipated'' = inverted third conditional (if they had anticipated); ''had they done so'' = pronoun-based repeat of condition.','hard'),
  (cid,75,237,'gap_fill','_____ (Were/the/analysis/to/reveal) that informal norms are more important than formal structures, it _____ (have/profound) _____ (implication) for how _____ (reform) is _____ (design) and _____ (evaluate/passive).','Were the analysis to reveal / would have profound / implications / reform / designed / evaluated',NULL,'''Were...to reveal'' = inverted second conditional (if the analysis were to reveal).','hard'),
  (cid,75,238,'gap_fill','_____ (Should/the/committee/find) that the current framework is inadequate, _____ (it/will/be/necessary) to initiate a comprehensive review — _____ (should/it/also/find) that resources are insufficient, _____ (additional) _____ (fund → noun) _____ (will/need/passive).','Should the committee find / it will be necessary / should it also find / additional / funding / will be needed',NULL,'''Should + subject + base verb'' = inverted first conditional (if the committee finds); double condition with ''should...also find.''','hard'),
  (cid,75,239,'gap_fill','_____ (Had/the/government/invest/past) adequately in implementation capacity, the reform _____ (might/achieve/passive) far more of its objectives — _____ (as/it/is/was), the _____ (gap) between _____ (aspiration) and _____ _____ (achieve → noun) _____ (remain) _____ (wide).','Had the government invested / might have been achieved / as it was / gap / aspiration / achievement / remains / wide',NULL,'''Had...invested'' (inverted past conditional) + ''might have been achieved'' (modal perfect passive).','hard'),
  (cid,75,240,'gap_fill','_____ (Were/institutional/reform/as/straightforward) as its proponents often _____ (suggest), the gap between design and _____ (outcome) would be considerably _____ (narrow) than the available _____ (evidence) _____ (suggest).','Were institutional reform as straightforward / suggest / outcomes / narrower / evidence / suggests',NULL,'''Were + subject + adjective'' = inverted second conditional (if institutional reform were as straightforward).','hard'),
  (cid,75,241,'gap_fill','_____ (Should/the/evidence/emerge) that the current approach is producing the intended effects, the case for _____ (continue) _____ (on) _____ (the) _____ (present) _____ (course) will be considerably _____ (strengthen/passive) — _____ (should/it/not), _____ (a) _____ (fundamental) _____ (reconsider → noun) _____ (will/be/necessary).','Should the evidence emerge / continuing / on / the / present / course / strengthened / should it not / a / fundamental / reconsideration / will be necessary',NULL,'''Should...emerge'' (inverted conditional); ''should it not'' = abbreviated inversion; ''reconsideration will be necessary.''','hard'),
  (cid,75,242,'gap_fill','_____ (Had/we/know/past) what we know now about the conditions for reform success, the design of the original program _____ (will) _____ (look) very _____ (different) — _____ (had/we/apply/past/passive) the lessons from _____ (compare → noun) research, _____ (many) of the errors _____ (identify/passive) _____ (in/retrospect) _____ (might/avoid/passive).','Had we known / would / have looked / different / had we applied / comparative / many / identified / in retrospect / might have been avoided',NULL,'''Had we known'' + ''would have looked'' + ''had we applied'' + ''might have been avoided'' = layered past conditional inversion.','hard'),
  (cid,75,243,'multiple_choice','Which sentence CORRECTLY applies conditional inversion?','Were the committee to find evidence of systematic failure, it would be necessary to initiate a comprehensive review.','[''If the committee were to find evidence of systematic failure, it would be necessary to review.'',''Were the committee to find evidence of systematic failure, it would be necessary to initiate a comprehensive review.'',''Were the committee find evidence of systematic failure, it would be necessary to review.'',''Should the committee were to find evidence, a comprehensive review would necessary.'']','Option B: ''Were + subject + to + base verb + clause, modal + subject + verb'' = correct second conditional inversion.','medium'),

  -- BLOCK 76: Fronted locatives and emphatic structures (8 ex)
  (cid,76,244,'gap_fill','_____ (Into/this/intellectual/landscape) _____ (come/past/the/work/of/researchers) who sought to bridge the gap between theoretical models of institutional change and empirical research on governance outcomes — _____ (a) _____ (contribution) that _____ (reshap/past) the _____ (field).','Into this intellectual landscape came the work of researchers / a / contribution / reshaped / field',NULL,'''Into [place] + came + subject'' = locative inversion (literary/formal style); subject follows verb when location is fronted.','hard'),
  (cid,76,245,'gap_fill','_____ (Central/to/this/analysis) _____ (be) the question of whether formal institutional rules are self-enforcing — _____ (equally/central) _____ (be/the/question) of whether informal norms can substitute for _____ (formal) _____ (enforce → noun) _____ (mechanism).','Central to this analysis / is / equally central / is the question / formal / enforcement / mechanisms',NULL,'''Central to this analysis is the question'' = fronted adjective phrase inversion; ''equally central is the question'' mirrors it.','hard'),
  (cid,76,246,'gap_fill','_____ (So/complex) _____ (is/the/relationship) between institutional design and governance outcomes _____ (that) no _____ (single) _____ (theoretical) _____ (framework) _____ (has/yet/prove/passive) capable of _____ (capture/gerund) it in _____ (its) _____ (entirety).','So complex / is the relationship / that / single / theoretical / framework / has yet proved / capturing / its / entirety',NULL,'''So + adjective + is + subject + that'' = emphatic inversion expressing degree; ''has yet proved capable of capturing.''','hard'),
  (cid,76,247,'gap_fill','_____ (Such/be/the/complexity) of the _____ (governance) _____ (challenge) _____ (face/passive) by _____ (contemporary) _____ (state) that _____ (no/single/discipline) can _____ (hope) to _____ (address) _____ (it) _____ (alone) — _____ (only) _____ (through) _____ (integrate → noun) of _____ (multiple) _____ (perspective) can _____ (meaningful) _____ (progress) be _____ (make/passive).','Such is the complexity / governance / challenges / faced / contemporary / states / no single discipline / hope / address / it / alone / only / through / integration / multiple / perspectives / meaningful / progress / be made',NULL,'''Such is the complexity...that'' = inversion with ''such'' (degree/extent); ''only through integration can...be made'' = second inversion.','hard'),
  (cid,76,248,'gap_fill','_____ (So/significant/be/the/implications) of these findings that _____ (the/field) _____ (will) _____ (need) to _____ (revisit) _____ (several) _____ (foundational) _____ (assumption) — _____ (so/far-reaching) _____ (be/their/potential/impact) that a comprehensive reassessment of existing frameworks appears _____ (warrant/passive).','So significant are the implications / the field / will / need / revisit / several / foundational / assumptions / so far-reaching / are their potential impacts / warranted',NULL,'''So significant are the implications that'' + ''so far-reaching are their potential impacts that'' = parallel so-inversion.','hard'),
  (cid,76,249,'gap_fill','_____ (Paramount/among/the/factors) that determine reform success _____ (be) the quality of political leadership — _____ (equally/important) _____ (be) the organizational culture that _____ (this/leader) _____ (create) and _____ (sustain/gerund → noun) over _____ (time).','Paramount among the factors / is / equally important / is / this / leadership / creates / sustaining / time',NULL,'''Paramount among the factors is'' + ''equally important is'' = fronted adjective inversion; subject follows predicate adjective.','hard'),
  (cid,76,250,'gap_fill','_____ (Here/lie) one of the most enduring tensions in the study of governance: the _____ (desire) to _____ (generate) _____ (universal) _____ (principle) and the _____ (recognition) that _____ (governance) _____ (dynamic) are _____ (inherent/adverb) _____ (context-specific).','Here lies / desire / generate / universal / principles / recognition / governance / dynamics / inherently / context-specific',NULL,'''Here lies'' = locative inversion (subject after verb when ''here'' fronted); colon introduces the tension.','medium'),
  (cid,76,251,'multiple_choice','Which sentence CORRECTLY uses ''so...that'' emphatic inversion?','So complex is the relationship between governance and development that no single framework can fully capture it.','[''So complex the relationship between governance and development is that no single framework can capture it.'',''So is complex the relationship between governance and development that no single framework captures it.'',''So complex is the relationship between governance and development that no single framework can fully capture it.'',''The relationship is so complex that no single framework captures it.'']','Option C: ''So + adjective + is + subject + that'' = correct emphatic inversion. Option D is correct but not inverted. Options A/B have structural errors.','medium'),

  -- BLOCK 77: TOEFL Reading — Inversion (8 ex)
  (cid,77,252,'multiple_choice','[TOEFL Reading] ''Never before had scholars attempted to synthesize findings from so many different disciplines.'' The inversion in this sentence is triggered by:','The negative adverb ''never'' fronted at the beginning of the clause.','[''The subject being a proper noun'',''The negative adverb \''never\'' fronted at the beginning of the clause.'',''The use of the past perfect tense'',''The word \''before\'' in the sentence'']','''Never before'' = negative adverbial that forces subject-auxiliary inversion (had + subject).','easy'),
  (cid,77,253,'gap_fill','[TOEFL Reading] ''_____ (Not only/has/the/field/advance) in its analytical tools, _____ (but/it/has/also/develop) a more sophisticated understanding of what makes reform succeed.'' The inverted structure means:','Not only has the field advanced / but it has also developed',NULL,'''Not only has...advanced'' = inversion in first clause; ''but it has also developed'' = normal order in second clause.','medium'),
  (cid,77,254,'gap_fill','[TOEFL Reading] ''_____ (Rarely/do/such/finding) emerge without significant methodological innovation.'' Why is ''do'' used here?','do is the auxiliary verb required for inversion with ''rarely'' in the present simple tense',NULL,'Present simple inversion requires do-support: ''Rarely do + subject + base verb.''','easy'),
  (cid,77,255,'gap_fill','[TOEFL Reading] ''_____ (Only when) _____ (the/evidence/become/past/overwhelming) _____ (did/the/government/act/past).'' What does this inversion structure express?','Only when the evidence became overwhelming / did the government act',NULL,'''Only when [clause] did [subject] [verb]'' = past inversion triggered by fronted ''only when.''','medium'),
  (cid,77,256,'gap_fill','[TOEFL Reading] ''_____ (Had/the/authors/acknowledge/past) these limitations, their conclusions would have been more persuasive.'' This is equivalent to:','Had the authors acknowledged / If the authors had acknowledged these limitations',NULL,'''Had...acknowledged'' = inverted third conditional; equivalent to ''if they had acknowledged.''','easy'),
  (cid,77,257,'gap_fill','[TOEFL Reading] ''So _____ (profound/be) the implications of this research that it prompted a complete reassessment of the field.'' Identify the inversion pattern:','profound are / So + adjective + verb + subject + that = ''so...that'' emphatic inversion',NULL,'''So profound are the implications that'' = emphatic degree inversion; subject follows auxiliary.','medium'),
  (cid,77,258,'gap_fill','[TOEFL Reading] ''_____ (Under no circumstances/should/this/finding/take/passive) as evidence that formal design is irrelevant.'' The correct form is:','Under no circumstances should this finding be taken',NULL,'''Under no circumstances should + subject + be + past participle'' = negative adverbial modal inversion.','medium'),
  (cid,77,259,'multiple_choice','[TOEFL Reading] ''Were institutional reform as straightforward as commonly assumed, the gap between design and outcome would be far narrower.'' This expresses:','A hypothetical second conditional — institutional reform is NOT straightforward.','[''A factual statement about institutional reform'',''A hypothetical second conditional — institutional reform is NOT straightforward.'',''A third conditional about past events'',''A prediction about future reform'']','''Were...as straightforward'' = inverted second conditional; implies the opposite is true in reality.','easy'),

  -- BLOCK 78: TOEFL Speaking — Inversion (8 ex)
  (cid,78,260,'production','[TOEFL Speaking — 45s] Summarize a reading on governance reform using inversion structures throughout.','',NULL,'The reading examines the conditions for successful governance reform, and rarely has the question been addressed with such analytical rigor. Not only does the analysis draw on a comprehensive comparative dataset, but it also incorporates qualitative evidence from case studies in twelve countries. Central to the reading''s argument is the claim that formal institutional design, while necessary, is insufficient on its own — only when it is accompanied by alignment of informal norms does it tend to produce the intended outcomes. Under no circumstances, the author argues, should practitioners assume that the adoption of formal rules is sufficient for behavioral change. Had policymakers appreciated these dynamics earlier, the reading implies, many failed reform efforts might have been avoided.','hard'),
  (cid,78,261,'production','[TOEFL Speaking — 45s] The professor challenges the reading. Use inversion structures throughout.','',NULL,'The professor challenges several of the reading''s central claims. Not only does she question the quality of the comparative evidence, but she also disputes the causal interpretation that the reading places on the correlations it identifies. Rarely, she notes, do researchers in this area adequately address the problem of reverse causality — that good governance may lead to better institutional design rather than the reverse. Only by controlling for this possibility, she argues, can the reading''s conclusions be considered reliable. Were the reading to apply more rigorous causal identification methods, she suggests, several of its findings might look considerably different. In no way, she concludes, should the reading be taken as a definitive account of what determines reform success.','hard'),
  (cid,78,262,'production','[TOEFL Speaking — 60s] Compare reading and professor''s views on governance reform using inversion throughout.','',NULL,'The reading and the professor both address the question of what determines governance reform success, though rarely have two analysts reached such different conclusions from apparently similar evidence. The reading argues that formal institutional design is the primary determinant of reform outcomes — so central is this claim to its argument that the entire analytical framework is built around it. The professor, by contrast, argues that informal factors matter at least as much as formal ones. Not only does she challenge the reading''s causal identification strategy, but she also questions its operationalization of key concepts. Only when both formal and informal factors are incorporated into the analysis, she argues, can the full complexity of the governance reform process be appreciated. Had the reading adopted a more comprehensive theoretical framework, the professor implies, its conclusions might have been more nuanced. Under no circumstances, she suggests, should the reading''s formal-design-centered approach be adopted by practitioners without qualification. So significant are the differences between the two perspectives that any attempt to synthesize them must grapple seriously with the methodological and theoretical issues that lie at the heart of the disagreement.','hard'),
  (cid,78,263,'gap_fill','[TOEFL Speaking] _____ (Not only/does/this/evidence/support) the reading''s main claim, _____ (but/it/also/suggest) that the relationship is more robust than previously _____ (assume/passive).','Not only does this evidence support / but it also suggests / assumed',NULL,'''Not only does...support'' (inversion) + ''but it also suggests'' (normal order) + ''than previously assumed.''','medium'),
  (cid,78,264,'gap_fill','[TOEFL Speaking] _____ (Rarely/have/scholars) managed to bridge the gap between theoretical models and empirical evidence as effectively as the reading _____ (attempt) to do — _____ (though/not/all) of its _____ (attempt → noun) _____ (be) _____ (equally/adverb) _____ (successful/adjective).','Rarely have scholars / attempts / though not all / attempts / are / equally / successful',NULL,'''Rarely have + subject + past participle'' (present perfect inversion) + ''though not all of its attempts are equally successful.''','hard'),
  (cid,78,265,'gap_fill','[TOEFL Speaking] _____ (Were/the/professor''s/critique/correct), the _____ (implication) _____ (would/be) that the _____ (entire) _____ (theoretical) _____ (framework) of the _____ (reading) _____ (need/passive) to _____ (revise/passive) — _____ (a) _____ (conclusion) _____ (that) the _____ (reading) _____ (reject/past) _____ (categorically).','Were the professor''s critique correct / implications / would be / entire / theoretical / framework / reading / needed / be revised / a / conclusion / that / reading / rejected / categorically',NULL,'''Were...correct'' (inverted second conditional) + ''would be that'' + ''a conclusion that the reading rejected categorically.''','hard'),
  (cid,78,266,'gap_fill','[TOEFL Speaking] _____ (So/compelling/is/the/evidence) for _____ (a) _____ (more) _____ (nuanced) _____ (approach) that _____ (even) _____ (the) _____ (most) _____ (skeptical) _____ (reader) would _____ (find) it _____ (difficult) to _____ (dismiss/passive) _____ (entirely).','So compelling is the evidence / a / more / nuanced / approach / even / the / most / skeptical / reader / find / difficult / be dismissed / entirely',NULL,'''So compelling is the evidence that'' = emphatic degree inversion; ''difficult to be dismissed entirely.''','hard'),
  (cid,78,267,'multiple_choice','[TOEFL Speaking] Which inverted sentence BEST demonstrates academic proficiency in a 45-second task?','Not only does the reading provide a comprehensive analysis of governance reform, but it also identifies several factors that prior research had overlooked.','[''The reading provides a comprehensive analysis and identifies factors that prior research overlooked.'',''Not only does the reading provide a comprehensive analysis of governance reform, but it also identifies several factors that prior research had overlooked.'',''The reading not only provides comprehensive analysis, and it also identifies prior-overlooked factors.'',''Not only the reading provides a comprehensive analysis, but it also identifies factors overlooked.'']','Option B: correct ''Not only does...but it also'' structure; complete parallel clauses; demonstrates mastery of inversion.','medium'),

  -- BLOCK 79: TOEFL Writing — Inversion produção (8 ex)
  (cid,79,268,'production','[TOEFL Writing — 200 words] Write a body paragraph on institutional reform using inversion structures throughout.','',NULL,'Rarely has the challenge of institutional reform been more urgent than it is today — and rarely have the tools available to researchers been more sophisticated. Not only do we now have access to large-scale comparative datasets that allow for more rigorous testing of theoretical claims, but we also have a growing body of qualitative research that illuminates the mechanisms through which formal institutional changes translate into behavioral outcomes. Central to the emerging consensus, however, is a recognition that had eluded earlier generations of scholars: that formal design, while necessary, is insufficient without corresponding alignment of informal norms and incentive structures. Under no circumstances should practitioners assume that the adoption of formal accountability mechanisms will automatically produce the accountability behavior those mechanisms are designed to encourage. Only when formal rules are reinforced by organizational culture, leadership behavior, and appropriate incentive alignment do they tend to produce the intended effects. So significant is this insight that it has prompted a fundamental reassessment of how governance reform programs are designed and evaluated — a reassessment that, had it occurred earlier, might have prevented many of the costly failures that have characterized reform efforts over the past several decades.','hard'),
  (cid,79,269,'production','[TOEFL Writing — 200 words] Write a body paragraph on the conditions for reform success using inversion.','',NULL,'Not only does governance reform require the right institutional design, but it also depends on a set of political and organizational conditions that are often overlooked in the design phase. Rarely do reform initiatives fail because of poor design alone — more commonly, they fail because the political conditions necessary for sustained implementation are not present, or because the organizational capacity to execute the reform as designed does not exist. Only when these political and organizational dimensions are addressed alongside the formal design questions can reform be expected to achieve its stated objectives. Had previous generations of reformers appreciated this complexity, many of the patterns of failure that characterize the historical record of governance reform might have been avoided. So persistent is the tendency to focus on design at the expense of implementation that it constitutes what might be called a systematic bias in how the governance reform community approaches its work. Under no circumstances should this bias be allowed to continue unchallenged — it distorts resource allocation, shapes unrealistic expectations, and ultimately undermines the case for reform by producing a record of disappointment that makes the enterprise seem less viable than it is.','hard'),
  (cid,79,270,'gap_fill','[TOEFL Writing] _____ (Not only/does/effective/governance/require) formal institutional structures, _____ (but/it/also/depend) on informal norms and professional cultures that _____ (shape) _____ (how) _____ (those) _____ (structure) _____ (operate) _____ (in) _____ (practice).','Not only does effective governance require / but it also depends / shape / how / those / structures / operate / in / practice',NULL,'''Not only does...require'' (inversion) + ''but it also depends'' (normal order) + ''shape how those structures operate.''','medium'),
  (cid,79,271,'gap_fill','[TOEFL Writing] _____ (Rarely/has/the/field/witness/passive) such rapid progress — _____ (and/rarely/has/the/need) for rigorous empirical _____ (test → noun) of _____ (theoretical) _____ (claim) been more _____ (urgent/adverb) _____ (feel/passive).','Rarely has the field been witnessed / and rarely has the need / testing / theoretical / claims / urgently / felt',NULL,'''Rarely has...been witnessed'' + ''rarely has the need been urgently felt'' = parallel present perfect inversions.','hard'),
  (cid,79,272,'gap_fill','[TOEFL Writing] _____ (Only by) _____ (attend/gerund) to _____ (both) _____ (formal) and _____ (informal) _____ (dimension) of _____ (governance) _____ (can/researcher) _____ (hope) to _____ (develop) _____ (a) _____ (fully) _____ (adequate) _____ (theoretical) _____ (account) of _____ _____ (what) _____ (determine) _____ (institutional) _____ (performance).','Only by / attending / both / formal / informal / dimensions / governance / can researchers / hope / develop / a / fully / adequate / theoretical / account / what / determines / institutional / performance',NULL,'''Only by attending to...can researchers hope to develop'' = fronted gerund phrase inversion.','hard'),
  (cid,79,273,'gap_fill','[TOEFL Writing] _____ (So/far-reaching/are/the/implication) of this research that _____ (the/entire) _____ (approach) to _____ (governance) _____ (reform) may _____ (need/passive) to _____ (reconsider/passive) — _____ (a) _____ (conclusion) that _____ (will/undoubtedly/provoke) both _____ (enthusiasm) and _____ (resistance).','So far-reaching are the implications / the entire / approach / governance / reform / need / be reconsidered / a / conclusion / will undoubtedly provoke / enthusiasm / resistance',NULL,'''So far-reaching are the implications that...need to be reconsidered'' = emphatic inversion; ''a conclusion that will provoke both enthusiasm and resistance.''','hard'),
  (cid,79,274,'gap_fill','[TOEFL Writing] _____ (Were/the/field/to/adopt) a more integrative approach to the study of governance, _____ (the/prospect) of _____ (develop/gerund) genuinely _____ (cumulative) _____ (knowledge) _____ (would/be) considerably _____ _____ (enhance/passive).','Were the field to adopt / the prospect / developing / genuinely / cumulative / knowledge / would be / considerably enhanced',NULL,'''Were + subject + to + base verb'' (inverted second conditional) + ''would be considerably enhanced'' (modal perfect).','hard'),
  (cid,79,275,'multiple_choice','[TOEFL Writing] Which inverted sentence MOST effectively opens a body paragraph on institutional reform?','Rarely has the challenge of institutional reform been more urgent — nor have the tools available to address it been more sophisticated.','[''Institutional reform is rarely urgent, and the tools to address it are sophisticated.'',''Rarely has the challenge of institutional reform been more urgent — nor have the tools available to address it been more sophisticated.'',''The challenge of institutional reform has rarely been so urgent or sophisticated.'',''Rarely institutional reform''s challenge has been urgent, and tools sophisticated.'']','Option B: two parallel negative adverbial inversions (''rarely has...been,'' ''nor have...been'') = elegant, formally complex academic opening.','hard'),

  -- BLOCK 80: Gap fills avançados — síntese (8 ex)
  (cid,80,276,'gap_fill','_____ (Not until/the/full/complexity/of/the/problem/be/appreciate/passive) _____ (did/the/field/begin) to develop theoretical frameworks adequate to address it — _____ (and/not/until/those/framework/be/test/passive) rigorously _____ (did/the/evidence/begin) to accumulate.','Not until the full complexity of the problem was appreciated / did the field begin / and not until those frameworks were tested / did the evidence begin',NULL,'''Not until [clause] did [subject] [verb]'' = past inversion; double ''not until'' structure with parallel inversion.','hard'),
  (cid,80,277,'gap_fill','_____ (Only/with/a/more/sophisticated/understanding) of the political economy of reform _____ (can/practitioner/hope) to design _____ (intervene → noun) that _____ (stand) a realistic chance of _____ (achieve/gerund) _____ (sustain) _____ (improve → noun) in _____ (governance) _____ (quality).','Only with a more sophisticated understanding / can practitioners hope / interventions / stand / achieving / sustained / improvement / governance / quality',NULL,'''Only with + noun phrase + can + subject + verb'' = fronted prepositional phrase inversion.','hard'),
  (cid,80,278,'gap_fill','_____ (So/profound/be/the/insight) that _____ (emerge) from _____ (careful) _____ (analyze → noun) of _____ (governance) _____ (failure) that _____ (they) _____ (deserve) to _____ (be) _____ (integrate/passive) _____ (into) _____ (the) _____ (design) _____ (of) _____ (reform) _____ (program) _____ (from) _____ (the) _____ (outset).','So profound are the insights / emerge / careful / analysis / governance / failure / they / deserve / be / integrated / into / the / design / of / reform / programs / from / the / outset',NULL,'''So profound are the insights that emerge from analysis that they deserve to be integrated.''','hard'),
  (cid,80,279,'gap_fill','_____ (Had/the/lessons/of/comparative/research/be/take/passive) more seriously by _____ (those) _____ (design/gerund) the _____ (original) _____ (reform), many of the _____ (costly) _____ (mistake) that _____ (subsequently/make/passive) _____ (might/avoid/passive).','Had the lessons of comparative research been taken / those / designing / original / reform / costly / mistakes / were subsequently made / might have been avoided',NULL,'''Had...been taken more seriously'' (past perfect inversion) + ''might have been avoided'' (modal perfect passive).','hard'),
  (cid,80,280,'gap_fill','_____ (Central/to/the/argument) _____ (be) the _____ (claim) that _____ (governance) _____ (quality) is _____ (determine/passive) _____ (by) _____ (both) _____ (formal) and _____ (informal) _____ (factor) — _____ (and/equally/central) _____ (be/the/implication) that _____ (reform) _____ (must/address) _____ (both) _____ (if) _____ (it) _____ (is) _____ (to/succeed).','Central to the argument / is / claim / governance / quality / is determined / by / both / formal / informal / factors / and equally central / is the implication / reform / must address / both / if / it / is / to succeed',NULL,'''Central to...is'' + ''and equally central is the implication'' = parallel fronted adjective inversions.','hard'),
  (cid,80,281,'gap_fill','_____ (Were/reform/as/simple/as/design/a/better/rule) and _____ (enforce/gerund) it, the persistent _____ (failure) of so many reform _____ (effort) would be difficult to explain — _____ (the) _____ (very) _____ (frequency) of that _____ (failure) suggests that _____ (something) _____ _____ (else/fundamental) _____ (be) _____ (at/work).','Were reform as simple as designing a better rule / enforcing / failure / efforts / the / very / frequency / failure / suggests / something / else / fundamental / is / at work',NULL,'''Were reform as simple as designing'' + ''the very frequency of failure suggests something fundamental is at work.''','hard'),
  (cid,80,282,'gap_fill','_____ (Under no circumstances) _____ (can/the/conclusion) that _____ (good) _____ (governance) is _____ _____ (impossible) be _____ (reconcile/passive) with the _____ _____ (evidence) — _____ (on/the/contrary), the _____ _____ (evidence) _____ (suggest) that _____ (it) _____ (is) _____ (achievable), _____ (though) _____ (difficult) and _____ _____ (depend) _____ (on) _____ (condition) _____ (that) _____ (be/rare).','Under no circumstances / can the conclusion / good / governance / inherently / be reconciled / available / evidence / on the contrary / available / evidence / suggests / it / is / achievable / though / difficult / dependent / on / conditions / that / are / rare',NULL,'''Under no circumstances can...be reconciled'' (negative adverbial inversion) + ''on the contrary, evidence suggests it is achievable.''','hard'),
  (cid,80,283,'multiple_choice','Which inverted sentence MOST effectively concludes a body paragraph on governance reform?','Rarely has the field produced findings of such practical significance — and rarely has the need to translate those findings into policy-relevant guidance been more apparent.','[''The field rarely produces significant findings, and it rarely needs to translate them into policy.'',''Rarely has the field produced findings of such practical significance — and rarely has the need to translate those findings into policy-relevant guidance been more apparent.'',''Rarely produced are significant findings by the field, and rarely apparent is such a need.'',''The field has rarely produced significant findings, but the need for policy guidance is apparent.'']','Option B: elegant parallel ''rarely has...been'' inversions, formal academic register, effective as a paragraph close.','medium'),

  -- BLOCK 81: Produção avançada (8 ex)
  (cid,81,284,'production','[TOEFL Writing — 200 words] Write a concluding paragraph on what the analysis has revealed using inversion.','',NULL,'Rarely has a question of such practical importance attracted so much scholarly attention for so long with so little consensus on the most fundamental issues. Not only does the study of governance reform span multiple academic disciplines, but it also sits at the intersection of theoretical inquiry and pressing practical need in ways that make its resolution especially important. Central to the frustration that many researchers feel is the gap between the sophistication of the analytical tools available and the quality of the conclusions that those tools have been able to generate. Only by addressing the underlying methodological challenges — the difficulty of causal identification, the measurement of governance quality, and the generalization of findings across contexts — can the field hope to make the kind of progress that its practical importance demands. Had earlier generations of scholars appreciated these challenges more clearly, the field might be in a stronger position today. Under no circumstances, however, should the difficulties that remain lead to intellectual despair — so significant have the advances of the past several decades been that there is every reason for cautious optimism about the prospects for further progress. The question is not whether progress is possible, but whether the field will organize itself to pursue it with the rigor and imagination that the challenge deserves.','hard'),
  (cid,81,285,'gap_fill','[TOEFL Writing] _____ (Not only/does/this/analysis/contribute) to theoretical understanding, _____ (but/it/also/offer) practical _____ (guidance) for those _____ (charged) with _____ (design/gerund) _____ (governance) _____ (reform) _____ (in) _____ (challenging) _____ (context).','Not only does this analysis contribute / but it also offers / guidance / charged / designing / governance / reform / in / challenging / contexts',NULL,'''Not only does...contribute'' (inversion) + ''but it also offers'' (normal order).','medium'),
  (cid,81,286,'gap_fill','[TOEFL Writing] _____ (Central/to/our/argument) _____ (be) the _____ (insight) that _____ (governance) _____ (is) not a _____ (technical) _____ (problem) with a _____ (determine/adjective) _____ _____ (solution) but a _____ (continuous) _____ (practice) that _____ (require) _____ (ongoing) _____ (invest → noun).','Central to our argument / is / insight / governance / is / technical / problem / determinate / solution / continuous / practice / requires / ongoing / investment',NULL,'''Central to our argument is the insight that'' = fronted adjective phrase inversion; insight = governance as continuous practice.','hard'),
  (cid,81,287,'gap_fill','[TOEFL Writing] _____ (So/important/be/the/question) of _____ (governance) _____ _____ (reform) _____ (that) _____ (no) _____ (analysis), _____ _____ (however) _____ (thorough), _____ (can) _____ (claim) to have _____ (exhaust) _____ (it) — _____ (only) _____ (through) _____ (cumulative) _____ _____ (collaborative) _____ (research) _____ (can) _____ _____ (meaningful) _____ _____ (advance) _____ (be) _____ (make/passive).','So important is the question / governance / reform / that / no / analysis / however / thorough / can / claim / exhausted / it / only / through / cumulative / collaborative / research / can / meaningful / advances / be / made',NULL,'''So important is the question that'' + ''only through cumulative research can meaningful advances be made'' = two inversions.','hard'),
  (cid,81,288,'gap_fill','[TOEFL Writing] _____ (Had/we/begin/past) this project with a clearer understanding of the methodological challenges we would face, the _____ (design) of the study _____ (might) _____ (look) _____ (very/different) — a _____ (reflection) that _____ (itself/serve/as/a/lesson) for _____ (future) _____ _____ (research/gerund → noun).','Had we begun / design / might / have looked / very different / reflection / itself serves as a lesson / future / research',NULL,'''Had we begun'' (past perfect inversion) + ''might have looked very different'' + ''a reflection that serves as a lesson.''','hard'),
  (cid,81,289,'gap_fill','[TOEFL Writing] _____ (Under no circumstances/should) _____ (the) _____ (difficulty) of the _____ (challenge) _____ (discourage) the _____ (invest → noun) of _____ (scholarly) _____ (attention) and _____ (resource) that _____ (its) _____ (importance) _____ (warrant) — _____ (difficult) _____ _____ (question) deserve _____ (difficult) _____ _____ (answer → noun).','Under no circumstances should / the / difficulty / challenge / discourage / investment / scholarly / attention / resources / its / importance / warrants / difficult / questions / difficult / answers',NULL,'''Under no circumstances should [subject] [verb]'' = negative adverbial inversion; aphoristic closing statement.','hard'),
  (cid,81,290,'production','[TOEFL Writing — 200 words] Write a final paragraph on what future research requires using inversion.','',NULL,'Never has the need for rigorous, policy-relevant research on governance reform been more apparent — and never have the methodological tools to conduct such research been more sophisticated. Not only do we now have access to large-scale comparative datasets, but we also have theoretical frameworks capable of generating testable predictions about the conditions for reform success. Central to the agenda for future research is the challenge of causal identification: only by developing better strategies for distinguishing cause from effect can the field produce the kind of evidence that practitioners need. Were future research to address these methodological challenges systematically, the insights generated would be of considerably greater practical value than those currently available. So significant is the gap between what is currently known and what would need to be known to support confident policy prescriptions that filling it represents perhaps the most important contribution that governance scholarship could make. Under no circumstances should this ambition be set aside in the face of the technical difficulties it presents — had earlier generations of scholars been similarly deterred, the substantial progress that has been made over the past several decades would not have been achieved. The challenge is large, but rarely has it seemed more tractable.','hard'),
  (cid,81,291,'gap_fill','[TOEFL Writing] _____ (Rarely/has/a/field) _____ (offer/passive) _____ _____ _____ (such/important/practical/insight) at _____ (such) _____ (a) _____ (moment) of _____ (policy) _____ _____ (urgency) — _____ (and/rarely/has/the/obligation) to _____ (communicate) those _____ _____ (insight) _____ (clearly/adverb) and _____ (accessibly/adverb) _____ (to) _____ (practitioner) _____ _____ (been/more/apparent).','Rarely has a field / been offered / such important practical insights / such / a / moment / policy / urgency / and rarely has the obligation / communicate / insights / clearly / accessibly / to / practitioners / been more apparent',NULL,'''Rarely has...been offered'' + ''rarely has the obligation...been more apparent'' = parallel present perfect inversions.','hard'),

  -- BLOCK 82: Capstone final (9 ex)
  (cid,82,292,'production','[TOEFL Writing — 200 words] Write a conclusion using inversion as the primary stylistic device.','',NULL,'Rarely has a question of such practical importance been approached with such analytical rigor as in this paper — and rarely have the implications of that rigor been so far-reaching. Not only does the analysis contribute to theoretical understanding of what makes governance reform succeed, but it also offers practical guidance for those charged with the difficult work of translating that understanding into better policy and better institutions. Central to the paper''s conclusions is the recognition that governance reform is neither simple nor impossible — so nuanced is the actual relationship between design and outcome that neither optimism nor pessimism, unqualified, is an adequate response. Only by appreciating this nuance, and by investing in the research and practice that allows it to be translated into actionable insight, can the field make the kind of progress that its importance demands. Had this paper accomplished only one thing, the author would hope it to be this: that it has made the case, however imperfectly, for the kind of analytically rigorous, practically engaged scholarship that the governance challenge deserves. Under no circumstances should that case be considered closed — so much remains to be understood that the work, in the most important sense, is only beginning.','hard'),
  (cid,82,293,'gap_fill','[Final] _____ (Never/before/have/the/challenge) of governance been _____ (so/well/understand/passive) — _____ (and/never/before/has/the/opportunity) to act on that understanding been _____ (so/clear/adverb) _____ (present/passive).','Never before have the challenges / so well understood / and never before has the opportunity / so clearly presented',NULL,'''Never before have/has...been'' = parallel present perfect inversions; ''so well understood'' and ''so clearly presented'' = degree adverbs.','hard'),
  (cid,82,294,'gap_fill','[Final] _____ (Not only/does/this/paper/argue) that governance reform is possible, _____ (but/it/also/demonstrate) that the conditions under which it _____ (succeed) are _____ (identify/passive) _____ (with) _____ (grow/gerund → noun) _____ (precision).','Not only does this paper argue / but it also demonstrates / succeeds / identifiable / with / growing / precision',NULL,'''Not only does...argue'' (inversion) + ''but it also demonstrates'' (normal order) + ''identifiable with growing precision.''','hard'),
  (cid,82,295,'gap_fill','[Final] _____ (Central/to/what/we/have/learn) from this analysis _____ (be) the _____ (importance) of _____ (humility) — _____ (intellectual) _____ (humility) about what is _____ (known), _____ (practical) _____ (humility) about what is _____ (achievable), and _____ (institutional) _____ (humility) about the _____ (limit) of what any _____ (single) _____ (body) can _____ (accomplish/alone).','Central to what we have learned / is / importance / humility / intellectual / humility / known / practical / humility / achievable / institutional / humility / limits / single / body / accomplish alone',NULL,'''Central to what we have learned is the importance of humility'' + tricolon: intellectual, practical, institutional humility.','hard'),
  (cid,82,296,'gap_fill','[Final] _____ (So/much/remain/passive) to _____ (learn) that _____ (this) _____ (paper) _____ (can) _____ (claim) to _____ (represent) _____ (only) _____ (a) _____ (beginning) — _____ (important), _____ _____ _____ _____ (one/hope), but _____ (a/beginning/nonetheless).','So much remains / to / learn / this / paper / can / claim / represent / only / a / beginning / important / one / hopes / a beginning nonetheless',NULL,'''So much remains to learn that'' + ''a beginning — important, one hopes, but a beginning nonetheless'' = emphatic inversion closing.','hard'),
  (cid,82,297,'gap_fill','[Final] _____ (Were/the/insights/of/this/analysis/to/be/adopt/passive) by _____ (those) _____ (charge/gerund) with _____ (governance) _____ _____ (reform), the _____ (quality) of that _____ (reform) _____ _____ (would/be) meaningfully _____ (better) — _____ _____ _____ _____ (whether/that/happens/be) ultimately _____ _____ _____ (for/practitioner/to/determine).','Were the insights of this analysis to be adopted / those / charged / governance / reform / quality / reform / would be / better / whether that happens is / for practitioners to determine',NULL,'''Were...to be adopted'' (inverted second conditional) + ''would be meaningfully better'' + ''whether that happens is for practitioners to determine.''','hard'),
  (cid,82,298,'production','[TOEFL Writing — 200 words] Write a final paragraph on the relationship between research and practice using inversion.','',NULL,'Rarely has the relationship between academic research and governance practice been more important to get right — and rarely has it been more difficult. Not only does good research require investment in methodological rigor that often pushes in the direction of abstraction and specialization, but it also demands engagement with the messy reality of practice that resists the kind of simplification that theoretical modeling requires. Central to the challenge is the question of what ''usable knowledge'' looks like in the governance domain: only when research findings are presented in forms that practitioners can act on, and only when they are accompanied by honest acknowledgment of the conditions under which they apply, can they be expected to improve the quality of practice. Were the relationship between research and practice to be redesigned from scratch, it would likely look quite different from what currently exists — more collaborative in its design, more oriented toward joint production of knowledge, and more explicitly focused on the conditions under which findings can be translated across contexts. Had the field invested earlier in developing these bridging capabilities, the gap between what we know and what we do might be considerably narrower than it is today. Under no circumstances should the persistence of that gap lead to resignation — so much has been learned that there is every reason to believe the gap can be narrowed further.','hard'),
  (cid,82,299,'gap_fill','[Final] _____ (Only/by/sustaining) the investment in _____ (both) _____ (rigorous) _____ (research) and _____ _____ _____ (thoughtful/practice) _____ (can/we/hope) to _____ _____ (narrow) the _____ _____ (gap) between _____ (what) _____ (we) _____ (know) and _____ (what) _____ (we) _____ (do) — _____ _____ (and/that/hope) is _____ (the) _____ (most) _____ (honest) _____ (conclusion) _____ (this) _____ _____ (paper) _____ _____ _____ (can/offer).','Only by sustaining / both / rigorous / research / thoughtful / practice / can we hope / narrow / gap / what / we / know / what / we / do / and that hope / the / most / honest / conclusion / this / paper / can offer',NULL,'''Only by sustaining...can we hope to narrow the gap'' + ''and that hope is the most honest conclusion this paper can offer.''','hard'),
  (cid,82,300,'production','[TOEFL Writing — Final capstone] Write a 200-word paragraph on the enduring importance of the governance reform question using inversion as the culminating stylistic device.','',NULL,'Never has the question of how to build effective governance institutions been more important — and never, it might be argued, has the capacity of the scholarly community to contribute to answering it been greater. Not only do we have analytical tools of unprecedented sophistication, but we also have a body of comparative evidence that, while imperfect, provides a firmer foundation for policy-relevant conclusions than any previous generation of scholars has enjoyed. Central to what remains to be done, however, is the challenge of closing the gap between the sophistication of our analytical frameworks and the practical guidance they are able to offer — so wide is that gap, in some domains, that bridging it represents the most important single task facing the field. Only by taking that task seriously, and by investing in the research designs, institutional arrangements, and communication strategies that make its accomplishment more likely, can the field deliver on the promise that its importance seems to warrant. Were future scholarship to succeed in this, the benefits — for governance, for policy, and ultimately for the populations whose welfare depends on the quality of the institutions that govern their lives — would be profound. Under no circumstances should the difficulty of the task lead to its abandonment; rarely has an intellectual enterprise been more worth pursuing.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
