-- ============================================================
-- SEED EXT 2: Módulo 18 — Nominalization (exercícios 71-165)
-- Novos tópicos: sufixos menos comuns, cadeias de nominalização,
-- verbo+prep→noun, estilos verboso vs acadêmico, TOEFL
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'nominalization';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo nominalization não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 11: sufixos menos comuns (-al/-ure/-th/-ce)
  (cid,11,71,'gap_fill','The _____ (deny) of the allegations came as a surprise to the committee.','denial',NULL,'"Deny" → "denial" (suffix -al). → The denial of the allegations.','medium'),
  (cid,11,72,'multiple_choice','The _____ of the new policy required extensive negotiations between all stakeholders.','approval','["approve","approving","approval","approvation"]','"Approve" → "approval" (suffix -al). → The approval of the new policy.','medium'),
  (cid,11,73,'gap_fill','The _____ (propose) to restructure the department was met with resistance.','proposal',NULL,'"Propose" → "proposal" (suffix -al).','medium'),
  (cid,11,74,'gap_fill','The _____ (fail) of the treatment in Phase 2 trials led to the study being terminated.','failure',NULL,'"Fail" → "failure" (suffix -ure). → The failure of the treatment.','easy'),
  (cid,11,75,'multiple_choice','The _____ of the structure under stress testing revealed critical flaws.','fracture','["fracturing","fract","fracture","fractility"]','"Fracture" = nominalization of "fracture" (process noun). → The fracture of the structure.','hard'),
  (cid,11,76,'gap_fill','The _____ (grow) of antibiotic-resistant bacteria poses a serious threat to global health.','growth',NULL,'"Grow" → "growth" (irregular suffix -th). → The growth of antibiotic-resistant bacteria.','easy'),
  (cid,11,77,'gap_fill','The _____ (warm) of the oceans is directly linked to increased hurricane intensity.','warming',NULL,'"Warm" → "warming" (-ing as nominalization for processes, especially climate). → The warming of the oceans.','medium'),
  (cid,11,78,'multiple_choice','The _____ of the experiment was unprecedented in the field.','significance','["signify","significantly","signification","significance"]','"Significant" → "significance." → The significance of the experiment.','easy'),

  -- BLOCK 12: nominalization chains (compound nominalizations)
  (cid,12,79,'gap_fill','The _____ of the _____ of the data led to the discovery of the error. (collect + analyze)','collection / analysis',NULL,'Nominalization chain: "collecting and analyzing" → "the collection of X and the analysis of Y."','hard'),
  (cid,12,80,'multiple_choice','Which sentence uses a nominalization chain correctly?','The implementation of the policy and the monitoring of its outcomes require dedicated resources.','["Implementing the policy and monitoring outcomes requires dedicated resources (more informal but correct).","The implementation of the policy and the monitoring of its outcomes require dedicated resources.","The implement of the policy and the monitor of outcomes require resources.","The implementations of the policies and the monitoring of outcome requires resources."]','Nominalization chain: "the implementation of X and the monitoring of Y."','hard'),
  (cid,12,81,'gap_fill','The _____ of the _____ of the manuscript delayed publication significantly. (lose + find)','loss / discovery',NULL,'"Losing and finding" → "the loss of the manuscript and the discovery of it." Or: "the loss and subsequent recovery."','hard'),
  (cid,12,82,'multiple_choice','Transform: "Researchers developed the drug and then tested it in trials." → Best nominalized version?','The development of the drug and its subsequent testing in clinical trials...','["Developing the drug and testing it in trials...","The development of the drug and its subsequent testing in clinical trials...","Researchers'' developing and testing of the drug in trials...","The development of the drug and the test of it in clinical trials..."]','Two-step nominalization: development + testing.','hard'),
  (cid,12,83,'gap_fill','The _____ and _____ of renewable energy sources require significant investment. (develop + deploy)','development / deployment',NULL,'"Develop" → "development"; "deploy" → "deployment." Paired nominalization.','hard'),
  (cid,12,84,'multiple_choice','Which sentence demonstrates the MOST sophisticated nominalization for academic writing?','The rapid deterioration of infrastructure and the concurrent decline in public investment have created a crisis.','["Infrastructure is rapidly deteriorating and public investment is declining, causing a crisis.","The rapid deterioration of infrastructure and the concurrent decline in public investment have created a crisis.","Infrastructure deteriorates rapidly and public investment declines concurrently, creating a crisis.","Infrastructure has been rapidly deteriorating and public investment has been declining, creating a crisis."]','Two nominalizations with "the rapid + noun" pattern = highest academic register.','hard'),

  -- BLOCK 13: verb + preposition → nominalization
  (cid,13,85,'gap_fill','Rewrite: "They contributed to the project" → "Their _____ (contribute) to the project was invaluable."','contribution',NULL,'"Contribute to" → "contribution to" (nominalization + preposition maintained).','medium'),
  (cid,13,86,'multiple_choice','Which nominalization preserves the correct preposition?','The reliance on fossil fuels has created a global energy crisis.','["The rely on fossil fuels has created a global energy crisis.","The reliance of fossil fuels has created a global energy crisis.","The reliance on fossil fuels has created a global energy crisis.","The relying on fossil fuels has created a global energy crisis."]','"Rely on" → "reliance on" — preposition stays the same after nominalization.','hard'),
  (cid,13,87,'gap_fill','Rewrite: "The team invested in new equipment" → "The _____ (invest) in new equipment transformed their output."','investment',NULL,'"Invest in" → "investment in."','medium'),
  (cid,13,88,'multiple_choice','Which sentence correctly uses a nominalized verb+preposition?','The adherence to ethical guidelines is non-negotiable in clinical research.','["The adhere to ethical guidelines is non-negotiable.","The adherence of ethical guidelines is non-negotiable.","The adherence to ethical guidelines is non-negotiable in clinical research.","The adhering to ethical guidelines is non-negotiable."]','"Adhere to" → "adherence to."','hard'),
  (cid,13,89,'gap_fill','Rewrite: "Researchers depend on peer review" → "The _____ (depend) on peer review ensures quality control."','dependence',NULL,'"Depend on" → "dependence on."','medium'),
  (cid,13,90,'multiple_choice','Transform: "The team agreed on the methodology" → nominalized form.','The team''s agreement on the methodology facilitated efficient collaboration.','["The team''s agreeing on the methodology facilitated collaboration.","The team agreed on the methodology facilitated collaboration.","The team''s agreement on the methodology facilitated efficient collaboration.","The team''s agreeing to the methodology facilitated collaboration."]','"Agree on" → "agreement on" (possessive + nominalization + same preposition).','hard'),

  -- BLOCK 14: verboso vs acadêmico — transformação
  (cid,14,91,'multiple_choice','Which sentence is MORE appropriate for academic writing?','The establishment of a national health monitoring system has significantly improved early disease detection.','["The government established a national health monitoring system and this has improved early disease detection significantly.","The establishment of a national health monitoring system has significantly improved early disease detection.","When the government established a national health monitoring system, early disease detection improved a lot.","Early disease detection improved because the government established a health monitoring system."]','Nominalization (the establishment of) creates compact, impersonal academic prose.','hard'),
  (cid,14,92,'gap_fill','Informal: "Because the city grew so fast, services couldn''t keep up." → Academic: "The rapid _____ (grow) of the city outpaced the _____ (provide) of essential services."','growth / provision',NULL,'"The rapid growth of the city" + "the provision of services" = nominalized academic version.','hard'),
  (cid,14,93,'multiple_choice','Transform: "The fact that the policy failed surprised everyone." → Nominalized?','The failure of the policy surprised all stakeholders.','["That the policy failed surprised everyone.","The fail of the policy surprised everyone.","The failing of the policy surprised everyone.","The failure of the policy surprised all stakeholders."]','"The failure of the policy" = nominalized subject.','medium'),
  (cid,14,94,'gap_fill','Informal: "Scientists found that the drug works" → Academic: "The _____ (find) that the drug is effective has significant clinical implications."','finding',NULL,'"Finding" (nominalized reporting verb) + that-clause = academic formulation.','hard'),
  (cid,14,95,'multiple_choice','Which is the MOST formally nominalized version?','The implementation of new safety protocols resulted in a significant reduction in workplace accidents.','["They implemented new safety protocols and accidents at work reduced significantly.","Implementing new safety protocols led to fewer workplace accidents.","The implementation of new safety protocols resulted in a significant reduction in workplace accidents.","They implemented protocols, which led to accident reduction in workplaces."]','Double nominalization: "implementation" + "reduction."','hard'),

  -- BLOCK 15: TOEFL Reading
  (cid,15,96,'multiple_choice','[TOEFL Reading] "The rapid urbanization of developing economies has placed enormous pressure on infrastructure." The nominalization "urbanization" does what?','Turns the process (urbanize/cities growing) into a noun, making the sentence more compact and formal.','["Makes the sentence informal","Turns the process into an adjective","Turns the process (urbanize/cities growing) into a noun, making the sentence more compact and formal.","Is a synonym for modernization"]','"Urbanization" = nominalization of the process of urbanizing.','medium'),
  (cid,15,97,'gap_fill','[TOEFL Reading] "The _____ of the treaty was celebrated as a historic moment." Best nominalization of "sign"?','signing',NULL,'"The signing of the treaty" = nominalization of an event.','medium'),
  (cid,15,98,'multiple_choice','[TOEFL Reading] "The implementation of stricter regulations led to a marked improvement in air quality." Identify the two nominalizations.','Implementation and improvement.','["Implementation and stricter","Led and improvement","Implementation and improvement.","Stricter and quality"]','"Implementation" (implement → noun) and "improvement" (improve → noun).','medium'),
  (cid,15,99,'gap_fill','[TOEFL Reading] "The _____ of fossil fuels and their replacement with renewables is central to current climate policy." Best nominalization of "use"?','use / consumption / utilization',NULL,'"The use/consumption/utilization of fossil fuels" = nominalized academic subject.','medium'),
  (cid,15,100,'multiple_choice','[TOEFL Reading] Why do academic texts favor nominalization over verb-based sentences?','Nominalization creates more concise, impersonal, and information-dense prose suited to formal writing.','["Verbs are too simple for academic writing","Nominalization is always grammatically correct","Nominalization creates more concise, impersonal, and information-dense prose suited to formal writing.","Academic journals require only noun-based sentences"]','Nominalization = formal register, information density, objectivity.','hard'),

  -- BLOCK 16: TOEFL Speaking
  (cid,16,101,'production','[TOEFL Speaking — 45s] You have read that cities should ban cars in urban centers. Discuss using nominalizations: the reduction of, the implementation of, the improvement of, the development of.','',NULL,'The reduction of private vehicle use in urban centers could significantly improve air quality. The implementation of pedestrian zones and expanded public transport is essential for this transition. The development of cycling infrastructure would further support the reduction of emissions. The improvement of public transport systems requires substantial investment but yields long-term economic and health benefits.','hard'),
  (cid,16,102,'production','[TOEFL Speaking — 45s] Transform these informal ideas into academic language using nominalizations: "AI is growing fast. It changes how we work. We need to train workers. This is urgent."','',NULL,'The rapid growth of artificial intelligence is reshaping workplace dynamics across virtually every industry. The transformation of labor markets demands the retraining of workers on a significant scale. The urgency of this transition cannot be overstated, as the pace of technological development outpaces current educational frameworks.','hard'),

  -- BLOCK 17: TOEFL Writing
  (cid,17,103,'production','[TOEFL Writing] Rewrite this informal paragraph using nominalization for every underlined verb/adjective: "Governments have failed to act. This is serious. They must respond quickly. They need to cooperate internationally. If they don''t, the situation will get worse."','',NULL,'The failure of governments to act constitutes a serious threat to global stability. A rapid response is essential. International cooperation is required to address the challenge effectively. Without decisive action, the deterioration of the situation appears inevitable.','hard'),
  (cid,17,104,'production','[TOEFL Writing — 150 words] Write an academic paragraph on the topic of educational reform using at least 5 nominalizations. Underline each nominalization.','',NULL,'The modernization of educational systems is widely recognized as essential for economic competitiveness in the 21st century. The integration of digital technology into curricula has accelerated the development of new pedagogical approaches. However, the implementation of reforms has been uneven, with significant disparities in access between urban and rural communities. The assessment of students through standardized testing remains controversial, as critics argue that such measurement tools fail to capture the full range of student competencies. The introduction of project-based learning, inquiry-driven methodologies, and collaborative problem-solving represents a promising alternative. Ultimately, the success of any educational reform depends on the training of teachers and the provision of adequate resources. Without sustained investment, even the most innovative reforms risk failure at the point of implementation.','hard'),
  (cid,17,105,'production','[TOEFL Writing — Error Correction] Fix nominalization errors: "The grow of the economy led to the improve of living standards. The fail of the policy disappointed many. The apply of this method produced consistent results. The significance of these findings are undeniable."','',NULL,'grow → growth; improve → improvement; fail → failure; apply → application; are → is (significance = singular).','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
