-- ============================================================
-- SEED EXT 2: Módulo 10 — Modal Verbs (exercícios 71-185)
-- Novos tópicos: should/ought to, had better, need to,
-- perfect modals, modal passives, TOEFL hedging
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'modais-basicos';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo modais-basicos não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 11: should/ought to — advice and expectation
  (cid,11,71,'gap_fill','Students ___ proofread their essays before submitting. (advice)','should / ought to',NULL,'"Should" and "ought to" give advice. Both are correct here.','easy'),
  (cid,11,72,'multiple_choice','Which expresses RECOMMENDATION in academic writing?','Policymakers should consider long-term environmental impacts.','["Policymakers must consider environmental impacts (strong obligation).","Policymakers should consider long-term environmental impacts.","Policymakers can consider environmental impacts (ability/possibility).","Policymakers will consider environmental impacts (certain prediction)."]','"Should" = recommendation / expectation, not a command.','medium'),
  (cid,11,73,'gap_fill','The methodology section ___ include a clear description of the sampling technique.','should / ought to',NULL,'"Should" for expected academic writing conventions.','medium'),
  (cid,11,74,'gap_fill','By now, the committee ___ have received all applications. (expectation about past)','should',NULL,'"Should have + past participle" for expectation about a past event.','hard'),
  (cid,11,75,'multiple_choice','Which sentence correctly uses "ought to"?','Students ought to cite all sources carefully.','["Students ought cite all sources.","Students ought to cited all sources.","Students ought to cite all sources carefully.","Students ought citing all sources."]','"Ought to" + base infinitive (never past participle or -ing).','medium'),
  (cid,11,76,'gap_fill','Researchers ___ (ought to) consider ethical implications before collecting data.','ought to',NULL,'"Ought to" = should (slightly more formal/old-fashioned).','easy'),
  (cid,11,77,'multiple_choice','What is the negative of "ought to" in formal writing?','ought not to','["ought not","oughtn''t","ought to not","ought not to"]','"Ought not to" = formal negative. "Oughtn''t to" = informal.','hard'),

  -- BLOCK 12: had better — strong advice/warning
  (cid,12,78,'gap_fill','You ___ ___ ___ study more if you want to pass the TOEFL. (had better)','had better',NULL,'"Had better" = strong informal advice/warning with implied negative consequence.','medium'),
  (cid,12,79,'multiple_choice','Which sentence uses "had better" correctly?','You had better submit the application before the deadline or you will lose your place.','["You had better to submit the application.","You better had submit the application.","You had better submitting the application.","You had better submit the application before the deadline or you will lose your place."]','"Had better" + base infinitive (no "to").','medium'),
  (cid,12,80,'gap_fill','The experiment is failing — we ___ ___ ___ change our approach immediately.','had better',NULL,'"Had better" implies there will be a negative result if we don''t act.','medium'),
  (cid,12,81,'multiple_choice','What is the difference between "should" and "had better"?','Had better implies a more urgent warning with consequences; should is a milder recommendation.','["Had better is more polite than should.","Had better is used only in formal writing.","Had better implies a more urgent warning with consequences; should is a milder recommendation.","They are completely interchangeable."]','"Had better" = stronger, often with implied threat. "Should" = general advice.','hard'),
  (cid,12,82,'gap_fill','You ___ ___ ___ not ignore the feedback from your supervisors.','had better',NULL,'"Had better not" = negative of had better.','medium'),
  (cid,12,83,'multiple_choice','Which context is MOST appropriate for "had better"?','A supervisor warning a student about a late submission.','["A textbook giving general academic writing advice","A supervisor warning a student about a late submission.","A scientific paper recommending future research","A professor explaining course content"]','"Had better" = immediate warning in spoken contexts (too informal for academic papers).','hard'),

  -- BLOCK 13: need to / don't have to / needn't
  (cid,13,84,'gap_fill','You ___ (need/bring) your student ID to access the library.','need to bring',NULL,'"Need to" = it is necessary. Need to + base infinitive.','easy'),
  (cid,13,85,'multiple_choice','Which sentence means "it is NOT necessary"?','You don''t have to submit a cover letter.','["You mustn''t submit a cover letter (prohibition).","You don''t have to submit a cover letter.","You shouldn''t submit a cover letter (advice against).","You can''t submit a cover letter (inability)."]','"Don''t have to" = not obligatory, no requirement.','medium'),
  (cid,13,86,'gap_fill','She ___ ___ (not/attend) the optional seminar if she has other commitments.','doesn''t need to / doesn''t have to',NULL,'No obligation = doesn''t need to OR doesn''t have to.','medium'),
  (cid,13,87,'multiple_choice','What is the difference between "mustn''t" and "don''t have to"?','Mustn''t = prohibition; don''t have to = no obligation','["They mean the same thing.","Mustn''t = no obligation; don''t have to = prohibition.","Mustn''t = prohibition; don''t have to = no obligation","Mustn''t is informal; don''t have to is formal."]','Critical distinction: mustn''t = forbidden; don''t have to = not required.','hard'),
  (cid,13,88,'gap_fill','Researchers ___ ___ (needn''t) prove that ethics guidelines were followed if they did not use human subjects.','needn''t',NULL,'"Needn''t" = don''t need to (British English / formal).','hard'),
  (cid,13,89,'multiple_choice','Choose the sentence with the CORRECT modal for the context: "Attendees at the conference may find the reception optional."','Attendees don''t have to attend the reception.','["Attendees mustn''t attend the reception.","Attendees shouldn''t attend the reception.","Attendees don''t have to attend the reception.","Attendees can''t attend the reception."]','"Don''t have to" = the reception is optional, not mandatory.','medium'),
  (cid,13,90,'gap_fill','You ___ (must not) forget to back up your data — losing it could be catastrophic.','must not / mustn''t',NULL,'"Mustn''t" = prohibition / strong warning.','medium'),

  -- BLOCK 14: perfect modals — past deductions and criticism
  (cid,14,91,'gap_fill','The results were unexpected. The team ___ ___ ___ (must/make) a calculation error.','must have made',NULL,'"Must have + past participle" = certain deduction about the past.','hard'),
  (cid,14,92,'multiple_choice','Which sentence expresses CERTAINTY about a past event?','She must have submitted the paper — it''s no longer on the list.','["She might have submitted the paper.","She could have submitted the paper.","She must have submitted the paper — it''s no longer on the list.","She may have submitted the paper."]','"Must have" = 95%+ certain deduction from evidence.','medium'),
  (cid,14,93,'gap_fill','He ___ ___ ___ (could/choose) a better methodology — the results might have been clearer.','could have chosen',NULL,'"Could have + past participle" = unrealized past possibility.','hard'),
  (cid,14,94,'multiple_choice','Which expresses PAST REGRET or CRITICISM?','They should have consulted the data before drawing conclusions.','["They must have consulted the data.","They might have consulted the data.","They should have consulted the data before drawing conclusions.","They could have consulted the data."]','"Should have" = past criticism/regret — they didn''t do it but they should have.','hard'),
  (cid,14,95,'gap_fill','She ___ ___ ___ (might/miss) the conference — I''m not sure.','might have missed',NULL,'"Might have + past participle" = uncertain past possibility.','hard'),
  (cid,14,96,'multiple_choice','What does "The study can''t have been rigorous" mean?','I am certain the study was NOT rigorous.','["The study was definitely rigorous.","I am certain the study was NOT rigorous.","It''s possible the study was not rigorous.","The study had no rigor in the past."]','"Can''t have" = negative past deduction with high certainty.','hard'),
  (cid,14,97,'gap_fill','The error in the dataset ___ ___ ___ (should/catch) during the review process.','should have been caught',NULL,'"Should have been + past participle" = passive perfect modal (past criticism).','hard'),
  (cid,14,98,'multiple_choice','Which modal expresses the WEAKEST certainty about a past event?','might have','["must have","can''t have","should have","might have"]','"Might have" = least certain (about 30-50%); "must have" = most certain.','medium'),
  (cid,14,99,'gap_fill','The correlation ___ ___ ___ (may/affect) by uncontrolled variables.','may have been affected',NULL,'"May have been + past participle" = passive past possibility in academic hedging.','hard'),
  (cid,14,100,'multiple_choice','Choose the correct perfect modal: "The researcher ___ the lab early — the lights were on all night."','must not have left','["didn''t must have left","must not have left","mustn''t left","must have left (wrong — lights on suggests NOT left)"]','"Must not have left" = certain deduction that the person did not leave.','hard'),

  -- BLOCK 15: academic hedging with modals
  (cid,15,101,'multiple_choice','Which modal hedge is MOST appropriate in a TOEFL academic essay?','These findings may suggest a causal relationship.','["These findings will prove a causal relationship.","These findings must mean a causal relationship exists.","These findings may suggest a causal relationship.","These findings can''t show any causal relationship."]','"May suggest" = appropriate academic hedging (not over-claiming).','hard'),
  (cid,15,102,'gap_fill','Further research ___ needed to determine whether these findings are replicable.','may be / might be / would be',NULL,'Modal + be for hedged academic recommendation.','medium'),
  (cid,15,103,'multiple_choice','In academic writing, which sentence is OVER-CLAIMING?','This proves that poverty directly causes crime.','["Poverty may contribute to crime rates.","The data suggests a correlation between poverty and crime.","This proves that poverty directly causes crime.","It is possible that poverty influences criminal behavior."]','"Proves" is too strong — replace with "suggests," "indicates," or "may."','medium'),
  (cid,15,104,'gap_fill','While the evidence is compelling, we ___ consider alternative explanations before reaching a conclusion.','must / should',NULL,'"Must/should consider" = academic caution and intellectual humility.','medium'),
  (cid,15,105,'multiple_choice','Which phrase best hedges a claim in academic writing?','The results could indicate that bilingualism enhances working memory capacity.','["The results show bilingualism enhances working memory.","The results prove bilingualism improves memory.","The results could indicate that bilingualism enhances working memory capacity.","The results definitely mean bilingualism improves memory."]','"Could indicate" = hedged claim; avoids over-asserting causality.','medium'),
  (cid,15,106,'gap_fill','The data ___ suggest a correlation, but causation ___ not be inferred without further study.','may / can',NULL,'"May suggest" + "cannot be inferred" = appropriate academic hedging.','hard'),
  (cid,15,107,'multiple_choice','Which sentence uses MODAL HEDGING most effectively for a TOEFL essay conclusion?','These findings suggest that digital literacy programs could significantly reduce educational inequality.','["These findings prove digital literacy programs will eliminate educational inequality.","These findings suggest that digital literacy programs could significantly reduce educational inequality.","These findings might maybe possibly show some reduction in educational inequality.","Digital literacy programs should eliminate educational inequality completely."]','"Suggest" + "could significantly reduce" = confident but appropriately hedged.','hard'),

  -- BLOCK 16: modal meaning discrimination
  (cid,16,108,'multiple_choice','What is the difference between "can" and "may" in formal academic writing?','Can = ability or theoretical possibility; may = permission or epistemic possibility','["They are interchangeable","Can = ability or theoretical possibility; may = permission or epistemic possibility","Can is informal; may is formal","May is stronger than can"]','In academic writing: "can" for ability; "may" for permission or probability.','hard'),
  (cid,16,109,'gap_fill','The results ___ from biased sampling, which would explain the inconsistency with previous findings. (epistemic speculation)','could result / may result / might result',NULL,'Epistemic modal (could/may/might) for academic speculation about cause.','hard'),
  (cid,16,110,'multiple_choice','In the sentence "Deforestation can lead to desertification," "can" expresses:','General possibility / capacity','["Specific permission","Past ability","General possibility / capacity","Strong obligation"]','"Can" here = theoretical possibility (general truth statement).','medium'),
  (cid,16,111,'gap_fill','Students ___ use calculators during the exam. (permission given)','may / can',NULL,'"May" for formal permission; "can" is acceptable but slightly informal.','medium'),
  (cid,16,112,'multiple_choice','Which sentence uses MUST correctly for LOGICAL DEDUCTION?','The lights are on — the professor must still be in the office.','["You must submit by Friday (obligation, not deduction).","The lights are on — the professor must still be in the office.","You must have a good time (wish).","She must study harder (advice)."]','"Must" for logical deduction from evidence (not obligation).','medium'),
  (cid,16,113,'gap_fill','___ I borrow your notes? My file didn''t save. (polite formal request)','Could / May',NULL,'"Could" or "May" = polite permission requests. "Can" is acceptable but more informal.','easy'),
  (cid,16,114,'multiple_choice','Rank these from LEAST to MOST certain: "She might pass / She will pass / She should pass / She must pass."','might pass < should pass < must pass < will pass','["might pass < should pass < must pass < will pass","should pass < might pass < will pass < must pass","will pass < must pass < should pass < might pass","might pass = should pass < must pass < will pass"]','Certainty order: might (30%) < should (expectation) < must (deduction ~95%) < will (100% prediction).','hard'),

  -- BLOCK 17: TOEFL Reading — modals in academic texts
  (cid,17,115,'multiple_choice','[TOEFL Reading] "Temperature increases could destabilize marine ecosystems." The modal "could" signals:','A possibility that depends on conditions.','["A certain future event","A past ability","A possibility that depends on conditions.","A prohibition"]','"Could" = conditional possibility, not certainty.','medium'),
  (cid,17,116,'gap_fill','[TOEFL Reading] "New treatments ___ ___ tested on a larger sample before clinical approval." Best modal: ___','must be / should be',NULL,'"Must be" (strong obligation) or "should be" (recommendation) for academic policy recommendation.','medium'),
  (cid,17,117,'multiple_choice','[TOEFL Reading] "The decline in bee populations may be attributed to pesticide use." The modal "may be" indicates:','The cause is possible but not proven.','["The cause is definitively pesticide use","The cause is unknown","The cause is possible but not proven.","Pesticide use is prohibited"]','"May be attributed" = hedged causation in academic writing.','medium'),
  (cid,17,118,'gap_fill','[TOEFL Reading] "Prior to antibiotics, even minor infections ___ ___ lethal." Best modal?','could be / might be',NULL,'"Could be / might be" = past possibility (historical general truth).','medium'),
  (cid,17,119,'multiple_choice','[TOEFL Reading] "Early theories about dark matter cannot be reconciled with current observational data." The phrase "cannot be reconciled" means:','It is impossible to make the theories consistent with current observations.','["It is unnecessary to reconcile them","It is possible but difficult to reconcile them","It is impossible to make the theories consistent with current observations.","Scientists should not try to reconcile them"]','Cannot = impossible/not able to.','medium'),
  (cid,17,120,'gap_fill','[TOEFL Reading] "This finding ___ ___ ___ (must/replicate) by independent researchers before it is accepted as evidence." Fill the blank.','must be replicated',NULL,'"Must be replicated" = passive modal obligation in scientific context.','hard'),
  (cid,17,121,'multiple_choice','[TOEFL Reading] "The authors suggest the model might have overlooked key variables." This implies:','The model possibly failed to account for some important factors.','["The model definitely excluded key variables","The authors overlooked the variables","The model possibly failed to account for some important factors.","The key variables were included correctly"]','"Might have overlooked" = past uncertain possibility (perfect modal).','hard'),

  -- BLOCK 18: TOEFL Speaking/Writing production
  (cid,18,122,'production','[TOEFL Speaking — 45s] Explain what students SHOULD do to prepare for the TOEFL. Use should, ought to, must, need to, and had better in your response.','',NULL,'Students should practice all four skills daily. They ought to focus on academic vocabulary. They must familiarize themselves with the test format. Students need to develop their time management skills. They had better start preparing at least three months in advance.','medium'),
  (cid,18,123,'production','[TOEFL Speaking — 45s] A major study has revealed unexpected results that contradict previous research. Use perfect modals to speculate about what might have gone wrong in either study.','',NULL,'The original study must have used a different methodology. The sample could have been biased. Researchers might have overlooked confounding variables. The new study should have replicated the original conditions exactly. Data collection may have been affected by environmental factors.','hard'),
  (cid,18,124,'production','[TOEFL Speaking — 45s] Describe the importance of biodiversity using academic hedging modals. Avoid over-claiming. Use: may, could, might, should, can.','',NULL,'Biodiversity may play a critical role in ecosystem stability. Loss of species could trigger cascading ecological effects. Declining populations might signal broader environmental problems. Conservation efforts should prioritize the most biodiverse regions. Protecting these areas can benefit both ecosystems and local communities.','hard'),
  (cid,18,125,'production','[TOEFL Writing] Write a 5-sentence paragraph on the role of artificial intelligence in education using a different modal verb in each sentence. Include: can, should, may, must, and could.','',NULL,'AI can personalize learning pathways for individual students. Teachers should be trained to integrate AI tools effectively. However, over-reliance on AI may reduce critical thinking skills. Educational institutions must establish clear guidelines for AI use. AI could eventually transform assessment methods entirely.','hard'),
  (cid,18,126,'production','[TOEFL Writing — Error Correction] Fix all modal errors: "Students must to submit by Friday. She can speaks three languages. They should went earlier. He must has made a mistake. We don''t must attend."','',NULL,'must submit (no to); can speak (no -s); should have gone; must have made; mustn''t / don''t have to attend (must not = prohibition; don''t have to = not required).','hard'),

  -- BLOCK 19: mixed modal mastery
  (cid,19,127,'multiple_choice','Which modal + perfect combination is grammatically INCORRECT?','She must to have left early.','["She might have left early.","She should have left early.","She can''t have left early.","She must to have left early."]','Must + base verb (never "to"). Must have left = correct.','easy'),
  (cid,19,128,'gap_fill','The missing files ___ ___ ___ (could/delete) accidentally during the software update.','could have been deleted',NULL,'"Could have been + past participle" = passive perfect modal.','hard'),
  (cid,19,129,'multiple_choice','Choose the best modal for a TOEFL essay sentence that hedges a causal claim:','Increased screen time may contribute to attention difficulties in children.','["Increased screen time proves attention difficulties in children.","Increased screen time always causes attention difficulties.","Increased screen time may contribute to attention difficulties in children.","Increased screen time can''t affect attention in children."]','"May contribute" = hedged causal claim, appropriate for academic writing.','medium'),
  (cid,19,130,'gap_fill','[TOEFL Listening] The professor states: "We still don''t know exactly why some species adapt rapidly while others don''t. It ___ ___ related to genetic diversity, but further research is needed."','could be / may be',NULL,'Modal + be for academic uncertainty about cause.','medium'),
  (cid,19,131,'multiple_choice','[TOEFL] Which sentence BEST demonstrates modal hedging in a TOEFL essay conclusion?','These results suggest that increased investment in early childhood education could yield significant long-term economic benefits.','["These results prove that investment in education will fix all economic problems.","These results might perhaps possibly show something about education.","These results suggest that increased investment in early childhood education could yield significant long-term economic benefits.","We must invest in education because it will definitely solve poverty."]','"Suggest" + "could yield" = confident but appropriately hedged conclusion.','hard'),
  (cid,19,132,'production','[TOEFL Writing — Capstone] Write a 150-word paragraph arguing for stronger environmental policies. Include at least 6 different modal verbs in a variety of functions (obligation, possibility, recommendation, deduction, hedging, ability). Avoid repeating any modal.','',NULL,'Governments must take immediate action to address climate change. Although renewable energy can meet global energy needs, significant investment is required. Current policies may be insufficient to limit warming to 1.5°C. Policymakers should therefore accelerate the transition to clean energy. Historical evidence suggests that rapid industrial change could trigger economic disruption, but this need not occur if transition plans are carefully designed. The world ought to recognize that the cost of inaction will far exceed the cost of adaptation.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
