-- ============================================================
-- SEED EXT 6: Módulo 03 — Past Simple (ex 269-300) — FINAL
-- Consolidação final: PS em todos os contextos TOEFL
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'past-simple';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo past-simple não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 61: Últimos gap fills
  (cid,61,269,'gap_fill','The jury _____ (deliberate) for six days and _____ (return) a verdict of not guilty on all counts.','deliberated / returned',NULL,'PS for completed legal process.','easy'),
  (cid,61,270,'gap_fill','The negotiators _____ (work) through the night and _____ (reach) a compromise that _____ (satisfy) neither side entirely.','worked / reached / satisfied',NULL,'PS sequence for completed negotiation.','medium'),
  (cid,61,271,'gap_fill','Galileo _____ (face) the Inquisition in 1633 and _____ (force/passive) to recant his support for the Copernican heliocentric model.','faced / was forced',NULL,'PS active + passive for historical event.','medium'),
  (cid,61,272,'multiple_choice','Which sentence CORRECTLY uses past simple with a specific historical year?','The United Nations was founded in 1945 in the aftermath of World War II.','["The United Nations has been founded in 1945.","The United Nations is founded in 1945 in the aftermath of World War II.","The United Nations was founded in 1945 in the aftermath of World War II.","The United Nations had been founded in 1945 in the aftermath of World War II."]','Specific date (1945) + completed event → past simple passive.','easy'),
  (cid,61,273,'gap_fill','The authors _____ (collect) data from 15 countries, _____ (analyze) it using multivariate regression, and _____ (identify) three significant predictors.','collected / analyzed / identified',NULL,'PS sequence in methods: three completed research steps.','easy'),

  -- BLOCK 62: Production tasks finais
  (cid,62,274,'production','[TOEFL Writing — 150 words] Write a paragraph about the Civil Rights Movement in the USA. Use: PS active (×4), PS passive (×3), PP (×1), irregular verbs, time markers.','',NULL,'The American Civil Rights Movement, which gained momentum in the mid-1950s, challenged the system of racial segregation that had been enshrined in law across the American South since the late nineteenth century. In 1955, Rosa Parks refused to give up her seat on a segregated Montgomery, Alabama bus, and her arrest sparked a 381-day bus boycott that brought national attention to the movement. Martin Luther King Jr. emerged as the movement''s most visible leader; his speeches articulated the moral and constitutional case for racial equality with extraordinary eloquence. In 1964, the Civil Rights Act was signed by President Lyndon Johnson, prohibiting discrimination based on race, color, religion, sex, or national origin. The following year, the Voting Rights Act was passed, eliminating many of the legal barriers that had prevented Black Americans from exercising their constitutional right to vote.','hard'),
  (cid,62,275,'production','[TOEFL Speaking — 45s] Describe a significant historical mistake and its consequences. Use PS.','',NULL,'One of the most consequential strategic miscalculations in modern history occurred in June 1941, when Adolf Hitler launched Operation Barbarossa — the German invasion of the Soviet Union. The decision violated the non-aggression pact that Germany had signed with the Soviet Union in 1939 and opened a two-front war that many military historians consider the turning point of the Second World War. The invasion initially made rapid territorial gains, but German forces became overextended as autumn turned to winter. Soviet resistance stiffened, the logistics of supplying the advancing German army broke down, and temperatures fell to extremes for which German troops were unprepared. The failure of the Barbarossa campaign consumed resources and personnel that Germany could not replace and contributed decisively to the eventual German defeat in 1945.','hard'),

  -- BLOCK 63: Final review
  (cid,63,276,'multiple_choice','[Final Review] Which sentence uses past simple INCORRECTLY?','Darwin has proposed the theory of natural selection in 1859.','["Darwin proposed the theory of natural selection in 1859 (correct — PS with specific year).","The theory was proposed in 1859 (correct — PS passive with year).","In 1859, Darwin proposed the theory of natural selection (correct — PS with year, fronted time adverb).","Darwin has proposed the theory of natural selection in 1859."]','''Has proposed'' + specific year 1859 = error. Past simple required with dates.','easy'),
  (cid,63,277,'gap_fill','The experiment _____ (begin) with a control phase, _____ (move) through three treatment conditions, and _____ (conclude) with a follow-up assessment six months later.','began / moved / concluded',NULL,'PS sequence for completed experimental design.','easy'),
  (cid,63,278,'gap_fill','Early conservationists _____ (recognize) the threat that industrial hunting _____ (pose), but _____ (struggle) to translate their concerns into effective policy.','recognized / posed / struggled',NULL,'PS for historical challenge to conservation advocacy.','medium'),
  (cid,63,279,'production','[TOEFL Writing — 150 words] Write a body paragraph about the fall of the Berlin Wall and its political consequences. Use PS active, PS passive, irregular verbs.','',NULL,'The Berlin Wall fell on the night of 9 November 1989, when East German authorities unexpectedly announced that citizens could cross freely into West Berlin. Crowds gathered at the checkpoints, overwhelmed the border guards, and began physically dismantling the Wall with hammers and bare hands. The images were broadcast around the world and became the defining visual symbol of communism''s collapse in Central and Eastern Europe. Within a year, Germany was reunified — a process that proceeded faster than most observers had predicted. The fall of the Wall triggered a cascade of political transformations: communist regimes across Eastern Europe collapsed in quick succession, new democratic governments were elected, and former satellite states sought membership in NATO and the European Community. The Soviet Union itself dissolved in 1991, ending a geopolitical order that had structured international relations for more than four decades.','hard'),

  -- BLOCK 64: Fechamento final
  (cid,64,280,'gap_fill','The peace treaty _____ (sign/passive) in Paris in 1919 and _____ (fundamentally/redraw/passive) the political map of Europe.','was signed / fundamentally redrawn',NULL,'PS passive sequence for historical document.','medium'),
  (cid,64,281,'gap_fill','When the laboratory _____ (close) due to funding cuts, years of ongoing research _____ (immediately/halt/passive).','closed / were immediately halted',NULL,'PS sequence: cause (active) + effect (passive).','medium'),
  (cid,64,282,'multiple_choice','[Final] Which sentence BEST demonstrates appropriate use of past simple in a TOEFL academic response?','Keynes argued that government spending could offset private sector contraction and stabilize output during recessions.','["Keynes argues that government spending can offset private sector contraction.","Keynes has argued that government spending could offset private sector contraction.","Keynes argued that government spending could offset private sector contraction and stabilize output during recessions.","Keynes will argue that government spending can offset private sector contraction."]','PS for historical economist + could for past-time possibility in reported claim.','hard'),
  (cid,64,283,'production','[TOEFL Writing — 150 words] Write a body paragraph about why the Soviet Union collapsed. Use PS, PS passive, past perfect.','',NULL,'The Soviet Union''s collapse in 1991 resulted from the convergence of economic stagnation, political reform that unleashed forces beyond the leadership''s control, and the delegitimization of communist ideology across most of the world. By the mid-1980s, the Soviet economy had stagnated significantly: technological innovation had fallen behind the West, agricultural output remained chronically insufficient despite massive investment, and the arms race had consumed resources that might otherwise have raised living standards. When Mikhail Gorbachev introduced glasnost and perestroika — openness and restructuring — the political system that Soviet leaders had built began to unravel faster than anyone anticipated. Nationalist movements in the Baltic states, Ukraine, and the Caucasus intensified, and republics that had been held within the union by force declared independence in quick succession. The formal dissolution of the Soviet Union was declared on 25 December 1991.','hard'),
  (cid,64,284,'production','[TOEFL Speaking — 60s] Describe a historical scientific controversy and how it was resolved. Use PS, PP, and PS passive.','',NULL,'One of the most significant scientific controversies in modern history surrounded the reception of Alfred Wegener''s theory of continental drift, which he first proposed in 1912. Wegener argued that the continents had once formed a single landmass — Pangaea — and had subsequently drifted apart over millions of years. The evidence he cited included the complementary shapes of the African and South American coastlines and matching fossil records across continents now separated by oceans. However, his theory was rejected by the majority of the geological establishment at the time because he could not explain the mechanism by which continents moved. The theory was vindicated decades later, in the 1950s and 1960s, when oceanographic surveys revealed the process of seafloor spreading and the existence of mid-ocean ridges. This evidence confirmed that crustal plates move slowly but continuously, driven by convection currents in the mantle.','hard'),
  (cid,64,285,'production','[TOEFL Writing — 200 words] Write a paragraph about the development of antibiotics and their role in medicine. Use PS active, passive, and PP.','',NULL,'The discovery of penicillin by Alexander Fleming in 1928 ranks among the most consequential medical breakthroughs of the twentieth century. Fleming observed that a mold, Penicillium notatum, had contaminated one of his bacterial cultures and had killed the surrounding bacteria. Though he recognized the potential significance of this observation, the drug was not successfully developed for therapeutic use until Howard Florey and Ernst Chain purified penicillin in the early 1940s and demonstrated its effectiveness in treating bacterial infections. During World War II, mass production of penicillin was initiated in the United States, and the drug saved thousands of lives that would previously have been lost to wound infections. The widespread availability of antibiotics transformed medicine: diseases that had killed millions — including pneumonia, tuberculosis, and meningitis — became treatable, and routine surgical procedures that had carried a high risk of fatal infection were made far safer. Within decades of the first clinical use of antibiotics, however, resistance had already begun to emerge, a problem that has steadily worsened as antibiotics have been prescribed inappropriately in both human medicine and animal agriculture.','hard'),
  (cid,64,286,'gap_fill','The investigative committee _____ (interview) 47 witnesses, _____ (review) more than 10,000 documents, and _____ (ultimately/find) no evidence of criminal wrongdoing.','interviewed / reviewed / ultimately found',NULL,'PS sequence for formal investigation procedure.','easy'),

  -- BLOCK 65: Últimos exercícios 287-300
  (cid,65,287,'multiple_choice','[Final] In a TOEFL literature review, ''Jones (2018) found that X was associated with Y'' uses past simple because:','A specific named study from a specific year = time-anchored event.','["Always use past simple in literature reviews","The finding is outdated","A specific named study from a specific year = time-anchored event.","Past simple is more formal than present"]','Named study + year → past simple. No name/year → present simple option.','medium'),
  (cid,65,288,'gap_fill','Newton _____ (formulate) the laws of motion in the late seventeenth century, yet their applicability _____ (extend) far beyond their original context.','formulated / extends',NULL,'PS for historical formulation + PS for ongoing relevance (present general truth).','hard'),
  (cid,65,289,'production','[TOEFL Speaking — 45s] Describe an important invention and its historical context. Use PS and PS passive.','',NULL,'The printing press, invented by Johannes Gutenberg around 1440, transformed the history of human communication and knowledge. Before its invention, books were produced by hand by monks or professional scribes and were extraordinarily expensive and rare. With the printing press, texts could be reproduced at a fraction of the previous cost and time, making written knowledge accessible to a far wider audience. The Bible was among the first major texts to be printed, and within fifty years of Gutenberg''s invention, millions of books had been produced across Europe. Ideas circulated faster than ever before, and the printing press is widely credited with accelerating the Renaissance, the Reformation, and ultimately the Scientific Revolution, by enabling scholars to read and build upon each other''s work at unprecedented speed.','hard'),
  (cid,65,290,'production','[TOEFL Writing — 200 words] Write a conclusion for a TOEFL essay on ''The legacy of colonialism in developing countries.'' Use PS for historical claims, present simple for enduring effects.','',NULL,'The historical record examined in this essay demonstrates that colonialism left profound and lasting structural legacies in the countries it subjugated. Colonial powers extracted resources, suppressed local institutions, distorted agricultural systems, and drew arbitrary boundaries that continue to generate ethnic and political conflict. These were not incidental features of colonial administration; they reflect deliberate choices that served metropolitan economic and strategic interests at the expense of colonized populations. The consequences persist today: patterns of economic specialization in commodity production, fragile state institutions, and inequality in access to education and healthcare all bear the imprint of colonial arrangements that ended legally decades ago but whose structures often remain in place. Acknowledging these historical realities does not require contemporary citizens of former colonial powers to accept personal moral responsibility for the actions of their ancestors. It does require, however, that current international economic arrangements — including trade rules, debt obligations, and intellectual property regimes — be examined for the degree to which they perpetuate historical inequities under new names and new institutional forms. Genuine decolonization demands more than formal political independence; it demands a restructuring of the relationships through which global economic power operates.','hard'),
  (cid,65,291,'production','[TOEFL Writing — 200 words] Write a paragraph on the history of the internet. Use PS, PS passive, past perfect, and time markers.','',NULL,'The internet originated in the late 1960s as ARPANET, a research network funded by the US Department of Defense that connected computers at four American universities. Over the following decade, the network expanded and its underlying protocols were standardized, allowing different types of computers to communicate across networks they had not originally been designed to connect. By the early 1980s, ARPANET had split into civilian and military networks, and the civilian network continued to grow as universities and research institutions around the world joined. The critical transformation came in 1989-1991, when Tim Berners-Lee invented the World Wide Web — a system of hyperlinked documents accessible through a browser — and the first graphical browser, Mosaic, was released to the public. For the first time, ordinary people without technical expertise could access the internet easily. During the mid-1990s, commercial activity on the internet exploded, producing both a technological revolution and a speculative financial bubble that burst in 2000. The subsequent decade saw the rise of social media, smartphones, and cloud computing, each of which further transformed how people and organizations communicated and stored information.','hard'),
  (cid,65,292,'gap_fill','The administration _____ (not/respond) to the early warning signs, and by the time emergency measures _____ (introduce/passive), the crisis _____ (already/spread) beyond the capacity of local authorities to manage.','did not respond / were introduced / had already spread',NULL,'PS negative + PS passive + PP for policy failure narrative.','hard'),
  (cid,65,293,'production','[TOEFL Writing — 150 words] Write about the development of vaccines in the 20th century. Use PS, PS passive, past perfect, irregular verbs (developed/led/grew/brought/swept).','',NULL,'The twentieth century brought transformative advances in vaccine development that collectively prevented hundreds of millions of deaths. Following Louis Pasteur''s foundational work in the late nineteenth century, scientists developed vaccines against diphtheria, tetanus, and pertussis in the early 1900s, dramatically reducing child mortality in countries where they were introduced. The development of the polio vaccine by Jonas Salk in 1955 represented a particular triumph: polio had swept through populations cyclically, paralyzing thousands of children annually, and its elimination from most of the world within decades of the vaccine''s introduction demonstrated what systematic immunization programs could achieve. By the 1970s, a global vaccination campaign had eradicated smallpox entirely — the first and so far only infectious disease to have been eliminated through deliberate human intervention. This achievement led to sustained investment in vaccine research that grew over the following decades and ultimately produced the rapid COVID-19 vaccine development of 2020.','hard'),
  (cid,65,294,'multiple_choice','[Final] Which sentence uses the past simple in EXACTLY the right context for TOEFL academic writing?','The landmark study by Milgram (1963) demonstrated the extent to which ordinary people were willing to obey authority figures.','["The landmark study by Milgram (1963) demonstrates the extent to which ordinary people were willing to obey authority figures.","The landmark study by Milgram (1963) demonstrated the extent to which ordinary people were willing to obey authority figures.","The landmark study by Milgram (1963) had demonstrated the extent to which ordinary people were willing.","The landmark study by Milgram (1963) has demonstrated the extent to which ordinary people were willing."]','Specific study + date → PS (demonstrated). Reported claim with past context → PS (were willing).','hard'),
  (cid,65,295,'production','[TOEFL Speaking — 60s] Describe the historical context and consequences of the Marshall Plan. Use PS throughout.','',NULL,'At the end of the Second World War in 1945, much of Europe lay in ruins. Industrial capacity had been destroyed, agricultural systems disrupted, and millions of people displaced. The United States, whose own economy had been strengthened rather than damaged by the war, recognized that economic recovery in Western Europe was essential both for humanitarian reasons and to prevent political instability from providing an opening for communist expansion. In 1948, the US Congress approved the European Recovery Program — known as the Marshall Plan, after Secretary of State George Marshall who proposed it. Over the next four years, the United States provided approximately $13 billion in economic assistance to sixteen Western European countries. The Plan contributed significantly to economic stabilization and growth in recipient countries and helped to establish the institutional foundations of what later became the European Union. It also deepened the Cold War divide, as the Soviet Union refused to participate and pressured Eastern European countries to do the same.','hard'),
  (cid,65,296,'gap_fill','The company _____ (go) public in 2010, _____ (raise) $2.1 billion in its IPO, and _____ (subsequently/use/passive) the capital to fund an aggressive expansion strategy.','went / raised / was subsequently used',NULL,'PS sequence: irregular (went) + regular (raised) + PS passive.','medium'),
  (cid,65,297,'production','[TOEFL Writing — 200 words] Write a body paragraph on the Enlightenment as a turning point in Western thought. Use PS, past perfect, and present simple for enduring truths.','',NULL,'The Enlightenment represented a fundamental reorientation in how European intellectuals understood the relationship between reason, authority, and progress. Drawing on the scientific breakthroughs of the preceding century — Copernicus, Galileo, and Newton had demonstrated that systematic empirical inquiry could reveal the laws governing nature — Enlightenment thinkers argued that the same methods could be applied to politics, economics, and morality. The French philosophes, including Voltaire, Diderot, and Rousseau, subjected traditional religious and aristocratic authority to withering rational critique, insisting that social institutions be justified by reason and evaluated by their effects on human welfare rather than by custom or divine sanction. These ideas spread across Europe through correspondence networks, coffeehouses, salons, and the Encyclopédie — a monumental collaborative project that attempted to systematize all human knowledge. When the American and French Revolutions drew their justifications from natural rights, popular sovereignty, and rational government, they demonstrated that Enlightenment ideas could generate genuine political transformation. The Enlightenment legacy is complex and contested today, but the principles it established — that reason is the appropriate basis for evaluating claims about truth and justice — remain foundational to democratic governance.','hard'),
  (cid,65,298,'gap_fill','Participants _____ (sign) informed consent forms, _____ (complete) the baseline assessment, and _____ (randomly/assign/passive) to one of three experimental conditions.','signed / completed / were randomly assigned',NULL,'PS active pair + PS passive for ethics and methods sequence.','easy'),
  (cid,65,299,'multiple_choice','[Final Combined Review] Which paragraph correctly uses PS and PP together?','By the time the second wave of industrialization reached the United States in the 1870s, Europe had already transformed most of its major economies.','["By the time the second wave of industrialization reaches the United States, Europe had already transformed most of its economies (tense inconsistency).","By the time the second wave of industrialization reached the United States in the 1870s, Europe had already transformed most of its major economies.","By the time the second wave of industrialization had reached the United States in the 1870s, Europe had already transformed most of its economies (over-use of PP).","By the time the second wave reached the United States in the 1870s, Europe already transformed most of its economies (PP missing)."]','PS in main clause time clause + PP for prior event = correct structure.','hard'),
  (cid,65,300,'production','[TOEFL Speaking — 60s] Summarize a major development in the history of science and explain why it mattered. Use PS active, passive, and past perfect.','',NULL,'The Human Genome Project stands as one of the most ambitious collaborative scientific endeavors in history. Launched in 1990 as a joint effort between research institutions in the United States, the United Kingdom, France, Germany, Japan, and China, the project aimed to map and sequence the complete set of human genetic instructions. It was completed in 2003, two years ahead of schedule, and its results were made publicly available at no cost — a decision that researchers had insisted upon from the outset to ensure that the data could be used as freely as possible. The completion of the genome sequence transformed biology and medicine almost immediately: it revealed that humans possessed far fewer protein-coding genes than scientists had predicted, it provided a foundational resource for studying genetic diseases, and it opened the door to personalized medicine based on individual genetic profiles. In the two decades since, costs had fallen so dramatically that whole-genome sequencing was no longer confined to elite research institutions but was becoming a routine clinical tool — a transformation that the project''s founders had hoped for but could not have confidently predicted.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
