-- ============================================================
-- SEED EXT 3: Módulo 21 — Inversion (ex 106-205)
-- Novos tópicos: only then/when/by, affirmative inversion
-- (here/there/so/neither), no sooner...than/hardly...when,
-- conditional inversion (Were/Had/Should), TOEFL
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'inversion';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo inversion não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 31: only then / only when / only after / only by
  (cid,31,106,'gap_fill','Only then _____ (the researchers / realize) the full significance of their finding.','did the researchers realize',NULL,'"Only then + did + subject + base verb" = temporal inversion.','hard'),
  (cid,31,107,'multiple_choice','Which sentence correctly uses "only when" with inversion?','Only when all data had been verified did the team submit the manuscript.','["Only when all data had been verified the team submitted the manuscript.","Only when all data had been verified did the team submit the manuscript.","Only when all data had been verified, the team did submit.","Only when all data verified did the team submit."]','"Only when + past perfect clause + did + subject + base verb."','hard'),
  (cid,31,108,'gap_fill','Only after _____ (the conflict/end) _____ (the full extent of the damage/emerge).','the conflict had ended / did the full extent of the damage emerge',NULL,'"Only after + past perfect clause + did + subject + base verb."','hard'),
  (cid,31,109,'multiple_choice','Transform: "We can solve this problem only by working together." → inverted form.','Only by working together can we solve this problem.','["Only by working together we can solve this problem.","Only by working together do we solve this problem.","Only by working together can we solve this problem.","Only by working together could we have solved this problem."]','"Only by + gerund + can/could + subject + base verb."','hard'),
  (cid,31,110,'gap_fill','Only through sustained international cooperation _____ (climate change / address/passive) effectively.','can climate change be addressed',NULL,'"Only through X + can + subject + passive infinitive."','hard'),
  (cid,31,111,'multiple_choice','Which "only" inversion is INCORRECT?','Only if the hypothesis is supported only the results can be published.','["Only if the hypothesis is supported can the results be published.","Only then did the significance of the discovery become apparent.","Only by reducing emissions can we avoid the worst effects of climate change.","Only if the hypothesis is supported only the results can be published."]','Redundant "only" and missing inversion.','hard'),
  (cid,31,112,'gap_fill','Only later _____ (historians / appreciate) the full consequences of the decision.','did historians appreciate',NULL,'"Only later + did + subject + base verb."','medium'),

  -- BLOCK 32: no sooner...than / hardly/scarcely...when
  (cid,32,113,'gap_fill','No sooner _____ (the experiment / begin) _____ an anomalous reading appeared on the monitors.','had the experiment begun / than',NULL,'"No sooner had + subject + past participle + than..." = inversion for immediate sequence.','hard'),
  (cid,32,114,'multiple_choice','Which is correct? "Hardly ___ the team arrived ___ the storm began."','had / when','["did / than","was / that","had / when","were / before"]','"Hardly had + subject + past participle + when..." (not "than" with hardly).','hard'),
  (cid,32,115,'gap_fill','Scarcely _____ (she/finish) speaking _____ the audience erupted in applause.','had she finished / when',NULL,'"Scarcely had + subject + past participle + when..."','hard'),
  (cid,32,116,'multiple_choice','What do "no sooner...than," "hardly...when," and "scarcely...when" have in common?','They all express that the second event immediately followed the first, with inversion required.','["They all use past simple","They all require than","They all express that the second event immediately followed the first, with inversion required.","They all require an infinitive"]','All three = immediate sequence inversions. Past perfect + inverted structure.','hard'),
  (cid,32,117,'gap_fill','No sooner _____ (the results / publish/passive) _____ other researchers began attempting to replicate them.','had the results been published / than',NULL,'"No sooner had + subject + been + past participle + than..." (passive in first clause).','hard'),
  (cid,32,118,'multiple_choice','Find the error: "Hardly did the meeting end when the crisis emerged."','Did should be had (past perfect required with hardly).','["Hardly is wrong","When should be than","Did should be had (past perfect required with hardly).","Crisis should be plural"]','"Hardly had the meeting ended when..." — past perfect, not simple past.','hard'),

  -- BLOCK 33: affirmative inversion with here/there/so/such
  (cid,33,119,'multiple_choice','In "Here comes the judge," the inversion is:','Subject-verb inversion: verb (comes) before subject (the judge).','["Present continuous","Subject-verb inversion: verb (comes) before subject (the judge).","Passive construction","Conditional"]','"Here + verb + subject" = affirmative inversion with place adverb.','medium'),
  (cid,33,120,'gap_fill','Here _____ (lie) the fundamental contradiction at the heart of the theory.','lies',NULL,'"Here + verb + subject (singular)" = affirmative inversion.','medium'),
  (cid,33,121,'multiple_choice','Which sentence uses affirmative inversion correctly?','There goes the last chance to resolve the dispute peacefully.','["There goes the last chance to resolve the dispute peacefully.","There the last chance goes to resolve the dispute.","There going is the last chance to resolve the dispute.","There went the last chance to resolve the dispute (past — also correct)."]','"There + verb + subject" = affirmative inversion after "there" as a place/direction adverb.','medium'),
  (cid,33,122,'gap_fill','So _____ (thorough) was the review process _____ it took eighteen months to complete.','thorough / that',NULL,'"So + adjective + was + subject + that" = emphatic affirmative inversion.','medium'),
  (cid,33,123,'multiple_choice','In "So concerned was the team that they ran three additional experiments," what does the inversion emphasize?','The extreme degree of the team''s concern.','["A conditional situation","The past tense","The extreme degree of the team''s concern.","A contrast"]','"So + adjective + was" = emphatic inversion fronting an adjective.','easy'),
  (cid,33,124,'gap_fill','Such _____ (be) the complexity of the problem _____ no single discipline could address it alone.','was / that',NULL,'"Such was + the + noun phrase + that..." = inversion with noun.','hard'),

  -- BLOCK 34: conditional inversion (Were / Had / Should)
  (cid,34,125,'gap_fill','_____ (Were) the government to introduce a carbon tax, emissions would likely fall significantly.','Were',NULL,'"Were + subject + to + base verb" = formal conditional inversion (Type 2).','hard'),
  (cid,34,126,'multiple_choice','Which is the FORMAL INVERTED version of "If I had known about the opportunity, I would have applied"?','Had I known about the opportunity, I would have applied.','["If I would have known about the opportunity, I would have applied.","Had I known about the opportunity, I would have applied.","Were I to have known about the opportunity, I would have applied.","Should I have known about the opportunity, I would have applied."]','"Had + subject + past participle + ..." = inverted Type 3 conditional.','hard'),
  (cid,34,127,'gap_fill','Should any participant experience adverse effects, they _____ (should/instruct) to contact the research team immediately.','should be instructed / are instructed',NULL,'"Should + subject + base verb, + result clause" = formal conditional inversion (Type 1 formal).','hard'),
  (cid,34,128,'multiple_choice','What is the difference between "If I were you" and "Were I you"?','Both are Type 2 conditionals; "Were I you" is more formal (inverted).','["Were I you is incorrect","If I were you is incorrect","Both are Type 2 conditionals; ''Were I you'' is more formal (inverted).","Were I you is past tense only"]','"Were I you" = formal/literary inversion of the same conditional.','hard'),
  (cid,34,129,'gap_fill','_____ (Had) the safety checks been completed on time, the accident would never have occurred.','Had',NULL,'"Had + subject + past participle + ..." = inverted Type 3 conditional.','hard'),
  (cid,34,130,'multiple_choice','Which conditional inversion is grammatically INCORRECT?','Were I to know the answer, I would have told you.','["Were I to know the answer, I would tell you (Type 2 — correct).","Had I known the answer, I would have told you (Type 3 — correct).","Should you require assistance, please contact the desk (Type 1 formal — correct).","Were I to know the answer, I would have told you."]','"Were I to know + would have told" = mixed Type 2/3. Cannot mix.','hard'),

  -- BLOCK 35: agreement inversions (so do I / neither did she)
  (cid,35,131,'gap_fill','She finds the research compelling, and _____ (so/do I/same verb).','so do I',NULL,'"So + auxiliary + subject" = agreement inversion for positive statements.','easy'),
  (cid,35,132,'multiple_choice','Which agreement inversion is correct?','The first experiment failed, and so did the second.','["The first experiment failed, and so the second did.","The first experiment failed, and so did the second.","The first experiment failed, and so the second failed.","The first experiment failed, and so did it."]','"So + did + subject" — the auxiliary matches the tense of the original verb.','medium'),
  (cid,35,133,'gap_fill','The senior researcher was skeptical about the methodology, and _____ (neither/junior team members).','neither were the junior team members',NULL,'"Neither + were + subject" = negative agreement inversion.','medium'),
  (cid,35,134,'multiple_choice','Complete: "She has never studied abroad, and ___ her supervisor."','neither has','["so has","neither have","neither has","so have"]','"Neither has + subject" (present perfect agreement inversion for negative).','medium'),
  (cid,35,135,'gap_fill','The results exceeded expectations, and _____ (so/did/the follow-up study).','so did the follow-up study',NULL,'"So + did + subject" — agree with positive past statement.','easy'),

  -- BLOCK 36: TOEFL Reading
  (cid,36,136,'multiple_choice','[TOEFL Reading] "No sooner had the volcano erupted than scientists from around the world converged on the site." This tells us:','Scientists arrived immediately after — or even as — the eruption occurred.','["Scientists arrived before the eruption","Scientists were already on site","Scientists arrived immediately after — or even as — the eruption occurred.","Scientists caused the eruption"]','"No sooner had...than" = the second event followed almost instantly.','easy'),
  (cid,36,137,'gap_fill','[TOEFL Reading] "Only by developing more efficient solar panels _____ (humanity / hope) to meet its energy needs sustainably." Best inverted form?','can humanity hope',NULL,'"Only by + gerund + can + subject + base verb."','hard'),
  (cid,36,138,'multiple_choice','[TOEFL Reading] "Were stricter financial regulations to be introduced, the risk of another banking collapse would be significantly reduced." This is:','A formal Type 2 conditional with inverted "were."','["A passive construction","A formal Type 2 conditional with inverted ''were.''","A Type 3 conditional","An affirmative inversion"]','"Were + subject + to + passive infinitive" = formal inverted Type 2 conditional.','hard'),
  (cid,36,139,'gap_fill','[TOEFL Reading] "Hardly _____ (a decade / pass) since the discovery _____ (when) researchers began challenging its conclusions." Best form?','had a decade passed / when',NULL,'"Hardly had + subject + past participle + when..."','hard'),
  (cid,36,140,'multiple_choice','[TOEFL Reading] "Such was the scale of the humanitarian crisis that the UN Security Council convened an emergency session." The "such was" construction emphasizes:','The extraordinary magnitude of the crisis.','["A contrast with a previous situation","The ordinary nature of the crisis","The extraordinary magnitude of the crisis.","A conditional outcome"]','"Such was + noun phrase" = emphatic inversion on the degree/magnitude.','medium'),

  -- BLOCK 37: TOEFL Speaking
  (cid,37,141,'production','[TOEFL Speaking — 45s] Discuss the long-term effects of deforestation. Use 3 different inversion types: negative adverbial (rarely/never), no sooner...than, and only + inversion.','',NULL,'Rarely have ecosystems been degraded as rapidly as the Amazon rainforest has been over the past half-century. No sooner had loggers cleared one section than communities downstream began experiencing flooding and drought cycles previously unknown to the region. Only by restoring large tracts of primary forest can we hope to reverse the cascading effects on biodiversity, water cycles, and global carbon sinks. The urgency of this challenge demands immediate policy action.','hard'),
  (cid,37,142,'production','[TOEFL Speaking — 45s] A reading argues that artificial intelligence poses an existential risk to humanity. Agree or disagree. Use: were + to, had + past perfect, should, so + adj + was.','',NULL,'Were AI systems to be developed without adequate safety constraints, the consequences for humanity could be severe. Had early computing pioneers foreseen the scale of today''s AI capabilities, they might have advocated for regulatory frameworks much sooner. Should governments fail to act in the near term, the window for meaningful oversight may close. So profound is the potential impact of this technology that it warrants the most serious international deliberation.','hard'),

  -- BLOCK 38: TOEFL Writing
  (cid,38,143,'production','[TOEFL Writing] Rewrite each sentence using an inversion: (1) "Scientists rarely observe such a clear correlation." (2) "I would have chosen a different methodology if I had known about this data." (3) "We can only understand the full implications by examining long-term data." (4) "The results were so surprising that the team ran three verification experiments."','',NULL,'(1) Rarely do scientists observe such a clear correlation. (2) Had I known about this data, I would have chosen a different methodology. (3) Only by examining long-term data can we understand the full implications. (4) So surprising were the results that the team ran three verification experiments.','hard'),
  (cid,38,144,'production','[TOEFL Writing — 150 words] Write an academic paragraph on "The role of international cooperation in addressing climate change" using at least 4 inversions: no sooner...than, only when/by, were + to, so + adjective + was/is.','',NULL,'No sooner had the scientific consensus on anthropogenic climate change been established than governments began engaging in formal diplomatic negotiations. Only when the evidence of rising temperatures became undeniable did many national governments commit to reducing emissions. Only by coordinating policy across borders can humanity hope to achieve the scale of transformation required. Were major emitters to fail in meeting their Paris Agreement commitments, the consequences for vulnerable low-lying nations would be catastrophic. So severe are the projected impacts of a 2°C warming scenario that many climatologists now argue only an immediate and unprecedented level of international cooperation can prevent the worst outcomes. The urgency of the challenge demands not merely rhetoric but binding, enforceable commitments backed by real financial and technological transfers from wealthy to developing nations.','hard'),
  (cid,38,145,'production','[TOEFL Writing — Error Correction] Fix inversion errors: "No sooner the experiment had begun than unexpected results appeared. Only when did the crisis emerge did we act. So profound the impact was that it changed everything. Were I known about the opportunity, I would have applied."','',NULL,'No sooner had the experiment begun than... (had + subject + past participle); Only when the crisis emerged did we act (no "did" inside the when-clause); So profound was the impact that... (was after adjective); Were I to have known / Had I known about the opportunity, I would have applied (were + to + base verb / had + past participle).','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
