-- ============================================================
-- SEED EXT 3: Módulo 16 — Advanced Articles (ex 111-210)
-- Novos tópicos: artigos com medidas/quantidades, genericidade
-- (a/the/zero article com espécies/conceitos), erros comuns
-- avançados, TOEFL integrado
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'articles-advanced';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo articles-advanced não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 31: artigos com expressões de quantidade e medida
  (cid,31,111,'gap_fill','She earns _____ thousand dollars a month working as a consultant.','a / several',NULL,'"A thousand" (one thousand) OR "several thousand" — "a" = one in expressions of measurement.','medium'),
  (cid,31,112,'multiple_choice','Which sentence uses "a" correctly in a measurement expression?','She was offered a salary of $80,000 a year.','["She was offered a salary of $80,000 the year.","She was offered a salary of $80,000 per year (also correct).","She was offered a salary of $80,000 a year.","She was offered a salary of $80,000 one year."]','"A year" in distributive expressions (per year = a year). "A" = distributive article.','medium'),
  (cid,31,113,'gap_fill','The speed of light is approximately 300,000 kilometers _____ second.','a / per',NULL,'"Per second" OR "a second" — both correct. "A" is the distributive article.','medium'),
  (cid,31,114,'multiple_choice','Which sentence uses "the" with a quantity expression correctly?','The higher the stakes, the greater the pressure to perform.','["Higher the stakes, greater the pressure to perform.","The higher stakes, the greater pressure to perform.","The higher the stakes, the greater the pressure to perform.","Higher stakes mean greater pressure (correct but different structure)."]','"The + comparative, the + comparative" = fixed correlative structure. Both "the"s required.','hard'),
  (cid,31,115,'gap_fill','_____ more data the researchers collected, _____ clearer the pattern became.','The / the',NULL,'"The + comparative + subject + verb, the + comparative + subject + verb."','medium'),

  -- BLOCK 32: genericidade — a/the/zero article com espécies e conceitos
  (cid,32,116,'multiple_choice','Which sentence uses articles correctly to express a GENERIC statement?','The lion is the most iconic symbol of courage in Western heraldry.','["A lion is the most iconic symbol (first mention — acceptable but less generic).","Lions are the most iconic symbol of courage in Western heraldry (plural zero article — also correct).","The lion is the most iconic symbol of courage in Western heraldry.","Lion is the most iconic symbol of courage in Western heraldry (wrong — needs article)."]','Three generic forms: A lion (singular indefinite), Lions (plural zero), The lion (singular definite generic). All valid.','hard'),
  (cid,32,117,'gap_fill','_____ whale is the largest mammal on Earth. (generic singular — species)','The',NULL,'"The + singular noun" = generic species reference. Common in scientific writing.','easy'),
  (cid,32,118,'multiple_choice','Which sentence is WRONG when making a generic claim?','A dogs make loyal companions.','["Dogs make loyal companions (zero article — plural generic — correct).","A dog makes a loyal companion (indefinite singular generic — correct).","The dog has been a human companion for thousands of years (definite generic — correct).","A dogs make loyal companions."]','"A dogs" = impossible. "A" = only with singular countable nouns.','easy'),
  (cid,32,119,'gap_fill','_____ knowledge is power. (abstract concept — general truth)','Ø (no article)',NULL,'Abstract nouns used as general truths take no article: Knowledge, Justice, Love, Freedom.','easy'),
  (cid,32,120,'multiple_choice','When does "the" appear before an abstract noun?','When the abstract noun is modified by a defining phrase or clause.','["Always","Never","When the abstract noun is modified by a defining phrase or clause.","Only with uncountable nouns"]','"The knowledge gained in this study..." — modifier makes it specific.','hard'),
  (cid,32,121,'gap_fill','_____ happiness that comes from meaningful work is more enduring than that from material possessions. (specific type, defined by the clause)','The',NULL,'"The happiness that comes from X" — relative clause defines/specifies → "the."','hard'),

  -- BLOCK 33: artigos com doenças, partes do corpo, e instituições
  (cid,33,122,'multiple_choice','Which sentence uses the correct article with a disease name?','She was diagnosed with cancer last year.','["She was diagnosed with a cancer last year.","She was diagnosed with the cancer last year.","She was diagnosed with cancer last year.","She was diagnosed with cancers last year."]','Disease names (cancer, diabetes, malaria, tuberculosis) = no article in general use.','medium'),
  (cid,33,123,'gap_fill','She broke _____ arm in two places. (specific body part — her arm)','her / an',NULL,'"She broke her arm" = possessive more natural. "She broke an arm" = less specific — both usable.','medium'),
  (cid,33,124,'multiple_choice','Which article use is CORRECT with a body part?','He was shot in the shoulder by a stray bullet.','["He was shot in a shoulder by a stray bullet.","He was shot in shoulder by a stray bullet.","He was shot in his shoulder by a stray bullet (also correct — possessive).","He was shot in the shoulder by a stray bullet."]','"In the shoulder" = definite article with body parts after passive verbs of injury.','medium'),
  (cid,33,125,'gap_fill','She plays _____ violin in a professional orchestra.','the',NULL,'Musical instruments: "the violin, the piano, the flute" — always "the" when playing an instrument.','easy'),
  (cid,33,126,'multiple_choice','Which sentence about an institution uses the article correctly?','He went to church every Sunday as a child. (attendance for worship)','["He went to the church to talk to the priest. (a specific building — correct).","He went to church every Sunday as a child. (attendance for worship — correct).","He went to a church every Sunday. (first mention — less idiomatic for habitual worship).","All of the above are correct in different contexts."]','All three are potentially correct depending on context: "church" (institution) vs "the church" (specific building).','hard'),

  -- BLOCK 34: erros comuns avançados com artigos
  (cid,34,127,'multiple_choice','Identify the article error: "She is the best student in a class."','The best + in the class (not "a class" when referring to a specific group).','["She is the best (correct superlative)","Student is singular (correct)","The best + in the class (not ''a class'' when referring to a specific group).","No error"]','"In the class" — specific class already identified. Not "a class."','hard'),
  (cid,34,128,'gap_fill','He is regarded as _____ authority on medieval European trade routes.','an',NULL,'"An authority on X" = one of several possible experts. Indefinite article for classification.','medium'),
  (cid,34,129,'multiple_choice','Which sentence is CORRECT?','She was appointed head of department without any prior management experience.','["She was appointed the head of department without any prior management experience (article optional in titles — both correct).","She was appointed a head of department without any prior management experience.","She was appointed head of department without any prior management experience.","Both A and C are correct."]','Unique positions/titles: "appointed head of department" (no article) OR "the head" (specific). Both common.','hard'),
  (cid,34,130,'gap_fill','The discovery of _____ penicillin changed _____ course of modern medicine.','Ø (no article) / the',NULL,'"Discovery of penicillin" — substance name (no article). "The course of" — specific defined path.','hard'),
  (cid,34,131,'multiple_choice','Which is INCORRECT? "He was elected ___ president."','He was elected a president (wrong — unique roles don''t take "a").','["He was elected president (no article — most common for unique roles).","He was elected the president of Brazil (specific country — correct).","He was elected a president (wrong — unique roles don''t take ''a'').","He will become president next year (no article — common)."]','Unique positions (president, CEO, director) = no article OR "the + of phrase." Never "a."','hard'),

  -- BLOCK 35: TOEFL Reading
  (cid,35,132,'multiple_choice','[TOEFL Reading] "The invention of the printing press transformed the spread of knowledge." Why does "the spread of knowledge" use "the"?','The spread is specific — defined by the preceding invention and context.','["Spread is always definite","The spread of knowledge is uncountable","The spread is specific — defined by the preceding invention and context.","Knowledge takes the because it is abstract"]','"The spread of knowledge" — defined by the prepositional phrase.','medium'),
  (cid,35,133,'gap_fill','[TOEFL Reading] "_____ coral reef is one of the most biodiverse ecosystems on Earth." Best generic article?','The / A',NULL,'"The coral reef" = generic definite singular (species). "A coral reef" = indefinite generic. Both valid.','medium'),
  (cid,35,134,'multiple_choice','[TOEFL Reading] "Researchers have long studied _____ effects of poverty on child development." Best article?','the','["a","no article","the","an"]','"The effects of poverty on child development" — specific effects being studied (defined by phrase).','medium'),
  (cid,35,135,'gap_fill','[TOEFL Reading] "_____ sun''s gravitational pull keeps _____ planets in their orbits." Best articles?','The / the',NULL,'Unique physical entities: "the sun" (one in our solar system). "The planets" = specific planets in our solar system.','easy'),
  (cid,35,136,'multiple_choice','[TOEFL Reading] "A study published in Nature found that climate change may accelerate _____ spread of vector-borne diseases." Best article?','the','["a","Ø (no article)","the","an"]','"The spread of vector-borne diseases" — specific process being studied (defined by prepositional phrase).','medium'),

  -- BLOCK 36: TOEFL Speaking
  (cid,36,137,'production','[TOEFL Speaking — 45s] Discuss the role of education in reducing inequality. Use articles correctly: Ø for abstract concepts (education, poverty, inequality), the for specific references, a/an for first mentions.','',NULL,'Education is widely recognized as one of the most powerful tools for reducing poverty and addressing structural inequality. A child who receives high-quality early education is significantly more likely to achieve economic mobility as an adult. The evidence for this relationship is compelling: countries with strong public education systems tend to demonstrate lower levels of income inequality. However, the quality of education available varies enormously between wealthy and disadvantaged communities, which undermines the very mechanism through which education is supposed to promote equality.','hard'),
  (cid,36,138,'production','[TOEFL Speaking — 45s] Describe a scientific discovery that changed medicine. Use: the discovery of + substance name (no article), an (first mention), the (second mention), the (definite generic), Ø (disease name).','',NULL,'The discovery of penicillin by Alexander Fleming in 1928 is widely regarded as one of the most important events in the history of medicine. A chance observation in his laboratory led to the realization that a mold could kill bacteria. The substance — later refined and mass-produced — transformed the treatment of bacterial infections. Before its discovery, tuberculosis, pneumonia, and sepsis were major causes of death. The antibiotic revolutionized surgery by making post-operative infection far less likely.','hard'),

  -- BLOCK 37: TOEFL Writing
  (cid,37,139,'production','[TOEFL Writing — 150 words] Write an academic paragraph about artificial intelligence using at least 6 distinct article uses: Ø (concept), the (specific/defined), a/an (first mention), the (second mention), the (generic singular), the (superlative). Label each.','',NULL,'Artificial intelligence [Ø — concept] is reshaping virtually every sector of the global economy. A growing number [a — quantity first mention] of companies are integrating AI into their operations, and the benefits [the — second mention of the subject, now defined] are increasingly well-documented. The algorithm [the generic — type of technology] at the heart of most modern AI systems is trained on vast datasets and refined through feedback loops. In healthcare, an AI system [a — first mention] was recently shown to outperform the most experienced [the + superlative] radiologists in detecting early-stage lung cancer. The system [the — second mention] achieved this using a convolutional neural network. Intelligence [Ø — abstract] in machines remains qualitatively different from human cognition, but the implications [the — specific, defined by context] for labor markets and education are profound.','hard'),
  (cid,37,140,'production','[TOEFL Writing — Error Correction] Fix article errors: "The knowledge is power. She plays a piano beautifully. He was elected a president of the company. A lion is king of the jungles. A poverty is widespread in developing nations."','',NULL,'The knowledge → Knowledge (abstract general); a piano → the piano (instrument); a president → president OR the president of the company (unique role); the jungles → the jungle (specific habitat, or ''the savannah'' — lions live in savannah, not jungle); A poverty → Poverty (abstract concept, no article).','hard'),
  (cid,37,141,'production','[TOEFL Writing — 200 words] Write a full academic paragraph on "The relationship between technology and employment." Focus on correct article use throughout. At minimum, use: Ø (abstract noun in general claim), a/an (indefinite first mention), the (second mention), the + of phrase (specific relationship), the + superlative, Ø (uncountable/abstract in general), the + relative clause (specific).','',NULL,'Technology has always [Ø] shaped the nature of work, but the pace of change in the current era is unprecedented. A new wave [a — first mention] of automation, driven by advances in machine learning and robotics, is displacing workers across manufacturing and service sectors simultaneously. The displacement [the — second mention] is not, however, uniformly negative: new technologies also create jobs, particularly in sectors that require human creativity and social intelligence. The relationship between technology and employment [the + of phrase] is therefore complex and context-dependent. The most vulnerable [the + superlative] workers are those in routine, codifiable roles who lack the transferable skills needed to adapt. Research [Ø — uncountable abstract] consistently shows that investment in education and retraining significantly improves outcomes for displaced workers. The evidence [the + relative clause: that investment improves outcomes] is sufficiently strong to justify substantial public expenditure on workforce development programs, particularly in regions where automation is advancing most rapidly.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
