-- ============================================================
-- SEED: Módulo 14 — Passive Voice (B1)
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'passive-voice';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo passive-voice não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 1: present simple passive (is/are + past participle)
  (cid,1,1,'gap_fill','The results ___ (publish) in a peer-reviewed journal every year.','are published',NULL,'Present simple passive: are + past participle.','easy'),
  (cid,1,2,'gap_fill','This theory ___ (teach) in introductory linguistics courses worldwide.','is taught',NULL,'Present simple passive: is + past participle (singular subject).','easy'),
  (cid,1,3,'multiple_choice','Choose the correct passive form: "New discoveries ___ every day by scientists around the world."','are made','["is made","are making","are made","make"]','Plural subject (discoveries) → are + past participle.','easy'),
  (cid,1,4,'gap_fill','The laboratory ___ (use) for both undergraduate teaching and doctoral research.','is used',NULL,'Is + past participle for present passive.','easy'),
  (cid,1,5,'gap_fill','Thousands of academic papers ___ (submit) to this journal each year.','are submitted',NULL,'Are + past participle for plural subject.','easy'),
  (cid,1,6,'multiple_choice','Which sentence is in the passive voice?','The data is analyzed using statistical software.','["Researchers analyze the data using statistical software (active).","The data is analyzed using statistical software.","Statistical software analyzes the data (active).","They analyze data with software (active)."]','Is + analyzed (past participle) = present passive.','easy'),
  (cid,1,7,'gap_fill','English ___ (speak) as an official language in over 50 countries.','is spoken',NULL,'Is + spoken (irregular past participle of speak).','easy'),

  -- BLOCK 2: past simple passive (was/were + past participle)
  (cid,2,8,'gap_fill','The Eiffel Tower ___ (build) between 1887 and 1889.','was built',NULL,'Past simple passive: was + past participle.','easy'),
  (cid,2,9,'gap_fill','The participants ___ (inform) about the study''s purpose before signing consent forms.','were informed',NULL,'Past simple passive: were + past participle (plural subject).','easy'),
  (cid,2,10,'multiple_choice','Choose the correct passive: "The samples ___ in a controlled environment last week."','were collected','["was collected","are collected","were collected","collected"]','Were + past participle for past simple passive (plural subject).','easy'),
  (cid,2,11,'gap_fill','DNA ___ (discover) to have a double-helix structure in 1953.','was discovered',NULL,'Was + past participle for past simple passive.','medium'),
  (cid,2,12,'multiple_choice','Which sentence is in the Past Simple Passive?','The hypothesis was tested using multiple methods.','["Researchers tested the hypothesis using multiple methods (active).","The hypothesis was testing using multiple methods (wrong form).","The hypothesis was tested using multiple methods.","The hypothesis is tested using multiple methods (present passive)."]','Was + tested (past participle) = past simple passive.','easy'),
  (cid,2,13,'gap_fill','Several important documents ___ (lose) during the fire at the archives.','were lost',NULL,'Were + past participle for past simple passive (plural).','medium'),
  (cid,2,14,'gap_fill','The theory ___ (first/propose) by Copernicus in the 16th century.','was first proposed',NULL,'Was + first + past participle for initial occurrence in history.','medium'),

  -- BLOCK 3: present perfect passive (has/have been + past participle)
  (cid,3,15,'gap_fill','The results ___ (already/review) by two independent experts.','have already been reviewed',NULL,'Present perfect passive: have + been + past participle.','medium'),
  (cid,3,16,'multiple_choice','Choose the correct form: "A new species ___ in the Amazon rainforest."','has been discovered','["was discovered (past simple — no connection to present)","has been discovered","is discovered (present simple)","is being discovered (in progress)"]','Present perfect passive: has been + past participle for recent discovery.','medium'),
  (cid,3,17,'gap_fill','The policies ___ (not/implement) yet despite strong evidence for their effectiveness.','have not been implemented',NULL,'Negative present perfect passive: have + not + been + past participle + yet.','medium'),
  (cid,3,18,'multiple_choice','Which sentence uses present perfect passive correctly?','Significant advances in cancer treatment have been made in the past decade.','["Significant advances in cancer treatment were made in the past decade (past simple — also OK with specific time).","Significant advances in cancer treatment have been made in the past decade.","Significant advances in cancer treatment have been making in the past decade.","Significant advances in cancer treatment has been made in the past decade."]','Have + been + made (past participle) with plural subject.','medium'),
  (cid,3,19,'gap_fill','The building ___ (renovate) three times since it was first constructed.','has been renovated',NULL,'Has + been + past participle for singular subject.','medium'),
  (cid,3,20,'multiple_choice','Convert to passive: "Scientists have proven that diet affects mental health."','It has been proven by scientists that diet affects mental health.','["It was proven by scientists that diet affects mental health (past simple passive).","It has been proven by scientists that diet affects mental health.","It has proven that diet affects mental health (missing ''been'').","Scientists have proven it that diet affects mental health (not passive)."]','Has + been + proven (past participle) in present perfect passive.','hard'),
  (cid,3,21,'gap_fill','The research ___ (conduct) ethically and all participants ___ (treat) with respect.','has been conducted / have been treated',NULL,'Two present perfect passive constructions in academic context.','hard'),

  -- BLOCK 4: future passive (will be + past participle)
  (cid,4,22,'gap_fill','The findings ___ (announce) at the international conference next month.','will be announced',NULL,'Future passive: will + be + past participle.','medium'),
  (cid,4,23,'multiple_choice','Choose the correct future passive: "All applications ___ reviewed before the deadline."','will be reviewed','["will be reviewed","are reviewed","were reviewed","will reviewed"]','Will + be + past participle = future passive.','medium'),
  (cid,4,24,'gap_fill','The new policy ___ (implement) across all departments next semester.','will be implemented',NULL,'Will + be + past participle for planned future passive.','medium'),
  (cid,4,25,'multiple_choice','Which sentence correctly uses future passive in an academic context?','The results will be published in the next edition of the journal.','["The results will published in the next edition (missing ''be'').","The results are published in the next edition (present passive).","The results will be published in the next edition of the journal.","The results would be published in the next edition (conditional, not future)."]','Will be + past participle for future passive.','medium'),
  (cid,4,26,'gap_fill','Candidates ___ (notify) of the selection decision within two weeks.','will be notified',NULL,'Will + be + past participle (irregular: notify → notified).','medium'),
  (cid,4,27,'multiple_choice','Convert to future passive: "The committee will review all proposals."','All proposals will be reviewed by the committee.','["All proposals will reviewed by the committee.","All proposals are reviewed by the committee.","All proposals will be reviewed by the committee.","The committee will be reviewed all proposals."]','Will + be + past participle. Agent introduced with "by."','medium'),
  (cid,4,28,'gap_fill','The new lab ___ (open) by the university president at a ceremony next Friday.','will be opened',NULL,'Will + be + past participle for future event + by-agent.','medium'),

  -- BLOCK 5: by-agent in passive sentences
  (cid,5,29,'gap_fill','The theory of evolution ___ (develop) ___ Charles Darwin.','was developed / by',NULL,'Was + past participle + by + agent.','easy'),
  (cid,5,30,'multiple_choice','When should the "by-agent" be included in a passive sentence?','When the agent is important, unknown, or adds new information.','["Always","Never","When the agent is important, unknown, or adds new information.","Only with past tense passive"]','The "by + agent" phrase is optional — include it when it adds meaningful information.','hard'),
  (cid,5,31,'gap_fill','The vaccine ___ (administer) to over a million people ___ health workers.','was administered / by',NULL,'Was + past participle + by + agent phrase.','medium'),
  (cid,5,32,'multiple_choice','Which passive sentence should NOT include a by-agent?','English is spoken in many countries. (agent = people in general)','["The paper was written by Professor Chen (specific, important agent).","The award was presented by the chancellor (adds relevant information).","English is spoken in many countries. (agent = people in general)","The discovery was made by a team of researchers (specific credit)."]','Omit "by + agent" when the agent is obvious, unknown, or unimportant.','hard'),
  (cid,5,33,'gap_fill','The Nobel Prize in Physics was awarded ___ the Royal Swedish Academy of Sciences.','by',NULL,'"By" introduces the agent performing the action in passive voice.','easy'),
  (cid,5,34,'multiple_choice','Choose the sentence where omitting "by + agent" is most appropriate.','Mistakes were made in the initial calculations.','["The article was written by Professor Smith (specific credit — include).","The building was designed by Zaha Hadid (famous architect — include).","Mistakes were made in the initial calculations.","The data was collected by a team of 20 researchers (specific — include)."]','When the agent is vague or irrelevant (mistakes = by someone unspecified), omit.','hard'),
  (cid,5,35,'gap_fill','The research was funded ___ a government grant and ___ private donors.','by / by',NULL,'"By" is repeated when listing multiple agents.','medium'),

  -- BLOCK 6: why we use passive in academic writing
  (cid,6,36,'multiple_choice','Why is passive voice preferred in academic/scientific writing?','To focus on the action, result, or object rather than the person doing it.','["To make sentences more complex","To avoid responsibility","To focus on the action, result, or object rather than the person doing it.","To make the text longer"]','Academic writing often prioritizes findings over the researcher.','medium'),
  (cid,6,37,'gap_fill','In academic writing, "The samples were stored at -20°C" is preferred over "We stored the samples at -20°C" because the passive focuses on ___.','the samples / the procedure (not the researcher)',NULL,'Passive depersonalizes methods sections, focusing on procedure.','hard'),
  (cid,6,38,'multiple_choice','Which active sentence is most effectively rewritten as passive for academic use?','Active: "We measured the temperature every hour." → Passive: "The temperature was measured every hour."','["Active: ''We think the results are significant.'' → Passive (less natural for opinions)","Active: ''We measured the temperature every hour.'' → Passive: ''The temperature was measured every hour.''","Active: ''We argue that the findings matter.'' → Passive (never use for arguments)","Active: ''We hope to publish soon.'' → Passive (intentions stay active)"]','Methods steps (measuring, collecting, storing) are best written in passive.','hard'),
  (cid,6,39,'gap_fill','The passive is especially common in academic ___ sections, where the focus is on procedure rather than the researcher.','methods / methodology',NULL,'Methods sections use passive to describe what was done.','medium'),
  (cid,6,40,'multiple_choice','Choose the most academically appropriate version.','Blood samples were collected at baseline and at 3, 6, and 12 months post-intervention.','["We collected blood samples at baseline and at 3, 6, and 12 months.","Blood samples were collected at baseline and at 3, 6, and 12 months post-intervention.","Researchers collected blood samples at baseline and at 3, 6, and 12 months.","Blood samples are collected at baseline in studies."]','Passive (were collected) is most appropriate in academic methods descriptions.','hard'),
  (cid,6,41,'gap_fill','When the agent is obvious or unimportant, the ___ phrase can be omitted from the passive sentence.','by',NULL,'The "by + agent" phrase is optional when the agent is obvious, unknown, or irrelevant.','medium'),
  (cid,6,42,'multiple_choice','Which sentence would NOT typically appear in the methods section of an academic paper?','We personally believe the experiment was successful.','["The participants were randomly assigned to groups.","Data were analyzed using SPSS software.","All interviews were recorded and transcribed.","We personally believe the experiment was successful."]','Methods sections use passive and avoid personal opinions.','hard'),

  -- BLOCK 7: get-passive
  (cid,7,43,'gap_fill','Her proposal ___ (get/accept) after three revisions.','got accepted',NULL,'"Get + past participle" = informal/colloquial passive, often for unexpected/unplanned results.','medium'),
  (cid,7,44,'multiple_choice','Which sentence uses "get-passive" correctly?','He got promoted to lead researcher after publishing his findings.','["He was gotten promoted to lead researcher.","He is getting promoted.","He got promoted to lead researcher after publishing his findings.","He gets promoted to lead researcher after publishing."]','Got + past participle for get-passive.','medium'),
  (cid,7,45,'gap_fill','Several students ___ (get/fail) because they didn''t submit their assignments on time.','got failed',NULL,'"Got failed" = get-passive for undesirable outcome.','medium'),
  (cid,7,46,'multiple_choice','In which context is "get-passive" more appropriate?','Informal spoken academic discussion','["Formal academic journal article","University thesis","Informal spoken academic discussion","Official research report"]','Get-passive is informal/colloquial — avoid in formal academic writing.','hard'),
  (cid,7,47,'gap_fill','Her car ___ (get/damage) in the flood that occurred near the campus.','got damaged',NULL,'"Got damaged" = get-passive for an unplanned, unfortunate event.','medium'),
  (cid,7,48,'multiple_choice','What is the formal academic equivalent of "The data got corrupted"?','The data was corrupted.','["The data got corrupt.","The data corrupted.","The data was corrupted.","The data is being corrupted."]','Formal academic writing uses was + past participle (not get-passive).','medium'),
  (cid,7,49,'gap_fill','She ___ (get/select) for the prestigious fellowship program.','got selected',NULL,'"Got selected" = informal get-passive for positive achievement.','medium'),

  -- BLOCK 8: active → passive transformation
  (cid,8,50,'gap_fill','Active: "Researchers observed a significant increase in temperature." → Passive: "A significant increase in temperature ___ by researchers."','was observed',NULL,'Was + past participle + by + agent.','medium'),
  (cid,8,51,'multiple_choice','Convert to passive: "Scientists will publish the findings next month."','The findings will be published by scientists next month.','["The findings will published next month.","The findings are published next month.","The findings will be published by scientists next month.","The findings would be published next month."]','Will + be + past participle (+ by + agent).','medium'),
  (cid,8,52,'gap_fill','Active: "The team has conducted three trials." → Passive: "Three trials ___ by the team."','have been conducted',NULL,'Have/has + been + past participle for present perfect passive.','medium'),
  (cid,8,53,'multiple_choice','Convert: "Darwin proposed the theory of natural selection." → Passive?','The theory of natural selection was proposed by Darwin.','["The theory of natural selection is proposed by Darwin.","The theory of natural selection was proposed by Darwin.","The theory of natural selection has been proposed by Darwin.","The theory of natural selection will be proposed by Darwin."]','Was + past participle + by + agent.','medium'),
  (cid,8,54,'gap_fill','Active: "The committee is reviewing all applications." → Passive: "All applications ___ by the committee."','are being reviewed',NULL,'Present continuous passive: are/is + being + past participle.','hard'),
  (cid,8,55,'multiple_choice','Convert to passive: "They are currently analyzing the data."','The data is currently being analyzed.','["The data currently analyzes.","The data is currently analyzed.","The data has been currently analyzed.","The data is currently being analyzed."]','Is + being + analyzed = present continuous passive.','hard'),
  (cid,8,56,'gap_fill','Active: "The professor had reviewed all the papers before the class." → Passive: "All the papers ___ by the professor before the class."','had been reviewed',NULL,'Past perfect passive: had + been + past participle.','hard'),

  -- BLOCK 9: TOEFL academic contexts
  (cid,9,57,'multiple_choice','[TOEFL Reading] Which sentence best uses passive in an academic context?','Carbon dioxide is absorbed by plants during photosynthesis.','["Plants absorb carbon dioxide during photosynthesis (active — also correct but active).","Carbon dioxide is absorbing by plants during photosynthesis (wrong form).","Carbon dioxide was absorbed by plants during photosynthesis (wrong tense for general truth).","Carbon dioxide is absorbed by plants during photosynthesis."]','Present simple passive for scientific fact.','medium'),
  (cid,9,58,'gap_fill','[TOEFL Listening] The professor says: "Over 200 species ___ (identify) in this ecosystem since the park was established."','have been identified',NULL,'Present perfect passive (have been + past participle) for achievements up to now.','hard'),
  (cid,9,59,'multiple_choice','[TOEFL Reading] Which passive sentence would most naturally appear in a results section?','A statistically significant difference was found between the two groups.','["We found a statistically significant difference between the two groups (active).","A statistically significant difference is found between the two groups (present — wrong tense).","A statistically significant difference was found between the two groups.","A statistically significant difference will be found between the two groups (future — wrong)."]','Was + found (past passive) for results section reporting.','hard'),
  (cid,9,60,'gap_fill','[TOEFL Reading] "It ___ (long/believe) that the brain''s capacity for neuroplasticity ___ (limit) to early childhood."','has long been believed / was limited',NULL,'Present perfect passive + past simple passive for established then-challenged belief.','hard'),
  (cid,9,61,'multiple_choice','[TOEFL Listening] The professor says a theory "was challenged by new evidence." What does this imply?','New evidence caused the theory to be questioned or disputed.','["The theory was disproven completely","The theory was supported","New evidence caused the theory to be questioned or disputed.","The theory was never tested"]','Was challenged = passive — the theory (not researchers) is the focus.','medium'),
  (cid,9,62,'gap_fill','[TOEFL Reading] "The structure of DNA ___ (describe) by Watson and Crick in 1953, though much of the foundational work ___ (carry out) by Rosalind Franklin."','was described / had been carried out',NULL,'Past simple passive + past perfect passive for sequence.','hard'),
  (cid,9,63,'multiple_choice','[TOEFL Listening] Which passive sentence is most appropriate for a TOEFL lecture about environmental policy?','Significant reductions in greenhouse gas emissions have been achieved in countries that adopted carbon pricing.','["Countries have achieved significant reductions in greenhouse gas emissions through carbon pricing (active).","Significant reductions in greenhouse gas emissions have been achieved in countries that adopted carbon pricing.","Significant reductions in greenhouse gas emissions had been achieved before countries adopted carbon pricing (wrong tense).","Significant reductions in greenhouse gas emissions are achieved in countries that adopt carbon pricing (present — not specific enough)."]','Have been achieved = present perfect passive for recent policy achievements.','hard'),

  -- BLOCK 10: TOEFL production tasks
  (cid,10,64,'multiple_choice','[TOEFL Reading] Identify the most academic passive construction in a research introduction.','It has been well established that exposure to a second language during early childhood significantly enhances cognitive flexibility.','["We have well established that exposure to a second language enhances cognitive flexibility (active + informal).","It has well established that exposure to a second language enhances cognitive flexibility (missing been).","It has been well established that exposure to a second language during early childhood significantly enhances cognitive flexibility.","It was well established that exposure to a second language enhances cognitive flexibility (wrong tense)."]','It has been + past participle = impersonal present perfect passive for established academic knowledge.','hard'),
  (cid,10,65,'gap_fill','[TOEFL Reading] The article argues that while the problem ___ (acknowledge) by policymakers for decades, insufficient measures ___ (take), and resources ___ (not/allocate) effectively to address it.','has been acknowledged / have been taken / have not been allocated',NULL,'Three present perfect passive constructions in complex academic sentence.','hard'),
  (cid,10,66,'multiple_choice','[TOEFL Speaking — 45s] You are asked to summarize how a scientific discovery was made. Which response best uses passive voice?','The vaccine was developed over a ten-year period. First, the virus was isolated, then the protein structure was analyzed, and finally, a viable compound was synthesized and tested on animal models.','["We developed the vaccine over ten years. We isolated the virus, we analyzed the protein, and we synthesized a compound.","The vaccine was developed over a ten-year period. First, the virus was isolated, then the protein structure was analyzed, and finally, a viable compound was synthesized and tested on animal models.","The vaccine has developed over ten years. The virus is isolated, and the protein is analyzed.","The vaccine was developing over ten years. The virus isolated, and the protein analyzed."]','Sequence of passive constructions (was developed, was isolated, was analyzed, was synthesized) for academic narration.','hard'),
  (cid,10,67,'production','[TOEFL Speaking — 45s] Describe a major scientific discovery or historical event using passive voice throughout. Include: past simple passive for what was done, present perfect passive for how it has been used or recognized since, and future passive for what will be achieved next.','',NULL,'Use passive across three tenses: was + past participle, has/have been + past participle, will be + past participle.','hard'),
  (cid,10,68,'production','[TOEFL Writing] Write a methods paragraph (4-5 sentences) for a hypothetical study on the effects of social media use on university students'' academic performance. Use passive voice throughout to describe: how participants were selected, how data were collected, how variables were measured, and how results were analyzed.','',NULL,'Methods sections use passive to depersonalize procedures: were selected, were collected, was measured, were analyzed.','hard'),
  (cid,10,69,'multiple_choice','[TOEFL Writing] Which sentence best demonstrates the use of passive in an academic essay conclusion?','These findings suggest that more rigorous oversight mechanisms must be established if the integrity of the research process is to be maintained.','["These findings suggest that we must establish more rigorous oversight mechanisms to maintain research integrity.","These findings suggest that more rigorous oversight mechanisms must be established if the integrity of the research process is to be maintained.","These findings suggest more rigorous oversight mechanisms should establish if integrity is to be maintained.","These findings suggest that more rigorous oversight mechanisms has been established."]','Must be established + is to be maintained = passive with modal for formal academic recommendation.','hard'),
  (cid,10,70,'production','[TOEFL Writing] Write a 5-sentence academic paragraph arguing for greater transparency in pharmaceutical research. Include: (1) a present simple passive for a general fact, (2) a present perfect passive for a recent development, (3) a past simple passive for a historical example, (4) a future passive for a proposed action, and (5) a modal passive (must/should + be + past participle) for a recommendation. Avoid using "by + agent" unless it is essential.','',NULL,'Demonstrate passive voice across all tenses and with modal verbs in a coherent academic argument.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
