-- ============================================================
-- SEED EXT 3: Módulo 08 — Past Perfect (ex 108-205)
-- Novos tópicos: PP em reported speech, conditional Type 3,
-- past perfect em narrativa histórica avançada, TOEFL
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'past-perfect';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo past-perfect não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 31: past perfect em situações hipotéticas (Type 3)
  (cid,31,108,'gap_fill','If the team _____ (secure) funding earlier, they would have published their results two years ago.','had secured',NULL,'"Had + past participle" in the if-clause of a Type 3 conditional.','hard'),
  (cid,31,109,'multiple_choice','Which Type 3 conditional uses past perfect correctly?','Had the researchers disclosed the conflict of interest, the paper would have been accepted.','["If the researchers had disclosed the conflict, the paper would accept.","If the researchers disclosed the conflict, the paper would have been accepted (wrong if-clause tense).","Had the researchers disclosed the conflict of interest, the paper would have been accepted.","Had the researchers disclose the conflict, the paper would have been accepted."]','Inverted Type 3: "Had + subject + past participle + result with would have."','hard'),
  (cid,31,110,'gap_fill','The patient _____ (survive) if the diagnosis _____ (make/passive) earlier.','would have survived / had been made',NULL,'Type 3 conditional: would have survived + had been made (passive PP in if-clause).','hard'),
  (cid,31,111,'multiple_choice','What does "would have been" express in: "The study would have been more impactful had the sample size been larger"?','An unrealized past outcome — the study was less impactful because the sample was small.','["A future prediction","An unrealized past outcome — the study was less impactful because the sample was small.","A past habit","A reported speech construction"]','Type 3 conditional result: would have been = what would have happened but didn''t.','medium'),
  (cid,31,112,'gap_fill','The policy _____ (not/fail) if it _____ (design/passive) with more stakeholder input.','would not have failed / had been designed',NULL,'Type 3: negative result + passive past perfect in if-clause.','hard'),

  -- BLOCK 32: PP em narrativa histórica avançada
  (cid,32,113,'gap_fill','By the time WWII ended, the Manhattan Project _____ (produce) two functional atomic bombs.','had produced',NULL,'"By the time + past simple, PP" for prior completion.','medium'),
  (cid,32,114,'multiple_choice','Which sentence uses past perfect most effectively in a historical narrative?','By the time the Great Fire of London erupted in 1666, the city had already survived decades of plague and civil war.','["When the Great Fire of London erupted in 1666, the city survived decades of plague and civil war.","By the time the Great Fire of London erupted in 1666, the city had already survived decades of plague and civil war.","By the time the Great Fire of London erupted in 1666, the city has survived decades of plague and civil war.","When the Great Fire of London erupted in 1666, the city had been surviving decades of plague and war."]','"By the time + past simple + past perfect" for events preceding the main historical event.','hard'),
  (cid,32,115,'gap_fill','Before Darwin _____ (publish) On the Origin of Species in 1859, other naturalists _____ (already/propose) related ideas.','published / had already proposed',NULL,'Past simple for main event, PP for earlier event.','hard'),
  (cid,32,116,'multiple_choice','In academic historical writing, the past perfect is used to:','Show that one event preceded another in the past.','["Describe repeated past events","Show that one event preceded another in the past.","Describe future plans from a past perspective","Express past wishes"]','Past perfect = "the past of the past" in historical narration.','easy'),
  (cid,32,117,'gap_fill','The Roman Empire _____ (expand/passive) across most of Europe long before its decline began in the 3rd century CE.','had been expanded / had expanded',NULL,'Past perfect for prior historical expansion before the main event.','hard'),

  -- BLOCK 33: PP em reported speech avançado
  (cid,33,118,'multiple_choice','Direct: "We have analyzed the data." → Reported (past):','She reported that they had analyzed the data.','["She reported that they have analyzed the data.","She reported that they analyzed the data (past simple — also acceptable).","She reported that they had analyzed the data.","She reported that they were analyzing the data."]','Present perfect → past perfect in reported speech (backshift).','medium'),
  (cid,33,119,'gap_fill','Direct: "The government has approved the budget." → Reported: The spokesperson announced that the government _____ the budget.','had approved',NULL,'Present perfect → past perfect in reported speech.','medium'),
  (cid,33,120,'multiple_choice','Direct: "We had already submitted the application before the deadline." → What happens in reported speech?','Past perfect stays as past perfect — no further backshift possible.','["Past perfect → past simple in reported speech","Past perfect → present perfect in reported speech","Past perfect stays as past perfect — no further backshift possible.","Past perfect → past perfect continuous"]','Past perfect cannot shift further back — it remains past perfect in reported speech.','hard'),
  (cid,33,121,'gap_fill','Direct: "The experiment failed because we used the wrong reagent." → Reported: She explained that the experiment _____ (fail) because they _____ (use) the wrong reagent.','had failed / had used',NULL,'Past simple → past perfect in reported speech (backshift of both verbs).','hard'),
  (cid,33,122,'multiple_choice','Which sentence correctly converts to reported speech? Direct: "I finished the report two hours ago."','She said she had finished the report two hours earlier / before.','["She said she has finished the report two hours ago.","She said she finished the report two hours ago (informal — acceptable in some contexts).","She said she had finished the report two hours earlier / before.","She said she would have finished the report two hours ago."]','Past simple → past perfect in backshift. "Ago" → "before/earlier" in reported speech.','hard'),
  (cid,33,123,'gap_fill','Direct: "By the time we arrived, they had eaten everything." → Reported: He told us that by the time they _____ (arrive), the others _____ (eat) everything.','had arrived / had eaten',NULL,'PP stays PP in reported speech.','medium'),

  -- BLOCK 34: PP com wish e if only
  (cid,34,124,'gap_fill','She wishes she _____ (apply) for the grant last year — she was fully eligible.','had applied',NULL,'"Wish + past perfect" = regret about a past action.','hard'),
  (cid,34,125,'multiple_choice','What is the meaning of "If only I had taken better notes during the lecture"?','I regret not taking better notes — it is too late to change it.','["I plan to take better notes in the future","I took excellent notes during the lecture","I regret not taking better notes — it is too late to change it.","I should take better notes in the future"]','"If only + past perfect" = past regret (opposite of what happened).','medium'),
  (cid,34,126,'gap_fill','If only the committee _____ (consult) more stakeholders, the policy would have been more widely accepted.','had consulted',NULL,'"If only + past perfect" = regret about a past failure to act.','hard'),
  (cid,34,127,'multiple_choice','Which expresses the STRONGEST past regret?','I wish I had never agreed to co-author that paper.','["I wish I would agree to co-author that paper.","I wish I hadn''t agreed (both correct — equally strong regret).","I wish I had never agreed to co-author that paper.","I hope I hadn''t agreed to co-author that paper."]','"I wish I had never + past participle" = past regret with strong emphasis.','medium'),

  -- BLOCK 35: TOEFL Reading
  (cid,35,128,'multiple_choice','[TOEFL Reading] "By the time the antibiotic was discovered, the infection had already spread to neighboring tissues." The past perfect "had spread" indicates:','The spread occurred before the discovery of the antibiotic.','["Both events happened simultaneously","The spread occurred after the discovery","The spread occurred before the discovery of the antibiotic.","The spread is still occurring"]','Past perfect = earlier of two past events.','easy'),
  (cid,35,129,'gap_fill','[TOEFL Reading] "Historians note that the seeds of the revolution _____ (plant/passive + PP) decades before the actual uprising occurred." Best form?','had been planted',NULL,'Past perfect passive for prior historical event.','hard'),
  (cid,35,130,'multiple_choice','[TOEFL Reading] "Had the levees been properly maintained, the flooding would have been far less severe." This Type 3 conditional implies:','The levees were NOT properly maintained, and the flooding was severe.','["The levees were maintained properly","The flooding was minimal","The levees were NOT properly maintained, and the flooding was severe.","The flood had not yet occurred"]','Type 3 conditional = contrary to past fact.','medium'),
  (cid,35,131,'gap_fill','[TOEFL Reading] "The explorer reported that he _____ (reach) the summit before any European had done so." Best PP form?','had reached',NULL,'Past perfect in reported speech (past simple in direct → PP in reported).','hard'),
  (cid,35,132,'multiple_choice','[TOEFL Reading] "By the time quantum mechanics emerged as a field, classical physics had dominated scientific thought for over two centuries." This sentence:','Uses past perfect to show classical physics preceded quantum mechanics.','["Describes two simultaneous events","Uses past simple for both events","Uses past perfect to show classical physics preceded quantum mechanics.","Describes a future prediction from a past perspective"]','Past perfect (had dominated) = earlier event preceding "emerged" (past simple).','easy'),

  -- BLOCK 36: TOEFL Speaking
  (cid,36,133,'production','[TOEFL Speaking — 45s] A professor discusses a failed scientific project. Use: past perfect (had + PP), had been + -ing (PP continuous), wish + PP (regret), Type 3 conditional (had + PP / would have).','',NULL,'The SETI project had been operating for nearly 50 years before government funding was significantly cut in the 1990s. Scientists who had worked on the project for decades expressed deep regret about the decision. Many wished the program had been given more time, arguing that the search for extraterrestrial intelligence required sustained, multi-generational commitment. Had funding been maintained, the field would have produced far more comprehensive datasets and attracted a new generation of researchers. The decision remains controversial.','hard'),
  (cid,36,134,'production','[TOEFL Speaking — 45s] An article says that mistakes in early childhood education have long-lasting effects. Agree or disagree. Use: past perfect, if only, had...not (Type 3), had been + -ing.','',NULL,'I agree that early education experiences have profound and lasting consequences. Research has shown that children who had not received adequate early stimulation often struggled with literacy for their entire school careers. If only education systems had invested more heavily in early childhood programs decades ago, the outcomes for millions of adults today would have been markedly better. Had policymakers recognized the importance of the early years sooner, funding would have been directed where it matters most. This evidence suggests that governments should be investing in early education now, not waiting for the consequences of neglect to manifest years later.','hard'),

  -- BLOCK 37: TOEFL Writing
  (cid,37,135,'production','[TOEFL Writing — 150 words] Write a historical narrative paragraph about the Apollo program using: past perfect (×3), past perfect continuous (×1), past perfect passive (×1), Type 3 conditional (×1), reported speech with PP (×1).','',NULL,'By the time Neil Armstrong stepped onto the lunar surface in July 1969, NASA had spent nearly a decade preparing for the moment. Engineers had been working around the clock since the early 1960s to solve the immense technical challenges of human spaceflight. Crucially, the program had benefited enormously from the tragic lessons of the Apollo 1 fire in 1967, which had claimed the lives of three astronauts and prompted a comprehensive redesign of the spacecraft. Mission controllers reported that the guidance computer had performed flawlessly during the final descent. Had the Soviet Union not posed such a formidable competitive challenge during the Space Race, it is uncertain whether the US Congress would have approved the extraordinary funding that made the lunar landing possible.','hard'),
  (cid,37,136,'production','[TOEFL Writing — Error Correction] Fix past perfect errors: "If the researchers would have been more careful, they would have caught the error. She said that she has finished the analysis the day before. By the time we arrive, the meeting already started. I wish I applied for the fellowship last year."','',NULL,'would have been more careful → had been more careful (Type 3 if-clause: had + past participle, not would have); has finished → had finished (present perfect → past perfect in reported speech); the meeting already started → the meeting had already started (past perfect for event prior to ''we arrive''); I wish I applied → I wish I had applied (wish + past perfect for past regret).','hard'),
  (cid,37,137,'production','[TOEFL Writing — 200 words] Write a TOEFL-style essay paragraph on "The lessons that history teaches about pandemic preparedness." Use: past perfect (×3), Type 3 conditional (×1), past perfect passive (×1), past perfect continuous (×1), and wish/if only (×1).','',NULL,'History offers sobering lessons about the consequences of neglecting pandemic preparedness. By the time COVID-19 was declared a global emergency in March 2020, scientists had been warning about the risk of a novel coronavirus for over a decade. Several national pandemic response plans had been drafted in the aftermath of SARS in 2003 and MERS in 2012, yet many governments had allowed the infrastructure and stockpiles those plans required to deteriorate through underinvestment. Had international health agencies been granted greater enforcement powers after the 2009 H1N1 pandemic, the global response to COVID-19 might have been far more coordinated and effective. Key early warning systems had been decommissioned or defunded by the time the first outbreak was detected in Wuhan. If only governments had maintained their pandemic preparedness agencies and supply chains, the catastrophic disruption of 2020 might have been significantly mitigated. The lesson is clear: investing in preparedness before a crisis, though politically unglamorous, is incomparably less costly than responding to one.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
