-- ============================================================
-- SEED EXT 4: Módulo 11 — Relative Clauses (ex 146-220)
-- Novos tópicos: cláusulas relativas reduzidas, participial clauses,
-- pseudo-cleft/cleft sentences, RC em academic writing avançado
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'relative-clauses';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo relative-clauses não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 41: Reduced relative clauses (participial phrases)
  (cid,41,146,'multiple_choice','Which participial phrase correctly REDUCES "the policy that was introduced in 2020"?','the policy introduced in 2020','["the policy introducing in 2020","the policy having introduced in 2020","the policy introduced in 2020","the policy which introduced in 2020"]','Passive relative clause → past participle alone: which was introduced → introduced.','medium'),
  (cid,41,147,'gap_fill','The researchers _____ (conduct) the study were affiliated with three different universities.','conducting',NULL,'Active relative clause reduced: who were conducting → conducting (present participle).','medium'),
  (cid,41,148,'multiple_choice','Which sentence correctly uses a REDUCED relative clause?','Countries experiencing rapid urbanization often face infrastructure shortfalls.','["Countries who experience rapid urbanization often face infrastructure shortfalls (full RC correct too).","Countries experiencing rapid urbanization often face infrastructure shortfalls.","Countries experienced rapid urbanization often face infrastructure shortfalls.","Countries that experiencing rapid urbanization often face infrastructure shortfalls."]','"Countries experiencing" = reduced RC (countries that are experiencing → experiencing).','medium'),
  (cid,41,149,'gap_fill','The evidence _____ (collect) by both teams _____ (point) toward the same conclusion.','collected / points',NULL,'Reduced passive RC (that was collected → collected) + PS main verb.','hard'),
  (cid,41,150,'multiple_choice','Which ACTIVE reduced relative clause is correct?','The student submitting the paper late will receive a penalty.','["The student submitted the paper late will receive a penalty (past participle — passive, wrong for active meaning).","The student having been submitted the paper late will receive a penalty (passive + wrong form).","The student submitting the paper late will receive a penalty.","The student which submits the paper late will receive a penalty."]','Active RC: student who submits → submitting (present participle).','hard'),
  (cid,41,151,'gap_fill','The package _____ (send) yesterday _____ (still/not/arrive).','sent / has still not arrived',NULL,'Reduced passive RC (that was sent → sent) + PP negative for current relevance.','medium'),

  -- BLOCK 42: RC com quantificadores (most of which, many of whom)
  (cid,42,152,'gap_fill','The committee reviewed forty proposals, _____ of _____ met the eligibility criteria.','most / which',NULL,'"Most of which" = quantifier + of which for things.','medium'),
  (cid,42,153,'multiple_choice','Which sentence correctly uses "many of whom"?','The participants, many of whom had never used digital banking before, completed the survey.','["The participants, many of which had never used digital banking before, completed the survey (which for people — error).","The participants, many of whom had never used digital banking before, completed the survey.","The participants, many of who had never used digital banking before, completed the survey (who → whom in object position).","The participants, many of them had never used digital banking before, completed the survey."]','"Whom" = object form of "who." "Of whom" follows quantifiers for people.','hard'),
  (cid,42,154,'gap_fill','The company operated 20 manufacturing facilities, _____ of _____ have since been closed as part of a restructuring program.','several / which',NULL,'"Several of which" for things (facilities).','medium'),
  (cid,42,155,'gap_fill','Scientists interviewed 300 experts, _____ of _____ expressed serious concern about the pace of development.','two-thirds / whom',NULL,'"Two-thirds of whom" for people = fraction quantifier + of whom.','hard'),
  (cid,42,156,'multiple_choice','Which quantifier + relative pronoun combination is INCORRECT?','"Half of who were women" — should be "half of whom".','["Most of which were published before 2000 (things — correct)","Some of whom disagreed with the findings (people — correct)","None of which was accepted (things, singular verb — correct)","Half of who were women — should be ''half of whom''."]','"Who" cannot follow prepositions/quantifiers — use "whom" in object/prepositional position.','hard'),

  -- BLOCK 43: Cleft sentences (It is... that/who)
  (cid,43,157,'multiple_choice','What is the function of a cleft sentence like "It was the lack of funding that caused the program to fail"?','To emphasize a specific part of the sentence by placing it in focus position.','["To avoid using the passive","To emphasize a specific part of the sentence by placing it in focus position.","To form a question","To express a condition"]','Cleft = emphatic construction: "It was X that..." highlights X as the key information.','easy'),
  (cid,43,158,'gap_fill','It _____ the increasing cost of living _____ forced many young people to move out of the city center.','was / that',NULL,'"It was + focus element + that + rest of sentence" = cleft construction.','easy'),
  (cid,43,159,'gap_fill','It _____ not the policy itself _____ was the problem, but the lack of community consultation before implementation.','was / that',NULL,'Negative cleft: "It was not X that... but Y" for contrast.','medium'),
  (cid,43,160,'multiple_choice','Which PSEUDO-CLEFT sentence is grammatically correct?','What the study demonstrates is that early intervention significantly improves outcomes.','["What the study demonstrates are that early intervention improves outcomes (subject-verb agreement error).","What the study demonstrates is that early intervention significantly improves outcomes.","What demonstrates the study is that early intervention improves outcomes.","What the study is demonstrates early intervention improves outcomes."]','Pseudo-cleft: What + clause + is/are + complement. Singular subject → "is."','hard'),
  (cid,43,161,'gap_fill','What the data _____ (reveal) _____ a systematic pattern of underinvestment in public infrastructure.','reveal / is',NULL,'Pseudo-cleft: What + verb + is + NP. Subject "what the data reveal" = singular → "is."','hard'),
  (cid,43,162,'multiple_choice','Which sentence uses a REVERSED PSEUDO-CLEFT correctly?','A complete overhaul of the tax code is what the opposition has been demanding.','["A complete overhaul of the tax code is what demands the opposition.","A complete overhaul of the tax code is what the opposition has been demanding.","What demands is a complete overhaul of the tax code by the opposition.","A complete overhaul of the tax code what the opposition has been demanding."]','Reversed pseudo-cleft: NP/AP + is + what-clause.','hard'),

  -- BLOCK 44: RC em academic writing — complex embedding
  (cid,44,163,'gap_fill','The theory, _____ (develop) by Vygotsky in the 1930s and _____ (extend) by subsequent researchers, remains foundational to developmental psychology.','developed / extended',NULL,'Non-defining RC reduced to paired past participles.','hard'),
  (cid,44,164,'multiple_choice','Which sentence uses a DEFINING relative clause in ACADEMIC WRITING most effectively?','Economies that rely heavily on commodity exports are particularly vulnerable to price volatility.','["Economies, which rely heavily on commodity exports, are vulnerable to price volatility (non-defining — true of ALL economies? Wrong for defining distinction).","Economies that rely heavily on commodity exports are particularly vulnerable to price volatility.","Economies who rely heavily on commodity exports are vulnerable to price volatility (who for things — error).","Economies which rely heavily on commodity exports, are particularly vulnerable to price volatility (comma error in defining RC)."]','Defining RC (no commas) + "that" = restricts which economies are meant.','medium'),
  (cid,44,165,'gap_fill','The model _____ (describe) in this paper builds on earlier work by integrating variables _____ previous studies _____ (neglect).','described / that / had neglected',NULL,'Reduced passive RC + defining RC with PP for prior neglect.','hard'),
  (cid,44,166,'multiple_choice','Which academic sentence correctly uses THREE embedded relative clauses?','The data, which were collected in a region in which environmental regulations have traditionally been weak, support a hypothesis that critics have long questioned.','["The data, which were collected in a region which environmental regulations have been weak in, support a hypothesis that critics questioned long.","The data, which were collected in a region in which environmental regulations have traditionally been weak, support a hypothesis that critics have long questioned.","The data that were collected in a region which environmental regulations have been weak, support a hypothesis which critics have long questioned.","The data, which collected in a region in which environmental regulations traditionally been weak, support a hypothesis that critics questioned."]','Three RCs: "which were collected" (non-def), "in which regulations... weak" (defining), "that critics have long questioned" (defining).','hard'),

  -- BLOCK 45: TOEFL Reading
  (cid,45,167,'multiple_choice','[TOEFL Reading] "The Amazon rainforest, which covers an area larger than Western Europe, plays a critical role in global climate regulation." The non-defining relative clause is used to:','Add background information about the Amazon''s size without restricting the subject.','["Identify which Amazon is meant","Add background information about the Amazon''s size without restricting the subject.","Express a condition","Introduce a contrast"]','Non-defining RC = additional, parenthetical information.','easy'),
  (cid,45,168,'gap_fill','[TOEFL Reading] "The findings, _____ point to a direct link between social isolation and cognitive decline, challenge the assumption _____ mental health and physical health are independent domains." Best forms?','which / that',NULL,'"Which" = non-defining RC for findings. "That" = defining RC for assumption content.','medium'),
  (cid,45,169,'multiple_choice','[TOEFL Reading] "Countries in which birth rates have fallen significantly are projecting pension system deficits within two decades." The RC "in which birth rates have fallen significantly" functions as:','A defining relative clause restricting which countries are under discussion.','["A non-defining clause adding supplementary information","A defining relative clause restricting which countries are under discussion.","A result clause","A concession clause"]','No commas + "in which" = defining RC: restricts to the specific countries with falling birth rates.','medium'),
  (cid,45,170,'gap_fill','[TOEFL Reading] "The technology _____ the engineers _____ (develop) proved more effective than _____ currently in use." Best forms?','that / developed / that / which',NULL,'"That...developed" = defining RC (object). "That/which currently in use" = reduced RC.','hard'),

  -- BLOCK 46: TOEFL Speaking
  (cid,46,171,'production','[TOEFL Speaking — 45s] A reading argues for a new urban planning approach. Describe it using relative clauses, cleft sentences, and reduced RCs.','',NULL,'The reading advocates for what urban planners call the "15-minute city" — a model in which all essential services, from groceries to healthcare to recreational facilities, are located within a 15-minute walk or cycle ride of every resident. It is this proximity principle that distinguishes the model from conventional suburban planning, which has historically prioritized the automobile as the primary mode of movement. Cities that have implemented versions of this approach, including Paris and Barcelona, have reported improvements in air quality, reductions in traffic, and increases in community social interaction. The reading argues that it is not the physical density of cities that matters most but the mix of uses within walking distance — a finding supported by research showing that mixed-use neighborhoods generate significantly more street activity, informal social contact, and perceived safety than single-use zones.','hard'),
  (cid,46,172,'production','[TOEFL Speaking — 45s] Discuss someone whose work you admire. Use defining and non-defining relative clauses, reduced RCs, and cleft sentences.','',NULL,'The scientist whose work I find most intellectually exciting is Barbara McClintock, a geneticist who spent most of her career studying maize and whose discoveries transformed our understanding of how genomes work. What made her work revolutionary was her discovery that genes could move between chromosomes — a phenomenon she called transposition, which the scientific community initially dismissed as implausible. It was not until the 1970s, decades after her initial findings, that molecular biologists confirmed transposons in other organisms and recognized their central role in genetic regulation. McClintock, who continued working actively into her eighties, received the Nobel Prize in 1983 — the first woman to win it unshared in Physiology or Medicine. What her career demonstrates is that significant scientific advances can be overlooked for decades when they challenge the prevailing theoretical framework of the field.','hard'),

  -- BLOCK 47: TOEFL Writing
  (cid,47,173,'production','[TOEFL Writing — 150 words] Write a body paragraph on economic inequality. Use: defining RC (×2), non-defining RC (×1), reduced RC (×2), cleft sentence (×1).','',NULL,'Economic inequality, which has widened significantly in most developed economies since the 1980s, poses challenges that extend well beyond the immediate welfare of those at the bottom of the income distribution. It is the concentration of income and wealth at the very top of the distribution that has attracted the most analytical attention, not merely the conditions of poverty. Economies experiencing extreme inequality tend to exhibit lower levels of social mobility — making it harder for individuals born into low-income households to achieve economic outcomes commensurate with their abilities. Research conducted in highly unequal societies also suggests that inequality is associated with higher rates of mental illness, crime, and political polarization, all of which impose costs that extend throughout the income distribution. The mechanisms connecting inequality to these outcomes remain debated, but the empirical patterns observed across countries are difficult to explain by any other variable.','hard'),
  (cid,47,174,'production','[TOEFL Writing — Error Correction] Fix RC errors: "The researcher, that won the prize, published her findings. The theory which developed by Kuhn challenges positivism. It was the evidence what convinced the committee. Scientists whom study volcanoes work in dangerous conditions."','',NULL,'that → who or comma-less that (non-defining RC requires ''which'' not ''that'': the researcher, who won... OR defining without commas: the researcher that won / who won); which developed → which was developed (passive RC needs ''was''); what → that (cleft: ''It was... that...'', not ''what''); whom → who (subject position in defining RC: scientists who study).','hard'),

  -- BLOCK 48: Consolidação final
  (cid,48,175,'production','[TOEFL Writing — 200 words] Write a paragraph on climate migration using defining RC (×2), non-defining RC (×1), reduced RC (×2), quantifier + of which/whom (×1), cleft sentence (×1).','',NULL,'Climate migration — the movement of people displaced by environmental changes attributed to climate change — is emerging as one of the most pressing humanitarian challenges of the coming century. It is the confluence of sea-level rise, extreme weather intensification, and agricultural collapse that is driving displacement at scales that existing refugee and asylum frameworks were never designed to manage. Low-lying island nations, which face the prospect of complete inundation within decades, represent the most extreme case of climate-driven displacement, but they are far from the only one. Regions experiencing prolonged drought — particularly in the Sahel, South Asia, and Central America — are already seeing migration intensify, with many of those displaced moving first to nearby cities before international migration becomes necessary or possible. The global institutional framework, developed primarily in the aftermath of World War II, does not formally recognize climate displacement as a basis for international protection, a gap that leaves many people affected by environmental degradation without legal status. Addressing this gap represents one of the most significant governance challenges that the international community has so far failed to adequately confront.','hard'),
  (cid,48,176,'production','[TOEFL Speaking — 60s] Discuss the concept of globalization. Use defining RCs, non-defining RCs, reduced RCs, and cleft sentences.','',NULL,'Globalization — the deepening integration of economies, cultures, and political systems across national boundaries — is a phenomenon that has generated intense debate among economists, sociologists, and political scientists. It is the combination of technological change, particularly in communications and transportation, and deliberate policy choices, particularly trade liberalization, that has driven the most recent phase of global economic integration. Countries that have participated actively in global trade networks have generally achieved faster economic growth and more rapid poverty reduction than those that have remained isolated, though the distribution of the gains from trade — both within countries and between them — has been profoundly unequal. At the same time, the globalization of production, which has allowed multinational companies to locate manufacturing wherever costs are lowest, has exposed many workers in developed countries to competition that their wages and working conditions cannot survive. The communities most affected by deindustrialization, many of whom have been promised retraining opportunities that never materialized, have experienced rising mortality, declining social cohesion, and growing political alienation. What the globalization debate ultimately concerns is not the aggregate efficiency gains from trade but the question of who captures those gains and who bears the adjustment costs.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
