-- ============================================================
-- SEED EXT 4: Módulo 13 — Reported Speech (ex 174-253)
-- Novos tópicos: verbos de report epistêmicos avançados,
-- reported exclamatives/wishes, free indirect discourse, TOEFL
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'reported-speech';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo reported-speech não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 41: verbos report + padrões sintáticos (V + that / V + obj + that / V + -ing)
  (cid,41,174,'multiple_choice','Which reporting verb pattern is "acknowledge + that"?','She acknowledged that the data contained a significant outlier.','["She acknowledged to the data containing an outlier.","She acknowledged that the data contained a significant outlier.","She acknowledged the data to contain an outlier.","She acknowledged the data contained (no ''that'' — informal but acceptable)."]','"Acknowledge + that-clause" = formal report of concession.','medium'),
  (cid,41,175,'gap_fill','The spokesperson _____ (confirm) that the product recall _____ (affect) approximately 200,000 units worldwide.','confirmed / affected',NULL,'"Confirm + that-clause" + backshift (affect → affected).','medium'),
  (cid,41,176,'multiple_choice','Which reporting verb takes an OBJECT before the that-clause?','The professor reminded students that the deadline was non-negotiable.','["The professor suggested that the deadline was non-negotiable (no object).","The professor reminded students that the deadline was non-negotiable.","The professor announced that the deadline was non-negotiable (no object).","The professor claimed that the deadline was non-negotiable (no object)."]','"Remind + object + that" requires an indirect object.','hard'),
  (cid,41,177,'gap_fill','Critics _____ (allege) that the government _____ (suppress/passive) key findings before the election.','alleged / had suppressed / had been suppressed',NULL,'"Allege + that-clause" = report unverified accusation + backshift.','hard'),
  (cid,41,178,'gap_fill','The scientist _____ (hypothesize) that the observed effect _____ (cause/passive) by a previously unknown enzyme.','hypothesized / was caused / had been caused',NULL,'"Hypothesize + that-clause" = academic report of a proposed explanation + backshift.','hard'),

  -- BLOCK 42: reported wishes, exclamations, and reactions
  (cid,42,179,'gap_fill','Direct: "What an extraordinary result!" → Reported: She _____ (exclaim) that the result _____ (be) extraordinary.','exclaimed / was',NULL,'"Exclaim + that-clause" = report an exclamation (no exclamation mark in reported speech).','medium'),
  (cid,42,180,'multiple_choice','Which reports a wish most correctly? Direct: "I wish I had more time."','She said she wished she had had more time.','["She said she wishes she had more time.","She said she wished she had had more time.","She said she wished she has more time.","She said that she wished she would have more time."]','"Wished" (backshift) + "had had" (past perfect for past wish/regret).','hard'),
  (cid,42,181,'gap_fill','Direct: "If only I had known about this earlier!" → Reported: He _____ (express) regret that he had not known about it earlier.','expressed',NULL,'"Express regret that" = formal way to report an if-only wish.','hard'),
  (cid,42,182,'multiple_choice','Which sentence correctly reports a rhetorical question?','The professor asked rhetorically how society could ignore such clear evidence.','["The professor asked how could society ignore such clear evidence.","The professor asked rhetorically how society could ignore such clear evidence.","The professor asked that society how it could ignore such evidence.","The professor asked rhetorically how society ignores such clear evidence."]','Indirect question order: how society could (not how could society).','hard'),
  (cid,42,183,'gap_fill','Direct: "I''m delighted to announce that the project has been funded!" → Reported: The director _____ (announce) with delight that the project _____ (fund/passive).','announced / had been funded',NULL,'"Announce + that-clause" + backshift passive.','medium'),

  -- BLOCK 43: free indirect discourse
  (cid,43,184,'multiple_choice','What is free indirect discourse?','A literary technique where the narrator presents a character''s thoughts/speech without explicit quotation markers or reporting verbs.','["A way to quote sources directly in academic writing","A literary technique where the narrator presents a character''s thoughts/speech without explicit quotation markers or reporting verbs.","A formal type of direct speech","A mistake in reported speech"]','Free indirect discourse = narration from a character''s perspective, third person, past tense: "She was tired. Why had nobody helped her?"','hard'),
  (cid,43,185,'gap_fill','Free indirect discourse example: "He walked into the lab. _____ (What + be + the point) of continuing? The data _____ (seem) hopeless." (FID — third person, past tense, no reporting verb)','What was the point / seemed',NULL,'Free indirect discourse: third person + past tense + character''s viewpoint without reporting verb.','hard'),
  (cid,43,186,'multiple_choice','Which sentence uses FREE INDIRECT DISCOURSE?','She stared at the results. How could this have happened? Everything had seemed so promising.','["She thought, ''How could this have happened?'' (direct thought)","She wondered how this could have happened (normal indirect thought).","She stared at the results. How could this have happened? Everything had seemed so promising.","The narrator explained that she was confused by the results."]','"How could this have happened?" = FID — rhetorical question in third-person narrative, no reporting verb.','hard'),

  -- BLOCK 44: reported speech em contexto acadêmico (citation reporting)
  (cid,44,187,'gap_fill','Smith (2020) _____ (argue) that economic models _____ (fail) to account for psychological factors.','argues / fail',NULL,'Academic citation: present simple for reporting active scholarly claim (no backshift when using present).','hard'),
  (cid,44,188,'multiple_choice','When reporting a 2010 study in a literature review, which tense choice is MOST typical in academic English?','According to Jones (2010), the intervention reduced dropout rates by 30%.','["According to Jones (2010), the intervention reduces dropout rates by 30% (present — possible but unusual for old studies).","According to Jones (2010), the intervention had reduced dropout rates by 30%.","According to Jones (2010), the intervention reduced dropout rates by 30%.","According to Jones (2010), the intervention was reducing dropout rates by 30%."]','Past simple = standard for reporting specific past studies with a date.','medium'),
  (cid,44,189,'gap_fill','As Chen et al. (2022) _____ (demonstrate), early intervention _____ (have) measurable long-term benefits.','demonstrate / has',NULL,'Present simple for recent, still-valid academic findings.','medium'),
  (cid,44,190,'gap_fill','The authors _____ (note) that their findings _____ (must/interpret/passive) with caution given the small sample size.','noted / must be interpreted',NULL,'Past simple (noted) + modal passive for reported caveat.','hard'),
  (cid,44,191,'multiple_choice','Which is MOST appropriate when reporting that a finding is now considered outdated?','Earlier studies claimed that X caused Y; however, subsequent research has shown that this relationship is more complex.','["Earlier studies claim that X caused Y; however, subsequent research has shown it is more complex.","Earlier studies claimed that X caused Y; however, subsequent research has shown that this relationship is more complex.","Earlier studies have claimed that X caused Y; subsequent research claimed it is complex.","Earlier studies claimed X caused Y and subsequent research showed it is complex."]','Past simple for outdated claim + present perfect for subsequent revision.','hard'),

  -- BLOCK 45: erros comuns em reported speech
  (cid,45,192,'multiple_choice','Which sentence contains a reported speech ERROR?','She said me that the results were significant.','["She told me that the results were significant (correct).","She said that the results were significant (correct).","She said me that the results were significant.","She informed me that the results were significant (correct)."]','"Said me" = error. "Say" does not take an indirect object. Use "told me" or "said to me."','medium'),
  (cid,45,193,'gap_fill','Direct: "We cannot accept late submissions." → Reported: The professor _____ (state) that they _____ (cannot/accept) late submissions.','stated / could not accept',NULL,'"Cannot" → "could not" in backshift.','medium'),
  (cid,45,194,'multiple_choice','Direct: "Always back up your files." → Reported (imperative):','She told the students to always back up their files.','["She said the students always to back up their files.","She told that the students should always back up their files.","She told the students to always back up their files.","She said to the students that they back up their files."]','"Tell + object + to + infinitive" = reported positive imperative.','medium'),
  (cid,45,195,'gap_fill','Direct: "Did you submit your thesis?" → Reported: She asked _____ (whether) he had submitted his thesis.','whether / if',NULL,'Yes/no indirect question: whether/if + subject + verb (no inversion).','easy'),
  (cid,45,196,'multiple_choice','Which reported question uses CORRECT word order?','The editor asked what the main contribution of the paper was.','["The editor asked what was the main contribution of the paper.","The editor asked what the main contribution of the paper was.","The editor asked that what the main contribution of the paper was.","The editor asked what had been the main contribution."]','Indirect question = statement order (what the contribution was, not what was the contribution).','medium'),

  -- BLOCK 46: TOEFL Reading
  (cid,46,197,'multiple_choice','[TOEFL Reading] "Proponents of the theory contend that current models fail to account for social heterogeneity." The verb "contend" signals:','A strongly held academic position in ongoing debate.','["Agreement with the theory","A historical claim now disproven","A strongly held academic position in ongoing debate.","A direct quotation"]','"Contend" = argue strongly in an ongoing academic dispute.','easy'),
  (cid,46,198,'gap_fill','[TOEFL Reading] "Researchers _____ (warn) that rapid urbanization _____ (exacerbate) existing inequalities unless accompanied by targeted policy interventions." Best tense?','warn / may exacerbate / exacerbates',NULL,'"Warn that + present/modal" for current ongoing academic warning.','medium'),
  (cid,46,199,'multiple_choice','[TOEFL Reading] A passage states: "Darwin (1859) argued that natural selection was the primary mechanism of evolution." This is reported speech because:','It reports what Darwin wrote in a past work with backshift applied.','["It uses direct quotation marks","It reports what Darwin wrote in a past work with backshift applied.","It describes a fact, not a claim","The verb ''argue'' signals free indirect discourse"]','Past simple + "argued" for specific historical past publication.','medium'),
  (cid,46,200,'gap_fill','[TOEFL Reading] "The author _____ (suggest) that the findings _____ (have) broad implications for educational policy." Best forms for a current publication?','suggests / have',NULL,'Present simple for citing current author + no backshift for current relevant claim.','hard'),

  -- BLOCK 47: TOEFL Speaking
  (cid,47,201,'production','[TOEFL Speaking — 45s] A reading and a lecture disagree. The reading argues that screen time harms children''s development. The lecture suggests that content quality matters more than time. Report both views.','',NULL,'The reading argues that excessive screen time is harmful to children''s cognitive and social development, citing studies that found correlations between heavy device use and reduced attention spans and poorer social skills. However, the lecture challenges this interpretation. The professor suggests that the reading conflates all screen time without distinguishing between different types of content. She noted that educational content, when appropriately managed, can have demonstrably positive effects on language development and problem-solving skills. The professor contended that parents and educators should focus on what children are watching rather than how long, urging researchers to abandon simplistic ''more is worse'' conclusions in favor of more nuanced content-focused analyses.','hard'),
  (cid,47,202,'production','[TOEFL Speaking — 45s] Report what a professor said about academic integrity. Use: warned, reminded, urged, acknowledged, told, asked, said, noted.','',NULL,'The professor began by noting that academic integrity forms the foundation of university life. She reminded students that all submitted work must be their own and that any use of external sources must be properly cited. She warned the class that plagiarism detection software would be applied to all submissions and that penalties for misconduct could include course failure or expulsion. When a student asked whether collaboration on assignments was permitted, the professor acknowledged that group work was encouraged for specific tasks but told students to check the guidelines for each individual assignment. She urged everyone to contact her before the deadline if they were uncertain rather than risk a violation.','hard'),

  -- BLOCK 48: TOEFL Writing
  (cid,48,203,'production','[TOEFL Writing — 150 words] Write an academic paragraph synthesizing three perspectives on immigration policy. Use a variety of reporting verbs: argue, contend, suggest, maintain, acknowledge, warn, note, point out.','',NULL,'Scholars adopt strikingly different normative positions on immigration policy. Economists such as Freeman (2006) argue that immigration generates substantial net benefits for receiving economies through increased labor supply, innovation, and consumer demand. Sociologists, however, contend that economic analyses systematically undervalue the social and cultural costs of rapid demographic change, noting that host communities may experience significant disruption to established social norms and institutions. A third perspective, advanced by legal scholars, maintains that the fundamental question is not economic but moral: receiving nations, they suggest, have obligations toward those fleeing poverty or persecution that transcend narrow cost-benefit calculations. Critics of this position acknowledge its moral force but warn that open-borders policies may generate political backlash that ultimately produces more restrictive and less humane outcomes than managed reform would achieve.','hard'),
  (cid,48,204,'production','[TOEFL Writing — Error Correction] Fix reported speech errors in academic writing: "Smith (2019) argued that natural selection plays (correct — no fix needed) a central role. The author said me that the findings were inconclusive. Chen (2021) reported that the drug has been effective in early trials. The committee told that additional evidence was required. Researchers warned of the risks of the policy (correct — no fix needed)."','',NULL,'Smith argued that... plays = correct (no backshift for still-valid truth); said me → told me (''say'' doesn''t take indirect object; use ''tell me''); has been effective → had been effective (backshift from present perfect to past perfect in reported speech); told that → told the committee that / said that (''tell'' requires an indirect object; use ''said that'' if no object); warned of the risks = correct.','hard'),

  -- BLOCK 49: Consolidação final
  (cid,49,205,'production','[TOEFL Writing — 200 words] Write a literature review paragraph on the relationship between poverty and crime using: argued, found, demonstrated, suggested, acknowledged, noted, reported, contended — with appropriate tenses and backshift.','',NULL,'The relationship between poverty and crime has attracted sustained scholarly attention for decades. Early criminologists such as Merton (1938) argued that criminal behavior emerged when individuals lacked legitimate means to achieve socially sanctioned goals, a theory that placed material deprivation at the center of deviant behavior. Subsequent empirical work largely supported this view: Sampson and Laub (1993) demonstrated that neighborhood-level poverty was a significant predictor of juvenile delinquency even when individual-level factors were controlled for. More recently, however, several scholars have contended that the relationship is not straightforwardly causal. Hsieh and Pugh (1993) found that income inequality, rather than absolute poverty, is the stronger predictor of violent crime rates across jurisdictions. Commentators have also noted that poverty reduction programs do not automatically translate into crime reduction, suggesting that social disconnection, institutional distrust, and exposure to violence operate as independent risk factors. Researchers have reported that communities with strong social cohesion and institutional resources often maintain low crime rates even under conditions of significant material deprivation, challenging purely economic explanations.','hard'),
  (cid,49,206,'production','[TOEFL Writing — 200 words] Essay body paragraph: "Governments should be transparent about their environmental data." Report multiple stakeholder positions using different reporting verbs and tenses.','',NULL,'Environmental advocates have long argued that governments are obligated to make environmental monitoring data publicly available, contending that citizens have a fundamental right to know about threats to the air, water, and land they depend upon. Industry representatives, however, have frequently maintained that mandatory disclosure requirements impose unreasonable compliance costs, particularly on small and medium enterprises. Legal scholars have noted that in many jurisdictions, freedom of information legislation already theoretically guarantees public access to government data, but they have also acknowledged that the practical barriers — complex application procedures, long response times, and frequent exemption claims — significantly limit effective access. Scientists working in the field of environmental health have repeatedly warned that delayed or incomplete data disclosure allows pollution problems to worsen before protective action is taken, with the heaviest health burdens typically falling on lower-income communities with the least political influence. A growing consensus in the policy literature suggests that proactive, real-time, machine-readable disclosure — rather than reactive provision following individual requests — represents the minimum acceptable standard for environmental accountability in the twenty-first century.','hard'),
  (cid,49,207,'production','[TOEFL Writing — 200 words] Integrated task: A lecture challenges a reading about the effectiveness of online therapy. The reading claims online therapy is as effective as face-to-face treatment. The professor argues that measurement tools used in online studies are inadequate. Report both positions accurately.','',NULL,'The reading claims that online therapy produces outcomes equivalent to face-to-face treatment, citing a meta-analysis that found no statistically significant difference in symptom reduction between the two modalities. The professor, however, argues that this conclusion rests on a problematic methodological foundation. She contended that the standardized symptom checklists typically used to measure outcomes in online therapy studies were originally validated for in-person clinical settings and may not accurately capture the full therapeutic experience in digital environments. The professor noted that non-verbal cues — which therapists rely upon to assess patient wellbeing — are significantly diminished in video-based sessions, and she suggested that current measurement tools therefore systematically underestimate the differences between the modalities. She acknowledged that online therapy may be genuinely effective for certain populations and conditions but warned against drawing the blanket conclusion that digital delivery is interchangeable with in-person treatment across all clinical contexts. The professor urged that new measurement instruments, specifically designed to capture the digital therapeutic relationship, be developed and validated before such equivalence claims can be responsibly made.','hard'),
  (cid,49,208,'production','[TOEFL Speaking — 60s] Describe a time someone gave you important advice. Report what they said and how it affected you. Use a variety of reporting verbs.','',NULL,'My academic supervisor gave me advice at a critical point in my graduate research that fundamentally changed my approach. She noted that I was spending too much time on theoretical frameworks and not enough on the empirical work that would actually support my argument. She suggested that I restructure my research design so that the data collection phase began earlier in the process. She also reminded me that a dissertation is an argument, not an encyclopedia, and told me to focus on one well-developed claim rather than attempting to cover every relevant issue. I acknowledged at the time that I had been avoiding the fieldwork because I found it more challenging than the library research, and she warned me that this avoidance would ultimately cost me significant time at the revision stage. Following her advice changed the entire trajectory of my project.','hard'),
  (cid,49,209,'gap_fill','The professor _____ (point out) that the sample size _____ (be) too small to support the generalizations the authors _____ (draw).','pointed out / was / had drawn',NULL,'Reported speech: past simple + backshift + past perfect for prior action.','hard'),
  (cid,49,210,'multiple_choice','Which academic reporting verb is MOST neutral (neither positive nor critical)?','The authors noted that further research is needed.','["The authors conceded that further research is needed (implies giving in to a critique).","The authors insisted that further research is needed (implies defensiveness).","The authors noted that further research is needed.","The authors admitted that further research is needed (implies reluctant acknowledgment)."]','"Note" = neutral report of an observation, without emotional or evaluative loading.','medium')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
