-- ============================================================
-- SEED EXT 5: Módulo 03 — Past Simple (ex 236-300) — FINAL
-- Consolidação: PS em narrativa acadêmica, TOEFL avançado
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'past-simple';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo past-simple não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 51: PS em seções de métodos
  (cid,51,236,'gap_fill','The study _____ (employ) a cross-sectional design and _____ (recruit) participants through stratified random sampling.','employed / recruited',NULL,'Methods PS: past simple for completed study design.','easy'),
  (cid,51,237,'gap_fill','Data _____ (collect/passive) between March and September 2022 using validated self-report questionnaires.','were collected',NULL,'Methods passive past for data collection procedure.','easy'),
  (cid,51,238,'gap_fill','Participants _____ (complete) a 30-minute online survey and _____ (receive) a small financial incentive upon completion.','completed / received',NULL,'Methods PS for participant tasks and compensation.','easy'),
  (cid,51,239,'multiple_choice','Which methods section sentence uses past simple MOST effectively?','Semi-structured interviews were conducted with 18 participants, each lasting approximately 90 minutes.','[''Semi-structured interviews are conducted with 18 participants.'',''Semi-structured interviews were being conducted with 18 participants.'',''Semi-structured interviews were conducted with 18 participants, each lasting approximately 90 minutes.'',''Semi-structured interviews have been conducted with 18 participants.'']','Past simple passive for completed data collection procedure.','easy'),
  (cid,51,240,'gap_fill','Statistical analyses _____ (perform/passive) using R version 4.2, and significance _____ (set/passive) at α = 0.05.','were performed / was set',NULL,'Methods PS passive for statistical procedures.','medium'),

  -- BLOCK 52: PS em resultados
  (cid,52,241,'gap_fill','The intervention group _____ (show) significantly greater improvement than the control group (t(142) = 3.47, p < .001).','showed',NULL,'Results PS for between-group comparison.','easy'),
  (cid,52,242,'gap_fill','No statistically significant differences _____ (observe/passive) between groups on baseline measures.','were observed',NULL,'Results PS passive for null finding.','easy'),
  (cid,52,243,'gap_fill','Post-hoc analyses _____ (reveal) that the effect _____ (concentrate/passive) primarily in the youngest age cohort.','revealed / was concentrated',NULL,'Results PS for post-hoc findings.','medium'),
  (cid,52,244,'multiple_choice','Why is past simple used in results sections rather than present simple?','Because the results were obtained at a specific point in time (the study).','[''Present simple is correct for results sections'',''Because results are not general truths — they are specific to this study'',''Because results were obtained at a specific point in time (the study).'',''Because past simple is always more formal'']','Results = time-specific findings → past simple. General truths (discussion section) → present.','hard'),
  (cid,52,245,'gap_fill','In total, 73% of respondents _____ (report) that they _____ (experience) significant stress during the examination period.','reported / had experienced / experienced',NULL,'Results PS for survey findings.','medium'),

  -- BLOCK 53: PS em discussão vs presente
  (cid,53,246,'multiple_choice','In which section of a research paper are BOTH past simple and present simple typically used?','The discussion section — past for study-specific findings, present for general truths.','[''The introduction — always present'',''The methods — always past'',''The discussion section — past for study-specific findings, present for general truths.'',''The abstract — always present'']','Discussion = ''this study found that X (past) / this suggests that Y (present).''','hard'),
  (cid,53,247,'gap_fill','This study _____ (find) that social support _____ (significantly/moderate) the relationship between stress and burnout — a finding that _____ (align) with previous research.','found / significantly moderated / aligns',NULL,'Discussion: PS for this study''s findings + PS for alignment with ongoing literature.','hard'),
  (cid,53,248,'gap_fill','The results _____ (not/support) the original hypothesis, which _____ (predict) a positive correlation between X and Y.','did not support / predicted',NULL,'Discussion PS: specific study result + specific hypothesis.','medium'),
  (cid,53,249,'multiple_choice','Which discussion sentence correctly uses both PS and present simple?','This study demonstrated that early intervention reduces dropout rates, which suggests that policy investment at this stage may be particularly cost-effective.','[''This study demonstrates that early intervention reduced dropout rates, which suggest investment may be cost-effective.'',''This study demonstrated that early intervention reduces dropout rates, which suggests that policy investment at this stage may be particularly cost-effective.'',''This study demonstrated that early intervention has reduced dropout rates, which suggested cost-effectiveness.'',''This study has demonstrated that early intervention reduced dropout rates, which suggests cost-effectiveness.'']','PS for study finding + PS for general implication = standard discussion logic.','hard'),

  -- BLOCK 54: PS em narrativa histórica — nível TOEFL
  (cid,54,250,'production','[TOEFL Writing — 150 words] Write a paragraph about the Green Revolution using: past simple (×5), past passive (×3), past perfect (×1), irregular verbs (led/grew/brought/spread).','',NULL,'The Green Revolution, which transformed global agriculture in the 1960s and 1970s, arose from a deliberate program of scientific innovation funded primarily by the Rockefeller and Ford Foundations. Plant breeders developed high-yielding varieties of wheat, rice, and maize that had been engineered to respond dramatically to artificial fertilizers and irrigation. These varieties spread rapidly across South and Southeast Asia, and food production grew at a pace that surprised even the scientists who had designed the program. Mexico, India, and the Philippines substantially increased their agricultural output within a single decade, and millions of people who had faced the prospect of famine were fed. New irrigation infrastructure was constructed, rural credit markets expanded, and agricultural extension services brought knowledge of the new techniques to farming communities. The program led to significant reductions in food insecurity and child mortality.','hard'),
  (cid,54,251,'production','[TOEFL Writing — 150 words] Write a paragraph about Mendel''s genetic discoveries. Use: past simple, past passive, literary present for Mendel''s theoretical claims, time markers.','',NULL,'Gregor Mendel, an Augustinian friar working in Brno in the 1860s, conducted a series of meticulous experiments with pea plants that laid the foundation for modern genetics. Over seven years, he grew approximately 29,000 plants and recorded the inheritance of seven distinct traits across multiple generations. His data revealed consistent mathematical ratios — notably the 3:1 ratio in second-generation offspring — that led him to propose the existence of discrete hereditary factors, which scientists later named genes. Mendel argues in his 1866 paper that inheritance is not a blending process but a particulate one, with each parent contributing distinct factors that retain their identity across generations. His work was published but largely ignored for decades; it was not rediscovered and appreciated until 1900, when three independent researchers arrived at similar conclusions and found that Mendel had preceded them by thirty-five years.','hard'),
  (cid,54,252,'production','[TOEFL Speaking — 45s] Describe a past scientific experiment and what researchers learned. Use past simple and past perfect.','',NULL,'In the 1950s, Stanley Miller and Harold Urey conducted an experiment that became one of the most famous in the history of biology. They simulated what they believed were the conditions of early Earth — a mixture of water, methane, ammonia, and hydrogen — and ran electric sparks through the system to represent lightning. Within a week, the mixture had turned brown, and when they analyzed its contents, they found that amino acids had formed spontaneously. This discovery suggested that the basic chemical building blocks of life could arise naturally under the conditions thought to have existed on the early Earth. The experiment transformed scientific thinking about the origin of life and opened an entirely new field of research into prebiotic chemistry.','hard'),

  -- BLOCK 55: TOEFL Reading — PS em contexto
  (cid,55,253,'multiple_choice','[TOEFL Reading] ''The Great Depression devastated the global economy, leaving millions unemployed and eroding confidence in market self-regulation.'' Past simple is used because:','The Depression is a completed historical event.','[''Depression is a universal truth'',''The passage is informal'',''The Depression is a completed historical event.'',''Past simple is required after ''global'''']','Historical event with clear end point → past simple.','easy'),
  (cid,55,254,'gap_fill','[TOEFL Reading] ''The Industrial Revolution _____ (begin) in Britain in the mid-eighteenth century and _____ (gradually/spread) to Continental Europe and North America.'' Best forms?','began / gradually spread',NULL,'Historical sequence: past simple for both verbs.','easy'),
  (cid,55,255,'multiple_choice','[TOEFL Reading] In the sentence ''Copernicus proposed that the sun, not the Earth, stood at the center of the solar system,'' the past simple ''proposed'' indicates:','That Copernicus made this proposal at a specific historical point in time.','[''The proposal is not currently accepted'',''The proposal was incorrect'',''That Copernicus made this proposal at a specific historical point in time.'',''The proposal was already known before Copernicus'']','Past simple for historical intellectual contribution.','easy'),
  (cid,55,256,'gap_fill','[TOEFL Reading] ''Early researchers _____ (attribute) the phenomenon to environmental factors; later work _____ (demonstrate) a strong genetic component.'' Best forms?','attributed / demonstrated',NULL,'Historical sequence: attributed → demonstrated (past simple, sequential).','easy'),

  -- BLOCK 56: TOEFL Speaking — narração de história pessoal
  (cid,56,257,'production','[TOEFL Speaking — 45s] Describe a significant learning experience using past simple narrative structure.','',NULL,'The experience that taught me the most about resilience came during my third year of university, when I submitted what I believed was my best essay to date and received a failing grade. I read the professor''s comments three times in disbelief before I accepted what they said — that I had misunderstood the central question and argued in a completely different direction. I went back to the original prompt, read it again carefully, and realized that the professor was right. I rewrote the entire essay from scratch in forty-eight hours, this time addressing the question directly. When the revised version came back with a high distinction, the contrast taught me something that no amount of prior success could have: that understanding the question is more important than the quality of the writing that answers the wrong one.','hard'),
  (cid,56,258,'production','[TOEFL Speaking — 45s] Summarize the development of the internet from 1969 to today using past simple and passive past.','',NULL,'The internet originated in 1969 as ARPANET, a US military research network that connected four university computers. In the following decades, the network expanded beyond the military into academic institutions, and new protocols were developed that standardized how data was transmitted. The World Wide Web was invented by Tim Berners-Lee in 1989 and was opened to the public in 1991, making the internet accessible to non-technical users for the first time. Through the 1990s, commercial internet services exploded in number, and browsers such as Netscape were released that allowed ordinary users to navigate the Web visually. Social media platforms emerged in the early 2000s, smartphones were introduced from 2007 onward, and together these developments turned the internet from a specialized tool into an infrastructure on which most economic and social activity now depends.','hard'),

  -- BLOCK 57: Consolidação — mixed review final
  (cid,57,259,'multiple_choice','Which sentence contains a TENSE ERROR?','Scientists have discovered penicillin in 1928.','[''Fleming discovered penicillin in 1928 (past simple + date = correct).'',''Penicillin was discovered in 1928 (past passive + date = correct).'',''Scientists have discovered penicillin in 1928.'',''The discovery of penicillin transformed medicine (past simple for historical impact = correct).'']','''Have discovered'' + specific year (1928) = error. Use past simple with dates.','easy'),
  (cid,57,260,'gap_fill','The conflict _____ (break out) in 1914, _____ (last) four years, and _____ (claim) more than 17 million lives before an armistice _____ (sign/passive) in November 1918.','broke out / lasted / claimed / was signed',NULL,'Historical sequence: four past simple verbs + passive.','medium'),
  (cid,57,261,'multiple_choice','Which set of verbs is CORRECTLY conjugated in the past simple?','arose, bound, fled, froze, shone, shrunk, strode, swore.','[''arised, bound, fleed, freezed, shone, shrank, strided, swore'',''arose, bound, fled, froze, shone, shrunk, strode, swore.'',''arised, bounded, fled, froze, shined, shrunk, strode, sworn'',''arose, bound, fled, froze, shone, shrunked, strode, sworn'']','All irregular past forms: arose/bound/fled/froze/shone/shrunk/strode/swore.','hard'),
  (cid,57,262,'production','[TOEFL Writing — 200 words] Write a paragraph about the space race and its technological legacy. Use past simple (×5), past passive (×3), past perfect (×1), time markers, irregular verbs.','',NULL,'The space race between the United States and the Soviet Union began in earnest in 1957 when Sputnik — the first artificial satellite — was launched by the Soviet Union into orbit around the Earth. The shock of this achievement drove the US Congress to substantially increase investment in science education and aerospace research, fearing that the Soviets had surpassed American technological capabilities. NASA was established in 1958, and within just eleven years, the US landed astronauts on the moon — a feat that was watched live by an estimated 600 million people worldwide. Beyond its symbolic significance, the space race produced technologies that transformed civilian life: satellite communications, weather forecasting, GPS navigation, and materials used in medical devices and consumer electronics all emerged directly from aerospace research programs. The miniaturization of computing technology required to fit navigation systems into spacecraft drove advances that eventually led to the personal computer and, decades later, the smartphone. Few public investment programs in history generated such extensive technological spillovers across so many sectors of the economy.','hard'),
  (cid,57,263,'production','[TOEFL Writing — 200 words] Write a paragraph about the Enlightenment and its political legacy. Use: past simple, past perfect, literary present for key Enlightenment thinkers, passive past.','',NULL,'The Enlightenment — the intellectual movement that swept Europe during the seventeenth and eighteenth centuries — fundamentally transformed the philosophical foundations of political thought. Thinkers such as Locke, Voltaire, Rousseau, and Montesquieu challenged the traditional justifications of monarchy and aristocratic privilege, proposing instead that legitimate government derives from the consent of the governed. Locke argues in his Second Treatise that individuals possess natural rights to life, liberty, and property that no government may legitimately violate, a claim that profoundly influenced both the American Declaration of Independence and the French Declaration of the Rights of Man. Rousseau, meanwhile, contends that the social contract requires each individual to surrender particular interests in exchange for the protection of the general will — a concept that proved deeply influential on subsequent democratic and socialist thought alike. These ideas did not emerge in isolation: they drew on scientific advances that had demonstrated the capacity of human reason to explain natural phenomena without appeal to theological authority. The political revolutions that followed — in America in 1776 and France in 1789 — were not caused by Enlightenment thought alone, but they were substantially shaped by its concepts.','hard'),

  -- BLOCK 58: Final 5 exercícios
  (cid,58,264,'gap_fill','The committee _____ (deliberate) for three hours before it _____ (reach) a unanimous decision.','deliberated / reached',NULL,'Past simple sequence for formal decision-making.','easy'),
  (cid,58,265,'multiple_choice','Final mixed review: Which sentence uses BOTH past simple and past perfect correctly?','By the time the vaccine was approved, researchers had conducted more than 30,000 clinical trials.','[''By the time the vaccine is approved, researchers had conducted 30,000 trials (mixed tense error).'',''By the time the vaccine was approved, researchers had conducted more than 30,000 clinical trials.'',''By the time the vaccine was approved, researchers conducted more than 30,000 clinical trials (no past perfect — also possible but less precise).'',''By the time the vaccine was approved, researchers were conducting more than 30,000 clinical trials.'']','''By the time + PS + PP'' = standard structure for prior completion.','medium'),
  (cid,58,266,'production','[TOEFL Speaking — 60s] Describe the key developments in the history of vaccines using past simple, past passive, and past perfect.','',NULL,'The history of vaccines begins with Edward Jenner, who in 1796 demonstrated that inoculation with cowpox material conferred protection against the far more dangerous smallpox virus. Jenner had observed that milkmaids who contracted cowpox rarely developed smallpox, and his experiment provided the first empirical evidence that controlled exposure to a less virulent pathogen could produce lasting immunity. Over the following century, Louis Pasteur extended this principle to other diseases: his vaccines against chicken cholera, anthrax, and rabies were developed in the 1880s using attenuated live bacteria. By the early twentieth century, vaccine development had become a central activity of government public health programs, and diphtheria, tetanus, and pertussis vaccines were introduced into mass use. The greatest achievement came in 1980, when the World Health Organization announced that smallpox had been eradicated — the first human disease to be eliminated through vaccination. The COVID-19 pandemic produced mRNA vaccines in record time, drawing on decades of fundamental research that had been conducted in academic laboratories without any immediate commercial application.','hard'),
  (cid,58,267,'gap_fill','The research _____ (commence) in January, _____ (proceed) without major delays, and _____ (conclude) ahead of schedule in November of the same year.','commenced / proceeded / concluded',NULL,'PS sequence for completed research timeline.','easy'),
  (cid,58,268,'production','[TOEFL Writing — 200 words] Write a body paragraph on colonialism and its economic legacy. Use: past simple (×5), past passive (×3), past perfect (×1), and present simple (×2) to show lasting effects.','',NULL,'European colonialism structured the economies of colonized territories in ways that served metropolitan interests rather than the developmental needs of local populations. Colonial powers extracted raw materials — minerals, agricultural commodities, timber — that were shipped to European factories for processing, ensuring that the economic value added by manufacturing remained within the imperial system. Infrastructure was built, but it was designed primarily to facilitate resource extraction rather than to connect economic centers within colonized territories; railway lines, for example, typically ran from interior mining regions to coastal ports rather than between cities. Local industries that might have competed with European manufacturers were suppressed through tariff policies and trade restrictions. By the time formal independence was achieved — for most African nations in the 1960s, for many Asian nations in the late 1940s and 1950s — the structural conditions for sustained industrial development had not been established. The legacy of this arrangement persists: many formerly colonized countries remain dependent on commodity exports, making their economies vulnerable to global price volatility in ways that were not inevitable but were deliberately constructed. Development economists today recognize that understanding colonial economic history is essential to explaining contemporary patterns of inequality.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
