-- ============================================================
-- SEED EXT 2: Módulo 17 — Non-Defining Clauses (exercícios 71-165)
-- Novos tópicos: preposition + which, clause = which/which means,
-- non-defining in academic writing, error correction, TOEFL
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'non-defining-clauses';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo non-defining-clauses não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 11: preposition + which in non-defining clauses
  (cid,11,71,'gap_fill','The treaty, under _____ the participating nations agreed to reduce emissions, was signed in 1997.','which',NULL,'"Under which" = formal prepositional relative clause replacing "under it."','hard'),
  (cid,11,72,'multiple_choice','Which sentence uses a prepositional non-defining clause correctly?','The mechanism, by which nutrients are transported, has been studied for decades.','["The mechanism, by that nutrients are transported, has been studied.","The mechanism, by which nutrients are transported, has been studied for decades.","The mechanism, which by nutrients are transported, has been studied.","The mechanism by which nutrients are transported, has been studied."]','Preposition + which in non-defining clause (commas required).','hard'),
  (cid,11,73,'gap_fill','The committee, for _____ this report was prepared, meets quarterly to review progress.','which',NULL,'"For which" = formal prepositional relative clause. "This report was prepared for it" → for which.','hard'),
  (cid,11,74,'gap_fill','The laboratory, in _____ the Nobel Prize-winning research was conducted, is being renovated.','which',NULL,'"In which" = formal relative for location in non-defining clause.','hard'),
  (cid,11,75,'multiple_choice','Formal version of: "The policy, which we spent three years developing it, has now been implemented."','The policy, on which we spent three years, has now been implemented.','["The policy, on that we spent three years, has now been implemented.","The policy, which we spent three years developing, has now been implemented. (no pronoun repetition)","The policy, on which we spent three years, has now been implemented.","The policy, which we developed it, has now been implemented."]','Preposition + which or relative clause without pronoun repetition.','hard'),
  (cid,11,76,'gap_fill','The criteria, against _____ all submissions are evaluated, are published on the website.','which',NULL,'"Against which" = evaluative prepositional relative.','hard'),
  (cid,11,77,'multiple_choice','Which is correct? "The period, ___ economic inequality reached its peak, lasted nearly a decade."','during which','["during that","during who","during which","during what"]','"During which" = formal temporal relative preposition.','hard'),

  -- BLOCK 12: clause-modifying which (referring to whole sentence)
  (cid,12,78,'gap_fill','The funding was withdrawn, _____ (which) forced the team to abandon the project.','which',NULL,'"Which" can refer to the entire preceding clause: the withdrawal of funding forced them to abandon it.','hard'),
  (cid,12,79,'multiple_choice','In the sentence "She missed the deadline, which surprised everyone," "which" refers to:','The entire event of her missing the deadline.','["The deadline","She","Her punctuality","The entire event of her missing the deadline."]','"Which" here = anaphoric reference to the whole previous clause.','hard'),
  (cid,12,80,'gap_fill','The results exceeded all expectations, _____ (which) means the theory may be correct.','which',NULL,'"Which means" = the entire situation led to this conclusion.','medium'),
  (cid,12,81,'multiple_choice','Which sentence correctly uses "which" to refer to a whole clause?','The government increased tuition fees, which led to widespread protests.','["The government increased tuition fees, which fee increase led to protests.","The government increased tuition fees, that led to widespread protests.","The government increased tuition fees, which led to widespread protests.","The government increased tuition fees, what led to widespread protests."]','"Which" refers to the whole situation (the fee increase), not just "tuition fees."','hard'),
  (cid,12,82,'gap_fill','The study found no significant correlation, _____ (which) suggests that the hypothesis needs revision.','which',NULL,'"Which suggests" = comment on the finding as a whole.','medium'),
  (cid,12,83,'multiple_choice','The phrase "which makes it one of the most important discoveries of the decade" refers to:','The entire discovery described in the preceding clause.','["A specific noun in the previous sentence","The decade","The entire discovery described in the preceding clause.","The researchers"]','"Which makes it" = refers back to the complete situation.','medium'),
  (cid,12,84,'gap_fill','Three independent teams confirmed the result, _____ (which) strengthens confidence in its validity.','which',NULL,'"Which strengthens confidence" = comment on the combined confirmation.','medium'),

  -- BLOCK 13: non-defining clauses in academic writing
  (cid,13,85,'multiple_choice','[Academic] Which sentence uses a non-defining clause most effectively?','The double-blind method, which eliminates observer bias, is considered the gold standard in clinical trials.','["The double-blind method that eliminates observer bias is the gold standard (defining — no commas).","The double-blind method, which eliminates observer bias, is considered the gold standard in clinical trials.","The double-blind method, that eliminates observer bias, is the gold standard (that with commas = wrong).","The double-blind method which eliminates observer bias is the gold standard (no commas = defining)."]','Non-defining clause (commas + which) adds crucial explanatory information.','hard'),
  (cid,13,86,'gap_fill','The participants, _____ ranged in age from 18 to 65, were drawn from three metropolitan areas.','who',NULL,'Non-defining clause about participants (people) → who.','easy'),
  (cid,13,87,'multiple_choice','Why do academic writers prefer non-defining relative clauses over separate sentences?','They allow writers to embed additional information concisely within a single, complex sentence.','["They are shorter","They avoid punctuation errors","They allow writers to embed additional information concisely within a single, complex sentence.","They are required by academic style guides"]','Non-defining clauses = compact, sophisticated embedding of supplementary information.','hard'),
  (cid,13,88,'gap_fill','The control group, _____ received no treatment, showed no improvement over the trial period.','which',NULL,'Non-defining clause about a group (thing) → which.','easy'),
  (cid,13,89,'multiple_choice','Which version of this sentence is most appropriate for academic writing?','The Kyoto Protocol, which was adopted in 1997, set binding targets for greenhouse gas reduction.','["The Kyoto Protocol was adopted in 1997. It set binding targets for greenhouse gas reduction.","The Kyoto Protocol that was adopted in 1997 set binding targets for greenhouse gas reduction.","The Kyoto Protocol, which was adopted in 1997, set binding targets for greenhouse gas reduction.","The Kyoto Protocol (1997) set binding targets and it was adopted that year for greenhouse gas reduction."]','Non-defining relative clause elegantly embeds historical context.','hard'),
  (cid,13,90,'gap_fill','The findings, _____ are discussed in detail in Chapter 4, have significant policy implications.','which',NULL,'Non-defining clause adds cross-reference information (discussed in Chapter 4).','medium'),

  -- BLOCK 14: error correction
  (cid,14,91,'multiple_choice','Find the error: "Shakespeare, that wrote Hamlet, is the most widely studied author in the English canon."','That should be who (non-defining clause requires who for people, not that).','["Shakespeare should be singular","wrote should be written","That should be who (non-defining clause requires who for people, not that).","studied should be studying"]','"That" cannot be used in non-defining relative clauses.','medium'),
  (cid,14,92,'gap_fill','Correct the error: "The Eiffel Tower, that was built by Gustave Eiffel, stands 330 meters tall." Fix: "The Eiffel Tower, _____ was built by Gustave Eiffel, stands 330 meters tall."','which',NULL,'"That" cannot be used in non-defining relative clauses — replace with "which."','easy'),
  (cid,14,93,'multiple_choice','Which sentence has a punctuation error?','The Amazon rainforest which covers over 5 million km² is vital for global biodiversity.','["The Amazon rainforest, which covers over 5 million km², is vital for global biodiversity.","Professor James, who has published 30 papers, is retiring next year.","The experiment, which lasted six months, produced unexpected results.","The Amazon rainforest which covers over 5 million km² is vital for global biodiversity."]','Non-defining clauses REQUIRE commas. "The Amazon rainforest which covers..." is missing commas.','medium'),
  (cid,14,94,'gap_fill','Error: "My colleague, who research I cited in my paper, will present at the conference." Fix: "My colleague, _____ research I cited in my paper, will present at the conference."','whose',NULL,'"Whose research" = possessive relative pronoun. Not "who research."','hard'),
  (cid,14,95,'multiple_choice','Which sentence is correctly punctuated and uses the right pronoun?','The Mediterranean diet, which has been linked to longevity, is popular in Southern Europe.','["The Mediterranean diet that has been linked to longevity is popular in Southern Europe (defining).","The Mediterranean diet, that has been linked to longevity, is popular in Southern Europe (wrong pronoun).","The Mediterranean diet, which has been linked to longevity, is popular in Southern Europe.","The Mediterranean diet which has been linked to longevity is popular in Southern Europe (no commas — defining)."]','Correct: commas + which = non-defining.','medium'),
  (cid,14,96,'gap_fill','Error correction: "The study, that was published last month, has already been cited 50 times." Corrected: "The study, _____ was published last month, has already been cited 50 times."','which',NULL,'Non-defining clause: "which" replaces "that" (which cannot be used with commas).','easy'),

  -- BLOCK 15: TOEFL Reading
  (cid,15,97,'multiple_choice','[TOEFL Reading] "The placebo effect, which has been documented in hundreds of studies, remains poorly understood." The non-defining clause does what?','Adds background information confirming the phenomenon is well-established.','["Identifies which placebo effect is being discussed","Adds background information confirming the phenomenon is well-established.","Restricts the meaning to a specific type of placebo effect","Introduces a contrast with other effects"]','Non-defining clause = adds supporting context, not a defining restriction.','medium'),
  (cid,15,98,'gap_fill','[TOEFL Reading] "The discovery of DNA''s structure, _____ occurred in 1953, transformed modern biology." Best pronoun?','which',NULL,'"Which" for a thing/event in non-defining clause.','easy'),
  (cid,15,99,'multiple_choice','[TOEFL Reading] "Watson and Crick, who built on earlier work by Rosalind Franklin, proposed the double helix model in 1953." The non-defining clause:','Provides additional historical context about the researchers'' methods.','["Identifies which Watson and Crick","Provides additional historical context about the researchers'' methods.","Restricts the meaning to those who built on Franklin''s work","Introduces a contrasting view"]','Non-defining clause = adds context, not identification.','medium'),
  (cid,15,100,'gap_fill','[TOEFL Reading] "The Industrial Revolution, _____ transformed Western economies between 1760 and 1840, also led to significant environmental degradation." Best pronoun?','which',NULL,'"Which" in non-defining clause for an event.','easy'),
  (cid,15,101,'multiple_choice','[TOEFL Reading] In the sentence "The researchers, whose methodology has since been criticized, reported a 40% reduction in symptoms," "whose" refers to:','The methodology belonging to the researchers.','["The symptoms","The reduction","The methodology belonging to the researchers.","The researchers themselves"]','"Whose" = possessive relative pronoun. The researchers''s methodology.','medium'),

  -- BLOCK 16: TOEFL Speaking production
  (cid,16,102,'production','[TOEFL Speaking — 45s] Describe three people or organizations important in your field. Use a non-defining relative clause (who/which/whose) for each one. Include one sentence where "which" refers to a whole clause.','',NULL,'Marie Curie, who won two Nobel Prizes in different sciences, remains the most celebrated female scientist in history. The WHO, which coordinates global health responses, played a critical role during the COVID-19 pandemic. Professor Lin, whose research on renewable energy has transformed the field, will deliver the keynote speech at the conference next month. Three new treatments were approved last year, which represents the fastest approval cycle in the history of the agency.','hard'),
  (cid,16,103,'production','[TOEFL Speaking — 45s] A new study claims that multitasking reduces productivity. Summarize the claim and supporting evidence using non-defining clauses for the study, the researchers, and the key findings.','',NULL,'A recent study, which was published in the Journal of Cognitive Psychology, found that multitasking significantly impairs performance on complex tasks. The researchers, who conducted experiments on 300 university students, reported a 40% decrease in accuracy when participants switched between tasks. The control group, which completed tasks sequentially, performed significantly better. These findings, which align with previous research, suggest that single-tasking strategies should be encouraged in educational settings.','hard'),

  -- BLOCK 17: TOEFL Writing production
  (cid,17,104,'production','[TOEFL Writing] Write 5 sentences about climate change using 5 different non-defining relative clause structures: (1) who, (2) which (non-defining), (3) whose, (4) where, (5) which referring to a whole clause.','',NULL,'Scientists, who have been monitoring global temperatures since the 1950s, report an unprecedented rate of warming. The Paris Agreement, which was signed by 196 countries in 2015, set targets for limiting warming to 1.5°C. The IPCC, whose reports have shaped global climate policy, releases updated assessments every five years. Island nations, where sea level rise poses an existential threat, are among the most vocal advocates for immediate action. Several major economies pledged to reach net-zero emissions by 2050, which represents a significant but still insufficient commitment.','hard'),
  (cid,17,105,'production','[TOEFL Writing — Error Correction] Fix all relative clause errors: "Albert Einstein, that developed the theory of relativity, is the most famous scientist of the 20th century. The vaccine, who was developed in record time, saved millions of lives. Climate change, which is a serious problem, its effects are felt worldwide. The committee met last week. That led to a new policy announcement."','',NULL,'that → who (person, non-defining); who → which (thing/vaccine, non-defining); remove "its effects are" — clause already modifies "climate change"; "That led..." → ...which led to a new policy announcement (combine with previous sentence using clause-referencing which).','hard'),
  (cid,17,106,'production','[TOEFL Writing — 200 words] Write an academic paragraph about artificial intelligence using at least 4 non-defining relative clauses with different relative pronouns (who, which [thing], whose, which [whole-clause reference]), and one prepositional non-defining clause (by which / in which / for which). Underline each non-defining clause.','',NULL,'Artificial intelligence, which has evolved from a theoretical concept into a practical technology over the past two decades, is reshaping virtually every sector of the global economy. Researchers, who once regarded human-level AI performance as decades away, are now grappling with systems that match or exceed expert performance on specific tasks. The field of natural language processing, in which progress has been particularly rapid, has produced tools capable of generating coherent, contextually appropriate text. Companies such as DeepMind and OpenAI, whose systems have demonstrated remarkable performance on academic benchmarks, are raising fundamental questions about the nature of intelligence. AI has begun to outperform radiologists in detecting certain cancers, which represents a turning point in the relationship between technology and healthcare. Policymakers are now racing to develop regulatory frameworks for which there are no established precedents, making international cooperation on AI governance an urgent global priority.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
