-- ============================================================
-- SEED EXT 5: Módulo 05 — Future Simple (ex 177-248)
-- Novos tópicos: future em projeções científicas e econômicas,
-- future perfeito/contínuo em TOEFL essays, future em policy
-- analysis, periphrastic futures avançados
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'future-simple';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo future-simple não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 51: Future em projeções científicas e econômicas
  (cid,51,177,'gap_fill','Under current trajectories, global temperatures _____ (exceed) 1.5°C of warming by _____ (late) 2030s, _____ (triggering) impacts that _____ (difficult/reverse).','will exceed / the late / triggering / will be difficult to reverse / will be increasingly difficult to reverse',NULL,'Future projection + participial result + future for consequence.','easy'),
  (cid,51,178,'gap_fill','Economic modelers project that sub-Saharan Africa _____ (account) for approximately 25% of the global population by 2050, _____ (making) it the most demographically significant region for _____ (assess) future global economic trends.','will account / making / assessing',NULL,'Future projection + participial result + gerund for purpose.','medium'),
  (cid,51,179,'gap_fill','If current deforestation rates _____ (not/reduce/passive), the Amazon basin _____ (no longer/function) as a carbon sink by the 2040s and _____ (potentially/become) a net carbon source.','are not reduced / will no longer function / will potentially become',NULL,'Type 1 conditional + double future consequence for environmental tipping point.','hard'),
  (cid,51,180,'multiple_choice','Which future sentence BEST conveys a high-confidence scientific projection?','According to current modeling, Arctic sea ice will essentially disappear in summer within three to four decades.','["Arctic sea ice might disappear in summer within three to four decades.","Arctic sea ice is disappearing in summer within three to four decades.","According to current modeling, Arctic sea ice will essentially disappear in summer within three to four decades.","Arctic sea ice shall disappear in summer within three to four decades."]','''Will disappear'' = high-confidence prediction based on models. ''Might'' = lower confidence.','easy'),
  (cid,51,181,'gap_fill','Demographic projections _____ (indicate) that the working-age population in several European countries _____ (decline) significantly over _____ next three decades, _____ (create) fiscal pressures on _____ pension and healthcare systems that _____ (require) structural reform.','indicate / will decline / the / creating / the / will require',NULL,'Present projections + future trends + participial consequences + future obligation.','hard'),

  -- BLOCK 52: Future perfeito em projeções acadêmicas
  (cid,52,182,'gap_fill','By 2030, most OECD countries _____ (transition/passive) from coal power and _____ (install/passive) sufficient renewable capacity to _____ (generate) more than 60% of _____ electricity from clean sources.','will have transitioned / will have installed / generate / their',NULL,'Future perfect for projected completed transition by a specified date.','medium'),
  (cid,52,183,'gap_fill','By _____ time the current generation of students _____ (enter) the labor market, automation _____ (transform/passive) the occupational landscape sufficiently _____ (make) some of _____ fastest-growing occupations today _____ (obsolete/render/passive) and _____ (create/passive) others that _____ (not/yet/conceive/passive).','the / enters / will have transformed / to make / the / have been rendered / created / have not yet been conceived',NULL,'Future perfect for projected completed transformation by time clause.','hard'),
  (cid,52,184,'multiple_choice','Which future perfect sentence is MOST APPROPRIATE in a policy paper?','By the end of the planning period, the government will have invested over $50 billion in infrastructure renewal.','["By the end of the planning period, the government will invest over $50 billion in infrastructure renewal.","By the end of the planning period, the government will have invested over $50 billion in infrastructure renewal.","By the end of the planning period, the government invested over $50 billion in infrastructure renewal.","By the end of the planning period, the government would have invested over $50 billion in infrastructure renewal."]','Future perfect ''will have invested'' = action projected to be completed by a future point (end of planning period).','easy'),
  (cid,52,185,'gap_fill','If the reforms _____ (implement/passive) as planned, the country _____ (reduce) its debt-to-GDP ratio significantly by 2035 and _____ (restore/passive) _____ access to international capital markets at sustainable interest rates.','are implemented / will have reduced / will have been restored / its',NULL,'Type 1 conditional + future perfect for projected completed outcomes.','hard'),

  -- BLOCK 53: Future contínuo em planejamento e policy
  (cid,53,186,'gap_fill','Throughout the next decade, the central bank _____ (monitor) inflationary pressures closely and _____ (adjust) its interest rate stance as conditions evolve.','will be monitoring / will be adjusting',NULL,'Future continuous for planned sustained activity over a period.','easy'),
  (cid,53,187,'gap_fill','As the reform program _____ (roll out) over the next three years, stakeholders _____ (observe) its effects carefully, and analysts _____ (assess) whether the projected efficiency gains _____ (materialize).','rolls out / will be observing / will be assessing / will materialize / are materializing',NULL,'PC for co-occurring scheduled process + future continuous for sustained observation.','medium'),
  (cid,53,188,'multiple_choice','What does future continuous communicate in ''The committee will be reviewing submissions until March 15th''?','A process that will be ongoing continuously from now until the deadline.','["A sudden future action","A process that will be ongoing continuously from now until the deadline.","A completed future action","A habitual future action"]','Future continuous = ongoing, continuous process during a specified future period.','easy'),
  (cid,53,189,'gap_fill','At this time next year, researchers _____ (conduct) _____ follow-up data collection phase, and by _____ end of _____ year they _____ (analyze) _____ preliminary results.','will be conducting / the / the / the / will be analyzing / the',NULL,'Future continuous for ongoing activity at a future point in time.','medium'),

  -- BLOCK 54: Periphrastic futures avançados
  (cid,54,190,'gap_fill','The new regulations _____ (due/come) into force on January 1st, at _____ point all affected entities _____ (required) _____ (demonstrate) compliance or _____ (face) significant penalties.','are due to come / which / will be required / to demonstrate / will face',NULL,'''Due to come'' = scheduled periphrastic future + ''will be required/will face.''','hard'),
  (cid,54,191,'gap_fill','The minister''s announcement _____ (set) to _____ (clarify) the government''s position on _____ issue that _____ (dominate) _____ policy debate for _____ past six months.','is set to / clarify / an / has dominated / the / the',NULL,'''Is set to clarify'' = periphrastic future (planned/expected) + PP for context.','hard'),
  (cid,54,192,'multiple_choice','Which periphrastic future BEST conveys a near-certain commitment in formal English?','The commission is to publish its final recommendations by the end of the year.','["The commission will publish its recommendations by the end of the year.","The commission might publish its recommendations by the end of the year.","The commission is to publish its final recommendations by the end of the year.","The commission is going to publish its recommendations by the end of the year."]','''Is to publish'' = official/formal obligation or strong plan (most formal). ''Will'' = simple future. ''Is going to'' = informal planned.','hard'),
  (cid,54,193,'gap_fill','Production capacity _____ (expect/passive) _____ (double) by 2030, _____ (buoyed) by both public investment and _____ (increase/passive) private sector confidence _____ (follow) the regulatory reform.','is expected to / double / buoyed / increased / following',NULL,'''Is expected to double'' = epistemic passive periphrastic future.','hard'),
  (cid,54,194,'gap_fill','Given _____ current pace of innovation, it _____ (not/long/be) before _____ (emerge/passive) technologies _____ (make) current approaches _____ (obsolete) and _____ (require) _____ wholesale redesign of _____ sector.','the / will not be long / emerging / make / obsolete / require / a / the',NULL,'''It will not be long before'' + PC (emerging) + make + adjective = near-future expectation.','hard'),

  -- BLOCK 55: TOEFL Reading avançado com future
  (cid,55,195,'multiple_choice','[TOEFL Reading] ''Under the baseline scenario, emissions will continue to rise through 2035 before beginning to decline.'' The future ''will continue'' suggests:','A projection based on current policies, presented as a likely outcome under defined conditions.','["An absolute certainty","A projection based on current policies, presented as a likely outcome under defined conditions.","A desired outcome","A past trend that will repeat"]','''Under the baseline scenario'' + ''will continue'' = conditional projection, not absolute certainty.','medium'),
  (cid,55,196,'gap_fill','[TOEFL Reading] ''If investment in preventive care _____ (increase/passive), long-term healthcare costs _____ (almost/certainly/fall) and _____ (improve/passive) will population health outcomes.'' Best forms?','is increased / will almost certainly fall / will be improved',NULL,'Type 1 conditional + future with high-confidence adverb (''almost certainly'').','medium'),
  (cid,55,197,'multiple_choice','[TOEFL Reading] ''By 2050, the world will have experienced a dramatic shift in the demographic center of gravity.'' What does ''will have experienced'' communicate?','A shift that will be completed (having occurred fully) by the year 2050.','["A shift happening exactly in 2050","A shift that will be completed (having occurred fully) by the year 2050.","A shift that began in 2050","A shift that might happen in 2050"]','Future perfect: completed by a future reference point (2050).','medium'),

  -- BLOCK 56: TOEFL Speaking avançado com future
  (cid,56,198,'production','[TOEFL Speaking — 45s] A reading makes predictions about the future of work. Summarize using future tenses.','',NULL,'The reading presents a set of predictions about how the future of work will evolve over the next two decades as automation and artificial intelligence continue to transform the occupational landscape. According to the reading, approximately one-third of current jobs will be substantially automated by 2040, and the workers whose roles will be most affected are those in routine clerical, manufacturing, and transportation occupations. The reading projects that new forms of employment will emerge in areas where human judgment, creativity, and interpersonal skills remain difficult to automate — including healthcare, education, creative industries, and complex services. The reading also predicts that the nature of careers will change fundamentally: most workers will be changing roles more frequently, continuously retraining, and moving between employed and self-employed status multiple times during their working lives. The reading concludes that education systems will need to adapt significantly to prepare students for this environment, shifting emphasis from knowledge acquisition toward the development of adaptable capabilities, and that social protection systems will need to be redesigned to provide security for workers whose career paths will be more fragmented than those of previous generations.','hard'),
  (cid,56,199,'production','[TOEFL Speaking — 45s] Discuss what will happen to biodiversity over the next century. Use varied future tenses throughout.','',NULL,'The trajectory of global biodiversity over the next century will depend critically on the policy choices made in the next two decades, and the range of plausible outcomes is very wide. Under current trajectories, extinction rates will continue to exceed their natural background rate by a factor of one hundred or more, and major ecosystems — tropical rainforests, coral reefs, and Arctic tundra — will undergo transformations whose scale will have no precedent in the period of human civilization. By mid-century, if current deforestation and climate change trajectories are not altered, many species will have been pushed to extinction or onto very small ranges from which recovery will be extremely difficult. However, there is also reason for cautious optimism: if current investment in protected area expansion is maintained and accelerated, if the most destructive agricultural and fishing practices are reformed, and if climate change is stabilized at lower levels of warming, many of the most catastrophic outcomes can still be avoided. Conservation biology has shown that ecological recovery is possible: habitats that have been degraded can be restored, and species whose populations have declined can recover if the pressures threatening them are adequately reduced. The outcome over the next century will be determined by choices that societies are making right now.','hard'),

  -- BLOCK 57: TOEFL Writing avançado com future
  (cid,57,200,'production','[TOEFL Writing — 200 words] Write a paragraph on the future of cities using varied future tenses.','',NULL,'The cities of the mid-twenty-first century will differ from those of today in several fundamental respects, and understanding the directions of transformation is essential for making the investment and governance decisions that will determine whether these changes serve broad human flourishing or exacerbate existing inequalities. Urban populations will continue to grow, with most of the net increase concentrated in cities in Asia and sub-Saharan Africa; by 2050, approximately two-thirds of humanity will be urban, and the cities that will house this population are in many cases still being built or have not yet been designed. The physical infrastructure of cities will be transformed by the progressive electrification of transportation, with electric vehicles and improved public transit systems replacing fossil-fuel-powered private cars in most urban centers over the coming decades. Buildings will be significantly more energy-efficient, powered increasingly by on-site renewable generation and connected to smart grids that will balance supply and demand in real time. The spatial organization of cities will also be evolving, as the shift to remote and hybrid work reduces the primacy of central business districts and creates opportunities for more distributed, polycentric urban forms. Whether these changes will have improved the sustainability and liveability of cities or widened the gaps between those who benefit from urban innovation and those who do not will depend substantially on the governance choices made in the coming decade.','hard'),
  (cid,57,201,'production','[TOEFL Writing — 200 words] Write a paragraph on the future of international trade using varied future tenses.','',NULL,'The architecture of international trade is undergoing changes that will shape economic relationships for decades to come, and predicting the precise trajectory is complicated by the interaction of technological, geopolitical, and policy variables that are themselves rapidly evolving. The long trend toward deeper trade integration will not simply continue: the ''decoupling'' of certain technology supply chains between major powers is already underway and will almost certainly deepen, with the semiconductor industry in particular being restructured in ways that will have significant consequences for the geography of global manufacturing. Digital trade will continue to grow rapidly as services, data, and intellectual property become increasingly significant components of cross-border economic exchange, though the regulatory frameworks for digital trade are still being negotiated and will shape the distribution of gains substantially. The transition to a low-carbon economy will also reshape trade flows, as carbon-intensive production methods become increasingly subject to carbon border adjustments and as the geography of energy production shifts away from oil and gas exporters toward countries with abundant solar and wind resources. Countries and companies that position themselves effectively for these transitions will be better placed to benefit from the emerging trade environment; those that do not adapt will face increasing challenges maintaining their competitiveness in export markets that are already changing faster than trade governance is adapting.','hard'),

  -- BLOCK 58: Final
  (cid,58,202,'production','[TOEFL Writing — 200 words] Write a conclusion on AI development using varied future tenses throughout.','',NULL,'The trajectory of artificial intelligence development over the coming decade will have implications that extend far beyond the technology sector, reaching into the foundations of labor markets, governance systems, and the cognitive tools through which humanity understands itself and the world. The systems that will be deployed at scale over this period will be significantly more capable than those available today, and the range of tasks they will be able to perform will expand into areas that current assessments may still underestimate. By the end of the decade, AI will have transformed the practice of medicine, legal services, education, scientific research, and creative industries in ways that will require new professional norms, regulatory frameworks, and educational pathways. The distribution of the gains from AI advancement will be determined not by the technology itself but by the governance choices that societies are making now: whether intellectual property frameworks will distribute returns to innovation broadly or allow them to concentrate in a small number of firms; whether education systems will equip most workers with the capabilities needed to work productively alongside AI tools; and whether regulatory frameworks will ensure that AI systems deployed in consequential domains are safe, accurate, and accountable. These choices will have been made — for better or worse — before the full consequences of advanced AI are apparent, which is precisely why they are so important to get right.','hard'),
  (cid,58,203,'production','[TOEFL Speaking — 60s] What will the healthcare system look like in 2050? Use varied future tenses throughout.','',NULL,'Healthcare in 2050 will have been transformed by a convergence of technological, demographic, and social changes that are already underway, and projecting its likely features requires attending to both the opportunities and the risks that this transformation will create. By mid-century, genomic medicine will have become a routine component of preventive care: genetic profiling at birth will allow the identification of disease predispositions decades before symptoms emerge, enabling interventions that will have reduced the incidence of many conditions that currently cause significant morbidity. AI diagnostic tools will be routinely assisting clinicians in interpreting imaging, pathology, and multi-omic data at a level of accuracy and comprehensiveness that current radiologists and pathologists will not be able to match alone. Wearable sensors will be continuously monitoring a range of physiological parameters and generating real-time alerts that will allow early intervention for conditions ranging from cardiac arrhythmias to mental health crises. Drug development will be proceeding significantly faster than today as AI tools accelerate the identification and testing of promising therapeutic candidates. However, several challenges that are already visible will also have intensified: the ageing population will be placing unprecedented demand on healthcare capacity; antimicrobial resistance will have rendered many currently effective antibiotics obsolete unless major investments in alternatives are made; and the equity implications of expensive personalized medicine will have become more rather than less acute if access is not deliberately structured into the system from the outset.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
