-- ============================================================
-- SEED EXT 6: Módulo 13 — Reported Speech (ex 251-300)
-- Blocos 59-64 | 50 exercícios
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'reported-speech';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo reported-speech não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 59: RS in TOEFL Reading (8 ex)
  (cid,59,251,'multiple_choice','In TOEFL Reading, ''The author contends that deforestation accelerates climate change.'' What does this sentence do?','It reports the author''s position using academic RS in the present tense.','["It quotes the author directly","It reports the author''s position using academic RS in the present tense.","It proves that deforestation causes climate change","It disagrees with the author''s view"]','Academic RS uses present tense (''contends'') to report textual claims that remain valid.','easy'),
  (cid,59,252,'gap_fill','[TOEFL Reading] The passage states that early astronomers _____ (believe/past RS) that the Earth _____ (be/RS) the center of the universe, a view that _____ (challenge/passive/eventually/RS) by Copernicus.','believed / was / was eventually challenged',NULL,'RS backshift: ''believe'' → ''believed''; ''is'' → ''was''; ''challenge'' → passive ''was challenged.''','medium'),
  (cid,59,253,'gap_fill','[TOEFL Reading] The researcher reported that the experiment _____ (conduct/passive/past perfect RS) under controlled conditions and that the results _____ (replicate/passive/past perfect RS) three times.','had been conducted / had been replicated',NULL,'Backshift to past perfect passive: ''was conducted'' → ''had been conducted''; ''has been replicated'' → ''had been replicated.''','hard'),
  (cid,59,254,'multiple_choice','[TOEFL Reading] ''Darwin suggested that species might evolve gradually through natural selection.'' The modal ''might'' here indicates:','Backshifted modal from ''may'' in the original speech, expressing tentative hypothesis.','["Darwin was uncertain about his own theory","Backshifted modal from ''may'' in the original speech, expressing tentative hypothesis.","Darwin was wrong about natural selection","''Might'' is present tense in this context"]','''May'' → ''might'' = modal backshift in RS. Darwin''s original claim used ''may''; RS shifts it to ''might.''','medium'),
  (cid,59,255,'gap_fill','[TOEFL Reading] The study found that participants who _____ (receive/past perfect RS) the treatment _____ (show/past perfect RS) greater improvement than those who _____ (not/receive/past perfect RS) it.','had received / had shown / had not received',NULL,'Backshift to past perfect for all verbs: ''received'' → ''had received''; ''showed'' → ''had shown.''','hard'),
  (cid,59,256,'gap_fill','[TOEFL Reading] According to the author, the policy _____ (implement/passive/past RS) without adequate consultation, which _____ (mean/past RS) that key stakeholders _____ (not/include/passive/past perfect RS) in the decision-making process.','was implemented / meant / had not been included',NULL,'Sequence of backshifted tenses in academic RS: passive past, past simple, past perfect passive.','hard'),
  (cid,59,257,'multiple_choice','[TOEFL Reading] Which sentence correctly uses RS to paraphrase a TOEFL reading passage?','Smith argues that urban populations require significantly more public green space to maintain well-being.','["Smith is arguing urban populations will need more green space","Smith argued that urban populations will require more green space","Smith argues that urban populations require significantly more public green space to maintain well-being.","Smith had argued urban populations needed more green space for well-being"]','''Argues'' (present RS for ongoing scholarly claims) + accurate paraphrase without backshift = correct academic RS.','easy'),
  (cid,59,258,'gap_fill','[TOEFL Reading] The passage explains that while early researchers _____ (assume/past RS) that memory _____ (be/past RS) a single system, later studies _____ (reveal/past RS) that it _____ (comprise/past RS) multiple distinct components.','assumed / was / revealed / comprised',NULL,'Consistent backshift throughout: present → past simple for all verbs in RS narrative.','medium'),

  -- BLOCK 60: Complex tense sequences in RS (8 ex)
  (cid,60,259,'gap_fill','The professor explained that if the government _____ (increase/past RS) funding, research productivity _____ (might/improve) — but she added that the evidence _____ (suggest/past RS) that funding alone _____ (not/be/past RS) sufficient.','increased / might improve / suggested / was not',NULL,'RS conditional: ''increases'' → ''increased''; modal ''might'' stays; backshift ''suggests'' → ''suggested.''','hard'),
  (cid,60,260,'gap_fill','The historian noted that the treaty _____ (sign/passive/past perfect RS) under duress and that many of the signatories _____ (not/understand/past perfect RS) the long-term consequences of what they _____ (agree/past perfect RS) to.','had been signed / had not understood / had agreed',NULL,'Past perfect RS for events prior to the moment of reporting: sign, understand, agree → past perfect.','hard'),
  (cid,60,261,'gap_fill','She said that she _____ (study/continuous RS) the question for years and _____ (become/past perfect RS) increasingly convinced that the prevailing explanation _____ (be/past RS) inadequate.','had been studying / had become / was',NULL,'RS tense sequence: past perfect continuous (''had been studying''), past perfect (''had become''), past simple (''was'').','hard'),
  (cid,60,262,'gap_fill','The committee reported that the data _____ (analyze/passive/past perfect RS) by three independent teams, that no errors _____ (find/passive/past perfect RS), and that the conclusions _____ (appear/past RS) robust.','had been analyzed / had been found / appeared',NULL,'Three parallel RS verbs in sequence: past perfect passive x2 + past simple.','hard'),
  (cid,60,263,'multiple_choice','Which sentence correctly maintains tense sequence in RS?','He explained that the experiment had been repeated and that the results had confirmed the original findings.','["He explained that the experiment was repeated and results confirmed the original findings.","He explains that the experiment had been repeated and results had confirmed the findings.","He explained that the experiment had been repeated and that the results had confirmed the original findings.","He explained that the experiment has been repeated and results have confirmed the findings."]','Option C: consistent past perfect (''had been repeated,'' ''had confirmed'') = correct backshift of present perfect to past perfect.','medium'),
  (cid,60,264,'gap_fill','The speaker claimed that unless governments _____ (act/past RS) immediately, the window of opportunity _____ (would/close/passive/RS), and that by 2050 many of the changes _____ (would/be/irreversible/RS).','acted / would be closed / would be irreversible',NULL,'RS conditional: ''act'' → ''acted'' (if-clause); future ''will close'' → ''would be closed''; ''will be'' → ''would be.''','hard'),
  (cid,60,265,'gap_fill','The economist argued that the crisis _____ (occur/past RS) because policymakers _____ (fail/past perfect RS) to heed warnings that researchers _____ (issue/past perfect RS) years earlier, and that similar failures _____ (be/likely to/past RS) recur.','occurred / had failed / had issued / were likely to',NULL,'RS narrative: simple past for main event + past perfect for earlier events + past simple for ongoing tendency.','hard'),
  (cid,60,266,'multiple_choice','[TOEFL Reading] ''The scientist noted that the findings confirmed what had long been suspected.'' What is the original direct statement?','These findings confirm what has long been suspected.','["These findings will confirm what was long suspected.","These findings confirmed what had long been suspected.","These findings confirm what has long been suspected.","These findings have confirmed what was long suspected."]','''Noted'' (past RS verb) → backshift reversal: ''confirmed'' → ''confirm''; ''had long been suspected'' → ''has long been suspected.''','medium'),

  -- BLOCK 61: RS with modal verbs — advanced (8 ex)
  (cid,61,267,'gap_fill','The advisor suggested that students _____ (should/consider) the long-term implications of their choices and _____ (might/want) to consult the guidelines before _____ (submit/gerund) their applications.','should consider / might want / submitting',NULL,'''Should'' stays as ''should'' in RS (no backshift); ''might'' stays; gerund unchanged.','medium'),
  (cid,61,268,'gap_fill','The report warned that the situation _____ (could/deteriorate) rapidly if action _____ (not/take/passive/past RS) and that additional resources _____ (would/need/passive) to be mobilized within weeks.','could deteriorate / was not taken / would need',NULL,'''Could'' stays in RS; ''is not taken'' → ''was not taken'' (backshift); ''will need'' → ''would need.''','hard'),
  (cid,61,269,'multiple_choice','Which sentence correctly reports ''You must submit the form by Friday''?','He insisted that she had to submit the form by Friday.','["He insisted she submits the form by Friday.","He insisted that she should have submitted the form by Friday.","He insisted that she had to submit the form by Friday.","He insisted she will submit the form by Friday."]','''Must'' → ''had to'' is the standard backshift for past RS of obligation; ''must'' can also stay if the obligation is still current.','hard'),
  (cid,61,270,'gap_fill','The expert warned that the technology _____ (might/pose) significant risks that _____ (not/fully/understand/passive/past RS) and that regulatory frameworks _____ (would/need) to evolve rapidly to _____ (address) them.','might pose / were not fully understood / would need / address',NULL,'''Might'' stays; ''are not fully understood'' → ''were not fully understood'' (backshift); ''will need'' → ''would need.''','hard'),
  (cid,61,271,'gap_fill','She mentioned that the proposal _____ (could/prove) controversial, that opposition _____ (might/emerge), and that the committee _____ (should/prepare) for a difficult debate.','could prove / might emerge / should prepare',NULL,'Modal verbs ''could,'' ''might,'' ''should'' remain unchanged in RS when already past-compatible.','medium'),
  (cid,61,272,'gap_fill','[TOEFL Reading] The policy document stated that governments _____ (must/ensure) that benefits _____ (distribute/passive/present) equitably, though it _____ (acknowledge/past RS) that _____ (achieve/gerund) this _____ (would/require) significant institutional reform.','must ensure / are distributed / acknowledged / achieving / would require',NULL,'''Must'' stays (ongoing obligation); present passive ''are distributed'' stays (general truth); ''would require'' = RS modal.','hard'),
  (cid,61,273,'multiple_choice','[TOEFL Reading] ''The study suggested that intervention X might reduce dropout rates by 20%.'' What does this tell us?','Intervention X''s effect was presented as possible, not certain.','["The study proved dropout rates fell by 20%","Intervention X is the best dropout reduction strategy","Intervention X''s effect was presented as possible, not certain.","The 20% reduction has been confirmed by other studies"]','''Suggested that...might'' = double epistemic hedging; the study proposed a possible relationship without claiming certainty.','easy'),
  (cid,61,274,'gap_fill','The speaker emphasized that while current data _____ (be/past RS) promising, more research _____ (would/need/passive) before firm conclusions _____ (could/draw/passive), and that premature conclusions _____ (might/do) more harm than good.','was / would be needed / could be drawn / might do',NULL,'Consistent RS modals: ''was'' (backshift); ''would be needed'' and ''could be drawn'' (modal passives in RS); ''might do'' unchanged.','hard'),

  -- BLOCK 62: RS in academic writing — citation and synthesis (8 ex)
  (cid,62,275,'gap_fill','[Academic Writing] When synthesizing sources, you should introduce each author''s claim with a precise _____ (report → noun) verb and then _____ (indicate) your own evaluative _____ (stance) toward it.','reporting / indicate / stance',NULL,'Academic synthesis RS: reporting verb + author''s claim + evaluative stance of the writer.','easy'),
  (cid,62,276,'multiple_choice','[Academic Writing] Which sentence BEST synthesizes two opposing scholars using RS?','While Jones argues that globalization reduces inequality, Smith contends that it exacerbates existing disparities, and the empirical evidence reviewed here supports the latter view.','["Jones says globalization reduces inequality but Smith says it makes things worse.","While Jones argues that globalization reduces inequality, Smith contends that it exacerbates existing disparities, and the empirical evidence reviewed here supports the latter view.","Jones argued globalization reduces inequality and Smith argued it makes things worse.","Jones and Smith have different views about globalization and inequality."]','Option B: ''argues'' + ''contends'' (present RS for ongoing positions); ''empirical evidence...supports'' = writer''s evaluative stance; academic register throughout.','hard'),
  (cid,62,277,'gap_fill','[Academic Writing] In an essay body paragraph, after you _____ (report) a scholar''s claim, you should _____ (evaluate) it, _____ (provide) supporting or contradictory evidence, and _____ (link) it explicitly to your thesis.','report / evaluate / provide / link',NULL,'Academic RS paragraph structure: report → evaluate → evidence → link to thesis.','easy'),
  (cid,62,278,'gap_fill','[Academic Writing] Smith (2018) _____ (argue/present) that institutional trust is declining, while Brown (2020) _____ (suggest/present) that the picture is more nuanced, _____ (find/gerund) that trust varies significantly by demographic group.','argues / suggests / finding',NULL,'Academic RS: present tense (''argues,'' ''suggests'') for ongoing scholarly positions; ''finding'' = participial clause for methodology.','medium'),
  (cid,62,279,'multiple_choice','[Academic Writing] Which citation pattern correctly integrates RS into a TOEFL essay?','As Chen and Liu (2021) demonstrate, urban density correlates positively with innovation output when controlling for human capital.','["Chen and Liu (2021) said that urban density correlates with innovation.","As Chen and Liu (2021) demonstrate, urban density correlates positively with innovation output when controlling for human capital.","Chen and Liu (2021) demonstrated urban density correlates positively with innovation.","According to Chen and Liu (2021), it was shown that urban density correlates with innovation output."]','Option B: ''demonstrate'' (strong present RS verb) + ''correlates'' (general truth) + methodological qualifier = full academic RS structure.','medium'),
  (cid,62,280,'gap_fill','[Academic Writing] The meta-analysis _____ (reveal/past RS) that across 47 studies, the intervention _____ (produce/past RS) a statistically significant improvement, though the authors _____ (caution/past RS) that effect sizes _____ (vary/past RS) considerably by population.','revealed / produced / cautioned / varied',NULL,'RS past tense for completed study: ''reveals'' → ''revealed''; ''produces'' → ''produced''; consistent backshift throughout.','medium'),
  (cid,62,281,'gap_fill','[Academic Writing] A common error in academic RS is using _____ (say) instead of a more _____ (precise) reporting verb such as ''argue,'' ''contend,'' ''demonstrate,'' or ''challenge.'' Choosing the right verb _____ (signal/present) the _____ (relation → noun) between the source and the claim.','says / precise / signals / relationship',NULL,'Reporting verb selection: ''say'' is too generic; specific verbs encode the epistemic relationship between scholar and claim.','easy'),
  (cid,62,282,'multiple_choice','[Academic Writing] You are writing a TOEFL essay on urban planning. Which sentence best uses RS to strengthen an argument?','As Jacobs (1961) famously argued, the vitality of urban neighborhoods depends on mixed land use and high pedestrian density, a claim that subsequent empirical research has largely confirmed.','["Jacobs (1961) had some ideas about urban neighborhoods that are interesting.","As Jacobs (1961) famously argued, the vitality of urban neighborhoods depends on mixed land use and high pedestrian density, a claim that subsequent empirical research has largely confirmed.","Jacobs said in 1961 that cities should have mixed land use and pedestrians.","Urban neighborhoods are important, according to Jacobs."]','Option B: strong RS verb (''argued'') + author with date + specific claim + evaluative synthesis (''subsequently confirmed'') = TOEFL-level academic RS.','hard'),

  -- BLOCK 63: RS in TOEFL Speaking (8 ex)
  (cid,63,283,'production','[TOEFL Speaking — 45s] Summarize a reading on biodiversity loss using academic RS throughout.','',NULL,'The reading argues that biodiversity loss represents one of the most serious environmental challenges of the current century. The author contends that habitat destruction is the primary driver of species extinction and suggests that current rates of loss are unprecedented in human history. The passage also maintains that the economic costs of biodiversity loss have been systematically underestimated by conventional economic models. According to the author, meaningful action requires both conservation of existing habitats and restoration of degraded ecosystems, and the author concludes by arguing that international cooperation is essential since biodiversity does not respect national boundaries.','hard'),
  (cid,63,284,'production','[TOEFL Speaking — 45s] A professor challenges the reading on biodiversity. Report both positions using RS.','',NULL,'The reading argues that biodiversity loss is driven primarily by habitat destruction, while the professor suggests that the picture is considerably more complex. She contends that climate change has emerged as an equally important driver of extinction — a factor that she argues the reading''s framework does not adequately incorporate. The professor also challenges the reading''s claim about economic costs, noting that some researchers have found that the costs of biodiversity conservation may exceed its benefits in certain contexts. She concludes by arguing that while the reading raises important concerns, its prescriptions for international cooperation underestimate the political obstacles to effective collective action.','hard'),
  (cid,63,285,'gap_fill','[TOEFL Speaking] ''The professor argues that the reading''s claim about habitat destruction _____ (oversimplify/RS) the issue.'' What tense should the blank be in?','oversimplifies',NULL,'Academic RS: ''argues that...oversimplifies'' = present tense RS for an ongoing scholarly position made in the lecture.','easy'),
  (cid,63,286,'gap_fill','[TOEFL Speaking] In your spoken summary: ''The professor claimed the study _____ (show/past perfect RS) inconclusive results.'' Is this correct? Which tense is needed?','had shown — Yes, correct: past RS (''claimed'') + backshift past simple → past perfect',NULL,'Past RS (''claimed'') triggers backshift: ''showed'' → ''had shown'' = correct tense sequence in RS.','medium'),
  (cid,63,287,'production','[TOEFL Speaking — 60s] Summarize reading and lecture on urban food systems. Reading supports urban farming; professor is skeptical. Use RS throughout.','',NULL,'The reading advocates strongly for urban farming as a solution to food security challenges in rapidly growing cities. The author argues that rooftop gardens and vertical farms can supply a significant proportion of urban food needs while reducing transport emissions and strengthening community bonds. The professor, however, challenges these claims on several grounds. She contends that the reading significantly overstates the productive capacity of urban growing systems, noting that studies suggest urban farming currently supplies less than two percent of food consumed in most large cities. She also argues that the reading fails to account for the high water and energy costs associated with intensive urban agriculture — costs that she suggests may offset the transport savings the reading highlights. The professor acknowledges that urban farming has social and educational value, but maintains that it should not be presented as a serious solution to food security given the limitations of its scale.','hard'),
  (cid,63,288,'gap_fill','[TOEFL Speaking] Complete the transition: ''The reading _____ (claim/present) that solar energy is now cost-competitive with fossil fuels. The professor, however, _____ (dispute/present) this, _____ (argue/gerund) that the comparison _____ (fail/RS) to account for storage and grid integration costs.','claims / disputes / arguing / fails',NULL,'Academic RS: present tense for both reading and professor positions; participial clause (''arguing'') for method of challenge.','medium'),
  (cid,63,289,'multiple_choice','[TOEFL Speaking] Which TOEFL speaking response best uses RS to compare reading and lecture?','The reading argues that remote work increases productivity, while the professor contends that the evidence is mixed and suggests that outcomes vary significantly by industry and job type.','["The reading says remote work is good for productivity but the professor disagrees.","The reading argued that remote work increased productivity, but the professor said evidence was mixed.","The reading argues that remote work increases productivity, while the professor contends that the evidence is mixed and suggests that outcomes vary significantly by industry and job type.","According to the reading, productivity goes up. The professor said no."]','Option C: ''argues'' + ''contends'' + ''suggests'' (academic RS verbs, present tense) + specific content from both sources = TOEFL Band 5 response.','medium'),
  (cid,63,290,'gap_fill','[TOEFL Speaking] Transform using proper academic RS: ''The reading says that cities need more public transport. The professor says urban transport is complicated.'' → ''The reading _____ (argue/present) that cities _____ (require) expanded public transport _____ (infrastructure). The professor, however, _____ (contend/present) that urban transport planning is considerably more complex than the reading _____ (acknowledge/present).''','argues / require / infrastructure / contends / acknowledges',NULL,'Replace ''says'' with specific RS verbs; use present tense; expand content; add adversative connector.','hard'),

  -- BLOCK 64: Capstone production (10 ex)
  (cid,64,291,'production','[TOEFL Writing — 200 words] Write an integrated task response on automation and employment. The reading argues automation creates jobs; the lecture says it destroys them. Use RS throughout.','',NULL,'The reading and the lecture offer fundamentally different assessments of automation''s impact on employment. The reading argues that historical evidence supports an optimistic view: each wave of automation has ultimately created more jobs than it destroyed, as efficiency gains generate new economic activity and new categories of work. The author contends that fears of permanent technological unemployment are inconsistent with the empirical record and reflect misunderstanding of how dynamic labor markets respond to technological change. The professor, by contrast, argues that current AI-driven automation differs fundamentally from previous waves because it can substitute for cognitive as well as physical labor — a combination she contends has no historical precedent. She suggests that the mechanisms by which past automation generated compensating employment may not operate when the technology can perform the creative and analytical tasks in which displaced workers might otherwise find refuge. The professor also challenges the reading''s evidence base, noting that the historical cases it cites involved technologies that complemented human skills rather than substituting for them — a distinction she argues the reading glosses over in its confident projection of past patterns onto a qualitatively different technological moment.','hard'),
  (cid,64,292,'gap_fill','[Final RS] In TOEFL writing, the three most important elements of a good RS sentence are: (1) a precise _____ (report → noun) verb, (2) accurate _____ (represent → noun) of the source''s claim, and (3) appropriate _____ (tense) _____ (sequence).','reporting / representation / tense / sequence',NULL,'The pillars of academic RS: reporting verb precision + claim accuracy + grammatical tense sequence.','easy'),
  (cid,64,293,'gap_fill','[Final RS] Correct the RS error: ''The author said the climate is changing and we need to act.'' → ''The author _____ (argue/present) that the climate _____ (change/present RS) and that _____ (urgent) action _____ (require/passive/RS).''','argues / is changing / urgent / is required',NULL,'Replace ''said'' with ''argues'' (academic RS); use present tense for ongoing scholarly claims; restructure for academic register.','medium'),
  (cid,64,294,'production','[TOEFL Writing — 200 words] Write a body paragraph on immigration policy using RS to report at least three scholarly positions.','',NULL,'The scholarly debate on immigration policy reflects fundamentally different values as well as empirical disagreements. Economists such as Clemens (2011) argue that the welfare gains from eliminating immigration restrictions would dwarf those from eliminating trade barriers, suggesting that immigration policy is one of the most consequential underexamined areas of economic governance. Card (1990) contends that sudden large inflows of low-skilled workers do not depress wages for native workers at comparable skill levels, challenging the intuition that immigration and native employment are in zero-sum competition. Borjas (2003), however, disputes Card''s findings, arguing that when comparison groups are properly defined, immigration does exert downward wage pressure on the lowest-paid native workers — a finding he maintains has important distributional implications that cannot be dismissed even if aggregate effects are positive. Political scientists contribute a different dimension, with Dancygier (2010) demonstrating that political backlash against immigration is mediated by local labor market conditions, housing competition, and the strength of existing ethnic networks. Together, these perspectives suggest that the effects of immigration are highly context-dependent and that blanket generalizations are unlikely to capture the full complexity of the phenomenon.','hard'),
  (cid,64,295,'multiple_choice','[Final RS Review] Which sentence contains an RS error?','The study claims that participants whom received the treatment performed better.','["The professor argues that the reading oversimplifies the relationship between growth and inequality.","The study claims that participants whom received the treatment performed better.","Smith suggests that the causal relationship remains unclear despite decades of research.","The author contends that institutional reform requires both formal and informal dimensions."]','Option B: ''whom'' should be ''who'' (subject of ''received''); additionally, ''claims'' works but ''found'' is more precise for a completed study.','medium'),
  (cid,64,296,'gap_fill','[Final RS] Complete the academic RS sentence: The researcher _____ (conclude/past) that the evidence, while _____ (suggestive), _____ (not/yet/be/past perfect RS) sufficient to _____ (establish) causality and that further _____ (study) _____ (would/require/passive) before _____ (firm) conclusions _____ (could/draw/passive).','concluded / suggestive / had not yet been / establish / study / would be required / firm / could be drawn',NULL,'RS past tense narrative with past perfect (''had not yet been''), modal passives (''would be required,'' ''could be drawn'').','hard'),
  (cid,64,297,'gap_fill','[Final RS] Rewrite using proper academic RS: ''Scientists say that temperatures will rise 2 degrees if emissions are not cut.'' → ''Climate scientists _____ (warn/present) that global temperatures _____ (project/passive/RS) to rise by approximately 2 degrees _____ (unless) emissions _____ (reduce/passive/RS) substantially.''','warn / are projected / unless / are reduced',NULL,'Academic RS: ''warn'' (strong reporting verb); ''are projected to'' (impersonal passive RS); ''unless'' + present passive for conditional.','hard'),
  (cid,64,298,'production','[TOEFL Writing — 200 words] Write a conclusion for a TOEFL essay on the future of higher education. Use RS to report at least two scholarly perspectives and state your own position.','',NULL,'The future of higher education is, as the scholars examined in this essay suggest, a matter of genuine uncertainty on which intelligent analysts disagree. Those in the optimistic camp, like Selingo (2013), argue that technological disruption will ultimately make high-quality education more accessible and affordable, disaggregating the credential, the learning experience, and the social network that universities currently bundle together. Critics such as Bok (2006) counter that this optimistic vision underestimates what is lost when education is reduced to credentialing and skill acquisition, maintaining that the broader developmental and civic purposes of higher education are precisely what democratic societies most need. This essay has argued, consistent with the latter view, that while technological tools offer genuine opportunities to improve pedagogy and expand access, they should be understood as complements to, rather than replacements for, the core educational relationship between teachers and students. The challenge for higher education institutions is not to resist technological change but to ensure that the values justifying public investment in education — critical thinking, civic preparation, and human flourishing — remain central to their mission as they navigate an uncertain future.','hard'),
  (cid,64,299,'gap_fill','[Final RS] Identify and correct all RS errors: ''The professor says that the reading was wrong, that the evidence is mixed and students should of known better.''','The professor argues that the reading is mistaken, that the evidence is mixed, and that students should have known better.',NULL,'Errors: ''says'' → ''argues''; ''was wrong'' → ''is mistaken'' (present for ongoing position); ''should of'' → ''should have'' (modal perfect).','hard'),
  (cid,64,300,'production','[TOEFL Writing — Final capstone] Write a 200-word paragraph on technology and democracy. Use RS to integrate at least three scholarly positions, evaluate them, and state your conclusion.','',NULL,'The relationship between technology and democracy has become one of the defining debates of contemporary political science, and scholars have reached strikingly different conclusions. Optimists such as Shirky (2008) argue that digital communication technology lowers the cost of collective action, enabling citizens to organize more effectively and hold governments accountable in ways that strengthen democratic participation. Morozov (2011), however, contends that this view is naive, arguing instead that authoritarian governments have proven adept at exploiting the same technologies to surveil citizens, spread disinformation, and suppress opposition — a dynamic he suggests has made repression more rather than less effective in the digital age. A third perspective, articulated by Sunstein (2017), focuses on internal democratic dynamics, arguing that algorithmic curation of information creates filter bubbles that deepen political polarization and undermine the shared informational basis that deliberative democracy requires. This essay has argued that all three perspectives capture something real: technology simultaneously enables new forms of democratic participation and new forms of democratic disruption, and the net effect depends heavily on the institutional and regulatory context in which these technologies operate. The policy implication is not technophobia but governance — the question is not whether to use these technologies but how to govern them in the service of democratic values.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
