-- ============================================================
-- SEED EXT 4: Módulo 08 — Past Perfect (ex 138-215)
-- Novos tópicos: PP em narrativa complexa, PP em discurso reportado,
-- PP para prioridade causal, PP passivo, PP em TOEFL avançado
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'past-perfect';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo past-perfect não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 41: PP para prioridade causal em narrativa
  (cid,41,138,'gap_fill','The factory _____ (already/close) by the time the government _____ (announce) the subsidy program.','had already closed / announced',NULL,'PP for prior completed action + PS for later announcement.','easy'),
  (cid,41,139,'gap_fill','The new policy _____ (fail) because the government _____ (not/consult) the affected communities before implementing it.','failed / had not consulted',NULL,'PP causal: PP for earlier omission → PS for resulting failure.','medium'),
  (cid,41,140,'multiple_choice','Which sentence correctly uses past perfect to show CAUSE BEFORE EFFECT?','The bridge collapsed because engineers had ignored early warning signs.','["The bridge collapsed because engineers ignored early warning signs (PS+PS — causal sequence possible but no priority).","The bridge collapsed because engineers had ignored early warning signs.","The bridge had collapsed because engineers ignored early warning signs (PP for collapse is wrong — collapse came after).","The bridge collapsing because engineers had ignored warning signs."]','PP = prior negligence → PS = resulting consequence.','medium'),
  (cid,41,141,'gap_fill','Scientists _____ (not/anticipate) how rapidly the ice sheet _____ (begin) to melt once carbon thresholds _____ (exceed/passive).','had not anticipated / began / were exceeded',NULL,'PP negative + PS for onset + PS passive for threshold crossing.','hard'),
  (cid,41,142,'gap_fill','The patient _____ (already/receive) two courses of antibiotics before doctors _____ (realize) the infection was bacterial-resistant.','had already received / realized',NULL,'PP for prior treatment + PS for later realization.','medium'),

  -- BLOCK 42: PP em discurso reportado (backshift)
  (cid,42,143,'gap_fill','She said she _____ (work) for the organization for ten years and _____ (never/consider) leaving.','had worked / had never considered',NULL,'Backshift in reported speech: PP for had worked + had never considered.','medium'),
  (cid,42,144,'multiple_choice','Which sentence correctly applies past perfect in reported speech?','He told the committee that he had submitted the report the previous Friday.','["He told the committee that he submitted the report the previous Friday (PS — backshift missing).","He told the committee that he had submitted the report the previous Friday.","He told the committee that he has submitted the report the previous Friday (PP in RS — wrong tense).","He told the committee that he would submit the report the previous Friday (wrong modal)."]','Backshift: PS → PP in reported speech when past reporting verb.','medium'),
  (cid,42,145,'gap_fill','Investigators found that the company _____ (hide) evidence for months before the case _____ (come) to court.','had been hiding / came',NULL,'PP continuous for extended hidden activity + PS for court date.','hard'),
  (cid,42,146,'gap_fill','The witness claimed she _____ (not/see) the defendant before that evening, but CCTV footage _____ (show) they _____ (meet) twice.','had not seen / showed / had met',NULL,'PP negative claim + PS for evidence + PP for contradicting prior meetings.','hard'),
  (cid,42,147,'multiple_choice','In reported speech, which original tense usually DOES NOT require backshift with a past reporting verb?','Past simple remains past simple (optionally) when context is already clearly past.','["Present simple always stays present simple","Past simple remains past simple (optionally) when context is already clearly past.","Present perfect always becomes past perfect","Future simple always stays future simple"]','Past simple may optionally stay as PS in RS if no ambiguity, or shift to PP.','hard'),

  -- BLOCK 43: PP passivo em narrativa histórica
  (cid,43,148,'gap_fill','By the time peace negotiations _____ (begin), millions of people _____ (displace/passive) by the conflict.','began / had been displaced',NULL,'PP passive for prior displacement + PS for later negotiations.','medium'),
  (cid,43,149,'gap_fill','The agreement _____ (not/ratify/passive) before the deadline _____ (pass), which _____ (render) it legally invalid.','had not been ratified / passed / rendered',NULL,'PP passive negative + PS for deadline + PS for result.','hard'),
  (cid,43,150,'multiple_choice','Which sentence uses past perfect passive CORRECTLY?','By 1945, most of the continent''s industrial capacity had been destroyed by the war.','["By 1945, most of the continent''s industrial capacity has been destroyed by the war (PP wrong tense).","By 1945, most of the continent''s industrial capacity had been destroyed by the war.","By 1945, most of the continent''s industrial capacity was destroyed by the war (PS — also acceptable but PP shows prior completion).","By 1945, most of the continent''s industrial capacity destroyed by the war."]','"Had been destroyed" = PP passive. "By 1945" = reference point making past-before-past clear.','medium'),
  (cid,43,151,'gap_fill','When the dam _____ (breach), the water that _____ (hold back/passive) for decades _____ (release/passive) in hours.','was breached / had been held back / was released',NULL,'PS for breach event + PP passive for prior retention + PS passive for rapid release.','hard'),
  (cid,43,152,'gap_fill','Investigators _____ (determine) that the fire _____ (start/passive) deliberately and _____ (set/passive) in the early hours of the morning.','determined / had been started / had been set',NULL,'PS for determination + PP passive x2 for earlier criminal acts.','hard'),

  -- BLOCK 44: PP em textos científicos (methods, discussion, background)
  (cid,44,153,'gap_fill','Previous studies _____ (establish) a correlation, but no experiment _____ (yet/test) a direct causal pathway until this study.','had established / had yet tested',NULL,'PP for prior field knowledge + PP negative for missing prior experiment.','hard'),
  (cid,44,154,'multiple_choice','In the background section of a research paper, why is past perfect used?','To show that certain developments occurred before the current study began.','["Because background sections always use past perfect","To show that certain developments occurred before the current study began.","Because past perfect is more formal in background sections","To distinguish ongoing from completed facts"]','Background PP = prior state of knowledge at the time the study was designed.','medium'),
  (cid,44,155,'gap_fill','By the time this study _____ (commence), two competing theoretical frameworks _____ (emerge) in the literature.','commenced / had emerged',NULL,'PP for prior framework development + PS for study start time.','medium'),
  (cid,44,156,'gap_fill','The participants _____ (complete) the intervention and _____ (follow-up/passive) at six months and twelve months after the original assessment _____ (conduct/passive).','had completed / were followed up / was conducted',NULL,'PP for completed intervention + PS passive for follow-up schedule + PS passive for baseline.','hard'),
  (cid,44,157,'gap_fill','Researchers _____ (note) that several earlier studies _____ (rely) on self-reported data without independent validation.','noted / had relied',NULL,'PS for observation + PP for earlier methodological limitation.','medium'),

  -- BLOCK 45: TOEFL Reading
  (cid,45,158,'multiple_choice','[TOEFL Reading] "By the time Columbus reached the Caribbean in 1492, indigenous civilizations had developed complex social, agricultural, and architectural systems over thousands of years." Why is past perfect used?','Because the civilizations'' development preceded Columbus''s arrival.','["Because 1492 is very long ago","Because the civilizations are no longer present","Because the civilizations'' development preceded Columbus''s arrival.","Because past perfect is required after ''by the time''"]','PP after "by the time" = prior development before the reference past point.','easy'),
  (cid,45,159,'gap_fill','[TOEFL Reading] "When archaeologists excavated the site in 1972, they discovered that earlier civilizations _____ (occupy) the land for at least three thousand years." Best form?','had occupied',NULL,'PP for prior occupation before the past discovery event.','easy'),
  (cid,45,160,'multiple_choice','[TOEFL Reading] "The ecosystem had been severely degraded long before environmental protection legislation was introduced." This sentence implies:','The legislation came too late to prevent the degradation.','["The legislation caused the degradation","The legislation protected the ecosystem effectively","The legislation came too late to prevent the degradation.","The degradation is still ongoing"]','PP passive before legislation = the damage predated protection → implication of lateness.','medium'),
  (cid,45,161,'gap_fill','[TOEFL Reading] "By the end of World War I, new military technologies _____ (reshape/passive) warfare in ways that generals _____ (not/foresee) at the conflict''s start." Best forms?','had reshaped / had not foreseen',NULL,'PP passive for prior transformation + PP negative for prior lack of anticipation.','hard'),

  -- BLOCK 46: TOEFL Speaking
  (cid,46,162,'production','[TOEFL Speaking — 45s] A reading describes how a historic policy was introduced. The lecture explains why previous approaches had failed. Summarize using PP for the prior failures.','',NULL,'The reading describes how the introduction of universal healthcare coverage in 1967 transformed health outcomes in the country. The lecture provides essential historical context: the professor explains that previous attempts to expand health coverage had consistently failed, largely because policymakers had underestimated the resistance from the private insurance industry and had not built sufficient political coalitions in advance. By the time the 1967 legislation passed, reformers had learned from these failures: they had negotiated directly with provider groups, had secured endorsements from major employers, and had designed a phased implementation that reduced immediate cost shock. The professor argues that understanding why earlier approaches had not worked is essential to understanding why this one finally succeeded.','hard'),
  (cid,46,163,'production','[TOEFL Speaking — 45s] Describe a past experience where you realized something had gone wrong before you could fix it. Use past perfect for the prior events.','',NULL,'During a research project in my second year, I realized midway through data analysis that I had recorded the responses from two participant groups in the same spreadsheet column — meaning I could not distinguish which responses belonged to which group. By the time I noticed the problem, I had already completed the analysis for three of the five variables. I had kept the data files, so I was able to go back and manually separate the groups, but it cost me nearly two days of additional work. The experience taught me something I had not fully appreciated before: that consistent file labeling and verification protocols at the data collection stage can save enormous amounts of time later.','hard'),

  -- BLOCK 47: TOEFL Writing
  (cid,47,164,'production','[TOEFL Writing — 150 words] Write a background paragraph for a study on urbanization in the 20th century. Use PP (×3), PS (×3), and PS passive (×2).','',NULL,'By the time the twentieth century began, the process of urbanization had already transformed the societies of the industrialized world. In Britain, the first country to industrialize, rural-to-urban migration had proceeded rapidly throughout the nineteenth century, and by 1900, more than half of the population already lived in cities. This pattern had not yet become universal, however: in most of Africa, Asia, and Latin America, the majority of the population remained rural and agricultural. During the twentieth century, urbanization accelerated globally at an unprecedented pace. Between 1950 and 2000, the world''s urban population grew from approximately 750 million to over 2.8 billion people. This growth was driven by a combination of rural poverty, land tenure change, and the pull of real or perceived economic opportunity in cities. New megacities emerged across the developing world, and urban infrastructure was frequently overwhelmed.','hard'),
  (cid,47,165,'production','[TOEFL Writing — Error Correction] Fix PP errors: "By the time the agreement was signed, negotiators spent three years discussing it. She said she finishes the report but the deadline had already passed. The ecosystem degraded before the law was introduced. Scientists discovered that the mechanism existed for centuries."','',NULL,'spent → had spent (PP for prior activity before signing); finishes → had finished (backshift in reported speech: finishes → finished → had finished); degraded → had been degraded / had degraded (PP for degradation before the law); existed → had existed (PP for prior existence before the discovery).','hard'),

  -- BLOCK 48: Consolidação final
  (cid,48,166,'production','[TOEFL Writing — 200 words] Write a discussion paragraph on why a social program succeeded where earlier initiatives had failed. Use PP for prior failures, PS for the new program, and analysis in the present.','',NULL,'The success of the conditional cash transfer program launched in 2003 can only be understood against the background of the approaches that had preceded it. Previous poverty reduction initiatives had typically delivered services in kind — food baskets, school uniforms, medical consultations — rather than cash, reflecting a paternalistic assumption that poor families could not be trusted to allocate resources effectively. These programs had also been poorly targeted: benefits frequently reached households above the poverty line while missing the most vulnerable. The 2003 program departed from these approaches in two critical respects. First, it transferred cash directly to mothers, who research had shown were more likely than fathers to spend incremental income on children''s nutrition, health, and education. Second, it conditioned transfers on specific behaviors — school attendance and regular health checkups — creating positive incentive structures rather than passive dependency. Decades of subsequent research suggest that well-designed conditional cash transfers represent one of the most cost-effective poverty reduction tools available, though critics note that they address symptoms rather than the structural conditions that generate poverty in the first place.','hard'),
  (cid,48,167,'production','[TOEFL Writing — 200 words] Write a body paragraph on how past scientific consensus had been wrong and how it was eventually corrected. Use PP, PS, and present simple.','',NULL,'The history of science contains numerous episodes in which the scientific community had reached confident consensus on propositions that subsequently proved to be wrong, and these episodes offer important lessons about the nature of scientific knowledge and its relationship to institutional authority. For much of the twentieth century, medical authorities maintained that peptic ulcers were caused by excess stomach acid, a lifestyle condition exacerbated by stress and spicy food. This explanation had been accepted without serious challenge for decades, and the treatments it implied — antacids and dietary modification — were widely used but provided only temporary relief. When Barry Marshall and Robin Warren proposed in the early 1980s that ulcers were caused by a bacterium, Helicobacter pylori, they were met with institutional skepticism: the scientific consensus had established that the stomach was too acidic to support bacterial life. Marshall famously drank a solution containing the bacterium to demonstrate its pathogenic potential. Within a decade, the bacterium theory had been accepted, antibiotic treatment was established, and the previous consensus was recognized as a paradigmatic case of prematurely closed scientific inquiry.','hard'),
  (cid,48,168,'production','[TOEFL Speaking — 60s] Describe the historical sequence of events that led to a major discovery or invention. Use PP for events that preceded the breakthrough, PS for the breakthrough itself.','',NULL,'The discovery of DNA''s double helix structure by Watson and Crick in 1953 did not emerge from nothing — it was the culmination of decades of scientific work by many researchers, not all of whom received appropriate credit. By the time Watson and Crick published their model in Nature in April 1953, Rosalind Franklin had already produced remarkably clear X-ray diffraction images of DNA — including the famous Photograph 51, which showed unmistakably that the molecule had a helical structure. Erwin Chargaff had established the rules governing the base composition of DNA: adenine always appeared in equal quantities to thymine, and cytosine always equaled guanine. Linus Pauling had already used X-ray crystallography to determine the alpha-helix structure of proteins, providing a methodological model. What Watson and Crick contributed was the specific spatial arrangement — the double helix with complementary base pairs — that explained how genetic information could be both stored and replicated. The story illustrates how major scientific discoveries typically depend on a foundation of prior work that made the breakthrough possible.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
