-- ============================================================
-- SEED EXT 4: Módulo 06 — Be Going To (ex 135-210)
-- Novos tópicos: BGT vs will avançado, BGT em diferentes registros,
-- BGT passivo, BGT em textos acadêmicos e TOEFL
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'be-going-to';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo be-going-to não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 41: BGT vs Will — decisões versus planos
  (cid,41,135,'multiple_choice','Which sentence shows a PRE-FORMED PLAN (not a spontaneous decision)?','We are going to launch the new product in Q2 — the decision was made last month.','["We''ll launch the new product in Q2 — good idea! (spontaneous)","We are going to launch the new product in Q2 — the decision was made last month.","We might launch the new product in Q2 (uncertain — might)","We launched the new product in Q2 (past — completed)"]','"Be going to" = pre-planned intention. "Will" = spontaneous decision.','easy'),
  (cid,41,136,'gap_fill','A: The server keeps crashing. B: I know. The IT team _____ (look into it) — they have an appointment this afternoon.','is going to look into it',NULL,'"Be going to" = pre-arranged plan for near future.','easy'),
  (cid,41,137,'multiple_choice','What is the key difference between "I''ll open the window" and "I''m going to open the window"?','"I''ll" = spontaneous decision made now. "I''m going to" = plan already formed before speaking.','["There is no difference","''I''ll'' is more formal","''I''ll'' = spontaneous decision made now. ''I''m going to'' = plan already formed before speaking.","''Going to'' is only for negative sentences"]','Will = at the moment of speaking. Be going to = prior plan or intention.','medium'),
  (cid,41,138,'gap_fill','The government _____ (raise) the minimum wage next year — it was in their election manifesto.','is going to raise',NULL,'"Be going to" for previously announced policy plan.','easy'),
  (cid,41,139,'gap_fill','Look at those dark clouds — it _____ (rain). We should head inside.','is going to rain',NULL,'"Be going to" for prediction based on visible present evidence.','easy'),
  (cid,41,140,'multiple_choice','Which sentence uses "be going to" for a PREDICTION BASED ON EVIDENCE?','The patient''s vital signs are deteriorating rapidly — she is going to need emergency intervention.','["The patient might need emergency intervention (uncertain possibility).","The patient will probably need emergency intervention (prediction without evidence).","The patient''s vital signs are deteriorating rapidly — she is going to need emergency intervention.","The patient is needing emergency intervention (wrong — PC for stative)."]','Visible evidence (deteriorating vitals) → "is going to" for imminent predicted outcome.','medium'),

  -- BLOCK 42: BGT em diferentes registros (formal vs informal)
  (cid,42,141,'multiple_choice','In formal academic writing, which future construction is PREFERRED over "be going to"?','Will + base verb or periphrastic forms (is expected to, is due to).','["Is going to (academic writing uses going to freely)","Would + base verb","Will + base verb or periphrastic forms (is expected to, is due to).","Present continuous for all future reference"]','"Be going to" = informal to neutral. Academic writing prefers "will" or "is expected to."','medium'),
  (cid,42,142,'gap_fill','In informal spoken English: "What _____ (you/do) after the meeting?" — formal equivalent?','are you going to do / What will you do / What do you plan to do',NULL,'"Going to" in informal questions. Formal: "will" or "plan to."','medium'),
  (cid,42,143,'gap_fill','The company _____ (not/renew) the lease — they have already started looking for new premises.','is not going to renew',NULL,'"Be going to" negative: is/are + not + going to + base verb.','easy'),
  (cid,42,144,'multiple_choice','Which sentence uses "be going to" INCORRECTLY?','The sun is going to rise tomorrow at 6:15 am.','["I''m going to finish this report before the meeting.","They are going to relocate to Singapore next spring.","The sun is going to rise tomorrow at 6:15 am.","It''s going to be a very hot summer."]','"Will rise" = correct for scheduled, predictable astronomical event. BGT = plans/intentions/evidence-based predictions.','hard'),
  (cid,42,145,'gap_fill','A: Have you booked the flights? B: Yes — we _____ (fly) to Tokyo via Seoul, and we _____ (arrive) on Tuesday morning.','are going to fly / are going to arrive',NULL,'BGT for pre-booked travel plans.','easy'),

  -- BLOCK 43: BGT passivo
  (cid,43,146,'gap_fill','The new hospital wing _____ (open/passive) by the mayor next week.','is going to be opened',NULL,'"Is going to be + past participle" = planned future passive.','hard'),
  (cid,43,147,'gap_fill','Three suspects _____ (question/passive) by detectives this afternoon.','are going to be questioned',NULL,'Planned future passive with plural subject.','hard'),
  (cid,43,148,'multiple_choice','Which sentence uses "be going to" passive CORRECTLY?','The data are going to be analyzed by an independent research team.','["The data are going to analyzed by an independent research team.","The data is going to be analyzing by an independent research team.","The data are going to be analyzed by an independent research team.","The data going to be analyzed by an independent research team."]','"Are going to be + past participle" = correct BGT passive (plural).','medium'),
  (cid,43,149,'gap_fill','The results _____ (present/passive) at the annual conference — the committee confirmed this yesterday.','are going to be presented',NULL,'BGT passive for confirmed future event.','medium'),
  (cid,43,150,'gap_fill','Hundreds of workers _____ (lay off/passive) — management _____ (announce) redundancies next Monday.','are going to be laid off / is going to announce',NULL,'BGT passive for workers + BGT active for management action.','hard'),

  -- BLOCK 44: BGT com expressões temporais avançadas
  (cid,44,151,'gap_fill','By this time tomorrow, the medical team _____ (perform) the operation and the patient _____ (recover/passive) in the ICU.','is going to be performing / is going to be recovered',NULL,'BGT future continuous + BGT passive for simultaneous future activities.','hard'),
  (cid,44,152,'multiple_choice','Which temporal marker most naturally co-occurs with "be going to"?','"This weekend / soon / next month" (near-term plans).','["Last year","Yesterday","This weekend / soon / next month (near-term plans).","Always / usually"]','"Be going to" naturally pairs with near-future time markers: tonight, next week, soon.','easy'),
  (cid,44,153,'gap_fill','The policy _____ (take effect) as soon as all 28 member states _____ (ratify) it.','is going to take effect / ratify',NULL,'BGT main clause + present simple after "as soon as" (not BGT/future in subordinate clause).','hard'),
  (cid,44,154,'multiple_choice','What does "be going to" in "Careful! You''re going to spill that!" express?','An imminent prediction based on observable evidence.','["A past habit","A polite suggestion","An imminent prediction based on observable evidence.","A scheduled event"]','Visible situation → going to for immediate prediction.','easy'),
  (cid,44,155,'gap_fill','Researchers _____ (release) their findings next month, and the implications _____ (not/be) welcome by everyone in the field.','are going to release / are not going to be',NULL,'BGT positive + BGT negative.','medium'),

  -- BLOCK 45: TOEFL Reading
  (cid,45,156,'multiple_choice','[TOEFL Reading] "The government is going to implement a carbon tax by the end of the year." In academic context, this would be better expressed as:','The government is expected to implement a carbon tax by the end of the year.','["The government goes to implement a carbon tax","The government implemented a carbon tax","The government is expected to implement a carbon tax by the end of the year.","The government has implemented a carbon tax"]','"Is going to" = informal; academic → "is expected to / is set to / plans to."','medium'),
  (cid,45,157,'gap_fill','[TOEFL Reading] "Early warning systems _____ (deploy/passive) across all coastal communities before the hurricane season." Best BGT passive form?','are going to be deployed',NULL,'BGT passive for planned deployment.','medium'),
  (cid,45,158,'multiple_choice','[TOEFL Reading] When a scientist says "This approach is going to revolutionize treatment," the form expresses:','Confident prediction based on current evidence, not mere speculation.','["A past achievement","A conditional possibility","Confident prediction based on current evidence, not mere speculation.","A scheduled event"]','BGT for confident evidence-based prediction.','medium'),

  -- BLOCK 46: TOEFL Speaking
  (cid,46,159,'production','[TOEFL Speaking — 45s] A reading describes plans to build a new high-speed rail network. The lecture argues this will not succeed. Summarize using "be going to" for the plans and "is not going to" for the counterarguments.','',NULL,'The reading describes ambitious government plans to construct a high-speed rail network connecting all major cities within the next decade. The project is going to create thousands of construction jobs and is going to reduce travel times between major urban centers by more than 60%. However, the lecture argues that these goals are not going to be achieved on schedule or within budget. The professor points out that similar projects in other countries have gone massively over budget and taken twice as long as planned. The necessary land acquisitions are going to face significant legal challenges from landowners, and the required level of public investment is going to strain government finances. The professor concludes that the project is going to need substantial foreign financing and political commitments that may not be sustainable across multiple election cycles.','hard'),
  (cid,46,160,'production','[TOEFL Speaking — 45s] Describe your plans for academic or career development in the next two years. Use "be going to" for concrete plans and "will" for more speculative predictions.','',NULL,'Over the next two years, I am going to focus on strengthening the specific skills that the fields I am interested in require. I am going to enroll in an advanced statistics course in the coming semester, since quantitative methods are going to be essential for the research track I am planning to pursue. In the summer, I am going to apply for a research internship or a work placement that will give me practical experience outside academic settings. I believe this combination of advanced coursework and applied experience will significantly strengthen any applications I make to graduate programs. By the end of this period, I am going to have a clearer sense of whether I want to go into research, policy, or practice — three pathways that currently all seem interesting but that will probably narrow as I gain more direct experience in each.','hard'),

  -- BLOCK 47: TOEFL Writing
  (cid,47,161,'production','[TOEFL Writing — 150 words] Write a paragraph about upcoming technological changes. Use "be going to" (×3), "will" (×3), and periphrastic futures (×2) to show register variation.','',NULL,'The next decade is going to witness transformations in transportation that are as significant as the introduction of the automobile a century ago. Electric vehicles are going to become the dominant new car type sold in most major markets by the early 2030s, driven by falling battery costs and strengthening government mandates. Autonomous vehicles are going to follow, though on a longer timeline: full self-driving capability in complex urban environments is expected to require several more years of regulatory testing and public trust-building. Beyond road transport, urban air mobility — small electric aircraft operating between city rooftops — is set to emerge as a commercial service in some cities within this decade. These changes will collectively reduce transportation''s contribution to greenhouse gas emissions significantly, though the pace of change will vary considerably across different income levels and geographic regions.','hard'),
  (cid,47,162,'production','[TOEFL Writing — Error Correction] Fix errors: "I am go to submit the proposal tomorrow. The conference going to be held online. Researchers are going to presented the findings next week. The team is going to has completed the analysis by Friday."','',NULL,'am go → am going (base form: be going to + base verb); going to be held = likely correct but ''conference going to'' missing ''is/are going to''; going to presented → going to present (base form after ''going to''); is going to has completed → is going to have completed or will have completed (future perfect: going to + have + past participle for completion by a future point).','hard'),

  -- BLOCK 48: Consolidação final
  (cid,48,163,'production','[TOEFL Writing — 200 words] Write an academic paragraph on planned government interventions for climate change. Use: is going to + base verb (×2), is expected to (×2), will (×2), unless (conditional), and at least one passive.','',NULL,'Governments worldwide are developing increasingly comprehensive policy packages to address the growing urgency of climate change, and several major economies are going to implement carbon pricing mechanisms within the next five years. The European Union''s Carbon Border Adjustment Mechanism, already in transitional phase, is going to be fully enforced from 2026, applying a carbon cost to imports from countries without equivalent domestic carbon pricing. Meanwhile, large economies including the United States, China, and India are expected to reach peak emissions by 2030, after which absolute emission levels are expected to begin declining. Renewable energy deployment will accelerate as the cost of solar and wind power continues to fall, and battery storage capacity will expand to address intermittency challenges. However, these trajectories will prove insufficient to limit warming to 1.5°C unless the pace of action is dramatically accelerated in the current decade — a conclusion that virtually all major climate modeling institutions now share.','hard'),
  (cid,48,164,'production','[TOEFL Writing — 200 words] Write a paragraph predicting changes in healthcare systems over the next 20 years. Use BGT for near-term plans, will for longer-term predictions, passive forms, and hedging.','',NULL,'Healthcare systems around the world are going to face profound structural challenges over the next two decades, as aging populations, rising treatment costs, and the rapid expansion of AI-driven medical technology combine to create both new pressures and new possibilities. In the near term, health ministries are going to be forced to make difficult choices about resource allocation as the ratio of working-age taxpayers to retired healthcare users deteriorates. AI diagnostic tools are going to be deployed across radiology, pathology, and primary care settings at increasing scale, improving accuracy and reducing the time from symptom to diagnosis. Over a longer horizon, personalized medicine — treatment protocols tailored to individual genetic profiles — will become standard practice for cancer and cardiovascular disease, the two leading causes of preventable death in most high-income countries. The greatest challenge will be ensuring that these advances do not exacerbate existing health inequalities: AI systems trained on unrepresentative data may perform poorly for underrepresented populations, and personalized treatments will initially be far too expensive for most health systems to provide universally.','hard'),
  (cid,48,165,'production','[TOEFL Speaking — 60s] Discuss what changes you believe the education system is going to undergo over the next decade. Use BGT, will, periphrastic futures, and hedging.','',NULL,'Education systems around the world are going to undergo some of their most significant changes since mass public schooling was established in the nineteenth century. The most immediate transformation is going to be driven by artificial intelligence: AI tutoring systems are going to become increasingly capable of providing personalized instruction that adapts to individual student pace, learning style, and knowledge gaps in real time. Traditional standardized testing is expected to give way to more continuous, portfolio-based assessment that measures a wider range of competencies. Schools are going to need to redesign their curricula to prioritize the skills that AI cannot easily replicate: complex problem-solving, creative thinking, interpersonal communication, and ethical reasoning. The physical school building is not going to disappear — research on child development strongly suggests that peer interaction and structured physical environments remain important for learning — but the role of the building will shift from a place where information is transmitted to a place where it is applied and discussed. Some of these changes will happen faster in well-resourced private systems, creating a risk that public education will fall further behind unless targeted investment is made.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
