-- ============================================================
-- SEED: Módulo 7 — Present Perfect (A2)
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'present-perfect';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo present-perfect não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 1: have/has + past participle formation
  (cid,1,1,'gap_fill','She ___ (write) three academic papers this year.','has written',NULL,'Present perfect: has + past participle. She → has + written (irregular).','easy'),
  (cid,1,2,'gap_fill','They ___ (conduct) extensive research on this topic.','have conducted',NULL,'They → have + past participle (regular verb: conduct→conducted).','easy'),
  (cid,1,3,'multiple_choice','Choose the correct form: "The scientists ___ a major breakthrough."','have made','["has made","have made","had made","have make"]','Plural subject (scientists) → have + past participle.','easy'),
  (cid,1,4,'gap_fill','I ___ (not/finish) reading the assigned article yet.','haven''t finished',NULL,'Negative present perfect: have not (haven''t) + past participle.','easy'),
  (cid,1,5,'gap_fill','He ___ (publish) five articles in peer-reviewed journals.','has published',NULL,'He → has + past participle.','easy'),
  (cid,1,6,'multiple_choice','Which sentence is correct?','The university has updated its curriculum three times.','["The university have updated its curriculum three times.","The university has updated its curriculum three times.","The university has update its curriculum three times.","The university updated its curriculum three times recently."]','Has + past participle for present perfect.','easy'),
  (cid,1,7,'gap_fill','We ___ (receive) positive feedback from the research committee.','have received',NULL,'We → have + past participle.','easy'),

  -- BLOCK 2: irregular past participles
  (cid,2,8,'gap_fill','She ___ (go) to several international conferences.','has gone',NULL,'Irregular: go→went→gone. Present perfect uses gone (3rd form).','medium'),
  (cid,2,9,'multiple_choice','What is the past participle of "take"?','taken','["taked","took","taken","taking"]','Irregular: take→took→taken.','medium'),
  (cid,2,10,'gap_fill','He ___ (become) one of the most cited researchers in his field.','has become',NULL,'Irregular: become→became→become. Present perfect: has become.','medium'),
  (cid,2,11,'multiple_choice','Choose the correct present perfect: "The committee ___ its decision."','has made','["has maked","has made","have make","has making"]','Irregular: make→made→made.','medium'),
  (cid,2,12,'gap_fill','They ___ (find) new evidence to support the theory.','have found',NULL,'Irregular: find→found→found.','medium'),
  (cid,2,13,'multiple_choice','What is the past participle of "choose"?','chosen','["choosed","chose","chosen","choosing"]','Irregular: choose→chose→chosen.','hard'),
  (cid,2,14,'gap_fill','The professor ___ (give) students extensive feedback on their drafts.','has given',NULL,'Irregular: give→gave→given.','medium'),

  -- BLOCK 3: ever/never - life experiences
  (cid,3,15,'gap_fill','Have you ___ (visit) a research laboratory?','ever visited',NULL,'"Ever" in present perfect questions about life experiences.','easy'),
  (cid,3,16,'multiple_choice','Which question correctly asks about a life experience?','Have you ever attended an international conference?','["Did you ever attend an international conference?","Have you ever attended an international conference?","Do you ever attend an international conference?","Have you ever attend an international conference?"]','"Have + ever + past participle" for life experiences.','medium'),
  (cid,3,17,'gap_fill','I have ___ (miss) a deadline — I always submit on time.','never missed',NULL,'"Never" in present perfect for a life experience that has not occurred.','easy'),
  (cid,3,18,'multiple_choice','Choose the correct response: "Have you ever studied a second language?" "Yes, ___."','I have.','["Yes, I did.","Yes, I have.","Yes, I had.","Yes, I do."]','Short answer for present perfect: Yes, subject + have/has.','easy'),
  (cid,3,19,'gap_fill','She has ___ (live) in three different countries for her research.','lived',NULL,'"Has + past participle" for life experiences without ever/never.','easy'),
  (cid,3,20,'multiple_choice','Which sentence uses "never" correctly in present perfect?','He has never failed an exam in his academic career.','["He never failed an exam in his academic career (past simple).","He has never failed an exam in his academic career.","He is never failing an exam.","He was never failing an exam."]','Has + never + past participle for present perfect.','medium'),
  (cid,3,21,'gap_fill','___ (they/ever/use) machine learning in their research?','Have they ever used',NULL,'Present perfect question with ever: Have/Has + subject + ever + past participle?','medium'),

  -- BLOCK 4: already/yet/just
  (cid,4,22,'gap_fill','She has ___ submitted her application — she sent it this morning.','already',NULL,'"Already" in present perfect = completed sooner than expected. Positive sentences.','easy'),
  (cid,4,23,'multiple_choice','Where does "yet" go in this sentence: "They haven''t published the results"?','at the end: They haven''t published the results yet.','["before the verb: They haven''t yet published","at the end: They haven''t published the results yet.","after haven''t: They haven''t yet published the results.","at the beginning: Yet they haven''t published the results."]','"Yet" goes at the end of negative present perfect sentences and questions.','medium'),
  (cid,4,24,'gap_fill','The professor has ___ returned the graded exams — he gave them back five minutes ago.','just',NULL,'"Just" = very recently. Position: between have/has and past participle.','easy'),
  (cid,4,25,'multiple_choice','Choose the correct sentence with "already".','I''ve already read that article — it was fascinating.','["I''ve already reading that article.","I''ve already read that article — it was fascinating.","I already read that article yesterday (past simple is fine here too).","I''ve read that article already? (question form)"]','Already + past participle in present perfect = completed action.','medium'),
  (cid,4,26,'gap_fill','Have they arrived ___? The meeting is about to start.','yet',NULL,'"Yet" in present perfect questions = expectation something should have happened.','easy'),
  (cid,4,27,'multiple_choice','Which sentence uses "just" correctly?','She has just defended her dissertation successfully!','["She just defended her dissertation yesterday (past simple OK with specific time).","She has just defended her dissertation successfully!","She has just defending her dissertation.","She just has defended her dissertation."]','Has + just + past participle for very recent actions.','medium'),
  (cid,4,28,'gap_fill','He hasn''t submitted his final chapter ___.','yet',NULL,'"Yet" at end of negative present perfect = expected but not done.','easy'),

  -- BLOCK 5: for/since - unfinished time
  (cid,5,29,'gap_fill','She has been a professor ___ 2010.','since',NULL,'"Since" + specific point in time (year, date, event).','easy'),
  (cid,5,30,'gap_fill','They have worked on this project ___ three years.','for',NULL,'"For" + duration/period of time.','easy'),
  (cid,5,31,'multiple_choice','Choose "for" or "since": "He has lived in the US ___ 2015."','since','["for","since"]','"Since" for a specific starting point (2015).','easy'),
  (cid,5,32,'gap_fill','I have studied English ___ many years.','for',NULL,'"For" for a period of time (many years = duration).','easy'),
  (cid,5,33,'multiple_choice','Which sentence is correct?','The lab has been operational since its inauguration in 2018.','["The lab has been operational for its inauguration in 2018.","The lab has been operational since its inauguration in 2018.","The lab has been operational since two years.","The lab has been operational for 2018."]','"Since" + a specific event/point in time.','medium'),
  (cid,5,34,'gap_fill','She has not published anything ___ she finished her last project.','since',NULL,'"Since" + clause (when an event occurred).','medium'),
  (cid,5,35,'multiple_choice','Choose "for" or "since": "The researchers have collaborated ___ more than a decade."','for','["since","for"]','"For" + a period/duration (more than a decade).','easy'),

  -- BLOCK 6: contrast with Past Simple
  (cid,6,36,'multiple_choice','Which sentence uses Past Simple (not Present Perfect)?','She graduated in 2019.','["She has graduated recently.","She has already graduated.","She graduated in 2019.","She has graduated from university."]','"In 2019" = specific finished time → Past Simple.','medium'),
  (cid,6,37,'gap_fill','I ___ (see) that film last Monday. (specific past time)','saw',NULL,'Specific past time (last Monday) → Past Simple, not Present Perfect.','medium'),
  (cid,6,38,'multiple_choice','Choose the correct sentence: "They ___ the data when ___ the study."','analyzed / they conducted','["have analyzed / they have conducted","analyzed / they conducted","have analyzed / they conducted","analyzed / they have conducted"]','Specific completed past event = Past Simple.','medium'),
  (cid,6,39,'gap_fill','She ___ (live) in Paris for two years, and now she speaks fluent French.','has lived',NULL,'She still speaks French → situation connects to present → Present Perfect.','hard'),
  (cid,6,40,'multiple_choice','Identify the correct sentence.','Have you seen the new study on cognitive load? It came out yesterday.','["Have you seen the new study? It has come out yesterday.","Have you seen the new study on cognitive load? It came out yesterday.","Did you see the new study? It has come out yesterday.","Have you saw the new study? It came out yesterday."]','"Have you seen" (recent + relevant now) + "came out yesterday" (specific past time → past simple).','hard'),
  (cid,6,41,'gap_fill','He ___ (submit) three applications. He ___ (submit) the last one on Friday.','has submitted / submitted',NULL,'Count without time (present perfect) vs. specific day (past simple).','hard'),
  (cid,6,42,'multiple_choice','Which time expression requires Past Simple (NOT Present Perfect)?','in 2015','["ever","just","in 2015","yet"]','"In 2015" is a specific finished time → use Past Simple.','medium'),

  -- BLOCK 7: present perfect with how long / questions
  (cid,7,43,'gap_fill','___ (how long/she/study) at this university?','How long has she studied',NULL,'How long + has/have + subject + past participle?','medium'),
  (cid,7,44,'multiple_choice','Which question is correct?','How long have you been interested in neuroscience?','["How long did you been interested in neuroscience?","How long have you been interested in neuroscience?","Since when have you interested in neuroscience?","How long you have been interested in neuroscience?"]','How long + have/has + subject + been + adjective/verb-ing.','medium'),
  (cid,7,45,'gap_fill','She has ___ (know) her supervisor ___ the beginning of her PhD.','known / since',NULL,'Known = irregular past participle of know. Since for starting point.','hard'),
  (cid,7,46,'multiple_choice','Choose the correct question about an experience.','How many articles has she published?','["How many articles did she has published?","How many articles has she published?","How many articles she has published?","How many articles have she published?"]','Has + subject + past participle for present perfect questions.','medium'),
  (cid,7,47,'gap_fill','___ (the research/show) any significant results so far?','Has the research shown',NULL,'Has + singular subject + past participle?','medium'),
  (cid,7,48,'multiple_choice','Which is a correct present perfect question?','Have they ever considered a longitudinal study design?','["Did they ever consider a longitudinal study design? (past simple)","Have they ever considered a longitudinal study design?","Have they ever considering a longitudinal study design?","Have they ever been consider a longitudinal study design?"]','Have + they + ever + past participle.','medium'),
  (cid,7,49,'gap_fill','___ (anyone/try) this methodology before?','Has anyone tried',NULL,'Has + subject + past participle for present perfect questions.','medium'),

  -- BLOCK 8: mixed present perfect review
  (cid,8,50,'multiple_choice','Choose the correct sentence.','The team has collected significant data over the past six months.','["The team collected significant data over the past six months (past simple also OK).","The team has collected significant data over the past six months.","The team have collected significant data over the past six months.","The team has collect significant data over the past six months."]','Has + past participle for present perfect with unfinished time frame.','medium'),
  (cid,8,51,'gap_fill','I ___ (not/read) this article yet, but I plan to read it tonight.','haven''t read',NULL,'Haven''t + past participle + yet for unfinished obligation.','easy'),
  (cid,8,52,'multiple_choice','Identify the error: "She has went to London twice."','went should be gone','["She is correct","has should be have","went should be gone","twice should be two times"]','Present perfect uses past participle: go→went→gone. Has gone, not has went.','medium'),
  (cid,8,53,'gap_fill','The university ___ (introduce) a new grading system this academic year.','has introduced',NULL,'This academic year = unfinished time period → present perfect.','medium'),
  (cid,8,54,'multiple_choice','Which sentence is correct?','I have known Professor Chen since I started my PhD.','["I knew Professor Chen since I started my PhD.","I have known Professor Chen since I started my PhD.","I have knew Professor Chen since I started my PhD.","I have known Professor Chen since I have started my PhD."]','Have known (irregular) + since + Past Simple clause.','hard'),
  (cid,8,55,'gap_fill','She ___ (just/present) her findings to the board of directors.','has just presented',NULL,'Has + just + past participle for very recent completed action.','medium'),
  (cid,8,56,'multiple_choice','Choose the sentence that correctly contrasts Present Perfect and Past Simple.','I have visited Paris three times; my last visit was in 2022.','["I have visited Paris three times; my last visit has been in 2022.","I have visited Paris three times; my last visit was in 2022.","I visited Paris three times; my last visit has been in 2022.","I visited Paris three times in total; my last visit was in 2022."]','Present perfect for experience count; past simple for specific time.','hard'),

  -- BLOCK 9: TOEFL academic contexts
  (cid,9,57,'multiple_choice','[TOEFL Reading] The passage states that scientists ___ new evidence linking gut microbiome to mental health.','have recently discovered','["discovered recently","have recently discovered","are recently discovering","recently discovered"]','Unfinished timeframe + academic relevance now = present perfect.','medium'),
  (cid,9,58,'gap_fill','[TOEFL Listening] The professor notes: "Researchers ___ (demonstrate) that sleep deprivation significantly impairs cognitive function."','have demonstrated',NULL,'Present perfect in academic contexts for established findings.','hard'),
  (cid,9,59,'multiple_choice','[TOEFL Reading] Which sentence best introduces a research finding in an academic passage?','Studies have shown a strong correlation between diet and cardiovascular disease.','["Studies showed a strong correlation (past simple).","Studies have showed a strong correlation.","Studies have shown a strong correlation between diet and cardiovascular disease.","Studies are showing a strong correlation."]','Have + shown (irregular) = academic present perfect for established findings.','medium'),
  (cid,9,60,'gap_fill','[TOEFL Listening] The lecturer explains: "The field ___ (change) dramatically since the introduction of CRISPR technology in 2013."','has changed',NULL,'Has + changed + since = present perfect for change from past point to now.','hard'),
  (cid,9,61,'multiple_choice','[TOEFL Reading] Which signal word in the sentence "The number of published papers on this topic has grown significantly over the past decade" indicates present perfect is correct?','over the past decade','["significantly","number","published","over the past decade"]','"Over the past decade" is an unfinished time period → present perfect.','hard'),
  (cid,9,62,'gap_fill','[TOEFL Reading] Economic inequality ___ (increase) steadily in many developed nations since the 1980s.','has increased',NULL,'Since 1980s = starting point; still relevant → present perfect.','hard'),
  (cid,9,63,'multiple_choice','[TOEFL Listening] The professor asks: "Has anyone in this class ___?" Which completion is most natural?','read the original Chomsky paper on transformational grammar?','["reading the original Chomsky paper?","reads the original Chomsky paper?","read the original Chomsky paper on transformational grammar?","was reading the original Chomsky paper?"]','Have + past participle for present perfect questions.','hard'),

  -- BLOCK 10: TOEFL production tasks
  (cid,10,64,'multiple_choice','[TOEFL Reading] Identify the correct present perfect sentence in academic context.','Researchers have identified three main factors contributing to urban air pollution.','["Researchers identified three main factors last year (past simple).","Researchers have identified three main factors contributing to urban air pollution.","Researchers are identifying three main factors.","Researchers has identified three main factors."]','Have + past participle for relevant current findings.','hard'),
  (cid,10,65,'gap_fill','[TOEFL Reading] The study ___ (reveal) that participants who ___ (receive) the treatment ___ (show) significant improvement since the trial began.','has revealed / received / have shown',NULL,'Has revealed = current relevance; received = past event; have shown = ongoing since.','hard'),
  (cid,10,66,'multiple_choice','[TOEFL Speaking — 45s] You are asked: "What experiences have prepared you most for academic study?" Which response best uses present perfect?','I have lived abroad for two years and have worked as a research assistant, both of which have given me valuable academic skills.','["I lived abroad for two years and worked as a research assistant.","I have lived abroad for two years and have worked as a research assistant, both of which have given me valuable academic skills.","I am living abroad and I am working as a research assistant.","I was living abroad and I was working as a research assistant."]','Present perfect for life experiences relevant to the present moment.','hard'),
  (cid,10,67,'production','[TOEFL Speaking — 45s] Describe your academic experiences. Include: things you have already accomplished, things you haven''t done yet, how long you have been studying English, and one specific past event using past simple.','',NULL,'Use present perfect for experiences/states connecting to now; past simple for specific past events.','hard'),
  (cid,10,68,'production','[TOEFL Writing] Write a paragraph (4-5 sentences) summarizing the key findings of recent research in a field you are interested in. Use present perfect at least 3 times to describe what researchers have discovered, proven, or demonstrated.','',NULL,'Academic writing uses present perfect for established findings that remain relevant.','hard'),
  (cid,10,69,'multiple_choice','[TOEFL Writing] Which sentence best opens a body paragraph in an academic essay?','Several studies have demonstrated that regular physical activity improves cognitive function in adolescents.','["Several studies demonstrated that regular physical activity improves cognitive function.","Several studies have demonstrated that regular physical activity improves cognitive function in adolescents.","Several studies are demonstrating that regular physical activity improves cognitive function.","Several studies had demonstrated that regular physical activity improves cognitive function."]','Present perfect (have demonstrated) introduces established academic evidence.','hard'),
  (cid,10,70,'production','[TOEFL Writing] Write an introductory paragraph for an essay on climate change. Include: (1) a present perfect sentence about what scientists have discovered, (2) a for/since time expression, (3) a contrast using past simple for a specific historical event, and (4) a present perfect sentence with "yet".','',NULL,'Integrate present perfect for background research, for/since, past simple contrast, and yet.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
