-- ============================================================
-- SEED EXT 5: Módulo 23 — Advanced Modals (ex 174-248)
-- Novos tópicos: modal perfects em academic analysis, deduction
-- chains, semi-modals avançados, TOEFL integrated tasks
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'advanced-modals';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo advanced-modals não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 51: Modal perfects para dedução e inferência
  (cid,51,174,'gap_fill','The sudden collapse of the institution _____ (not/anticipate/passive) overnight; systematic weaknesses _____ (develop/passive) over years while regulators _____ (fail) to act on the warning signs.','could not have been anticipated / must have been developing / must have failed / cannot have been anticipated',NULL,'"Could not have been anticipated" = near-zero past possibility (passive). "Must have been developing" = logical deduction about past process.','hard'),
  (cid,51,175,'gap_fill','The policy _____ (introduce/passive) without adequate stakeholder consultation, which _____ (explain) the ferocity of the subsequent public resistance.','must have been introduced / might explain / may explain / could explain',NULL,'"Must have been introduced" = deduction from evidence + "might/may/could explain" = epistemic hedge.','hard'),
  (cid,51,176,'gap_fill','Given the available resources, the team _____ (achieve) more _____ (deploy/passive) more strategically; the failure _____ (not/technical) — it _____ (be) managerial.','could have achieved / had they been deployed / was not technical / must have been',NULL,'"Could have achieved" = unrealized past potential + "must have been" = logical deduction.','hard'),
  (cid,51,177,'multiple_choice','Which modal perfect expresses the STRONGEST certainty about a past deduction?','"The data must have been corrupted before the analysis was run — the errors are systematic and could not have arisen randomly."','["The data might have been corrupted.","The data could have been corrupted before the analysis was run.","The data must have been corrupted before the analysis was run — the errors are systematic and could not have arisen randomly.","The data should have been corrupted in the analysis."]','"Must have been" = logical necessity deduction (near certain). "Might/could" = possibility.','medium'),
  (cid,51,178,'gap_fill','The disparity _____ (emerge) over several years rather than as a single event; early intervention _____ (prevent) the most severe consequences, but the opportunity _____ (miss/passive).','must have emerged / could have prevented / should have prevented / was missed',NULL,'Modal perfect chain: "must have emerged" (deduction) + "could/should have prevented" (missed opportunity) + "was missed" (PS fact).','hard'),

  -- BLOCK 52: Should have / ought to have — crítica ao passado
  (cid,52,179,'gap_fill','Regulators _____ (identify) these vulnerabilities much earlier; the fact that they _____ (not/do so) _____ (constitute) a serious institutional failure that _____ (require) thorough investigation.','should have identified / did not do so / constitutes / requires',NULL,'"Should have identified" = past obligation not fulfilled + PS for current facts.','medium'),
  (cid,52,180,'gap_fill','The report _____ (circulate/passive) to all relevant departments before the decision _____ (take/passive); _____ (not/do so/passive) represents a procedural failure that _____ (correct/passive) urgently.','should have been circulated / was taken / not having done so / must be corrected',NULL,'"Should have been circulated" (passive modal perfect) + "must be corrected" (present obligation).','hard'),
  (cid,52,181,'multiple_choice','What does "ought to have been" mean in academic criticism?','The action was the correct one but did not happen — a past unfulfilled obligation.','["The action happened correctly","The action was the correct one but did not happen — a past unfulfilled obligation.","The action will happen in the future","The action might have happened"]','"Ought to have been" = criticism of past inaction, same as "should have been" (past obligation unfulfilled).','medium'),
  (cid,52,182,'gap_fill','The data _____ (store/passive) in a way that _____ (allow) retrospective analysis; the decision to _____ (not/do so) _____ (significantly/limit) the capacity for long-term evaluation.','should have been stored / allowed / not do so / has significantly limited',NULL,'"Should have been stored" + PS result clause for ongoing consequence.','hard'),

  -- BLOCK 53: Need to / used to / dare (semi-modals avançados)
  (cid,53,183,'gap_fill','Researchers _____ (not/rely) on self-reported data alone; more objective measures _____ (develop/passive) alongside questionnaire instruments.','need not rely / need to develop / should develop / needed to develop / need not have relied',NULL,'"Need not rely" = present absence of necessity + "need to develop" = present necessity.','hard'),
  (cid,53,184,'gap_fill','Academic publishing _____ (be) dominated by a small number of large commercial publishers whose pricing _____ (price) many institutions out of access; this _____ (not/continue).','used to be / has priced / need not continue / must not continue',NULL,'"Used to be" = past state no longer true + "need not continue" = absence of necessity for continuation.','hard'),
  (cid,53,185,'multiple_choice','What does "dare not" mean in the following? "Policymakers dare not ignore the evidence on climate risks any longer."','"Dare not" = they would face very serious consequences if they ignored the evidence — a strong negative obligation.','["They choose not to ignore","They are not able to ignore","''Dare not'' = they would face very serious consequences if they ignored the evidence — a strong negative obligation.","They have not ignored the evidence"]','"Dare not" = strong discouraged action; it signals that the risk of the action is too serious to contemplate.','hard'),
  (cid,53,186,'gap_fill','Developing economies _____ (not/need) to _____ (repeat) the environmental mistakes of early industrialization; cleaner pathways _____ (now/available) at costs that _____ (be) competitive with fossil fuels.','need not / repeat / are now available / are',NULL,'"Need not repeat" = absence of necessity for a negative action (= you have a better option).','medium'),
  (cid,53,187,'gap_fill','Such disparities _____ (use) _____ (consider/passive) inevitable; they _____ (now/recognize/passive) as the product of specific policy choices that _____ (reverse/passive).','used to be / considered / are now recognized / can be reversed',NULL,'"Used to be considered" = past habitual passive state (now changed).','hard'),

  -- BLOCK 54: Modal passive avançado em academic writing
  (cid,54,188,'gap_fill','The mechanism _____ (hypothesize/passive) to involve epigenetic changes, though this _____ (not/yet/confirm/passive) by experimental evidence.','is hypothesized / has not yet been confirmed',NULL,'"Is hypothesized to involve" = epistemic passive present + PP passive negative for current gap.','hard'),
  (cid,54,189,'gap_fill','These patterns _____ (not/dismiss/passive) as methodological artifacts; they _____ (replicate/passive) across multiple independent datasets using different measurement approaches.','cannot be dismissed / have been replicated',NULL,'"Cannot be dismissed" = strong prohibition modal passive + PP passive for evidence.','medium'),
  (cid,54,190,'gap_fill','A definitive causal claim _____ (not/make/passive) at this stage; further experimental evidence _____ (require/passive) before the proposed mechanism _____ (accept/passive) as established.','cannot be made / is required / can be accepted',NULL,'Sequence of modal passives: cannot be made → is required → can be accepted.','hard'),
  (cid,54,191,'multiple_choice','Which modal passive is MOST APPROPRIATE for a research limitation?','The long-term effects could not be assessed within the timeframe of the current study.','["The long-term effects must not be assessed within the timeframe.","The long-term effects would not be assessed within the timeframe.","The long-term effects could not be assessed within the timeframe of the current study.","The long-term effects should not be assessed within the timeframe."]','"Could not be assessed" = capacity/possibility limitation in research context.','easy'),

  -- BLOCK 55: TOEFL Reading avançado
  (cid,55,192,'multiple_choice','[TOEFL Reading] "The symptoms must have developed gradually over months before diagnosis." "Must have developed" expresses:','A confident past deduction — the speaker is logically certain this is what happened.','["A past obligation","A confident past deduction — the speaker is logically certain this is what happened.","A past possibility","A regret about the past"]','"Must have + PP" = logical past deduction based on evidence. Not obligation, possibility, or regret.','medium'),
  (cid,55,193,'gap_fill','[TOEFL Reading] "The researchers _____ (acknowledge) these limitations earlier; _____ (not/do so/passive) has called the validity of the conclusions into question." Best modal perfect?','should have acknowledged / not having done so',NULL,'"Should have acknowledged" = past obligation/criticism + gerund clause.','medium'),
  (cid,55,194,'multiple_choice','[TOEFL Reading] "Might not have" vs "could not have" in academic writing: what is the difference?','"Might not have" = it''s possible it didn''t happen. "Could not have" = it was impossible for it to have happened.','["They are always interchangeable","''Might not have'' = strong impossibility, ''could not have'' = possibility","''Might not have'' = it''s possible it didn''t happen. ''Could not have'' = it was impossible for it to have happened.","Both express past obligation"]','"Might not have" = epistemic (possible that not). "Could not have" = epistemic impossibility.','hard'),
  (cid,55,195,'gap_fill','[TOEFL Reading] "This technology _____ (not/develop) without sustained public investment in basic research over several decades." Best modal perfect form?','could not have developed / would not have developed',NULL,'"Could not have developed" = it was impossible without X. "Would not have" = it would not have done so (Type 3 result clause).','hard'),

  -- BLOCK 56: TOEFL Speaking avançado
  (cid,56,196,'production','[TOEFL Speaking — 45s] A reading describes a failed development project. A lecture analyzes what went wrong. Use modal perfects throughout.','',NULL,'The reading describes a large-scale irrigation project that was intended to transform agricultural productivity in an arid region but ultimately failed to achieve its objectives. The lecture analyzes the multiple factors that must have contributed to the failure. According to the professor, project designers should have conducted more comprehensive community consultations before finalizing the technical design; had they done so, they might have avoided the fundamental misalignment between the infrastructure they built and the actual farming practices of local communities. The professor also argues that implementation managers cannot have been monitoring field conditions adequately, since the early signs of operational problems — which ought to have triggered design adjustments — went unaddressed for almost two years. Furthermore, the professor suggests that the governance structure of the project could have been designed to give local communities much greater ownership and decision-making authority, which would have created stronger incentives for maintenance and problem-solving. In sum, the lecture argues that the project need not have failed as comprehensively as it did: the technical approach was sound, but the institutional and participatory dimensions should have been given far greater weight from the outset.','hard'),
  (cid,56,197,'production','[TOEFL Speaking — 45s] Discuss how the 2008 financial crisis might have been prevented. Use modal perfects throughout.','',NULL,'The 2008 global financial crisis has generated considerable retrospective analysis, and there is now a substantial body of evidence suggesting that the most catastrophic outcomes could have been avoided through different regulatory and policy choices. Regulators should have recognized that the rapid growth of complex mortgage-backed securities was creating systemic risks that could not be adequately assessed by standard risk models. Credit rating agencies ought to have applied far more rigorous standards to the structured products they were evaluating; their failure to do so must have been at least partly influenced by the obvious conflict of interest created by their business model of being paid by the issuers whose products they rated. Central banks and supervisory authorities could have required financial institutions to hold substantially higher capital buffers against their exposures to these instruments. The monetary policy that was maintained in the years prior to the crisis might have been tighter, which could have reduced the build-up of leverage that amplified the eventual shock. While it would be unfair to suggest that all of this was fully predictable — some of the crisis''s dynamics could not have been anticipated without hindsight — the structural vulnerabilities that allowed it to become as severe as it did should have been visible to regulators who were paying close attention.','hard'),

  -- BLOCK 57: TOEFL Writing avançado
  (cid,57,198,'production','[TOEFL Writing — 200 words] Write a paragraph on the history of development aid failures using modal perfects throughout.','',NULL,'Retrospective analysis of international development assistance reveals a pattern of missed opportunities and avoidable failures that ought to have been recognized and addressed much earlier. The structural adjustment programs imposed by the IMF and World Bank during the 1980s and 1990s required recipient governments to reduce public spending, liberalize trade, and privatize state enterprises under conditions of economic crisis; in hindsight, economists should have predicted that these measures would contract demand and reduce the public investment in health, education, and infrastructure on which long-term development depends. The institutions could not have failed to observe the early evidence that austerity was generating the predicted negative effects, yet policy corrections were slow and incomplete. Aid modalities throughout much of this period should have been far more attentive to recipient country ownership and institutional capacity; the practice of attaching detailed conditionality to loans and grants undermined the development of genuine policy autonomy that sustainable development requires. Donor coordination ought to have been much more coherent: the proliferation of donors with different priorities, reporting requirements, and project cycles imposed transaction costs on recipient governments that should have been recognized as counterproductive. Many of these failures could have been avoided had the institutions been more genuinely open to feedback from the countries they claimed to be assisting.','hard'),
  (cid,57,199,'production','[TOEFL Writing — 200 words] Write a body paragraph on energy policy failures using advanced modal perfects and semi-modals.','',NULL,'The slow pace of the energy transition in many countries can be attributed in significant part to policy failures that need not have occurred and that should have been avoided with better institutional design. Governments used to treat energy policy primarily as a matter of energy security and price stability, and need not have failed to recognize the climate dimension of energy choices — the scientific evidence has been unambiguous since at least the early 1990s. Carbon pricing mechanisms that ought to have been introduced decades ago to align market incentives with the social cost of emissions were repeatedly delayed or weakened in response to industry lobbying; had they been implemented earlier, the technological and behavioral transitions required for decarbonization would have begun sooner and proceeded further. The regulatory frameworks governing electricity markets in many countries used to be designed for vertically integrated utilities and could not accommodate the distributed, variable generation that renewables require without significant restructuring; these frameworks should have been reformed much earlier. That said, it would be unfair to characterize the entire history of energy policy as one of failure: the dramatic cost reductions in solar and wind technology were supported by sustained public investment in research and by regulatory policies that created markets for early-stage technology, and these choices must have contributed significantly to where we are today.','hard'),

  -- BLOCK 58: Final
  (cid,58,200,'production','[TOEFL Writing — 200 words] Write a paragraph on colonial economic legacies using modal perfects and semi-modals.','',NULL,'The economic legacies of colonialism continue to shape development trajectories in formerly colonized regions, and counterfactual analysis of what might have developed differently reveals some of the most significant missed opportunities in economic history. Colonial powers used to design economic institutions in their territories to serve extraction rather than indigenous development: transportation infrastructure ought to have connected interior regions to one another for domestic economic development, but was instead built to connect resource extraction sites to ports for export. Revenue from commodity exports could have been reinvested in human capital and diversified industry — as some commodity exporters have managed with natural resource wealth — but was instead transferred out of the territories. Local manufacturing that might have developed need not have been suppressed by colonial trade policies that reserved industrial production for the metropolitan country. The human capital that would have been developed if colonial administrations had invested in education and health as a genuine priority, rather than as an incidental to labor management, could have created the foundations for self-sustaining economic growth decades earlier. These missed opportunities compound over time, and the current development gaps between formerly colonized and colonizing countries cannot be understood without recognizing the structural conditions that colonial economic policy created and that post-independence governments inherited.','hard'),
  (cid,58,201,'production','[TOEFL Speaking — 60s] Discuss what the scientific community should have done differently in communicating climate change. Use modal perfects throughout.','',NULL,'The history of climate science communication contains lessons that ought to have been learned earlier and that the scientific community should have applied more consistently over the decades during which public understanding of the issue remained inadequate to the scale of the risk. Scientists must have underestimated the difficulty of communicating probabilistic and uncertain findings to audiences accustomed to expecting definitive answers from experts; the nuanced language that appropriate scientific caution requires — "likely," "consistent with," "may" — was repeatedly interpreted by critics as indicating fundamental uncertainty about whether anthropogenic climate change was occurring at all. The scientific community should have responded more robustly and publicly to the deliberate disinformation campaigns funded by fossil fuel interests; by treating this as a scientific debate rather than as what it was — a political and public relations strategy — climate scientists might have countered misinformation more effectively. Communication approaches need not have remained so focused on technical data and away from the human impacts that make climate change personally meaningful to general audiences; the research on effective science communication that was available by the early 2000s should have informed a more strategic approach much earlier. That said, the institutional incentives within academic science used to reward technical publication over public communication, and individual scientists cannot fairly be held solely responsible for a structural failure that institutions ought to have addressed.','hard'),
  (cid,58,202,'production','[TOEFL Writing — Final 200 words] Write a conclusion on pandemic governance using modal perfects throughout.','',NULL,'This essay has argued that the governance failures exposed by the COVID-19 pandemic were not primarily failures of scientific knowledge — the intellectual tools for understanding and responding to pandemic threats had been developed — but failures of institutional design, political leadership, and international cooperation that need not have produced the scale of suffering that occurred. Governments should have maintained the pandemic preparedness infrastructure and stockpiles that were allowed to erode after the SARS and H1N1 outbreaks; had they done so, healthcare systems would not have been overwhelmed in the early months of the pandemic. The international community ought to have developed the financing mechanisms and governance frameworks for rapid equitable vaccine deployment before a pandemic occurred, rather than attempting to improvise them under crisis conditions. Richer countries need not have monopolized vaccine supplies during the acute phase of the pandemic; a more equitable distribution could have been organized had the political will existed and had the mechanisms been in place. The pandemic must have demonstrated as clearly as any event in recent history that global collective action problems require genuinely global institutions with the authority and resources to respond effectively. Building those institutions now — before the next pandemic — is not merely prudent policy: it is a moral obligation whose urgency the past several years should have made unmistakable.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
