-- ============================================================
-- SEED EXT 4: Módulo 10 — Modais Básicos (ex 161-240)
-- Novos tópicos: modais em contexto acadêmico (hedging),
-- modais epistêmicos vs deônticos, sequências de modais
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'modais-basicos';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo modais-basicos não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 41: modais epistêmicos (certeza vs possibilidade)
  (cid,41,161,'multiple_choice','What is an EPISTEMIC modal?','A modal expressing the speaker''s degree of certainty about a proposition.','["A modal expressing obligation","A modal expressing permission","A modal expressing the speaker''s degree of certainty about a proposition.","A modal expressing ability"]','Epistemic modals: must (deduction), may/might/could (possibility), will (prediction).','hard'),
  (cid,41,162,'gap_fill','The sample size is very small; the results _____ (might) therefore be due to chance rather than a genuine effect.','might',NULL,'"Might" = epistemic possibility (the results COULD be due to chance).','easy'),
  (cid,41,163,'gap_fill','Given the evidence, this _____ (must) be the mechanism responsible for the observed correlation.','must',NULL,'"Must" = epistemic necessity/deduction (the speaker is highly certain).','medium'),
  (cid,41,164,'multiple_choice','Rank these epistemic modals from MOST to LEAST certain: must / might / could / may / will (prediction).','Will (prediction) ≈ must > may > could ≈ might.','["Must > will > may > could > might (all correct — minor variation in ranking).","Might > could > may > must > will.","Will (prediction) ≈ must > may > could ≈ might.","May > must > might > will > could."]','Will = strong prediction; must = strong deduction; may > could ≈ might = decreasing certainty.','hard'),
  (cid,41,165,'gap_fill','The anomaly in the data _____ (could) be an artifact of the measurement instrument rather than a real phenomenon.','could',NULL,'"Could" = weaker epistemic possibility — one of several explanations.','easy'),

  -- BLOCK 42: modais deônticos (obrigação, permissão, proibição)
  (cid,42,166,'multiple_choice','What is a DEONTIC modal?','A modal expressing obligation, permission, or prohibition.','["A modal expressing certainty","A modal expressing ability only","A modal expressing obligation, permission, or prohibition.","A modal expressing a polite request only"]','Deontic modals regulate behavior: must (obligated), may (permitted), must not (prohibited).','hard'),
  (cid,42,167,'gap_fill','All applicants _____ (must) complete the online registration form before the closing date.','must',NULL,'"Must" = deontic obligation (rule/requirement).','easy'),
  (cid,42,168,'multiple_choice','Which modal is DEONTIC in: "Participants may withdraw at any time"?','"May" = deontic (permission to withdraw).','["Must","Should","''May'' = deontic (permission to withdraw).","Would"]','"May" as deontic = grants permission. "May" as epistemic = expresses possibility.','medium'),
  (cid,42,169,'gap_fill','Researchers _____ (must not) contact participants outside the approved communication channels.','must not',NULL,'"Must not" = deontic prohibition (it is forbidden).','easy'),
  (cid,42,170,'multiple_choice','In the sentence "You should submit your draft early," which deontic shade does "should" express?','A strong recommendation, not a strict obligation.','["Permission","Prohibition","A strong recommendation, not a strict obligation.","Certainty"]','"Should" = deontic advice/recommendation (weaker than ''must'').','easy'),

  -- BLOCK 43: modais em textos acadêmicos (hedging epistêmico)
  (cid,43,171,'gap_fill','The data _____ (suggest) that the intervention _____ (may) have produced these results, but further replication is needed.','suggest / may',NULL,'Academic hedging: "suggest + may" = double hedge (weak claim + uncertainty).','medium'),
  (cid,43,172,'multiple_choice','Which sentence is MOST appropriately hedged for a research paper''s discussion section?','The observed pattern might be attributable to selection bias, though this cannot be confirmed without further analysis.','["The observed pattern is attributable to selection bias.","It is obvious that the pattern is caused by selection bias.","The observed pattern might be attributable to selection bias, though this cannot be confirmed without further analysis.","The pattern could possibly perhaps maybe be due to bias."]','"Might be attributable to" + "cannot be confirmed" = appropriate double hedge in academic discussion.','hard'),
  (cid,43,173,'gap_fill','These findings _____ (could) have significant implications for public health policy, although it _____ (would) be premature to draw firm conclusions at this stage.','could / would',NULL,'"Could" (weak epistemic possibility) + "would be premature" = appropriately hedged academic claim.','hard'),
  (cid,43,174,'multiple_choice','What is the pragmatic function of "This may suggest that..." in academic writing?','It hedges the interpretation — the suggestion is tentative, not certain.','["It indicates the author is wrong","It makes the statement more persuasive by sounding informal","It hedges the interpretation — the suggestion is tentative, not certain.","It introduces a direct quotation"]','"May suggest" = double hedge. Marks the following claim as one possible interpretation.','medium'),
  (cid,43,175,'gap_fill','The correlation _____ (might) reflect a common cause rather than a direct causal relationship between the two variables.','might',NULL,'"Might reflect" = academic epistemic hedge for alternative explanation.','medium'),

  -- BLOCK 44: modais em perguntas e formas negativas avançadas
  (cid,44,176,'gap_fill','_____ (Could) you elaborate on the methodology used to control for confounding variables?','Could',NULL,'"Could you + base verb" = polite request (deontic, formal).','easy'),
  (cid,44,177,'multiple_choice','What is the difference between "Can you help me?" and "Could you help me?"?','"Can" is direct; "could" is more polite and tentative.','["They are identical","''Can'' is more formal","''Can'' is direct; ''could'' is more polite and tentative.","''Could'' is past only"]','"Could" for polite requests = more indirect/tentative than ''can''.','easy'),
  (cid,44,178,'gap_fill','The results _____ (cannot) be generalized to populations that were not represented in the sample.','cannot',NULL,'"Cannot" = impossibility/prohibition (here: epistemic impossibility of valid generalization).','medium'),
  (cid,44,179,'multiple_choice','Which negative modal correctly expresses that an action is NOT NECESSARY?','Students don''t have to purchase the textbook — it is available in the library.','["Students mustn''t purchase the textbook (prohibition — wrong meaning).","Students can''t purchase the textbook (impossibility — wrong meaning).","Students don''t have to purchase the textbook — it is available in the library.","Students shouldn''t purchase the textbook (advice against — wrong meaning)."]','"Don''t have to" = no obligation (it is not necessary, but not forbidden).','medium'),
  (cid,44,180,'gap_fill','You _____ (needn''t) memorize the formula — it _____ (will/provide/passive) in the examination.','needn''t / will be provided',NULL,'"Needn''t" = no necessity (British). "Will be provided" = future passive.','hard'),

  -- BLOCK 45: modal perfect avançado
  (cid,45,181,'gap_fill','The committee _____ (should/inform) applicants of the decision by now — it''s been three weeks.','should have informed',NULL,'"Should have informed" = unfulfilled past obligation or expectation.','medium'),
  (cid,45,182,'multiple_choice','What is the meaning of "The results might have been affected by seasonal variation"?','There is a possibility (uncertain) that seasonal variation influenced the results in the past.','["The results were definitely affected by seasonal variation","Seasonal variation will affect results in the future","There is a possibility (uncertain) that seasonal variation influenced the results in the past.","The results must have been affected by seasonal variation (stronger deduction)"]','"Might have + past participle" = past possibility (uncertain retrospective).','hard'),
  (cid,45,183,'gap_fill','She _____ (could/achieve) even more if she _____ (have) access to better resources.','could have achieved / had had',NULL,'"Could have + past participle" = unrealized past potential (mixed conditional implication).','hard'),
  (cid,45,184,'multiple_choice','What does "The experiment must have failed" express?','A strong deduction that failure occurred in the past.','["An obligation that existed in the past","A strong deduction that failure occurred in the past.","A past possibility","A regret about the past"]','"Must have + past participle" = logical deduction about a past event.','medium'),
  (cid,45,185,'gap_fill','The data _____ (cannot/misinterpret/passive) this way — it clearly shows the opposite trend.','cannot have been misinterpreted',NULL,'"Cannot have been + past participle" = strong negative deduction about past.','hard'),

  -- BLOCK 46: TOEFL Reading
  (cid,46,186,'multiple_choice','[TOEFL Reading] "The findings may challenge conventional assumptions about language acquisition." The modal "may" expresses:','Epistemic possibility — the author is uncertain whether findings will challenge assumptions.','["Obligation to challenge assumptions","Epistemic possibility — the author is uncertain whether findings will challenge assumptions.","Permission to challenge assumptions","Ability to challenge assumptions"]','"May" = epistemic uncertainty: the challenge is possible, not certain.','easy'),
  (cid,46,187,'gap_fill','[TOEFL Reading] "This _____ (must) have been a significant oversight on the part of the early researchers, as the data was publicly available." Best modal form?','must have been',NULL,'"Must have been" = strong past deduction (the speaker is confident it was an oversight).','medium'),
  (cid,46,188,'multiple_choice','[TOEFL Reading] "Critics of the policy argue that it should have been piloted in smaller communities before national rollout." The phrase "should have been piloted" expresses:','A past unfulfilled obligation — in the author''s view, piloting should have happened but did not.','["A future recommendation","Certainty that it was piloted","A past unfulfilled obligation — in the author''s view, piloting should have happened but did not.","An epistemic deduction about the past"]','"Should have been + past participle" = unfulfilled past obligation or missed action.','medium'),
  (cid,46,189,'gap_fill','[TOEFL Reading] "The anomaly _____ (could/explain/passive) by a calibration error in the measuring equipment." Best form?','could be explained / could have been explained',NULL,'"Could be explained" (present possibility) or "could have been explained" (past possibility).','hard'),

  -- BLOCK 47: TOEFL Speaking
  (cid,47,190,'production','[TOEFL Speaking — 45s] Discuss what a government SHOULD do about rising housing costs, what it MUST NOT do, and what COULD be done as alternatives. Use a range of deontic and epistemic modals.','',NULL,'Governments facing rising housing costs must act on both the supply and demand sides of the market simultaneously. On the supply side, planning regulations should be reformed to allow higher-density construction in urban areas, and public land could be made available to social housing developers at below-market rates. Governments must not respond to the crisis by simply inflating demand further through homebuyer subsidies without addressing supply constraints — this has historically proven counterproductive. Tax policy could play a significant role: imposing higher taxes on vacant properties and land banking might discourage speculative behavior. The state should also strengthen tenant protections, as renters are disproportionately vulnerable to rapid market price movements. These measures may not produce immediate results, but they represent a coherent long-term approach.','hard'),
  (cid,47,191,'production','[TOEFL Speaking — 45s] A reading says a scientist may have falsified data. Discuss using epistemic modals (must have, might have, could have, cannot have) to express different degrees of certainty.','',NULL,'The situation described in the reading is deeply troubling but requires careful epistemic caution before any conclusions are drawn. The inconsistencies in the dataset are significant, and they must have arisen from somewhere — whether human error or deliberate manipulation remains unclear. If the data cannot have been accidentally corrupted given the specific pattern of anomalies, then intentional falsification becomes harder to dismiss. However, it is equally possible that the researcher might have made systematic errors in the recording process that produced the observed pattern without any intent to deceive. Several studies could have been affected, which would require independent reanalysis. The scientific community should avoid premature condemnation — a thorough investigation must be conducted before any professional or legal consequences are considered.','hard'),

  -- BLOCK 48: TOEFL Writing
  (cid,48,192,'production','[TOEFL Writing — 150 words] Write a body paragraph on "The ethical responsibilities of AI developers" using deontic modals (must, should, may, must not) and epistemic hedges (might, could, may, should have).','',NULL,'AI developers bear substantial ethical responsibilities that current regulatory frameworks have been slow to address. Developers must disclose the training data and decision-making logic underlying their systems, particularly when those systems are deployed in high-stakes domains such as healthcare, law, or finance. They should conduct rigorous bias audits before deployment and must not release systems that embed discriminatory patterns without providing accessible mechanisms for challenge and correction. Critics have argued that the industry should have adopted these standards voluntarily years ago, before regulatory pressure was required. The consequences of inaction are not merely reputational: systems that make consequential decisions about employment or creditworthiness in ways that are opaque and unchallenged could produce systematically unjust outcomes across millions of cases. Greater transparency might not solve every problem, but it represents an indispensable minimum condition for meaningful public accountability.','hard'),
  (cid,48,193,'production','[TOEFL Writing — Error Correction] Fix modal errors: "Researchers must to disclose all funding. You should have submitted earlier (correct — no fix). The results might explaining the anomaly. Scientists must not never fabricate data. She could helped if she had known."','',NULL,'must to disclose → must disclose (modal + base verb, no ''to''); should have submitted = correct; might explaining → might explain / might have explained (modal + base verb or modal perfect + past participle); must not never → must not / must never (double negative — use one: must not OR must never); could helped → could have helped (past modal: could have + past participle).','hard'),
  (cid,48,194,'production','[TOEFL Writing — 200 words] Write an argument that scientists should communicate more effectively with the public. Use epistemic and deontic modals throughout: must, should, may, might, could, should have, must have, could have.','',NULL,'The relationship between scientific expertise and public understanding has become critically important in an era when evidence-based policymaking is contested and science denial poses genuine risks to public health and environmental governance. Scientists should communicate their findings in accessible language not merely as a courtesy but as a professional obligation — the public, after all, often funds scientific research through taxation and deserves to understand its significance. The scientific community must acknowledge that it has historically communicated primarily within academic circles, largely ignoring the need to build public trust and literacy. Many of the worst episodes of science denial — around vaccines, climate change, and evolutionary biology — might have been less severe had researchers engaged proactively with public concerns rather than dismissing them as ignorance. Scientists could partner with science journalists, educators, and community organizations to ensure that evidence reaches the people most likely to benefit from it. These efforts may not produce immediate results, but they represent an essential investment in the social contract between science and society that must be sustained over the long term.','hard'),
  (cid,48,195,'production','[TOEFL Writing — 200 words] Integrated paragraph: The reading argues that free trade must be protected. The lecture argues trade can be harmful to workers. Use epistemic and deontic modals to represent both positions.','',NULL,'The reading argues that free trade agreements must be protected and expanded, contending that the empirical record demonstrates that open markets increase overall economic welfare. The author insists that governments should resist protectionist impulses, which might benefit specific industries in the short term but will ultimately reduce aggregate productivity and consumer welfare. The lecture, however, challenges this consensus. The professor suggests that the distributional consequences of free trade may be far more severe than aggregate welfare statistics reveal: while national economies could benefit overall, specific communities — particularly those dependent on manufacturing — have suffered steep and largely irreversible job losses. The professor argues that trade policy should have been accompanied by far more robust adjustment programs than were actually implemented, suggesting that the political and social costs of dislocation were systematically underestimated by policymakers and economists who championed liberalization. She contends that future agreements must include enforceable labor and environmental standards if they are to command democratic legitimacy. Without such provisions, trade deals might generate economic benefits for investors while eroding the conditions that support stable and decent employment for workers.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
