-- ============================================================
-- SEED EXT 5: Módulo 08 — Past Perfect (ex 169-248)
-- Tópicos: PP em narrativas acadêmicas, PP para antecipação
-- causal, PP em análise histórica, PP passivo avançado,
-- tarefas TOEFL integradas avançadas
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'past-perfect';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo past-perfect não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 51: Past Perfect em narrativas acadêmicas e análise histórica
  (cid,51,169,'gap_fill','By the time the armistice _____ (sign/passive), the conflict _____ (claim) more than fifteen million lives and _____ (redraw) _____ political map of _____ entire continent.','was signed / had claimed / had redrawn / the / the',NULL,'PP ''had claimed/redrawn'' = completed before PS ''was signed'' (past reference point).','easy'),
  (cid,51,170,'gap_fill','The reforms _____ (prove) more difficult to implement than _____ architects _____ (anticipate) — _____ resistance from entrenched interests _____ (not/factor) into _____ original calculations.','proved / their / had anticipated / the / had not been factored / the',NULL,'PP ''had anticipated/had not been factored'' = prior assessment revealed insufficient at the past event.','medium'),
  (cid,51,171,'gap_fill','Before _____ scientist _____ (publish) her landmark study, _____ field _____ (operate) under _____ assumption that _____ two variables were unrelated — an assumption that _____ (dominate) _____ literature for decades.','the / published / the / had operated / the / the / had dominated / the',NULL,'PP ''had operated/dominated'' = prior state of the field before the publication event.','medium'),
  (cid,51,172,'multiple_choice','Which sentence CORRECTLY uses past perfect to establish temporal sequence?','The committee rejected the proposal because it had failed to address the key concerns raised in the previous consultation.','["The committee rejected the proposal because it failed to address concerns raised.","The committee rejected the proposal because it had failed to address the key concerns raised in the previous consultation.","The committee had rejected the proposal because it fails to address key concerns.","The committee had rejected the proposal because it failed to address concerns."]','PP ''had failed'' = failure in consultation (earlier) → rejection (later). The sequence is grammatically marked.','medium'),
  (cid,51,173,'gap_fill','_____ negotiators _____ (reach) _____ agreement only after both sides _____ (make) significant concessions on _____ issues that _____ (prove) most contentious throughout _____ talks.','The / reached / an / had made / the / had proved / the',NULL,'PP ''had made/proved'' = concessions and contentious issues established before final agreement.','medium'),
  (cid,51,174,'gap_fill','_____ crisis _____ (expose) _____ structural weaknesses that _____ (develop) over years of _____ neglect — weaknesses that _____ (flag/passive) by analysts but _____ (not/address/passive) by policymakers.','The / exposed / the / had developed / regulatory / had been flagged / had not been addressed',NULL,'PP ''had developed/been flagged/not been addressed'' = prior neglect before the crisis exposure.','hard'),
  (cid,51,175,'gap_fill','By _____ end of _____ decade, _____ researchers _____ (establish) conclusively that _____ earlier findings _____ (confound/passive) by _____ methodological artifact, _____ (render) _____ previous policy recommendations questionable.','the / the / the / had established / the / had been confounded / a / rendering / the',NULL,'PP for research timeline: conclusive establishment of what had been confounded.','hard'),

  -- BLOCK 52: Past Perfect para sequência causal em textos acadêmicos
  (cid,52,176,'gap_fill','The failure _____ (stem) from _____ series of decisions that _____ (accumulate) over years: funding _____ (cut/passive), oversight _____ (weaken/passive), and warning signs _____ (ignore/passive).','stemmed / a / had accumulated / had been cut / had been weakened / had been ignored',NULL,'PP causal chain: accumulated decisions → ultimate failure.','medium'),
  (cid,52,177,'gap_fill','When _____ auditors _____ (arrive), they _____ (discover) that _____ accounts _____ (manipulate/passive) systematically and that _____ discrepancies _____ (conceal/passive) through _____ series of fraudulent entries.','the / arrived / discovered / the / had been manipulated / the / had been concealed / a',NULL,'PP ''had been manipulated/concealed'' = completed fraudulent actions discovered at audit.','medium'),
  (cid,52,178,'multiple_choice','Which sentence BEST illustrates past perfect in a causal academic explanation?','The policy failed because the government had not consulted affected communities before drafting the legislation.','["The policy failed because the government did not consult affected communities.","The policy failed because the government had not consulted affected communities before drafting the legislation.","The policy had failed because the government did not consult communities.","The policy failed because the government has not consulted communities."]','PP ''had not consulted'' = omission prior to drafting (prior event) → failure at implementation (later event).','medium'),
  (cid,52,179,'gap_fill','_____ institution _____ (survive) _____ financial crisis because it _____ (build) sufficient capital buffers and _____ (diversify) its portfolio in _____ preceding years — _____ precisely _____ steps that _____ competitors _____ (not/take).','The / survived / the / had built / had diversified / the / the / the / its / had not taken',NULL,'PP contrasts institution that had prepared with competitors that had not — causal explanation for survival.','hard'),
  (cid,52,180,'gap_fill','By _____ time _____ intervention _____ (launch/passive), _____ situation _____ (deteriorate) to _____ point where _____ conventional measures _____ (no longer/prove) effective, _____ (necessitate) _____ more radical approach.','the / the / was launched / the / had deteriorated / a / the / had no longer proved / necessitating / a',NULL,'PP ''had deteriorated/proved'' = prior deterioration necessitated the intervention timing.','hard'),
  (cid,52,181,'gap_fill','_____ scholars _____ (long/argue) that _____ revolution _____ (make) inevitable by _____ structural conditions that _____ (build/passive) over generations, and that _____ immediate triggers, while important, _____ (merely/provide) _____ occasion for _____ change that _____ (become) unavoidable.','Scholars / had long argued / the / had been made / the / had been building / the / had merely provided / the / the / had become',NULL,'PP for historical argument about long-term structural causation.','hard'),
  (cid,52,182,'gap_fill','_____ company''s collapse _____ (shock) _____ markets, but _____ insider investigation later _____ (reveal) that _____ warning signs _____ (present) for years and that _____ board _____ (choose) to _____ (ignore) them in _____ pursuit of _____ short-term profitability.','The / shocked / the / an / revealed / the / had been present / the / had chosen / ignore / the / short-term',NULL,'PP ''had been present/chosen'' = prior evidence and decision before the shocking collapse.','hard'),

  -- BLOCK 53: Past Perfect Passivo em textos acadêmicos formais
  (cid,53,183,'gap_fill','The legislation _____ (draft/passive) by _____ cross-party committee before _____ parliamentary session _____ (begin), ensuring that _____ final text _____ (scrutinize/passive) by _____ broad range of _____ stakeholders.','had been drafted / a / the / began / the / had been scrutinized / a / the',NULL,'PP passive ''had been drafted/scrutinized'' = prior actions completed before session began.','medium'),
  (cid,53,184,'gap_fill','By _____ time _____ evidence _____ (compile/passive) and _____ report _____ (submit/passive), _____ opportunity to _____ (prevent) _____ worst _____ (outcomes) _____ (already/pass).','the / the / had been compiled / the / submitted / the / prevent / the / outcomes / had already passed',NULL,'PP passive chain: compiled, submitted → opportunity already passed.','hard'),
  (cid,53,185,'multiple_choice','Which sentence uses past perfect PASSIVE correctly?','The protocol had been revised three times before it was finally approved by the board.','["The protocol was revised three times before it had been approved by the board.","The protocol revised three times before it was finally approved.","The protocol had been revised three times before it was finally approved by the board.","The protocol has been revised three times before it was finally approved."]','PP passive ''had been revised'' = prior revisions completed before the final approval (past reference).','medium'),
  (cid,53,186,'gap_fill','_____ data _____ (collect/passive) over _____ five-year period, _____ (clean/passive) and _____ (verify/passive) by _____ independent team, and _____ (analyze/passive) using _____ multiple regression framework before _____ results _____ (present/passive) to _____ peer review committee.','The / had been collected / a / cleaned / verified / an / analyzed / a / the / were presented / the',NULL,'PP passive chain of research steps completed before the presentation event.','hard'),
  (cid,53,187,'gap_fill','_____ original proposal _____ (reject/passive) because _____ ethical review committee _____ (not/consult/passive) and _____ appropriate protocols _____ (not/follow/passive) in _____ recruitment of _____ participants.','The / had been rejected / the / had not been consulted / the / had not been followed / the / the',NULL,'PP passive for prior procedural failures leading to rejection.','hard'),
  (cid,53,188,'gap_fill','When _____ inspectors _____ (conduct) _____ follow-up assessment, they _____ (find) that _____ corrective measures _____ (implement/passive) only partially and that several _____ (identify/passive) risks _____ (not/address/passive) in _____ intervening period.','the / conducted / the / found / the / had been implemented / previously / identified / had not been addressed / the',NULL,'PP passive for partial compliance discovered at follow-up assessment.','hard'),

  -- BLOCK 54: Past Perfect em análise de política e argumentação acadêmica
  (cid,54,189,'gap_fill','_____ policy _____ (not/succeed) because _____ government _____ (fail) to _____ (account) for _____ behavioral responses of _____ affected populations, which _____ (render) _____ projected outcomes unrealizable.','The / did not succeed / the / had failed / account / the / the / rendered / the',NULL,'PP ''had failed'' = prior design failure; PS ''rendered'' = consequence.','medium'),
  (cid,54,190,'gap_fill','Historians now _____ (recognize) that _____ peace treaty, though _____ (celebrate/passive) at _____ time, _____ (plant) _____ seeds of future conflict by _____ (ignore) _____ legitimate grievances of _____ defeated parties.','recognize / the / celebrated / the / had planted / the / ignoring / the / the',NULL,'PP ''had planted'' = prior consequence of the treaty recognized retrospectively.','medium'),
  (cid,54,191,'multiple_choice','Which sentence MOST effectively uses past perfect in academic causal analysis?','Analysts later recognized that the crisis had been building for years before the collapse triggered widespread concern.','["Analysts later recognized that the crisis built for years before the collapse.","Analysts later recognized that the crisis had been building for years before the collapse triggered widespread concern.","Analysts later recognized that the crisis has been building for years before the collapse.","Analysts recognized that the crisis would build for years before the collapse."]','PP continuous ''had been building'' = ongoing prior process established before the collapse (past reference).','medium'),
  (cid,54,192,'gap_fill','_____ evidence _____ (suggest) that _____ intervention _____ (arrive) too late — _____ damage _____ (already/do/passive) and _____ institutions that _____ (take) decades to build _____ (weaken/passive) beyond repair.','The / suggested / the / had arrived / the / had already been done / the / had taken / had been weakened',NULL,'PP chain: damage done, institutions weakened — all before the intervention arrived.','hard'),
  (cid,54,193,'gap_fill','What _____ (begin) as _____ localized dispute _____ (escalate) into _____ major crisis because _____ early warning mechanisms _____ (fail) to _____ (detect) _____ pattern of _____ escalation and _____ international community _____ (not/mobilize) until _____ situation _____ (become) unmanageable.','had begun / a / escalated / a / the / had failed / detect / the / the / the / had not mobilized / the / had become',NULL,'PP for prior failure of detection and mobilization before crisis escalated fully.','hard'),
  (cid,54,194,'gap_fill','_____ institutional reforms _____ (prove) insufficient because _____ underlying power structures _____ (not/change) — _____ same actors who _____ (benefit) from _____ old system _____ (manage) to _____ (preserve) their position under _____ new arrangements.','The / proved / the / had not changed / the / had benefited / the / managed / preserve / the',NULL,'PP ''had not changed/benefited'' = prior structural continuity explaining reform failure.','hard'),
  (cid,54,195,'gap_fill','Scholars _____ (debate) whether _____ decision _____ (make) for _____ reasons _____ (cite/passive) or whether _____ leaders _____ (already/commit) to _____ course of action before _____ formal deliberations _____ (begin).','have debated / the / was made / the / cited / the / had already committed / a / the / began',NULL,'PP ''had already committed'' = prior decision suspected before formal process began.','hard'),

  -- BLOCK 55: TOEFL Reading avançado com Past Perfect
  (cid,55,196,'multiple_choice','[TOEFL Reading] ''By the time the reforms were enacted, the economic damage had already exceeded initial projections.'' What does ''had already exceeded'' communicate?','The damage was completed and surpassed projections before the past reference point (enactment of reforms).','["The damage happened after the reforms","The damage was completed and surpassed projections before the past reference point (enactment of reforms).","The damage is still ongoing","The damage might happen in the future"]','PP ''had already exceeded'' = action completed before past reference point ''were enacted.''','easy'),
  (cid,55,197,'gap_fill','[TOEFL Reading] ''The treaty _____ (establish) _____ framework for cooperation that _____ (elude) _____ parties for _____ preceding generation.'' Best forms?','established / a / had eluded / the / the',NULL,'PS ''established'' for historical narrative; PP ''had eluded'' for prior failed attempts before the treaty.','medium'),
  (cid,55,198,'multiple_choice','[TOEFL Reading] ''Researchers discovered that the compound had already been synthesized by a team working independently in another country.'' The PP ''had already been synthesized'' indicates:','The synthesis was completed (by the other team) before the discovery moment.','["The synthesis happened after the discovery","The synthesis happened at the same time","The synthesis was completed (by the other team) before the discovery moment.","The synthesis is planned for the future"]','PP passive ''had already been synthesized'' = completed prior to ''discovered'' (past reference point).','easy'),
  (cid,55,199,'gap_fill','[TOEFL Reading] ''When _____ investigation _____ (conclude), it _____ (become) clear that _____ regulations _____ (not/update/passive) in response to _____ changed conditions and that _____ risks _____ (assess/passive) inadequately.'' Best forms?','the / concluded / became / the / had not been updated / the / had been assessed',NULL,'PP passive ''had not been updated/had been assessed'' = prior regulatory failures revealed by investigation.','hard'),
  (cid,55,200,'gap_fill','[TOEFL Reading] ''_____ transformation _____ (be) more profound than _____ observers _____ (anticipate): _____ technology that _____ (promise) incremental improvement _____ (instead/produce) _____ paradigm shift that _____ (reshape) _____ entire field.'' Best forms?','The / was / most / had anticipated / a / had promised / instead produced / a / reshaped / the',NULL,'PP ''had anticipated/promised'' = prior expectation vs. actual outcome; PS for narrative events.','hard'),

  -- BLOCK 56: TOEFL Speaking avançado com Past Perfect
  (cid,56,201,'production','[TOEFL Speaking — 45s] A reading describes a historical scientific breakthrough. Use past perfect to show sequence.','',NULL,'The reading describes the discovery of the structure of DNA as one of the most consequential scientific breakthroughs of the twentieth century, and the sequence of events leading to it illustrates the cumulative nature of scientific knowledge. By the time Watson and Crick published their model in 1953, other researchers had already assembled much of the crucial evidence: Rosalind Franklin had produced X-ray crystallography images that revealed the helical structure, and Erwin Chargaff had established the base-pairing rules that turned out to be essential to the model. Watson and Crick had visited Franklin''s laboratory and had seen her data, a fact that had remained controversial for decades. The double helix model succeeded where previous proposals had failed because it integrated evidence that had been gathered by multiple researchers working independently. The reading notes that the Nobel Prize awarded in 1962 had not included Franklin, who had died in 1958 — a decision that had generated lasting criticism about how the scientific establishment had treated women researchers.','hard'),
  (cid,56,202,'production','[TOEFL Speaking — 45s] A professor discusses why an economic reform program failed. Use past perfect throughout.','',NULL,'The professor explains that the economic reform program failed for reasons that had been apparent to critics long before the program was abandoned. She argues that the architects of the program had underestimated the social costs of rapid liberalization and had overestimated the institutional capacity of the government to implement the required changes simultaneously. By the time the program was suspended, unemployment had risen to levels that had not been seen since the Great Depression, and the social safety net that had existed before the reforms had been dismantled without adequate replacement structures being put in place. The professor also notes that the international advisors who had designed the program had applied a template that had been developed for different economic contexts, and that they had not adequately studied the specific institutional conditions that had shaped this economy. She concludes that the experience had demonstrated that economic reforms that had not been sequenced carefully and supported by adequate social protection were likely to generate the kind of political backlash that had ultimately derailed the program.','hard'),

  -- BLOCK 57: TOEFL Writing avançado com Past Perfect
  (cid,57,203,'production','[TOEFL Writing — 200 words] Write a paragraph on the causes of a historical crisis using past perfect to establish sequence.','',NULL,'The financial crisis of 2008 was the result of a set of interconnected failures that had been developing for years before the dramatic events of September 2008 brought them to public attention. Financial institutions had accumulated enormous exposures to mortgage-backed securities whose underlying risk had been systematically underestimated by rating agencies that had developed inadequate models and had faced perverse incentive structures that rewarded the assignment of high ratings. Regulators had permitted the growth of a shadow banking system that had escaped the capital requirements and oversight that had been imposed on traditional banks after the lessons of earlier crises. Monetary policy had maintained interest rates at historically low levels for an extended period, and the resulting search for yield had driven investors toward instruments that had been structured to obscure their true risk profiles. Warning signals had been raised by several analysts and economists, but their concerns had not been incorporated into the mainstream risk assessments that had guided institutional behavior. By the time policymakers recognized the severity of the situation, the interconnections that had developed between financial institutions meant that the failure of one major institution had the potential to cascade through the system in ways that had not been anticipated even in the most pessimistic scenario analyses.','hard'),
  (cid,57,204,'production','[TOEFL Writing — 200 words] Write a paragraph on why a social movement succeeded, using past perfect to explain the historical context.','',NULL,'The success of the civil rights movement in the United States in the 1960s can only be understood in the context of the conditions that had developed over the preceding decades and that had created both the urgency and the opportunity for transformative change. African Americans had fought in two World Wars and had returned to a country that had denied them the rights they had risked their lives to defend — an experience that had radicalized a generation and had generated a moral claim that had proved increasingly difficult for liberal opinion to ignore. The Great Migration had moved millions of African Americans to northern cities where they had developed economic resources, organizational capacity, and political influence that had been impossible in the rural South. The Cold War had created an international context in which the gap between American democratic ideals and the reality of racial segregation had become a significant liability in the competition for the allegiance of newly independent nations in Africa and Asia. Television had created a mass audience for the images of peaceful protesters being met with police violence — images that had shocked the conscience of white Americans who had previously remained largely indifferent to the realities of segregation. All of these factors had converged to make the civil rights legislation of the mid-1960s both possible and, given the movement''s extraordinary moral and organizational capacity, ultimately inevitable.','hard'),

  -- BLOCK 58: TOEFL Writing — Past Perfect em análise comparativa
  (cid,58,205,'production','[TOEFL Writing — 200 words] Compare two countries'' approaches to pandemic response. Use past perfect to establish prior preparedness.','',NULL,'The divergence in COVID-19 outcomes between countries that had invested heavily in pandemic preparedness infrastructure and those that had not was one of the most instructive aspects of the global response to the pandemic. Countries that had developed robust public health surveillance systems, had stockpiled personal protective equipment, and had maintained surge capacity in their healthcare systems were able to respond more quickly and effectively to the initial outbreak than those whose pandemic preparedness had been allowed to atrophy after the urgency of previous health emergencies had faded from political memory. Some East Asian countries that had experienced SARS in 2003 had drawn lessons from that experience and had invested in contact tracing capacity and public communication systems that had proved crucial in the early weeks of COVID-19. In contrast, several high-income countries that had historically ranked highly on pandemic preparedness indices had allowed their readiness to deteriorate, had failed to maintain adequate stockpiles, and had not conducted the exercises and planning processes that might have identified gaps in their response capacity. The result was that countries whose per capita income and healthcare spending might have predicted strong performance had sometimes fared worse than lower-income countries that had prioritized preparedness more consistently. This experience had reinforced the argument that pandemic preparedness required sustained investment rather than the surge-and-neglect cycle that had characterized many governments'' approach.','hard'),
  (cid,58,206,'production','[TOEFL Writing — 200 words] Write a paragraph on how colonial history had shaped post-independence development trajectories.','',NULL,'The development trajectories of post-independence nations in Africa and Asia cannot be understood without reference to the colonial structures that had shaped their economies, institutions, and social organization in ways that had persisted long after formal independence was achieved. Colonial administrations had extracted resources and had oriented economic activity toward the needs of the metropolitan power rather than toward the development of domestic productive capacity, had maintained infrastructure primarily to facilitate resource extraction rather than to connect domestic markets, and had trained a professional class in numbers adequate to staff the lower levels of the colonial bureaucracy but had deliberately limited access to the education that would have prepared Africans and Asians for senior leadership roles. The borders that had been drawn by colonial powers had often grouped together peoples with different languages, cultures, and economic interests and had divided communities and peoples that had historical ties, creating the conditions for the ethnic and regional tensions that had complicated governance in many post-independence states. The institutions of governance that had been bequeathed at independence had been designed for colonial administration rather than for democratic self-governance and had been ill-suited to the tasks of national development. These legacies had not determined post-independence outcomes — the variation in development performance among former colonial states had demonstrated the importance of post-independence choices — but they had shaped the constraints within which those choices had been made.','hard'),

  -- BLOCK 59: TOEFL Writing — síntese complexa com Past Perfect
  (cid,59,207,'production','[TOEFL Writing — 200 words] Write a synthesis paragraph on technological change and social disruption using past perfect.','',NULL,'The relationship between technological change and social disruption is not a new phenomenon, and examining the historical record reveals that previous waves of transformative technology had generated similar patterns of disruption, adjustment, and ultimately transformation that may offer lessons for understanding contemporary technological change. The Industrial Revolution had displaced millions of workers from traditional occupations and had concentrated them in urban environments that had been wholly unprepared for their arrival, generating social dislocations — from the destruction of family and community structures to the emergence of new forms of poverty and disease — that had eventually produced political responses in the form of labor legislation, public health infrastructure, and social insurance. The electrification of industry and the adoption of the internal combustion engine had similarly destroyed existing industries and occupational structures while creating new ones, and the adjustment had taken decades and had required substantial institutional innovation. What these historical transitions had demonstrated was that the trajectory of technological change had not been technologically determined — the institutions, policies, and distributional arrangements that had governed each transition had substantially shaped its social consequences. The lesson for contemporary policymakers was not that disruption could be prevented, but that the choices made about how to manage it had historically determined whether technological change had produced broad prosperity or concentrated gains alongside widespread dislocation.','hard'),
  (cid,59,208,'production','[TOEFL Speaking — 60s] Why had the international community failed to prevent a specific humanitarian crisis? Use past perfect throughout.','',NULL,'The failure to prevent the Rwandan genocide of 1994 represents one of the most thoroughly examined failures of international response in recent history, and the analysis of why the international community had failed reveals a combination of institutional limitations, political calculations, and failures of will that had converged to produce catastrophic inaction. By the time the genocide began, intelligence agencies had received multiple warnings that mass violence was being planned, but this information had not been acted upon. The United Nations had stationed a peacekeeping force in Rwanda, but its commander, General Roméo Dallaire, had been denied permission to take the preemptive action against weapons caches that might have disrupted the planning for violence, despite his having warned his superiors explicitly about what was being prepared. Permanent members of the Security Council had been reluctant to authorize stronger action because they had recently experienced costly interventions in Somalia and had concluded that the political costs of African peacekeeping operations outweighed the strategic benefits. The term ''genocide'' had been deliberately avoided in official communications because officials had understood that using it would have triggered legal obligations under the Genocide Convention that major powers had not been willing to fulfill. By the time the scale of the violence had become undeniable, approximately 800,000 people had been killed, and the international community had stood by as one of the most rapid mass atrocities in history had unfolded.','hard'),

  -- BLOCK 60: Exercícios finais avançados de Past Perfect
  (cid,60,209,'gap_fill','_____ structural adjustment programs _____ (implement/passive) without adequate attention to _____ social costs that _____ (warn/passive) about by _____ critics who _____ (study) _____ outcomes of similar programs elsewhere.','The / had been implemented / the / had been warned / the / had studied / the',NULL,'PP passive chain: programs implemented without heeding prior warnings from prior research.','hard'),
  (cid,60,210,'gap_fill','What _____ (begin) as _____ technical dispute _____ (evolve) into _____ constitutional crisis because _____ underlying tensions _____ (build) for years and _____ institutional mechanisms _____ (not/design/passive) to _____ (handle) _____ scale of _____ disagreement that _____ (emerge).','had begun / a / evolved / a / the / had been building / the / had not been designed / handle / the / the / had emerged',NULL,'PP ''had begun/been building/not been designed/emerged'' = prior origins and failures before the crisis.','hard'),
  (cid,60,211,'gap_fill','_____ international agreement _____ (reach/passive) only after _____ parties _____ (exhaust) _____ range of _____ alternative approaches and _____ (recognize) that _____ disagreements _____ (prove) impossible _____ (resolve) through _____ conventional _____ (negotiate).','An / was reached / the / had exhausted / the / the / had recognized / the / had proved / to resolve / conventional / negotiation',NULL,'PP for exhausted alternatives and recognized failure before agreement was reached.','hard'),
  (cid,60,212,'gap_fill','_____ evaluation _____ (reveal) that _____ program _____ (deliver) significantly fewer _____ benefits than _____ (project/passive), that _____ costs _____ (exceed) _____ original budget by _____ substantial margin, and that _____ monitoring mechanisms _____ (not/function/passive) as _____ (intend/passive).','The / revealed / the / had delivered / the / had been projected / the / had exceeded / the / a / the / had not been functioning / intended',NULL,'PP for prior failures in delivery, cost, and monitoring revealed by evaluation.','hard'),
  (cid,60,213,'multiple_choice','[TOEFL Reading] Which sentence MOST effectively uses past perfect to explain a historical outcome?','The peace negotiations collapsed because both sides had failed to build the domestic political support needed for compromise.','["The peace negotiations collapsed because both sides failed to build domestic support.","The peace negotiations collapsed because both sides had failed to build the domestic political support needed for compromise.","The peace negotiations had collapsed because both sides failed to build support.","The peace negotiations collapsed because both sides have failed to build support."]','PP ''had failed'' = prior failure to build support (before the collapse) = correctly establishes temporal sequence.','medium'),
  (cid,60,214,'production','[TOEFL Writing — 200 words] Write a paragraph on environmental degradation using past perfect to show cumulative damage.','',NULL,'The environmental crisis that prompted the sweeping legislative response of the 1970s in many high-income countries was the product of decades of industrialization during which the environmental consequences of economic growth had been treated as externalities unworthy of regulatory attention. By the time environmental legislation began to be enacted in earnest, rivers that had once supported abundant aquatic life had been poisoned by industrial effluent that had been discharged for decades with little restriction. Urban air quality had deteriorated to levels that had been documented to cause measurable increases in respiratory disease, yet the political will to impose costs on industry had developed only slowly and had required the evidence of severe and visible harm to mobilize. Species had been pushed to the brink of extinction by habitat destruction, hunting, and pesticide use, and the full ecological consequences of these pressures had not yet been understood when the damage had already been done. Forests that had taken centuries to develop had been cleared within decades, and the soils that had been exposed had eroded rapidly, generating downstream sedimentation that had damaged fisheries and water supplies. The environmental movement that had emerged in response to these visible crises had succeeded in placing environmental protection on the political agenda, but it had done so in a context where much of the damage that could most easily have been prevented had already occurred.','hard'),

  -- BLOCK 61 (final): Past Perfect em estruturas mais complexas
  (cid,61,215,'gap_fill','_____ analysis _____ (demonstrate) that _____ intervention _____ (not/achieve) _____ intended _____ outcomes because _____ baseline conditions _____ (assess/passive) incorrectly and _____ implementation strategy _____ (design/passive) on _____ basis of _____ flawed assumptions.','The / demonstrated / the / had not achieved / its / intended / the / had been assessed / the / had been designed / the / flawed',NULL,'PP ''had not achieved/been assessed/been designed'' = prior failures in design and assessment.','hard'),
  (cid,61,216,'gap_fill','What _____ (start) as _____ experiment in _____ decentralized governance _____ (become) _____ model _____ (replicate/passive) across _____ region, _____ (demonstrate) that _____ approach that _____ (dismiss/passive) as _____ impractical by _____ skeptics _____ (prove) its value under _____ real-world conditions.','had started / an / decentralized / became / a / replicated / the / demonstrating / an / had been dismissed / the / had proved / real-world',NULL,'PP ''had started/been dismissed/proved'' = prior origins and skepticism before the model succeeded.','hard'),
  (cid,61,217,'gap_fill','_____ reforms _____ (introduce/passive) too rapidly and without _____ broad consultative process that _____ (accompany) successful reforms elsewhere — _____ mistake that _____ (cost) _____ government _____ political _____ capital it _____ (need) to _____ (sustain) _____ program through _____ inevitable difficulties of _____ implementation.','The / had been introduced / the / had accompanied / a / had cost / the / the / capital / had needed / sustain / the / the / implementation',NULL,'PP ''had been introduced/accompanied/cost/needed'' = chain of prior actions and their consequences.','hard'),
  (cid,61,218,'production','[TOEFL Speaking — 60s] A reading argues that previous attempts to reform this institution had all failed for similar reasons. Summarize using past perfect throughout.','',NULL,'The reading makes a compelling and somewhat sobering argument that all previous attempts to reform the institution had ultimately failed for reasons that were structurally similar, suggesting that the reformers who had attempted change had not adequately understood the sources of resistance they faced. According to the reading, each wave of reform had been initiated in response to a crisis that had temporarily weakened the position of established interests, but once the immediate urgency of the crisis had passed, those interests had reassembled and had succeeded in limiting or reversing the changes that had initially been introduced. The reformers had typically had access to political leadership and had succeeded in enacting formal legislative or regulatory changes, but they had underestimated the capacity of entrenched actors to shape implementation in ways that had hollowed out the intent of the reforms without formally violating their letter. Earlier reformers had also failed to build the broad coalitions that might have sustained pressure for change over the long implementation periods that genuine institutional reform required, and had relied too heavily on technical design solutions to problems that had been fundamentally political in nature. The reading concludes that any future reform effort would need to learn from these failures by building broader support, maintaining sustained pressure through implementation, and addressing the political economy of resistance rather than treating it as a secondary concern.','hard'),
  (cid,61,219,'gap_fill','By _____ end of _____ conflict, _____ social fabric that _____ (take) generations to _____ (build) _____ (tear/passive), institutions that _____ (once/provide) _____ basic public services _____ (collapse), and _____ sense of _____ common _____ purpose that _____ (bind) _____ diverse _____ population _____ (shatter/passive).','the / the / the / had taken / build / had been torn / had once provided / the / had collapsed / a / common / purpose / had bound / a / had been shattered',NULL,'PP chain for cumulative destruction by end of conflict: torn, collapsed, shattered.','hard'),
  (cid,61,220,'gap_fill','_____ negotiators _____ (concede) more than they _____ (intend) because _____ alternative — _____ collapse of _____ talks — _____ (consider/passive) _____ (unacceptable) _____ given _____ pressures that _____ (build) over _____ preceding weeks.','The / conceded / had intended / the / the / had been considered / unacceptable / given / the / had been building / the',NULL,'PP ''had intended/been considered/been building'' = prior positions and pressures before the concession.','hard'),
  (cid,61,221,'gap_fill','_____ tribunal _____ (find) that _____ state _____ (breach) its obligations under _____ treaty by _____ (fail) to _____ (protect) _____ investors who _____ (rely) on _____ regulatory framework that _____ (subsequently/dismantle/passive) without _____ adequate compensation.','The / found / the / had breached / the / failing / protect / the / had relied / the / had subsequently been dismantled / adequate',NULL,'PP ''had breached/relied/been dismantled'' = prior treaty breach and investor reliance.','hard'),
  (cid,61,222,'gap_fill','_____ intervention that _____ (design/passive) to _____ (address) _____ specific market failure _____ (instead/create) _____ series of _____ distortions that _____ (prove) more _____ costly than _____ original problem it _____ (intend/passive) to _____ (solve).','An / had been designed / address / a / instead created / a / distortions / proved / more / the / had been intended / solve',NULL,'PP ''had been designed/intended'' = prior design intent contrasted with unintended outcome.','hard'),
  (cid,61,223,'gap_fill','What _____ analysts _____ (once/dismiss) as _____ peripheral concern _____ (emerge) as _____ central issue precisely because _____ established _____ frameworks _____ (not/develop/passive) _____ tools _____ (needed) to _____ (analyze) it _____ adequately.','the / had once dismissed / a / emerged / a / the / established / had not been developed / the / needed / analyze / adequately',NULL,'PP ''had once dismissed/not been developed'' = prior dismissal and analytical gap.','hard'),
  (cid,61,224,'gap_fill','By _____ time _____ second review _____ (complete/passive), it _____ (become) apparent that _____ recommendations of _____ first review _____ (not/implement/passive) systematically, that _____ resources _____ (allocate/passive) to _____ wrong priorities, and that _____ opportunity for _____ early correction _____ (miss/passive).','the / the / was completed / became / the / the / had not been implemented / the / had been allocated / the / the / had been missed',NULL,'PP passive chain for prior failures in implementation revealed by second review.','hard'),
  (cid,61,225,'gap_fill','_____ scholar _____ (note) that _____ concept _____ (evolve) significantly since _____ (introduce/passive) — what _____ (begin) as _____ narrow _____ (technical) framework _____ (broaden) to _____ (encompass) _____ range of _____ dimensions that _____ original _____ theorists _____ (not/anticipate).','The / noted / the / had evolved / it was introduced / had begun / a / technical / had broadened / encompass / a / dimensions / the / original / had not anticipated',NULL,'PP ''had evolved/begun/broadened/not anticipated'' = intellectual history of concept development.','hard'),
  (cid,61,226,'production','[TOEFL Writing — Final 200 words] Reflect on what factors had made a historical peace agreement possible, using past perfect throughout.','',NULL,'The conditions that made a landmark peace agreement possible had been created by a confluence of factors that had developed over years and that had gradually shifted the cost-benefit calculations of all parties sufficiently to make negotiation preferable to continued conflict. The military stalemate that had developed after years of fighting had persuaded both sides that further violence was unlikely to produce the decisive victory that each had originally anticipated. The economic costs of the conflict had accumulated to levels that had begun to undermine the domestic political support that leaders on both sides had depended upon to sustain the war effort. External actors whose support had been essential to the conflict had signaled that they were no longer willing to provide the resources that had kept it going, confronting the parties with a choice between negotiation and a deterioration of their military position. A small group of individuals on both sides who had maintained informal contacts throughout the conflict had built sufficient mutual trust to explore whether a negotiated outcome was possible, and the back-channel conversations they had conducted had identified a zone of potential agreement that formal negotiation had subsequently elaborated into the final text. The diplomatic groundwork that had been laid over years, the changed military and economic realities, and the relationships that key individuals had cultivated across the divide had all been necessary for the agreement that was ultimately reached.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
