-- ============================================================
-- SEED EXT 4: Módulo 05 — Future Simple (ex 141-220)
-- Novos tópicos: futuro formal em documentos, futuro perifrástico
-- avançado, futuro perfeito/contínuo em TOEFL
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'future-simple';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo future-simple não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 41: futuro em documentos formais (contratos, políticas)
  (cid,41,141,'gap_fill','The contractor _____ (deliver) the completed project no later than 31 December 2025.','will deliver',NULL,'"Will" in contracts and formal commitments = binding future obligation.','easy'),
  (cid,41,142,'gap_fill','All participants _____ (receive) a written summary of the findings upon completion of the study.','will receive',NULL,'"Will" for guaranteed future action in research/consent contexts.','easy'),
  (cid,41,143,'multiple_choice','In formal documents (contracts, policies), which modal is used for future obligations?','"Shall" (most formal) or "will" (standard formal).','["Might","Would","''Shall'' (most formal) or ''will'' (standard formal).","Going to"]','"Shall" = legal/formal obligation future. "Will" = standard formal commitment.','medium'),
  (cid,41,144,'gap_fill','The Policy _____ (come into effect) on 1 January 2026 and _____ (apply) to all employees.','will come into effect / will apply',NULL,'Future simple for policy implementation and scope.','easy'),
  (cid,41,145,'gap_fill','Any disputes arising under this agreement _____ (resolve/passive) through binding arbitration.','will be resolved',NULL,'"Will be + past participle" = future passive for policy procedures.','medium'),
  (cid,41,146,'multiple_choice','In a research proposal, which future form expresses a COMMITMENT to carry out an action?','The study will recruit 200 participants from five cities.','["The study might recruit 200 participants from five cities.","The study could recruit 200 participants from five cities.","The study will recruit 200 participants from five cities.","The study would recruit 200 participants from five cities."]','"Will" = commitment/promise in proposals. "Might/could" = mere possibility.','easy'),

  -- BLOCK 42: futuro perfeito (will have + PP)
  (cid,42,147,'gap_fill','By 2050, the global population _____ (reach) approximately 10 billion people.','will have reached',NULL,'"Will have + past participle" = future perfect for completion by a future point.','hard'),
  (cid,42,148,'multiple_choice','What does "will have completed" express?','An action that will be finished before a specified future time.','["A future habit","An action that will be finished before a specified future time.","A past completed action","A future continuous action"]','Future perfect = completed before a future point.','medium'),
  (cid,42,149,'gap_fill','By the time the committee _____ (meet) next month, the research team _____ (analyze) all 500 responses.','meets / will have analyzed',NULL,'Time clause (present simple) + future perfect result.','hard'),
  (cid,42,150,'gap_fill','Scientists project that by 2100, sea levels _____ (rise) by between 0.5 and 1.5 meters above today''s levels.','will have risen',NULL,'Future perfect for projected cumulative change by a future point.','hard'),
  (cid,42,151,'multiple_choice','Which sentence uses future perfect CORRECTLY?','If the current deforestation rate continues, the Amazon will have lost 25% of its remaining forest cover by 2050.','["If the current deforestation rate continues, the Amazon will lose 25% by 2050 (future simple — also acceptable but less precise about completion).","If the current deforestation rate continues, the Amazon will have lost 25% of its remaining forest cover by 2050.","If the current deforestation rate continues, the Amazon has lost 25% by 2050 (wrong tense).","If the current deforestation rate continues, the Amazon would have lost 25% by 2050 (conditional — wrong)."]','Future perfect in academic projections: will have + PP by [future date].','hard'),

  -- BLOCK 43: futuro contínuo (will be + -ing)
  (cid,43,152,'gap_fill','This time next year, researchers _____ (analyze) the second wave of data.','will be analyzing',NULL,'"Will be + -ing" = future continuous: action in progress at a future point.','hard'),
  (cid,43,153,'multiple_choice','When do we use future continuous instead of future simple?','To emphasize that an action will be in progress at a specific future time, or to describe a planned arrangement.','["They are always interchangeable","To emphasize that an action will be in progress at a specific future time, or to describe a planned arrangement.","Future continuous is always more formal","Future simple is for predictions; continuous is for facts"]','"Will be doing" = future action in progress at a time (more vivid/precise than "will do").','medium'),
  (cid,43,154,'gap_fill','Don''t call between 9 and 11 — the team _____ (run) the final experiment during that time.','will be running',NULL,'Future continuous for planned activity in progress at a future time.','medium'),
  (cid,43,155,'gap_fill','Over the coming decade, companies _____ (increasingly/deploy) AI systems to automate decision-making.','will increasingly be deploying / will increasingly deploy',NULL,'Future continuous for ongoing future trend.','hard'),
  (cid,43,156,'multiple_choice','Which sentence uses future perfect continuous CORRECTLY?','By the time the study concludes, researchers will have been collecting data for three years.','["By the time the study concludes, researchers will have been collecting data for three years.","By the time the study concludes, researchers are collecting data for three years.","By the time the study concludes, researchers will collect data for three years.","By the time the study concludes, researchers will have collected data for three years (future perfect — also correct but emphasizes completion not duration)."]','Future perfect continuous (will have been + -ing) = duration up to a future point.','hard'),

  -- BLOCK 44: futuro perifrástico avançado (is due to / is set to / is projected to)
  (cid,44,157,'gap_fill','The report _____ (due/release/passive) on Friday after months of expert review.','is due to be released',NULL,'"Is due to be + past participle" = scheduled future passive.','hard'),
  (cid,44,158,'gap_fill','Global renewable capacity _____ (set/double) by 2030, according to IEA projections.','is set to double',NULL,'"Is set to + base verb" = formal future prediction (strong likelihood).','hard'),
  (cid,44,159,'gap_fill','Carbon emissions from the aviation sector _____ (project/triple/passive) between 2020 and 2050 unless radical new technologies are deployed.','are projected to triple',NULL,'"Are projected to + base verb" = formal academic future projection.','hard'),
  (cid,44,160,'multiple_choice','Which periphrastic future is MOST formal in academic writing?','Carbon concentrations are expected to exceed 500 ppm by the end of the century.','["Carbon concentrations are going to exceed 500 ppm by the end of the century.","Carbon concentrations will probably exceed 500 ppm by the end of the century.","Carbon concentrations are expected to exceed 500 ppm by the end of the century.","Carbon concentrations might exceed 500 ppm by the end of the century."]','"Are expected to" = formal, hedged academic future projection.','hard'),
  (cid,44,161,'gap_fill','The merger _____ (complete/passive) within the next 90 days, subject to regulatory approval.','is expected to be completed / is due to be completed',NULL,'Formal future passive for business transaction timeline.','hard'),
  (cid,44,162,'gap_fill','Ocean pH _____ (project/drop) by a further 0.3–0.4 units by 2100 if emissions continue at current rates.','is projected to drop',NULL,'Academic future projection for environmental science.','hard'),

  -- BLOCK 45: TOEFL Reading
  (cid,45,163,'multiple_choice','[TOEFL Reading] "By 2030, electric vehicles will account for more than half of all new car sales globally." The future "will account" expresses:','A prediction about a future proportion.','["A past trend","A conditional possibility","A prediction about a future proportion.","A scheduled event"]','Future simple for a future prediction.','easy'),
  (cid,45,164,'gap_fill','[TOEFL Reading] "If current trends continue, the global demand for water _____ (increase) by 55% by 2050." Best future form?','will have increased / will increase',NULL,'Future perfect or future simple for cumulative projected change.','medium'),
  (cid,45,165,'multiple_choice','[TOEFL Reading] "The population of Sub-Saharan Africa is projected to double by 2050." "Is projected to double" is used to:','Hedge the prediction — it is based on demographic modeling, not certainty.','["Express a definite plan","Hedge the prediction — it is based on demographic modeling, not certainty.","Describe a past trend","Express immediate intention"]','"Is projected to" = formal hedged future (model-based, not certain).','medium'),
  (cid,45,166,'gap_fill','[TOEFL Reading] "By the time effective treatments are developed, the disease _____ (already/spread) to several additional countries." Best future perfect?','will have already spread',NULL,'Future perfect + "already" for prior completion before a future milestone.','hard'),
  (cid,45,167,'multiple_choice','[TOEFL Reading] "The dam is due to be completed in 2027." "Is due to be completed" expresses:','A scheduled future passive event.','["A current incomplete action","A past event","A scheduled future passive event.","An obligation"]','"Is due to be + past participle" = scheduled future passive.','medium'),

  -- BLOCK 46: TOEFL Speaking
  (cid,46,168,'production','[TOEFL Speaking — 45s] Predict the future of remote work in 5 and 10 years. Use: will, will have + PP, will be + -ing, is expected to, is projected to.','',NULL,'In five years, remote and hybrid work arrangements will have become the norm for a majority of knowledge workers in developed economies. Companies will have redesigned their office spaces to function as collaboration hubs rather than daily workplaces. Over the next decade, AI-powered virtual collaboration tools will continue improving, making synchronous online interaction increasingly indistinguishable from in-person meetings in terms of quality. The share of the workforce working fully remotely is projected to stabilize at around 20-25%, though this will vary significantly by sector and region. By 2035, workers who have spent their entire careers in hybrid environments will have become the majority of the workforce, making traditional nine-to-five, five-days-a-week office culture a minority experience.','hard'),
  (cid,46,169,'production','[TOEFL Speaking — 45s] A reading predicts that automation will eliminate millions of jobs by 2040. Discuss using: will, will have + PP, are projected to, unless, may/might for hedging.','',NULL,'The reading''s projection that automation will eliminate tens of millions of jobs by 2040 is consistent with several major forecasting reports from institutions such as the McKinsey Global Institute and the World Economic Forum. By 2040, an estimated 300 to 800 million workers worldwide may have been displaced from their current roles as AI and robotics systems become cheaper and more capable than human labor across a widening range of tasks. However, the net employment effect is less certain: new occupations will also have been created, and history suggests that technological displacement is not the same as permanent unemployment. That said, the transition will be painful for many workers in occupations that are projected to shrink rapidly, unless education and retraining systems are redesigned at significant scale and speed.','hard'),

  -- BLOCK 47: TOEFL Writing
  (cid,47,170,'production','[TOEFL Writing — 150 words] Write a body paragraph predicting the future of higher education. Use: will, will have + PP, will be + -ing, is expected to, and hedged futures (may/might).','',NULL,'Higher education will undergo dramatic transformation over the next two decades as digital technology, demographic change, and shifting labor market demands reshape the sector. Traditional four-year residential degree programs will remain valued, but their share of total learning activity is expected to decline as shorter, more flexible credential pathways expand. By 2040, millions of students will have completed their first degree through hybrid or fully online programs that combine the flexibility of digital delivery with periodic in-person cohort experiences. Artificial intelligence will be playing an increasingly significant role in personalizing learning pathways, providing instant feedback, and assessing a wider range of competencies than conventional examinations can capture. The economics of higher education will also have shifted: institutions that cannot offer demonstrable labor market outcomes at reasonable cost may find it increasingly difficult to justify traditional pricing structures.','hard'),
  (cid,47,171,'production','[TOEFL Writing — Error Correction] Fix future tense errors: "By 2050 the population will reach 10 billion (also correct as future simple — no fix needed OR specify will have reached for completion). Scientists are going to discover a cure for cancer next decade. The report is due release Friday. Carbon emissions will have triple by 2100. This time next year, we finish the project."','',NULL,'will reach / will have reached = both defensible for "by 2050" — no change strictly needed, but "will have reached" is more precise for completion; are going to discover = debatable, but ''next decade'' suggests speculative prediction → ''will discover'' is more natural; is due release → is due to be released (is due to + base verb or is due to be + PP for passive); will have triple → will have tripled (future perfect: will have + past participle); we finish → we will have finished / we will be finishing / we will finish (simple future or future continuous for specific future point).','hard'),

  -- BLOCK 48: Consolidação final
  (cid,48,172,'production','[TOEFL Writing — 200 words] Write an essay body paragraph predicting the effects of climate change on coastal cities by 2100. Use: will (prediction), will have + PP (future perfect), will be + -ing (future continuous), is projected to (formal hedge), unless (conditional).','',NULL,'Coastal cities face an uncertain but potentially devastating future as sea levels rise and storm surges intensify. By 2100, global mean sea levels will have risen by between 0.5 and 1.5 meters compared with current levels, a range that reflects profound uncertainty in the rate of ice sheet destabilization in Greenland and West Antarctica. Many low-lying coastal cities — including Miami, Jakarta, and Alexandria — will be experiencing regular flooding in areas that are currently residential and commercial zones. Tens of millions of people who are living in these areas today will have relocated or will be planning to do so by the second half of the century, representing one of the largest managed or forced migrations in human history. Global infrastructure investment in coastal protection is projected to reach trillions of dollars annually by the 2060s, as governments attempt to protect assets that cannot easily be relocated. Unless emissions are dramatically reduced by mid-century, the more severe scenarios for sea-level rise — those involving major ice sheet collapse — will become significantly more probable, potentially committing many of the world''s largest coastal cities to eventual inundation.','hard'),
  (cid,48,173,'production','[TOEFL Writing — 200 words] Write an introduction to an essay on "The role of international agreements in addressing global challenges." Use future tense for the essay''s own argument: will argue, will examine, will demonstrate.','',NULL,'International cooperation has become indispensable for addressing the category of challenges — climate change, pandemic preparedness, nuclear non-proliferation, and digital governance — that by definition cannot be managed effectively within the borders of any single nation. Yet the institutions designed to facilitate such cooperation frequently appear inadequate to the scale of the challenges they face: slow to respond, constrained by sovereignty concerns, and poorly adapted to the speed at which transnational threats evolve. This essay will argue that the existing framework of international agreements, while imperfect, represents an irreplaceable foundation for global governance that should be reformed and strengthened rather than abandoned or circumvented. The essay will examine three domains — climate, health, and trade — in which international agreements have produced measurable outcomes and will demonstrate that the failures of global governance typically reflect a deficit of political will rather than an inherent inadequacy of the multilateral framework. The conclusion will assess what institutional reforms would need to occur for international agreements to function more effectively in an era of intensified geopolitical competition.','hard'),
  (cid,48,174,'production','[TOEFL Speaking — 60s] Make predictions about medical technology in the next 50 years. Use will, will have, will be + -ing, is set to, might, may.','',NULL,'Medical technology will transform healthcare almost beyond recognition over the next half century. Genomic sequencing, which currently takes days and costs hundreds of dollars, will have become a routine diagnostic tool within a decade — fast, cheap, and available in most clinical settings. By mid-century, AI systems will be diagnosing many conditions more accurately than human physicians in radiology, pathology, and dermatology, though the role of human clinical judgment will remain essential in complex or ambiguous cases. Regenerative medicine is set to produce functional replacement organs grown from patients'' own cells, eliminating the transplant waiting lists that currently contribute to thousands of preventable deaths annually. Personalized pharmaceuticals — drugs designed around an individual''s specific genetic profile — may have replaced most current one-size-fits-all prescribing by 2070. Some researchers believe that interventions targeting the aging process itself will be extending healthy human lifespan significantly beyond current limits by the second half of this century, though this remains among the more speculative projections. The greatest challenge may not be technological but equitable: ensuring that these advances are accessible to all people and not only to those with the means to pay for them.','hard'),
  (cid,48,175,'gap_fill','By the time this generation of students _____ (graduate), the job market _____ (transform/passive) by artificial intelligence in ways that _____ (not yet/fully/predict/passive).','graduates / will have been transformed / have not yet been fully predicted',NULL,'By the time + PS + future perfect passive + passive negative.','hard'),
  (cid,48,176,'gap_fill','The treaty _____ (enter into force) once all signatory nations _____ (ratify) it through their domestic legislatures.','will enter into force / have ratified',NULL,'"Once + present perfect = completed condition" + "will + base verb" for result.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
