-- ============================================================
-- SEED EXT 2: Módulo 2 — Present Simple (exercícios 71-200)
-- Novos tópicos: stative verbs, zero conditional, academic
-- present, wh-questions, spelling, time expressions, TOEFL
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'present-simple';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo present-simple não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 11: stative verbs (state vs action)
  (cid,11,71,'multiple_choice','Which verb is a stative verb (NOT normally used in continuous)?','believe','["run","believe","eat","drive"]','Stative verbs describe states, not actions: know, believe, want, love, understand.','medium'),
  (cid,11,72,'gap_fill','I ___ what you mean. (understand)','understand',NULL,'Stative verb: do NOT use "am understanding."','easy'),
  (cid,11,73,'multiple_choice','Which sentence is INCORRECT?','She is knowing the answer.','["She knows the answer.","She is knowing the answer.","She has always known the answer.","Did she know the answer?"]','Know is stative — never use with -ing in present.','easy'),
  (cid,11,74,'gap_fill','This soup ___ delicious. (taste)','tastes',NULL,'Stative sense of taste: He/It + tastes. NOT is tasting.','medium'),
  (cid,11,75,'gap_fill','He ___ three languages fluently. (speak — ability)','speaks',NULL,'Ability = stative; uses present simple not continuous.','medium'),
  (cid,11,76,'multiple_choice','Choose the CORRECT sentence:','I prefer coffee to tea.','["I am preferring coffee to tea.","I prefer coffee to tea.","I am prefer coffee to tea.","I prefering coffee to tea."]','Prefer is stative — use present simple.','easy'),
  (cid,11,77,'gap_fill','She ___ that the hypothesis is correct. (believe)','believes',NULL,'Believe = stative. 3rd person: believes.','easy'),
  (cid,11,78,'multiple_choice','Which sentence uses "have" as a STATIVE verb?','She has two degrees from MIT.','["She is having lunch right now.","She has two degrees from MIT.","She is having a great time.","She is having a baby soon."]','Have = stative when expressing possession.','hard'),
  (cid,11,79,'gap_fill','This material ___ rough. (feel — texture)','feels',NULL,'Sensory stative: feels (not is feeling) for texture description.','medium'),
  (cid,11,80,'gap_fill','The professor ___ a lot about neuroscience. (know)','knows',NULL,'Know = stative; 3rd person singular = knows.','easy'),
  (cid,11,81,'multiple_choice','Which verb can be BOTH stative and dynamic?','taste','["go","run","write","taste"]','Taste: stative = "It tastes good"; dynamic = "She is tasting the soup."','hard'),
  (cid,11,82,'gap_fill','I ___ we need more data before drawing conclusions. (think — opinion)','think',NULL,'Think = stative when expressing opinion.','medium'),
  (cid,11,83,'multiple_choice','Choose the sentence where "see" is used as a STATIVE verb:','I see what you mean.','["She is seeing the doctor tomorrow.","I see what you mean.","They are seeing a film tonight.","We are seeing great results."]','See = stative for understanding ("I see" = I understand).','hard'),

  -- BLOCK 12: present simple for future (timetables, schedules)
  (cid,12,84,'gap_fill','The conference ___ at 9:00 AM tomorrow. (start)','starts',NULL,'Fixed schedule → present simple for future.','easy'),
  (cid,12,85,'multiple_choice','Which sentence uses present simple correctly for a scheduled future?','The train leaves at 6:45.','["The train will leave at 6:45.","The train is leaving at 6:45.","The train leaves at 6:45.","The train left at 6:45."]','Timetable: present simple.','easy'),
  (cid,12,86,'gap_fill','Our flight ___ at midnight and ___ in New York at 7 AM. (depart/arrive)','departs / arrives',NULL,'Both verbs = 3rd person singular in a schedule.','medium'),
  (cid,12,87,'multiple_choice','Which use of present simple for future is NOT appropriate?','I start a completely new career tomorrow.','["The exam starts at 10am.","The train departs at 7pm.","The film ends at 11pm.","I start a completely new career tomorrow."]','Spontaneous personal plans are expressed with "going to" or "will," not present simple.','hard'),
  (cid,12,88,'gap_fill','The university semester ___ on the 15th of February. (begin)','begins',NULL,'Official institutional schedules → present simple.','easy'),
  (cid,12,89,'gap_fill','What time ___ the library ___ on Saturdays? (close)','does / close',NULL,'Question with does + base verb for schedule.','medium'),
  (cid,12,90,'multiple_choice','A student says: "Class ends at 3pm — I pick you up right after." What does "I pick you up" express?','A plan tied to a fixed schedule event.','["A habitual action","A scientific fact","A plan tied to a fixed schedule event.","A command"]','Chained to a fixed event = present simple for immediate future.','hard'),

  -- BLOCK 13: zero conditional (if/when + present simple → present simple)
  (cid,13,91,'gap_fill','If you ___ water to 100°C, it ___. (heat / boil)','heat / boils',NULL,'Zero conditional: if + present simple, present simple (both clauses).','easy'),
  (cid,13,92,'multiple_choice','Which is a zero conditional?','If metal gets hot, it expands.','["If it rains, I will bring an umbrella.","If I were you, I would study more.","If metal gets hot, it expands.","If she had studied, she would have passed."]','Zero conditional: general truth, both verbs = present simple.','easy'),
  (cid,13,93,'gap_fill','When the temperature ___ below 0°C, water ___ into ice. (drop/turn)','drops / turns',NULL,'When = zero conditional trigger; both verbs = present simple.','easy'),
  (cid,13,94,'gap_fill','If plants ___ enough sunlight, they ___ to grow properly. (not/receive / fail)','don''t receive / fail',NULL,'Negative in zero conditional: don''t + base verb.','medium'),
  (cid,13,95,'multiple_choice','Choose the correct zero conditional:','If you mix red and blue, you get purple.','["If you mixed red and blue, you get purple.","If you mix red and blue, you get purple.","If you mix red and blue, you will get purple.","If you mix red and blue, you got purple."]','Both clauses = present simple for a scientific fact.','easy'),
  (cid,13,96,'gap_fill','[Academic] If a cell ___ to divide uncontrollably, it ___ a tumor. (begin/form)','begins / forms',NULL,'Zero conditional for biological process.','medium'),
  (cid,13,97,'multiple_choice','What is the difference between zero and first conditional?','Zero conditional = always true fact; first = specific likely future event.','["Zero conditional has two future clauses; first has one present clause.","Zero conditional = always true fact; first = specific likely future event.","Zero and first conditionals are identical.","First conditional uses past tense."]','Zero = universal truth; first = probable specific outcome.','hard'),

  -- BLOCK 14: academic present simple (authorial stance)
  (cid,14,98,'gap_fill','[Academic] The author ___ that cultural identity is shaped by language. (argue)','argues',NULL,'Academic present: author + 3rd person verb to introduce a claim.','easy'),
  (cid,14,99,'multiple_choice','In academic writing, why is present simple used when discussing a published work?','Because the work and its claims are considered still valid/present.','["Because the work happened in the past","Because the work and its claims are considered still valid/present.","Because it sounds more formal","Because the author is still alive"]','The eternal present: published ideas are referenced in present tense.','medium'),
  (cid,14,100,'gap_fill','Smith (2020) ___ that social media ___ academic performance. (claim/affect)','claims / affects',NULL,'Academic present: author + claims; subject + affects (3rd person).','medium'),
  (cid,14,101,'gap_fill','The study ___ a strong correlation between exercise and cognitive function. (demonstrate)','demonstrates',NULL,'Academic present: study/research + 3rd person verb.','medium'),
  (cid,14,102,'multiple_choice','Which academic sentence correctly uses present simple?','The data suggest that early intervention significantly reduces dropout rates.','["The data suggested that early intervention significantly reduces dropout rates.","The data suggest that early intervention significantly reduces dropout rates.","The data are suggesting that early intervention significantly reduced dropout rates.","The data suggested that early intervention significantly reduced dropout rates."]','Both verbs = present simple for academic results discussion.','medium'),
  (cid,14,103,'gap_fill','The findings ___ that bilingualism ___ cognitive flexibility. (indicate/enhance)','indicate / enhances',NULL,'Indicate = plural verb (findings); enhances = 3rd singular.','hard'),
  (cid,14,104,'multiple_choice','Which verb is WRONG in an academic results summary?','The results suggested (single experiment, general truth)','["The results show","The results indicate","The data reveal","The results suggested (single experiment, general truth)"]','For general truths from research: use present simple, not past.','hard'),
  (cid,14,105,'gap_fill','According to Chen et al. (2021), the relationship between poverty and education ___ complex and multidimensional. (remain)','remains',NULL,'3rd person singular for academic claim.','medium'),

  -- BLOCK 15: spelling rules for 3rd person singular
  (cid,15,106,'gap_fill','She ___ hard for every exam. (try)','tries',NULL,'Consonant + y → ies: try → tries.','easy'),
  (cid,15,107,'gap_fill','He ___ a lot of time on social media. (spend — check spelling)','spends',NULL,'Regular: spend + s = spends.','easy'),
  (cid,15,108,'multiple_choice','Which is the correct 3rd person form of "carry"?','carries','["carrys","carries","carres","carryes"]','Consonant + y → ies: carry → carries.','easy'),
  (cid,15,109,'gap_fill','The manager ___ all incoming emails. (fix)','fixes',NULL,'fix + es = fixes (verb ending in x).','easy'),
  (cid,15,110,'multiple_choice','Which 3rd person form is INCORRECT?','he dos','["he watches","he goes","he catches","he dos"]','do → does (irregular), NOT dos.','easy'),
  (cid,15,111,'gap_fill','She ___ to work by bicycle every day. (go)','goes',NULL,'go → goes (irregular 3rd person singular).','easy'),
  (cid,15,112,'gap_fill','He ___ the dishes after dinner. (wash)','washes',NULL,'wash + es = washes (verb ending in sh).','easy'),
  (cid,15,113,'multiple_choice','Choose the correctly spelled sentence:','She teaches mathematics at the university.','["She teachs mathematics at the university.","She teache mathematics at the university.","She teaches mathematics at the university.","She teachies mathematics at the university."]','teach + es = teaches.','easy'),
  (cid,15,114,'gap_fill','He ___ to music while studying. (listen)','listens',NULL,'Regular verb: listen + s = listens.','easy'),
  (cid,15,115,'gap_fill','The company ___ to expand into new markets. (plan)','plans',NULL,'plan + s = plans (no doubling for 3rd person -s, only for -ed).','medium'),

  -- BLOCK 16: wh-questions in present simple
  (cid,16,116,'gap_fill','___ does she work? (where)','Where',NULL,'Wh- + does + subject + base verb.','easy'),
  (cid,16,117,'gap_fill','___ do you study English? (why)','Why',NULL,'Why + do + subject + base verb.','easy'),
  (cid,16,118,'multiple_choice','Which question is grammatically correct?','How often does he go to the gym?','["How often do he go to the gym?","How often he goes to the gym?","How often does he go to the gym?","How often does he goes to the gym?"]','How often + does + subject + base verb.','medium'),
  (cid,16,119,'gap_fill','___ time does the class start? (what)','What',NULL,'What + time + does + subject + base verb.','easy'),
  (cid,16,120,'multiple_choice','Choose the correct wh-question for: "She studies at Harvard."','Where does she study?','["Where she studies?","Where does she study?","Where does she studies?","Where do she study?"]','Where + does + subject + base verb.','medium'),
  (cid,16,121,'gap_fill','___ languages ___ she speak? (how many)','How many / does',NULL,'How many + noun + does + subject + base verb.','medium'),
  (cid,16,122,'gap_fill','___ often ___ they meet to discuss research? (how / do)','How / do',NULL,'How often + do + subject + base verb.','easy'),
  (cid,16,123,'multiple_choice','What is the correct question for: "It costs $50."?','How much does it cost?','["How much it costs?","How much does it cost?","How much does it costs?","What does it cost how much?"]','How much + does + subject + base verb.','medium'),
  (cid,16,124,'gap_fill','[Academic] ___ does the study ___ to achieve? (what/aim)','What / aim',NULL,'Wh-question with auxiliary do: What + does + subject + aim.','medium'),
  (cid,16,125,'gap_fill','___ does the professor recommend for further reading? (what)','What',NULL,'What + does + subject + base verb.','easy'),

  -- BLOCK 17: time expressions with present simple
  (cid,17,126,'multiple_choice','Which time expression is MOST associated with present simple?','every day','["yesterday","last year","tomorrow at 3pm","every day"]','Every day = routine/habit = present simple.','easy'),
  (cid,17,127,'gap_fill','He ___ the gym ___ a week. (go / twice)','goes / twice',NULL,'Twice a week = frequency expression for present simple routine.','easy'),
  (cid,17,128,'multiple_choice','"On Mondays, she teaches advanced grammar." The underlined phrase is:','A frequency time expression indicating a routine.','["A past time expression","A frequency time expression indicating a routine.","A specific future plan","A general historical fact"]','On + day = routine frequency marker → present simple.','medium'),
  (cid,17,129,'gap_fill','The market ___ every Saturday morning. (open)','opens',NULL,'Every + time = routine → present simple.','easy'),
  (cid,17,130,'gap_fill','She ___ her parents ___ a month. (visit / once)','visits / once',NULL,'Once a month = frequency; 3rd person singular.','medium'),
  (cid,17,131,'multiple_choice','Which sentence pairs the WRONG time expression with present simple?','He finished the report last Monday.','["She visits her parents twice a year.","He usually reads before bed.","The library opens at 8am daily.","He finished the report last Monday."]','Last Monday = past time expression → past simple needed.','medium'),
  (cid,17,132,'gap_fill','[Academic] Research in this field ___ significant progress ___ the past decade. (make — trick question)','has made',NULL,'Over the past decade = present perfect, NOT present simple.','hard'),
  (cid,17,133,'multiple_choice','Which time expression CANNOT be used with present simple?','at 3pm yesterday','["every month","on Fridays","twice a week","at 3pm yesterday"]','Yesterday = specific past time → past simple.','medium'),

  -- BLOCK 18: TOEFL Reading advanced
  (cid,18,134,'multiple_choice','[TOEFL Reading] "The prefrontal cortex regulates decision-making and impulse control." The present simple is used here because:','It states a general scientific fact.','["The experiment happened recently","It states a general scientific fact.","The author is describing past research","The brain is currently performing this function"]','Scientific/anatomical facts use present simple.','medium'),
  (cid,18,135,'gap_fill','[TOEFL Reading] "The article ___ that urban environments ___ stress levels in most populations." (argue/increase)','argues / increase',NULL,'Academic present: argues (author claim) + increase (general truth).','medium'),
  (cid,18,136,'multiple_choice','[TOEFL Reading] "Economic inequality tends to widen when governments fail to invest in public education." This sentence demonstrates:','Present simple for a causal relationship treated as a general principle.','["Past simple for historical event","Future simple for predicted outcome","Present simple for a causal relationship treated as a general principle.","Present perfect for recent discovery"]','Tends + fail = present simple for principle.','hard'),
  (cid,18,137,'gap_fill','[TOEFL Reading] "The study ___ three variables and ___ two major findings." (examine/report)','examines / reports',NULL,'Academic present: both verbs 3rd person singular.','medium'),
  (cid,18,138,'multiple_choice','[TOEFL Reading] Which sentence correctly summarizes a reading passage in academic English?','The author contends that digital literacy is now a prerequisite for civic participation.','["The author contended that digital literacy was a prerequisite.","The author contends that digital literacy is now a prerequisite for civic participation.","The author is contending that digital literacy is a prerequisite.","The author has contended that digital literacy was a prerequisite."]','Academic present: contends + is.','medium'),
  (cid,18,139,'gap_fill','[TOEFL Reading] Passage quote: "Coral reefs ___ a disproportionate percentage of marine biodiversity." The present simple implies: ___','coral reefs always / continuously support marine biodiversity',NULL,'Scientific fact: the relationship is ongoing.','hard'),
  (cid,18,140,'multiple_choice','[TOEFL Reading] "The author challenges the notion that economic growth automatically translates into improved well-being." The present simple "challenges" suggests:','This is still the author''s current position in the published work.','["The author challenged this idea in the past","This is still the author''s current position in the published work.","The author will challenge this in future research","The author occasionally challenges this notion"]','Eternal present: published position remains current.','hard'),
  (cid,18,141,'gap_fill','[TOEFL Reading] "Photosynthesis ___ when chlorophyll ___ sunlight." (occur / absorb)','occurs / absorbs',NULL,'Biological process = zero conditional; both = present simple 3rd person.','medium'),
  (cid,18,142,'multiple_choice','[TOEFL Reading] In the sentence "Urbanization drives inequality across developing economies," the present simple indicates:','A general economic principle the author presents as fact.','["A specific event that happened once","A general economic principle the author presents as fact.","A future prediction","A past observation"]','Present simple for argued principle/general truth.','medium'),

  -- BLOCK 19: TOEFL Listening and Speaking
  (cid,19,143,'multiple_choice','[TOEFL Listening] A professor says: "So the blood-brain barrier prevents most pathogens from entering the brain." The present simple indicates:','A biological fact being stated.','["An experiment underway","A discovery made last week","A biological fact being stated.","A past procedure"]','Scientific fact → present simple.','easy'),
  (cid,19,144,'gap_fill','[TOEFL Listening] "The hypothesis ___ that motivation ___ from intrinsic rather than extrinsic sources." (propose/derive)','proposes / derives',NULL,'Present simple: proposes + derives (both 3rd person).','medium'),
  (cid,19,145,'multiple_choice','[TOEFL Listening] Which sentence from a lecture uses present simple INCORRECTLY?','Last century, scientists discover new chemical elements regularly.','["Water freezes at 0°C under standard atmospheric conditions.","The study reveals an unexpected pattern in migratory behavior.","Economic systems adapt to technological disruption over time.","Last century, scientists discover new chemical elements regularly."]','Last century = past time expression → past simple required.','medium'),
  (cid,19,146,'production','[TOEFL Speaking — 45s] Describe your daily academic routine using at least 5 present simple verbs. Include frequency adverbs (always, usually, sometimes, never) and one stative verb (know, believe, prefer, understand).','',NULL,'I always wake up at 7, I usually attend lectures, I sometimes study with friends, I never miss deadlines. I believe consistent effort leads to success.','medium'),
  (cid,19,147,'production','[TOEFL Speaking — 45s] Summarize the main argument of an academic article you have read. Use the academic present to report what the author argues, shows, or claims.','',NULL,'The author argues that... The study shows that... Chen et al. claim that... The findings indicate that...','hard'),
  (cid,19,148,'production','[TOEFL Speaking — 45s] Explain a scientific fact or process you have studied (e.g., photosynthesis, gravity, evolution). Use present simple throughout for scientific truths.','',NULL,'Plants absorb sunlight... Chlorophyll converts light energy... The process occurs in the chloroplasts...','medium'),
  (cid,19,149,'gap_fill','[TOEFL Listening] "When researchers ___ a new drug, they ___ it through three phases of clinical trials." (develop/pass)','develop / pass',NULL,'Zero conditional for standard scientific procedure.','medium'),
  (cid,19,150,'multiple_choice','[TOEFL Listening] "The professor explains that the experiment demonstrates how neurons fire in sequence." The verbs in this sentence are:','Present simple throughout (explains, demonstrates, fire).','["Past simple + present simple","Present simple throughout (explains, demonstrates, fire).","Present continuous + present simple","Present perfect + simple"]','All three verbs = present simple.','medium'),

  -- BLOCK 20: TOEFL Writing production
  (cid,20,151,'production','[TOEFL Writing] Write a 4-sentence paragraph summarizing an academic study. Use present simple for: the study''s claim, its method, its result, and your own argument about its significance. Avoid past tense.','',NULL,'The study examines... The authors argue... The data show... This suggests...','hard'),
  (cid,20,152,'production','[TOEFL Writing] Write 5 zero conditional sentences about scientific or environmental facts (e.g., temperature, ecosystems, chemistry). Each sentence must use a different subject.','',NULL,'If global temperatures rise, ice caps melt. If species lose their habitat, populations decline...','medium'),
  (cid,20,153,'production','[TOEFL Writing — Error Correction] Fix all errors: "The study argue that climate change effect sea levels. According to Smith, the sea level are rising every year. The research demonstrate a clear link."','',NULL,'argues, affects, levels is rising→is rising→have been rising (better), demonstrates','hard'),
  (cid,20,154,'production','[TOEFL Writing] Write a 150-word TOEFL-style paragraph arguing whether technology improves or hinders academic learning. Use present simple throughout for general truths, author claims, and your position.','',NULL,'Many researchers argue... Technology enables... Students access... The evidence suggests... I contend that...','hard'),
  (cid,20,155,'multiple_choice','[TOEFL Writing] Which set of verbs is MOST appropriate for academic writing when summarizing research in present simple?','argues, demonstrates, reveals, suggests, contends','["said, showed, discovered, found, proved","argues, demonstrates, reveals, suggests, contends","is arguing, is demonstrating, is revealing","argued, demonstrated, revealed, suggested, contended"]','Academic present tense verbs for summarizing research.','medium'),
  (cid,20,156,'production','[TOEFL Writing] Write a one-sentence thesis statement for EACH of these topics using academic present simple: (1) social media, (2) climate change, (3) bilingual education, (4) income inequality.','',NULL,'Social media increasingly shapes political discourse. Climate change poses an existential threat to biodiversity. Bilingual education enhances cognitive flexibility. Income inequality undermines social cohesion.','hard'),
  (cid,20,157,'gap_fill','[TOEFL Writing] "While critics ___ that online education lacks social depth, proponents ___ that its accessibility ___ the traditional equity gap." (argue/maintain/address)','argue / maintain / addresses',NULL,'All three present simple verbs in academic contrast structure.','hard'),
  (cid,20,158,'multiple_choice','[TOEFL Writing] Which sentence BEST opens a TOEFL essay using present simple?','It is widely acknowledged that access to quality education determines long-term economic outcomes.','["It was widely acknowledged that access to education determined outcomes.","It is widely acknowledged that access to quality education determines long-term economic outcomes.","Researchers are increasingly acknowledging that education determines outcomes.","It has been acknowledged that education is determining outcomes."]','Academic present: it is acknowledged + determines.','hard'),

  -- BLOCK 21: advanced error identification
  (cid,21,159,'multiple_choice','Which sentence contains an error?','Every student in both groups complete the survey.','["Every student completes the survey.","Researchers conduct experiments every semester.","Every student in both groups complete the survey.","The hypothesis suggests a link between diet and mood."]','Every + singular noun → 3rd person singular verb → completes (not complete).','hard'),
  (cid,21,160,'gap_fill','Neither the professor nor the students ___ the new schedule yet. (know)','know',NULL,'Neither A nor B + verb agrees with B (students = plural) → know.','hard'),
  (cid,21,161,'multiple_choice','Which sentence uses present simple INCORRECTLY for a general truth?','The satellite orbited the Earth every 90 minutes.','["Water boils at 100°C at sea level.","Light travels at approximately 300,000 km/s.","The satellite orbited the Earth every 90 minutes.","Plants absorb CO₂ during photosynthesis."]','Orbited = past simple; general truth needs orbits.','medium'),
  (cid,21,162,'gap_fill','Each of the participants ___ a different cultural background. (have)','has',NULL,'Each + singular: has (not have). "Each" always takes singular verb.','hard'),
  (cid,21,163,'multiple_choice','Choose the correct sentence with subject-verb agreement:','The committee meets every Tuesday to review proposals.','["The committee meet every Tuesday to review proposals.","The committees meets every Tuesday.","The committee meets every Tuesday to review proposals.","The committees meet every Tuesday to review proposal."]','Committee = collective noun → singular verb meets.','hard'),
  (cid,21,164,'gap_fill','One of the researchers ___ a unique approach to data collection. (use)','uses',NULL,'One of + plural noun → singular verb (uses).','hard'),
  (cid,21,165,'multiple_choice','Which sentence correctly handles a complex subject in present simple?','The data, along with the analysis, supports the hypothesis.','["The data, along with the analysis, support the hypothesis.","The data, along with the analysis, supports the hypothesis.","The data, along with the analysis, are supporting the hypothesis.","The data, along with the analysis, are supported the hypothesis."]','Data (main subject) + along with (parenthetical) → singular verb supports.','hard'),

  -- BLOCK 22: mixed advanced
  (cid,22,166,'gap_fill','[TOEFL] Neither the methodology nor the results ___ the authors'' original claims. (support)','support',NULL,'Neither A nor B + verb agrees with B (results = plural).','hard'),
  (cid,22,167,'multiple_choice','Choose the sentence that correctly uses present simple for a CONDITIONAL RELATIONSHIP in science:','When a population exceeds the carrying capacity of its environment, resources decline.','["When a population exceeded the carrying capacity, resources declined.","When a population exceeds the carrying capacity of its environment, resources decline.","When a population has exceeded the carrying capacity, resources will decline.","If a population exceeded the carrying capacity, resources would decline."]','Zero conditional: present + present for scientific principle.','hard'),
  (cid,22,168,'gap_fill','The more students ___, the better they ___. (practice / perform)','practice / perform',NULL,'The more + present simple, the more + present simple = proportional relationship.','hard'),
  (cid,22,169,'multiple_choice','[TOEFL Academic Reading] "Globalization facilitates the spread of both knowledge and inequality." The present simple "facilitates" is used because:','It expresses the author''s position as a general principle.','["The author observed this in the past","It expresses the author''s position as a general principle.","This is happening right now","It happened once in history"]','Academic present for general argument.','hard'),
  (cid,22,170,'production','[TOEFL — Synthesis Task] You read an article claiming technology increases educational inequality. Write 4 sentences: (1) a summary of what the article argues (present simple), (2) a counterpoint (present simple), (3) a zero conditional supporting your view, (4) your thesis statement (present simple).','',NULL,'The article argues that... However, research also shows that... If students lack access to technology, they fall behind... Therefore, equal access to digital tools matters more than the tools themselves.','hard'),

  -- BLOCK 23: production tasks
  (cid,23,171,'production','[TOEFL Speaking — 45s] Compare two academic subjects (e.g., science vs. humanities). Use present simple at least 6 times to describe differences, advantages, and what each field offers.','',NULL,'Science provides empirical evidence... Humanities explores human experience... Both fields require critical thinking... Science tends to focus on... Humanities often examines...','hard'),
  (cid,23,172,'production','[TOEFL Writing] Write a paragraph arguing that universities should require students to study a second language. Use present simple for: general truths, author citations, causal relationships, and your thesis.','',NULL,'Bilingualism enhances cognitive function (Chen, 2020)... Language learning demands cultural sensitivity... The evidence suggests that multilingual students perform better...','hard'),
  (cid,23,173,'production','[TOEFL Speaking — 45s] Describe what a typical TOEFL exam day involves. Use present simple for the schedule and what test-takers do. Include: frequency adverbs, time expressions, and at least one stative verb.','',NULL,'The exam typically starts at 9am... Candidates usually arrive 30 minutes early... Test-takers need a valid ID... The reading section contains 20 questions...','medium'),
  (cid,23,174,'production','[TOEFL Writing — Error Correction Task] A student wrote: "Smith argues that poverty effects education. He claim this is true since 1990. The data shows children whom are poor learns less." Correct ALL errors.','',NULL,'affects (not effects); claims (not claim); since 1990→has been true since; who are poor; learn less (they/children).','hard'),
  (cid,23,175,'production','[TOEFL Academic Writing] Write a 5-sentence paragraph beginning with "Research consistently demonstrates that..." Use present simple throughout and include at least three different academic reporting verbs (argue, suggest, reveal, indicate, confirm, challenge).','',NULL,'Research consistently demonstrates... Smith (2019) argues... However, Jones (2021) challenges... The evidence suggests... This indicates...','hard'),

  -- BLOCK 24: final consolidation
  (cid,24,176,'multiple_choice','Which sentence correctly uses ALL present simple rules?','The professor requires that each student submit a weekly reflection.','["The professor require that each student submits a weekly reflection.","The professor requires that each student submit a weekly reflection.","The professor requires that each students submit a weekly reflection.","The professor requires that each student submits a weekly reflection."]','Requires (3rd sing) + subjunctive: submit (base form, no -s after "that each student").','hard'),
  (cid,24,177,'gap_fill','[TOEFL] "It ___ (seem) that the traditional model of schooling no longer ___ (meet) the needs of a digital society."','seems / meets',NULL,'Both 3rd person present: seems + meets.','medium'),
  (cid,24,178,'multiple_choice','[TOEFL Writing] The best academic alternative to "Lots of studies say that exercise helps your brain" is:','A growing body of research indicates that physical activity enhances cognitive function.','["Many studies tell that exercise helps the brain.","A growing body of research indicates that physical activity enhances cognitive function.","Many studies says exercise helps brains.","Lots of research shows that exercise is helpful for your brain."]','Formal vocabulary + present simple + academic register.','hard'),
  (cid,24,179,'gap_fill','The more a student ___ (engage) with the material, the deeper their understanding ___ (become).','engages / becomes',NULL,'The more + 3rd singular, the + 3rd singular: comparative present simple.','hard'),
  (cid,24,180,'production','[TOEFL — Final Integration Task] Write a 6-sentence academic paragraph that uses present simple in at least four distinct functions: (1) general scientific truth, (2) academic author citation, (3) stative verb, (4) zero conditional, (5) schedule/timetable, (6) thesis statement.','',NULL,'Neurons transmit signals through synapses (scientific fact). Chen (2022) argues that sleep consolidates memory (citation). I believe consistent study habits matter most (stative). If students sleep less than 6 hours, performance declines (zero conditional). The TOEFL exam begins at 8:30am (schedule). Evidence therefore suggests that sleep is the most underrated academic tool (thesis).','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
