-- ============================================================
-- SEED EXT 2: Módulo 20 — Academic Connectors (exercícios 71-190)
-- Novos tópicos: registro formal/informal, conectivos +
-- cláusula, erros comuns, síntese, TOEFL avançado
-- ============================================================
DO $$
DECLARE cid TEXT;
BEGIN
  SELECT id INTO cid FROM contents WHERE id = 'academic-connectors';
  IF cid IS NULL THEN RAISE EXCEPTION 'Módulo academic-connectors não encontrado'; END IF;

  INSERT INTO exercises (content_id, block_number, exercise_number, type, question, answer, options, explanation, difficulty) VALUES

  -- BLOCK 11: formal vs informal connectors
  (cid,11,71,'multiple_choice','Which connector is appropriate in ACADEMIC writing but NOT in casual speech?','Furthermore','["Also","And","Plus","Furthermore"]','"Furthermore" is formal. "Also," "and," and "plus" are neutral or informal.','medium'),
  (cid,11,72,'multiple_choice','The informal "but" is best replaced in formal academic writing by:','However','["Yet","But","However","Except"]','"However" at the start of a sentence is the formal academic equivalent of "but."','easy'),
  (cid,11,73,'gap_fill','Informal: "So, the policy didn''t work." → Academic: "___, the policy proved ineffective."','Consequently / Therefore / As a result',NULL,'Formal cause-effect connector replaces "so."','medium'),
  (cid,11,74,'multiple_choice','Which is the most formal alternative to "also"?','In addition','["Plus","Too","In addition","As well"]','"In addition" is the most formal of these options.','easy'),
  (cid,11,75,'gap_fill','Informal: "The study was good, but it had problems." → Academic: "The study was rigorous; ___, it had significant limitations."','however',NULL,'"However" introduces a formal contrast after a semicolon.','medium'),
  (cid,11,76,'multiple_choice','Which phrase is NOT appropriate in formal academic writing?','On top of that','["Moreover","Furthermore","In addition","On top of that"]','"On top of that" is informal/colloquial.','medium'),
  (cid,11,77,'gap_fill','Informal: "Because of this, the results changed." → Academic: "___ this unexpected outcome, the research team revised their model."','In light of / Given',NULL,'"In light of" or "Given" = formal causal framing connector.','hard'),
  (cid,11,78,'multiple_choice','The most formal academic alternative to "even though" is:','Although','["Even so","Although","But still","Even though (both formal)"]','"Although" is the most neutral formal concessive connector; "even though" is also acceptable.','medium'),
  (cid,11,79,'gap_fill','In academic writing, "you know" and "I mean" are replaced by "___ other words" or "___ is to say."','in / that',NULL,'"In other words" and "that is to say" = formal reformulation connectors.','medium'),
  (cid,11,80,'multiple_choice','Which set is ALL formal academic connectors?','Consequently, nonetheless, notwithstanding, henceforth','["And, but, so, yet","Consequently, nonetheless, notwithstanding, henceforth","Also, but, because, plus","However, and, yet, too"]','All four are formal register connectors found in academic texts.','hard'),

  -- BLOCK 12: connector + clause construction (punctuation and structure)
  (cid,12,81,'multiple_choice','Which sentence has CORRECT punctuation with "however"?','The study had a large sample; however, the response rate was low.','["The study had a large sample however, the response rate was low.","The study had a large sample; however, the response rate was low.","The study had a large sample, however the response rate was low.","The study had a large sample; however the response rate was low."]','Semicolon before "however" + comma after = correct.','medium'),
  (cid,12,82,'gap_fill','The experiment was costly. _____, the results justified the investment.','Nevertheless / Nonetheless',NULL,'Sentence connector: capital letter, comma after.','medium'),
  (cid,12,83,'multiple_choice','How is "although" correctly positioned?','Although the results were significant, they require further verification.','["The results were significant, although they require further verification — both OK.","Although the results were significant, they require further verification.","Results were significant; although, they require further verification.","Although, the results were significant they require further verification."]','Although at the start: followed by a clause + comma + main clause. Also OK mid-sentence.','medium'),
  (cid,12,84,'gap_fill','The data were incomplete. ___, the team proceeded with the analysis.','Nevertheless',NULL,'Sentence connector after a period: capital + comma.','easy'),
  (cid,12,85,'multiple_choice','Which sentence correctly uses "because of"?','The project was delayed because of insufficient funding.','["The project was delayed because of there was insufficient funding.","The project was delayed because of insufficient funding.","Because of, the project was delayed with insufficient funding.","The project, because of insufficient funding, was it delayed."]','"Because of" + noun phrase (not + clause). "Because" + clause.','medium'),
  (cid,12,86,'gap_fill','___ the complexity of the data, the analysis took longer than expected.','Due to / Because of / Owing to',NULL,'Preposition connector + noun phrase for cause.','medium'),
  (cid,12,87,'multiple_choice','Choose the correct use of "despite":','Despite the challenges, the research team met the deadline.','["Despite the challenges were significant, the team met the deadline.","Despite of the challenges, the team met the deadline.","Despite the challenges, the research team met the deadline.","Despite that the challenges were significant, the team met the deadline."]','"Despite" + noun phrase (NOT "despite of" or "despite that").','hard'),
  (cid,12,88,'gap_fill','___ having a smaller budget, the team produced higher-quality results than expected.','Despite / In spite of',NULL,'"Despite/In spite of" + gerund (having).','hard'),
  (cid,12,89,'multiple_choice','Which connector can begin a sentence AND appear mid-sentence with the same meaning?','Although','["Therefore","Although","As a result","Consequently"]','"Although" can begin ("Although X, Y") or appear mid-sentence ("Y, although X").','hard'),
  (cid,12,90,'gap_fill','The new policy aims to reduce emissions; ___, it may increase energy costs for consumers.','however',NULL,'Semicolon + however + comma = formal mid-sentence contrast.','medium'),

  -- BLOCK 13: concession vs contrast
  (cid,13,91,'multiple_choice','What is the difference between "however" (contrast) and "nevertheless" (concession)?','Nevertheless shows the second point is true DESPITE the first; however simply contrasts.','["They are identical in meaning and usage.","Nevertheless shows the second point is true DESPITE the first; however simply contrasts.","However is stronger than nevertheless.","Nevertheless is informal; however is formal."]','"Nevertheless" implies "even so, in spite of what was said." "However" introduces a different angle.','hard'),
  (cid,13,92,'gap_fill','The methodology had clear weaknesses. ___, the findings are statistically significant.','Nonetheless / Nevertheless',NULL,'Concessive connector: despite the weakness, the findings are still valid.','medium'),
  (cid,13,93,'multiple_choice','Choose the best connector: "The data collection was flawed. _____, the overall trend is consistent with previous studies."','That said','["Therefore","Furthermore","That said","In addition"]','"That said" = a concessive pivot: acknowledging the problem before supporting the conclusion.','hard'),
  (cid,13,94,'gap_fill','___ it was the most expensive option, it proved to be the most cost-effective in the long term.','Although / Even though',NULL,'Concessive conjunction: acknowledging the cost while affirming the value.','medium'),
  (cid,13,95,'multiple_choice','Which sentence correctly uses "in spite of"?','In spite of the controversy, the study was widely cited.','["In spite of the study was controversial, it was widely cited.","In spite of the controversy, the study was widely cited.","In spite the controversy, the study was widely cited.","In spite of controversial, the study was widely cited."]','"In spite of" + noun phrase (not clause).','medium'),
  (cid,13,96,'gap_fill','The patient recovered quickly. This was surprising _____ the severity of the diagnosis.','given / considering',NULL,'"Given / Considering" = concessive preposition connector.','hard'),
  (cid,13,97,'multiple_choice','Choose the connector that introduces a CONCESSION followed by a STRONG CONCLUSION:','Admittedly, the sample size was small; however, the effect sizes were substantial.','["The sample size was small; therefore, the effect sizes were substantial.","Admittedly, the sample size was small; however, the effect sizes were substantial.","The sample size was small; moreover, the effect sizes were substantial.","The sample size was small; consequently, the effect sizes were substantial."]','Admittedly (concession) + however (pivot to conclusion).','hard'),
  (cid,13,98,'gap_fill','_____, one must acknowledge that no single study can establish definitive causality.','That said / Admittedly',NULL,'Concessive connector at start of sentence acknowledging a limitation.','hard'),

  -- BLOCK 14: purpose and result connectors
  (cid,14,99,'gap_fill','The researchers used a control group ___ ___ (so that) eliminate confounding variables.','so as to / in order to',NULL,'"So as to" or "in order to" = formal purpose connector + infinitive.','medium'),
  (cid,14,100,'multiple_choice','Which purpose connector is followed by a gerund (-ing)?','with a view to','["so that","in order to","so as to","with a view to"]','"With a view to" + gerund: "with a view to improving outcomes."','hard'),
  (cid,14,101,'gap_fill','___ avoid bias, the evaluators were kept blind to the treatment conditions.','In order to / So as to',NULL,'Formal purpose connector + infinitive at start of sentence.','medium'),
  (cid,14,102,'multiple_choice','Choose the correct purpose structure: "The study was replicated ___ verify the original results."','in order to','["so that","in order to","despite","consequently"]','"In order to" + infinitive for purpose.','easy'),
  (cid,14,103,'gap_fill','The team recruited 500 participants ___ ___ ensure statistical power.','so as to / in order to',NULL,'Formal purpose connectors before infinitive.','medium'),
  (cid,14,104,'multiple_choice','Which sentence uses "so that" correctly?','Data were collected at multiple time points so that changes could be tracked longitudinally.','["Data were collected so that to track changes.","Data were collected in order to so that changes could be tracked.","Data were collected at multiple time points so that changes could be tracked longitudinally.","Data were collected so as that changes could be tracked."]','"So that" + clause with modal (could/would/can).','hard'),
  (cid,14,105,'gap_fill','Surveys were anonymized ___ ___ encourage honest responses.','so as to / in order to',NULL,'Purpose infinitive clause.','easy'),

  -- BLOCK 15: connector error correction
  (cid,15,106,'multiple_choice','Find the error: "The results were positive. Despite, the sample was small."','Despite should be followed by a noun phrase or "this"','["results should be result","positive should be positively","Despite should be followed by a noun phrase or ''this''","small should be smaller"]','"Despite" + noun phrase or gerund. Correct: "Despite this" or "Despite the small sample."','hard'),
  (cid,15,107,'gap_fill','Error: "The experiment failed. Therefore the team celebrated." → Correct: "The experiment failed. Therefore___ the team celebrated."','Therefore, (comma needed after "Therefore")',NULL,'Sentence connectors (therefore, however, etc.) require a comma after them.','medium'),
  (cid,15,108,'multiple_choice','Which sentence has an error?','He failed the exam; moreover, he didn''t study.','["He failed the exam; however, he didn''t give up.","He passed the exam; consequently, he celebrated.","He failed the exam; moreover, he didn''t study.","She studied hard; therefore, she succeeded."]','"Moreover" adds a further point. Here it contradicts logic: not studying should be the cause, not an addition. Use "besides" or restructure.','hard'),
  (cid,15,109,'gap_fill','Error correction: "Although the results were promising, but the team needed more data." Remove the error: "___ the results were promising, the team needed more data."','Although',NULL,'"Although" already expresses contrast — do NOT add "but." Choose one or the other.','hard'),
  (cid,15,110,'multiple_choice','Which sentence is CORRECT?','Despite the limitations, the findings are valuable.','["Despite of the limitations, the findings are valuable.","In despite of the limitations, the findings are valuable.","Despite the limitations, the findings are valuable.","Despite to the limitations, the findings are valuable."]','"Despite" + noun phrase (no "of," "in," or "to").','medium'),
  (cid,15,111,'gap_fill','Error: "The hypothesis was correct. Therefore, proved our theory." → Correct: "The hypothesis was correct. Therefore, it ___ our theory."','proved',NULL,'Missing subject after "Therefore, it proved…"','hard'),
  (cid,15,112,'multiple_choice','Which pair of connectors creates a LOGICAL ERROR?','The experiment was a success; however, the team celebrated.','["The experiment failed; however, the team persisted.","The data were incomplete; nevertheless, conclusions were drawn cautiously.","The experiment was a success; however, the team celebrated.","The results were surprising; therefore, further investigation was warranted."]','"However" signals contrast but "success → celebration" is NOT a contrast — use "therefore" or "consequently."','hard'),

  -- BLOCK 16: TOEFL Reading — connector identification
  (cid,16,113,'multiple_choice','[TOEFL Reading] "Urbanization has accelerated economic development; however, it has also intensified social inequality." The connector "however" indicates:','A contrast between two outcomes of urbanization.','["An addition to the previous point","A contrast between two outcomes of urbanization.","A cause-effect relationship","A concession followed by a conclusion"]','However = contrast between positive and negative effects.','easy'),
  (cid,16,114,'gap_fill','[TOEFL Reading] "The study found no significant correlation. ___, the trend was consistent across all demographic groups." The best connector: ___','Nevertheless / Nonetheless / That said',NULL,'Concessive connector: despite finding no correlation, the trend was consistent.','hard'),
  (cid,16,115,'multiple_choice','[TOEFL Reading] "Species diversity decreases as temperature increases; consequently, tropical deforestation poses a greater biodiversity threat than deforestation in temperate zones." "Consequently" signals:','A logical cause-effect conclusion drawn from the previous fact.','["An addition of a new idea","A contrast with a previous point","A logical cause-effect conclusion drawn from the previous fact.","A concession acknowledging a limitation"]','Consequently = therefore, the previous fact causes this conclusion.','medium'),
  (cid,16,116,'gap_fill','[TOEFL Reading] A paragraph begins: "The Roman Empire''s decline has been attributed to multiple factors." The next sentence begins with "___ historians emphasize military overextension." Best connector: ___','Some / While some',NULL,'While/Whereas introduces contrasting interpretations.','hard'),
  (cid,16,117,'multiple_choice','[TOEFL Reading] "Although access to healthcare has improved globally, significant disparities remain between wealthy and low-income nations." Which function does "although" serve?','It introduces a concession before a contrasting main point.','["It adds a further supporting point","It introduces a concession before a contrasting main point.","It signals a cause-effect relationship","It introduces an example"]','Although = concessive — the first clause is true but does not prevent the second.','medium'),
  (cid,16,118,'gap_fill','[TOEFL Reading] "New fossil evidence has been discovered. ___, scientists must revise the current evolutionary timeline." Best connector: ___','Consequently / As a result / Therefore',NULL,'New evidence → revision = cause and effect.','medium'),
  (cid,16,119,'multiple_choice','[TOEFL Reading] The passage uses "in contrast" to compare two groups. This suggests:','The two groups differ significantly on the dimension being discussed.','["The groups are similar","The second group is better","The two groups differ significantly on the dimension being discussed.","The first group is more important"]','"In contrast" = significant difference between two things.','easy'),
  (cid,16,120,'gap_fill','[TOEFL Reading] "Early astronomy relied on naked-eye observation. Modern telescopes, ___, can detect objects billions of light-years away." Best connector: ___','by contrast / in contrast / however',NULL,'Contrast between past and present capabilities.','medium'),
  (cid,16,121,'multiple_choice','[TOEFL Reading] "The traditional model assumed all species evolve at the same rate; _____, punctuated equilibrium theory suggests rapid, discontinuous change." Best connector:','conversely','["moreover","as a result","conversely","for instance"]','"Conversely" = the opposite point of view.','hard'),

  -- BLOCK 17: TOEFL Listening — connectors in spoken academic context
  (cid,17,122,'multiple_choice','[TOEFL Listening] A professor says: "Now, turning to the other side of the argument..." This phrase functions as:','A topic shift / contrast signal.','["A summary","A topic shift / contrast signal.","A cause-effect connector","An example introduction"]','"Turning to" = discourse marker signaling a new topic or contrasting view.','medium'),
  (cid,17,123,'gap_fill','[TOEFL Listening] "The study supports this claim. ___, there are some important caveats." The professor is introducing: ___','a contrast or qualification',NULL,'However/That said = contrast after a supporting statement.','medium'),
  (cid,17,124,'multiple_choice','[TOEFL Listening] "First,... Second,... Finally,..." These are:','Sequence/enumeration connectors.','["Contrast connectors","Cause-effect connectors","Sequence/enumeration connectors.","Purpose connectors"]','Enumeration: first, second, finally.','easy'),
  (cid,17,125,'gap_fill','[TOEFL Listening] A professor says: "That''s a valid point. ___, we should also consider the long-term consequences." Best connector: ___','However / That said / Nevertheless',NULL,'Concessive pivot: acknowledging a point before adding another dimension.','medium'),
  (cid,17,126,'multiple_choice','[TOEFL Listening] "The data suggest rising sea levels. As a result, coastal cities are at risk." A student paraphrases this as: "Sea levels are rising, so coastal cities are at risk." Is this paraphrase accurate?','Yes — "as a result" and "so" both signal cause-effect.','["No — as a result is stronger than so","Yes — ''as a result'' and ''so'' both signal cause-effect.","No — ''as a result'' signals contrast","No — ''so'' is more formal than ''as a result''"]','Cause-effect: as a result = so (informal).','medium'),
  (cid,17,127,'gap_fill','[TOEFL Listening] "Many students perform poorly not because of a lack of intelligence, but ___ inadequate time management." Best connector: ___','rather due to / because of',NULL,'"Not X but rather Y" = corrective contrast connector.','hard'),
  (cid,17,128,'multiple_choice','[TOEFL Listening] The professor contrasts two theories using "on the one hand... on the other hand." This structure:','Presents two sides of an argument before reaching a synthesis.','["Introduces a cause-effect relationship","Presents two sides of an argument before reaching a synthesis.","Adds further evidence to one theory","Introduces a sequence of events"]','"On the one hand / on the other hand" = bilateral contrast for balanced argument.','medium'),

  -- BLOCK 18: TOEFL Speaking production
  (cid,18,129,'production','[TOEFL Speaking — 45s] Use at least 5 different academic connectors to argue whether social media benefits or harms society. Include: a contrast, an addition, a cause-effect, a concession, and a conclusion connector.','',NULL,'However... Furthermore... As a result... That said... Therefore... In conclusion...','hard'),
  (cid,18,130,'production','[TOEFL Speaking — 45s] Compare two types of universities (large research universities vs. small liberal arts colleges) using these connectors: whereas, on the other hand, by contrast, moreover, nevertheless.','',NULL,'Whereas large universities offer extensive resources... On the other hand, liberal arts colleges... Moreover, smaller institutions... By contrast... Nevertheless...','hard'),
  (cid,18,131,'production','[TOEFL Speaking — 45s] You read that remote work increases productivity. Use connectors to present both the supporting and opposing views: although, however, in addition, consequently, therefore.','',NULL,'Although remote work increases flexibility... However, studies also show... In addition, social isolation... Consequently, productivity... Therefore, a hybrid model...','hard'),
  (cid,18,132,'production','[TOEFL Speaking — 45s] Describe a cause-effect chain about climate change using: as a result, consequently, therefore, and furthermore.','',NULL,'Greenhouse gases trap heat; as a result, global temperatures rise. Consequently, ice caps melt. Therefore, sea levels increase. Furthermore, extreme weather events become more frequent.','medium'),
  (cid,18,133,'production','[TOEFL Speaking — 45s] A professor argues that mandatory voting improves democracy. Do you agree? Use at least 4 connectors from different categories (addition, contrast, cause-effect, concession).','',NULL,'I agree that mandatory voting encourages participation. Furthermore, it reduces the influence of extreme views. However, some argue it violates personal freedom. That said, the benefits arguably outweigh the costs. Consequently, I support mandatory voting with abstention options.','hard'),

  -- BLOCK 19: TOEFL Writing production
  (cid,19,134,'production','[TOEFL Writing] Write a paragraph arguing that renewable energy should replace fossil fuels. Use exactly these connectors: furthermore, however, as a result, despite, therefore.','',NULL,'Renewable energy reduces emissions. Furthermore, it creates new jobs. However, transition costs are significant. Despite these challenges, several countries have successfully switched. As a result, carbon levels have declined in those regions. Therefore, global adoption is both necessary and feasible.','hard'),
  (cid,19,135,'production','[TOEFL Writing — Error Correction] Fix all connector errors: "The study was successful. Despite, it had limitations. Moreover the sample was small, but the results were significant. Although this, we recommend further research."','',NULL,'Despite this / In spite of its limitations; Moreover, the sample (add comma); Despite this / However (not "Although this").','hard'),
  (cid,19,136,'production','[TOEFL Writing] Write a 5-sentence paragraph contrasting traditional and online education. Use at least 4 connectors: whereas, on the other hand, in addition, as a result.','',NULL,'Traditional education fosters face-to-face interaction, whereas online education offers flexibility. On the other hand, online learners may struggle with self-discipline. In addition, employers are increasingly accepting online credentials. As a result, the distinction between the two modes is diminishing.','hard'),
  (cid,19,137,'production','[TOEFL Writing] Write a 5-sentence concession paragraph on artificial intelligence using: admittedly, however, that said, nevertheless, therefore.','',NULL,'Admittedly, AI raises significant ethical concerns. However, its potential to solve complex problems is undeniable. That said, implementation must be carefully regulated. Nevertheless, completely banning AI research would be counterproductive. Therefore, a balanced, internationally coordinated approach is essential.','hard'),
  (cid,19,138,'production','[TOEFL Writing — 150 words] Write a full paragraph arguing either for or against a four-day work week. Use at least 6 connectors from different categories. Underline each connector.','',NULL,'Furthermore, consequently, however, in spite of, in order to, that said, therefore, as a result — weave into logical argument.','hard'),

  -- BLOCK 20: advanced multi-connector synthesis
  (cid,20,139,'production','[TOEFL — Synthesis] Read these two positions: (A) Technology improves learning outcomes. (B) Technology distracts students. Write 5 sentences synthesizing both using: while, however, moreover, as a result, and in conclusion.','',NULL,'While technology can enhance access to information, it can also distract students. However, research suggests that structured digital learning improves outcomes. Moreover, interactive platforms increase student engagement. As a result, schools that regulate rather than ban technology report better performance. In conclusion, technology''s impact depends on how it is implemented.','hard'),
  (cid,20,140,'multiple_choice','[TOEFL Writing] Which paragraph uses connectors MOST effectively?','Despite its cost, nuclear energy produces minimal carbon emissions; consequently, several countries view it as an essential component of their climate strategy. Moreover, recent advances have improved safety significantly. However, concerns about waste disposal remain unresolved.','["Nuclear energy is cheap. Moreover it is clean. However there are problems.","Nuclear energy is good and has low emissions, but there are problems too, so some countries like it.","Despite its cost, nuclear energy produces minimal carbon emissions; consequently, several countries view it as an essential component of their climate strategy. Moreover, recent advances have improved safety significantly. However, concerns about waste disposal remain unresolved.","Nuclear energy: despite its cost, it is clean. Moreover, it is good. However problems."]','Correctly punctuated connectors creating a logical, coherent paragraph.','hard'),
  (cid,20,141,'production','[TOEFL Writing — Capstone] Write a full TOEFL-style body paragraph (100-120 words) on globalization. You must use at least 7 different academic connectors covering: addition, contrast, concession, cause-effect, and purpose. Underline each connector.','',NULL,'Globalization has accelerated economic development in many regions. Furthermore, it has facilitated the exchange of ideas and cultural practices. However, critics argue that it has also widened inequality between wealthy and developing nations. Despite these concerns, the benefits of global trade remain undeniable. Moreover, international cooperation has enabled nations to address shared challenges such as climate change more effectively. In order to maximize benefits while minimizing harm, governments must therefore implement policies that protect vulnerable communities. As a result, a more equitable and sustainable form of globalization may emerge.','hard'),

  -- BLOCK 21: connector classification and mastery
  (cid,21,142,'multiple_choice','Which connector signals EXEMPLIFICATION?','For instance','["Nevertheless","Consequently","For instance","Whereas"]','"For instance" = por exemplo. Used to introduce an example.','easy'),
  (cid,21,143,'gap_fill','___ ___ (for example), the Mediterranean diet has been linked to reduced rates of cardiovascular disease.','For example / For instance',NULL,'Exemplification connector at start of sentence + comma.','easy'),
  (cid,21,144,'multiple_choice','"Such as" differs from "for example" because:','Such as introduces a list within a sentence; for example introduces a full illustrative clause.','["Such as is more formal","They are identical","Such as introduces a list within a sentence; for example introduces a full illustrative clause.","For example is more formal"]','"For example" + full sentence; "such as" + noun phrase list.','hard'),
  (cid,21,145,'gap_fill','Several factors contributed to the decline, ___ ___ (for example) lack of funding, poor management, and outdated infrastructure.','such as / for example',NULL,'"Such as" preferred before a list; "for example" before a full clause.','medium'),
  (cid,21,146,'multiple_choice','Which connector introduces a REFORMULATION or CLARIFICATION?','In other words','["As a result","In other words","Nevertheless","Furthermore"]','"In other words" = that is to say = a restatement or clarification.','easy'),
  (cid,21,147,'gap_fill','The policy was ineffective. ___ ___ words, it failed to achieve any of its stated goals.','In other',NULL,'"In other words" = reformulation of the previous statement.','easy'),
  (cid,21,148,'multiple_choice','Which connector signals that you are about to SUMMARIZE?','In summary','["Moreover","In contrast","In summary","Nevertheless"]','"In summary / In conclusion / To summarize" signals a summary.','easy'),
  (cid,21,149,'gap_fill','___ conclusion, the evidence strongly supports the view that early intervention produces the best long-term outcomes.','In',NULL,'"In conclusion" = final summary connector in academic writing.','easy'),
  (cid,21,150,'multiple_choice','Which is the correct academic connector for CHRONOLOGICAL ORDER?','Subsequently','["Moreover","Subsequently","By contrast","As a result"]','"Subsequently" = after that, in time sequence.','medium'),

  -- BLOCK 22: advanced integration
  (cid,22,151,'gap_fill','[TOEFL] "The treatment reduced symptoms; ___, patient quality of life improved significantly." Best connector: ___','as a result / consequently / therefore',NULL,'Cause-effect: reduced symptoms → improved quality of life.','easy'),
  (cid,22,152,'multiple_choice','[TOEFL Writing] Which sentence uses "whereas" correctly?','Traditional economies prioritize growth, whereas sustainable economies balance growth with environmental protection.','["Traditional economies prioritize growth; whereas sustainable economies balance growth.","Whereas traditional economies prioritize growth whereas sustainable economies balance growth.","Traditional economies prioritize growth, whereas sustainable economies balance growth with environmental protection.","Traditional economies prioritize growth. Whereas sustainable economies balance it."]','"Whereas" in a single sentence connecting two contrasting clauses.','medium'),
  (cid,22,153,'gap_fill','[TOEFL Reading] "Colonization initially brought economic benefits to European powers. ___, indigenous populations suffered immeasurable losses." Best connector: ___','However / Nevertheless / Conversely',NULL,'Contrast: one group benefited while another suffered.','medium'),
  (cid,22,154,'multiple_choice','[TOEFL] A student writes: "The economy improved. Furthermore, unemployment rose." This is:','A logical error — "furthermore" adds a positive; rising unemployment contradicts improvement.','["Correct use of furthermore","A grammar error","A logical error — ''furthermore'' adds a positive; rising unemployment contradicts improvement.","A punctuation error"]','Furthermore adds supporting information — cannot logically link improvement + rising unemployment.','hard'),
  (cid,22,155,'gap_fill','[TOEFL Writing] "Research has shown that sleep deprivation impairs cognitive function. ___, students who sleep fewer than six hours per night consistently score lower on academic assessments."','Furthermore / Moreover / In addition',NULL,'Addition: adding further supporting evidence.','easy'),
  (cid,22,156,'multiple_choice','[TOEFL] A student uses "nevertheless" after two sentences that both support the same argument. Is this correct?','No — nevertheless signals contrast after an opposing point, not agreement.','["Yes — nevertheless can strengthen an argument","Yes — it means ''additionally''","No — nevertheless signals contrast after an opposing point, not agreement.","Yes — it is interchangeable with furthermore"]','"Nevertheless" = despite what was just said. Use only after a contrasting/negative point.','hard'),
  (cid,22,157,'production','[TOEFL Writing — Advanced Task] Write 4 sentences on the topic of urban poverty using all four connector categories in one paragraph: (1) addition (furthermore/moreover), (2) contrast (however/nevertheless), (3) cause-effect (consequently/as a result), (4) concession (that said/despite this).','',NULL,'Urban poverty is driven by systemic inequality. Furthermore, inadequate infrastructure limits opportunities for upward mobility. However, several cities have successfully reduced poverty through targeted investment. Consequently, evidence suggests that policy intervention can break the cycle. That said, sustained political will is essential for long-term success.','hard'),

  -- BLOCK 23: TOEFL paragraph cohesion
  (cid,23,158,'multiple_choice','[TOEFL Writing] Which opening sentence BEST uses an academic connector to signal the paragraph''s main function?','Although technological advances have transformed education, significant disparities in access remain.','["Technology has changed education.","Although technological advances have transformed education, significant disparities in access remain.","Furthermore, technology is changing education today.","Technology is important; however, education is too."]','Although (concession/contrast) at the start signals a nuanced, balanced argument.','hard'),
  (cid,23,159,'production','[TOEFL — Final Integration] Write a 7-sentence academic paragraph on the topic of artificial intelligence in the workplace. You must use one connector from EACH category: addition, contrast, concession, cause-effect, purpose, exemplification, summary. Underline each connector.','',NULL,'Artificial intelligence is increasingly integrated into workplaces. Moreover, it automates routine tasks, freeing humans for creative work. However, this raises concerns about mass unemployment. In spite of these fears, historical evidence suggests technology ultimately creates more jobs than it eliminates. As a result, workers must upskill to remain competitive. In order to facilitate this transition, governments should invest in retraining programs. For instance, Germany''s vocational retraining model has successfully reduced technological unemployment. In summary, AI poses challenges but also offers significant opportunities for economic growth.','hard'),
  (cid,23,160,'production','[TOEFL Writing] Rewrite this incoherent paragraph using appropriate connectors: "Online education is popular. Students can study at home. They miss face-to-face interaction. Some students fail online courses. Online education is valuable."','',NULL,'Online education has become increasingly popular. Furthermore, it allows students to study from home, offering flexibility unavailable in traditional settings. However, students often miss face-to-face interaction, which can affect motivation. Consequently, some students struggle and fail online courses. That said, online education remains valuable when supported by clear structure and regular feedback.','hard')

  ON CONFLICT (content_id, block_number, exercise_number) DO NOTHING;
END $$;
